### ISSUE TITLE
Invariant Violation: Native component for "RNCWKWebView does not exist"

### ISSUE THREAD

**Issue by pizza-r0b** [react-native-community/react-native-webview#100]
Not sure why I am getting the error `Invariant Violation: Native component for "RNCWKWebView does not exist"`.

**Comment by Titozzz** [comment]
I think you did not link the library properly

**Comment by pizza-r0b** [comment]
Got it - I am using expo and linking is not supported without detaching from expo.

**Comment by Titozzz** [comment]
oh yes sorry about that. Hopefully expo will pull that repository and their next release
