### ISSUE TITLE
Trigger and notice fullscreen embed video programmatically

### ISSUE THREAD

**Issue by minhnbwork97** [react-native-community/react-native-webview#1000]
**1**
I'm using react-native-webview to embed Vimeo video in my app.
I want to make my app like Youtube:
- App automatically rotates screen to landscape when user clicks fullscreen button.
- App automatically goes fullscreen when user rotates screen to landscape.

**2**
- I want to notice or catch an event (programmatically) when user clicks fullscreen button so that app will rotate screen to landscape.
- I want to trigger fullscreen button programmatically when user rotates screen to landscape.

**3**
I think this is neither a bug report nor a feature report. I really need help.
Is there any way I can do that?
Sorry for my poor English.
If you need more information please comment below.

**Comment by lashansam** [comment]
I'm looking for a solution to this problem as well.

**Comment by jdponomarev** [comment]
I've got some video from YouTube in my app and I made this work by using a workaround:
`
const injected = 
			["fullscreenchange", "webkitfullscreenchange", "mozfullscreenchange", "msfullscreenchange"].forEach(
				eventType => document.addEventListener(eventType, function(e){
					window.ReactNativeWebView.postMessage(e)
				}, false)
			);
			true;
`;

`
<WebView
				  injectedJavaScript={injected}
				  	onMessage={(data)=>{
						  if(this.orientation=="PORTRAIT"){
							setTimeout(function(){
								ScreenOrientation.lockAsync(ScreenOrientation.OrientationLock.LANDSCAPE)
							},200)
							this.orientation = "LANDSCAPE";
						  }else{
							this.orientation = "PORTRAIT";
						  }
					}}
				  	allowsFullscreenVideo={true}
					javaScriptEnabled={true}
					source={{
						uri,
					}}
				/>
`

So the idea is to inject some js code into youtube iframe, listen for the fullscreen event there and pass a message to RN as soon as it changes

**Comment by minhnbwork97** [comment]
> I've got some video from YouTube in my app and I made this work by using a workaround:
> `const injected = ["fullscreenchange", "webkitfullscreenchange", "mozfullscreenchange", "msfullscreenchange"].forEach( eventType => document.addEventListener(eventType, function(e){ window.ReactNativeWebView.postMessage(e) }, false) ); true;`;
> 
> `<WebView injectedJavaScript={injected} onMessage={(data)=>{ if(this.orientation=="PORTRAIT"){ setTimeout(function(){ ScreenOrientation.lockAsync(ScreenOrientation.OrientationLock.LANDSCAPE) },200) this.orientation = "LANDSCAPE"; }else{ this.orientation = "PORTRAIT"; } }} allowsFullscreenVideo={true} javaScriptEnabled={true} source={{ uri, }} />`
> 
> So the idea is to inject some js code into youtube iframe, listen for the fullscreen event there and pass a message to RN as soon as it changes

This is a really good workaround. I got mine successfully running on Android device, but on iOS there is no fullscreen button 😄. Anyway thank you very much.

**Comment by gabcvit** [comment]
@minhnbwork97 I found a Listener function that worked for me on iOS devices, maybe this could work for you too:

`window.addEventListener("orientationchange", function(e) { 
              window.ReactNativeWebView.postMessage(e) 
          });`

**Comment by luatvudinh** [comment]
Mid 2022, is there any idea for iOS everyone? Still not work on iOS.

**Comment by shinnthantminn** [comment]
> I've got some video from YouTube in my app and I made this work by using a workaround: `const injected = ["fullscreenchange", "webkitfullscreenchange", "mozfullscreenchange", "msfullscreenchange"].forEach( eventType => document.addEventListener(eventType, function(e){ window.ReactNativeWebView.postMessage(e) }, false) ); true;`;
> 
> `<WebView injectedJavaScript={injected} onMessage={(data)=>{ if(this.orientation=="PORTRAIT"){ setTimeout(function(){ ScreenOrientation.lockAsync(ScreenOrientation.OrientationLock.LANDSCAPE) },200) this.orientation = "LANDSCAPE"; }else{ this.orientation = "PORTRAIT"; } }} allowsFullscreenVideo={true} javaScriptEnabled={true} source={{ uri, }} />`
> 
> So the idea is to inject some js code into youtube iframe, listen for the fullscreen event there and pass a message to RN as soon as it changes

**That was not working in ios onMessage was no invoke when webview was change**
