### ISSUE TITLE
is there any method for navigation in webview ?

### ISSUE THREAD

**Issue by detroit007** [react-native-community/react-native-webview#1001]
I'm looking for a method to navigate in webview eg: clicking on a link take me on that page but when I press back button on my mobile it do not allow me to go on previous page but instead my app is closed and when I open it again it starts from the first page.
I want to navigate between these pages if pressing link take me to next page I want to go previous page by clicking back button.
help!

**Comment by rohmanhm** [comment]
I'm having this problem too. On Android click hardware back will close the app and swipe back doesn't do anything on iOS

**Comment by detroit007** [comment]
Still searching for solutions..

**Comment by safaiyeh** [comment]
This seems possible, just not implemented

https://developer.android.com/reference/android/webkit/WebView#goBack()
https://developer.apple.com/documentation/webkit/wkwebview/1414952-goback
