### ISSUE TITLE
Html Rich Text not wrapping on the edges

### ISSUE THREAD

**Issue by kapil-mardi** [react-native-community/react-native-webview#1007]
I am using this library to show Rich text from the server. There are currently 2 problems that I am facing. 
1) I have to provide a hard-coded Height parameter to the component. I can not provide this height as this web view resides inside a scroll view and how would anyone know in advance how much hight HTML text will need.
2) To overcome the first problem I have given hardcoded height, but now this web view is not wrapping the text on the right edge. It shows some characters from the word and then the next word is shown on the new line. 
![bug](https://user-images.githubusercontent.com/7642204/68540156-80040d80-03b3-11ea-8ab7-cee136440a96.png)

**Comment by student-t** [comment]
Do we have a solution?

**Comment by castalonirenz** [comment]
any solution here?
