### ISSUE TITLE
Rendering webview on android device overlaps previous siblings from same parent

### ISSUE THREAD

**Issue by fdobre** [react-native-community/react-native-webview#101]
Android React native 0.57
Version 2.4.0

```
import React, { Component } from 'react';
import { ScrollView, View, Text } from 'react-native';
import { WebView } from 'react-native-webview';

export default class MyWeb extends Component {
  render() {
    return (
      <ScrollView contentContainerStyle={{ backgroundColor: 'pink', flexDirection: 'column', alignItems: 'center', justifyContent: 'center' }}>
        <View style={{backgroundColor: 'yellow', margin: 5, height: 60, width: 300, alignItems: 'center', justifyContent: 'center' }}>
          <Text>TEXT COMPONENT 1</Text>
        </View>
        <View style={{backgroundColor: 'yellow', height: 60, width: 300, alignItems: 'center', justifyContent: 'center' }}>
          <Text>TEXT COMPONENT 2</Text>
        </View>
        <View style={{flex: 1}}>
          <WebView
            source={{ html: '<div>COTENT OF WEBVIEW HERE</div>' }}
            // source={{ uri: 'https://infinite.red/react-native' }}
            style={{margin: 20, flex :1, height: 250, width: 300, backgroundColor: 'red'}}
          />
        </View>
        <View style={{backgroundColor: 'yellow', height: 100, width: 300, alignItems: 'center', justifyContent: 'center', padding: 10 }}>
          <Text>TEXT COMPONENT 3</Text>
         </View>
      </ScrollView>
    );
  }
}
```

On  simulator all siblings are rendered (text component 1 - 3)
On real device webview overlaps previous siblings and they are not renderd.

![screen shot 2018-10-18 at 1 26 22 pm](https://user-images.githubusercontent.com/3833179/47148453-6dff8a80-d2d9-11e8-8c0e-3a98045afc77.png)

Stackoverflow question:
https://stackoverflow.com/questions/52872045/rendering-webview-on-android-device-overlaps-previous-siblings-from-same-parent

**Comment by Titozzz** [comment]
This is something I noticed too which is due to new overflow implementation. Maybe we could fix it on our end, but in the meantime, use overflow: 'hidden' on the view that's around your webview.

FUN SAD FACT: I will still work on some devices but not all, and some emulators, but not all

**Comment by NetPumi2** [comment]
@Titozzz Thank you! You save our lifes :D ....

**Comment by fdobre** [comment]
> This is something I noticed too which is due to new overflow implementation. Maybe we could fix it on our end, but in the meantime, use overflow: 'hidden' on the view that's around your webview.
> 
> FUN SAD FACT: I will still work on some devices but not all, and some emulators, but not all

`overflow: 'hidden'` seems to work perfect in my case. I will come with an update after tests on several devices are done.

**Comment by marconett** [comment]
the overflow workaround should be in the readme imo

**Comment by lpikora** [comment]
I just found that this approach can cause crash on some Android devices (tested on Pixel 1, Android Pie)

Same issue can be fixed by setting 0.99 opacity to WebView component `<WebView style={{ opacity: 0.99 }} />`

I tested it on Pixel 1, Android Pie.

https://stackoverflow.com/questions/54131875/screen-blinks-once-when-rendering-a-webview-on-android/54719378#54719378

**Comment by florian-lemiere** [comment]
@lpikora : Thanks a lot for this one, overflow:'hidden' crash my app since few days and opacity:0.99 work perfectly !!!

**Comment by Titozzz** [comment]
CC #429 .
