### ISSUE TITLE
better way of custom css injection

### ISSUE THREAD

**Issue by rockneverdies55** [react-native-community/react-native-webview#1012]
I'm using `injectJavascript` to put some mobile specific css onto page.  

Doing something like: 
``` 
  const style = document.createElement('style');
  style.type = 'text/css';
  style.appendChild(document.createTextNode('${this.getCss()}'));
  document.head.appendChild(style);
```
within `injectJavascript` prop function. 

However those styles  (such as height, color, font changes) show their effect after page renders thus very visible to user within the first couple of seconds on load. Like you see things load orange and then turn red and etc...

Is there a way (or would be awesome if there was) to cache such content to webview before page loads instead of injecting it into the page content like this?

**Comment by philipp65** [comment]
2 possible solutions:

- try using `injectedJavaScript`: https://github.com/react-native-community/react-native-webview/blob/master/docs/Reference.md#injectedjavascript

- download dom, inject your styles & scripts, set `WebView` to your local `html` file: https://github.com/react-native-community/react-native-webview/blob/master/docs/Reference.md#source

**Comment by rockneverdies55** [comment]
Just realized that I have typo above I'm actually already using `injectedJavascript` not injectJavascript.

However the second solution you suggested sounds like an interesting idea. Thanks a lot.

**Comment by mattbucci** [comment]
In case anyone comes across this. There is now: injectedJavaScriptBeforeContentLoaded
https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#injectedjavascriptbeforecontentloaded
