### ISSUE TITLE
The window.ReactNativeWebView.postMessage release version does not work, the program will automatically exit

### ISSUE THREAD

**Issue by axin313** [react-native-community/react-native-webview#1014]
**Bug description:**
I am using data from: `Web -> React Native` using `window.ReactNativeWebView.postMessage() `encountered some exceptions, The debug version is normal, but when I create a release android, executing to window.ReactNativeWebView.postMessage will cause the program to automatically exit.

```
 renderChart(props) {

        let data = "hello";
        const injectedJavaScript = `window.ReactNativeWebView.postMessage('${data}');`;
        return injectedJavaScript;
    }

<WebView
         ref={ref => this.web = ref}
         source= {{uri:"http://192.168.31.78:8089/index.html"}}
         injectedJavaScript = {this.renderChart(this.props)}
         javaScriptEnabled={true}
         messagingEnabled={true}
         onMessage={(even) => {
         console.info(JSON.stringify(even.nativeEvent.data))
                }}
            />
```
The output is normal in the Debug version：
![image](https://user-images.githubusercontent.com/34739776/68578843-c9388800-04ad-11ea-9ae2-af4ad30aadd2.png)

**To Reproduce:**

release does not work

**Expected behavior:**
`react-native run-android --variant=release`
WebView's onMessage can output content normally

**Screenshots/Videos:**

**Environment:**
 - OS:  Android
 - OS version: 9
 - react-native version:0.60.4
 - react-native-webview version:7.4.3

**Comment by KingAmo** [comment]
i have the same issue with `hermes` enabled, and it seems because of https://github.com/facebook/hermes/issues/114

**Comment by anetka31** [comment]
I had a similar problem with injectedJavaScript prop. Injedted string did not work only on realease version. It turned out that the problem was that i build my data with the addition assignment operator (+=). When I changed it, it started working. Example:
I had:
```data +=markerContent;  ```
Replace to:
``` data = data + markerContent; ```

**Comment by Huxpro** [comment]
@axin313 @KingAmo 

We (Hermes) introduced a special directive `"show source"` to make `toString` returning original source code in Hermes 0.8.1. Would you mind try it with React Native 0.65-rc.3 and see if it helps? You can find more details at https://github.com/facebook/hermes/issues/114#issuecomment-887106990
