### ISSUE TITLE
[iOS]: Custom Font not working

### ISSUE THREAD

**Issue by brandtnewww** [react-native-community/react-native-webview#1016]
**Bug description:**
On iOS, custom fonts are not used within the WebView. I followed the instructions on a few prior bug reports but I can't get the custom font running on iOS.

**To Reproduce:**

To generate the html for a WebView, I created this function

```
export const generateHtml = (content, textColor, fontFileName = 'NeuzeitOffice-Regular', fileFormat = 'ttf') => {

  const fileUri = Platform.select({
    ios: `${fontFileName}.${fileFormat}`,
    android: `file:///android_asset/fonts/${fontFileName}.${fileFormat}`
  })

  return (
    `
      <!DOCTYPE html>
      <html lang="en">
      <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
          <style media="screen" type="text/css">

            html, body {
              height: 100%;
              width: 100%;
              margin: 0;
              background-color: transparent;

              @charset "UTF-8";
              @font-face {
                font-family: ${fontFileName};
                src: url('${fileUri}'), local('${fontFileName}'), format('${fileFormat === 'ttf' ? 'truetype' : 'opentype'}');
              };

              font-size: 15px;
              line-height: 22px;
              text-align: left;
              color: ${textColor};
            }

          </style>
      </head>
      <body>
        ${content}
      </body>
    `
  )
}
```

I use it like this:

```
import { ActivityIndicator, View } from 'react-native'
import { WebView } from 'react-native-webview'

const html = generateHtml(content, '#FFF')

<WebView
            pointerEvents='none'
            scrollEnabled={false}
            source={{ html }}
            renderLoading={() => <View style={{ flex: 1 }} ><ActivityIndicator size='small' color='#FFF' /></View>}
            startInLoadingState

            allowFileAccess
            allowUniversalAccessFromFileURLs
            allowingReadAccessToURL='file:///assets/fonts'

          />
```

I tried to use the last 3 properties to get using the custom font on iOS running but it didn't help. 

I also tried it on a real Device - not only on the Simulator.

**Expected behavior:**

As this code works perfectly fine on Android, I would like to know what I have to do to make it run on iOS too. It would be great to include an example in the documentation. I'd like to contribute it to the documentation if I learn how to do it.

**Environment:**
 - OS: iOS
 - OS version: iOS 13.0 and iOS 13.2
 - react-native version: 0.61.2
 - react-native-webview version: 7.4.2

**Comment by punksta** [comment]
https://github.com/react-native-community/react-native-webview/issues/326 might help

**Comment by brandtnewww** [comment]
@punksta I got my current solution from there (https://github.com/react-native-community/react-native-webview/issues/326#issuecomment-510005798) but it was written for React Native 0.57 - maybe something changed? It doesn't work for me on iOS.

**Comment by punksta** [comment]
```
export const generateAssetsFontCss = (
	fontFamily: string,
	fileFormat: fontFormats = "ttf"
) => {
	const fileName = Platform.select({
		ios: `${fontFamily}.${fileFormat}`,
		android: `file:///android_asset/fonts/${fontFamily}.${fileFormat}`
	});

	return `
	@font-face {
        	font-family: '${fontFamily}';
        src: local('${fontFamily}'), url('${fileName}') format('${
		fileFormat === "ttf" ? "truetype" : "opentype"
	}');
	}
	`;
};
```

just checked, we have changed `generateAssetsFontCss` this way. `local` has been changed. `local('${fontFamily}')`

**Comment by brandtnewww** [comment]
But the value of fontFamily hasn't, right? You just renamed the variable from fontFileName to fontFamily.

**Comment by punksta** [comment]
@brandtnewww oh, right. idk then :)

**Comment by Beissner** [comment]
@brandtnewww Did you find a solution for this?

**Comment by Subham-Dutta** [comment]
Is there any workaround to load custom fonts in IOS?  facing the same issue.

**Comment by Beissner** [comment]
Using google fonts seems to work but I'm still having issues with a local otf font file.

**Comment by brandtnewww** [comment]
I didn't find a solution for this yet.

**Comment by hadrienl** [comment]
I have same problem : I have set the same function given upper, but the font is not loaded in my webview.

**Comment by sonseait** [comment]
I have a solution, you guys can use this tool [https://transfonter.org](https://transfonter.org) to transform the font to base64 and add the generated css to html, I have tested and it working [https://imgur.com/MMhMrQg](https://imgur.com/MMhMrQg)

**Comment by tolgaberk** [comment]
> I have a solution, you guys can use this tool https://transfonter.org to transform the font to base64 and add the generated css to html, I have tested and it working https://imgur.com/MMhMrQg

This one worked flawlessly for me. Thanks man i spent like 3 days for this thing.   🤪

**Comment by brandtnewww** [comment]
@sonseait & @tolgaberk How does the css you're using look like?

**Comment by tolgaberk** [comment]
@brandtnewww  i basically declared a font-face like this:

`@font-face {
font-family: 'Apple Chancery';
src: url(data:application/font-woff;charset=utf-8;base64,_**YourFontInBase64Format**_) format('woff'); 
font-weight: normal;
font-style: normal;
}`

and it works both on android and ios. I guess the reason that custom fonts aren't rendered on WebView is that the WebView cannot seem to recognize dependencies of the css file which is already a dependency from the html or whatever you're using. In conclusion i think WebView just can't reach nested imports like this. With this way we completely embedded the font to css. So it can be seen by WebView.

**Comment by NightWarrior** [comment]
> @brandtnewww i basically declared a font-face like this:
> 
> `@font-face { font-family: 'Apple Chancery'; src: url(data:application/font-woff;charset=utf-8;base64,`_**YourFontInBase64Format**_`) format('woff'); font-weight: normal; font-style: normal; }`
> 
> and it works both on android and ios. I guess the reason that custom fonts aren't rendered on WebView is that the WebView cannot seem to recognize dependencies of the css file which is already a dependency from the html or whatever you're using. In conclusion i think WebView just can't reach nested imports like this. With this way we completely embedded the font to css. So it can be seen by WebView.

Can confirm that this works, also you can get the @font-face from fonts.googleapis.com, e.g. 
`https://fonts.googleapis.com/css?family=Times` copy one of them (i had to make mine one liner, might not be required for anyone else) and then put it in the style as:

```
@font-face { **your font data** } body { **your body styling** } **...any other styling**
```

**Comment by mavalos1** [comment]
I a

> @brandtnewww i basically declared a font-face like this:
> 
> `@font-face { font-family: 'Apple Chancery'; src: url(data:application/font-woff;charset=utf-8;base64,`_**YourFontInBase64Format**_`) format('woff'); font-weight: normal; font-style: normal; }`
> 
> and it works both on android and ios. I guess the reason that custom fonts aren't rendered on WebView is that the WebView cannot seem to recognize dependencies of the css file which is already a dependency from the html or whatever you're using. In conclusion i think WebView just can't reach nested imports like this. With this way we completely embedded the font to css. So it can be seen by WebView.

@tolgaberk @NightWarrior @brandtnewww  I'm struggling to set up the directories (where to put the fonts, what's the route ...) right for this to work. Would you have a boilerplate/source code to a project where this work. Please help!

**Comment by methineeinkan** [comment]
> I have a solution, you guys can use this tool https://transfonter.org to transform the font to base64 and add the generated css to html, I have tested and it working https://imgur.com/MMhMrQg

is work for me thx

**Comment by edritech93** [comment]
same for me

**Comment by OlivierFreyssinet** [comment]
In case anyone is interested, I was struggling to get the initial solution working **on Android**  (I didn't try iOS) and 
finally managed to get it to work just by removing the `format()` part.

It works fine with `.otf` `.ttf` `.woff` `.woff2`.

It works without any special prop (or maybe it requires `allowFileAccess` to be `true` but I didn't try with this prop set to `false` since I'm using WebView to load a local html file).

Here's what I'm using:

```
@font-face {
    font-family: ${fontFileName};
    src: url('${fileUri}');
};
```
where `fileUri` is something like that: `file:///android_asset/fonts/fontFileName.ttf`

**Comment by rossjohnsonMP** [comment]
For me it works on android without having to declare the font face - bare in mind i have added the custom font to the app as a whole, but cannot get it to work on iOS at all, with any of the solutions above (bar the base64 one)

**Comment by sandeepg1220** [comment]
Still custom font is not woring for android and ios. I checked the versions from 7.0.1 to latest 9.2.2

**Comment by rossjohnsonMP** [comment]
> Still custom font is not woring for android and ios. I checked the versions from 7.0.1 to latest 9.2.2

@sandeepg1220 custom fonts definitely work on android on v7 and v8 (and probably 9) just not iOS - plenty of examples of how to make it work on android above ^^

**Comment by sandeepg1220** [comment]
Not working. I checked for Android v9 and v10 .

**Comment by sandeepg1220** [comment]
Please provide any update on this. I was struck with this issue. I'm unable to move forward with this issue. Even not able to use other packages because having the same issue facing.

**Comment by tolgaberk** [comment]
@sandeepg1220 convert your fonts to base64 and declare a font-face in between style tags of your html. It works on both platforms. Giving the path as file:///android_asset works for android but there is no solution for ios beside base64 solution for using custom fonts in webview.

**Comment by sandeepg1220** [comment]
@tolgaberk thanks for your help. Is this solution will work for iOS. Could you give any example so that I can understand easily

**Comment by tolgaberk** [comment]
> @tolgaberk thanks for your help. Is this solution will work for iOS. Could you give any example so that I can understand easily

I literally explained and gave example about this.

> @brandtnewww i basically declared a font-face like this:
> 
> `@font-face { font-family: 'Apple Chancery'; src: url(data:application/font-woff;charset=utf-8;base64,`_**YourFontInBase64Format**_`) format('woff'); font-weight: normal; font-style: normal; }`
> 
> and it works both on android and ios. I guess the reason that custom fonts aren't rendered on WebView is that the WebView cannot seem to recognize dependencies of the css file which is already a dependency from the html or whatever you're using. In conclusion i think WebView just can't reach nested imports like this. With this way we completely embedded the font to css. So it can be seen by WebView.

**Comment by sandeepg1220** [comment]
@tolgaberk thanks. I will try this

**Comment by sandeepg1220** [comment]
@tolgaberk no luck

**Comment by personjerry** [comment]
@sandeepg1220 Look at this answer https://stackoverflow.com/a/25798199/ which might be supported by these changes https://github.com/react-native-community/react-native-webview/pull/784 if you want to do the work and revive that pull request.

**Comment by shumin** [comment]
Using base64 coded font is really a hacky way of achieving which supposed to be very simple thing.

It turns out (for me at least) all I need is to use `baseUrl` along with `html`:
```
<WebView
 originWhitelist={['*']}
 source={{
    baseUrl: '', // this makes it to work for ios, for android it works without this
    html: htmlContent, }}
/>
```

**Comment by sandeepg1220** [comment]
@shumin No luck. Can you tell which versions are using for react-native and react-native-webview

**Comment by shumin** [comment]
@sandeepg1220 This is what I'm using.

```
    "react": "16.11.0",
    "react-native": "0.62.2",
    "react-native-webview": "^9.3.0"
```

**Comment by EndLess728** [comment]
> Using base64 coded font is really a hacky way of achieving which supposed to be a very simple thing.
> 
> It turns out (for me at least) all I need is to use `baseUrl` along with `html`:
> 
> ```
> <WebView
>  originWhitelist={['*']}
>  source={{
>     baseUrl: '', // this makes it to work for ios, for android it works without this
>     html: htmlContent, }}
> />
> ```

Can you give some example how to apply it 

```
import React, {useRef} from 'react';
import {WebView} from 'react-native-webview';

const htmlContent = `
<!DOCTYPE html>
<html>
  <head>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <style>
      @font-face {
        font-family: "CooperBlackBT";
        src: url("file:///android_asset/fonts/CooperBlackBT.ttf");
      }
      @font-face {
        font-family: "ApercuRegular";
        src: url("file:///android_asset/fonts/Apercu-Regular.ttf");
      }
      @font-face {
        font-family: "ApercuBold";
        src: url("file:///android_asset/fonts/Apercu-bold.ttf")
      }
      html, body, div {
        margin: 0;
		    padding: 0;
		    border: 0;
      }
      .faq_container {
        background: #f8bab9;
        padding: 15px 25px;
      }
      .underline {
        text-decoration-line: underline;
        font-size: 16px;
        font-family: ApercuBold;
      }
      .header {
        margin-top: 5px;
        margin-bottom: 5px;
        text-align: center;
        color: #fff;
        font-size: 28px;
        font-family: CooperBlackBT;
      }
      .titleStyle {
        color: #fb5759;
        font-size: 18px;
        font-family: ApercuRegular;
      }
      .text {
        color: #fff;
        font-size: 16px;
        font-family: ApercuRegular;
      }
      .textBold {
        color: #fff;
        font-size: 16px;
        font-family: ApercuBold;
      }
      .listItem {
        color: #fff;
      }
    </style>
  </head>
  <body>
    <div class="faq_container">
      <h1 class="header">Help</h1>

      <p class="titleStyle">
        <b> demo text is here</b>
      </p>

      <p class="text">
         demo text is here
      </p>

      <p class="titleStyle">
        <b> demo text is here? </b>
      </p>

      <p class="text">
        I demo text is here
      </p>

      <p class="titleStyle">
        <b>I have seen an offensive photo. How do I report it? </b>
      </p>

      <p class="text">
        On each pick there is a report button at the top right hand side. Tap
        the button and you will be able to select a reason for why you are
        reporting.\nYour information will not be shared with the user you
        report.
      </p>

      <p class="titleStyle"><b>How do I block someone?</b></p>

      <p class="text">
       demo text is here
      </p>

      <p class="titleStyle"><b>Can I create multiple accounts?</b></p>

      <p class="text">
        demo text is here
      </p>

      <p class="titleStyle"><b> demo text is here?</b></p>

      <p class="text">
        demo text is here
      </p>

      <p class="text">
       demo text is here
      </p>
    </div>
  </body>
</html>
`;

export default () => {
  const _listViewHeight = useRef(0);

  const _onLayout = e => {
    const {height} = e.nativeEvent.layout;
    _listViewHeight.current = height;
  };

  return (
    <WebView
      containerStyle={{borderRadius: 15}}
      onLayout={_onLayout}
      onError={err => console.log(err)}
      scrollEventThrottle={1}
      source={{
        html: htmlContent,
      }}
    />
  );
};
```

**Comment by sandeepg1220** [comment]
> @sandeepg1220 This is what I'm using.
> 
> ```
>     "react": "16.11.0",
>     "react-native": "0.62.2",
>     "react-native-webview": "^9.3.0"
> ```

I'm using the same versions it is working for android but not for ios.

**Comment by shumin** [comment]
@sandeepg1220 
I will try to create a hello world app and put it in github repo, probably that will help.

**Comment by sandeepg1220** [comment]
> @sandeepg1220
> I will try to create a hello world app and put it in github repo, probably that will help.

Please do that it will be use-full for others also.
Thanks

**Comment by shumin** [comment]
Here is a Hello World app with custom font in `react-native-webview` that works both on Android and iOS. Hope this will help.

https://github.com/mohammad-haque/react-native-webview-custom-font

**Comment by rossjohnsonMP** [comment]
Thanks @shumin originWhitelist={['*']} + base url + declaring the font face like @punksta said above + its finally working

**Comment by rossjohnsonMP** [comment]
@shumin so using `originWhitelist={['*']}` in combination with `source={{ baseUrl: '', html: content }}` works but now if i have an anchor tag that points to an app deeplink I get this: 
![Screenshot 2020-05-11 at 15 17 12](https://user-images.githubusercontent.com/44770156/81571947-83944380-939a-11ea-8349-f53d0e11861e.png)

Appreciate the need to set up an associated domain is going to make this a bit tricky to create a replicable example

**Comment by rossjohnsonMP** [comment]
Bug still exists and workaround is not ideal

**Comment by sagargondaliya** [comment]
Any workaround for remote html content loading ?

**Comment by ersefuril** [comment]
Agree with @rossjohnsonMP, the base64 or ```source={{ baseUrl: '', html: content }}``` workarounds are not really nice. Any idea how to force the webview to load the local font ?

**Comment by lamaj411** [comment]
How change font-family of react-native webview, i want to use font-family.ttf from assets, is this possible?

**Comment by trinvh** [comment]
I use this tool for generating base64 font-face then it's working fine https://amio.github.io/embedded-google-fonts/

**Comment by nguyen95** [comment]
Yeah! **baseUrl** is the key!

**Comment by webuijorgeGL** [comment]
> I have a solution, you guys can use this tool https://transfonter.org to transform the font to base64 and add the generated css to html, I have tested and it working https://imgur.com/MMhMrQg

works for me... thanks

**Comment by yogendrajs** [comment]
Doesn't make it work for iOS even after applying every possible solution mentioned above. Any other possible workaround?

**Comment by yogendrajs** [comment]
Doesn't make it to work for iOS even after applying every possible solution mentioned above. Any other possible workaround?

**Comment by yogendrajs** [comment]
Didn't make it work for iOS even after applying every possible solution mentioned above. Any other possible workaround?

**Comment by michaelmika** [comment]
I am trying to include FontAwesome (4) into a react-native-webview (using react-native-canvas). I tried every solution above, but neither loading the ttf of FontAwesome from file nor including it as base64 seem to work. Has anyone else tried it with FontAwesome?

**Comment by bitfabrikken** [comment]
Old issue, but still open.
Just encountered it again, and it works for me to have both originWhitelist set to [*] and source.baseUrl to "".

```
<WebView 
    source={{ html, baseUrl: '' }}
    originWhitelist={["*"]}
/>
```

**Comment by NguyenVanVietPoLy** [comment]
I code, i think right but not work, until i copy https://github.com/mohammad-haque/react-native-webview-custom-font/blob/master/App.tsx that work perfect :D

**Comment by xjdqq** [comment]
> ```
> export const generateAssetsFontCss = (
> 	fontFamily: string,
> 	fileFormat: fontFormats = "ttf"
> ) => {
> 	const fileName = Platform.select({
> 		ios: `${fontFamily}.${fileFormat}`,
> 		android: `file:///android_asset/fonts/${fontFamily}.${fileFormat}`
> 	});
> 
> 	return `
> 	@font-face {
>         	font-family: '${fontFamily}';
>         src: local('${fontFamily}'), url('${fileName}') format('${
> 		fileFormat === "ttf" ? "truetype" : "opentype"
> 	}');
> 	}
> 	`;
> };
> ```
> 
> just checked, we have changed `generateAssetsFontCss` this way. `local` has been changed. `local('${fontFamily}')`

works for me, the ttf  file need in    android/app/scr/assets/fonts/    and     ios/Resources/   then you can use it in webview

**Comment by codal-mpawar** [comment]
> I have a solution, you guys can use this tool https://transfonter.org to transform the font to base64 and add the generated CSS to HTML, I have tested and it works https://imgur.com/MMhMrQg

It's a working charm. Thanks, buddy to saves time.

**Comment by pedrogoiania** [comment]
thanks @shumin your solutions works fine

**Comment by redionSpace** [comment]
`export const injectedStyle = `<head>
  <style>
@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@500&display=swap');
    body {
      margin-left: 24px;
      margin-right: 24px;
    }
    * {
      font-size: 1.9rem !important;
      color: white !important;
      margin: 0 !important;
      padding: 0 !important;
   font-family: 'Poppins', sans-serif !important;
    }
  </style>
</head>`;

 <WebView
          originWhitelist={['*']}
          contentContainerStyle={styles.contentContainerStyle}
          useWebKit={true} // not sure this plays a role
          onMessage={onWebViewMessage}
          source={{
            html: injectedStyle + '<span>' + value + '</>' || '',
          }}
          style={{
            backgroundColor: Colors.transparent,
          }}
          scrollEnabled={false}
          nestedScrollEnabled={false}
        />`
        
        WORKS ALL THE TIME!
