### ISSUE TITLE
Input type = "file" not responding in Android 

### ISSUE THREAD

**Issue by Kiranyellu** [react-native-community/react-native-webview#1017]
**Bug description:**

I am loading webview in my app with input type = "file" there it has open my folder from the device but I didn't see the options

**Expected behavior:**

When I click browser in webview it has to open the camera, Library, and folder 

**Environment:**
 - OS: Macbook pro
 - OS version: 10.14
 - react-native version: 0.59
 - react-native-webview version: we are using webView component from react-native .
   below the link has the same issue 

[https://github.com/facebook/react-native/issues/19144](URL).

I have been facing this issue for 4 days.

**Comment by andreipfeiffer** [comment]
The builtin `WebView` from `react-native` doesn't support file upload.

Please use the `react-native-webview` package:
https://github.com/react-native-community/react-native-webview/blob/master/docs/Getting-Started.md
