### ISSUE TITLE
Camera for iOS is not working in webvieww

### ISSUE THREAD

**Issue by lukaskai** [react-native-community/react-native-webview#1020]
Hello,

I am using lastest version of webview and want to access iOS camera from within webview. Everything works great on Safari (e.g. page: https://davidwalsh.name/demo/camera.php), however, nothing happens inside webview. I granted needed permissions like camera or audio, however, it still does not work.

Any ideas?

**Comment by skdev24** [comment]
@lukaskai Have you found the solution?

**Comment by Titozzz** [comment]
That's weird, cause I definitely can use camera for input fields. 🙁

**Comment by TchernyavskyDaniil** [comment]
@Titozzz 
Maybe you can give some example how it works?
Add permissions to Info.plist (NSMicrophoneUsageDescription, NSCameraUsageDescription), ask permissions after load webview, but nothing
https://github.com/react-native-community/react-native-webview/issues/1045

**Comment by skdev24** [comment]
@Titozzz I believe react native webview is blocking permission alert, even though you give permission from the app, I found a work around using the lib https://github.com/proyecto26/react-native-inappbrowser, when doesn't block the alert when you view that above web page you will get the camera permission alert which is blocked in react native webview.

**Comment by kaissaroj** [comment]
@lukaskai did you find solution ?

**Comment by kaissaroj** [comment]
@lukaskai did you solve this problem ?

**Comment by fhenri42** [comment]
Hey @lukaskai any update on this issue?

**Comment by gordomo** [comment]
no solution yet? thanks

**Comment by LucasLpr** [comment]
Having this issue too on ios, did you find any solutions ?
