### ISSUE TITLE
Invariant Violation: Invalid URL: cannot be empty

### ISSUE THREAD

**Issue by zhonggithub** [react-native-community/react-native-webview#1024]
**Bug description:**

when i use like this, the bug will show in android.  ios is normal.
<WebView
            source={{uri: 'https://dev-reception.aiusmart.com/dataCenter/uke'}}
          />
**To Reproduce:**

**Expected behavior:**

**Screenshots/Videos:**

![image](https://user-images.githubusercontent.com/17545551/68989272-efc83b80-087e-11ea-841d-d20fa1e28307.png)

**Environment:**
 - OS: android
 - OS version: android 8.0
 - react-native version: 0.61.4
 - react-native-webview version: 7.5.1

**Comment by zhonggithub** [comment]
> **Bug description:**
> 
> when i use like this, the bug will show in android. ios is normal.
> <WebView
> source={{uri: '[https://dev-reception.aiusmart.com/dataCenter/uke'}}](https://dev-reception.aiusmart.com/dataCenter/uke'%7D%7D)
> />
> **To Reproduce:**
> 
> **Expected behavior:**
> 
> **Screenshots/Videos:**
> 
> ![image](https://user-images.githubusercontent.com/17545551/68989272-efc83b80-087e-11ea-841d-d20fa1e28307.png)
> 
> **Environment:**
> 
> * OS: android
> * OS version: android 8.0
> * react-native version: 0.61.4
> * react-native-webview version: 7.5.1

when i use this:
<WebView
source={{uri: 'https://dev-reception.aiusmart.com/dataCenter/uke'}}
originWhitelist={['*']}
            onShouldStartLoadWithRequest={request => {
              return request.url.startsWith('https://dev-reception.aiusmart.com');
            }}
/>


it work success.  i don't know why ?

**Comment by rodmastro32** [comment]
Hi @zhonggithub did you ever found out the issue? it started to me this weekk
