### ISSUE TITLE
App crashes when WebView contains embed video player

### ISSUE THREAD

**Issue by esjs** [react-native-community/react-native-webview#1026]
**Bug description:**
Hello, I'm facing app crash on Android (Meizu M5s) with webview when it has iframe with embed video player.
Seems to be working ok on Samsung S9 and Xiaomi Mi 5s.

`    --------- beginning of crash
11-18 11:27:22.926 27293-27293/com.test.application E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.test.application, PID: 27293
    java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
        at com.android.webview.chromium.WebViewContentsClientAdapter.getDefaultVideoPoster(WebViewContentsClientAdapter.java:1339)
        at org.chromium.android_webview.DefaultVideoPosterRequestHandler$1.run(DefaultVideoPosterRequestHandler.java:39)
        at android.os.Handler.handleCallback(Handler.java:815)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:6000)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:840)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:730) `

**To Reproduce:**
Minimal reproducible example:
`<WebView
          originWhitelist={['*']}
          source={{
          html: '<html> <head> <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, shrink-to-fit=no" /> </head> <body webkit-playsinline playsinline> <iframe width="560" height="315" allowfullscreen="allowfullscreen" frameborder="0" src="https://motorsport.tv/embed/2mLbWhnD-macau-gp-f3-world-cup-race-highlights?autoplay=1"></iframe> </body> </html>',
          }}
/>`

**Expected behavior:**
App should continue to work without crash.

**Environment:**
 - OS: Android
 - OS version: 6.0
 - react-native version: 0.61.4
 - react-native-webview version: 7.5.1

**Comment by MuhammadMattiullah** [comment]
@esjs i am still getting crash on Android.
      <WebView
        containerStyle={
          {
            width,
            alignSelf: 'center',
            alignContent: 'center',
          }
        }
        source={{
          baseUrl: data.provider_url,
          html: makeIframeHTML(),
        }}
        allowsInlineMediaPlayback
        allowsFullscreenVideo
        mediaPlaybackRequiresUserAction={false}
        mixedContentMode='always'
        scalesPageToFit
        originWhitelist={['*']}
        startInLoadingState
        renderLoading={() =>  <Spinner variant={Spinner.VARIANTS.SMALL} /> }
      />
**Versions**
"react-native-webview": "9.3.0",
"react-native": "0.61.5",
Any solution for this ? @esjs

**Comment by esjs** [comment]
> @esjs i am still getting crash on Android.
> 
> ```
>   <WebView
>       containerStyle={
>         {
>           width,
>           alignSelf: 'center',
>           alignContent: 'center',
>         }
>       }
>       source={{
>         baseUrl: data.provider_url,
>         html: makeIframeHTML(),
>       }}
>       allowsInlineMediaPlayback
>       allowsFullscreenVideo
>       mediaPlaybackRequiresUserAction={false}
>       mixedContentMode='always'
>       scalesPageToFit
>       originWhitelist={['*']}
>       startInLoadingState
>       renderLoading={() =>  <Spinner variant={Spinner.VARIANTS.SMALL} /> }
>     />
> ```
> 
> **Versions**
> "react-native-webview": "9.3.0",
> "react-native": "0.61.5",
> Any solution for this ? @esjs

Are you sure that crash is related to video poster? @MuhammadMattiullah

**Comment by MuhammadMattiullah** [comment]
Yes @esjs when I comment out this particular piece of code then app runs smoothly as expected but when it comes to rendering embedded videos using web view then it crashes the app.
And I think this is because of react-native-navigation and web view does not work well together :(

**Comment by esjs** [comment]
> Yes @esjs when I comment out this particular piece of code then app runs smoothly as expected but when it comes to rendering embedded videos using web view then it crashes the app.
> And I think this is because of react-native-navigation and web view does not work well together :(

Can you provide source code for embed video player which causes issue? @MuhammadMattiullah

**Comment by msriaz** [comment]
@MuhammadMattiullah

Webview on android is crashing when it is wrapped in other views
Adding opcity 0.99 fix this crash
Feel free to check these references.
#811
https://www.gitmemory.com/issue/react-native-community/react-native-webview/430/493976111

**Comment by chhornponleu** [comment]
> @MuhammadMattiullah
> 
> Webview on android is crashing when it is wrapped in other views Adding opcity 0.99 fix this crash Feel free to check these references. #811 https://www.gitmemory.com/issue/react-native-community/react-native-webview/430/493976111

still need this in RN 0.72 in 2023
