### ISSUE TITLE
net::ERR_ACCESS_DENIED When Rendering Local HTML

### ISSUE THREAD

**Issue by ALEEF02** [react-native-community/react-native-webview#1028]
**Bug description:**

I am trying to display a local PDF in base64. I have assigned all the correct permissions to view the document. When I try to render it I get the error `net::ERR_ACCESS_DENIED`. This only happens on Android.

**To Reproduce:**

Create a WebView
Use a path in the local system
Try to view the WebView
[https://github.com/ALEEF02/Bulletin-Magazine-Mobile-App/blob/da41ff504d1ad2a5463b2d062adaa66fb54c61c2/rn-pdf-reader-js/index.js#L200](url)

**Expected behavior:**

The WebView should be able to render to specified PDF in the local files

**Screenshots/Videos:**

![image (1)](https://user-images.githubusercontent.com/12904259/69078847-9df1f380-09ed-11ea-95f1-7ef8c4d957f3.png)
![image](https://user-images.githubusercontent.com/12904259/69078849-9df1f380-09ed-11ea-85e5-d3ea81787cb9.png)
![IMG_4626](https://user-images.githubusercontent.com/12904259/69078850-9df1f380-09ed-11ea-830e-7253b78e998e.JPG)

**Environment:**
 - OS: Android
 - OS version: Unknown
 - react-native version: 34.0.2
 - react-native-webview version: 7.5.1

**Comment by ALEEF02** [comment]
Alright, so I was able to find a temporary fix to the solution, seen here: [https://github.com/react-native-community/react-native-webview/issues/656#issuecomment-551312436](url)

**Comment by douglaslondrina** [comment]
@ALEEF02, I'm having the same issue loading a static HTML, it apparently happens when loading the file right after or during webview being de-instantiated by the runtime from a previous load.

Both your links aren't working. Would you kindly provide your workaround?
Thanks!

**Comment by ALEEF02** [comment]
I fixed the links :D

**Comment by vmontanheiro** [comment]
Doesn't work to me

Encountered an error loading page {description: "net::ERR_ACCESS_DENIED"

name: "Screenshot_20200330-002215.png"
type: "image/png"
uri: "content://com.android.providers.media.documents/document/image%3A1318"

  const handleAndroidSource = useCallback(() => {
    setSource({uri: params.file.uri});
  }, [params]);

    <WebView
        style={styles.container}
        pagingEnabled
        javaScriptEnabled
        domStorageEnabled
        startInLoadingState={true}
        // automaticallyAdjustContentInsets={false}
        source={source}
        originWhitelist={[`*`]}
        allowFileAccess={true}
        allowFileAccessFromFileURLs={true}
        allowingReadAccessToURL={true}
        onLoad={Platform.select({
          android: onAndroidLoad,
          ios: onIOSLoad,
        })}
      />

Any solution?

**Comment by krizpoon** [comment]
I faced the same problem. It happened randomly on first load. I found that if the WebView source was initially null, then it won't happen. Hope this could provide some insight to debug the problem. 

This temporary fix is not quite desirable as it would leave a blank page in the WebView's history stack.

**Comment by 92pino** [comment]
Facing the same issue. Anyone found the solution?
<img width="314" alt="스크린샷 2020-09-09 오후 12 15 10" src="https://user-images.githubusercontent.com/45158632/92550264-1cc65e80-f296-11ea-9369-79d87a962b76.png">
<img width="770" alt="스크린샷 2020-09-09 오후 12 15 31" src="https://user-images.githubusercontent.com/45158632/92550369-43849500-f296-11ea-8c32-962c51b7485d.png">

**Comment by alancwoo** [comment]
Same issue with `react-native 0.63.3`, `react-native-webview ^10.10.0`, tried everything with all flags and the `state.renderedOnce` solution above:

```
<WebView
  allowFileAccess={true}
  originWhitelist={['*']}
  javaScriptEnabled={true}
  domStorageEnabled={true}
  source={this.state.renderedOnce ? {uri: this.state.cachedItemPath} : undefined}
  allowFileAccess={true}
  allowUniversalAccessFromFileURLs={true} />
```

I'm trying to render some html that was saved to local storage.

**Comment by seancheung** [comment]
Here is the fix:

```typescript
const [uri, setUri] = useState(null);

useEffect(() => {
  setUri('blahblah');
  return () => {
    setUri(null);
  };
}, []);
```

**Comment by joscelyn** [comment]
Solution by vgort here: https://github.com/react-native-webview/react-native-webview/issues/656#issuecomment-561067913 worked for me !
As he explained, you have to define source after webview onLoad():
```
const [renderedOnce, setRenderedOnce] = useState(false);

const updateSource = () => {
    setRenderedOnce(true);
 };

return(
   <WebView
       originWhitelist={['*']}
       source={renderedOnce ? {uri: localHTML} : undefined}
       style={{flex: 1}}
       allowFileAccess={true}
       allowUniversalAccessFromFileURLs={true}
       onLoad={updateSource}
   />)
```

**Comment by c-moyer** [comment]
> Solution by vgort here: [#656 (comment)](https://github.com/react-native-webview/react-native-webview/issues/656#issuecomment-561067913) worked for me ! As he explained, you have to define source after webview onLoad():
> 
> ```js
> const [renderedOnce, setRenderedOnce] = useState(false);
> 
> const updateSource = () => {
>     setRenderedOnce(true);
>  };
> 
> return(
>    <WebView
>        originWhitelist={['*']}
>        source={renderedOnce ? {uri: localHTML} : undefined}
>        style={{flex: 1}}
>        allowFileAccess={true}
>        allowUniversalAccessFromFileURLs={true}
>        onLoad={updateSource}
>    />)
> ```

This worked for me but I agree this issue shouldn't be closed.

**Comment by oded-regev** [comment]
@alancwoo `allowFileAccess={true}` saved me 🙏
