### ISSUE TITLE
cannot access local html in android

### ISSUE THREAD

**Issue by yqyily** [react-native-community/react-native-webview#1030]
react-native: 0.61.4
react-native-webview: 7.5.1
when i render echarts with webview,it is work in ios ,but it is issues in android
![image](https://user-images.githubusercontent.com/7323733/69124811-7da26180-0adf-11ea-808c-b30d9ed4ac36.png)

![image](https://user-images.githubusercontent.com/7323733/69124953-c0643980-0adf-11ea-9388-30fee1d27df9.png)

`
export default class WebViewDemo extends Component {
    
    render() {
        return (
            <SafeAreaView style={{flex: 1}}>
                <WebView
                    ref={el => this.webviewRel = el}
                    originWhitelist={['*']}
                    source={require('../h5/chart.html') }
                
                />
            </SafeAreaView>

        );
    }
   }
`

**Comment by safaiyeh** [comment]
On Android you need to prepend your file path with `file:///android_asset/`

**Comment by msqar** [comment]
@safaiyeh for that to work, where should i put my html file? Because i put it in the same folder where i have the screen that uses it, works on iOS but doesnt work on android.

**Comment by safaiyeh** [comment]
When it is in the React Native project, it gets bundled into `file:///android_asset/`

Let's assume this is your project structure:
```
/android
/ios
/src
   | Component.tsx (WebView used here)
   | page.html
...
```

Here is how you can load the html:
```javascript
Platform.OS === 'android'
? { uri: 'file:///android_asset/src/page.html' }
: require('./page.html');
```

**Comment by safaiyeh** [comment]
@msqar

**Comment by msqar** [comment]
@safaiyeh thanks man, it worked!

**Comment by safaiyeh** [comment]
Awesome! Glad it worked out.
