### ISSUE TITLE
renderLoading in not rendered in the correct position

### ISSUE THREAD

**Issue by mydesweb** [react-native-community/react-native-webview#1031]
I just observed that in the latest version (compared to an old one) I am not able to render an ActivityIndicator centered on the screen while the webview is loading

`    renderLoading = () => (
        <View style={{flex: 1, justifyContent: 'center', alignItems: 'center'}}>
            <ActivityIndicator
                color={'#B9002F'}
                size="large"
            />
        </View>
    );`

`   render() {
        return (
            <SafeAreaView forceInset={{top: 'always'}} style={{flex: 1, backgroundColor: '#fff'}}>
                <WebView
                    source={this.source}
                    startInLoadingState={true}
                    renderLoading={this.renderLoading}
                />
            </SafeAreaView>
        );
    }`

will not work as expected, the ActivityIndicator is rendered in the bottom of the screen

**Comment by kyo504** [comment]
@mydesweb I have been faced with the same issue and found a solution by looking at the internal codes. The default style of loading view has following props:
```
  loadingOrErrorView: {
    position: 'absolute',
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    height: '100%',
    width: '100%',
    backgroundColor: 'white'
  },
``` 
which means that you can achieve what you expect if you pass following additional props to your style.
```
{
    position: 'absolute',
    height: '100%',
    width: '100%',
}
```

**Comment by mydesweb** [comment]
@kyo504 thank you, hope the maintainers will fix this also in the core lib

**Comment by plaa** [comment]
Thanks, the workaround worked for me as well.  Note that this affects both `renderLoading` and `renderError`.

As the following two screenshots from React Native Debugger shows, both the `RNCWebView` and the `renderLoading/Error` views are displayed one after another, instead of the loading/error view replacing the WebView.  (In this case they have equal height as I have `flex: 1` defined for the loading view.)

<img width="603" alt="Screenshot 2020-01-15 at 15 29 46" src="https://user-images.githubusercontent.com/1436281/72438778-3a4a3380-37ae-11ea-997a-1406a4c16154.png">

<img width="617" alt="Screenshot 2020-01-15 at 15 29 22" src="https://user-images.githubusercontent.com/1436281/72438784-3e765100-37ae-11ea-998d-9a8a6a68b3c8.png">

**Comment by plaa** [comment]
`renderError` styles must also include `backgroundColor: '#fff'`, otherwise the WebView page load error will be displayed in the background.

**Comment by safaiyeh** [comment]
@mydesweb How would you like this "fixed" styles can be overwritten, better docs?

**Comment by mydesweb** [comment]
@safaiyeh better docs can be a good start but in an older version of this library this just worked. It is quite confusing when I create a new component (View) which is not respecting the style defined..

**Comment by safaiyeh** [comment]
Got it @mydesweb I'll investigate the regression!

**Comment by mydesweb** [comment]
@safaiyeh probably there is a good reason for setting the default style like this
` loadingOrErrorView: {
    position: 'absolute',
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    height: '100%',
    width: '100%',
    backgroundColor: 'white'
  },`
but then I don't understand why the loading indicator is not rendered in the center of the screen out of the box
`  renderLoading = () => (
      <ActivityIndicator color={'#B9002F'} size="large" />
  );`
actually it is rendered on bottom of the screen

**Comment by plaa** [comment]
At least in my case the reason why the spinner was rendering at the bottom of the screen was that the native webview was rendering in the top half and pushing the loading / error view down to the bottom.

In earlier versions *either* the native webview *or* the loading / error view was rendered, not both at the same time.

**Comment by annjawn** [comment]
Still an issue.

**Comment by plaa** [comment]
What are the magic words needed to keep an unresolved issue open (as annjawn's comment clearly was insufficient)?

**Comment by developer239** [comment]
@plaa Magic words? "Do it yourself. This library is open source." 😂

**Comment by dzmitrykavalenka-own** [comment]
As mention @kyo504 , u can add those styles to `View` wrapper above `ActivityIndicator` and `top: '50%'`. It works for me.
```
{
    position: 'absolute',
    height: '100%',
    width: '100%',
    top: '50%',
}
```

**Comment by phanvanphuhn** [comment]
Issue with WebView Rendering in ScrollView
When you wrap a WebView inside a ScrollView, it may render at the bottom of the screen. The height of the WebView will be based on its parent, which can cause layout issues. The correct way to fix this is to separate the WebView and ScrollView.

```
<>
  <ScrollView>
    ...
  </ScrollView>
  <SafeAreaView
    style={{
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: "white",
      zIndex: 999, // Ensures it's above all other elements
    }}
  >
    <WebView {...props} />
  </SafeAreaView>
</> 
```

This will ensure that the WebView is positioned correctly and won't be pushed to the bottom by the ScrollView.

**Comment by Joseph-web-create** [comment]
> [@mydesweb](https://github.com/mydesweb) I have been faced with the same issue and found a solution by looking at the internal codes. The default style of loading view has following props:
> 
> ```
>   loadingOrErrorView: {
>     position: 'absolute',
>     flex: 1,
>     justifyContent: 'center',
>     alignItems: 'center',
>     height: '100%',
>     width: '100%',
>     backgroundColor: 'white'
>   },
> ```
> 
> which means that you can achieve what you expect if you pass following additional props to your style.
> 
> ```
> {
>     position: 'absolute',
>     height: '100%',
>     width: '100%',
> }
> ```
> 
> Hope this would be helpful for you.

This work well for me thank you

**Comment by RodolfoSilva** [comment]
Also add the `startInLoadingState`. To show the loading indicator in the first load!
