### ISSUE TITLE
Cookie in header not being sent on Android

### ISSUE THREAD

**Issue by baron816** [react-native-community/react-native-webview#1033]
**Bug description:**

Cookies are not being sent from Android. iOS works perfectly.

**To Reproduce:**

Exactly as described in the docs (except with a real url).

```javascript
const App = () => {
  return (
    <WebView
      source={{
        uri: 'https://www.google.com',
        headers: {
          Cookie: 'cookie1=asdf; cookie2=dfasdfdas',
        },
      }}
      sharedCookiesEnabled={true}
    />
  );
};
```

**Environment:**
 - OS: Android
 - OS version: 10.0
 - react-native version: 0.61.4
 - react-native-webview version:7.5.1

**Comment by leachjustin18** [comment]
I have also had the same issue on iOS too.  The only way I have been able to set cookies is through injectedJavaScript.

**Comment by leachjustin18** [comment]
I've had an issue with both iOS and Android.  I ended up setting the cookies through injectedJavaScript prop, but this would seem the more proper way to do it.

**Comment by 2linziyi2** [comment]
same

**Comment by 2linziyi2** [comment]
modify native code to fix the bug, find not sync the header's cookie

**Comment by jpodpro** [comment]
cookies on android have had this bug for at least a year and a half. see #631
