### ISSUE TITLE
WebViews with auto play video show in full screen 

### ISSUE THREAD

**Issue by harriot** [react-native-community/react-native-webview#1035]
**Bug description:** When the URL accessed has an autoplay video this is automatically shown full screen. Having tried the `mediaPlaybackRequiresUserAction` this stops the autoplay, however, it then doesn't even show within the web page.

**To Reproduce:**
Go to any URL via the webview that has an autoplay video.

**Expected behavior:**
To be able to pass props to disable, more specifically the `mediaPlaybackRequiresUserAction`

**Environment:**
 - OS: iOS
 - react-native version: 0.60.5
 - react-native-webview version: 7.0.1

**Comment by philipp65** [comment]
Please take a look at https://github.com/react-native-community/react-native-webview/blob/master/docs/Reference.md#allowsinlinemediaplayback

`allowsInlineMediaPlayback={true}` should do the trick

(Should be true by default imho)

**Comment by mikeyrt16** [comment]
Just to add to this. The html `video` tag needs to have `playsInline` applied to it too.

```
<video
  autoPlay
  playsInline
  src="https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-mp4-file.mp4"
/>
```

**Comment by MartinZemanik** [comment]
In my case setting `mediaPlaybackRequiresUserAction={true}` helped. even though the docs say that `true` is the default value.

**Comment by devth** [comment]
Even following all suggestions in this thread, the video still shows fullscreen in my app 🤔 

```tsx
          <WebView
            ref={(webView) => (webViewRef = webView)}
            sharedCookiesEnabled={true}
            allowUniversalAccessFromFileURLs={true}
            allowFileAccessFromFileURLs={true}
            allowFileAccess={true}
            startInLoadingState={true}
            renderLoading={LoadingSpinner}
            pullToRefreshEnabled={true}
            allowsBackForwardNavigationGestures={true}
            onContentProcessDidTerminate={() => webViewRef.reload()}
            mediaPlaybackRequiresUserAction={false}
            allowsInlineMediaPlayback={true}
            allowsFullscreenVideo={false}
            ...
          />
```

Video tag is:

```tsx
          <video
            style={{
              objectFit: "cover",
              position: "absolute",
              top: "0",
              left: "0",
              height: "100%",
              width: "100%",
            }}
            muted
            loop
            autoPlay
            playsInline
            disablePictureInPicture
            src="https://video.wixstatic.com/video/11062b_b109368ac4264b688d21b3e361372fb1/1080p/mp4/file.mp4"
          />
```

**Comment by devth** [comment]
Thanks @Crash-- . I downgraded to `11.21.2` but same problem. 🤔

**Comment by markerio** [comment]
I confirm what @devth has concluded! I'm using version 11.18.1

**Comment by k2xl** [comment]
Still an issue. Anyone figure this out?
`<video autoPlay loop muted playsInline>`

And yet it still is always fullscreen plays

```
      <WebView
        ref={webViewRef}
        allowsInlineMediaPlayback={true}
        allowsFullscreenVideo={ false }
        style={{ marginTop: 40 }}
```

**Comment by SliverYuki** [comment]
> Even following all suggestions in this thread, the video still shows fullscreen in my app 🤔即使遵循了此主题中的所有建议，视频仍然在我的应用程序中全屏显示🤔
> 
>           <WebView
>             ref={(webView) => (webViewRef = webView)}
>             sharedCookiesEnabled={true}
>             allowUniversalAccessFromFileURLs={true}
>             allowFileAccessFromFileURLs={true}
>             allowFileAccess={true}
>             startInLoadingState={true}
>             renderLoading={LoadingSpinner}
>             pullToRefreshEnabled={true}
>             allowsBackForwardNavigationGestures={true}
>             onContentProcessDidTerminate={() => webViewRef.reload()}
>             mediaPlaybackRequiresUserAction={false}
>             allowsInlineMediaPlayback={true}
>             allowsFullscreenVideo={false}
>             ...
>           />
> Video tag is:  视频标签为：
> 
>           <video
>             style={{
>               objectFit: "cover",
>               position: "absolute",
>               top: "0",
>               left: "0",
>               height: "100%",
>               width: "100%",
>             }}
>             muted
>             loop
>             autoPlay
>             playsInline
>             disablePictureInPicture
>             src="https://video.wixstatic.com/video/11062b_b109368ac4264b688d21b3e361372fb1/1080p/mp4/file.mp4"
>           />

I have the same problem, do you have any suggestions?
