### ISSUE TITLE
compileSdkVersion not specified

### ISSUE THREAD

**Issue by ldco2016** [react-native-community/react-native-webview#1043]
**Bug description:**

This error occurred after running `./gradlew clean`

```
Build file '/file/to/project/node_modules/react-native-webview/android/build.gradle' line: 26
    (No message provided)
    > org.gradle.api.internal.file.DefaultSourceDirectorySet.<init>(java.lang.String,org.gradle.api.internal.file.FileResolver,org.gradle.api.internal.file.collections.DirectoryFileTreeFactory)
    
    View exception
    A problem occurred configuring project :react-native-webview.
    compileSdkVersion is not specified.
```

**To Reproduce:**

https://github.com/ldco2016/RNapp

**Expected behavior:**

gradle should clean successfully

**Environment:**
 - OS:
 - OS version: MacOS 10.14
 - react-native version: 0.60.4
 - react-native-webview version: 5.12.1

**Comment by SuhairZain** [comment]
still searching for solutions

**Comment by EhteshamAnwar** [comment]
@ldco2016  how did you solve this error

**Comment by rpelorosso** [comment]
Has anybody been able to fix this?

**Comment by SuhairZain** [comment]
@EhteshamAnwar @rpelorosso  I got it fixed by upgrading to the latest version (9.4.0). I was on 6.0.2

**Comment by adifdwimaulana** [comment]
@SuhairZain @EhteshamAnwar @rpelorosso 

I solved this issue by clearing the cache and re-install react-native-webview. The steps shown as below:
1. reset cache
2. npm install react-native-webview --save
3. edit compileSdkVersion in build.gradle to 29 and buildToolsVersion to "29.0.3"
4. cd android && gradlew clean && gradlew build
5. run with react-native run-android

**Comment by Benzer1406** [comment]
Still happening on `10.3.1`

**Comment by GennadiyVSG** [comment]
Still happening on 10.3.2

**Comment by JoaoBGusmao** [comment]
not happening on 11.0.2

**Comment by xtianmpimbaza** [comment]
Still happening on 13.3.1

**Comment by 2Cubes** [comment]
Still happening!
