### ISSUE TITLE
WebView with Audio/Video permissions

### ISSUE THREAD

**Issue by TchernyavskyDaniil** [react-native-community/react-native-webview#1045]
Hey. 
We have a web-chat with video and audio communications. At the time of the call, permission requests occur. But just not in the web view. If you do the resolution of audio / video at the application level, then this of course will not help. If you call the method navigator.mediaDevices.getUserMedia ({audio: true, video: true}) through the injection of JS, then there is no result either (undefined). Does this library solve it somehow?

```
<CustomWebView
      originWhitelist={['*']}
      ref={webviewRef}
      allowsFullscreenVideo
      allowsInlineMediaPlayback
      heightDevice={height}
      source={{
        uri: 'https://webcamtoy.com/ru/',
      }}
    />
```

This is problem for Ios and Android, both platform

**Comment by afilp** [comment]
I cannot hear audio (HTML5) inside the WebView either. Is there a solution to this please? Thanks.

**Comment by divy-work** [comment]
Why are the developers ingnoring issues? Please provide an answer.

**Comment by Gabrielhvcardoso** [comment]
I'm having the same issue. Please provide an answer.

**Comment by Palayoub** [comment]
Any progress on this?

**Comment by divy-work** [comment]
Hey all, I solved this issue by using the `react-native-permissions` module. (I request the user everytime the root component is rendered but it shows only first time...works well)

Also don't forget to add permissions for Mic and Camera in AndroidManifest.xml.

**Comment by amsimoes** [comment]
@divy-work were you able to solve `getUserMedia` issue by asking CAMERA permission?

I've asked it using `expo-permissions` module to no avail, still appears this:
![MicrosoftTeams-image](https://user-images.githubusercontent.com/13181161/83672153-bc0bf380-a5cd-11ea-9c7c-256f87823dfe.png)

**Comment by vinaynarayankutty** [comment]
@amsimoes Got any solution ? For iOS the permissions are asking if I try to reload the site using `webviewRef.current.reload()`. But it's not working for android.
