### ISSUE TITLE
WebView loading URL but not loading ESRI map / map is blank

### ISSUE THREAD

**Issue by roseKQ** [react-native-community/react-native-webview#1048]
I am using the webview component in react native, it is working well except I can't load maps. The webview loads everything else on the page but not the mapping. The URL works in Chrome  and ESRI and loads the map properly. Do I need to enable something? Use the injectedJavascript prop? Any advice please?

Environment:
react-native-cli: 2.0.1
react-native: 0.59.8
react-native-webview@7.5.2

**Comment by mo7373** [comment]
Others have

**Comment by venkatakrishna7787** [comment]
I am also facing the same issue with mapBox, Other content is displaying except map, when i pinch in it is displaying the some title text but map is not displaying
