### ISSUE TITLE
Consider replacing iOS WKWebView with react-native-wbkwebview

### ISSUE THREAD

**Issue by KoenLav** [react-native-community/react-native-webview#105]
It doesn't seem like a good idea to redo all the work that has already been done here:

https://github.com/CRAlpha/react-native-wkwebview

We should probably get in touch with the author and see if they want to merge their efforts into this repository (or provide it as a submodule).

They have already implemented some of the changes I proposed in another PR (notably removing window.postMessage integration) as well: https://github.com/CRAlpha/react-native-wkwebview/commit/29588d4144940864126c689c4c400eb215f72adf

PR: https://github.com/react-native-community/react-native-webview/pull/104

@insraq @ruoyu-unity

**Comment by Titozzz** [comment]
We already got in touch with them:
https://github.com/CRAlpha/react-native-wkwebview/issues/191

I think it is also good to note this:
https://facebook.github.io/react-native/blog/2018/08/27/wkwebview

I think it's better to keep the whole code in one place. This package has been designed with the community participating in mind.

However, I would not want to force everyone to use a new version of the WKWebview, as it is supposed to be react-native's webview extracted on which we will iterate, and probably take back some parts from all the existing repository.
As a quick example, the solution to the bridge CRAlpha/react-native-wkwebview@29588d4 is not necessarly what we would implement over here.

I'm open to discuss this ! 😄

**Comment by KoenLav** [comment]
@Titozzz good to see! I didn't catch that.

I agree it would ideally be kept in one place, and it seems the author of the old package is willing to make that happen, so that's great!

With regard to the new iOS WebView; I assumed this repository would already be up to date with the new WKWebView from React Native?

It definitely seems sensible to extract the WKWebView from React Native first and then apply a selection of the fixes from react-native-wkwebview on top of that; I just noticed that some issues in this repository could already be fixed by changes made in that package, so thought I'd open up a wider discussion.

Maybe we can include a note about checking pre-existing WebView packages for fixes to issues in the issue reporting guidelines (which aren't setup yet)?

**Comment by Titozzz** [comment]
Okay sorry I was not clear, webview HAS BEEN extracted! Nothing will probably be merged on react-native side. (or would need to be it critical and would get pulled here too). I like the idea of adding the comment to check other packages to our non existing template (we really need one) ❤️ .

I'll keep this issue opened as a reminder !

**Comment by indapublic** [comment]
Hello. I'm using `react-native-wkwebview` in my project and once thing because I can't replace it with `react-native-webview` is not possible to share cookies between `fetch`/`react-native-cookies` and `react-native-webview` (look at `sendCookies` property). Was it done? Probably I do something wrong?

**Comment by jamonholmgren** [comment]
@indapublic We are working on it in https://github.com/react-native-community/react-native-webview/pull/175 -- once we release that, you should be able to share cookies between the two.

**Comment by indapublic** [comment]
@jamonholmgren Oh, glad to hear it! Thanks
