### ISSUE TITLE
iOS - WKWebView doesn't support 'set-cookie' headers in 302 redirect

### ISSUE THREAD

**Issue by liulianci** [react-native-community/react-native-webview#1053]
**Bug description:**

looks like WKWebView in iOS doesn't support 'set-cookie' headers in 302 redirect. android is woking fine

**Expected behavior:**

webView should pass cookies after a 302 redirect

**Environment:**
 - OS: iOS
 - OS version: 11.0 +
 - react-native version: 60.5
 - react-native-webview version: 7.4.2

**Comment by tonuegbu** [comment]
Having the same issue. Please what can be done to resolve this?

**Comment by liulianci** [comment]
@tonuegbu we have reverted back to v6.11.1 to use UIWebView instead

**Comment by tonuegbu** [comment]
okay. Thanks so much. @liulianci I'll do that and give you feedback.

**Comment by lannablue89** [comment]
same issue, I am using RN 0.61.2 and set-cookie not work in both v7.4.2 and v6.11.1 .  Anyway, can this issue fixed for WKWebView instead of using back deprecated UIWebView?

**Comment by arunraj-qburst** [comment]
This worked for me with v6.11.1

```
<WebView
          useWebKit={false}
          startInLoadingState
          onNavigationStateChange={this.onPagechange}
          thirdPartyCookiesEnabled={true}
          style={styles.container}
          source={{uri: endPoint.WEB_HOME_PAGE_URL}}
        />
```

**Comment by alejojonas** [comment]
:( is this still an issue? Cant get my cookies. Tried downgrading to v 6.11.1 also, no luck. Im using RN. 0.59.10

**Comment by safaiyeh** [comment]
@alejojonas To get cookies check out https://github.com/react-native-community/react-native-cookies.

**Comment by paulmasters** [comment]
I'm still seeing problems with this

**Comment by TommyLeong** [comment]
@paulmasters  I think as mentioned by @safaiyeh you will need to use [https://github.com/react-native-community/react-native-cookies](https://github.com/react-native-community/react-native-cookies)

Here's how you get all cookies for **iOS**
```
await CookieManager.getAll()
  .then((cookies) => {
    console.log('CookieManager.getAll =>', cookies);
  });
```

**Comment by TommyLeong** [comment]
@paulmasters  are you upgrading UIWebview to WKWebview and face issue with the token receive to call api?

**Comment by paulmasters** [comment]
@TommyLeong I've been doing some more digging and debugging with `@react-native-community/cookies` and a proxy.
It turns out problem is not caused by the redirect but by something else.

Some cookies are not being sent with the initial request, we have so many I missed it. 
It turns out that if a cookie has no `expires` property it does not get sent. 
If I give them an expiry with `@react-native-community/cookies` the cookie, they are sent.

Is this a known issue? If not I will raise a new one

**Comment by TommyLeong** [comment]
@paulmasters  Good finding on cookie has no `expires` will not be sent. How do you ensure this? Will you be able to share some findings on code/article? I'm not aware of this. But you seems right, my cookie does not come along with `expires`.

For me, I have to attach the Cookie value to HTTPHeaderField myself manually. Right now I have my code running well, with the cookie forward in request header.

**Comment by safaiyeh** [comment]
> @paulmasters  Good finding on cookie has no `expires` will not be sent. How do you ensure this? Will you be able to share some findings on code/article? I'm not aware of this. But you seems right, my cookie does not come along with `expires`.
> 
> 
> 
> For me, I have to attach the Cookie value to HTTPHeaderField myself manually. Right now I have my code running well, with the cookie forward in request header. 
> 
> 
> 
> 

Possibly, please create an issue on the cookies repo.

**Comment by TommyLeong** [comment]
> > @paulmasters  Good finding on cookie has no `expires` will not be sent. How do you ensure this? Will you be able to share some findings on code/article? I'm not aware of this. But you seems right, my cookie does not come along with `expires`.
> > For me, I have to attach the Cookie value to HTTPHeaderField myself manually. Right now I have my code running well, with the cookie forward in request header.
> 
> Possibly, please create an issue on the cookies repo.

@paulmasters  Are you able to confirm on this? and create the issue ticket?

**Comment by paulmasters** [comment]
@TommyLeong I am looking for a fix or work-around at the moment. It's not an issue with https://github.com/react-native-community/cookies. I can see the cookies with that. The problem is that they don't get sent with the request. I don't understand why - yet.
