### ISSUE TITLE
Playing video in fullscreen doesn't prevent screen from going to sleep

### ISSUE THREAD

**Issue by feiooos** [react-native-community/react-native-webview#1054]
**Bug description:**

When you play an inline video (like for example one from youtube.com), inside of a WebView, the screen never goes to sleep. As soon as we enter fullscreen, the screen locks after the specified timeout value set in the OS settings, on Android.
This is reproducible with youtube videos but not only.

I don't know if this is the way to do this or not but the only way I can fix this is by adding a `FLAG_KEEP_SCREEN_ON` in RNCWebViewManager.java whenever the fullscreen event is triggered.
I [add this flag in the onShowCustomView method](https://github.com/react-native-community/react-native-webview/blob/master/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java#L664) like so

```
mReactContext.getCurrentActivity().getWindow().setFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON, WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON)
```

and then [remove it in the onHideCustomView method](https://github.com/react-native-community/react-native-webview/blob/master/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java#L690) like so
```
mReactContext.getCurrentActivity().getWindow().clearFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON)
```

I'm not a native Android developer so I appreciate any kind of feedback in regards to a better solution :)

**To Reproduce:**

Run `npx react-native init` and load any youtube video inside of a WebView like so:
```
<WebView
  allowsFullscreenVideo
  source={{uri: 'https://www.youtube.com/watch?v=hL7qGkTZgwo'}}
  style={{flex: 1}}
/>
```

**Expected behavior:**

Whenever a video is in fullscreen, the screen shouldn't go to sleep for the whole duration of the video or until the user leaves the fullscreen view.

**Screenshots/Videos:**

**Environment:**
 - OS: Android
 - OS version: 10.0 (could be affecting more idk)
 - react-native version: 0.61.5
 - react-native-webview version: 7.5.2

**Comment by SnaiNeR** [comment]
Another question too, why screen **not** goes to sleep when  inline video is playing, why app not doing it like in another pages?

**Comment by feiooos** [comment]
This problem is still present in v9.4.0.
