### ISSUE TITLE
Webview on android with hardware acceleration white flash before render

### ISSUE THREAD

**Issue by krakz999** [react-native-community/react-native-webview#1057]
I'm using react-navigation's tab navigator to render 4 webviews on different tabs. Whenever I switch tab, the webview starts out as an empty white view for a split second before showing the actual content. (the webview is loaded already, if I navigate away and come back it blinks again initially)

The issue only happens when hardware acceleration is turned on, turning it off solved the blinking issue but the performance is unacceptable.

Environment:

OS: Android
OS version: 9.0
react-native version: 0.61.4
react-native-webview version: 7.5.1

**Comment by krakz999** [comment]
Installed flutter

**Comment by adamsaeid** [comment]
@krakz999 We have a similar set up to yours, with webviews inside tabs, and are also seeing a blink when navigating away and back to a screen with a webview.

I see you've closed this issue. Is this not actually an issue with the library? If not, did you find a solution?

**Comment by krakz999** [comment]
> @krakz999 We have a similar set up to yours, with webviews inside tabs, and are also seeing a blink when navigating away and back to a screen with a webview - but only when hardware acceleration is enabled
> 
> I see you've closed this issue. Is this not actually an issue with the library? If not, did you find a solution?

Hi. I developed the app natively without React Native.
