### ISSUE TITLE
the webview is changing StatusBar.StatusBarStyle

### ISSUE THREAD

**Issue by mydesweb** [react-native-community/react-native-webview#1059]
react-native-webview should never change StatusBarStyle automatically . On iOS I set StatusBar.setBarStyle('dark-content') as default for the screen but after a while (tap some links inside the webview) the StatusBarStyle is changed automatically to 'light-content'

 In older versions of react-native-webview I don't remember to see this kind of issue

**Comment by ruslanaplid** [comment]
I confirm
onMessage handler comming event.nativeEvent.data.type == 'win_height' and after StatusBarStyle changed automatically to 'light-content'
