### ISSUE TITLE
Support onShouldStartLoadWithRequest on Android

### ISSUE THREAD

**Issue by alebedev** [react-native-community/react-native-webview#106]
Please add `onShouldStartLoadWithRequest` support on Android.  react-native-webview-android has it, but built-in webview never had.  This causes developers to use different WebView libraries on different platforms

**Context**
I use WebView to display some static resources like license agreement, documentation, etc.  It's desirable to open links from those files in system browser rather than inside same webview.  Currently, the best way to do this is to use `onShouldStartLoadWithRequest`, return `false` and use `Linking` to open URL externally

**Comment by Titozzz** [comment]
You mean https://github.com/react-native-community/react-native-webview/pull/59 ..?

**Comment by maxammann** [comment]
Ok shit.. I really have to fix this soon :)

**Comment by malonguwa** [comment]
@maxammann @Titozzz hi guys~ thanks for looking after the project! Just want to ask when we can get the PR merged~~~ really need this feature~~

**Comment by Titozzz** [comment]
I've reviewed the PR!
