### ISSUE TITLE
What is the status of opacity:0.99 fix/workaround

### ISSUE THREAD

**Issue by vvusts** [react-native-community/react-native-webview#1063]
**Bug description:**
We want to remove opacity: 0.99 but not sure if this is fixed and don't want to hit users with bug if not fixed.

Once we discovered that on IOS webView make problem with other screens elements (make them white) and once we set opacity: 0.99 it worked.
Also this opacity fixed crashes on some android devices.

Now we have a problem on android 5 webView is there clickable HTML elements inside but it is blank/white.

If I remove opacity on android 5 it work.

**To Reproduce:**
Set webView style opacity: 0.99 and on android 5 it's blank.

**Expected behavior:**
WebView is visible on all phones without setting opacity.

**Environment:**
 - OS: Android
 - OS version: 5
 - react-native version: 0.60.5
 - react-native-webview version: 7.5.2

**Comment by 329530588** [comment]
Has the same issue. In Android 5, opacity 0.99 will make webview blank

**Comment by opeologist** [comment]
has this been resolved? or did it just get closed because of its staleness?

**Comment by shry325** [comment]
still searching for solutions
