### ISSUE TITLE
'React/RCTViewManager.h' file not found

### ISSUE THREAD

**Issue by pedromelo98** [react-native-community/react-native-webview#1064]
Hello!

**Bug description:**
I started to use pod in my project because i wanted to use react-native-qrcode-scanner with react-native-permissions and now I'm getting this error 'React/RCTViewManager.h' file not found I already fixed React(missing) from schemes and I don't know what I have to do to fix that error, could anyone help me please?

**Screenshots:**
<img width="264" alt="Captura de Tela 2019-12-05 às 15 04 47" src="https://user-images.githubusercontent.com/35875910/70261154-9c0b8c80-1770-11ea-8614-4a7cf180d8a2.png">

**Environment:**
 - OS: macOS Catalina
 - OS version:  10.15.1
 - react-native version: 0.61.5
 - react-native-webview version: ^5.11.0

**Comment by nayan27** [comment]
I don't know if a solution was found but i bumped into that same thing today.

Wanted to use WebView in project and so i started using cocoapods. I get the following errors while building for ios (haven't tried for android):

../node_modules/react-native-webview/ios/RNCWebViewManager.:8:9: fatal error: 'React/RCTViewManager.h' file not found

../node_modules/react-native-webview/ios/RNCWebView.:8:9: fatal error: 'React/RCTView.h' file not found

react: 16.6.3
react-native: 0.57.8
react-native-webview: ^8.1.0

My podfile looks like this:

platform :ios, '9.0'
target 'AreaRN' do
  use_frameworks!
  pod 'React', :path => '../node_modules/react-native', :subspcs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    #The following ones are the ones taken from 'Libraries' in XCode:
    'RCTAnimation',
    'RCTActionSheet',
    'RCTBlob',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]
  #The following dependancies are dependancies of React native itself
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/GLog.podspec'
  # Pods for AreaRN
  pod 'react-native-webview', :path => '../node_modules/react-native-webview'
end
# The following is needed to ensure the "archive" step works in XCode.
# It removes React from the Pods project, as it is already included in the main project.
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end


Thank you

**Comment by sachinsr-github** [comment]
facing the same issue.

**Comment by nix23** [comment]
Faced same issue on React Native 0.58.1. Fixed with following steps:
1) Rm react-native-webview from Podfile
2) Perform manual linking step 1 && 2 from following tutorial: https://reactnative.dev/docs/linking-libraries-ios
3) Build successfull

**Comment by timomeara** [comment]
why is this closed?
still happening

**Comment by tvelev92** [comment]
Having same issue

**Comment by chetankotkar** [comment]
Any Solution so far ???

**Comment by georgian3688** [comment]
Facing same issue ? Any solution.

**Comment by uripre** [comment]
Re-opened via another ticket: #1789
