### ISSUE TITLE
Keyboard overlaps on webview in android

### ISSUE THREAD

**Issue by ranshine** [react-native-community/react-native-webview#1065]
I am using this plugin. In ios it is working fine but in android keyboard overlaps on webview content. Webview contains inputbox at bottom of the screen like chat window. After clicking on input box keyboard coming on webview.

**Comment by clementoriol** [comment]
We have the same issue here.
The expected behavior would be the same as the standard Chrome, where the browser adds some padding to the bottom of the window, making sure the keyboard doesn't overlap on critical elements (like a submit button).

**Comment by clementoriol** [comment]
Actually using `KeyboardAvoidingView` (https://facebook.github.io/react-native/docs/keyboardavoidingview) and enabling it only for Android fixes this.

```

**Comment by abdurrehmaan** [comment]
Hi, I m facing the same issue, but not in react native, I m testing my web app on different devices using browserstack, and on android devices, when i use to add comment, keyboard overlaps the text field, How can I fix this issue in react js
![image](https://user-images.githubusercontent.com/29798155/211184173-fc5ef683-c7d3-414d-807e-193a92703602.png)

**Comment by tuanngocptn** [comment]
Hello @abdurrehmaan 

you can add `keyboardVerticalOffset={20}` prop in KeyboardAvoidingView 

That will fix your problem

**Comment by Satish789748** [comment]
Getting similar issue

**Comment by TheEhsanSarshar** [comment]
I see different behavior of webview on different devices, for some devices content goes behind the keyboard, and for some content goes on top of the keyboard. so adding KeyboardAvoidingView fix it for some devices but make a problem for other devices that already pushed the content up

**Comment by Pablo-DiazTassara** [comment]
I used KeyboardAvoidingView but added a container inside with the following styles:

`<KeyboardAvoidingView
  behavior={Platform.OS == "ios" ? "padding" : "height"}
  style={{ flex: 1 }}
>
  <SafeAreaView style={styles.contenedorView}>
      <WebView
        ...`


`const styles = StyleSheet.create({
contenedorView: {
justifyContent: "flex-start",
position: "relative",
flex: 1,},`

**Comment by TheEhsanSarshar** [comment]
if using expo. put this inside your `app.config.ts`

```
android: {
    softwareKeyboardLayoutMode: "pan"
}
```


not exactly sure if it's "pan" or "resize". you can try them 
it's a good practice to always set this value, otherwise, different Android devices will behave differently.
some render content behind the keyboard and some on top
