### ISSUE TITLE
How to handle a link that will force a certain file to be downloaded locally?

### ISSUE THREAD

**Issue by mydesweb** [react-native-community/react-native-webview#1074]
on Android after I visit a link that is forcing me to download locally a PDF for example I will see a network error in the web view because that link can't be actually opened.. but the file is downloaded locally on my phone.. and I don't have too much control , I would like to automatically open that file or go Back

**Comment by jamonholmgren** [comment]
@mydesweb Can you provide a repro so I can see this in action?

**Comment by mydesweb** [comment]
@jamonholmgren sure, I will send you in private the user and pass for a testing account so you can access the web app, is this fine?

**Comment by jamonholmgren** [comment]
@mydesweb Before you do that, does this happen when clicking on any PDF, or this particular PDF? Like, try it with some public PDF first maybe?

**Comment by mydesweb** [comment]
To better understand this special case:
1. open https://www.mydavy.ie/login.htm in the web view (or the web browser to better understand) OK
2. log in with the user: 786951 & pass: 5uper5ecure!2018
3. scroll down until you will see Download PDF or Download Excel , now when you will click on those links on Android you will receive an error .. on iOS is working fine.. the files will be downloaded locally on Android if you grant write permission anyway, but:
- I don't want to see that error
- it is difficult to handle go back in this case
- it would be nice to automatically open the file after download
4. please log out after you are done

**Comment by mydesweb** [comment]
@jamonholmgren I forgot to mention you

**Comment by mydesweb** [comment]
@jamonholmgren let me know if you managed to see the issue or you expect something from me

**Comment by mydesweb** [comment]
@jamonholmgren please see above the edited (completed flow) - please let me know if everything is clear now

**Comment by newseedit** [comment]
Hello @mydesweb ! I think that you might have to request the permission android.permission.WRITE_EXTERNAL_STORAGE in order to save files on android. You can try to add 
`<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />`
to AndroidManifest.xml and see if that makes any difference, or request the permission when the app launches the first time.

**Comment by mydesweb** [comment]
@newseedit The permission is requested and I am able do download and open the file, the issue is about an error that will be visible after you download the file.. react native web view will not handle correctly this case

**Comment by mydesweb** [comment]
there is any maintainer that can check and confirm the issue? for me this lib is almost useless with such an error on Android..

**Comment by salvariable** [comment]
Hi, I've been having this exact same issue for a month now. Did you find any fixes / alternatives @mydesweb ?

**Comment by mydesweb** [comment]
@salvariable unfortunately I didn't find any alternative, the good part is that the file is downloaded locally so I just set `renderError` prop to display nothing to the end user (I just ignore any error).. and is no control over what is downloaded..

**Comment by anija** [comment]
Same issue here. Works fine on ios but on Android the download starts automatically and the webview displays the error: Error loading page / Error Code: -1 / Description: net::ERR_FAILED

**Comment by gregoryfm** [comment]
Same error here

**Comment by salvariable** [comment]
still searching for solutions...

**Comment by odanicola** [comment]
@mydesweb hello, i think there's no solution yet from this case, so i put "onError={() => { this.webView.ref.goBack() }}" to get back to previous page after hitting the download page. 
Or maybe you can change the way to download the file to response type (jquery) on your web page so it won't direct to download page, but i haven't tried this yet. Any solutions if you found, please share.
