### ISSUE TITLE
React Native problem: WebView has been removed from React Native

### ISSUE THREAD

**Issue by andrewterex20190813** [react-native-community/react-native-webview#1075]
2

I built new React Native project yesterday using react-native-cli. But when running the project with my android phone, I got this error in red screen.

Invariant Violation: WebView has been removed from React Native. It can now be installed and imported from 'react-native-webview' instead of 'react-native'. See 'https://github.com/react-native-community/react-native-webview'.

I never used WebView and here is my "package.json".

{
  "name": "",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-image-slider": "^2.0.3",
    "react-native-svg": "^9.13.6",
    "react-navigation": "^4.0.10",
    "react-navigation-drawer": "^2.3.3",
    "react-navigation-stack": "^1.10.3",
    "react-redux": "^7.1.3",
    "redux": "^4.0.4"
  },
  "devDependencies": {
    "@babel/core": "^7.7.5",
    "@babel/runtime": "^7.7.6",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.9.0",
    "eslint": "^6.7.2",
    "install-peers": "^1.0.3",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.57.0",
    "react-native-gesture-handler": "^1.5.2",
    "react-native-reanimated": "^1.4.0",
    "react-test-renderer": "16.9.0"
  },
  "jest": {
    "preset": "react-native"
  }
}

I tried to fix this problem for a whole day but I couldn't. I just think 'react-native-gesture-handler' causes this problem. Anyone who has much experience of React-Native, please help me. Thank you.

**Comment by safaiyeh** [comment]
I built a fresh project with the provided `package.json` and did not get the error.

The error you mentioned occurs when you import WebView as

```JavaScript
import { WebView } from 'react-native';
```

ref: https://github.com/facebook/react-native/blob/dd8e5f468a29e299647ffbd0887f53afd24936e3/index.js#L506

This is most likely not an issue with this module.

**Comment by sumitduggal** [comment]
i have installed `v8.0.4` and `./lib/WebView.js` file is generated which has the following import statement which is causing the same problem.
`import { WebView } from 'react-native';`

can you please help.

**Comment by smakosh** [comment]
Webview has been moved to `react-native-webview`

**Comment by sumitduggal** [comment]
Highlighted `WebView.js` has the following code `import { WebView } from 'react-native';` as shown in the pic below

<img width="294" alt="Screen Shot 2020-01-23 at 9 56 18 pm" src="https://user-images.githubusercontent.com/5361378/72978828-3d3ac900-3e2b-11ea-8e64-4cc5d6ffbb10.png">

<img width="434" alt="Screen Shot 2020-01-23 at 9 57 17 pm" src="https://user-images.githubusercontent.com/5361378/72978914-5a6f9780-3e2b-11ea-8141-8e3939a81214.png">

**Comment by sumitduggal** [comment]
i have solved my issue, it was caused by one of the other dependencies i was using `react-native-qrcode`. This project is not maintained anymore so i move to using `react-native-qrcode-svg` and it solved the bug

**Comment by safaiyeh** [comment]
@sumitduggal thanks!
