### ISSUE TITLE
Cannot use Camera

### ISSUE THREAD

**Issue by ooo2003003v2** [react-native-community/react-native-webview#1076]
I am using a webview for my project but the camera inside the webview didnt works. I've enabled the app camera permission but the bower permission for the camera never shows up and  this was showed in my chrome debugger. 
{
message: "No video input devices found"
name: "NoVideoInputDevicesError"
}

However the camera works fine when I am using chrome. Can anyone fix it?

**Comment by yodaheis** [comment]
I just tested it with the latest version of this library for webrtc based video chat and camera works fine.
Please elaborate your environment info to help us understand better

**Comment by ooo2003003v2** [comment]
I've found the problem. Apparently I am using http instead of https. Even tho I have found another problem.
