### ISSUE TITLE
WebView on Android 4.3 fails to execute any injected Javascript

### ISSUE THREAD

**Issue by spaceye** [react-native-community/react-native-webview#108]
### Environment

React Native Environment Info:
System:
OS: macOS High Sierra 10.13.6
CPU: x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
Memory: 26.41 MB / 16.00 GB
Shell: 3.2.57 - /bin/bash
Binaries:
Node: 10.7.0 - /usr/local/bin/node
Yarn: 1.7.0 - /usr/local/bin/yarn
npm: 6.2.0 - /usr/local/bin/npm
Watchman: 4.9.0 - /usr/local/bin/watchman
SDKs:
iOS SDK:
Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
Android SDK:
Build Tools: 23.0.1, 26.0.1, 27.0.3
API Levels: 23, 26, 27
IDEs:
Android Studio: 3.1 AI-173.4819257
Xcode: 10.0/10A255 - /usr/bin/xcodebuild
npmPackages:
@lingui/react: 2.7.0 => 2.7.0
react: 16.5.0 => 16.5.0
react-native: 0.57.0 => 0.57.0
npmGlobalPackages:
react-native-cli: 2.0.1

### Description

Recent [changes](https://github.com/facebook/react-native/commit/e6b305b722a8f52fad8ac8bf9f95204fa2192944) that were carried over into this new repo broke execution of any injected Javascript (either via injectedJavaScript prop or manually via injectJavaScript method of the WebView on devices running on Android prior to 4.4.

Looking through the linked issues of the above mentioned commit, say [this one](https://github.com/facebook/react-native/issues/19611), javascript scheme RFC and Android implementation prior to 4.4 (see [issue](https://issuetracker.google.com/issues/36995865)) we can see that the following action is the culprit:

`loadUrl("javascript:" + URLEncoder.encode(script, "UTF-8"));`

This line will encode passed Javascript code for Android <= 4.3 and due to the latter's implementation of loadUrl that doesn't decode the scheme's text we end up with a problem.

In our application we need to grab loaded page's title and set it into our header in RN. Prior to 0.57.0 and the commit it worked without any issues.

As any injected Javascript is wrapped into self-executing anonymous function here:

`evaluateJavascriptWithFallback("(function() {\n" + injectedJS + ";\n})();");`

This is what goes to loadUrl:

`%28function%28%29+%7B%0Awindow.postMessage%28document.title%29%3B%0A%7D%29%28%29%3B
`
### Reproducible Demo

Setup your WebView with any correct value for injectedJavascript prop that would provide a feedback (console.log, data passed via onPostMessage, visible DOM manipulations, etc) on <=4.3 Android device / emulator.

So I suggest we remove the encoding bit from that line as it clearly messes up any passed Javascript.

**Comment by KoenLav** [comment]
I've noticed the same; using injectJavascript in the onLoad event works though!

**Comment by spaceye** [comment]
> I've noticed the same; using injectJavascript in the onLoad event works though!

I'm not sure how you were able to achieve that since:

1. JS side code dispatches command in _injectJavaScript_ method.

```
injectJavaScript = (data: string) => {
    UIManager.dispatchViewManagerCommand(
      this.getWebViewHandle(),
      UIManager.RNCWebView.Commands.injectJavaScript,
      [data],
    );
  };
```

2. Command is processed in Java side and `evaluateJavascriptWithFallback` is executed.

```
case COMMAND_INJECT_JAVASCRIPT:
        RNCWebView reactWebView = (RNCWebView) root;
        reactWebView.**evaluateJavascriptWithFallback**(args.getString(0));
        break;
```

3. It will still encode the passed string and mess any special chars, so even simple test like `window.document.body.innerHTML=null` will be turned into `window.document.body.innerHTML%3Dnull` and thus become invalid code.

```
protected void evaluateJavascriptWithFallback(String script) {
      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
        evaluateJavascript(script, null);
        return;
      }

      try {
        loadUrl("javascript:" + URLEncoder.encode(script, "UTF-8"));
      } catch (UnsupportedEncodingException e) {
        // UTF-8 should always be supported
        throw new RuntimeException(e);
      }
    }
```

So it makes me wonder whether you are sure you're running Android 4.3?

**Comment by KoenLav** [comment]
Ah, I'm sorry, I was definitely not testing on Android 4.3 (but it worked find in Android 8).

How is this issue specific to Android 4.3 though? I believe the code executed in 4.3 should be the same as in 8?

**Comment by KoenLav** [comment]
@spaceye I see, sorry for jumping to conclusions. I'm familiar with the javascript: scheme.

So I guess before 4.4 directly inserting Javascript into the WebView wasn't possible yet? Maybe worth confirming.

Your suggestion would be changing:

`loadUrl("javascript:" + URLEncoder.encode(script, "UTF-8"));`

to

`loadUrl("javascript:" + script);`

then?

**Comment by spaceye** [comment]
@KoenLav It's fine! I'm no expert in the question but as I see it prior to 4.4 scheme was the only way and so it was implemented as such. 4.4+ brought implementation change in `loadUrl` where it performed decoding so encoded string was expected and people had [issues.](https://github.com/facebook/react-native/commit/e6b305b722a8f52fad8ac8bf9f95204fa2192944). By the time it was [addressed](https://github.com/facebook/react-native/commit/e6b305b722a8f52fad8ac8bf9f95204fa2192944) new [evaluateJavascript](https://developer.android.com/reference/android/webkit/WebView#evaluateJavascript(java.lang.String,%20android.webkit.ValueCallback%3Cjava.lang.String%3E)) API method to execute Javascript was utilized for 4.4+ [available since API version 19 which is 4.4] but for older versions where `loadUrl` does not do the decoding encoding was still put in place.

So yes, my idea is that we should remove encoding for 4.3 and below.

Dank u wel!

**Comment by spaceye** [comment]
@Titozzz, @KoenLav any progress on this one? Thanks!

**Comment by jamonholmgren** [comment]
@spaceye Would you want to make a PR for this?

> So yes, my idea is that we should remove encoding for 4.3 and below.

This seems reasonable to me.
