### ISSUE TITLE
React Native webview doesn't load images

### ISSUE THREAD

**Issue by SimonRijn** [react-native-community/react-native-webview#1080]
I have the problem that my webview does not show images in the app. The strange thing is that sometimes an image is shown and sometimes not. If I click on a message that does not have a photo, it will display the content with any images, but not the main image.

**Photos under the code

App.js component.

```
const defaultUrl = 'https://www.gelrenieuws.nl/';

  render() {
    return (
          <Header style={{backgroundColor: 'white', zIndex: 99999999}}>
            <Body style={{flex: 1}}>
              <View style={styles.imageCenter}>
                <Image style={styles.imageLogo} source={logo} />
              </View>
            </Body>
            <Right style={{flex: 1}}>
              {this.state.loading ? <ActivityIndicator /> : null}
            </Right>
          </Header>
          <WebView
            ref="webViewGelreNieuws"
            source={{defaultUrl}}
            javaScriptEnabled
            domStorageEnabled
            allowFileAccessFromFileURLs
            startInLoadingState
            originWhitelist={['*']}
            mixedContentMode="compatibility"
          />
        </Container>
    );
  }
}
```

https://i.stack.imgur.com/xXNiu.jpg

https://i.stack.imgur.com/9cTcF.png

https://i.stack.imgur.com/c3DhW.jpg

**Comment by safaiyeh** [comment]
I looked into your issue with `react-native-webview@^7.6.0`. Could you confirm your react-native version and react-native-webview version?

```JavaScript
const defaultUrl = 'https://www.gelrenieuws.nl/'

const App = () => {
  return (
    <View style={{ height: '100%' }}>
      <StatusBar barStyle="dark-content" />
        <SafeAreaView />
        <WebView 
          source={{ uri: defaultUrl }}
          javaScriptEnabled
          domStorageEnabled
          allowFileAccessFromFileURLs
          startInLoadingState
          originWhitelist={['*']}
          mixedContentMode="compatibility"
        />
    </View>
  );
};
```

The images show up correctly.
<img width="402" alt="Screen Shot 2019-12-14 at 2 46 26 PM" src="https://user-images.githubusercontent.com/8675043/70855497-82f59080-1e80-11ea-904d-7a15d94bfe62.png">

**Comment by SimonRijn** [comment]
Hmm weird...

I'm using version 7.5.2 of react-native-webview.
I will try the 7.6 version. I'll let you know

**Comment by SimonRijn** [comment]
Well updated to version 7.6. It seemed to go well only when I opened the app the first four articles came with a photo and then I got some without ...

To come back to your previous question which version of react native I had. If I enter the command 'npm view react-native version' it says '0.61.5' for me. Does this match your version?
