### ISSUE TITLE
Invariant Violation: Element type is invalid: expected a string (for built-in components) 

### ISSUE THREAD

**Issue by AyushiBShah** [react-native-community/react-native-webview#1081]
**Bug description:**
App Crashing when trying to open web-view in release apk. Working fine in debug build.

**To Reproduce:**

**Expected behavior:**

**Screenshots/Videos:**

**Environment:**
 - OS: Android
 - OS version: 23
 - react-native version:0.61.5
 - react-native-webview version:7.5.2

**Comment by safaiyeh** [comment]
Could you give more information or an example of your implementation?

**Comment by AyushiBShah** [comment]
I am opening a Page from Side Bar using React Navigation. Code is as below, this seems to work fine in debug build but issue is being faced when apk is built in release mode.
 ```
render() {
        return (
            <Container>
                <Layout title={this.props.title}>
                    {/*<Content padder>*/}
                    {/*<View style={{height: Dimensions.get('window').height}}> /!*Needed for displaying web view*!/*/}
                    <WebView style={{
                        justifyContent: 'center',
                        alignItems: 'center',
                        flex: 1,
                        marginTop: (Platform.OS) === 'ios' ? 20 : 0
                        // height: Dimensions.get('window').height
                    }} ref="web" source={{uri: this.props.url}}
                             originWhitelist={['*']}
                             javaScriptEnabled={true}
                             onNavigationStateChange={this._onNavigationStateChange.bind(this)}
                             domStorageEnabled={true}
                             onError={console.error.bind(console, 'error')}
                    >
                    </WebView>
                    {/*</View>*/}
                    {/*</Content>*/}
                </Layout>
            </Container>
        )
    }
```

**Comment by YacovK** [comment]
I am getting the same Issue here . 

For me it is only occurs in release mode . 
when running in debug , the app work great . 

react-native 0.61.5
react-native-webview 8.1.2
android 9

I am getting : 
 E/unknown:ReactNative: Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.
    
    This error is located at:
        in t
        in t
        in RCTView
        in RCTView
        in Unknown
        in RCTView
        in AppContainer, stack:
    Ko@57:3287041
    <unknown>@57:3238546
    en@57:3248809
    ln@57:3253016
    Mo@57:3271244
    To@57:3268352
    To@-1
    Po@57:3267042
    Po@-1
    <unknown>@57:3226390
    unstable_runWithPriority@81:4110
    nr@57:3226337
    ar@57:3226272
    ko@57:3266034
    enqueueSetState@57:3232181
    setState@65:4419
    <unknown>@1:2902
    d@1:1954844
    <unknown>@1:1954629
    i@1:2242
    <unknown>@40:7393
    <unknown>@40:7420
    k@57:2764473
    j@57:2764838
    callImmediates@57:2766913
    callImmediates@-1
    value@57:2484121
    <unknown>@57:2482061
    value@57:2483797
    value@57:2482031
    value@-1
    value@-1

the only component on screen is the webview . 
when replacing it to a different component the app doesn't crash

**Comment by Devil-Cong** [comment]
same Issue +1
