### ISSUE TITLE
Invariant Violation: Tried to register two views with the same name RNCWebView

### ISSUE THREAD

**Issue by YanYuanFE** [react-native-community/react-native-webview#1083]
**Bug description:**
I Have a user read a web page (using a WebView Ive made) and then have a modal window where they need to add a signature use WebView.

Or to go even simpler I've put together this snack which shows the issue - hopefully it will make more sense with what im trying to do:

https://snack.expo.io/@trashpants/cfc43a

**To Reproduce:**
https://snack.expo.io/@trashpants/cfc43a

**Screenshots/Videos:**
https://user-images.githubusercontent.com/29092604/70743274-52deae00-1d17-11ea-9bb0-0ecc3c853d78.jpeg

**Comment by YanYuanFE** [comment]
Can a page contain two Webviews？

**Comment by hank121314** [comment]
Hi! @YanYuanFE  this issue caused by the react-native-webview in react-native-signature-canvas package.json version is not matched with your project package.json.

Change your package.json react-native-webivew version to react-native-signature-canvas's react-native-webview version will solve this issue.

**Comment by Dhanraj-bidchat** [comment]
Did you fixed it?
I am also facing same in RN:0.60.10

**Comment by IMRahulSaini** [comment]
Facing same issue
`"react-native": "0.61.5"`
`"react-native-webview": "^7.6.0"`

**Comment by LeonardodeLima** [comment]
issue here too
"react-native": "0.61.5"
"react-native-webview": "^8.0.0"

**Comment by hank121314** [comment]
If you are facing this issue, please check your dependencies. If some of your dependencies are using react-native-webview, you should match your react-native-webview version of them.
For example:
myproject package.json
```
{
  "dependencies": {
    "react-native-webview": "7.4.3",
    "react-native-signature-canvas": "^1.6.0"
  }
}
```
and
react-native-signature-canvas package.json
```
{
  "dependencies": {
    "react-native-webview": "^7.5.2"
  }
}
```
change myproject package.json to 
```
{
  "dependencies": {
    "react-native-webview": "^7.5.2",
    "react-native-signature-canvas": "^1.6.0"
  }
}
```
and  do yarn or npm install.
In IOS RN version >=60 you will need to do pod install.
After this, the issue should be resolved.

**Comment by safaiyeh** [comment]
Yup I encountered the something as @hank121314 with https://github.com/fusioncharts/react-native-fusioncharts.

Matching the WebView version does the trick.

**Comment by ranju691** [comment]
I have faced same problem, plz let me know if any solution found

**Comment by hardikshah197** [comment]
For **non-Expo applications**, the above-given solution does work out.
So, for ***react-native applications*** made in **ANDROID Studio** here is the solution:-

 - Replace your **react-native-linked** dependency version with its
   the latest version currently latest is **2.1.1** which gives this error,
   replace it with this link - [version][1]
   "https://github.com/xcarpentier/react-native-linkedin.git" along with
   required changes.
 - Delete and reinstall node_module.
 - After installing, either delete the **WEBVIEW** folder from
   "react-native-linked" in node_module manually or write the below the
   line in your script in the package.json file:
`"postinstall": "npx jetifier; patch-package; rm -rf ./node_modules/react-native-linkedin/node_modules/react-native-webview",
` after "start" key.

  [1]: https://github.com/xcarpentier/react-native-linkedin.git

**Comment by nandukalidindi** [comment]
Is matching the version across dependencies the only solution? If I happen to have two or more dependencies that bring in `react-native-webview` am I supposed to lookup for the package where versions across all the packages meet? I have seen multiple forums but was not able to find any solution.
