### ISSUE TITLE
mailto: and tel: links do not work in webview

### ISSUE THREAD

**Issue by cristianoccazinsp** [react-native-community/react-native-webview#1084]
**Bug description:**

If the page opened in the webview has any mailto: or tel: links, pressing them causes the webview to return the generic android page and fire the error events.

I believe the error is: `net::ERR_UNKNOWN_URL_SCHEME` (android) and `unsupported URL` (iOS)

Happens on both iOS and Android

**To Reproduce:**

Load any page with mailto and/or tel links. 

**Expected behavior:**

Other schemas should be working

**Screenshots/Videos:**

**Environment:**
 - OS: Android and iOS
 - OS version: 8.1, 10, 13.2.3
 - react-native version: 0.61.5
 - react-native-webview version: 7.6.0

**Comment by cham1985** [comment]
Hello, IOS can change the shouldstartloadforrequest method of RNCWebViewManager.m 
![image](https://user-images.githubusercontent.com/7087874/71434600-3895ce80-2720-11ea-9703-d79e6cd73e01.png)    It can be solved temporarily

**Comment by cham1985** [comment]
Android can change the shouldoverrideurlloading method of RNCWebViewManager.java, like this

**Comment by cham1985** [comment]
Hope to help you.

**Comment by Visakeswaran** [comment]
@cham1985 made the changes as mentioned, but it doesn't seem to work. My URL is something similar to 
**intent://user?screen_name=paul_kinlan#Intent;scheme=twitter;S.browser_fallback_url=https%3A%2F%2Ftwitter.com%2Fpaul_kinlan;end**

**Comment by Visakeswaran** [comment]
@cristianoccazinsp did you find any work around ?

**Comment by cristianoccazinsp** [comment]
@Visakeswaran  not really, I just handled the links case by case with the `onShouldStartLoadWithRequest` prop and something like this:

```
function onShouldStartLoadWithRequest(request){

  // short circuit these
  if (!request.url ||
    request.url.startsWith('http') ||
    request.url.startsWith("/") ||
    request.url.startsWith("#") ||
    request.url.startsWith("javascript") ||
    request.url.startsWith("about:blank")
  ) {
    return true;
  }

  // blocked blobs
  if(request.url.startsWith("blob")){
    Alert.alert("Link cannot be opened.");
    return false;
  }

  // list of schemas we will allow the webview
  // to open natively
  if(request.url.startsWith("tel:") ||
    request.url.startsWith("mailto:") ||
    request.url.startsWith("maps:") ||
    request.url.startsWith("geo:") ||
    request.url.startsWith("sms:")
    ){

    Linking.openURL(request.url).catch(er => {
      Alert.alert("Failed to open Link: " + er.message);
    });
    return false;
  }

  // let everything else to the webview
  return true;
}
```

**Comment by AstroCorp** [comment]
Error loading page
Domain:
Error code: 0
Description: Redirection to URl with a scheme that is not HTTP(S)

**Comment by cristianoccazinsp** [comment]
Still an issue. The above work around is not that bad, perhaps a docs update could do it.

**Comment by sbycrosz** [comment]
Does this still work? We found that when we open an `intent://` link, `onShouldStartLoadWithRequest` prop is not called anymore (An error `Can't open url: intent://xxx` is displayed instead)

It used to work on 5.x.x 😢

**Comment by sbycrosz** [comment]
Update:

We found that we need to add `originWhitelist={['http://*', 'https://*', 'intent://*']}` so that `intent://` link can be handled with `onShouldStartLoadWithRequest` (Note that mailto/tel/geo/etc. would likely have the same problem)

The commit with breaking changes: https://github.com/react-native-community/react-native-webview/commit/0442126

**Comment by trinhvanminh2009** [comment]
> Update:
> 
> We found that we need to add `originWhitelist={['http://*', 'https://*', 'intent://*']}` so that `intent://` link can be handled with `onShouldStartLoadWithRequest` (Note that mailto/tel/geo/etc. would likely have the same problem)
> 
> The commit with breaking changes: [0442126](https://github.com/react-native-community/react-native-webview/commit/0442126)

Does not work

**Comment by dragonlong206** [comment]
Even when I added "intent://*" to whitelist, it still cannot open url intent://xxxx. Is there anyone has solution for this issue?

**Comment by MrAlekhin** [comment]
Yes, the same

**Comment by dragonlong206** [comment]
We must work around by putting the "intent://" link in a webpage. The app opens the webpage on browser first and then user taps the link to open another app.

**Comment by PeagaOS** [comment]
Any updates on it? I am having the same issue.

    "**react-native**": "0.63.2"
    "**react-native-webview**": "^10.10.2"

When I try to open a link who directs the user to dialling, this is what happens to the app:

![Captura de Tela 2020-11-19 às 10 23 00](https://user-images.githubusercontent.com/70170206/99671720-354eb400-2a51-11eb-86ff-9ac33a1435c2.png)

**Comment by abhijithvijayan** [comment]
@PeagaOS @dragonlong206 @MrAlekhin Did any of you figured out a fix for this?

**Comment by albertsaenz** [comment]
> Any updates on it? I am having the same issue.
> 
> ```
> react-native: "0.63.2"
> react-native-webview: "^10.10.2"
> ```
> 
> When I try to open a link who directs the user to dialling, this is what happens to the app:
> 
> ![Captura de Tela 2020-11-19 às 10 23 00](https://user-images.githubusercontent.com/70170206/99671720-354eb400-2a51-11eb-86ff-9ac33a1435c2.png)

I have the same problem, did you solve it?

**Comment by anonewb** [comment]
replace `originWhitelist={[*]}` with `originWhitelist={['http://*', 'https://*', 'intent://*']}`

**Comment by albertsaenz** [comment]
I have this error, even placing this originWhitelist={['http://*', 'https://*', 'intent://*']}

shows phone options, but error screen continues.
I currently have it fixed using: onError={()=> webViewRef.current.goBack() } , but I don't like this solution.
![photo5006302271100791049](https://user-images.githubusercontent.com/13897873/108408884-37a8e180-71eb-11eb-912c-35b18cf43f3e.jpg)

**Comment by aamay001** [comment]
> > @Visakeswaran not really, I just handled the links case by case with the `onShouldStartLoadWithRequest` prop and something like this:
> > ```
> > function onShouldStartLoadWithRequest(request){
> > 
> >   // short circuit these
> >   if (!request.url ||
> >     request.url.startsWith('http') ||
> >     request.url.startsWith("/") ||
> >     request.url.startsWith("#") ||
> >     request.url.startsWith("javascript") ||
> >     request.url.startsWith("about:blank")
> >   ) {
> >     return true;
> >   }
> > 
> >   // blocked blobs
> >   if(request.url.startsWith("blob")){
> >     Alert.alert("Link cannot be opened.");
> >     return false;
> >   }
> > 
> >   // list of schemas we will allow the webview
> >   // to open natively
> >   if(request.url.startsWith("tel:") ||
> >     request.url.startsWith("mailto:") ||
> >     request.url.startsWith("maps:") ||
> >     request.url.startsWith("geo:") ||
> >     request.url.startsWith("sms:")
> >     ){
> > 
> >     Linking.openURL(request.url).catch(er => {
> >       Alert.alert("Failed to open Link: " + er.message);
> >     });
> >     return false;
> >   }
> > 
> >   // let everything else to the webview
> >   return true;
> > }
> > ```
> 
> This still crashed webview for me.
> 
> But, luckily [this commit](https://github.com/react-native-webview/react-native-webview/commit/aaf788169b53e5d5a0a892dbef8f4e23fbcb98a9) released with [11.0.0](https://github.com/react-native-webview/react-native-webview/commit/aaf788169b53e5d5a0a892dbef8f4e23fbcb98a9) features a new option `setSupportMultipleWindows`, which when set to `true` opens links that open in new tabs/windows (such as `<a target="_blank">`) will now prompt to open in the system browser, rather than re-using the current WebView.
> 
> ```
> <WebView
> 	// links that open in new tabs/windows will now prompt to open in the system browser
>     setSupportMultipleWindows={true}
> 	// other props here
>   />
> ```
> 
> So, once enabled the flag(default set to true), make the link open in a new tab
> 
> ```
> <a target="_blank" rel="nofollow noreferrer noopener" href="tel:+91xxxxxxxxx">Call now</a>
> ```
> 
> Update: if changing `target` is not a viable option, I suggest adding some fallbacks when error is thrown
> 
> ```
> const webViewRef = React.useRef(null);
> 
> <WebView
>   ref={webViewRef}
>   setSupportMultipleWindows={true}
>   onError={({nativeEvent}) => {
>               // Function that is invoked when the WebView load fails.
>               if (nativeEvent.url.startsWith('tel:') && nativeEvent.canGoBack) {
>                 // Fallback for tel links without target="_blank"
>                 webViewRef.current.goBack();
>               }
>            }}
> />
> ```

Adding the onError to handle the tel links worked for me.

**Comment by ansalspurtree** [comment]
After updating to 11.0.0 my issue resolved thanks team

**Comment by wennaspeedy** [comment]
> > const webViewRef = React.useRef(null);
> > 
> > <WebView
> >   ref={webViewRef}
> >   setSupportMultipleWindows={true}
> >   onError={({nativeEvent}) => {
> >               // Function that is invoked when the WebView load fails.
> >               if (nativeEvent.url.startsWith('tel:') && nativeEvent.canGoBack) {
> >                 // Fallback for tel links without target="_blank"
> >                 webViewRef.current.goBack();
> >               }
> >            }}
> > />
> > ```
> 

I have this issue also with 11 version. This workaround works for me.

**Comment by natemartins** [comment]
> @Visakeswaran not really, I just handled the links case by case with the `onShouldStartLoadWithRequest` prop and something like this:
> 
> ```
> function onShouldStartLoadWithRequest(request){
> 
>   // short circuit these
>   if (!request.url ||
>     request.url.startsWith('http') ||
>     request.url.startsWith("/") ||
>     request.url.startsWith("#") ||
>     request.url.startsWith("javascript") ||
>     request.url.startsWith("about:blank")
>   ) {
>     return true;
>   }
> 
>   // blocked blobs
>   if(request.url.startsWith("blob")){
>     Alert.alert("Link cannot be opened.");
>     return false;
>   }
> 
>   // list of schemas we will allow the webview
>   // to open natively
>   if(request.url.startsWith("tel:") ||
>     request.url.startsWith("mailto:") ||
>     request.url.startsWith("maps:") ||
>     request.url.startsWith("geo:") ||
>     request.url.startsWith("sms:")
>     ){
> 
>     Linking.openURL(request.url).catch(er => {
>       Alert.alert("Failed to open Link: " + er.message);
>     });
>     return false;
>   }
> 
>   // let everything else to the webview
>   return true;
> }
> ```

This worked for me in opening mailto links. 👍

**Comment by demedos** [comment]
> @Visakeswaran not really, I just handled the links case by case with the `onShouldStartLoadWithRequest` prop and something like this:
> 
> ```
> function onShouldStartLoadWithRequest(request){
> 
>   // short circuit these
>   if (!request.url ||
>     request.url.startsWith('http') ||
>     request.url.startsWith("/") ||
>     request.url.startsWith("#") ||
>     request.url.startsWith("javascript") ||
>     request.url.startsWith("about:blank")
>   ) {
>     return true;
>   }
> 
>   // blocked blobs
>   if(request.url.startsWith("blob")){
>     Alert.alert("Link cannot be opened.");
>     return false;
>   }
> 
>   // list of schemas we will allow the webview
>   // to open natively
>   if(request.url.startsWith("tel:") ||
>     request.url.startsWith("mailto:") ||
>     request.url.startsWith("maps:") ||
>     request.url.startsWith("geo:") ||
>     request.url.startsWith("sms:")
>     ){
> 
>     Linking.openURL(request.url).catch(er => {
>       Alert.alert("Failed to open Link: " + er.message);
>     });
>     return false;
>   }
> 
>   // let everything else to the webview
>   return true;
> }
> ```

Please note that this won't work on the iOS simulator, but will on the physical device.

**Comment by kranthi1216** [comment]
Hi 
i am trying load url intent://app.....................
set originWhitelist={['http://*', 'https://*', 'intent://*']} like this 
sdk version is 30
receiving unknown url scheme
please help me?

**Comment by jeynergil** [comment]
How do we resolve this?
I am getting this error when using the iPhone simulator but it works in iPhone 6 device.

<img width="349" alt="Screenshot 2022-06-16 at 11 35 35 PM" src="https://user-images.githubusercontent.com/231434/174107201-8c686cc0-b285-4ee8-80c3-8e913bac946f.png">

**Comment by johhansantana** [comment]
I fixed it by adding 

```javascript
originWhitelist={[
                    "http://*",
                    "https://*",
                    "intent://*",
                    "tel:*",
                    "mailto:*"
                ]}
```

and 

```javascript
onError={event => {
                    webViewRef.current?.goBack();
                }}
                onNavigationStateChange={event => {
                    if (
                        event.url !==
                        "your original url here"
                    ) {
                        webViewRef.current?.stopLoading();
                        Linking.openURL(event.url);
                    }
                }}
```

**Comment by jhzzzz** [comment]
> I fixed it by adding
> 
> ```js
> originWhitelist={[
>                     "http://*",
>                     "https://*",
>                     "intent://*",
>                     "tel:*",
>                     "mailto:*"
>                 ]}
> ```
> 
> and
> 
> ```js
> onError={event => {
>                     webViewRef.current?.goBack();
>                 }}
>                 onNavigationStateChange={event => {
>                     if (
>                         event.url !==
>                         "your original source uri here"
>                     ) {
>                         webViewRef.current?.stopLoading();
>                         Linking.openURL(event.url);
>                     }
>                 }}
> ```

i made minor changes, this worked:

```
onError={(event) => {
  webviewRef.current?.goBack()
  if (event.nativeEvent.url.indexOf('mailto:') > -1) {
    Linking.openURL(event.nativeEvent.url)
  }
}}
```

**Comment by zaghadon** [comment]
> > I fixed it by adding
> > ```js
> > originWhitelist={[
> >                     "http://*",
> >                     "https://*",
> >                     "intent://*",
> >                     "tel:*",
> >                     "mailto:*"
> >                 ]}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and
> > ```js
> > onError={event => {
> >                     webViewRef.current?.goBack();
> >                 }}
> >                 onNavigationStateChange={event => {
> >                     if (
> >                         event.url !==
> >                         "your original source uri here"
> >                     ) {
> >                         webViewRef.current?.stopLoading();
> >                         Linking.openURL(event.url);
> >                     }
> >                 }}
> > ```
> 
> i made minor changes, this worked:
> 
> ```
> onError={(event) => {
>   if (event.nativeEvent.url.indexOf('mailto:') > -1) {
>     webviewRef.current?.goBack()
>     Linking.openURL(event.nativeEvent.url)
>   }
> }}
> ```

I made further changes to accommodate other protocols.

```javascript
onError={(event) => {
            const url = event.nativeEvent.url;
            if (
              url.startsWith('intent://') ||
              url.startsWith('tel:') ||
              url.startsWith('mailto:')
            ) {
              webViewRef.current?.goBack();
              Linking.openURL(url);
            }
          }}
```

**Comment by jgarplind** [comment]
I ran into this thread when trying to support `tel:`-links, but didn't manage to get things working with the suggestions here.

What did (very cleanly) work for me, was to:
1. Add the non-https-scheme to `originWhitelist`, e.g. `originWhitelist={["https://*", "tel:*",]}`, and then
2. Use [onShouldStartLoadWithRequest](https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#onshouldstartloadwithrequest) to intercept the link opening (would otherwise navigate to an error state), and handle it similar to how it was suggested above (`Linking.openURL` etc.).

My full `onShouldStartLoadWithRequest`-handler looks something like this:
```
const supportedNonHttpsSchemes = ["tel:"];
```
```
onShouldStartLoadWithRequest={(request) => {
  // Intercept supported non-https links and open in external app
  const scheme = supportedNonHttpsSchemes.find((s) => request.url.startsWith(s));
  if (scheme) {
    Linking.openURL(request.url).catch(() => {
      Alert.alert(
        "Cannot open link",
        `No app is available to handle ${scheme} links.`,
      );
    });
    // Handled, should not proceed to normal navigation
    return false;
  }
  // Unhandled, navigate as normal
  return true;
}}
```

Some relevant source code can be found here: https://github.com/react-native-webview/react-native-webview/blob/5bc526fce5b9d6225df183bdf3d8cf542007d90a/src/WebViewShared.tsx#L40

Hopefully this is useful for someone.
