### ISSUE TITLE
No ServiceWorker management in Webview on IOS 12+

### ISSUE THREAD

**Issue by MonsieurBuffle** [react-native-community/react-native-webview#1086]
**Bug description:**

I have an application built with Expo which needs to use serviceWorker within Webviews.
I used to handle this with basic Webviews from React Native which had the possibility to specify usage of **WKWebview** or **UIWebview**. 
By default on IOS, **UIWebview** was used and serviceWorker worked well since IOS 11.3 or 11.4

I upgraded Expo and React Native versions until I had to migrate to **react-native-webview**.
Since I did, serviceWorker stopped working on IOS 12+.

It appears that in the navigator spawned by react-native-webview, **navigator.serviceWorker is undefined.**
I found [a pretty old post on Webkit site](https://webkit.org/blog/8090/workers-at-your-service/) (with an update) specifying that:

> Update: A previous version of this post stated the Service Worker API is available in all applications using WKWebView. At this time it is only available in Safari, applications that use SFSafariViewController, and web applications saved to your home screen.

- does react-native-webview use SFSafariViewController or something else ?
- if it's not already there, will react-native-webview provide a way to use ServiceWorker in an IOS app ?
- Am I missing something ?

**To Reproduce:**

1. Start an Expo Project with react-native-webview deps
2. Add a Webview component opening this URL https://jakearchibald.github.io/isserviceworkerready/
3. Launch your app in an IOS Simulator
4. In your app, scroll to navigator.serviceWorker and click on "Test" link
5. You'll be redirect to a test page with this following result meaning that serviceWorker is not defined : 
`navigator.serviceWorker, `

**Expected behavior:**
Having ServiceWorker working in Webviews within IOS app. 
Following steps, having this as result :
` navigator.serviceWorker, [object ServiceWorkerContainer]`

**Environment:**
 - OS: IOS
 - OS version: 12+ (probably 11.4+, 12 and 13 tested)
 - react-native version: 0.59+
 - react-native-webview version: 7.0.5, 7.4.3 (installed with expo command on sdk 35 and 36), 8.0.1

**Comment by safaiyeh** [comment]
@MonsieurBuffle this module uses WKWebView for iOS, I do not believe it is possible to use service works with it.

**Comment by MonsieurBuffle** [comment]
@safaiyeh Maybe you know why it's not possible to make it work ? 
Sorry I'm trying to understand :) 

 The waiting for the support of ServiceWorker for iOS(11.3) was long and finally it came through. I mean, a lot of people were waiting for it and I think this is somehow an important feature.
Do you know if there is a way that ServiceWorker will work in the future with react-native-webview ?

**Comment by edsonayllon** [comment]
Any updates on this?

**Comment by somasekharkakarla** [comment]
Any update on service worker?

**Comment by Stevemoretz** [comment]
Still not working 2021. :)

**Comment by mrnerdhair** [comment]
Apparently, Apple has decided that little people don't get service workers; you need the `com.apple.developer.WebKit.ServiceWorkers` entitlement -- which is only usable locally because they won't let anything with it into the app store -- or the `com.apple.developer.web-browser` entitlement, which is for people designing apps intended to be replacement default web browsers, and which has other [baggage](https://developer.apple.com/documentation/xcode/preparing-your-app-to-be-the-default-browser-or-email-client) attached like not being able to use Universal Links.

**Comment by GuySerfaty** [comment]
It's possible with [App-Bound Domains](https://webkit.org/blog/10882/app-bound-domains/) & [limitsNavigationsToAppBoundDomains](https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#limitsnavigationstoappbounddomains) = true
