### ISSUE TITLE
Composed wrong temp file name

### ISSUE THREAD

**Issue by OleksandrKucherenko** [react-native-community/react-native-webview#1088]
**Bug description:**

https://github.com/react-native-community/react-native-webview/blob/7ba1bc5129fd71b7291f07538671ea36af0aab63/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewModule.java#L380

instead of the `filename` should be used variable `prefix`.

reasoning:
- `File.createTempFile` compose name file with path: `dir + prefix + timestamp + suffix`
- `filename`is actually `prefix + timestamp + suffix` - so we repeat the same operations again.

**Comment by safaiyeh** [comment]
@OleksandrKucherenko could you make a PR for this?
