### ISSUE TITLE
Android hard crash with blob:// links

### ISSUE THREAD

**Issue by cristianoccazinsp** [react-native-community/react-native-webview#1090]
**Bug description:**

Getting a hard crash on Android (see log below) when the webview tries to open a blob link. 

In addition, the `onShouldStartLoadWithRequest ` prop is not called which I'm also using to stop blob links from even running.

```
java.lang.IllegalArgumentException Can only download HTTP/HTTPS URIs: blob:https://app.zinspector.com/b20a08ad-41c7-4d93-bd14-2280b9d96d2c 
    DownloadManager.java:614 android.app.DownloadManager$Request.<init>
    RNCWebViewManager.java:199 com.reactnativecommunity.webview.RNCWebViewManager$2.onDownloadStart
    PG:537 sV.a
    PG:25 aHF.handleMessage
    Handler.java:106 android.os.Handler.dispatchMessage
    Looper.java:164 android.os.Looper.loop
    ActivityThread.java:7000 android.app.ActivityThread.main
    Method.java:-2 java.lang.reflect.Method.invoke
    RuntimeInit.java:441 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run
    ZygoteInit.java:1408 com.android.internal.os.ZygoteInit.main
```

**To Reproduce:**

Test the webview with any page that as a blob download.

**Expected behavior:**

First, it shouldn't crash with a blob:// link. Secondly, at least `onShouldStartLoadWithRequest ` should be called so we can prevent the link from running.

**Screenshots/Videos:**

**Environment:**
 - OS: Android
 - OS version: 8.1, 9, 10
 - react-native version: 0.61.5
 - react-native-webview version: 7.6.0

**Comment by manuelabarca** [comment]
The same issue but only in Android, when return blob link the webview crash and close this.

**Comment by vpankov** [comment]
same issue

**Comment by vpankov** [comment]
Not a bug fix but I hope that it will be helpful.

I used webView **postMessage** api, to send params from web application to native application and downloaded files using 

- **rn-fetch-blob** for Android, 
- **rn-fetch-blob**, **react-native-fs**, **react-native-share** for iOS.

**1. Web application side** (if you haven't access for web app code, you can try to use injectedJavaScript for this)
1.1 Check is `window.ReactNativeWebView` exists to verify that it's native app context and prevent crashing for regular web browsers.
1.2 Send data that you need to process api from native app, using `window.ReactNativeWebView.postMessage` 
1.3 "return null" to prevent blob link processing in webview
Summary:
`  if (window.ReactNativeWebView) {
     window.ReactNativeWebView.postMessage(
      JSON.stringify({
        type: 'meeting',
        url: URL + `/calendar-events/${eventId}/ics/`,
        token: getToken().access_token,
        eventId,
      }),
    );
    return null;
  }`

2. Native App side
2.1 Pass onMessage callback to WebView props
`<WebView
source={{ uri: url }}
onMessage={
//this.onMessage 2.2
}>
</WebView>
`
2.2 Writing onMessage callback (in my case I have different events so used switch case) nativeEvent - data, that we prepared on point 1.

`  onMessage = async ({ nativeEvent }) => {
    const data = JSON.parse(nativeEvent.data);
    switch (data.type) {
     case 'meeting': {
     // 2.3 downloading blob files section
     break;
    }
  }
}
`
2.3 For ios and android we will use different ways, so we need to check Platform
`if (Platform.OS === 'android')
 {//2.4 Android downloading}
else {//2.5 iOS Downloading}`

2.4 Android downloading

- Check and request permissions for files downloading
- Setup configs for RNFetchBlob to set it to download mode (Download folder in my case and file id, that I passed from web app)
- Pass fetch url and headers (In my case Authorization was required)
- Notification that operation completed

`            request(PERMISSIONS.ANDROID.WRITE_EXTERNAL_STORAGE).then(result => {
              RNFetchBlob.config({
                fileCache: true,
                path: `${RNFetchBlob.fs.dirs.DownloadDir}/sb-event-${data.eventId}.ics`
              }).fetch('GET', data.url, {
                "Authorization": "Bearer " + data.token
              })
              .then((res) => {
                Alert.alert("Download Success !");
              })
              .catch((errorMessage, statusCode) => {
              })
            });`
2.5 iOS downloading
- Send fetch request
- Cache downloaded file
- Download it with share api
- Clear file from cache
`            RNFetchBlob
            .config({
              fileCache: true,
              path: RNFetchBlob.fs.dirs.DocumentDir + `/sb-event-${data.eventId}.ics`
            })
            .fetch('GET', data.url, {
              "Authorization": "Bearer " + data.token
            }).then(async (res) => {

              // the temp file path
              if (res && res.path()) {
                const filePath = res.path()
                let options = {
                  type: 'application/ics',
                  url: filePath
                }
                await Share.open(options)
                await RNFS.unlink(filePath)
              }
            })`
----------------------
**used libraries**
import { request, PERMISSIONS } from 'react-native-permissions';
import { WebView } from 'react-native-webview';
import { Alert } from 'react-native';
import RNFetchBlob from 'rn-fetch-blob';
import RNFS from 'react-native-fs';
import Share from 'react-native-share';

**Comment by cristianoccazinsp** [comment]
Although the above is a nice workaround, this is still an issue and can't be worked around like that all the time (e.g., a google maps viewer). Not looking for a definite solution, but at least a try/catch in the native code would be awesome.

**Comment by cristianoccazinsp** [comment]
Please re-open, this is still happening :(

**Comment by Alb93** [comment]
Same problem here

**Comment by jasongaare** [comment]
Also seeing this issue

**Comment by jasongaare** [comment]
opened as new PR here: https://github.com/react-native-community/react-native-webview/pull/1546
