### ISSUE TITLE
Copy content in webview if source from html String

### ISSUE THREAD

**Issue by NinhPhamHai** [react-native-community/react-native-webview#1091]
hello!
i have String html like this:
 <p>Trong 100g ức gà sống có: <br>Tổng 120 kcal<br>✅ Nước: 74g<br>✅Chất béo (fat): 2.62g<br>✅ Tinh bột (Carb): 0g<br>✅ Chất đạm (Protein): 22.5g</p>
    <figure class="wp-block-image"><img src="http://123.30.169.57:8000/wp-content/uploads/2019/12/an-gi-hom-nay.jpg" alt="" class="wp-image-1435" srcset="http://123.30.169.57:8000/wp-content/uploads/2019/12/an-gi-hom-nay.jpg 843w, http://123.30.169.57:8000/wp-content/uploads/2019/12/an-gi-hom-nay-150x150.jpg 150w, http://123.30.169.57:8000/wp-content/uploads/2019/12/an-gi-hom-nay-300x300.jpg 300w, http://123.30.169.57:8000/wp-content/uploads/2019/12/an-gi-hom-nay-768x768.jpg 768w" sizes="(max-width: 843px) 100vw, 843px" /></figure>
and i set this for webview:
<WebView
          originWhitelist={['*']}
           source={{html:""+sourceWebView}} style={[Styles.itemText6, {textAlign: 'justify'}]}
             />
When my app run, webview render exactly what i want, but i can't select text, select all ...
please help me

**Comment by dinhsuu** [comment]
I can copy 1 text on android, but can't copy the whole text. And on iOS, it's ok
