### ISSUE TITLE
Webview using html source, disappear after reloading.

### ISSUE THREAD

**Issue by blueberry6401** [react-native-community/react-native-webview#1092]
**Bug description:**
My webview using html text as source, after calling reload, the content disappear.

**To Reproduce:**
```
<WebView
                source={{
                    html: '<h1>AAAAAA</h1>',
                }}
                ref={this.refWebView}
            />
this.refWebView.reload(); // And gone!
```

**Expected behavior:**
Page is reloaded, not disappeared.

**Environment:**
 - OS: iOS
 - OS version: 13.3
 - react-native version: 0.61.5
 - react-native-webview version: 8.0.1

**Comment by blueberry6401** [comment]
Hiiiiiiiiii, anyone here  :(

**Comment by zhangbaoshuai** [comment]
请问这个问题是怎么解决的呢？

**Comment by blueberry6401** [comment]
> 请问这个问题是怎么解决的呢？

For the time being, workaround way is force Webview to reload by changing the key props. Hope this will be fixed soon.
