### ISSUE TITLE
InjectedJavascript before content loaded.

### ISSUE THREAD

**Issue by congnt171** [react-native-community/react-native-webview#1093]
Hi, I have try injectedJavascript startup javascript for website. But if i using injectedJavascript, the js load when content loaded. I try using new prop injectedJavaScriptBeforeContentLoaded js was not even added.
How can i do it? 
Thanks!
P/S: I'm using Expo SDK36 with react-native-webview 8.0.1 in package.json
I have testing on real device android and ios and simulator both platform.

**Comment by danielgoulding** [comment]
I have the same issue. Is there a work around?
