### ISSUE TITLE
injectedJavaScriptBeforeContentLoaded is not work for android

### ISSUE THREAD

**Issue by innocces** [react-native-community/react-native-webview#1095]
**Bug description:**
injectedJavaScriptBeforeContentLoaded is work fine in IOS, but not work for android

**Expected behavior:**
every point is work fine

**Environment:**
 - OS: macOS
 - OS version: 10.15.2
 - react-native version: 0.60.4
 - react-native-webview version: 8.0.1

**Comment by ch-jung** [comment]
so do I. In expo sdk 35, both were normal. I'm changing source related <code>postMessage</code> in expo sdk 36. It is on ios, but still not working on android.

OS: macOS
OS version: 10.14.6
react-native version: 0.61.5 (expo36)
react-native-webview version: 7.4.3

**Comment by stephanebachelier** [comment]
Same here for this environment : 

OS: macOS
OS version: 10.14.6
react-native version: 0.61.5
react-native-webview version: 8.0.2

**Comment by xxf1110** [comment]
Same here for this environment 
OS: android
OS verison: android 9
react version: 16.9.0
react-native version: 0.61.5
react-native-webview version: 8.0.3

**Comment by panda0603** [comment]
same here. any update?

**Comment by omidshafai** [comment]
same here too!
OS: android
OS version: android 9
react-native version 0.61.5
react-native-webview version 8.1.2

**Comment by denwilliams** [comment]
Same issue here. 
Doesn't look like it is implemented for Andoid. Can only see iOS source files, so maybe the issue is just that it needs to be documented as iOS only??

https://github.com/react-native-community/react-native-webview/search?q=injectedJavaScriptBeforeContentLoaded&unscoped_q=injectedJavaScriptBeforeContentLoaded

But there is an implementation for Android for injectedJavaScript

https://github.com/react-native-community/react-native-webview/search?l=Java&q=injectedJavaScript

**Comment by kkw10** [comment]
Same here for this environment
OS: android
OS verison: android 9
react version: 16.9.0
react-native version: 0.61.5
react-native-webview version: 9.0.1

**Comment by marcokernler** [comment]
Same here...
OS: android
OS version: android 9
react version: 16.9.0
react-native version: 0.61.5
react-native-webview version: 8.1.2

**Comment by TylerNRobertson** [comment]
Still an issue....

**Comment by embray** [comment]
Ditto here.  Anyone have any idea how I could capture an window.onload event without this on Android?

**Comment by RWOverdijk** [comment]
Guess I'll throw in my +1 as well.

**Comment by Aure77** [comment]
Any update for Android impl ?

**Comment by rajorpratyush** [comment]
Any update

**Comment by ArvindNikam76** [comment]
any update

**Comment by birdca** [comment]
any update

**Comment by rajorpratyush** [comment]
It works with new version give it a try

**Comment by RWOverdijk** [comment]
When Github starts grouping your "Any update" comments, you know it's maybe time to start using emoji responses and +1.

This was added [here](https://github.com/react-native-community/react-native-webview/commit/ac4e05e0f2a206d662f136244efd03fa05c3425c).

@jamonholmgren Can you do your thing with this issue?

**Comment by ArvindNikam76** [comment]
> It works with new version give it a try

thank you, it's working in latest version.
