### ISSUE TITLE
Webview on android very slow

### ISSUE THREAD

**Issue by MelMayssonOwen** [react-native-community/react-native-webview#1098]
**Bug description:**
I've upgraded my app to the latest rn version (61.4) and did the same for the webview package. Speed has improved significantly on IOS (it's amazing!) but It's ridiculously slow (think a couple of seconds for a heavy website compare to instant on IOS) on Android (release and debug). It may even be even slower than before on android.

What could be causing this?

**To Reproduce:**
A clean project with a webview to a page like facebook

**Expected behavior:**
Same speed between IOS and Android

**Environment:**
 - OS: Android
 - OS version: 21+
 - react-native version: 61.4
 - react-native-webview version: 8.0.1

**Comment by nakinthorn** [comment]
no one answer your post,
i dont know why ?

**Comment by IZSkiSurfer** [comment]
I have exactly the same problem - no clue

**Comment by Davidzhu001** [comment]
why close it?

**Comment by KrifaYounes** [comment]
always the same problem....

**Comment by Davidzhu001** [comment]
Is this repo still maintaining by anymore

**Comment by ajitsing** [comment]
I am also facing the same issue. Is there any solution for it?

**Comment by Pranit-Harekar** [comment]
I'm facing the same issue. Any update? Is there any way we can help?

**Comment by odeyatwi** [comment]
for me it helped to remove androidHardwareAccelerationDisabled property
and add            
androidLayerType with 'none' or 'hardware'

**Comment by fungmo** [comment]
+1

**Comment by gtfunes** [comment]
Same issue here, anyone have any ideas?

**Comment by garce99** [comment]
to me helped the property androidLayerType with 'none' or 'hardware' when i run `yarn start`, but when i create the apk in android studio the same problem appear, help please

**Comment by Kristinn-Thor** [comment]
I was experiencing the same thing. For me the problem occurred when using the WebView in modal stack-screen (i'm using react-navigation 5.9.3). But when using the WebView in non-modal stack-screen the performance was great.

**Comment by cweise** [comment]
I also have the problem that the following website https://shop.schrammek.de/ can hardly be used in the WebView. Also changing androidLayerType, cache etc did not bring any change. Are there any other solutions?

**Comment by maxmann74** [comment]
Am also noticing this issue. We have an Expo hybrid app on the android and ios stores that use webview. IOS performance seems good, but the webview on Android is about twice as slow to load pages in webview. If you open the same site on Chrome on the same android device it's way faster.
