### ISSUE TITLE
iOS - I can't zoom out view after click on input inside webview.

### ISSUE THREAD

**Issue by osvald0** [react-native-community/react-native-webview#110]
I have a react-native app that render a webchat (Microsoft webchat). It was working fine until the last apple iOS update. I've changed the WebView component and now I'm using react-native-webview but issues persists. When I click on input the view zoom in to insert the text but the zoom persist after sent the content. Also after the keyboard hide a blank space is show.
(Please check screenshot)

OSX
node: v8.11.3
react: 16.6.0-alpha.8af6728
react-native: 0.57.3
react-native-webview: 2.5.0

![img_0014](https://user-images.githubusercontent.com/20977158/47525387-80e30380-d873-11e8-9cd4-ad1a65ba8fa5.PNG)

![img_0012](https://user-images.githubusercontent.com/20977158/47525385-80e30380-d873-11e8-8a99-156b1d12e9dc.PNG)

![img_0013](https://user-images.githubusercontent.com/20977158/47525386-80e30380-d873-11e8-9d76-4a1acf0577de.PNG)

Thanks!

**Comment by krishan1kamal** [comment]
Same problem any body please help on that

**Comment by Titozzz** [comment]
https://stackoverflow.com/questions/26295277/wkwebview-equivalent-for-uiwebviews-scalespagetofit would that help ?

**Comment by osvald0** [comment]
@krishan1kamal Where did you use this code? I couldn't found any workaround yet 😭

**Comment by krishan1kamal** [comment]
Hey @osvald0 you can update to 0.57.4 and it's removed

**Comment by osvald0** [comment]
I've updated to 0.57.5 and the issue persist 😔

**Comment by vitorreis** [comment]
I'm also suffering with this problem since the migration to this package... would be cool to have this as part of the package, since the previous implementation would already handle this with the scalesPageToFit property

**Comment by Titozzz** [comment]
WKWebview does not have such property, but if you find a solution, please provide a PR

**Comment by hwth** [comment]
Same problem. Does anyone have the solution?

**Comment by hwth** [comment]
I found the solution to solve this error. I edited the source code in [RNCUIWebView.m](https://github.com/react-native-community/react-native-webview/blob/master/ios/RNCUIWebView.m#L47) to change the scroll view insets setting from **UIScrollViewContentInsetAdjustmentNever** to **UIScrollViewContentInsetAdjustmentAutomatic**.
If you use WKWebView, you have to change the same. I don't ensure that this will not raise any another errors, but it works for me.

**Comment by osvald0** [comment]
Hi, @hwth , thank for your comment but the workaround didn't work for me :(

**Comment by Titozzz** [comment]
Have you tried playing with tags like https://github.com/react-native-community/react-native-webview/issues/447#issuecomment-477201365?

**Comment by fekajin** [comment]
same issue :(

**Comment by eag-synechron** [comment]
Facing same issue

**Comment by awatt-cox** [comment]
I'm also having this issue. My webview loads a url that contains a text input. When a user clicks on the text input, the view zooms in. When the user leaves the text input, the page is still zoomed in, which causes the webview to scroll horizontally. Please let me know if there is a fix for this.

**Comment by awatt-cox** [comment]
Based on @fekajin response, this worked for me:

render() {
    const iosZoomFix = "const meta = document.createElement('meta'); " +
        "meta.setAttribute('content', 'width=device-width, initial-scale=1, maximum-scale=1, user-scalable=1'); " +
        "meta.setAttribute('name', 'viewport'); " +
        "document.getElementsByTagName('head')[0].appendChild(meta); " +
        "true; ";
    return (
      <WebView
        style={styles.webview}
        ref={this.refName}
        startInLoadingState={true} // this can cause problems in Android. Leaving here for now.
        source={{ uri: this.currentUrl }}
        javaScriptEnabledAndroid={true}
        automaticallyAdjustContentInsets={true}
        renderError={this.renderError}
        onNavigationStateChange={this.navigationStateChange}
        injectedJavaScript={injectedJS}
        key={this.state.key}
      />
    );
  }

**Comment by bkitduy** [comment]
> automaticallyAdjustContentInsets={true}

not work for me :(

**Comment by ChrisL108** [comment]
@awatt-cox 

I had an issue with an iframe within a WebView not detecting the smaller screen size, on iOS only (this was for an embedded dashboards through Domo). The meta tag used here fixed this for me.
Thanks!

**Comment by potatoengineer** [comment]
```
    const iosZoomFix = "const meta = document.createElement('meta'); " +
        "meta.setAttribute('content', 'width=device-width, initial-scale=1, maximum-scale=1, user-scalable=1'); " +
        "meta.setAttribute('name', 'viewport'); " +
        "document.getElementsByTagName('head')[0].appendChild(meta); " +
        "true; ";
```
did not work for me. when I dismiss the keyboard, the zoom pans the right side of my input fields partially clipped out of view instead of restoring original state.
