### ISSUE TITLE
net::ERR_CACHE_MISS on Android 5.0 and 5.1

### ISSUE THREAD

**Issue by kylesziv** [react-native-community/react-native-webview#1101]
**Bug description:**
When using Expo 35, react-native-webview 7.4.3, and Android 5.1 an error appears when the uri is defined as "https://www.google.com". The error is "Error Loading Page" and has a description of "net::ERR_CACHE_MISS". 

**To Reproduce:**
Create a new expo 35 or 36 project and install react-native-webview@7.4.3. Add WebView to the page with a uri of https://www.google.com. An error will appear saying "Error loading Page" and "net::ERR_CACHE_MISS".

**Expected behavior:**
The page should load inside of the WebView. This works perfectly on Android 6, 7, 8, 9, etc.

**Screenshots/Videos:**
![image](https://user-images.githubusercontent.com/1623963/71550026-4acc7280-2995-11ea-8947-245d15456cdf.png)

**Environment:**
 - OS: Android
 - OS version: 5.1
 - react-native version: 0.59 (bundled with expo)
- expo version: 35
 - react-native-webview version: 7.4.3

**Comment by Magrider** [comment]
same issue.
I upgrade expo 35 to 36, which forces me to use react-native-webview. 
Working fine on IOS, but show ERR_CACHE_MISS on android.

please help.

**Comment by Magrider** [comment]
> same issue.
> I upgrade expo 35 to 36, which forces me to use react-native-webview.
> Working fine on IOS, but show ERR_CACHE_MISS on android.
> 
> please help.

I just ran expo on my real device with no problem. I was developing on Nox android simulator, I think this problem only happen on virtural device?

**Comment by kylesziv** [comment]
No this was on a real device.

**Comment by Magrider** [comment]
Is this happen on Expo app client? 
I got this issue on expo Client: 2.14.0, but no this kind of issue on expo client 2.13.0

**Comment by bilalyaqoob** [comment]
Hi i am also getting this error. can you please tell me the solution.
"sdkVersion": "36.0.0",
"expo": "~36.0.0",
"react-native": "https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz",
"react-native-webview": "^8.0.2",

Encountered an error loading page, Object {
  "canGoBack": false,
  "canGoForward": false,
  "code": -1,
  "description": "net::ERR_CACHE_MISS",
  "loading": false,
  "target": 3193,
  "title": "",
  "url": "https://facebook.github.io/react-native/",
}

**Comment by Samide47** [comment]
the same problem on Android 5.1 (Real device) no error in IOS or <=7 Android 
"react-native-webview": "^7.4.3",
 "expo": "~36.0.0",
"react": "~16.9.0",

**Comment by safaiyeh** [comment]
https://stackoverflow.com/questions/30637654/android-webview-gives-neterr-cache-miss-message

Provides a couple fixes. Try setting this permission verbatim how it is spelt here:

**Comment by Samide47** [comment]
> https://stackoverflow.com/questions/30637654/android-webview-gives-neterr-cache-miss-message
> 
> Provides a couple fixes. Try setting this permission verbatim how it is spelt here:
> `<uses-permission android:name="android.permission.INTERNET"/>`
> 
> Otherwise we would need a check to disable caching for JellyBean
> 
> ```
> if (18 < Build.VERSION.SDK_INT ){
>     //18 = JellyBean MR2, KITKAT=19
>     mWeb.getSettings().setCacheMode(WebSettings.LOAD_NO_CACHE);
> }
> ```

what about Expo ??

**Comment by safaiyeh** [comment]
I’m not familiar with Expo, can you investigate that?

**Comment by Samide47** [comment]
I wonder why no one is responding to this issue, it's a big one Webview is one of the most important components and it's not working on Android 5.1 when using Expo
should we regret using Expo or what ??

**Comment by blvesman** [comment]
Any solution?

**Comment by vascofg** [comment]
Facing the same issue

**Comment by diogojefs** [comment]
same problem here.

**Comment by pawel3ala** [comment]
ha, just stumbled across this problem

**Comment by Tinku0** [comment]
same problem here lets all cry here

**Comment by Beissner** [comment]
Has anyone found a solution to this? Everything was working fine on Android before updating to Expo SDK 36. Now images and videos aren't rendering in `react-native-webview`.

**Comment by mateusfg7** [comment]
same problem

**Comment by kudah99** [comment]
same problem here

**Comment by Ihvanmp** [comment]
same problem here,

**Comment by nielsvanspauwen** [comment]
same problem

**Comment by hypnotic-frog** [comment]
Seems to be an Android problem they just fixed. Check...
https://github.com/expo/expo/issues/6665#issuecomment-571623759

No luck until expo upgrades to androidx.appcompat:appcompat:1.2.0.   :-/

**Comment by aviveyal** [comment]
same problem here

**Comment by grunch** [comment]
Facing the same issue, in my case on Android 10 with expo app

```
  "dependencies": {
    "expo": "~37.0.3",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz",
    "react-native-web": "~0.11.7",
    "react-native-webview": "8.1.1"
  },
```

**Comment by odeke** [comment]
same problem here

**Comment by NeliHarbuzava** [comment]
I'm facing this issue with some sites, but with some other webview works well with cache. I'm thinking that this is maybe some site settings that don't allow to cache it (news sites for ex.)

**Comment by khanh-it** [comment]
same problem, Genymotion - Google Nexus 7 - Android 5.1.0
Encountered an error loading page, Object {
  "canGoBack": false,
  "canGoForward": false,
  "code": -1,
  "description": "net::ERR_CACHE_MISS",
  "loading": false,
  "target": 23,
  "title": "Webpage not available",
  "url": "https://www.google.com",
}

**Comment by 026binit** [comment]
looking for solutions 

expo sdk :- 39
plaform :- Android 5.1.1

**Comment by alejoasotelo** [comment]
same problem on Android 5.1

**Comment by testime007** [comment]
EXPO team, you have to push the fix ASAP, waiting from long time.........

**Comment by testime007** [comment]
This is causing issues in production had issue with android 5.0, team release the fix ASAP

**Comment by MakMoinee** [comment]
same issue.

**Comment by celsodevelop** [comment]
Same issue here
