### ISSUE TITLE
hello, how can i change the title of the alert message? it's coming written javascript

### ISSUE THREAD

**Issue by raphaelluiz128** [react-native-community/react-native-webview#1105]
hello, how can i change the title of the alert message? it's coming written javascript

**Comment by aabhatnagar050988** [comment]
what is the solution to it ?

**Comment by SachinPal8050101** [comment]
what is solution for this @aabhatnagar050988  @raphaelluiz128

**Comment by aabhatnagar050988** [comment]
@SachinPal8050101 solution to it is to go native, you need to override the prompt behaviour in android on iOS it works fine https://stackoverflow.com/questions/38053779/android-webview-how-to-change-javascript-alert-title-text-in-android-webview this is the solution

**Comment by wilav-dev** [comment]
Is there any solution without overriding library native code?

**Comment by jja08111** [comment]
It's good to override library code but we need solution without overriding library code.
