### ISSUE TITLE
iOS - Buttons don't work.

### ISSUE THREAD

**Issue by osvald0** [react-native-community/react-native-webview#111]
Buttons inside a webview don't work. This functionality was working fine using react-native Webview.

Webview code:

```
<WebView
    useWebKit={true}
    ref={(ref) => { this.webview = ref; }}
    source={{ uri }}
    style={{ marginTop: 0 }}
    onNavigationStateChange={(event) => {
        if (!event.url.includes(tonaAreaUrl)) {
            this.webview.stopLoading();
            Linking.openURL(event.url);
        }
    }}
/>
```

OSX
node: v8.11.3
react: 16.6.0-alpha.8af6728
react-native: 0.57.3
react-native-webview: 2.5.0

Thanks!

**Comment by Titozzz** [comment]
What button are you talking about ?

Are you sure just changing the import to `import { WebView } from 'react-native'` changes how the code above works ?

**Comment by osvald0** [comment]
I'm talking about any button inside the webview.
I open any web using Linking in a new browser instance instead of the webview if the url in not the first url rendered.

**Comment by Titozzz** [comment]
Have you tried with the original import ?

**Comment by osvald0** [comment]
Yes, It works with the original import but I have another issue with that. When click on input to insert a text the current text that I'm writing is not show. Its occurs with each inputs.

**Comment by jamonholmgren** [comment]
@osvald0 Would you be able to publish a minimal app recreating this issue, so we can clone it down and see for ourselves?

**Comment by osvald0** [comment]
Sorry, I can reproduce the issue only if I use the JS code commented in the following post: https://github.com/react-native-community/react-native-webview/issues/110.
I'll close the issue. Thanks!

**Comment by meiqi1992** [comment]
same issue！ click button in webview but it can not navigae next page！
