### ISSUE TITLE
InjectJavascript or postMessage isn't work on Android (but iOS is works!)

### ISSUE THREAD

**Issue by ch-jung** [react-native-community/react-native-webview#1110]
When I using Expo SDK35, all is well. but upgrading Expo SDK36, and I'm changing source related <code>postMessage</code>. It is working on iOS, but Android is abnormal.

The Flow is message is sent from the webView to the app, and the app that receives the message passes the token. In the webView that receives the token, the business logic is executed afterwards. 

OS: macOS
OS version: 10.14.6
react-native version: 0.61.5 (expo36)
react-native-webview version: 7.4.3

I migrated to the URL below. 
https://github.com/react-native-community/react-native-webview/issues/809#issuecomment-547695298
```
function _postMessage() {
  const generateOnMessageFunction = (data) => 
     `(function() {
      window.dispatchEvent(new MessageEvent('message', {data: ${JSON.stringify(data)}}));
  })()`;

  webView.injectJavaScript(generateOnMessageFunction(message));
}
```

And This is part of source.
```
// app.js (RN)
<WebView
     ref={view => (this.webView = view)}
     source={{
       uri: this.state.endpoint
     }}
     onMessage={this._onMessage}
     useWebKit={true} 
     onNavigationStateChange={this._injectedToken}         // first of all, I injected a token
     startInLoadingState={true}
     renderLoading={this._activityIndicatorLoadingView}
/>

_onMessage = async event => {
    const receiveData = JSON.parse(event.nativeEvent.data);

    if (receiveData.action === "logout") {
      this.props._onLogoutToApp();
    } else if (receiveData.action === "token") {
      const token = await this.props._onTokenFromApp();
      _postMessage(this.webView, token);      // this is migrate guide source
    }
};
``` 

```
// web.js (WEB source)
...

function init(){
  var jsonData = {"action": "token", "type": "string"}; 
  _postMessage(JSON.stringify(jsonData), "*");
}

function _postMessage(message, target){
  (window["ReactNativeWebView"]||window).postMessage(message, target);
}

...
```

**Comment by congnt171** [comment]
Expo using react-native-webview 7.4.3. So something will not run.

**Comment by ch-jung** [comment]
@congnt171 you mean.. this issue is version issue? if I update from 7.4.3 to over 8, all problem is gone?

**Comment by infazA** [comment]
Just use one parameter...
It works on both iOS and Android.

Example : 

`window.ReactNativeWebView.postMessage("Hello React");`

**Comment by AdityaKotamraju** [comment]
Any update on the above issue, calling injectJavaScript in android ?
react-native version: 0.61.2
react-native-webview version: 8.0.2

**Comment by aperomingo** [comment]
Any update?

This problem exists from 5.0.1 version... 
What happen? `window.postMessage()` was deprecated since then, that's OK, but his supposed solution is to use `window.ReactNativeWebView.postMessage()` but both are always **undefined** (`window.postMessage()` and `window.ReactNativeWebView`).

So, how can I send data from **WebView to React Native**?

**Comment by aperomingo** [comment]
This solution is for send data from **WebView** to **React Native**

SOLVED WITH **setTimeout** function on Web (JS) side using next function:

WEB:
```
setTimeout(() => {
    window.ReactNativeWebView &&
      window.ReactNativeWebView.postMessage(
        JSON.stringify({ type: "token", data: "kbadsfi74ty59y47934875v93ruhfekrt983457" })
      );
  }, 0);
```

REACT NATIVE:
```
<WebView
          ref={ref => (this.webview = ref)}
          source={{ uri: DASHBOARD_URL }}
          onNavigationStateChange={this.handleWebViewNavigationStateChange}
          onMessage={this.handleOnMessage}
          renderLoading={() => this.renderLoading()}
          startInLoadingState
          incognitotimes
        />

handleOnMessage(event) {
    const { type, data } = JSON.parse(event.nativeEvent.data)
    if (type === "token") {
      console.log('token', data)
    }
  }
```

In my opinion, this is horrible and the unique solution i have found.

Good luck.

**Comment by flikQ** [comment]
Still looking for a solution

**Comment by ali27001** [comment]
the problem continues

**Comment by rikschennink** [comment]
Had the same issue. Needed to remove the `*` to make it work on Android.


```js
// Post message from WebView to React Native
window.ReactNativeWebView.postMessage('hello world');

// Listen in WebView for messages received from React Native
const handleMessage = (event) => {
  const message = event.data;
  alert(message);
}

// For Android
document.addEventListener('message', handleMessage);

// For iOS
window.addEventListener('message', handleMessage);
```

**Comment by 349989153** [comment]
For me, just comment some code in `node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java` like:
```java
    protected void evaluateJavascriptWithFallback(String script) {
// comment the following lines
//       if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
//         evaluateJavascript(script, null);
//         return;
//       }

      try {
        loadUrl("javascript:" + URLEncoder.encode(script, "UTF-8"));
      } catch (UnsupportedEncodingException e) {
        // UTF-8 should always be supported
        throw new RuntimeException(e);
      }
    }
```

and then the bug has gone....

**Comment by 349989153** [comment]
I don't understand, why I call `evaluateJavascript` on UiThread, and still no luck to fix it ?

Accroding to [evaluateJavascript doc:](https://developer.android.com/reference/android/webkit/WebView#evaluateJavascript(java.lang.String,%20android.webkit.ValueCallback%3Cjava.lang.String%3E)) 
**This method must be called on the UI thread and the callback will be made on the UI thread.**

So I change `node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java` like:
```java
import com.facebook.react.bridge.UiThreadUtil;

      case COMMAND_INJECT_JAVASCRIPT:
        RNCWebView reactWebView = (RNCWebView) root;
//         reactWebView.evaluateJavascriptWithFallback(args.getString(0));
        UiThreadUtil.runOnUiThread(new Runnable() {
                @Override
                public void run() {
                  root.evaluateJavascript(args.getString(0), null);
                }
            });
        break;
```

It expected to fix this problem but in fact it doesn't.
I don't get it, how to make `webview.evaluateJavascript` work? 
All we can do is just calling `loadUrl`?
