### ISSUE TITLE
Support multi view instances like a browser

### ISSUE THREAD

**Issue by binhndicts** [react-native-community/react-native-webview#1111]
**Bug description:**
We are trying to make a simple browser using the module but I found some problems on iOS:
- `shouldStartLoadForRequest` use a single lock condition. If 2 RNCWebview instances call the method, the previous call will always get `YES` with a warning "Did not receive response to shouldStartLoad in time, defaulting to YES"
- `createWebViewWithConfiguration` will work incorrect in sites that need google or github login like https://app.gitbook.com/login. In the site, a parent window wants to create a child window (by window.open) for authentication, and then close it after login success (by window.close).

**Comment by binhndicts** [comment]
Sorry, I think it's not a **bug report** but **feature request**. Anybody helps me change its label, please?

**Comment by tmaly1980** [comment]
@binhndicts Did you ever find a solution? I'd like to have a more universal fix for window.open/close as well. I can't control third party sites that use popups (ie facebook login), and I don't always have control over timing - sometimes window.open/close is put in <head>, which runs before any injected javascript is added. Ideally there'd be a way to intercept window.open/close calls with custom event handlers.

**Comment by binhndicts** [comment]
@tmaly1980 I just found a workaround solution. It's working good a except 1 bug related to CSS that I haven't found the reason. Here are some notes of my solution:
1. You SHOULD return a WKWebview in `createWebViewWithConfiguration` with provided configuration. It's called when `window.open` in JS called
2. There is no way to create a new RNCWebview from JS before returning the WKWebview in step 1, so I have to create and save the webview instance in Manager and then use it when manager creates view
```
- (UIView *)view
{
  RNCWebView *webView = newWindow ? newWindow : [RNCWebView new];
  webView.delegate = self;
  newWindow = nil;
  return webView;
}
```

Step 1 is the key point to keep connection between parent and child windows.
In theory, Android has the similar flow but I could not make it works like iOS

**Comment by bova80** [comment]
@binhndicts is there an android solution to this?  I have a link that has attribute target="_blank" and it doesn't work right in android, but fine in iOS.

**Comment by calm-rad** [comment]
@binhndicts Where do you declare `newWindow` and where do you set it to be the previous webView?

**Comment by Aikenwu** [comment]
Anyone who finds a common solution. pls, share. thanks.
