### ISSUE TITLE
crash on android 5.1.1, ID #0x2040003 error

### ISSUE THREAD

**Issue by Magrider** [react-native-community/react-native-webview#1112]
**Bug description:**

I upgrade my expo sdk from 35 to 36, and Webview from react-native is removed. Therefore I have to use Webview from "react-native-webview". 
android 5.1.1 will produce error String resource ID #0x2040003, I googled it and it seems like most of this happen on 5.1.1.  There was no problem before but it is happening after I upgrade my sdk. Anyone can fix this? otherwise I have to downgrade my sdk : (

**To Reproduce:**

- expo sdk 36

- use WebView normally it will produce the error.  I try all kind of version but it failed on expo client and standalone app they all has this error.

**Expected behavior:**

Expected work normally.

**Screenshots/Videos:**

![IMG_20200103_103038](https://user-images.githubusercontent.com/7843546/71706583-dbd19c80-2e20-11ea-9592-5d38499507ea.jpg)
![IMG_20200103_103108](https://user-images.githubusercontent.com/7843546/71706584-dbd19c80-2e20-11ea-8e70-7850a5f5e3d9.jpg)

String resource ID#0x2040003

**Environment:**
 - OS: Android
 - OS version: 5.1.1
 - react-native version: 0.61
 - expo-sdk: 36
 - react-native-webview version: all version

**Comment by Magrider** [comment]
I downgraded my expo sdk to 35, and still having this issue. I tried to reinstall my expo client (EXPONENT 2.13.0), and it works again.

**Comment by Magrider** [comment]
I think it is expo run-time issue.
https://github.com/expo/expo/issues/6665

**Comment by Davidzhu001** [comment]
i have the same problem on sdk 33 34

**Comment by Magrider** [comment]
This is a bug found on androidx.appcompat:appcompat:1.1.0 which is expo currently to use.
1.2.0 will fix it, and expo waiting for the 1.2.0 stable version.
