### ISSUE TITLE
How do I opt into WKWebview?

### ISSUE THREAD

**Issue by jisaacks** [react-native-community/react-native-webview#1113]
I am trying to use WKWebview instead of UIWebview.

This docs don't seem to mention how to turn this on?

In the react docs it says to set [`useWebKit`](https://facebook.github.io/react-native/docs/webview#usewebkit) to true. I searched this repo for the string `useWebKit` with no results and I tried setting it anyways but I am still getting deprecation warnings from Apple about UIWebview

Can someone please tell me how to opt into WKWebview?

**Comment by Naturalclar** [comment]
@jisaacks 
In the latest version of react-native-webview, i believe they have already removed UIWebview, so you are automatically using WKWebview by default

**Comment by jisaacks** [comment]
@Naturalclar thanks for the comment.

I just updated from 7.4.3 to 8.0.2 and I am still getting the error. When I deliver the build to App Store Connect I get the following email from apple:

```
Dear Developer,

We identified one or more issues with a recent delivery for your app, "App Name" 0.0.3 (1). Your delivery was successful, but you may wish to correct the following issues in your next delivery:

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

After you’ve corrected the issues, you can upload a new binary to App Store Connect.

Best regards,

The App Store Team
```

**Comment by Naturalclar** [comment]
@jisaacks Thanks for checking!
That's very odd.. this repo seems to have stopped using UIWebView from 7.0.1
https://github.com/react-native-community/react-native-webview/releases/tag/v7.0.1

Would it be possible that some other dependencies in your app thats using an older version of webview?
`npm ls react-native-webview` may help.

**Comment by jisaacks** [comment]
@Naturalclar

I ran that and just had one result:
`└── react-native-webview@8.0.2`

In my code I am importing it like this:
`import { WebView as RNWebView } from 'react-native-webview'`

styling it with styled-components like this:
```
const WebView = styled(RNWebView)`
  min-width: 320px;
  align-self: stretch;
  flex: 1;
  width: ${width};
  background: #BDA8FF;
`
```

And then using it like this:
```
<WebView
        ref={webview}
        originWhitelist={['*']}
        source={{uri: webviewURL}}
        useWebKit={true}
        onLoadEnd={() => {
          console.log('APP READY')
          setWebviewLoaded(true)
        }}
        onMessage={event => {
          handleMessage(event.nativeEvent.data)
        }}
/>
```

Also there aren't many dependencies in the app at all:
```
"dependencies": {
    "axios": "^0.19.0",
    "expo": "^35.0.0",
    "expo-location": "~7.0.0",
    "react": "16.8.3",
    "react-dom": "16.8.3",
    "react-native": "https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz",
    "react-native-web": "^0.11.7",
    "react-native-webview": "^8.0.2",
    "styled-components": "^4.4.1",
    "url-parse": "^1.4.7"
  },
  "devDependencies": {
    "babel-preset-expo": "^7.1.0"
  },
```

Finally I am using [Expo](https://expo.io/)

Not really sure what else to try. This is my first time using react native, expo, or building an ios app. I am primary a web developer.

**Comment by Titozzz** [comment]
This library does not use UIWebView. So the issue is not coming from here, but please note that you cannot use this library with expo as you cannot link native dependencies with expo.

**Comment by jisaacks** [comment]
> This library does not use UIWebView. So the issue is not coming from here,

That's fair. But neither are any of the other packages, nor do they have anything to do with webviews at all. And I am only using one webview and I am importing it from this library. 🤷‍♂ Maybe Apple's code that checks it is wrong or cached. Or maybe expo itself has it.. or the version of react-native I am using has a reference to UIWebView. Although I would expect them to get tree-shaken out. I'll look into those things, thanks.

I'll report back if I figure anything out.

> but please note that you cannot use this library with expo as you cannot link native dependencies with expo.

Not sure what you mean? Would love for you to elaborate on that. Expo docs specify to use this library:
https://docs.expo.io/versions/latest/sdk/webview/

**Comment by Stephen2** [comment]
@Titozzz If you could elaborate on _please note that you cannot use this library with expo_ ?

I've just made this transition locally, and about to give a test run, but Expo made it sound like this lib is the way to go

**Comment by ankhzet** [comment]
@jisaacks @Stephen2 Expo and some of it's packages still internally do reference deprecated UIWebView. Expo team is planning to remove those references completely in SDK 37+.

For now it's safe to use the library despite deprecated code being referenced, Apple just reminds you, that it's support would be removed in the next versions of iOS and you might need to update your code accordingly (the most important parts of the message from Apple are **`Your delivery was successful`** and `but you may wish to correct the following issues in your next delivery`).

**Comment by alessandro-bottamedi** [comment]
@ankhzet Do we have this problem with expo bare workflow too?

**Comment by ankhzet** [comment]
@alessandro-bottamedi Some folks manage to get rid of deprecated references with just updating related dependencies (react-native 0.61.1, react-native-device-info 3.1.4) it seems.
Some more info in a dedicated expo issue:
https://github.com/expo/expo/issues/5497#issuecomment-544598567

**Comment by luco** [comment]
I'm also getting the 90809 error.
![image](https://user-images.githubusercontent.com/246373/81460060-4b61ea80-9179-11ea-9227-0bc7f9431d8a.png)

**Comment by Skullcan** [comment]
I'm having problems with this too.

Only reference I could find was through react-native-webview dependency of other library my project uses.
Tried to update but the result is the same.

web-view version I'm using is 10.8.3
