### ISSUE TITLE
Does base64 not supported by webView? 

### ISSUE THREAD

**Issue by lkum11** [react-native-community/react-native-webview#1114]
//converting blob to base64data

const fileReaderInstance = new FileReader();
                    fileReaderInstance.readAsDataURL(response.data); 
                    fileReaderInstance.onload = () => {
                        base64data = fileReaderInstance.result;                
                        console.log(base64data);
                        dispatch({
                                type: OPEN_DOCUMENT, url:  base64data
                            });
                    }

//rendering 

 <WebView 
                    source={{ uri: url }} 
                    originWhitelist={['*']}
                />
                <Image source={{uri: url}} style={{ height: 400, width: 300, }} />

I am able to render the image file using Image tag but Webview is throwing error "028
data:application/pdf;base64,JVBERi0xLjMNCiXi48/TDQoNCjEgMCBvYmoNCjw8DQovVHlwZ... is not a file url ".

Please help.

**Comment by paddu1246** [comment]
what is the solution for this issue?
Please let me know 
thank you

**Comment by paddu1246** [comment]
source={{ html: `
                 <iframe src="data:application/doc;base64,${documentBase64}" height="100%" width="100%">
                    The “iframe” tag is not supported by your browser.
                 </iframe>
                ` }}
