### ISSUE TITLE
NSPOSIXErrorDomain Error 53

### ISSUE THREAD

**Issue by MelMayssonOwen** [react-native-community/react-native-webview#1115]
**Bug description:**

When reopening a webview this error appear with certain pages.
**To Reproduce:**

Very easy to reproduce, an app with a webview (instagram seems to be having this issue most).
Open the webview, put app in background and reopen app.

**Expected behavior:**

No error

**Screenshots/Videos:**

**Environment:**
 - OS: Android
 - OS version: 
 - react-native version: 0.61.4
 - react-native-webview version: 8.0.2

**Comment by louback-rethink** [comment]
Same problem here testing in iOS 12.1 device.

**Comment by lrusso** [comment]
This is still an issue, it shouldn't be closed.
