### ISSUE TITLE
Is there a way to disable the default context menu that pops on selection inside ios webview ?

### ISSUE THREAD

**Issue by adkaushik** [react-native-community/react-native-webview#1117]

**Comment by rockneverdies55** [comment]
Do you mean cut, copy, paste menu that pops up on text selection? If so, how about disabling text selection all together? #607 ?

**Comment by bittu1028** [comment]
@rockneverdies55  need to hide those cut copy paste menu but allow selections is there any solution for that.

**Comment by adkaushik** [comment]
`-webkit-touch-callout: none;` should ideally work and hide the callout menu. But unfortunately this is not working in ios webview. On the other hand `user-select: none` completely disables the selection of text.

**Comment by binhndicts** [comment]
@adkaushik how about `document.body.style.webkitTouchCallout='none'`?

**Comment by orchardfruit** [comment]
Is there any solution to this problem?

**Comment by dzcpy** [comment]
Actually, is there any possiblity to be able to redefine the menu?

**Comment by interstates21** [comment]
same question

**Comment by brand000** [comment]
you have to use the prop injectedJavaScript.  here's an example of what I did.

const removeOverlay = `
    document.body.style.webkitTapHighlightColor = 'rgba(0, 0, 0, 0)';
    document.body.style.webkitLineClamp = 'none';
    document.body.style.userSelect = 'none';
   `;

  return (
    <PaperPlusStyled
      source={{
        uri: "https://www.paperplus.ca/",
      }}
      startInLoadingState={true}
      scalesPageToFit={true}
      javaScriptEnabled={true}
      domStorageEnabled={true}
      startInLoadingState={false}
      scalesPageToFit={true}
      geolocationEnabled
      allowFileAccess
      allowUniversalAccessFromFileURLs
      allowsFullscreenVideo
      focusable={false}
      accessible={false}
      injectedJavaScript={removeOverlay}
      onError={() => navigation.navigate("Web404")}    
    />
  );
};

This  line 

 document.body.style.userSelect = 'none';  

 in the code is what turns off the context menu ( copy, paste, etc).

and these lines

 document.body.style.webkitTapHighlightColor = 'rgba(0, 0, 0, 0)';
 document.body.style.webkitLineClamp = 'none'; 

lets you turn off the highlight when the user would click on an image and among other things.

hope this solves everyone's problem.
