### ISSUE TITLE
Wrong extension for images selected in an input type file 

### ISSUE THREAD

**Issue by esynaps** [react-native-community/react-native-webview#1122]
**Bug description:**

This bug was introduced in version 6.9.1 and has still not been fixed in the latest version.
https://github.com/react-native-community/react-native-webview/releases/tag/v6.9.1

When you selects a photo in an input with attributes "type" = "file" and "accept" including "image/\*" and "video/\*" the image extension is .mp4 instead of .jpg

This works correctly when the input only accepts "image/\*"

**To Reproduce:**
Use a version equal or greater than 6.9.1 of react-native-webview.

Open a Webview to a page containing an input type file accepting images and videos. 
Example page : https://addpipe.com/html-media-capture-demo/

Click on the input and select a photo (in my case I am using the camera).

**Expected behavior:**
The image must have the extension .jpg

**Screenshots/Videos:**

## **V6.9.0**

![Image of Yaktocat](https://i.gyazo.com/06e02daddaefa17ef72dabca36d86ee1.png)

![Image of Yaktocat](https://i.gyazo.com/cfc21518528538f1fb8beb0973fc9378.png)

## **V6.9.1**

![Image of Yaktocat](https://i.gyazo.com/73ff3db339db8fc579c9a269e66f67c9.png)

### **The BUG :**

![Image of Yaktocat](https://i.gyazo.com/77a4fcf687263279635f40c634f60c5c.png)

**Environment:**
 - OS: Android
 - OS version: 9 (test on otherd android with unknown versions, same problem)
 - react-native version: 0.61.5
 - react-native-webview version:  6.9.1 and greater

**Comment by esynaps** [comment]
This bug is blocking and may cause us to abandon this package. Any news ?

**Comment by jwilliamson-qb** [comment]
Noticing it on our app as well. +1

**Comment by sdc987** [comment]
We ran into a similar issue.  I've been able to fix the issue by switching the order of the following code, in both startPhotoPickerIntent methods.

Original code:
if (acceptsImages(acceptTypes)){ extraIntents.add(getPhotoIntent()); }
if (acceptsVideo(acceptTypes)) { extraIntents.add(getVideoIntent()); }

Switch to :

if (acceptsVideo(acceptType)) { extraIntents.add(getVideoIntent()); }
if (acceptsImages(acceptType)) { extraIntents.add(getPhotoIntent()); }

I'm not sure why the Intent order resolved our issue. I haven't done lot of Android development.  Still running more tests but so far it seem to fix our issue.

**Comment by appify-waheed** [comment]
@sdc987 In which file I can find startPhotoPickerIntent method?

**Comment by lfalkner** [comment]
@appify-waheed here https://github.com/react-native-community/react-native-webview/blob/master/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewModule.java#L157
and here https://github.com/react-native-community/react-native-webview/blob/master/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewModule.java#L180

we have not attempted this fix yet

**Comment by alexandre-le-borgne** [comment]
Still searching for solutions

**Comment by alexandre-le-borgne** [comment]
Why...?
