### ISSUE TITLE
Doesn't respond immediately to changes in iOS Dynamic Type

### ISSUE THREAD

**Issue by HolySamosa** [react-native-community/react-native-webview#1123]
**Bug description:**
WebView does not respond immediately to DynamicType changes on iOS. When "Text Size" is changed in iOS Settings, the text size does not change in WebView until it is reloaded.   For RN Text components, the size change is immediate.  

According to this article, this may be due to an underlying issue with WKWebKit:
https://useyourloaf.com/blog/using-dynamic-type-with-web-views/

As a work around, the article recommends observing `UIContentSizeCategory` events to trigger a reload of the WKWebView, however I don't believe it's possible to subscribe to these events in ReactNative?

What solution would be advisable? Would the above suggested work-around be something that would be reasonable to integrate into `react-native-webview`?

**To Reproduce:**
Here's a snack that was **intended** to demonstrate the problem:
https://snack.expo.io/@holysamosa/f7ac17

However, unfortunately my Expo client opens the QR code scanner when I resume the Snack after making a change to the "Text Size" in "Settings"-- thus, the view will always get reloaded after the text size change.  Running as a local project should demonstrate the issue.

**Expected behavior:**
The text size in the WebView should immediately reflect a change in DynamicType settings.

**Screenshots/Videos:**

**Environment:**
 - OS: iOS 
 - OS version: 13.3
 - react-native version: 0.61.4
 - react-native-webview version: 7.4.3

**Comment by darshil** [comment]
Hey @HolySamosa! 

Is there any other way to change font-size in WebView instead of using Apple's system font?

**Comment by HolySamosa** [comment]
@darshil: Sorry for the late reply.  I guess this is off-topic, but I created a StackOverflow issue seeking a solution for setting the font-size of a WebPage asid from using the system font: https://stackoverflow.com/questions/59638400/scale-page-font-size-in-ios-wkwebview-like-safaris-page-zoom

Using the system font is the only method I've seen work (which of course ties the font size to your Display settings), however Safari does support adjusting the font size of any web page, so this should be possible with a WebView.
