### ISSUE TITLE
Not Possible download on webiview

### ISSUE THREAD

**Issue by arunreenamohan-creator** [react-native-community/react-native-webview#1126]
Hi.
I cant download any files on webview

I cant download any files on webview even in google page

**Comment by arunreenamohan-creator** [comment]
pls help me iam struggled with this issue

**Comment by arunreenamohan-creator** [comment]
<View style={{ flex: 1 }}>
 <WebView
 onLoad={() => this.hideSpinner()}
 style={{ flex: 1 }}

 source={{ uri:'https://www.google.com/'}}
  javaScriptEnabled = {true}





       />

**Comment by dvicory** [comment]
What platform? What's the symptom?

Did you make sure to [follow the instructions here](https://github.com/react-native-community/react-native-webview/blob/361529630fbe7e0f743eaa71d72ba3f542553ec2/docs/Guide.md#add-support-for-file-download)?

For iOS, there is no true downloading of arbitrary files. Only file previews (e.g., opening a PDF will let you preview it, but there is no built-in way to save to the phone). You can long press images to save them. Implementing true downloading in WKWebView has been quite the epic for our team and we've settled on a custom solution involving a custom protocol, outside the purview of react-native-webview in my opinion.
