### ISSUE TITLE
react-native-webview 8.0.2 could  not posting message to webside (app crashed)

### ISSUE THREAD

**Issue by SVinay27** [react-native-community/react-native-webview#1128]
### **CameraScreen**
also i referred  this guide link
[webview guide](https://github.com/react-native-community/react-native-webview/blob/master/docs/Guide.md#communicating-between-js-and-native)

i want to post message when i calling function not in render function ...

_**also help for how to listen injected data on web side**_

*webview part:*
```
<View style={styles.webViewContainer}>
            <WebView
              ref={webview => {
                this.myWebView = webview;
              }}
              scrollEnabled={true}
              source={{uri: this.state.initialURL}}
              onNavigationStateChange={this.onWebViewStateChange.bind(this)}
              renderError={e => {
                console.log(e);
                if (e === 'WebKitErrorDomain') {
                  return;
                }
              }}
              onShouldStartLoadWithRequest={this.onShouldStartLoadWithRequest}
              onMessage={this.handleWebViewBridgeMessage}
              userAgent="demo"
              onError={e => {
                console.log('onERROR: ' + e.nativeEvent.code);
                this.onWebViewError();
              }}
              allowUniversalAccessFromFileURLs={true}
              allowFileAccessFromFileURLs={true}
              originWhitelist={['*']}
              sharedCookiesEnabled={true}
              thirdPartyCookiesEnabled={true}
              mixedContentMode={'always'}
              startInLoadingState={true}
            />
            {this.state.showCamera && (
              <CameraScreen
                getBarcodeData={this.getBarcodeData}
                closeCamera={this.closeCamera}
              />
            )}
</View>
```

*Function:*

```
getBarcodeData = qrcode => {
    if (qrcode) {
      this.state.msgg.isSuccessfull = true;
      this.state.msgg.qrcode = qrcode;
      this.myWebView.postMessage(JSON.stringify(this.state.msgg));
    }
    this.closeCamera();
    this.showToast(qrcode, 500);
  };
```
**Description:**

*the same code is working in **react-native : 0.57** version*

**Environment:**
 - OS: ios
 - OS version:10.15.1
 - react-native version: 0.57
 - **webview** imported from native element
 
**And**
*the same code is crashed on **react-native : 0.61.5** version*
if i comment the this.myWebView.postMessage(JSON.stringify(this.state.msgg)); then app is working fine

**Environment:**
 - OS: ios
 - OS version:10.15.1
 - react-native version: 0.61.5
 - react-native-webview: 8.0.3

Help me

**Comment by SVinay27** [comment]
hello..
i 'm waiting response

**Comment by raajnadar** [comment]
**Try this method (For android)**

cd into android folder

run `gradlew clean` or `./gradlew clean` according to your OS

Now run `react-native run-android` it worked for me in android.

**Try this method (For ios)**

For iOS try deleting pods folder and `pod install`

**Comment by raajnadar** [comment]
Is the issue resolved?
