### ISSUE TITLE
Can not open href links on Android, but on IOS it works well

### ISSUE THREAD

**Issue by jocoders** [react-native-community/react-native-webview#1129]
react-native: 0.61.05
react-native-webview: 8.0.1

**Bug description:**
I use react-native-webview for the navigation from my app to the browser by href links from HTML source props. And on IOS it works fine, without any troubles. But on Android it does not work. When i press to the link nothing has happening, the link is not opening on the browser and i'm not getting any errors.
**Expected behavior:**
When i press to the link it has to be opened in the browser on both platform IOS/Android, now it works only on IOS.
**To Reproduce:**
 I already tried to change this block of code in RNCVebViewManager.java:
```
    settings.setAllowFileAccess(true);
    settings.setAllowContentAccess(true);
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN) {
      settings.setAllowFileAccessFromFileURLs(true);
      setAllowUniversalAccessFromFileURLs(webView, true);
    }
```
And add different props like:
```
javaScriptEnabled={true},  
domStorageEnabled={true}, 
allowFileAccess={true}, 
allowUniversalAccessFromFileURLs={true},
```
But nothing works for me.
**My Component:** 
```
          <WebView
            ref={this.setWebView}
            automaticallyAdjustContentInsets={true}
            source={{ html: this.state.correctHtml, baseUrl: '' }}
            onMessage={this.onMessage}
            javaScriptEnabled={true}
            injectedJavaScript={`${postMessage};document.body.scrollHeight;`}
            style={{ height: this.state.height }}
            onNavigationStateChange={this.onNavigationChange}
            domStorageEnabled={true}
            scalesPageToFit={Platform.select({ios: undefined, android: true})}
            startInLoadingState={true}
            scrollEnabled={true}
            showsHorizontalScrollIndicator={false}
            showsVerticalScrollIndicator={false}
            bounces={false}
            originWhitelist={['*']}
          />
```
Can somebody help me please.

**Comment by lewisf** [comment]
hey @jocoders how did you resolve this?

**Comment by asavardplante** [comment]
@jocoders  I'd like to also know if possible, I have the same problem right now

**Comment by michaelkitas** [comment]
Same issue here, were you able to resolve this?
