### ISSUE TITLE
How to disable display sys menu on WebView by long touch.

### ISSUE THREAD

**Issue by taketomon** [react-native-community/react-native-webview#1131]
Hi, there.

When using WebView, I do not want to share the content link etc., so I want to hide the menu (touchCallout ? please see the attached file).
I cannot catch and handle events of long touch (or force press) on react-native-webview…

device: iPhone 7 (iOS 12)
react-native-webview: 7.0.5

Thank you!

![sample_display_sys_menu](https://user-images.githubusercontent.com/44116685/72142583-5b8ad880-33d8-11ea-9fb2-57a5b7292d34.png)

**Comment by adkaushik** [comment]
You can try using the following CSS `-webkit-touch-callout: none;`

**Comment by taketomon** [comment]
Hi adkaushik,

Sorry for the late reply.

Thank you for the advice.

I will use it.

Best regards,
taketomon
