### ISSUE TITLE
opens in browser when originWhitelist contains a path

### ISSUE THREAD

**Issue by giregk** [react-native-community/react-native-webview#1133]
**Bug description:**
If you specify ```originWhitelist={['https://domain.com/']}```, the link opens in the browser instead of inside the app.

If you remove the trailing '/', it works fine.
(My use case is to specify an originWhitelist equal to source.uri so users can't navigate outside the domain of the link.)

**To Reproduce:**
on iOS (not tested on android)
```
<WebView
  source={{uri: 'https://exemple.com/index.html}}
  originWhitelist={['https://exemple.com/index.html']}
>...
```
**Expected behavior:**
The link should open in the app (as a webview) instead of opening the navigator and the domain user should be unable to navigate outside the domain.

**Screenshots/Videos:**
N/A

**Environment:**
 - OS: iOS
 - OS version: 13.3
 - react-native version: 0.59
 - react-native-webview version: 8.02

**Comment by james1888** [comment]
I got the same problem too. It opens the browser to this link https://staticxx.facebook.com/connect/xd_arbiter.php?version=45#
`url="https://l192.mediaload.co"`
`originWhitelist={['https://*.l192.com', 'https://*.mediaload.co']}`

**Comment by theUNnicked** [comment]
I have the same problem. The behavior I want to achieve is only allowing to render a specific page. Redirecting to any other page on the same domain should open it in the browser.

I know that the documentation about originWhitelist states that: The strings allow wildcards and get matched against just the origin (not the full URL). But is there an actual reason why full urls cannot be whitelisted?

**Comment by princefishthrower** [comment]
I can confirm this is reproducible in version 11.13.0

But I need it to parse special intent links...

**Comment by jeromecovington** [comment]
I would like the ability to only load a specific matched path on the whitelisted origin into the WebView, but have links that are tapped in the loaded document (which do not match the whitelisted origin + path), be opened in the browser.
