### ISSUE TITLE
Can not read cookies in Android

### ISSUE THREAD

**Issue by maxiconil** [react-native-community/react-native-webview#1134]
**Bug description:**
Getting the next error trying to access the cookies from an Android device:

Error: Failed to read the 'cookie' property from 'Document': Access is denied for this document.

**To Reproduce:**
Injecting a piece of JS that uses cookies, I'm seeing that error as soon as the JS code is executed

i.e.
    const cookies = document.cookie.split(";");

**Expected behavior:**
Be able to read cookies as in iOS

**Environment:**
 - OS: Android
 - OS version: 9
 - react-native version: 0.61.5
 - react-native-webview version: 8.0.3

**Comment by timeturnback** [comment]
`source={{ baseUrl: "https://example.com", html: html }}`
add baseUrl (any url work) to the source . that will work because WebView seem use different method to load html if baseUrl missing

**Comment by wajahat414** [comment]
I have Identitifed the issue , The Problem is of Android API level, you just try on newest Android  version it will Work

**Comment by 4mit** [comment]
i tired on android 13 still its the same issue

**Comment by Harikarthyk** [comment]
+1

**Comment by MuskanMittal0987** [comment]
> source={{ baseUrl: "https://example.com", html: html }}

thanks its worked for me
