### ISSUE TITLE
 Doesn't support some URL schemes

### ISSUE THREAD

**Issue by Visakeswaran** [react-native-community/react-native-webview#1135]
**Bug description:**
I am using react-native-community/react-native-webview, to render a web view in my application. My URL scheme looks something like intent://cdn.glitch.com/.... (which is basically a WebAR, that basically opens a 3D model in the space around with help of camera). It throws an error saying ERROR_UNKNOWN_URL_SCHEME.

**To Reproduce:**
Add source uri as **'intent://user?screen_name=paul_kinlan#Intent;scheme=twitter;S.browser_fallback_url=https%3A%2F%2Ftwitter.com%2Fpaul_kinlan;end'**

**Expected behavior:**
Should load the url content

**Screenshots/Videos:**
[https://ibb.co/zNb9H7P](url)

**Environment:**
 - OS: Mac OS
 - OS version: Mojave
 - react-native version: 0.61.5
 - react-native-webview version: 8.0.1

**Comment by thekingrenz23** [comment]
do you solved this problem?

**Comment by j-piasecki** [comment]
https://github.com/facebook/react-native/pull/31836
