### ISSUE TITLE
Fit Page to mobile view shows content from middle IOS

### ISSUE THREAD

**Issue by soumyamishra89** [react-native-community/react-native-webview#1137]
**Bug description:**
So scalePageToFit is no longer supported on WKWebView on ios. So, as a work around I inject javascript code

`const meta = document.createElement('meta'); meta.setAttribute('content', 'width=device-width, initial-scale=1'); meta.setAttribute('name', 'viewport'); document.getElementsByTagName('head')[0].appendChild(meta);  true`

The scale works fine, but to see the top of the content, I need to scroll the view. 

https://snack.expo.io/@ssmishra/react-native-webview-issue
I have created a snack repo for the issue. 

**Environment:**
 - react-native version: 0.61.5
 - react-native-webview version: 8.0.3

**Comment by truongthanh1303** [comment]
Hi maintainers,

Could you have a look at this issue? I hope this issue could be fix as soon as possible.
Thanks in advance!

**Comment by soumyamishra89** [comment]
any update on this?

**Comment by mcatmos** [comment]
Still an issue here!

**Comment by soumyamishra89** [comment]
WIth the new version 9.2.1, the injectedJS with 
`const meta = document.createElement('meta'); meta.setAttribute('content', 'width=device-width, initial-scale=1'); meta.setAttribute('name', 'viewport'); document.getElementsByTagName('head')[0].appendChild(meta); true`;

does not work at all
