### ISSUE TITLE
Webview is loading continuously in iOS. 

### ISSUE THREAD

**Issue by karthikmandava7** [react-native-community/react-native-webview#1138]
**Bug description:**
We are using Webview to HTML dom in Android it's working as expected but in iOS, it is continuously loading.

**To Reproduce:**
<WebView
        originWhitelist={["*"]}
        source={{ html: this.state.htmlDOM, baseUrl: Services.mSiteDomain }}
        onShouldStartLoadWithRequest={request => {
          const categoryId = FNPUtils.parseHtmlLink(request.url);
          this.props.navigation.push("GiftListScreen", {
            productCategoryId: categoryId
          });
          return false;
        }}
        showsVerticalScrollIndicator={false}
      />

**Expected behavior:**
It should open only once and when the user clicked on anything on Webview then it should redirect to a particular thing

**Environment:**
 - react-native version: 0.60.0
 - react-native-webview version: 8.0.0

**Comment by ryanmcclure4** [comment]
I'm experiencing this same exact issue - Everything loads fine on Android, but iOS just shows the loader forever. I added all of the event props, and onLoadProgress gets triggered twice - First with "0.1", and second with "0". So it seems like something is failing, but none of the other events ever get called.

**Comment by FuzzyFade** [comment]
U counld add a custom Loading Components at renderLoading.
Like this:
`const [showLoading, setShowLoading] = useState<boolean>(true)`
`onLoadEnd={() => setShowLoading(false) }`
`<WebView
        {...props}
        renderLoading={() => showLoading ? (
	      <View style={{
			position: 'absolute',
			left: 0,
			right: 0,
			top: 0,
			bottom: 0,
			backgroundColor: '#fff',
			justifyContent: 'center',
			alignItems: 'center'}}>
	        <ActivityIndicator color="#737373" size="large" />
	        <Text>loading</Text>
	      </View>
    	) : null}
/>`

**Comment by ryanmcclure4** [comment]
@FuzzyFade that is helpful in the case that the loading succeeds, but our issue is that loading is failing and onLoadEnd is never called. There is essentially no indication of why it fails either, as none of the callbacks (i.e. onError, onHttpError, renderError, etc...) get triggered.

**Comment by ryanmcclure4** [comment]
@karthikmandava7 were you able to figure out the cause of this?

**Comment by ryanmcclure4** [comment]
I can't imagine no one else is running into this issue. Anyone know what we might be doing wrong?

**Comment by karthikmandava7** [comment]
@ryanmcclure4 No, I didn't get why it is.

**Comment by ShahidAnjum** [comment]
I'm also stuck in same issue,  onShouldStartLoadWithRequest   loads only once in case of Android,  but for iOS it loaded multiple times,  ideally it should be called only once

**Comment by ShinKano** [comment]
I've been getting same type of error.  

- "react-native": "0.61.5",
- "react-native-webview": "^8.0.5",


My component has;

- onShouldStartLoadWithRequest
- onLoadStart
- onLoadEnd

 onShouldStartLoadWithRequest & onLoadStart are called but onLoadEnd isn't called.

 With some URL, it works well, but with some other URL, onLoadEnd never be called.

Android is OK, only iOS has this problem.

**Comment by douglasviehbeck** [comment]
This happens because the behaviour of `onShouldStartLoadWithRequest` is not the same for iOS and Android. On iOS the event is triggered on the first page load, so you need to return `true` the first time. On Android the event is triggered only when navigation between pages occurs.

**Comment by hkar19** [comment]
for me, the webview progress stuck at value` 0.870618947737071` and it does not fire the next `onNavigationStateChange` that i expected

**Comment by hkar19** [comment]
i randomly reproduced this bug, and i got this error 
```
Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
```

and maybe related to this [link?](https://stackoverflow.com/questions/44585980/com-apple-webkit-webcontent-drops-113-error-could-not-find-specified-service)

**Comment by hkar19** [comment]
it appears to me, my users are using iOS 14. there is no finding yet on previous version of iOS.

**Comment by rhadamez** [comment]
As a temporary solution, I removed the "onLoadStart" on iOS throught "Platform.OS", and let it only in Android.

Another solution would be: create a modal with loader above the webview, and display it until you want, change the state of visibility of the modal.
