### ISSUE TITLE
Cannot play sound in silent mode

### ISSUE THREAD

**Issue by baquy96** [react-native-community/react-native-webview#1140]
**Bug description:**
I am using WebView to load a webpage which has an embedded audio player. It works fine when the app is in ringer mode. But does not have any sound when App is in IOS silent mode.

**Expected behavior:** Sound working in IOS silent mode

**Screenshots/Videos:**

![image](https://user-images.githubusercontent.com/13012834/72322002-dc4b1c80-36d7-11ea-9677-3d423b087184.png)

**Environment:**
 - react-native version: 0.61.5
 - react-native-webview version: 8.0.1

**Comment by afilp** [comment]
I also have a similar problem, it is actually this one which may be relevant:
https://github.com/react-native-community/react-native-webview/issues/542

Unfortunately, the Bot closed that as inactive, while it is an important bug (we cannot have HTML5 sounds within the webview). I hope there is someone that knows the internals to look at it, time permitting. Thanks!

**Comment by jasonmcaffee** [comment]
This issue has not been fixed.  From what I can tell, this fix may have been included at some time, but is no longer there, and setting the ignoreSilentMode property (I forget the exact name, and it's not documented) does nothing.

Can this be re-opened, or should a new issue be created?

**Comment by Geneonosis** [comment]
really could use a resolution to this as I am running version 11.0.0. I am using this in a project for different "courses" 2 of the courses work fine in silent mode (there is audio!) the others don't and I am failing to see the difference in material.
