### ISSUE TITLE
reactNative 0.61.5 Initiate error reporting Could not download kotlin-compiler-embeddable.jar

### ISSUE THREAD

**Issue by Zhang-DaLei** [react-native-community/react-native-webview#1141]
**Bug description:**
I installed it according to the document react-native-webview and link
then react-native run-android  Report errors

**Expected behavior:**
Initiate error reporting Could not download kotlin-compiler-embeddable.jar

**Screenshots/Videos:**
<img width="564" alt="image" src="https://user-images.githubusercontent.com/23338914/72331640-7cfb0580-36f3-11ea-80da-95a6446098f6.png">

**Environment:**
 - OS:android
 - OS version: android 8.0
 - react-native version:0.61.5
 - react-native-webview version:8.0.3

**Comment by mi-mazouz** [comment]
@Zhang-DaLei did you solve your issue?
