### ISSUE TITLE
About "Could not find specified service" Error.

### ISSUE THREAD

**Issue by Macrow** [react-native-community/react-native-webview#1145]
I use webview to load this page:

https://demo-rtc.herewhite.com/zh-CN/

![image](https://user-images.githubusercontent.com/240792/72673270-eb004d80-3aa2-11ea-8e7e-1f9ef2e695f6.png)

click  “开源产品在线体验” to enter whiteboard

all works fine in the iphone, but it can't work in the ipad, it says:

```console
Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
```

how can I debug and solve this ?

Thanks.

**Comment by Macrow** [comment]
fixed by setting userAgent

**Comment by Davidzhu001** [comment]
@Macrow how do yoo ufix it

**Comment by Macrow** [comment]
> @Macrow how do yoo ufix it

fixed by setting userAgent
