### ISSUE TITLE
Proxy logic in a Webview

### ISSUE THREAD

**Issue by opolo** [react-native-community/react-native-webview#115]
Hi,

I do not believe this feature is added yet, therefore I post this in the proposal board here. So please consider it a proposal too for something that would be neat if it is not existing yet.

Anyway,

I have not been able to find any way, by which I can achieve this in the webview (or in React Native in general). And there does not seem to be any post on it yet, so I hope it is okay that I ask (and/or suggest):

Is it possible to add any sort of http proxy to a webview? What I want to achieve is to route the webview browsing traffic through a proxy (that is running Privoxy), which can strip the HTTP content in the communication for the tracking scripts and ads.
I can do it on a full-fledged desktop browser, and through a global setting on the iphone which routes all traffic on the iphone for all apps through the proxy (the IP and port number of the proxy can be set in network settings on the iPhone).... That is not userfriendly though, since it needs to be done outside the app manually by the user, and the bandwidth usage skyrockets on the proxy compared to if only the webview in my app routed it.

Is it possible to have just the webview achieve this? I cannot seem to get access to any sort of underlying http client or anything in it, so I cannot do something hacky either :/

Hope to hear from you, whether it is possible to setup any proxy on the webview in any way :) Thanks!

NB. What I want to make is an app, where users can browse privately without fear of being monitored and profiled for what they browse and buy.

**Comment by jamonholmgren** [comment]
From what I can tell, this isn't possible with WKWebView:

https://stackoverflow.com/a/41268348/204044

nor Android WebView, although there's a hacky workaround:

https://stackoverflow.com/questions/4488338/webview-android-proxy

I'll close this issue, but please feel free to follow up with any additional information. Thank you!

**Comment by Mohsen7s** [comment]
@jamonholmgren I correct your response that its possible in android API 29 with the feature implemented inside webview.
Check this
https://developer.android.com/reference/androidx/webkit/ProxyController

We cant do it only in iOS but with all other platforms this is possible. So maybe consider to reopen this issue

**Comment by jhontech32** [comment]
any solution here ? i want to access blocked website in webview, please help ..

**Comment by nthiendev** [comment]
the same issue, i also want to access blocked website in react native webview
