### ISSUE TITLE
Doesn't redirect if the source and target URLs only differ in their fragment

### ISSUE THREAD

**Issue by zcesur** [react-native-community/react-native-webview#1150]
**Bug description:**
WebView doesn't redirect if the source and target URLs only differ in their fragment. For example, while on `/posts`, if I send a POST request to the server and get a 302 response to `/posts#1`, the WebView does not follow the redirection as it should. I'm not too familiar with the codebase but this might be due to `RNCWebViewManager` overriding the loading of hash URL changes. If so, zcesur/react-native-webview@92e36d0 might be an easy fix.

**To Reproduce:**
https://github.com/zcesur/react-native-webview-bug-repro
- Follow README instructions to run the app
- Fill out and post the textarea to server

**Expected behavior:**
The page should reload with new content as in the screenshot below, since the server responds with a 302.

**Screenshots/Videos:**
![](https://user-images.githubusercontent.com/17045339/72646403-20b01400-3987-11ea-9853-0a204d117fd2.png)

**Environment:**
 - OS: Android
 - OS version: 8.0.0
 - react-native version: 0.61.5
 - react-native-webview version: 8.0.3

**Comment by safaiyeh** [comment]
Fix is merged thanks for the PR @zcesur
