### ISSUE TITLE
'React/RCTView.h' file not found

### ISSUE THREAD

**Issue by cuongpv219** [react-native-community/react-native-webview#1151]
I manually added the RNCWKWebView.xcodeproj to the XCode Libraries and now I've run into this problem: ../node_modules/react-native-webview/ios/RNCWKWebView.h:8:9: 'React/RCTView.h' file not found
react-native: 0.61.5
react-native-webview: 8.0.1

Has there been a fix? Please help.

**Comment by binhndicts** [comment]
*manually*? Why did you have to do that? Using autolink would work
