### ISSUE TITLE
This is possibly due to an unsupported return type. Try adding true to the end of your injectedJavaScript string.

### ISSUE THREAD

**Issue by xclidongbo** [react-native-community/react-native-webview#1153]
**Bug description:**

```
(function(){
                            iosXY('${location.coords.latitude}', '${location.coords.longitude}');
                        })()
```
some error:
This is possibly due to an unsupported return type.
Try adding true to the end of your injectedJavaScript string.

**To Reproduce:**

**Expected behavior:**

**Screenshots/Videos:**

**Environment:**
 - OS: iOS
 - OS version: 13.3
 - react-native version: 0.59
 - react-native-webview version: 5.12.1

**Comment by truongthanh1303** [comment]
Hi @xclidongbo ,
Currently I get the same, could you please share your solution?
Thanks.
