### ISSUE TITLE
onError does not catch bad URIs

### ISSUE THREAD

**Issue by sabraham** [react-native-community/react-native-webview#1154]
**Bug description:**
A misspecified URI throws an exception that onError does not catch. Instead, we get a red box error: `Exception thrown while executing UI block: https:// is not a file URL` (when using just `https://` as the uri).

**To Reproduce:**
import React, { Component } from 'react';
import { WebView } from 'react-native-webview';

```
class App extends Component {
  render() {
    return (
      <WebView
        source={{ uri: 'https://' }}
        onError={syntheticEvent => {
          const { nativeEvent } = syntheticEvent;
          console.warn('WebView error: ', nativeEvent);
        }}
        style={{ marginTop: 20 }}
      />
    );
  }
}

export default App;
```

**Expected behavior:**
I would expect there to be some way to catch this type of exception gracefully.

**Environment:**
 - OS: iOS
 - OS version: simulator
 - react-native version: 0.61.4
 - react-native-webview version: 8.0.3

**Comment by cmcaboy** [comment]
I also ran into this and I'm not sure what a good solution for this is.

**Comment by SamiChab** [comment]
Hello, still searching for solutions on this...
I get an error in my logs `backend.js:32 Error opening URL:  Error: Unable to open URL [...]` without having onError fired

**Comment by billnbell** [comment]
Can you do a try catch ?

**Comment by FreTimmerman** [comment]
this is still an issue. this ticket should not have been closed

**Comment by ThePinkHatDev** [comment]
This is still an issue as of today, why is this issue closed? I'll probably put a PR in when I have some time.

**Comment by LuciKritZ** [comment]
Still facing this issue, any workarounds people?

**Comment by nullpointer010** [comment]
Same issue

**Comment by GeeGYMR** [comment]
Still an issue to this day

**Comment by stephensanwo** [comment]
If your goal is to just render an error component and renderError or onError does not work, this is how I got it working. Not perfect, but it works
- Track the nativeEvent in a state
- Update the nativeEvent state in onLoadProgress

```ts
function CustomWebView({ source }: WebViewProps) {
  const [nativeEvent, setNativeEvent] =
    React.useState<WebViewNativeProgressEvent>();

  return (
    <View.Default>
      <WebView
        source={source}
        onLoadProgress={({ nativeEvent }) =>
          setNativeEvent(nativeEvent as WebViewNativeProgressEvent)
        }
        renderLoading={() => {
          if (nativeEvent?.url === "") {
            return (
             // Error component
            );
          }
          return (
            // Activity Indicator
          );
        }}
        startInLoadingState={true}
      />
    </View.Default>
  );
}
```

- If there is an error the nativeEvent returns an object with an empty url, like this, so you can render a view with conditionals
```
{"canGoBack": false, "canGoForward": false, "loading": false, "progress": 0, "target": 1003, "title": "", "url": ""}
```
