### ISSUE TITLE
Copy to Clipboard Issue from webview

### ISSUE THREAD

**Issue by PrantikMondal** [react-native-community/react-native-webview#1155]
I have 
import {Clipboard} from 'react-native'
import { WebView } from "react-native-webview";

Clipboard.getString() not working (App crashing) on some android version like 8.0 or 8.1 while coping something from Webview and device google chrome version is not updated.
While i update chrome to latest version then Clipboard.getString() is working fine.

React Native version:
0.61.5
React Native Webview version:
8.0.1

**Comment by PrantikMondal** [comment]
I am waiting for the response.. Still the issue is there

**Comment by anhvuongtuancerebral** [comment]
hey everyone, has this issue new update? please help me.

**Comment by krishnaTORQUE** [comment]
I am also facing the same issue

**Comment by juliancorrea** [comment]
same here.

**Comment by jagjotsinghparry** [comment]
I am facing the same problem

**Comment by stan-sack** [comment]
+1

**Comment by EsomchiFranklin** [comment]
Facing the same problem. Expo webview crashes when I execute copy command in webview

**Comment by EsomchiFranklin** [comment]
This issue has not been fixed. Any solution yet?

**Comment by Slapbox** [comment]
We're also interested in this.
