### ISSUE TITLE
How Can I set the cookies to be used by a WKWebView?

### ISSUE THREAD

**Issue by SVinay27** [react-native-community/react-native-webview#1158]
**Bug description:**

I'm trying to switch an existing app from UIWebView to WKWebView. The current app manages the users login / session outside of the webview and sets the cookies required for authentication into the the NSHTTPCookieStore. Unfortunately new WKWebView doesn't use the cookies from the NSHTTPCookieStorage. Is there another way to achieve this

**also i referred this [Link](https://github.com/react-native-community/react-native-webview/blob/master/docs/Guide.md#managing-cookies)**

**Environment:**
 - OS: Mac
 - OS version: Catalina
 - react-native version: 0.61.5
 - react-native-webview version:8.0.4

Please help me

**Comment by safaiyeh** [comment]
You can use `@react-native-community/react-native-cookies`. I pull the cookies manually and add it to my request.

**Comment by SVinay27** [comment]
Hello thank you responding...

I am able set cookies for ios by given hint/solution.

But not Android I am still facing problem for android ..

I'm using @react-native-community/cookies.
