### ISSUE TITLE
onMessage is not trigger on Android (working on iOS as well)

### ISSUE THREAD

**Issue by livefuture009** [react-native-community/react-native-webview#1160]
<WebView
          style={{flex: 1}}
          javaScriptEnabled={true}
          domStorageEnabled={true}
          originWhitelist={['*']}
          source={{uri: 'https://slo-v0.netlify.com/'}}              
          injectedJavaScript={`window.ReactNativeWebView.postMessage(JSON.stringify({ listening: 'Sup' }), '*')`}
          onMessage={(event) => console.log(event.nativeEvent.data)}
 />

This is my code to use react-native-webview 8.0.4 now. It's working as well on iOS version.
But on android, onMessage function don't trigger.

What's the reason?

**Comment by haveamission** [comment]
I also am having an issue like this as well.

I have a message on my server side (the site loaded in the webview) that should send a message back like so:

`window.ReactNativeWebView.postMessage("testdsfdsfdsfds");`

However nothing is happening

**Comment by livefuture009** [comment]
Is there any solve way yet? It's very critical issue to make native app for websites now. :(

**Comment by dvicory** [comment]
This feature works for our app in v8.0.4/v8.0.6, can you provide a reproducible example?

**Comment by dvicory** [comment]
I can reproduce with your example, since I found that `window.ReactNativeWebView.postMessage` is not defined until a moment later. But injecting the following JS works:

```js
setTimeout(function() { window.ReactNativeWebView.postMessage('Hello world'); }, 0);
```

What will _not work_ is `window.ReactNativeWebView.postMessage('Hello world', '*')`, as `postMessage` only takes a single argument. It is not the same as the browser interface. If you try that, you will get an error:

![image](https://user-images.githubusercontent.com/1542454/74073997-2f577d00-49c1-11ea-9194-08932f5b7986.png)

We use `window.ReactNativeWebView.postMessage` extensively in our app and haven't found any problems yet so would be curious to hear if these strategies don't work for you.

**Comment by haveamission** [comment]
When trying with your example:

```
      <View style={{ width: "100%", height: "100%" }}>
        <Loading title={this.props.title} text={this.props.text} isLoading={this.state.isLoading} offer={this.props.offer} />
        <WebView
          source={{ uri: this.props.uri }}
          onLoad={this.hideSpinner}
          {... this.props}
          onMessage={this.onMessage}
          mixedContentMode={"always"}
          javaScriptEnable={true}
          injectedJavaScript={setTimeout(function () { window.ReactNativeWebView.postMessage('Hello world'); }, 0)}
        />
      </View>
```

I get (on both iOS as well as Android):

<img width="413" alt="Screen Shot 2020-02-10 at 4 50 08 PM" src="https://user-images.githubusercontent.com/10475533/74193852-21eefc80-4c26-11ea-9bc8-f275196a1275.png">

**Comment by haveamission** [comment]
Apparently setting it as a string works:

```
const injectedJavascript = `setTimeout(function() { window.ReactNativeWebView.postMessage('Hello world'); }, 0);`;

injectedJavaScript={injectedJavascript}
```

**Comment by NightWarrior** [comment]
I faced the same (or similar) issue where android would not trigger the onMessage function. For me it turned out i wasnt sending a string in the postMessage function. 

Fix: 
change `window.ReactNativeWebView.postMessage()`
to `window.ReactNativeWebView.postMessage('')`

**Comment by giacomoalonzi** [comment]
I have the same issue, anyone can help?
on iOS this runs perfectly on android it doesn't.

```
  const injectedJavaScript = `setTimeout(function() { window.ReactNativeWebView.postMessage(data); }, 0);`;
```

**Comment by hamam99** [comment]
got the same issue for android

**Comment by wamry** [comment]
make sure to send a string to `postMessage`, not a number
