### ISSUE TITLE
at android Unable to resolve module `./lib/WebView`

### ISSUE THREAD

**Issue by HusseinElGanzory** [react-native-community/react-native-webview#1163]
**Bug description:**

**To Reproduce:**

**Expected behavior:**

**Screenshots/Videos:**

**Environment:**
 - OS: Mac
 - OS version:
 - react-native version: 6.0
 - react-native-webview version: ^8.0.4

**Comment by HusseinElGanzory** [comment]
i solved by replace lib with src 
`./lib/WebView`
to
`./src/WebView`

**Comment by topherPedersen** [comment]
I had to do the same thing as HusseinElGanzory to get a fork of react-native-webview to work in a react-native init project. I've been following along with the instructions on the Contributing.md page of the docs, but could not get any of this to work until I renamed "lib" to "src" in my fork of react-native-webview.
