### ISSUE TITLE
[iOS] baseUrl not working. local image is not showing up.

### ISSUE THREAD

**Issue by dev-yakuza** [react-native-community/react-native-webview#1165]
**Bug description:**

I use the code below to display a local image to Webview.

```
const imagePath = `${RNFS.DocumentDirectoryPath}/${new Date().toISOString()}.jpg`.replace(/:/g, '-');
const html = `<img src="${imagePath}" style="position: relative; max-width: 100%; max-height: 100%;"/>`;

<WebView
    originWhitelist={['*']}
    allowUniversalAccessFromFileURLs={true}
    allowFileAccessFromFileURLs={true}
    allowFileAccess={true}
    source={{
        html,
        baseUrl: 'file://',
    }}
/>
```

And it works perfectly on Android(emulator, device) and iOS(simulator).
However, not work on iOS device.

the image exists. I can display it with the code below on RN.

```
<Image
    style={{width: 250, height: 250,}}
    source={{
        uri: Platform.OS === 'ios' ?
            imagePath
            : `file://${imagePath}`,
    }}
/>
```

**To Reproduce:**
I couldn't find

**Expected behavior:**
the image is displayed on iOS device.

**Screenshots/Videos:**

**Environment:**
 - react-native version: 0.61.5
 - react-native-webview version: 8.0.4

**Comment by ekkis** [comment]
this component seems unusable but I don't find any alternatives.  I cannot make it work on iOS either.  I've tried numerous ways as recommended on various postings but without success.  I'm on the latest versions of everything

**Comment by ambreesh** [comment]
The same issue facing with all latest version, I need community support and help to fix it.

**Comment by PaulPourtout** [comment]
Same problem here. Using a react app inside a react-native-webview images are displayed on simulator but not on real iOS device.

**Comment by ambreesh** [comment]
I have found a solution for local images rendering in react-native-webview in iOS.
convert the image in base64 then used it's working fine on all iOS devices.

const fs = RNFetchBlob.fs
const imageData = await fs.readFile(`${imageLocalPath}`, 'base64')
const htmlStr =  `<html><body><img src="data:image/png;base64,${imageData} ></body> </html>`
 
return (<WebView
     originWhitelist={['*']}
    source={{ htmlStr }}
    />)

**Comment by gebo96** [comment]
I have the same problem, only instead of an image it's an html file (previously created in React). Has anyone been able to solve this?

**Comment by ekkis** [comment]
> I have the same problem, only instead of an image it's an html file (previously created in React). Has anyone been able to solve this?

the joys of open-source, where an issue never gets any love.  I eventually gave up on this

**Comment by pallaviMN** [comment]
@ambreesh , i am facing similar issue, could you please post your complete answer?
Where should i add image in iOS?

**Comment by leandronorcio** [comment]
I'm currently facing this issue, everything works perfectly on the iOS simulator but on an actual iOS device, no images/css/js files are being correctly resourced by the HTML file.

**Comment by suwu150** [comment]
I have the same problem ， any update
