### ISSUE TITLE
Recaptcha v3 and webview

### ISSUE THREAD

**Issue by morscad** [react-native-community/react-native-webview#1168]
I am using the [Google Recaptcha V3](react-google-recaptcha-v3) library in my webview content, which is a gastby site.

The loaded website works fine on my browsers (Chrome + firefox) and Android devices, it makes the needed requests to the recaptcha API to retrieve the token with no issues.
However, when I test it on iOS emulators, my app opens a link to the google recpatcha api in a new safari browser, switching context from the app.
When I added "google.com" to `onShouldStartLoadWithRequest` and return true, it doesn't open the new browser anymore, but but I get repeated (around 20-30 times) these console logs (using the react native ui-debugger)
```
YellowBox.js:71 
Possible Unhandled Promise Rejection (id: 18):
Error: Unable to open URL: about:blank
Error: Unable to open URL: about:blank
at Object.fn [as openURL] (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:2149:36)
    at Linking.openURL (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:94337:39)
    at openExternalLink (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:125693:28)
```
and when I test on Safari (desktop) I am getting this message also about 30 times:
```
The source list for Content Security Policy directive 'script-src' contains an invalid source: ''strict-dynamic''. It will be ignored.
```
and Recpatcha token retrieval fails

using version: 8.0.3

**Comment by k2xl** [comment]
any resolutions? seeing this too
