### ISSUE TITLE
window.ReactNativeWebView is undefined in v8.0.5

### ISSUE THREAD

**Issue by dingyonglaw** [react-native-community/react-native-webview#1169]
**Bug description:**
`window.ReactNativeWebView.postMessage` is not working in v8.0.5, **it works when I fall back to use v7.4.3** 
Suspect the `window.ReactNativeWebView` is not being injected at all, see below:

**To Reproduce:**
```
<script>
          setTimeout(function () {
            alert(window.ReactNativeWebView); // this should alert [object Object] but now undefined
          }, 2000);
</script>
```

**Environment:**
 - OS: iOS
 - OS version: 13.3
 - react-native version: 0.61.5
 - react-native-webview version: 8.0.5

**Comment by dvicory** [comment]
This feature works for our app in v8.0.4/v8.0.6, can you provide a reproducible example?
