### ISSUE TITLE
It should be possible to set `UserAgent` on iOS WKWebView

### ISSUE THREAD

**Issue by johanforssell** [react-native-community/react-native-webview#117]
[iOS WKWebView supports setting your own user agent](https://developer.apple.com/documentation/webkit/wkwebview/1414950-customuseragent), as Android also does.

This should be exposed. I suggest that the feature fails silently when you use UIWebView.

**Comment by Titozzz** [comment]
#112 Is addressing that I think ?

**Comment by johanforssell** [comment]
Yes, for sure. I had forgotten about that PR :)

**Comment by Titozzz** [comment]
I'll keep this issue open to track the PR status !

**Comment by Titozzz** [comment]
Closing as it was released
