### ISSUE TITLE
onload events are not working, on sites like youtube, when you press on the video

### ISSUE THREAD

**Issue by jejopl** [react-native-community/react-native-webview#1171]
**Bug description:**

Onload events (like `onLoadStart`, `onLoadProgress` etc.) are not working, on sites like youtube when you are changing the url by clicking on the video. I had to downgrade to WebView 6+

**To Reproduce:**

- Set url to youtube.com
- Wait until youtube will load
- Click on the video
- `onLoadStart`, `onNavigationStateChange`, `onLoadProgress`, `onLoadEnd` - none of these will be invoked. It works in WebView version 6

**Expected behavior:**

When you click on the video, you are going to the video page. This should trigger onload events.

**Environment:**
- PC OS: Windows
- PC OS version: 10 64-bit latest 
- Phone OS: Android
 - Phone OS version: 9.0
 - react-native version: 0.61
 - react-native-webview version: 8.0.4

**Comment by vishgoel007** [comment]
Hi @jejopl ,
Did you find any solution ?

**Comment by jejopl** [comment]
@vishgoel007 nope, I had to downgrade to 6.11.1

**Comment by dorw123** [comment]
Any news on fixing the load events ?

**Comment by apswak** [comment]
bad bot

**Comment by jejopl** [comment]
still searching for solutions...

**Comment by lyseiha** [comment]
+1

**Comment by goncalvesej** [comment]
Still nothing?

**Comment by kiennd-miichisoft** [comment]
it still happens to me
