### ISSUE TITLE
.focus() doesn't work in Android

### ISSUE THREAD

**Issue by Jakuubzmeko** [react-native-community/react-native-webview#1172]
**Bug description:**
I am using react native rich text editor on both android and iOS. It uses webview component and it gets some javascript as a source. In the javascript I have defined some html and there ist a div, which is editable. By selecting this div and calling .focus() funcion I can focus it only on iOS not on Android and that's the problem, that after calling focus() in android id doesn't focus and doesn't show keyboard

**To Reproduce:**
I am using this rich text editor: https://github.com/stulip/react-native-pell-rich-editor

**Expected behavior:**
when I call .focus() in js, the div should be focused and show keyboard in android

**Environment:**
 - OS: macOS
 - OS version: 10.15.1
 - react-native version: 0.61.0
 - react-native-webview version: 8.0.5

**Comment by sgtpepper43** [comment]
I'm having the same problem. There _is_ a `requestFocus` you can call on the webview itself that _should_ work, but, at least for me it's not working.

**Comment by stoica94** [comment]
We also have the same problem. We did a workaround where we put above the editor a `TextInput` as a title which is initially focused but when we change focus from the React Native TextInput to the Webview from `pell-rich-editor`, they keyboard just dismisses. We also wrapped everything in a scrollview with `keyboardShouldPersistTaps={'always'}` and `keyboardDismissMode={'none'}` but it didn't fix the problem

**Comment by Nice-zrd** [comment]
I tried to call `requestFocus` in the `onLoad` method, which is not easy to use, but I put it in `setTimeout` and gave it a 100 millisecond delay to solve Android's focus.
`if (Platform.OS != 'ios') {
                setTimeout(() => {
                    webView.requestFocus();
                }, 100);
            }`

**Comment by Nice-zrd** [comment]
> We also have the same problem. We did a workaround where we put above the editor a `TextInput` as a title which is initially focused but when we change focus from the React Native TextInput to the Webview from `pell-rich-editor`, they keyboard just dismisses. We also wrapped everything in a scrollview with `keyboardShouldPersistTaps={'always'}` and `keyboardDismissMode={'none'}` but it didn't fix the problem

I have the same problem as you. When you switch the cursor from `Textinput` to `webView`, the keyboard will be hidden. You need to click WebView again to pop up the keyboard and wait for the problem to be solved.

**Comment by Slapbox** [comment]
Is it _theoretically_ possible to make this work? Or will Android refuse to open the keyboard and that's beyond our control?

**Comment by rmanalo-getdevs** [comment]
i'm having the same problem

**Comment by AndreySierra** [comment]
Please solve this :(

**Comment by rojo2530** [comment]
Yes, in IOS work OK, but not in Android.

**Comment by jamonholmgren** [comment]
We'd love some help solving this issue from the community. Post a link to the PR here if you submit one. Thank you!

**Comment by jamonholmgren** [comment]
Oops, didn't mean to close this.

**Comment by wxik** [comment]
@stoica94 @Jakuubzmeko  @Nice-zrd 
pell-rich-editor publish `1.0.9-beta.0` Based on the `1.0.8` experimental processing method（Android only）
#https://github.com/stulip/react-native-pell-rich-editor/commit/db17f73bd1d5db6540d03ec0615b0d2c8fddfe3e

Can refer to`pell-rich-editor` example

**Comment by Slapbox** [comment]
The pell-rich method can only work in non-Expo apps, as Expo can't control keyboard visibility.

**Comment by wxik** [comment]
> The pell-rich method can only work in non-Expo apps, as Expo can't control keyboard visibility.

@Slapbox **`1.0.9-beta.1`** fix Expo android keyboard open


**Environment**:

- OS: macOS
- OS version: 10.15.5
- expo version: ~38.0.8
- react-native-webview version: ^9.4.0

**Comment by Slapbox** [comment]
I haven't given it a test, but wow that's crazy! 

How did you manage that @wxik? I took a look at [the code here](https://github.com/stulip/react-native-pell-rich-editor/commit/c7a6c3a1225f6275626e4275d41d0417e52a5460#diff-45158efb69bb48994e8fdae1ae787647), but I don't quite understand how works.

**Comment by wxik** [comment]
@Slapbox 

A TextInput of size 1 and invisible is used, the TextInput Keyboard of focus will be opened, and then the focus in the webview is triggered, at this time the keyboard will remain open

**Comment by Slapbox** [comment]
@stulip thanks for the explanation! 

If I understand correctly, it's not that Android users can't focus the `webview`, it's just that the focusing of the `webview` doesn't trigger the keyboard to show? I won't get to give this a try for a while, but I'm excited. Thanks again for sharing!

**Comment by Slapbox** [comment]
Not stale.

**Comment by ammarahm-ed** [comment]
You need to manually open the keyboard after the input is focused on android. It cannot be done automatically. A simple method on Native Side can do this probably. 

```java
public static void showKeyboard(FragmentActivity activity) {
        InputMethodManager inputMethodManager = (InputMethodManager) activity.getSystemService(Context.INPUT_METHOD_SERVICE);
        inputMethodManager.toggleSoftInputFromWindow(activity.getCurrentFocus().getWindowToken(), InputMethodManager.SHOW_FORCED, 0);
    }
```

**Comment by Slapbox** [comment]
@ammarahm-ed thanks for sharing! That seems very useful, but it's not something Expo users can leverage. It would be great if this was built into React Native Webview.

**Comment by Slapbox** [comment]
While there is a functional workaround, it's really quite onerous to implement. I don't think this issue should be closed.

**Comment by zaiisao** [comment]
I want to leave a comment here to write about my own approach to solving this problem, and although it is quite hacky, it seems to work like a charm.

1. In the component with the `WebView`, also put in a `TextInput` with `autoFocus` set to `true`
2. In `componentDidMount`, call `requestFocus` on the `WebView` component
3. When `onLoad` of the `WebView` component is fired, get the rich text editor (I'm using QuillJS) to focus (in my case, QuillJS's `focus` function) to focus with `postMessage` triggering the HTML page to do so
4. Get another message sent back to React Native once focusing is applied
5. Set a boolean in the component's state that would cause the `TextInput` with `autoFocus = true` to be removed

I'm treating this solution with a grain of salt, but it seems to work. The temporary `TextInput` kicks the keyboard open, and from there we can switch the focus to the `WebView` component with the rich text editor input already focused, and everything seems to work like a charm. I'm still going to be treating this solution with a grain of salt in case if anything weird happens in the future, but this allowed me to be able to solve the problem without digging into Java.

**Comment by hongquan281096** [comment]
Dear everyone, I'm having the same issue. I need helppppppppppppppppppppp!!!

**Comment by ChinhLT** [comment]
I can fixed this issue on Android.
I am use that rich text for edit html, toolbar with action foreColor to set text color.
When click on action foreColor, I used:
**richText.current?.blurContentEditor(); => to dismiss web keyboard.
setTimeout(() => {
      setIShowModalColor(true); => to open color picker modal
    }, 100); => must delay**
Then selected color from modal: 
**setIShowModalColor(false); => hide modal
setTimeout(() => {
                  richText.current?.focusContentEditor(); => focus web input
                  richText.current?.setForeColor(selectedHTMLColor);
                }, 100); => must delay**
=> And on Android keyboard auto focus and open OK.
setTimeout 100 is working.

**Comment by arunim2405** [comment]
This should be neither stale nor closed, this is still very much an issue

**Comment by realityexpander** [comment]
Here is the workaround solution I came up with based on `zaiiso`'s suggestions:

// in `TextEditor.tsx` component
```
    const webviewRef = useRef<WebView>(null);
    const [isKeyboardVisible, setIsKeyboardVisible] = useState<boolean>(false);
    const [isTextEditorLoadCompleted, setIsTextEditorLoadCompleted] = useState<boolean>(false);

useEffect(() => {
        // focus on the webview to show keyboard on Android
        if (Platform.OS === 'android') {
            if (webviewRef.current) webviewRef.current.requestFocus();
        }
    }, []);

 useEffect(() => {
        const keyboardDidShowListener = Keyboard.addListener('keyboardDidShow', () => {
            setIsKeyboardVisible(true);
            setIsTextEditorLoadCompleted(true);
        });
        const keyboardDidHideListener = Keyboard.addListener('keyboardDidHide', () => {
            setIsKeyboardVisible(false);
        });

        return () => {
            keyboardDidHideListener.remove();
            keyboardDidShowListener.remove();
        };
    }, []);

    // Workaround to get keyboard to show when TextEditor is opened (on Android.)
    // - This is a currently a hack, but it works for now.
    // - Issue is officially "closed" on react-native-webview, but was not fixed/resolved. *shrug*
    // - https://github.com/react-native-webview/react-native-webview/issues/1172#issuecomment-810219790
    const showKeyboardOnAndroidWorkaround =
        Platform.OS === 'android'
            ? !isTextEditorLoadCompleted && (
                  <TextInput
                      autoFocus={true}
                      style={{
                          display: 'none',
                          width: 0,
                          height: 0,
                          position: 'absolute',
                          flex: 1,
                          top: 0,
                          left: 0,
                      }}
                  />
              )
            : null;

    return (
        <View style={[{flex: 1}, animatedStyles]}>
            {showKeyboardOnAndroidWorkaround}
            <WebView
                key={'TextEditor'}
                allowFileAccessFromFileURLs={true}
                ref={webviewRef}
                automaticallyAdjustContentInsets={true}
                source={{html: textEditorHTML}}
                bounces={false}
                overScrollMode="never"
                style={[{backgroundColor: 'transparent', maxHeight: 510}]}
                originWhitelist={['*']}
            />
        </View>
```

**Comment by canlongdifisoft102** [comment]
@realityexpander You look as old as your experience

**Comment by ovistoica** [comment]
@canlongdifisoft102 That is a very inappropriate response here
