### ISSUE TITLE
onClick inside webview not working

### ISSUE THREAD

**Issue by eeeman1** [react-native-community/react-native-webview#1175]
**Bug description:**

If you put a site created on a react in a webview that has elements with a onClick event handler, then such events will not work. When you click on an item, nothing happens

**To Reproduce:**

Add to the webview the address of the site made on the reaction in which there is an element with a onClick event handler. Open the app. When you are on the site, try clicking on an element that has an event onClick handler. You will notice that nothing is happening. If you open the same site in any mobile browser, then everything works well.

**Expected behavior:**

I expect that a site open in an application using webview will work just like it does in a browser. When you onClick on an element with an event handler, a onClick will start the function assigned to it.

**Environment:**

OS: Android, ios
OS android version: 6.0.0 - 9, ios 12 - 13
react-native version: 0.61
react-native-webview version: 8.0.4

**Comment by vovkasm** [comment]
On macOS Safari can debug javascript in webviews, can you try to open app in simulator, open Safari and connect to webview, then click on non-working links and see any output in console?

**Comment by eeeman1** [comment]
I do not have a macOS

**Comment by feruzm** [comment]
It does indeed happen on some Android devices, not emulators.
@eeeman1 Can you try to click on those links faster? Like tap on them really quick and see if it fires?

**Comment by eeeman1** [comment]
> 
> 
> It does indeed happen on some Android devices, not emulators.
> @eeeman1 Can you try to click on those links faster? Like tap on them really quick and see if it fires?

I tried to tap very quickly and very many times, sometimes it turned out after 100 attempts

**Comment by feruzm** [comment]
@eeeman1 are you using webview inside TouchableOpacity or something similar?

**Comment by xtebs** [comment]
Since I updated react-native >0.60, the webview is an external module. 
`import WebView from "react-native-webview"`
Since then, I could not click anything inside my webview. I wonder if the javascript inside the html `<script src="external_url:/something.js"></script>` is being loaded

**Comment by shariffaraz** [comment]
Anyone found the cause of the issue? and is anyone able to solve this issue?

**Comment by Balasnest** [comment]
Its **BREAKING**. I couldn't able to click anything inside my webview.  @eeeman1 @xtebs Did you manage to get it to work?

**Comment by mohamed-sultan** [comment]
@shariffaraz @Balasnest did you find any solution

**Comment by SainagChunduru** [comment]
Please open the issue. 

Do anyone found solution for this?

**Comment by mohamed-sultan** [comment]
@SainagChunduru  for ios it works fine for android i had to put it inside modal the problem appear when putting the webview inside scroll view

**Comment by SainagChunduru** [comment]
@mohamed-sultan I have a webview inside a modal. Its not working in iOS also.

**Comment by mostafero** [comment]
Here a working solution that worked very well for me (also posted on stackoverflow)
`window.postMessage` doesn't work for me for current last version. And found many other solutions that maybe worked for someone in some version but not for me.

Anyway, I could come up with a solution that uses `window.ReactNativeWebView.postMessage` and doesn't need to wait the click result, check it:

My current libraries versions:
```JSON
"react": "16.13.1",
"react-native": "0.63.3",
"react-native-webview": "^11.0.2",
```

**Note: that I am using html string instead of url**

```javascript
<WebView
    bounces={false}
    showsHorizontalScrollIndicator={false}
    showsVerticalScrollIndicator={false}
    javaScriptEnabled={true}
    originWhitelist={['*']}
    source={{ html }}
    onLoadEnd={this.onLoadEnd}
    onError={this.onError}
    mixedContentMode={'never'} // security
    startInLoadingState={true} // when starting this component
    onMessage={onMessage}
    javaScriptEnabledAndroid={true}
/>
```

```javascript
onMessage = (message: string) => {
    console.log('action result coming from the webview: ', message);
};
```
And in the `html` string I added the script below and set the `onclick` for a given html `button` or `a` tag:
```html
...
<div>
    <button onclick="clickYourButton([PASS SOME STRING DATA HERE])">Click</button>
</div>
...
<script type="text/javascript">
    function clickYourButton(data) {
        setTimeout(function () {
            window.ReactNativeWebView.postMessage(data)
        }, 0) // *** here ***
    }
</script>
```
Some very important notes:
- Data to be passed to the `postMessage` func should be `string` type
- I set 0 for `timeout` to let the `postMessage` the last in the pile to execute and ofc I avoid waiting.

**Comment by Naroh091** [comment]
This is still happening in Android.

**Comment by hackhackhackhackhack** [comment]
I solved this problem.
It maybe has something to do with Webview type.
My device has 2 options about webview. -  Chrome WebView / Android System WebView
Default settiong was Chrome WebView on my device.
If changed to Android System WebView type, it will be worked.

I recommand this video.-> https://www.youtube.com/watch?v=g3CX6qLPb1U

**Comment by OxamaHxn** [comment]
Does any one have a solution?

**Comment by elbarryamine** [comment]
in my case I was using the **Webview** inside the modal from **react-native-modalize** which cause the same issue you are having. However, it worked when I placed the webview inside a regular screen. i could not find why modalize causing this issue so i decided to just use it this way.

clicking on android not working this way

`  <Modalize
        ref={ref}
        adjustToContentHeight={true}
        handlePosition="inside"
        modalStyle={styles.modalStyle}
        childrenStyle={{paddingVertical: 20}}
        >
        <MyWebView />
      </Modalize>`

clicking on android worked this way

`<Stack.Screen
          name="web-view"
          component={MyWebView}
          options={{presentation: 'modal', headerShown: false}}
        />`


Please let me know if you were able to use it inside of Modalize Modal, even if it has been a while.

**Comment by kellykels21** [comment]
This issue is closed but is still a problem i'm still facing this problem in my mobile app. I am using Google maps within the WebView and trying to click on markers on the map, I have a click event on these markers that works in the desktop chrome browser but not via the react-native-webview.

I can drag the map around on mobile but when i click it makes the markers blink but nothing happens.

Are there any updates on this?

**Comment by OxamaHxn** [comment]
> 

https://stackoverflow.com/a/72555083/16607002

**Comment by stefoid** [comment]
> It does indeed happen on some Android devices, not emulators. @eeeman1 Can you try to click on those links faster? Like tap on them really quick and see if it fires?
> 
> I am currently looking ways to solve this as well, but so far I found sometimes quick click fires the click event. Would be curious to see if it works for you as well, if it does maybe that's starting point to see what might be the bug... I have multiple instances of webview on same page, first instance works fine but subsequent instances with separate js script doesn't.
> 
> This is react related but maybe helps to identify cause in react native webview [facebook/react#17258](https://github.com/facebook/react/issues/17258)

YES.  This is indeed the issue for me.  if I tap on the link in a relaxed normal fashion, it probably doesnt work.

If I make an effort to be an olympic speed quick touchdown and release, it always works

**Comment by stefoid** [comment]
I should add, I dont necessarily see this as a react-native-webview problem specifically - its could be a browser engine problem.

However, I lack the expertise to work out what is going on and how to fix it.

suggestions welcome

**Comment by hamza-choudhary** [comment]
for me its working fine on android devices but on ios i am not able to click on menus or button its does not work.

**Comment by pawanja** [comment]
SAME,

for me its working fine on android devices but on ios i am not able to click on menus or button its does not work however links are working.

**Comment by Nishanth-123** [comment]
I'm facing the same issue. I tried replacing my content with simple button inside webview and firing alert on click. 

the same issue persists.

**Comment by lul-g** [comment]
having similar issue whats the fix

**Comment by lul-g** [comment]
i added the following to the webview and it worked
`javaScriptEnabled
domStorageEnabled
nestedScrollEnabled={true}`
