### ISSUE TITLE
No way to load JS files

### ISSUE THREAD

**Issue by v0lume** [react-native-community/react-native-webview#1178]
**Bug description:**
Im creating port of AmCharts for react-native using @rn-community/rn-webview to render webview and show charts in it.
Facing error when Im trying to load main amcharts.js file in injected js code:
```
Error: 'src/components/AmCharts/amcharts-files/amcharts.js' cannot be loaded as its extension is not registered in assetExts
```

**To Reproduce:**
```
const runFirst = `
    function loadScripts(file, callback) {
      var xhttp = new XMLHttpRequest();

      xhttp.onreadystatechange = function() {
        if (this.readyState == 4 && this.status == 200) {       
          var amcScript = document.createElement('script');
          amcScript.innerHTML = this.responseText;
          document.body.appendChild(amcScript);

          if (callback) {
            callback.call();
          }
        }
      };

      xhttp.open("GET", '${scriptsPath}' + file + '.js', true);
      xhttp.send();
    }
    
    loadScripts('amcharts', () => alert('ok'));
    `;

<WebView
          source={amchartsLayout}
          originWhitelist={['*']}

          injectedJavaScript={runFirst}
          mixedContentMode="always"
          allowFileAccessFromFileURLs
          automaticallyAdjustContentInsets
          allowFileAccess
          javaScriptEnabled
          domStorageEnabled
          useWebKit
/>
```

**Expected behavior:**
Js would be loaded properly without any errors.

**Investigation:**
Guys had same problems when they trying to use highcarts-react-native lib with this @rn-community/rn-webview package:
https://github.com/highcharts/highcharts-react-native/issues/4
https://github.com/highcharts/highcharts-react-native/issues/8

**Environment:**
 - OS: macos, iOS
 - OS version:  iOS 13
 - react-native version: 0.61
 - react-native-webview version: 8.0.5

**Comment by v0lume** [comment]
Also I tried to to extend metro.config to support loading js extension:
```
const defaultAssetExts = require('metro-config/src/defaults/defaults').assetExts;

module.exports = {
  transformer: {
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: false,
      },
    }),
  },
  resolver: {
    assetExts: [
      ...defaultAssetExts,
      'js'
    ],
  },
};
```

in this case Im getting error 

![image](https://user-images.githubusercontent.com/5075100/73462245-89868b80-438c-11ea-9791-2866ff26102a.png)

**Comment by ControlAltDel01** [comment]
Have anyone found a solution?

**Comment by Umesh079** [comment]
Any solution ?? I have got to show presentation which is in HTML, lots of CSS, lots of js in webview. I am not able to find any workaround. Please check.

**Comment by drager** [comment]
This is still an issue...

**Comment by V-in** [comment]
> Any solution ?? I have got to show presentation which is in HTML, lots of CSS, lots of js in native ios webview. I am not able to find any workaround. Please check.

I’ve had some success using https://www.npmjs.com/package/inliner . If you in-line all css and js into your html file you take metro out of the equation. 

With metro I managed to get rid of errors by changing my .js asset files to a custom extension ( webviewjs ) and adding that to package extensions options on metro config. You can’t add .js to the whitelist because it will try loading some react native files as assets instead of modules all goes haywire. Even with no erros my page was not loading correctly though so I tried inlining and it worked! I’m running on expo btw

**Comment by drager** [comment]
> Before this approach I managed to get rid of errors by changing my .js asset files to a custom extension ( webviewjs ) and adding that to package extensions options on metro config. You can’t add .js to the whitelist because it will try loading some react native files as assets instead of modules all goes haywire. Even with no erros my page was not loading correctly though so I tried inlining and it worked! I’m running on expo btw

I tried using `.webviewjs` as well but that doesn't work as you say. That's because Safari will complain about no-sniff i.e. Refused to execute http://127.0.0.1:19001/assets/assets/file.webviewjs as script because "X-Content-Type: nosniff" was given and its Content-Type is not a script MIME type...

**Comment by Umesh079** [comment]
Also we are getting these js and CSS files dynamically , we cant change extension manually.

**Comment by drager** [comment]
> Also we are getting these js and CSS files dynamically , we cant change extension manually.

Yeah, same here!

**Comment by drager** [comment]
@Titozzz @jamonholmgren Why is this being closed? The issue isn't resolved...

**Comment by jamonholmgren** [comment]
@drager It was our stale bot that closed it.

**Comment by ugar0ff** [comment]
This is still an issue. Any solution?

**Comment by fukemy** [comment]
any solution ? plz

**Comment by pmprete** [comment]
Same issue here for IOS 8
