### ISSUE TITLE
Image in webview on Android not shown

### ISSUE THREAD

**Issue by udarts** [react-native-community/react-native-webview#118]
I am using a webview to display custom html taken from Cloud FireStore. In some cases there is an image in that html. On iOS the image shows, but on Android the image is not shown. I just get the alt text.

This is the image tag inside the html:
`<img src="https://firebasestorage.googleapis.com/v0/b/sjaloom-connect.appspot.com/o/images%2Fdcf8ab78-e98f-46db-bdae-eab7b18ded1a.jpg?alt=media&token=e654671a-4320-464a-b1fd-7236170d48f7" alt="undefined" style="float:none;height: 100px;width: 120px"/>`

Is this a bug in webview or is there a setting I miss.

React Native Environment Info:
System:
OS: macOS High Sierra 10.13.6
CPU: x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
Memory: 24.10 MB / 16.00 GB
Shell: 3.2.57 - /bin/bash
Binaries:
Node: 11.0.0 - /usr/local/bin/node
npm: 6.4.1 - /usr/local/bin/npm
Watchman: 4.9.0 - /usr/local/bin/watchman
SDKs:
Android SDK:
Build Tools: 27.0.3, 28.0.2, 28.0.3
API Levels: 19, 21, 22, 23, 24, 25, 26, 27, 28
IDEs:
Android Studio: 3.2 AI-181.5540.7.32.5056338
Xcode: /undefined - /usr/bin/xcodebuild
npmPackages:
react: 16.6.0-alpha.8af6728 => 16.6.0-alpha.8af6728
react-native: 0.57.4 => 0.57.4
npmGlobalPackages:
react-native-cli: 2.0.1
react-native-git-upgrade: 0.2.7

**Comment by Titozzz** [comment]
I actually have no idea, does this work when you import WebView directly from react-native or is that a regression on this repo ?

**Comment by udarts** [comment]
@Titozzz, nope same issue. Are there some characters in the img code above that webview doesn't like?

**Comment by Titozzz** [comment]
No. You can access the chrome debugger inside the webview and check if there are any error ? https://github.com/react-native-community/react-native-webview/blob/master/docs/Debugging.md

**Comment by udarts** [comment]
No error shown.

**Comment by Titozzz** [comment]
And is the HTML loaded?

**Comment by udarts** [comment]
I did some more digging and found the follow in Android Studo:

Cannot call determinedVisibility() - never saw a connection for the pid

This message appears together with the html, so I guess it has something to do with the issue.

**Comment by udarts** [comment]
Is there an idea on how to fix this?

**Comment by Titozzz** [comment]
Have you tried this:
https://stackoverflow.com/questions/33083066/android-webview-cannot-call-determinedvisibility-never-saw-a-connection-for

**Comment by udarts** [comment]
Thanks for your reply, I have tried it, but still the image is not showing inside the website, it still only shows the alt text.

**Comment by jamonholmgren** [comment]
@udarts Can you publish a minimal app that reproduces this issue so we can clone and look at it? Thank you!

**Comment by udarts** [comment]
@jamonholmgren I will try to provide it this week.

**Comment by afilp** [comment]
I have the same problem, in Android, using the latest React Native version (0.57).

**Comment by udarts** [comment]
@jamonholmgren will try to add a minimal repo today

**Comment by udarts** [comment]
@jamonholmgren, hereby the snack.expo (only it has an issue with native code for the webview, don't know why), so you have an idea on the setup and you can try it yourself on an android device: https://snack.expo.io/@udarts2/webview

**Comment by udarts** [comment]
@jamonholmgren any idea on this issue?

**Comment by Titozzz** [comment]
from your example: 

```
      <View style={styles.container}>
        <WebView 
          originWhitelist={['*']}
          ref={WEBVIEW_REF}
          automaticallyAdjustContentInsets={false}
          source={{ html: "https://firebasestorage.googleapis.com/v0/b/sjaloom-connect.appspot.com/o/images%2Fdcf8ab78-e98f-46db-bdae-eab7b18ded1a.jpg?alt=media&token=e654671a-4320-464a-b1fd-7236170d48f7"}}
          javaScriptEnabled={true}
          domStorageEnabled={true}
          startInLoadingState={true}
        />
      </View>
```

You cannot just set HTML like that. If you want to retrieve code from your server, I guess you want to use it as an URI ? Else you need to use actual HTML code with the <img> tag and all.

**Comment by Titozzz** [comment]
By the way you cannot use that repository with expo so it's not possible to make reproductions using snack

**Comment by udarts** [comment]
@Titozzz Sorry I forgot the html markup. Originally the data I get from Firestore is html (saved like that). So basically what the above code with be is something like:

```javascript
<View style={styles.container}>
        <WebView 
          originWhitelist={['*']}
          ref={WEBVIEW_REF}
          automaticallyAdjustContentInsets={false}
          source={{ html: "<img src="https://firebasestorage.googleapis.com/v0/b/sjaloom-connect.appspot.com/o/images%2Fdcf8ab78-e98f-46db-bdae-eab7b18ded1a.jpg?alt=media&token=e654671a-4320-464a-b1fd-7236170d48f7" alt="undefined" style="float:none;height: 100px;width: 120px"/>"}}
          javaScriptEnabled={true}
          domStorageEnabled={true}
          startInLoadingState={true}
        />
      </View>
```

And that code doesn't display the image on an android device, it does on iOS.

Cheers

**Comment by Titozzz** [comment]
Can you try with that prop : allowUniversalAccessFromFileURLs

**Comment by udarts** [comment]
Already have that set to true, no difference.

**Comment by udarts** [comment]
> I did some more digging and found the follow in Android Studo:
> 
> Cannot call determinedVisibility() - never saw a connection for the pid
> 
> This message appears together with the html, so I guess it has something to do with the issue.

This seems to be the most likely reason why it is failing to show the image, no idea on how to fix this though.

**Comment by gaohan1994** [comment]
try this

mixedContentMode="compatibility"

**Comment by gaohan1994** [comment]
hi there
if you use html
It's better to set up a complete HTML like this 
```
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no">
    
    <title>cceos</title>
  </head>
  <body>
<img src="your img source" />
</body>
</html>
   ```

**Comment by Danelund** [comment]
was this ever fixed? am facing same issue

**Comment by mjaradat** [comment]
still searching for solutions

**Comment by hoonblizz** [comment]
No solution here? Facing the same issue. 
Works (nearly) perfectly on iOS but not on Android 9.

**Comment by hoonblizz** [comment]
Never mind. It works great. 
The issue for me was, I was using Google Static Map and setting 'Size' property was the issue. 
Size property must be integers.

**Comment by Beissner** [comment]
Still searching for solutions

**Comment by WilbertJanney** [comment]
Me too, it a URI set to a URL that downloads an image works in iOS, but not on Android.

**Comment by Declan-Mertens** [comment]
I'm suffering from the same issue.

**Comment by dondragon2** [comment]
+1

**Comment by jamonholmgren** [comment]
We'd love help solving this issue from those who are reporting it. Refer to this issue in your PR. Thank you!

**Comment by tien6597** [comment]
i think i have same issue with you. I use webview to show image from HTML code. Some image link working and some error. I think it depend on Image Link
WORKING: https://s3-ap-southeast-1.amazonaws.com/bework-test/wiki/document/district/6/2020/7/1/1905995386_1593592533946.png
ERROR: https://storage.googleapis.com/slite-api-files-production/files/197346c9-fa22-4713-84df-3379f92c3e73/Screenshot%25257%25251%25252020.png
Which link have "%" then it don't working, same as you

**Comment by lmint1** [comment]
I had a similar issue, and I think that was some issue with the certificate.
And that worked for me:
```
webView.webViewClient = object : WebViewClient() {              
    //Intercepts SslError and proceed
    override fun onReceivedSslError(view: WebView?, handler: SslErrorHandler?, error: SslError?) {
        //try to print SslError to find out what's happening
        println(error)
        handler?.proceed()                                                                        
    }                                                                                             
}                                                                                                 
```

**Comment by JongtaekChoi** [comment]
@lmint1 It worked for me too!

**Comment by phuwin95** [comment]
> I had a similar issue, and I think that was some issue with the certificate.
> And that worked for me:
> 
> ```
> webView.webViewClient = object : WebViewClient() {              
>     //Intercepts SslError and proceed
>     override fun onReceivedSslError(view: WebView?, handler: SslErrorHandler?, error: SslError?) {
>         //try to print SslError to find out what's happening
>         println(error)
>         handler?.proceed()                                                                        
>     }                                                                                             
> }                                                                                                 
> ```

Where do you add these?

**Comment by lmint1** [comment]
@phuwin95 It was in a native project. Sorry but I don't know how to fix it in React Native. 
Take a look in this PR, maybe it can be useful:
https://github.com/react-native-community/react-native-webview/pull/1450#issue-432207455

**Comment by mazorvanunu** [comment]
any news about the issue? failed to get image on iphone..
ignore ssl fixed it but now on later version no ignore ssl?

**Comment by mzain512** [comment]
> try this
> 
> mixedContentMode="compatibility"

Worked for me on android.

**Comment by geragt280** [comment]
> try this
> 
> mixedContentMode="compatibility"

I tried this and it worked on the emulator but when created an Apk and ran it on the real device the issue was same. No images got loaded and showing alternative name or empty image boxes.

**Comment by JamesDHW** [comment]
If you look at the android props there's also a `mixedContentMode` prop which you can set to `"always"` if you trust the site you're getting content from which allows it to load media - worked for me

**Comment by elie-chaaban** [comment]
the images are being loaded in Expo Go app but when using APK no

**Comment by ggmartins091** [comment]
Having this same issue with images loaded from firebase storage.

**Comment by aliceni81** [comment]
That's because Android emulator cannot access the internet.
Solution: https://stackoverflow.com/questions/42736038/android-emulator-not-able-to-access-the-internet/49332186#49332186
