### ISSUE TITLE
Webview does not display anything incrementally before fully downloaded/rendered

### ISSUE THREAD

**Issue by alancwoo** [react-native-community/react-native-webview#1180]
**Bug description:**
The component seems to wait to fetch the entire DOM and execute all the javascript before it displays. Is there no way to have it load incrementally/progressively as in Safari/Chrome?

I see this mentioned in #128 - which seems to be closed due to the default caching, but on initial load, it still seems only to display after the entire DOM has been rendered and thus appears to be incredibly slow, if not frozen at times (especially if a page is media heavy and includes video for example).

My main question: is there a reason it is unable to display before the DOM is fully rendered?

**To Reproduce:**
Load a remote URL into webview

**Expected behavior:**
The page displays while loading.

**Screenshots/Videos:**

**Environment:**
 - OS: iPhone 6s plus, iphone 11 simulator
 - OS version: 13.3
 - react-native version: 0.61.5
 - react-native-webview version: 8.0.3

**Comment by mharrison-nzme** [comment]
Also experiencing this exact issue. While using the startInLoadingState prop, external sites are taking up to 10 seconds to load, and then pop in fully rendered.
I can remove the startInLoadingState prop and it renders slightly faster, but then the user is left without visual feedback

**Comment by pxmage** [comment]
> Also experiencing this exact issue. While using the startInLoadingState prop, external sites are taking up to 10 seconds to load, and then pop in fully rendered.
> I can remove the startInLoadingState prop and it renders slightly faster, but then the user is left without visual feedback

@mharrison-nzme  thanks for your information, I removed `startInLoadingState` props and it did render faster, and just like you said, now I'm giving users a blank page with no feedback.

I'll have to draw a progress bar on my own from scratch, which really sucks  :(

**Comment by chrisbobbe** [comment]
https://github.com/react-native-community/react-native-webview/blob/master/docs/Reference.md#onloadprogress at least gives you a number about the progress; 0 through 1 on iOS ([doc](https://developer.apple.com/documentation/webkit/wkwebview/1415007-estimatedprogress)) (not sure about Android).

**Comment by arthur-sousa** [comment]
I also observed the same behaviour. The component seems to only display after fetching the entire DOM and executing all the JS. Has anyone found a way to load partially/incrementally/progressively like most browsers usually do?

**Comment by khalloud** [comment]
We have the same issue. Does anyone know of a solution to this?

**Comment by fungmo** [comment]
+1
