### ISSUE TITLE
can i set connection timeout value?

### ISSUE THREAD

**Issue by JamesJs** [react-native-community/react-native-webview#1182]

**Comment by jameswilddev** [comment]
I've also looked for such a feature and not found one.

**Comment by giautm** [comment]
I'm also looking for this feature. I use WebView to embed payment gateway, if it take too long (> 5s), I want to cancel request then reload page.

**Comment by JamboProduction** [comment]
I'm also looking for this feature :)

**Comment by Marian0** [comment]
Same here. It will be very helpful !

**Comment by 1awaleed** [comment]
It would be a helpful feature.

**Comment by web3Liuwentong** [comment]
It would be helpful!

**Comment by cblaze22** [comment]
Is this available yet? Its unacceptable to wait 2 minutes for a page to load and timeout.

**Comment by fe-jcorreia** [comment]
Why was this issue closed? Did not find the resolution to this

**Comment by iamandiradu** [comment]
> ```tsx
> hasEncounteredTimeout
> ```

Having *hasEncounteredTimeout* as a useEffect dependency will lead to a 'too many re-renders' error. :)
