### ISSUE TITLE
onLoad,onLoadEnd,onLoadStart events are not fired

### ISSUE THREAD

**Issue by sandeepg1220** [react-native-community/react-native-webview#1185]
onLoad,onLoadEnd,onLoadStart events are not fired.
 - react-native version:0.61.5
 - react-native-webview version:7.5.2

**Comment by jschenkDD** [comment]
+1

**Comment by mathieu-ouvrard** [comment]
what did you try ? what did you write ? what page are you trying to load ? did it work on a previous version ? it's working for me (not as expected but events are somehow fired)

**Comment by tanoabeleyra** [comment]
Not working for me either on version **8.1.2**, load events are not fired at all.

**Comment by mehul2013** [comment]
In my side, sometimes onLoadStart is not called but others like onLoad, onLoadEnd, onLoadProgress are working. And the issue is Html content is not rendering in Webview, it shows blank page sometimes.
Any solution for that?

**Comment by sandeepg1220** [comment]
@mehul2013 Yes, even me too showing blank page when html content is rendering. Any solution?

**Comment by samuelasd** [comment]
Same problem here, they are not firing using RN 61.5

**Comment by jeswcollins** [comment]
same

**Comment by AnLuoRidge** [comment]
In my case, these callbacks fail to fire if your webpage is jumping to an HTTP website.

**Comment by k2xl** [comment]
Anyone figure this out? having same issue

**Comment by Atheane** [comment]
Same here
