### ISSUE TITLE
Expo SDK36: Error Code: -1

### ISSUE THREAD

**Issue by faqi** [react-native-community/react-native-webview#1186]
My **Expo App's** entry point code:
```
import React from 'react';
import { WebView } from 'react-native-webview';

export default App = () => (
    <WebView
        originWhitelist={['*']}
        source={{ uri: 'https://www.google.com' }}
    />
);
```

but when i run it, i get following error:

```
Encountered an error loading page, Object {
  "canGoBack": false,
  "canGoForward": false,
  "code": -1,
  "description": "net::ERR_CACHE_MISS",
  "loading": false,
  "target": 3,
  "title": "Web page not available",
  "url": "https://www.google.com/",
}
```
..
**NOTE:** My Android phone is connected to wifi, and internet is reachable, still the `Web page not available error` with `code: -1`.

**My Environment:**
Android phone (Android version 5.1.1),
EXPO SDK version is 36,
react-native-webview version 8.0.6,
Expo client app version 2.14.0

**PS:** For `react-native-webview`, **I didn't do `npm install --save react-native-webview`** , **instead i did `expo install react-native-webview`** **with expo-cli version 3.11.7**

**PPS:** I tried running the expo snack of webview from https://snack.expo.io/@wodin/webview-example (official?) on my phone via QR code scan, yet got the same error, `"code": -1`.

Can someone guide how to get rid of this error and get the webview up and running?

**Comment by grunch** [comment]
I have the same issue, this issue should not be closed

**Comment by dysuryawanshi** [comment]
Getting error 
Eroor loading page, Domain undefined, Error code -1 ERR_CACHE_MISS,  
please update as soon as possible. We are having live app facing issue
