### ISSUE TITLE
Cant Download Zip Files on iOS 

### ISSUE THREAD

**Issue by Krypternite** [react-native-community/react-native-webview#1187]
**Bug description:**
Not able to download **zip** and other file formats on iOS .

**To Reproduce:**

**Expected behavior:**
When I click the download link, the download should start. The download starts on Android but on iOS the webview tries to open the zio file and shows the encoded data instead. When I tried this on safari, I was able to download the file and save it on the iPad.

**Screenshots/Videos:**
![image](https://user-images.githubusercontent.com/9376390/73755673-642ebe80-478c-11ea-8f3a-a10012ed060a.png)
Upon clicking the download link I am getting this. 
![image](https://user-images.githubusercontent.com/9376390/73755705-6db82680-478c-11ea-9a07-d9b951b5a1c7.png)

**Environment:**
 - OS: iOS
 - OS version: > 12.0
 - react-native version:  > 0.61
 - react-native-webview version: latest

**Comment by dvicory** [comment]
Unfortunately, the underlying WKWebView APIs are extremely limiting here. There are no true file downloads in WKWebView. WKWebView will basically attempt to preview any URL given to it. Android has a dedicated handler you can implement when WebView detects there is a download, for which there is no equivalent on iOS. The only true file download for WKWebView is long pressing on an image and saving it.

Our team has struggled off and on for months with various workarounds to overcome this. I've come to the conclusion there does not exist a technique that can universally be applied to this library with the WKWebView API as it is.

What I can tell you is ways we overcame it.

The first strategy we took was using `onShouldStartLoadWithRequest` that compares the URL we're trying to load to a list of regex URLs that are actually downloads. If it matches that list, we `return false`, blocking the loading of it, and have other code that does the download, and shows a file preview (we used [react-native-file-viewer](https://github.com/vinzscam/react-native-file-viewer)) that allows for saving to the device.

Our evolution of that technique is our web app is aware that we're sending a download, and instead sends a custom protocol (like `rn-app://`) with a serialized message indicating a download, which we are able to similarly intercept, block, and handle ourselves.

After a long time looking at the WKWebView API, I feel like this is the best that can be currently done. At least until the API allows for getting at raw response headers and/or data without having to use a custom protocol...

**Comment by Krypternite** [comment]
@

> Unfortunately, the underlying WKWebView APIs are extremely limiting here. There are no true file downloads in WKWebView. WKWebView will basically attempt to preview any URL given to it. Android has a dedicated handler you can implement when WebView detects there is a download, for which there is no equivalent on iOS. The only true file download for WKWebView is long pressing on an image and saving it.
> 
> Our team has struggled off and on for months with various workarounds to overcome this. I've come to the conclusion there does not exist a technique that can universally be applied to this library with the WKWebView API as it is.
> 
> What I can tell you is ways we overcame it.
> 
> The first strategy we took was using `onShouldStartLoadWithRequest` that compares the URL we're trying to load to a list of regex URLs that are actually downloads. If it matches that list, we `return false`, blocking the loading of it, and have other code that does the download, and shows a file preview (we used [react-native-file-viewer](https://github.com/vinzscam/react-native-file-viewer)) that allows for saving to the device.
> 
> Our evolution of that technique is our web app is aware that we're sending a download, and instead sends a custom protocol (like `rn-app://`) with a serialized message indicating a download, which we are able to similarly intercept, block, and handle ourselves.
> 
> After a long time looking at the WKWebView API, I feel like this is the best that can be currently done. At least until the API allows for getting at raw response headers and/or data without having to use a custom protocol...

Thanks.

**Comment by dvicory** [comment]
@Krypternite 

Good news! My teammate @trcoffman cracked the code on this with a fresh look. We will be dropping a PR to support downloads on iOS. There will be an option to pass in a `onDownload` prop, that if provided, will cancel trying to navigate to the download and call the callback with the URL for you to handle.

**Comment by safaiyeh** [comment]
Appreciate it @dvicory!

**Comment by Krypternite** [comment]
@dvicory Great, waiting for the update 👍

**Comment by trcoffman** [comment]
#1214 Addresses this @Krypternite @safaiyeh.
