### ISSUE TITLE
FullScreen Observer listening for event that is not limited to just entering Full Screen, also triggered on KeyboardUI windows showing.

### ISSUE THREAD

**Issue by tyleragnew** [react-native-community/react-native-webview#1190]
**Bug description:**

There is an Observer in RNCWebView.m that listens for UIWindowDidBecomeVisibleNotification events being triggered, and then selects the method showFullScreenVideoStatusBars to execute. I do not think this is the appropriate event to listen for when attempting to determine whether or not a FullScreenVideo view has indeed been entered. In fact, if a keyboard is shown, it will also emit a UIWindowDidBecomeVisibleNotification. This is causing issues for the Status Bar when there is a WebView component in the project, because the showFullScreenVideoStatusBars method is hardcoding the statusBarStyle to LightContent (causing it to disappear for screens where the background is white). 

I think it would be best to truly search for an event that is scoped only to only a fullScreenVideo being displayed, to take care of this. UPDATE: It looks like a feature request has come in specifically for this type of event: https://github.com/react-native-community/react-native-webview/issues/1189

**To Reproduce:**

In a component using WebView, do an action that requires a keyboard window to display. You will see that the statusBar ends up toggling its style. This is the expected behavior for entering a fullScreenVideo, but not for just any keyboard event.

**Expected behavior:**

A keyboard event should not trigger a method that is supposed to just listen for changes to the fullScreen status affect the status bar. 

**Screenshots/Videos:**
[KeyboardActionTriggersFullScreenMode.zip](https://github.com/react-native-community/react-native-webview/files/4165675/KeyboardActionTriggersFullScreenMode.zip)

**Environment:**

 - iOS: 13
 - react-native version: .60.8
 - react-native-webview version: 7.6.0 and 8.0.6

**Comment by trollepierre** [comment]
this bug is still painful.
Related #2576
