### ISSUE TITLE
Zero height

### ISSUE THREAD

**Issue by ekkis** [react-native-community/react-native-webview#1192]
the component has no height unless I give it one but '100%' doesn't seem to work.  I've also set `flex: 1` and `alignContent: 'stretch'` but to no avail.  I've read posts out there that suggest abandoning this component in favour of _react-native-autoheight-webview_, _react-native-render_ and other such modules but I'm certain there's a simple way to manage this

how can I make the component fill its parent?

**Bug description:**
Setting the component's height to 100% is ignored

**To Reproduce:**
```js
<WebView style={{height: '100%'}} />
```
**Expected behavior:**
The component should fill the parent container's space

**Environment:**
 - OS: OSX
 - OS version: Mojave
 - react-native version: 0.61.5
 - react-native-webview version: 8.0.6

**Comment by Razorholt** [comment]
Actually, setting height to 0 or 100% will make the app crash on Android. It's a nasty bug.
Also, react-native-autoheight-webview (which I'm using on iOS) depends on react-native-webview, which also crashes on Android.

**Comment by cluis13915** [comment]
Same issue here ! :cry:

**Comment by kamwoz** [comment]
Same on 0.59.10
