### ISSUE TITLE
webview not working on Android 10

### ISSUE THREAD

**Issue by hanifmhd** [react-native-community/react-native-webview#1196]
Since the new update of API 29 Android 10 in December 2019, react-native-webview is not working on Android 10.

**Bug description:**
White screen on the view

**To Reproduce:**
`<View style={{flex: 1}}>
          <WebView
            style={{flex: 1}}
            startInLoadingState
            scalesPageToFit
            javaScriptEnabled
            source={{
              uri: RestConstant.grafanaLink + this.state.username,
              headers: {
                Authorization: 'Bearer ' + this.state.token,
              },
            }}
            originWhitelist={['*']}
            domStorageEnabled={true}
            ignoreSslError={true}
            renderError={e => {
              return this.renderError();
            }}
          />
</View>
`

**Expected behavior:**
Show the webview from url 
*on iOS*
<img width="439" alt="Screen Shot 2020-02-10 at 10 58 03" src="https://user-images.githubusercontent.com/15220788/74120053-9315bc00-4bf4-11ea-9f82-71af57c5338b.png">

**Screenshots/Videos:**
White screen and loop loading
*on Android Nexus 5 API 29*
<img width="452" alt="Screen Shot 2020-02-10 at 11 04 30" src="https://user-images.githubusercontent.com/15220788/74120281-539b9f80-4bf5-11ea-9012-718418bb1a46.png">

**Environment:**
 - OS: Android
 - OS version: 10
 - react-native version: 0.61.2
 - react-native-webview version: ^7.4.3

**Comment by mghozyn** [comment]
Same problem, need solution for this bugs

**Comment by imamkodei889** [comment]
same problem.. need solution..

**Comment by mahavirvataliya** [comment]
+1

**Comment by mghozyn** [comment]
Any update on this bugs ?

**Comment by rynatk** [comment]
same problem

**Comment by njthulung** [comment]
same problem

**Comment by kimpoy04** [comment]
Encountered this in expo. Fixed it by executing: yarn react-native link react-native-webview

**Comment by maxlxq** [comment]
same problem +1

**Comment by xinfang** [comment]
+1

**Comment by andraz-at** [comment]
+1

**Comment by sebinq** [comment]
Hmm so there is currently no solution for this one? I'm encountering same issue but only in production release (using Android App Bundle)

**Comment by sebinq** [comment]
Oh, my problem was that I didn't explicitely prepend "https://" to the URL address.

**Comment by oailloud** [comment]
Same here, our users report crashes with Android 10 (amongst devices there's a S9).

Sadly, I can't reproduce it on the emulator and I don't have any physical device.
Does anyone have a clue of what's going on? Maybe an exception trace? 

Could it be related with Google stopping using Chrome as the WebView handler in Android 10 and switching back to Android System WebView?

**Comment by mustachedkdev** [comment]
+1

**Comment by jatin9996** [comment]
facing the same issue

**Comment by Asadi123** [comment]
is anyone able to workaround this? I am also facing the same issue.

**Comment by oailloud** [comment]
For me, disabling the hardware acceleration was enough to fix it, see https://github.com/react-native-webview/react-native-webview/issues/1069#issuecomment-642072920 if that's acceptable in your case.

**Comment by Asadi123** [comment]
@oailloud, disabling hardware acceleration does not work in my case.

**Comment by halocedark** [comment]
Same problem with me, it is showing a blank sceen when I load a url, I have android 10, I am using Android Studio.

**Comment by t1111-alt** [comment]
+1

**Comment by MarioKrstevski** [comment]
+1 But except this happens to me on Android Studio. I think it's something to do with the WebView implementation itself ( a guess at best ). The issue appears for only Android 10+ devices and for only the one website I'm trying to access. The website opens on Android 8 devices and other sites (URLs) open on both Android 10 & 8. So I don't know if that's helpful for this thread

**Comment by Raphaelinyang** [comment]
+ 1 ( android 10)

**Comment by vitorverasm** [comment]
+1 any updates?

**Comment by Raphaelinyang** [comment]
No update

**Comment by coolswood** [comment]
+1

**Comment by Rakshith658** [comment]
+1

**Comment by mainguyenhoi** [comment]
+1

**Comment by IlyaTaidi** [comment]
+1

**Comment by ThanhKhiem2k** [comment]
I have fixed this issue.. You need to uninstall 'Android System WebView' on your Android 10 device then update it. done

**Comment by solimanian** [comment]
same problem +1

**Comment by kundakcii** [comment]
+1

**Comment by Elliott-Chong** [comment]
+1

**Comment by julien-ctx** [comment]
+1
