### ISSUE TITLE
React-router history pushes / replaces not triggering webview events unless links are clicked twice

### ISSUE THREAD

**Issue by vascofg** [react-native-community/react-native-webview#1197]
**Bug description:**

On Android, when navigating on our React web app, running inside a react-native-webview, no navigation events are triggered, unless you click the link twice.
Adding the workarounds previously found in `Guide.md` (shimming the history methods) works, but I was under the impression this shouldn't be necessary.
The page I'm working with doesn't use `react-router` directly but it uses the same underlying library (ReactTraining/history) and I can confirm the problem exists with react-router as well.

**To Reproduce:**

Load this [codesandbox](https://codesandbox.io/s/react-router-basic-bnpsd) (it's one of the react-router demo pages): https://bnpsd.csb.app/ in a react-native-webview
Click around

**Expected behavior:**

Navigation events (like `onNavigationStateChange`) are called.

**Environment:**
 - OS: Android
 - OS version: 9 / 10
 - react-native version: 0.61.4
 - react-native-webview version: 8.0.3

**Comment by vascofg** [comment]
Any updates on this?

**Comment by folowing** [comment]
I encounter the same problem, iOS is ok, but not Android.

**Comment by ijasm** [comment]
me too

**Comment by vascofg** [comment]
@ijasm It was in an older version of that file. I'm injecting this snipped of Javascript code:
```js
const historyAPIShim = `
(function() {
    function wrap(fn) {
      return function wrapper() {
        var res = fn.apply(this, arguments);
        window.ReactNativeWebView.postMessage(
          '{"method": "historyChange"}'
        );
        return res;
      };
    }
    history.pushState = wrap(history.pushState);
    history.replaceState = wrap(history.replaceState);
    window.addEventListener("popstate", function() {
      window.ReactNativeWebView.postMessage(
        '{"method": "historyChange"}'
      );
    });
  })();
`;

```

**Comment by iAmGhost** [comment]
@vascofg 's workaround is working but I was unable to capture title change(w/ react-helmet).

put code below to root element of web app(not in native) and use it from `WebView.onMessage` event.

```js
  React.useEffect(() => {
    const titleElement = document.getElementsByTagName('title')[0];
    const documentElement = document.documentElement;

    function onElementChange(e: any) {
      const changedElement = e.target;

      if (changedElement === titleElement) {
        window.ReactNativeWebView.postMessage(
          JSON.stringify({
            method: 'titleChange',
            title: titleElement.innerText,
          }),
        );
      }
    }

    if (documentElement) {
      documentElement.addEventListener('DOMSubtreeModified', onElementChange);

      return () => {
        documentElement.removeEventListener(
          'DOMSubtreeModified',
          onElementChange,
        );
      };
    }
  });
```

**Comment by iAmGhost** [comment]
As I can see in [source code](https://github.com/react-native-community/react-native-webview/blob/master/apple/RNCWebView.m#L1230-L1249) it works on iOS because it injects similar shim js code into WebView.

I'm not sure why it's not on Android. I wonder Is it just not implemented or it worked without shim and broken on some environment?

**Comment by vascofg** [comment]
This is still not fixed

**Comment by cbotsikas** [comment]
Although this is an old thread, maybe it's helpful for others. It appears that `onNavigationStateChange` is not called on Android when the app uses history `pushState` and `popState` when navigating back in history. On iOS it is being called just fine.
I noticed that `onLoadProgress` is called in both platforms so what I did was to use both like this:
```
      onNavigationStateChange={(navState) => {
        // On Android if the page uses history pushState and popState,
        // onNavigationStateChange is not called but onLoadProgress does
        setCanGoBackInWebView(navState.canGoBack);
      }}
      onLoadProgress={(syntheticEvent) => {
        const { nativeEvent } = syntheticEvent;
        // On Android if the page uses history pushState and popState,
        // onNavigationStateChange is not called but onLoadProgress does
        setCanGoBackInWebView(nativeEvent.canGoBack);
      }}
```

**Comment by maximilize** [comment]
This problem is not solved. Can this issue be opened again?

**Comment by VariabileAleatoria** [comment]
Why is this issue closed?
