### ISSUE TITLE
window.location update with InjectJavaScript not working for the first time but works fine after that

### ISSUE THREAD

**Issue by DevArenaCN** [react-native-community/react-native-webview#1198]
**Bug description:**

window.location update with InjectJavaScript not working for the first time but works fine after that

**To Reproduce:**

```
  componentDidMount () {
    this.removeNotificationOpenedListener = firebase.notifications().onNotificationOpened((notificationOpen) => {
          const urlRedirect = notification.data.url
        this.webview.stopLoading()
        this.webview.injectJavaScript(`
        (function(){
          window.location.href = '${urlRedirect}';
          return false;
        })();
        false;
        `)
      }
    })
```

**Expected behavior:**

The webview should load the urlRedirect, but it loaded in the default url set when init the webview. App is running in the background, the urlRedirect has the correct value. What's weird to me is that the first call to injectJavaScript failed to work but the 2nd one would take the webview to the value set to urlRedirect.

**Environment:**
 - OS: iOS
 - OS version: 13.3
 - react-native version: 0.61.5
 - react-native-webview version: 8.0.3

**Comment by sajeeldigitali** [comment]
Any solutions on getting window.location.href on first time.
Please open this issue its not fixed
