### ISSUE TITLE
Any way to implement onScrollEndDrag in webview? 

### ISSUE THREAD

**Issue by panda0603** [react-native-community/react-native-webview#1199]
It would be nice to have onScrollEndDrag prop(just like scrollview), which is callback called after user has finished dragging & lifts finger off the screen. 
I've tried work arounds such as injecting javascript to detect scrolling, as follows:

```
var isScrolling;
// Listen for scroll events
window.addEventListener('scroll', function ( event ) {

	// Clear our timeout throughout the scroll
	window.clearTimeout( isScrolling );

	// Set a timeout to run after scrolling ends
	isScrolling = setTimeout(function() {

		// Run the callback
		console.log( 'Scrolling has stopped.' );

	}, 66);

}, false);
```

However this also detects when user stops scrolling but has finger down on screen. 
Any possible ways?

**Comment by baesumin** [comment]
+1

**Comment by KrisLau** [comment]
@panda0603 did you ever figure this out?

**Comment by KrisLau** [comment]
Just wanted to say I've continued looking into this and this is might be why:
https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollend_event

The scrollend event is not available in Safari
