### ISSUE TITLE
MIGRATED: Pinch-to-Zoom doesn't work without setting scalesPageToFit={true} explicitly on WebView component. (#17005)

### ISSUE THREAD

**Issue by jamonholmgren** [react-native-community/react-native-webview#12]
Migrated from https://github.com/facebook/react-native/issues/17005.

@ewhitebloom says:

---

Environment
Steps to Reproduce
(Write your steps here:)

Make a WebView Component
Set the source attribute to have a uri value of a PDF.
You'll notice that you can't pinch-to-zoom without explicitly setting scalesPageToFit={true}. Even though the docs say that it is set to true by default, it appears it is not.
Expected Behavior
The pinch-to-zoom behavior should be there without setting scalesPageToFit equal to true, explicitly.

Actual Behavior
Pinch-to-zoom doesn't work without setting the scalesPageToFit explicitly.

---

_More info in original thread_

**Comment by Salakar** [comment]
@ewhitebloom I'll go ahead and close this issue given that there's been no further activity for a few months. If you want this re-opened please let me know.

**Comment by kaushal9678** [comment]
Put Webview outside of ScrollView because Webview is a subclass of ScrollView. It will work.
