### ISSUE TITLE
some video not playing in webview

### ISSUE THREAD

**Issue by abo-ziad95** [react-native-community/react-native-webview#1201]
Some Videos are not playing in webview.

**The code which I used is mentioned below.

<WebView source={{ uri: 'https://kaitest.nyc3.digitaloceanspaces.com/1579720213226_issg45exovmi3y57rpg9d1v4wr288u' }} />**

Note : Youtube videos are playing perfectly

Please help me to solve the issue...

**Comment by zhaiyjgithub** [comment]
Same issue.
