### ISSUE TITLE
Webviews inside a flat list in Android

### ISSUE THREAD

**Issue by TfADrama** [react-native-community/react-native-webview#1207]
**Bug description:**

When i put a flat list of webviews on Android the scroll vertical for the webviews and horizontal for the flat list gets all messy. When i try to do a horizontal scroll the vertical scroll from the webview gets control and vice versa. 
In iOS the scrolls are all working as expected.

**To Reproduce:**

Just create a flat list with some webviews and compare it on iOS and Android

**Expected behavior:**

The expected behavior is to be like on iOS.

**Environment:**
 - OS: Android
 - react-native version: 0.60.6
 - react-native-webview version: 7.5.2

**Comment by kheeong** [comment]
Hi @TfADrama , can I know how u did it? I tried to use webview with flatlist and sectionlist but none of them work

**Comment by nauticalcoder** [comment]
I also have the same issue.  I have the WebView inside of a SwiperFlatList page which is just a horizontal version of the FlatList.  There is no way to scroll the WebView as any scrolling wants to scroll the list, not the content of the WebView.

**Comment by TfADrama** [comment]
> Hi @TfADrama , can I know how u did it? I tried to use webview with flatlist and sectionlist but none of them work

Maybe you didnt gave a style for the webview or for the flat list. It's really easy, just a simple flat list with flex1 and many webviews with only url and style. For he webview if the flex doesn't work try hard coding te heigh and width to understand what is happening. 

But in android you will have a bad experience trying to scroll it has i mention on this issue.

**Comment by TfADrama** [comment]
Why it's closed?

**Comment by mahadevsempire** [comment]
Same issue

**Comment by Nensi9** [comment]
Is there any solution for this issue?

**Comment by BrancuAlexandru** [comment]
this is STILL a problem

**Comment by DavitVosk** [comment]
Is there any solution here please?
