### ISSUE TITLE
The Android default error page flashed

### ISSUE THREAD

**Issue by LovelyWhite** [react-native-community/react-native-webview#1215]
**Bug description:**
自定义renderError后会闪屏出Android错误页

**To Reproduce:**
https://github.com/LovelyWhite/FinalProject

**Expected behavior:**

**Environment:**
 - OS:MIUI 11 9.9.26 
 - OS version: Android 9
 - react-native version:0.61.5
 - react-native-webview version:^8.0.6

```typescript
<WebView ref={ref => {
            this.webview = ref
          }}
            onLoadEnd={() => {
              this.setState({
                mapSync: FLAGS.PLAY
              })
            }}
            scalesPageToFit={false}
            source={{ uri: serverAdress + 'page/bd-map' }}
            startInLoadingState={true}
            onError={() => { this.setState({ ready: false }) }}
            renderError={() =>
              <TouchableWithoutFeedback
                onPressIn={this.pressIn}
                onPressOut={this.pressOut}>
                <View style={{ position: 'absolute', flex: 1, backgroundColor: '#FFFFFF', width: '100%', height: '100%', justifyContent: "center", alignItems: "center" }}>
                  <MaterialIcons name={'error-outline'} size={35} />
                  <Text style={{ fontSize: 12 }}>地图加载失败</Text>
                </View>
              </TouchableWithoutFeedback>}
            renderLoading={() => <Loading />}
          />
```

**Comment by LovelyWhite** [comment]
![Screenrecorder-2020-02-19-08-55-00-788](https://user-images.githubusercontent.com/23720995/74792213-baa50c80-52f7-11ea-8f61-2796c3b68a12.gif)

**Comment by puckey** [comment]
I have also been trying to figure this out. There is some more information in this Stackoverflow answer, but no solution that works for me yet: https://stackoverflow.com/questions/55489803/remove-android-default-error-page-on-react-native-webview

**Comment by EminShahbazi** [comment]
still searching for solutions
