### ISSUE TITLE
StatusBar turns white color when WebView loads pdf link file (iOS)

### ISSUE THREAD

**Issue by VitalikParshin** [react-native-community/react-native-webview#1219]
**Bug description:**
StatusBar turns white color when WebView loads pdf link file (iOs)

**To Reproduce:**
uri_example = "https://static......Privacy_Policy.pdf"
Passing any source={{ uri }} prop to WebView, Status bar become from black text color to white 
<WebView source={{ uri }}  />

**Expected behavior:**
Passing any source={{ uri }} prop to WebView, Status bar shouldn't change color

**Screenshots/Videos:**
WebView with pdf remote link file is loaded
<img width="484" alt="Screenshot 2020-02-19 at 22 05 46" src="https://user-images.githubusercontent.com/41287813/74872001-18237280-5365-11ea-8d39-aa582f3bd658.png">

**Environment:**
 - OS: iOS
 - OS version: 13.3
 - react-native version: 0.61.5
 - react-native-webview version: 8.0.2

**Comment by dillonhafer** [comment]
This is also happening for me when I load a PDF from a `file:///` url. A workaround I found is to set the status bar programmatically after the WebView loads, which flickers, but is better than nothing.

```
<WebView
  source={{ uri: 'file:///...' }}
  onLoadEnd={() => {
    [10, 50, 100, 500, 1000].forEach(timeout => {
      setTimeout(() => {
        StatusBar.setBarStyle("dark-content");
      }, timeout);
    });
  }}/>

**Comment by bluedaniel** [comment]
Still searching for solutions as this is unresolved

**Comment by VitalikParshin** [comment]
Issue still exists

**Comment by arjunkomath** [comment]
+1

**Comment by mattwoberts** [comment]
Related I think to https://github.com/react-native-community/react-native-webview/issues/1580

**Comment by mattwoberts** [comment]
Just to add to this, it's not limited to PDFs, I'm finding the same issue for all sites. 

The webview seems to be interfering with the statusbar color. I have a simple react app that's just rendering a webview, with a statusbar with dark content:

```jsx
<SafeAreaView style={{flex:1, backgroundColor:'white'}}>
      <StatusBar barStyle="dark-content"/>
      <WebView
        ref={webref}
        source={{ uri: url}}
        style={{ flex: 1 }}
        onNavigationStateChange={handleNavigate}
      />
    </SafeAreaView>
```

This works. If I change that to `light-content`, I see it light for a flash, then the webview loads it's content and the statusbar returns to being dark.

**Comment by elgambet** [comment]
I'm having the same problem:

- react: "17.0.1"
- react-native: "0.64.1"
- react-native-webview: 11.4.4

**Comment by elgambet** [comment]
> I'm having the same problem:
> 
> * react: "17.0.1"
> * react-native: "0.64.1"
> * react-native-webview: 11.4.4

It's only happening in emulator, in physical device is working just fine so you can dismiss my previous comment.

**Comment by joaonew** [comment]
Can we add a button next to Terms of Service in the example above for the user to click on it and trigger a function?
