### ISSUE TITLE
Application frige 

### ISSUE THREAD

**Issue by krishan1kamal** [react-native-community/react-native-webview#122]
When keyword is closed webview get fridge 
1) when you click on done button and keyword is closed and complete webview is fridge 
2) when input lose focus keyword is closed and complete webview is fridge 
3) when you click out side input keyword is closed and complete webview is fridge 

I am using ios 12.1 and react-native 0.57.4 and xcode 10.1 
note:- when i  scroll on webview body its again start working but if i touch on webview body its still fridged 
and its working well in ios 11.4
Please help

**Comment by jamonholmgren** [comment]
Hi @krishan1kamal! I’d be happy to take a look at this. Please create, publish, and link here a minimal app that reproduces this issue and I’ll take a look.

**Comment by krishan1kamal** [comment]
Hi @jamonholmgren Soory for the late response my app link is
https://testflight.apple.com/join/1pVTpTgX
and login credential is
Username : - mobileTest@yopmail.com
Password:- kk@123
Device require 
:- any apple mobile phone with operating system IOS 12.1 
Step to setup:-
1. Login with given credential
2. Set your pin for future easy login
3. Biometric authentication if available on device (Optional) 
4. wait few second to load chat bot after setup
5. Click on click here to begin to start the chat
6. You can ask question like can i bring a pets to work?

Issues:-
when you click on done button and keyword is closed and complete webview is fridge
when input lose focus keyword is closed and complete webview is fridge
when you click out side input keyword is closed and complete webview is fridge

**Comment by krishan1kamal** [comment]
its working fine with react native 0.57.5 
Closing 
Thanks
