### ISSUE TITLE
crash - android 5.1 - string resource id #0x2040003

### ISSUE THREAD

**Issue by AstroCorp** [react-native-community/react-native-webview#1222]
string resource id #0x2040003
![Screenshot_1582193498](https://user-images.githubusercontent.com/22180346/74923849-c8c75b80-53d1-11ea-8490-efb55ea9d266.png)

**Comment by sharifashraful** [comment]
crash on api level 21
![image](https://user-images.githubusercontent.com/7131239/75534619-25b0ba80-5a3f-11ea-904b-9259f15bc6c8.png)

**Comment by sharifashraful** [comment]
fixed by using androidx.appcompat:appcompat:1.2.0-alpha02

**Comment by perottilds** [comment]
For those reading: androidx.appcompat:appcompat:1.2.0 is stable and I can attest it works recommended
One can add the following line in `android/build.gradle`

```
dependencies {
    // react dependencies
    // add this line
    implementation "androidx.appcompat:appcompat:1.2.0"

    // probably hermes if block down here
}
```
