### ISSUE TITLE
Android, react-native-cli init project, Invariant Violation: requireNativeComponent: "RNCWebView" was not found in the UIManager.

### ISSUE THREAD

**Issue by YanYuanFE** [react-native-community/react-native-webview#1225]
**Bug description:**
Invariant Violation: requireNativeComponent: "RNCWebView" was not found in the UIManager.

This error is located at:
    in RNCWebView (at WebView.android.js:241)
    in RCTView (at WebView.android.js:244)
    in WebView (at App.js:34)
    in RCTView (at App.js:24)
    in App (at renderApplication.js:40)
    in RCTView (at AppContainer.js:101)
    in RCTView (at AppContainer.js:119)
    in AppContainer (at renderApplication.js:39)

and I has try this method:
react-native link
react-native start --reset-cache
uninstall the app from the device
react-native run-android

**To Reproduce:**
https://github.com/YanYuanFE/react-native-signature-canvas/tree/master/example/signapp

**Expected behavior:**
no error

**Screenshots/Videos:**

![image](https://user-images.githubusercontent.com/17774285/75092881-66c84b00-55b7-11ea-8c2f-e733d5d80d86.png)

**Environment:**
 - OS: MacOS
 - OS version: 10.15.2
 - react-native version: v0.61.5
 - react-native-webview version: v8.1.2

**Comment by Florent75** [comment]
I do have the same issue on Android,
React native : 0.59.10
react-native-webview : 8.1.2

Did you find any solution ?

**Comment by LorienHW** [comment]
Same, looks like running `react-native link` isn't actually linking the android project. I got it working by manually linking. You can add the following to manually link the project:

In android/settings.gradle add:
```include ':react-native-webview
project(':react-native-webview').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-webview/android')```

in android/app/src/main/java/com/outpatient/MainApplication.java import the package in your imports section:
`import com.reactnativecommunity.webview.RNCWebViewPackage;`
and also init the package where you see the other bits that look like this:
`new RNCWebViewPackage()`

in android/app/build.gradle look for the other bits that look like this and add it:
`implementation project(':react-native-webview')`

**Comment by Florent75** [comment]
Hi LorienHW,

Thanks for the reply, that did work for me !

**Comment by ravindranpandu** [comment]
Thanks @LorienHW,

you saved the day :)
