### ISSUE TITLE
Hello, I am trying to use `react-native-webview` and I keep running into different errors

### ISSUE THREAD

**Issue by bobbylemm** [react-native-community/react-native-webview#1226]
**Bug description:**
I installed `react-native-webview` but keep running into different errors. A full breakdown of the error is pasted below. 

> Task :react-native-firebase:compileDebugJavaWithJavac FAILED
/Users/tk-summitech/Documents/mobile/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/database/RNFirebaseData
baseReference.java:11: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
/Users/tk-summitech/Documents/mobile/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/database/RNFirebaseDatabaseReference.java:12: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
/Users/tk-summitech/Documents/mobile/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/database/RNFirebaseDatabaseUtils.java:3: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
/Users/tk-summitech/Documents/mobile/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/firestore/RNFirebaseFirestore.java:4: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
/Users/tk-summitech/Documents/mobile/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/firestore/RNFirebaseFirestoreCollectionReference.java:4: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
/Users/tk-summitech/Documents/mobile/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/firestore/RNFirebaseFirestoreDocumentReference.java:3: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
/Users/tk-summitech/Documents/mobile/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/config/RNFirebaseRemoteConfig.java:3: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
/Users/tk-summitech/Documents/mobile/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/auth/RNFirebaseAuth.java:7: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
/Users/tk-summitech/Documents/mobile/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/admob/RNFirebaseAdmobInterstitial.java:5: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;

**To Reproduce:**

**Expected behavior:**

**Screenshots/Videos:**

Here us my `app/build.gradle` file 
<img width="896" alt="Screenshot 2020-02-23 at 10 28 11 AM" src="https://user-images.githubusercontent.com/38977569/75109826-872fee00-5627-11ea-8e54-5912e582d4fd.png">

**Environment:**
 - OS: MAC
 - OS version:
 - react-native version: 0.59.3
 - react-native-webview version:^8.1.2

**Comment by binhndicts** [comment]
@bobbylemm Do you use `jetifier`?

**Comment by RaviKiranMakala** [comment]
> **Bug description:**
> I installed `react-native-webview` but keep running into different errors. A full breakdown of the error is pasted below.
> 
> > Task :react-native-firebase:compileDebugJavaWithJavac FAILED
> > /Users/tk-summitech/Documents/mobile/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/database/RNFirebaseData
> > baseReference.java:11: error: package android.support.annotation does not exist
> > import android.support.annotation.NonNull;
> > ^
> > /Users/tk-summitech/Documents/mobile/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/database/RNFirebaseDatabaseReference.java:12: error: package android.support.annotation does not exist
> > import android.support.annotation.Nullable;
> > ^
> > /Users/tk-summitech/Documents/mobile/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/database/RNFirebaseDatabaseUtils.java:3: error: package android.support.annotation does not exist
> > import android.support.annotation.Nullable;
> > ^
> > /Users/tk-summitech/Documents/mobile/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/firestore/RNFirebaseFirestore.java:4: error: package android.support.annotation does not exist
> > import android.support.annotation.NonNull;
> > ^
> > /Users/tk-summitech/Documents/mobile/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/firestore/RNFirebaseFirestoreCollectionReference.java:4: error: package android.support.annotation does not exist
> > import android.support.annotation.NonNull;
> > ^
> > /Users/tk-summitech/Documents/mobile/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/firestore/RNFirebaseFirestoreDocumentReference.java:3: error: package android.support.annotation does not exist
> > import android.support.annotation.NonNull;
> > ^
> > /Users/tk-summitech/Documents/mobile/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/config/RNFirebaseRemoteConfig.java:3: error: package android.support.annotation does not exist
> > import android.support.annotation.NonNull;
> > ^
> > /Users/tk-summitech/Documents/mobile/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/auth/RNFirebaseAuth.java:7: error: package android.support.annotation does not exist
> > import android.support.annotation.NonNull;
> > ^
> > /Users/tk-summitech/Documents/mobile/node_modules/react-native-firebase/android/src/main/java/io/invertase/firebase/admob/RNFirebaseAdmobInterstitial.java:5: error: package android.support.annotation does not exist
> > import android.support.annotation.Nullable;
> 
> **To Reproduce:**
> 
> **Expected behavior:**
> 
> **Screenshots/Videos:**
> 
> Here us my `app/build.gradle` file
> <img alt="Screenshot 2020-02-23 at 10 28 11 AM" width="896" src="https://user-images.githubusercontent.com/38977569/75109826-872fee00-5627-11ea-8e54-5912e582d4fd.png">
> 
> **Environment:**
> 
> * OS: MAC
> * OS version:
> * react-native version: 0.59.3
> * react-native-webview version:^8.1.2

I am getting same issues, any update. Did u fixed the issue?
