### ISSUE TITLE
Browser native login dialog for authentication.

### ISSUE THREAD

**Issue by jhrinoa** [react-native-community/react-native-webview#1232]
Description:
Our login flow involves talking to IdP (identity provider) through WebView to get authenticated.
And, the IdP page spawns a native browser dialog for getting user credential (Login ID and Password).

Currently, RNCWebView doesn't handle this page as regular browser does. It simply closes dialog as if "Cancel" is clicked. 

It would be nice to have RNCWebView to handle page that pops up native dialog like normal browser.

This is how it works on normal Safari browser.
![login-popup](https://user-images.githubusercontent.com/6693932/75299465-f5bca980-57e9-11ea-9d4e-97d1d516af42.png)

This is how it works in RNCWebView for same IdP page.
![login-error](https://user-images.githubusercontent.com/6693932/75299470-f9503080-57e9-11ea-80c8-2bf338b9a955.png)

**Comment by binhndicts** [comment]
@jhrinoa Basic authentication is not supported in this module officially. It's such a simple and common feature so I don't understand why they don't do that.

Here is what we did to support it:
https://github.com/gulabs/react-native-webview/blob/dev/ios/RNCWebView.m#L874
