### ISSUE TITLE
jquery touch punch plugin is not working on react-native-webview for android

### ISSUE THREAD

**Issue by Nehal-29** [react-native-community/react-native-webview#1237]
My issue: [https://www.screencast.com/t/Uuh6hdEk](url)
**Environment:**
 - OS: Android
 - react-native version: 0.60.4
 - react-native-webview version:8.0.6

I've a webview in a flatlist, there I want to apply sortable function using jqueryTouchPunch but it is not working.

Running smooth on all iOS devices

Using 
jquery-1.11.3.js; 
jQuery UI - v1.12.1
jQuery UI Touch Punch 0.2.3

@Titozzz @jamonholmgren @all-contributors

**Comment by Nehal-29** [comment]
@jamonholmgren @Titozzz 
can you look into the issue ?
I'd shared video related to issue. [https://www.screencast.com/t/Uuh6hdEk](url)

**Comment by jamonholmgren** [comment]
@Nehal-29 I can't seem to see that screencast:

![image](https://user-images.githubusercontent.com/1479215/82764617-01a61080-9dc5-11ea-970a-f67ec4c4d6e9.png)

**Comment by Nehal-29** [comment]
Hey @jamonholmgren 
You've to allow flash player plugin to run in your chrome, to see this video. 
<img width="1222" alt="Screenshot 2020-05-26 at 10 10 57 AM" src="https://user-images.githubusercontent.com/41570871/82861212-929df880-9f39-11ea-8517-9b0ea097763d.png">
<img width="1147" alt="Screenshot 2020-05-26 at 10 12 59 AM" src="https://user-images.githubusercontent.com/41570871/82861221-9af63380-9f39-11ea-9aa1-9b549ffb6c0d.png">

**Comment by jamonholmgren** [comment]
@Nehal-29 DId you figure this out?

**Comment by Nehal-Sanklecha** [comment]
@jamonholmgren  No, not yet.
But were you able to see the videos I'd shared?

**Comment by Nehal-29** [comment]
@jamonholmgren  Any luck??
