### ISSUE TITLE
Using window.ReactNativeWebView on Android KitKat returns an empty object

### ISSUE THREAD

**Issue by mikelros** [react-native-community/react-native-webview#1238]
**Bug description:**
I'm developing an app that consists of a webview and a few extra features based on `postMessage`/`onMessage` and `injectJavascript`. In order to be able to use the app, the webview should support these methods across all android versions. I've tried these methods on an emulator and a real device and when using the app in Android 4.4 `window.ReactNativeWebView` is an empty object: `{}` instead of an object with postMessage. That works for all versions greater than 4.4.
I've also tried disabling proguard without success thinking that could be the problem as the `window.ReactNativeWebView` is based on the use of `@JavascriptInterface` annotation. I found it happens in debug and release variants indistinctly.

**Expected behavior:**
I'm expecting `window.ReactNativeWebView` to behave the same way across all the android versions so the web can send data with `postMessage` and the app can receive that data.

**Environment:**
 - OS: Android
 - OS version: 4.4.2
 - react-native version: 0.61.5
 - react-native-webview version: 8.1.2
 - minSdkVersion = 18
 - compileSdkVersion = 28
 - targetSdkVersion = 28

Repository with repro: https://github.com/mikelros/ReactNativeWebViewKitKat
Screenshots of that repository:

**Android 4.4.2**
<img width="359" alt="android-442" src="https://user-images.githubusercontent.com/22213811/75657737-29bf2100-5c67-11ea-940f-12290975a6d5.png">

**Android 5.1**
<img width="366" alt="android-51" src="https://user-images.githubusercontent.com/22213811/75657743-2c217b00-5c67-11ea-884a-2572cdff61ad.png">

**Comment by bulby97** [comment]
@mikelros  Did you find any solutions ?

**Comment by mikelros** [comment]
@bulby97 nope. Still not supporting Android 4.x versions.

**Comment by bulby97** [comment]
argh that's so sad. The main feature of my app is in a webview...and everything is just empty.

Anyway, thanks mate !

**Comment by bulby97** [comment]
https://play.google.com/store/apps/details?id=com.google.android.webview

It seems like it's possible to update the android webview. It fixes the issue for one of my users on Android 5.1.1, don't know if it can do the same for Android 4.4

**Comment by bulby97** [comment]
NVM, it's working only for android 5.0 and above

**Comment by bulby97** [comment]
No solution found :(
