### ISSUE TITLE
Iframe in webview allowInlineMediaPlayback does not work

### ISSUE THREAD

**Issue by sopheareachte** [react-native-community/react-native-webview#1240]
I checked the document, for IOS the webview allowInlineMediaPlayback is required to be true and put WebKit-playsinline in the video element. Is there any way to work around for iframe to be able to playsinline in IOS to avoid the native full-screen controller?

**Comment by enzomonjardin** [comment]
We're having the same issue. The `allowsInlineMediaPlayback` prop is set in the webview, videos in the webview are playing inline as they should, but videos within an iframe within the webview always trigger the full screen player in ios, despite having the playsinline attribute set.

Haven't found a solution yet.

**Comment by miquelcopet** [comment]
This issue is still happening. If the camera is opened in an iframe inside the webview it triggers the fullscreen player, even with allowsInlineMediaPlayback enabled.
Found any solutions @enzomonjardin ?

**Comment by enzomonjardin** [comment]
I know we fixed it but I can't recall how. If it's any use to you, the props we're setting on the WebView component are:
```
          allowFileAccess
          scrollEnabled={false}
          allowsInlineMediaPlayback
          allowUniversalAccessFromFileURLs
          allowFileAccessFromFileURLs
          domStorageEnabled
          useWebkit
          keyboardDisplayRequiresUserAction={false}
          mixedContentMode="always"
```
Maybe one of was related to fixing the issue. Sorry I can't be of anymore help.
