### ISSUE TITLE
v2.5.0 injectedJavaScript dost not work on ios

### ISSUE THREAD

**Issue by chenyao6134** [react-native-community/react-native-webview#125]
react-native-webview  injectedJavaScript dost not work on ios

**Comment by Titozzz** [comment]
Please tell me more info about that, I'm using it without any issue

**Comment by chenyao6134** [comment]
I found it does not work on iOS Simulator,and it work fine on iPhone8 physics device.

**Comment by chenyao6134** [comment]
I found it does not work on iOS Simulator,and it work fine on iPhone8 physical device.

**Comment by jamonholmgren** [comment]
@chenyao6134 Can you publish a minimal app or [Snack](https://snack.expo.io/) that demonstrates this behavior so we can clone it and take a look?

**Comment by xinfang** [comment]
+1 not work in real device and simulator for ios

**Comment by smakosh** [comment]
Doesn't work on real device :)

**Comment by smakosh** [comment]
Ended up using https://www.npmjs.com/package/react-native-webview-invoke
