### ISSUE TITLE
[ANDROID] Race condition of life cycles in Webview

### ISSUE THREAD

**Issue by panda0603** [react-native-community/react-native-webview#1250]
Hello, 

There seems to be a race condition within the life cycle of the webview (i.e. loadEnd, loadStart, loadProgress, etc...). 

What happens is each lifecycle does not seem to be called correctly at the timing they are supposed to be when navigating to different pages. I.e. onProgress is called before onStart, onEnd being called at the start of navigation, etc. Sometimes, onLoadProgress is not even called(for cached pages maybe?)

ALso they are 'delayed' are is called upon next navigation page. E.g, part of onLoadProgress event of page A is called upon the start of navigation of page B, etc.. 

This does not happen in IOS.

**Comment by shirakaba** [comment]
I encountered this in #1099 (lots of head-scratching to read in there). The race condition seems to be problematic for hosted websites but less so – or not at all – for static HTML sources. I'm not familiar enough with Android WebView or its lifecycle to understand why it's so broken. But you're certainly not imagining things.

**Comment by nadav2051** [comment]
I'm also experiencing this. 

I get onProgress called after onLoadEnd has been called

**Comment by shirakaba** [comment]
still searching for solutions

**Comment by nadav2051** [comment]
still searching for solutions

**Comment by shirakaba** [comment]
@safaiyeh The `github-actions` bot didn't take the hint; could you please re-open this? Thanks.

**Comment by KingAmo** [comment]
`onLoadProgress` do not work sometimes
