### ISSUE TITLE
Webview doesn't play videos inline

### ISSUE THREAD

**Issue by masudhossain** [react-native-community/react-native-webview#1251]
**Bug description:**
Rendering a webview with a video with playsinline tag causes it to play in fullscreen anyways. 

**To Reproduce:**
Create a <video src="" playsinline"></video> on an html page and render it on the webview, and it will play in fullscreen. Try it on safari and it will play inline. 

**Expected behavior:**
Should play the video inline without going fullscreen when playing. 

**Environment:**
 - OS: React Native / iOS 
 - react-native-webview version: 7.4.3

**Comment by masudhossain** [comment]
Not a bug. Have to add `allowsInlineMediaPlayback="true"` to the webview.

**Comment by hooiyan** [comment]
> Not a bug. Have to add `allowsInlineMediaPlayback="true"` to the webview.

Hello there, I have added this but it is still going fullscreen when playing. Is this still working on your end?

**Comment by junguksim** [comment]
@hooiyan Any update on this? I also suffer from this issue

**Comment by hooiyan** [comment]
> @hooiyan Any update on this? I also suffer from this issue

Hey @junguksim, I was able to solve this issue by installing `"react-native-webview": "^11.17.2"`.

Maybe you can try this!

**Comment by junguksim** [comment]
> > @hooiyan Any update on this? I also suffer from this issue
> 
> Hey @junguksim, I was able to solve this issue by installing `"react-native-webview": "^11.17.2"`.
> 
> Maybe you can try this!

Oh, update the version to `11.17.2` and adding `allowsInlineMediaPlayback="true"` worked!!!! Thanks @hooiyan !!

**Comment by ravinderCD3803** [comment]
I am having same issue. Also updated 11.17.2. but not working

**Comment by skanger** [comment]
not working on     "react-native-webview": "^11.22.1",

I add playsinline to video tag, and set allowsInlineMediaPlayback="true" to Webview ，  notworking on ios

**Comment by simonho1025** [comment]
> Please add the two props below for IOS.
> 
> ```
> allowsInlineMediaPlayback={true}
> mediaPlaybackRequiresUserAction={false}
> ```

not working on `"react-native-webview": 11.26.0`

**Comment by simonho1025** [comment]
set allowsInlineMediaPlayback="true" was working before, but suddenly not working

**Comment by MarcusPOliveira** [comment]
I was experiencing this problem too. I was using the `<video />` tag in a NextJs app, which was displayed through a WebView in React Native. Even using `playsInline` and `webkit-playsinline`, the problem persisted. On Android it was working perfectly, this problem was only on iOS.
So, as a solution, I removed the `allowsFullscreenVideo` property from the WebView and it worked, no longer displaying in full screen!

I kept the `<video />` tag as follows:
`
<video
        controls={false}
        ref={videoRef}
        preload="auto"
        autoPlay
        playsInline
        webkit-playsinline
 />
`

**Environment:**
OS: React Native / iOS
react-native version: 0.64.0
react-native-webview version: 11.23.1

**Comment by chaudev** [comment]
`allowsInlineMediaPlayback={true}` worked with me 🫰

**Comment by LCseniordev** [comment]
@chaudev could you please share how you solved the issue? Do you use html or uri and what are the props that you set to webview?

Thank you in advance!

**Comment by WayneKim92** [comment]
In iOS / react-native-webview@13.12.5, i got the same issue at youtube.
