### ISSUE TITLE
Question: Font is very small on iOS?

### ISSUE THREAD

**Issue by rob-orch** [react-native-community/react-native-webview#1252]
Hello,

I am currently implementing this library into my app to display blog articles written by authors.

The blogs articles are exported via Word and look like this: https://codepen.io/rob__/pen/dyodEqr.
Opening these pages on mobile devices looks like it should - so the file itself shouldn't cause issues.

When showing the article in the app however, the text is tiny and bearly readable. I could fix this problem on Android by setting `scalesPageToFit={false}` but whatever I try, I can't fix it on iOS.

Do you guys see anything I am doing wrong? I feel like I tried everything I could think of but I just can't find a solution.

**Comment by shirakaba** [comment]
Probably no need for `scalesPagesToFit`, and not a WebView issue but a webpage issue. Try adding this [viewport meta tag](https://developer.mozilla.org/en-US/docs/Mozilla/Mobile/Viewport_meta_tag) to the `<head>`:

```html
<meta name="viewport" content="width=device-width, initial-scale=1">
```

@rob-orch does that fix things?

**Comment by rob-orch** [comment]
That was the problem - thank you very much!
