### ISSUE TITLE
Getting ERR_CLEARTEXT_NOT_PERMITTED in WebView

### ISSUE THREAD

**Issue by chenop** [react-native-community/react-native-webview#1259]
**Bug description:**
Given unsecured links in html
When user click on those links
Then I get an error page with ERR_CLEARTEXT_NOT_PERMITTED 

**To Reproduce:**
Load an html page that include unsecured http links

**Expected behavior:**
Allow redirect to http links

**Screenshots/Videos:**
![image](https://user-images.githubusercontent.com/446575/76943243-b0caf500-6907-11ea-8458-32ac3358472a.png)

**Environment:**
 - react-native version: 0.61.2

Note that my AndroidManifest.xml includes:
`<application android:usesCleartextTraffic="true" />`

Related links:
- https://stackoverflow.com/questions/54752716/why-am-i-seeing-neterr-cleartext-not-permitted-errors-after-upgrading-to-cordo

**Comment by FanShiDe** [comment]
Add the below line in your application tag:

```
android:usesCleartextTraffic="true"
```

As shown below:

```
<application
    ....
    android:usesCleartextTraffic="true"
    ....>
```

Hope it helps.

https://stackoverflow.com/questions/52707918/webview-showing-err-cleartext-not-permitted-although-site-is-https

**Comment by HellzAngel** [comment]
![Screenshot_2020-06-14-15-38-50-690_com intexer](https://user-images.githubusercontent.com/52148921/84593690-07928d00-ae6b-11ea-89f8-bcc2f34bcd2c.jpg)
 I am also faceing same issue

**Comment by harveyconnor** [comment]
@HellzAngel got the same problem, did you solve this?

**Comment by skizzo** [comment]
Adding
```
android:usesCleartextTraffic="true"
```
doesn't help. Any other suggestions?

**Comment by Josnic** [comment]
Hi!

I get the same error, but this solution working!

Thanks!

**Comment by Oscarz90** [comment]
> y other s

how did u solve it?

**Comment by Josnic** [comment]
Hi Oscar.

I fix it adding `android:usesCleartextTraffic="true"` in my AndroidManifest:

![image](https://user-images.githubusercontent.com/13033658/143320303-18d5684d-646f-4607-ac51-5d68c64deb9d.png)

Regards!

**Comment by LYevhen** [comment]
> Adding
> 
> ```
> android:usesCleartextTraffic="true"
> ```
> 
> doesn't help. Any other suggestions?

- Please note that this file (AndroidManifest.xml) is in **main** folder not in debug folder

**Comment by vaishnav-197** [comment]
hey is there anyway to allow cleartext text traffic in android only for the webview ?
like in iOS we do have **`NSAllowsArbitraryLoadsInWebContent`** key

**Comment by rajguptaH** [comment]
https://github.com/rajguptaH/ReactNativeWebView you can take reference from here you just have to add 
```xml
android:usesCleartextTraffic="true"
```
in AndroidManifest.xml file 
and if your expo there is no android folder so you have to use normal template of react native as their official documents have

**Comment by MdIntezarAlam** [comment]
add this lines of code in AndroidMainfest.xml file =>>>>>  android:usesCleartextTraffic="true"

**Comment by Sumansourabh14** [comment]
How to do this in an Expo managed project since there is no android folder present?

**Comment by JohnTechAU** [comment]
> How to do this in an Expo managed project since there is no android folder present? @rajguptaH

You could execute the `npx expo prebuild` command in root of your expo project which will create the android folder.

**Comment by oldo** [comment]
> How to do this in an Expo managed project since there is no android folder present? @rajguptaH

As per https://stackoverflow.com/a/76708333/2987737


> You'll need to use the expo-build-properties plugin
> 
> npx expo install expo-build-properties and then add the config in app.json

```
{
  "expo":
  {
  ...
    "plugins": [
      ["expo-build-properties", {
        "android": {
          "usesCleartextTraffic": true
        },
        "ios": {
          ...
        }
      }]
  }
}
```

**Comment by ErickMaeda** [comment]
I encountered the same issue and was using android:usesCleartextTraffic="true", but it didn't resolve the problem.

To fix it, I had to add `android:networkSecurityConfig="@xml/network_security_config"` as well.

e.g.
```xml
<application
      …
      android:usesCleartextTraffic="true"
      android:networkSecurityConfig="@xml/network_security_config">
```

My network_security_config.xml located at `{reactNativeAppPath}/android/app/src/main/res/xml/network_security_config.xml`:

```xml
<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <domain-config cleartextTrafficPermitted="true">
        <domain includeSubdomains="true">{allowedDomain}</domain>
        <domain includeSubdomains="true">localhost</domain>
    </domain-config>
</network-security-config>

```

**Comment by yussems** [comment]
@ErickMaeda Do you know a way to do this at expo?

**Comment by ErickMaeda** [comment]
> [@ErickMaeda](https://github.com/ErickMaeda) Do you know a way to do this at expo?

No, I'm using expo bare workflow, but you could try the solution provided by @oldo https://github.com/react-native-webview/react-native-webview/issues/1259#issuecomment-2231970799

**Comment by Ikariusx94** [comment]
> [@ErickMaeda](https://github.com/ErickMaeda) Do you know a way to do this at expo?

You can try by:
