### ISSUE TITLE
Fix type for events which are emited from the WebView 

### ISSUE THREAD

**Issue by maxammann** [react-native-community/react-native-webview#126]
The documentation about the emited events is wrong: https://github.com/react-native-community/react-native-webview/pull/107/files/879fbdccf56ea89aad27df07a93e1d9c8cd31d93#diff-186a7fa0ea29d9ede1ed98c48d63340fL82

So either fix the documentation or take a look at the types of the events and set the missing values.
Currently the documentation is not correct for TopMessageEvent and TopShouldStartLoadWithRequest.

**Comment by jamonholmgren** [comment]
Thanks for reporting, @maxammann. I'd love a pull request to our docs!

**Comment by Titozzz** [comment]
Closing as too vague for now. Feel free to submit PRs tho.
