### ISSUE TITLE
canGoBack is true when i use location.replace in Webview

### ISSUE THREAD

**Issue by ChaoYuLeo** [react-native-community/react-native-webview#1261]
**Bug description:**
canGoBack is true when i use location.replace in Webview，expect false

**Expected behavior:**
expect false

**Environment:**
 - OS: Android
 - react-native-webview version: 9.0.1

**Comment by xclidongbo** [comment]
same problem

**Comment by xclidongbo** [comment]
> **Bug description:**
> canGoBack is true when i use location.replace in Webview，expect false
> 
> **Expected behavior:**
> expect false
> 
> **Environment:**
> 
> * OS: Android
> * react-native-webview version: 9.0.1

解决了没?

**Comment by xclidongbo** [comment]
@ChaoYuLeo
