### ISSUE TITLE
injectedJavaScript intercept url buggy on latest IOS version

### ISSUE THREAD

**Issue by BruceSuperProgramer** [react-native-community/react-native-webview#1264]
The code I have for injectedJavaScript is trying to intercept some URL. It working perfectly on any version below ios OS version 12. Any version = or above ios OS version 12 wouldn't do the job. 
  I have two urls request need to intercept. On OS blow 12, both of them could be able to intercept. However, on the version - or above IOS version 12, only first url request would be able to intercept. The second one becomes unable to intercept. Anyone help, please. 

**Environment:**
 - IOS emulator version: 13.3
 - react-native version: 0.61.4"
 - react-native-webview version: 9.0.1

**Comment by wikiwu** [comment]
Same problem.

**Comment by inkCrazy** [comment]
我也有相同的问题，android设备上有数据，iOS设备上没有检测到数据传递到webview网页上。
