### ISSUE TITLE
Android: target attribute _blank doesn't work

### ISSUE THREAD

**Issue by bova80** [react-native-community/react-native-webview#1268]
I have a url that has pdf links in it, and when viewing that link on android when tapping to download the pdf it doesn't trigger a navstate change.  

I have concluded that is due to the link having the target="_blank" attribute on it.  Everything works fine on iOS, but android it appears after the system tries to handle the download it self but then says unsuccessful.  What I was trying to do is intercept the tap event with onShouldStartLoadWithRequest and then pass that URL to RNFetchBlob to do the download.  

Like I said that works great on iOS, but for whatever reason android won't hit onShouldStartLoadWithRequest or onNavigationStateChange with tapping to download pdf.  I've tried injecting some javascript to remove the attribute, but unfortunately the site is an iframe that hosts a LMS course.   

Any help would be appreciated.

Running latest version of react-native-webview

**Comment by fukemy** [comment]
any solution now?
