### ISSUE TITLE
Stop opening Image Links

### ISSUE THREAD

**Issue by oliverdolgener** [react-native-community/react-native-webview#127]
Hey Guys, I have the following problem:

I'm showing a website inside the WebView and I want to handle all links by myself. I'm calling `this.webView.stopLoading()`, so I'll be able to handle to link. This is going well for all kind of links that lead to a website. But if the link leads to an image (e.g https://example.com/image.jpg) then the image will be opened inside the WebView no matter what and that looks just terrible. I have a FullScreenMedia Component to show all kind of images and I want to display images from the WebView inside that Component. Somehow the image links are preloaded so that calling `this.webView.stopLoading()` has no effect on them.

How can I stop the WebView from redirecting to the linked image?

**Comment by Titozzz** [comment]
Can you tell me if you are using android or iOS ? we have a PR that might help you achieve what you need : #107

**Comment by oliverdolgener** [comment]
Oh sorry, I'm using Android

**Comment by Titozzz** [comment]
Would the PR allow you to fix that issue ?

**Comment by oliverdolgener** [comment]
That actually looks very promising. I'll have to test it but from the discussing it seems to be pretty much what I need.

**Comment by jamonholmgren** [comment]
@oliverdolgener We'd love your help testing it!

**Comment by oliverdolgener** [comment]
I just checked out https://github.com/maxammann/react-native-webview/tree/android-onShouldStartLoadWithRequest and noticed some changes in the behaviour of links compared to version 2.5.0. Now all links are opened in a browser and my internal link handling is getting ignored completely. What exactly has changed since 2.5.0? Do I need to set a certain prop?

**Comment by oliverdolgener** [comment]
I just checked the commits since 2.5.0 and in this one https://github.com/maxammann/react-native-webview/commit/2cc89718585407d732004f0eb9c7b7252a587dd7 all navigation events are getting dispatched. How can I catch them? I thought this should happen in `onShouldStartLoadWithRequest` but that's not getting called.

**Comment by oliverdolgener** [comment]
Forget everything I said! I just forget to rebuild the native code :-/
Now it works like a charm and it is exactly what I was looking for!
Thank you! I'm looking forward to it getting merged soon!
