### ISSUE TITLE
Load JS and CSS file

### ISSUE THREAD

**Issue by Umesh079** [react-native-community/react-native-webview#1271]
**Bug description:**
index.html not able to load multiple js and CSS files from the HTML page. 

**To Reproduce:**
1. Create react native app
2. Add webview library
3. Add a folder in root which have index.html , css and more than 30 js files.
4. Now run it 
5. Received error : core.js' cannot be loaded as its extension is not registered in assetExts, for css too i received the error.

**Expected behavior:**
Ideally js and css should get loaded which will show required view.

**Screenshots/Videos:**

**Environment:**
 - OS: iPad
 - OS version:
npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.3 => 0.61.3 
  npmGlobalPackages:
    create-react-native-module: 0.16.0
    react-native-cli: 2.0.1
    react-native-create-library: 3.1.2
 - react-native-webview version: 9.0.1

**Comment by Umesh079** [comment]
There is a workaround that can be followed.

1. create a static server using react-native-static-server.
2. start the server.
3. host the document directory path on localhost and open that on webview.
4. But the only prob here is you can not communicate with those js files present in document directory. It works for all kinds of files. Enjoy !!!.

**Comment by ChenRaul** [comment]
as Umesh079 ,react-native-webview load local html that It works for android,but no ios,and it hint xxxx.js cannot be loaded as its extension is not registered in assetExts.

**Environment:**

OS: iPad
OS version:
 "react": "16.11.0",
  "react-native": "0.62.2",
react-native-webview : 8.0.0;

**Comment by Umesh079** [comment]
Yes you can load the HTML, JS file but can not communicate with the JS file. 
I am struggling to fetch the data from js file.

**Comment by ChenRaul** [comment]
@Umesh079 I'm sry,we need to communicate with the js file.so I need to find other .thanks

**Comment by Umesh079** [comment]
@ChenRaul  If you find something please update here so that I can use it.

**Comment by ChenRaul** [comment]
@Umesh079  Finally, I found the specific problem, which was probably that react-native-webview could not find js, CSS and other resource files imported outside of HTML as webview did before.I used the following url reference method successfully displayed, I hope it is useful for you!https://www.wddsss.com/main/displayArticle/297

**Comment by luojiong** [comment]
I injected the plug-ins I needed directly into the HTML, instead of using the script tag. He hopes this will help you

**Comment by Umesh079** [comment]
I am using react-native-webview and passing the path dynamically using react-native-fs. I am successfully able to load the html, css, js files. To communicate with js file i am using postmessage attribute which will get executed as soon as we are injecting any javascript function dynamically.

**Comment by BocanceaIonut** [comment]
@Umesh079 How do you do that?

**Comment by fukemy** [comment]
> I am using react-native-webview and passing the path dynamically using react-native-fs. I am successfully able to load the html, css, js files. To communicate with js file i am using postmessage attribute which will get executed as soon as we are injecting any javascript function dynamically.

can u give more explain, plz
