### ISSUE TITLE
unable to open item-services-url

### ISSUE THREAD

**Issue by xjf348060793** [react-native-community/react-native-webview#1274]
**Bug description:**
  it is unable to open itms-services-url,
  and window.location.href = "itms-services://*"  can't trigger the onNavigationStateChange 
**Expected behavior:**
  i wanna open items-service-url in webview, who can i do that?

**Environment:**
 - OS:  macos
 - OS version: 10.15.3
 - react-native version: 0.61.5
 - react-native-webview version: 8.1.2

**Comment by yorickshan** [comment]
same issue, any solutions?
