### ISSUE TITLE
Long press cannot invoke the context menu in iOS 13.4

### ISSUE THREAD

**Issue by s1ro6** [react-native-community/react-native-webview#1275]
**Bug description:**
I cannot invoke the context menu by long pressing the WebView.
After upgrade to iOS 13.4 with the same code, only non-notch-screen iPhones (iPhone 6s, iPhone 8, etc) can invoke the context menu, and the notch-screen iPhone and iPads cannot invoke the context menu by long pressing the WebView.

**To Reproduce:**
Open a webpage like github.com, then long press any text.

**Expected behavior:**
It should popup an menu view which looks like the "UIMenuController" in iOS.

**Screenshots/Videos:**
![WeChatWorkScreenshot_7cadd0a3-b8c1-4299-b791-54b4136c1271](https://user-images.githubusercontent.com/8791869/77739031-d2d11f80-704b-11ea-8f4a-81b5ef43f4f6.png)

**Environment:**
 - OS: iOS
 - OS version: 13.4
 - react-native version: 0.62.0
 - react-native-webview version: 9.0.1

**Comment by pmusaraj** [comment]
Looks like a bug with `allowsLinkPreview`. When not set, it looks like it defaults to false and (for some reason) causes iOS 13.4 to disable all text selection (and context menu invocation).

A temporary workaround is to add `allowsLinkPreview={true}`, that seems to work for me.

**Comment by s1ro6** [comment]
> Looks like a bug with `allowsLinkPreview`. When not set, it looks like it defaults to false and (for some reason) causes iOS 13.4 to disable all text selection (and context menu invocation).
> 
> A temporary workaround is to add `allowsLinkPreview={true}`, that seems to work for me.

Thank you, bro. This is works for me, too.
So it seems only the iPhone without 3D Touch has this bug.

**Comment by pmusaraj** [comment]
I think the ticket should be open though, because `allowsLinkPreview` defaults to `false` where in fact it should default to `true` (both for this issue and to match how iOS works).

**Comment by oreillyjw** [comment]
The workaround works by setting `allowLinkPreview` to `true`. At the same time I do not want to allow previewing of link and found that this is a known webkit issue and supposedly has been fixed.

https://stackoverflow.com/questions/61106626/wkwebview-allowslinkpreview-to-false-breaks-text-selection 
Webkit Issue: 
https://bugs.webkit.org/show_bug.cgi?id=210191
