### ISSUE TITLE
React-native-webview crashes when selecting file from upload file.

### ISSUE THREAD

**Issue by tae-at-speer** [react-native-community/react-native-webview#1276]
I'm using Android devices for development and the version of react-native-webview is "^8.1.2".
It works fine for taking picture through webview but whenever selecting file upload, it crashes right after selecting the file or exiting the select file (choose an action).

I've using these options: 
```
mediaPlaybackRequiresUserAction={false}
                        startInLoadingState={true}
                        allowsInlineMediaPlayback={true}
                        allowFileAccess={true}
                        allowUniversalAccessFromFileURLs={true}
                        useWebKit
                        source={{ uri: 'uri' }}
                        originWhitelist={['*']}
```

**Bug description:**

**To Reproduce:**

**Expected behavior:**

**Screenshots/Videos:**

**Environment:**
 - OS:
 - OS version:
 - react-native version:
 - react-native-webview version:

**Comment by dinhduongson** [comment]
me too

**Comment by swathi2378** [comment]
found any solution?

**Comment by danigm87** [comment]
I have the same issue, found you any solution? 🤔

**Comment by TuanDat-Tran** [comment]
same to me

**Comment by sainyanhtay** [comment]
same to me here, any solution, please? This issue shouldn't be closed. 

still happening in "react-native": "0.61.5",  "react-native-webview": "^11.17.2" even granted all READ_EXTERNAL_STORAGE and WRITE_EXTERNAL_STORAGE permissions on Android. 

It is working well in ios.
