### ISSUE TITLE
Does not work with React Native 0.62.0

### ISSUE THREAD

**Issue by fspacerpg** [react-native-community/react-native-webview#1280]
**Bug description:**
Will not yarn in a RN 0.62.0 project and gives following errors:

yarn install v1.22.4
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > react-native-webview@9.0.2" has incorrect peer dependency "react-native@>=0.60 <0.62".
warning " > react-native-windows@0.61.0" has incorrect peer dependency "react@16.9.0".
warning " > react-native-windows@0.61.0" has incorrect peer dependency "react-native@0.61.5".
[4/4] 🔨  Building fresh packages...
warning Error running install script for optional dependency: "/Users/martinrait/Documents/Dev/Mobi2GoStorefrontRN/node_modules/fsevents: Command failed.
Exit code: 1
Command: node install

**To Reproduce:**
In package.json have:
"react-native": "^0.62.0"
"react": "16.11.0"
"react-native-webview": "^9.0.2"
"react-native-windows": "^0.61.0"

**Expected behavior:**
Would like a version release that works with current RN 0.62.0 (and subsequent 0.62.x releases). And a way to remove react-native-windows dependency - since that isn't required for many apps

**Environment:**
 - OS: macOS
 - OS version: 10.15.4
 - react-native version: 0.62.0
 - react-native-webview version: 9.0.2

**Comment by fspacerpg** [comment]
Could be categorised as a feature request.

**Comment by ovy9086** [comment]
can you please post your top `build.gradle` file @fspacerpg  ?
I think I managed to pass this issue by upgrading the kotlin version :
```
buildscript {
    ext.kotlinVersion = '1.3.71'
...
}
```

**Comment by dudeinthemirror** [comment]
Getting the same thing while trying to upgrade react-native from `0.59.9` to `0.62.0`
![Screen Shot 2020-04-01 at 3 53 37 PM](https://user-images.githubusercontent.com/981638/78194581-6df23c80-7432-11ea-8104-8e866aff6896.png)

Are there any plans to add compatibility with react-native `0.62.0` soon? 
Or do you recommend we upgrade to the previous version `0.61.5` instead?
Thank you

**Comment by Florent75** [comment]
+1
I just upgraded to react native 0.62 from 0.59.10 and have the same issue

**Comment by alex521** [comment]
+1

**Comment by Bore-TuDou** [comment]
我也有同样的问题，想问什么时候能够兼容0.62，要不然我们这里 都不能升级0.62了

**Comment by Thientran2910** [comment]
+1 I can't update to react native 0.62

**Comment by Benzer1406** [comment]
Same issue, can't update to RN `0.62` because of this library...will have to replace it

**Comment by SandroMachado** [comment]
In the `build.gradle` of the project, update the kotlin version to this:

```
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.71'
```
