### ISSUE TITLE
Webview scroll jumps erratically when scrolled fast enough

### ISSUE THREAD

**Issue by azkahi** [react-native-community/react-native-webview#1281]
**Bug description:**

Scrolling inside webview is not behaving properly, when you scroll fast enough, it jumps erratically. This doesn't happen when you scroll slowly though.

**To Reproduce:**

Freshly created project using react-native-webview 5.12.1.
```
<WebView source={{uri: "https://mnurrahman.com"}} />
```

**Expected behavior:**

Scroll normally without jumps when you scroll fast.

**Screenshots/Videos:**

https://youtu.be/W_44lhPTJ6k

**Environment:**
 - OS: Android
 - OS version: Android 9.0
 - react-native version: 0.59.5
 - react-native-webview version: 5.12.1

I can't upgrade the webview to the newest version because of AndroidX. I would like to use `react-native-webview` version if possible < 6.0. Any help would be appreciated. Thanks!

**Comment by Dror-Bar** [comment]
Experiencing the same issue with version 5.12.0

**Comment by Dror-Bar** [comment]
Is there a way to use the props `bounces` and `decelerationRate` in Android? perhaps that could fix this problem.

**Comment by MossP** [comment]
Any joy on this one? I'm also seeing this behaviour on 10.8.2

**Comment by martinthedinov** [comment]
I had the same issue on the latest React Native and react-native-webview on Android. The solution was to add this attribute to the `<WebView>` element:

`androidHardwareAccelerationDisabled={false}`

**Comment by luantrasel** [comment]
Any updates on this?

`androidHardwareAccelerationDisabled={false}` didn't solve the problem for me, actually it make it worse...

- react-native-webview version: 11.6.2

**Comment by luantrasel** [comment]
Tested on physical devices (Android 10 and Android 11, both Samsung) and the problem didnt happen
