### ISSUE TITLE
How I write addEventListener in injectedJavascrirpt. I want to listen postMessage

### ISSUE THREAD

**Issue by ahmetaydogduoglu** [react-native-community/react-native-webview#1285]
const injectedJavascript = `
        window.addEventListener("message",function(event){
            window.ReactNativeWebView.postMessage(event)
        })
        `;
        return (
            <Modal visible={true} transparent={true}>
                <View style={{
                    flex: 1,
                    backgroundColor: 'rgba(0,0,0,0.5)',
                    height: "100%",
                    justifyContent: "center"
                }}>
                    <View style={{ width: "90%", height: "95%", alignSelf: "center" }}>
                        <WebView
                            ref={(webView) => this.webView = webView}
                            useWebKit={true}
                            injectedJavaScript={injectedJavascript}
                            source={{
                                html: `
                                    <html>
                                    <body>
                                        <h1>MERHABA</h1>
                                    </body>
                                    <script>
                                        window.postMessage('Bridge is ready and WebView can now successfully receive messages.');
                                    </script>
                                    </html>
                                `,
                            }}
                            style={{ marginTop: 20, flex: 1 }}
                            onMessage={(event) => console.log('onMessage:', event.nativeEvent.data)}
                            onError={(e) => {
                                console.warn('error occured', e)
                            }}
                        />
                    </View>
                </View>

            </Modal>

**Comment by ahmetaydogduoglu** [comment]
@Titozzz help me please. I am waiting for this problem

**Comment by Ak10990** [comment]
What is the fix done here for Android ? @ahmetaydogduoglu
