### ISSUE TITLE
Add allowUniversalAccessFromFileURLs to iOS

### ISSUE THREAD

**Issue by jelder-digital-stack** [react-native-community/react-native-webview#1290]
Currently the prop allowUniversalAccessFromFileURLs is only supported for Android. This means you cant load files from the iOS storage e.g. an image from the phones camera roll, into the WKWebView without receiving the error "Origin null is not allowed by Access-Control-Allow-Origin."

The iOS WKWebView actually includes this config key in the WKWebViewConfiguration, so it's a straightforward fix. I added the line:

`[wkWebViewConfig setValue:@TRUE forKey:@"allowUniversalAccessFromFileURLs"];` 

In the file RNCWebView.m, line 200, to get it to work (after adding to the react-native shared props in the bridge.)

**Comment by RecianuCiprian** [comment]
Hello, is this fix going to be put in the library?
Is there a reason why is not in the official release yet?
