### ISSUE TITLE
How to Listening to HTML content change inside a WebView

### ISSUE THREAD

**Issue by Nirav1432** [react-native-community/react-native-webview#1292]
Please Add New Feature for Listening to HTML content change inside a WebView, I Find Out lot But Can't Get Any Solution,

Wen UI Changed Then We can are get New Html Code

onNavigationChage Event Work Only If we go to from one page to Another, but what for if Content Chageged on Same Page or url

Please Give Any Solution, Thankyou

**Comment by shirakaba** [comment]
Use the injectedJavaScript prop and set a MutationObserver on the part of the page that you’re interested in watching.

**Comment by skArtoon** [comment]
> Use the injectedJavaScript prop and set a MutationObserver on the part of the page that you’re interested in watching.

I Tried But Not Get Success, Can You Give me some peace of code for that ???
