### ISSUE TITLE
"Module WebViewMessageHandler is not a registered callable module (calling onMessage)" when mounting web view

### ISSUE THREAD

**Issue by edmo0031** [react-native-community/react-native-webview#1295]
**Bug description:**

I am getting the following error when using a `WebView` to [react-native-draftjs](https://github.com/DaniAkash/react-native-draftjs)
```
Invariant Violation: Module WebViewMessageHandler is not a registered callable module (calling onMessage).
``` 
This works fine in 8.1.2. I'm guessing its to do with [the main change in 9.1.0 to use the native messaging](https://github.com/react-native-community/react-native-webview/commit/c88e380).\

**To Reproduce:**
Mount the WebView component with that react-native-draftjs pacakge.

**Expected behavior:**
The component should mount a load. 

**Screenshots/Videos:**

**Environment:**
 - OS: Windows
 - OS version: Windows 10 Pro
 - react-native version: 0.61.1
 - react-native-webview version: 9.1.0

**Comment by gabpaet** [comment]
I'm still experiencing this issue, I'm using RN 0.64.2 and react-native-webview 11.14.0
