### ISSUE TITLE
Cookies cleared when property incognito is false

### ISSUE THREAD

**Issue by alekseyanikin** [react-native-community/react-native-webview#1296]
On Android cookies always deleted regardless of incognito is true or false.

**To Reproduce:**
```
<WebView
source={{uri: 'https://google.com'}}
incognito={false}
/>
```

**Expected behavior:**
When prop incognito is `false` cookies are not cleared and cache not removed.

**Screenshots/Videos:**
<img src="https://api.monosnap.com/file/download?id=qiv71YLUDuv9k2PeX5HZV5rSVYV8eL" width="500"/>

**Environment:**
 - OS: Android
 - OS version: Android 9
 - react-native version: 0.62.0
 - react-native-webview version: 9.0.2

**Comment by pdandradeb** [comment]
I've created this PR https://github.com/react-native-community/react-native-webview/pull/1465 to fix this issue.
