### ISSUE TITLE
Android: Black screen on back press

### ISSUE THREAD

**Issue by michan85** [react-native-community/react-native-webview#1297]
**Bug description:**
There is an edge case where while in fullscreen mode on android, the parent webview is removed then the black screen (video background) is still visible. 

In my case i was using react-navigation and had a stack view that opens a webview, when back is pressed the stack closes and removes the webview before the video is hidden, see screenshot.

its worth noting that it is intermittent so might be related to react-navigation but the fact remains that if this case happens you get stuck with a black screen.

 **To Reproduce:**
remove the webview while fullscreen is active

**Expected behavior:**
no black screen remains and app functions as expected

**Screenshots/Videos:**
![react-native-webview-bug-min](https://user-images.githubusercontent.com/207225/78639067-9ef8c400-78ad-11ea-81ff-b0634cf7d861.gif)

https://user-images.githubusercontent.com/207225/78639067-9ef8c400-78ad-11ea-81ff-b0634cf7d861.gif

**Environment:**
 - OS: Android
 - OS version: 6+
 - react-native version:0.61.3
 - react-native-webview version:9.1.0

**Comment by kesha-antonov** [comment]
Same issue
I use react-navigation 4.3.7
Even without video, just html page

**Comment by michan85** [comment]
this pr fixes the issue,
https://github.com/react-native-community/react-native-webview/pull/1298

**Comment by gdoudeng** [comment]
+1
