### ISSUE TITLE
Local Files get cached even if cacheEnabled=false and cacheMode='LOAD_NO_CACHE'

### ISSUE THREAD

**Issue by tobikl1** [react-native-community/react-native-webview#1299]
**Bug description:**
This behaviour is seen when debugging on an actual Android device, not emulator
Android 9

Hi, i am loading a WebPage from local storage with resources also from local storage. We have implemented a sync which might change the resources, like javascript, at any time.

rn-fetch-blob for downloading and react-native-fs for checking existence and stats.

The files get downloaded correctly and when loading stats for the files getting updated (fs.stats(<filePath)) in between, the created and modified date get changed. 
The WebView has cacheEnabled set to false and cacheMode set to LOAD_NO_CACHE, yet the content of the loaded js does not get changed when opening the same html again after update.

*YET*, if i enable incognito mode, it does get updated and cache seems to be disabled.

    {
      ...    
      "react-native": "^0.61.5",    
      "react-native-fs": "^2.16.6",    
      "react-native-webview": "^9.0.2",  
      "rn-fetch-blob": "^0.12.0",  
      ...  
    }

**To Reproduce:**
- Download html and resources into Apps storage (not using external storage)
- Load html as string which contains js existing in baseUrl path (also App storage)  

Code:

    <WebView
      originWhitelist={['*']}
      // ref={(ref) => (this.webView = ref || undefined)}
      // onNavigationStateChange={this.onNavigationStateChange}
      // onShouldStartLoadWithRequest={this.onShouldStartLoadWithRequest}
      source={{ html, baseUrl }}
      allowFileAccess={true}
      allowFileAccessFromFileURLs={true}
      allowUniversalAccessFromFileURLs={true}
      allowingReadAccessToURL={baseUrl}
      // incognito={true}
      javaScriptEnabled={true}
      cacheMode={'LOAD_NO_CACHE'}
      cacheEnabled={false}
    />

- First load: all fine
- Updating the js with new content
- Next Load: still using old js without changes, even though file clearly has changed (modified date changed and reading  js content as a string and logging shows changes as well)

Using incognito actually does what i want but is not intended for this usecase, also if this featureRequest #1231 actually gets approved, will destroy my workaround.
 

**Expected behavior:**
Updated local resources make the cache refresh it, so changes are applied to the webview

**Environment:**
 - OS: Android
 - OS version: 9
 - react-native version: 61.5
 - react-native-webview version: 9.0.2

**Comment by dmexs** [comment]
I just noticed a related issue tonight.

I serve images via single-use urls (Rails ActiveStorage) from my app server. I noticed that on repeat views of the page the images would not load even after setting the cacheEnabled prop to false. As you noticed, setting incognitoMode achieved what I was looking for.

**Environment:**
* OS: iOS (not tested on Android yet)
* OS version: 12.4
* react-native version: 0.61.3
* react-native-webview version: 9.1.4

**Comment by hzw0407** [comment]
> * he js with new content
> 
> *

I have the same problem. How did you solve it？

**Comment by tobikl1** [comment]
As stated above i am using the webview in inkognito mode right now. it solves the problem for now.

**Comment by zeeshanwarriach93** [comment]
WebView version you have used is imported from 'react-native' which is deprecated now please update to the latest version
