### ISSUE TITLE
MIGRATED: WebView ScrollEnabled={false} Bug w/ Keyboard iOS Only (#20793)

### ISSUE THREAD

**Issue by Titozzz** [react-native-community/react-native-webview#13]
Migrated from facebook/react-native#20793.

@PvanHengel says:

---

When using a WebView with the scrollEnabled prop set to false, the scrolling is disabled as expected, however, if the user focus a text area within the webview, and the keyboard displays, the scroll view automatically scrolls up to offset for the keyboard, there is no way for the user to scroll back down to see the content at the top of the page because scrolling is disabled. When scrollEnabled is set to true, and the keyboard is shown, the page should not scroll up to avoid they keyboard (or at least there should be a prop to adjust this). Note that if you use window.scrollTo(0,0) on a timer, it will scroll up, but then scroll back into view.

---

_More infos in the original thread_

**Comment by Salakar** [comment]
@PvanHengel I'll go ahead and close this issue given that there's been no further activity for a few months. If you want this re-opened please let me know.

**Comment by JeremyBradshaw7** [comment]
So is this still a bug?

**Comment by jamonholmgren** [comment]
@JeremyBradshaw7 I'm not sure -- want to check it and see if it is?

**Comment by bulby97** [comment]
Here is the bug.

![togif](https://user-images.githubusercontent.com/3509412/62004518-4b5ca500-b17a-11e9-9f0b-e3c515da8cf3.gif)

**Comment by kopax** [comment]
I am having the same issue and I don't know how I can solve this. It only happen on portrait mode.
