### ISSUE TITLE
Support for KeyboardAvoidingView behaviors?

### ISSUE THREAD

**Issue by TuckerWhitehouse** [react-native-community/react-native-webview#130]
Current Behavior
- When an input is focused in a WebView, the keyboard forces the view to move up (so the top of the view is off of the screen), and there isn't a documented way of changing this.

Expected Behavior
- A method for customizing the behavior (similar to the `behavior` attribute of a `KeyboardAvoidingView`).

Attempted Solution
- Wrapping the `WebView` in a `KeyboardAvoidingView`, this does not disable the built in behavior of the `WebView` so you get a bunch of extra whitespace.

Is there a way of achieving a result similar to setting `behavior="height"` on a `KeyboardAvoidingView` with this package, or would a change need to be made here (and is that a change you'd be willing to make)?

**Comment by jamonholmgren** [comment]
Hey @TuckerWhitehouse, we don't currently have support for this. Is that something you'd want to take a shot at adding? We'd be happy to discuss any ideas you have. Bonus points for thinking cross-platform.

**Comment by TuckerWhitehouse** [comment]
Does it make sense to mark feature requests as stale and automatically close them? Is there somewhere outside of github issues where feature requests are being tracked?

**Comment by Titozzz** [comment]
well if no one ever comments on it, maybe? This is a trial so I'll happily listen to people reactions.

**Comment by donysukardi** [comment]
Hi @jamonholmgren @Titozzz, can we revisit this? I've been struggling to get the integration between current implementation of KeyboardAvoidingView and WebView to work nicely.

**Comment by jacobmolby** [comment]
Anybody have a solution for this?

**Comment by rado196** [comment]
the problem still exists. :/

**Comment by josegoval** [comment]
Any updates or plans to do it? 👀
