### ISSUE TITLE
Text selection in webview is not working in latest iOS version 13.4.1

### ISSUE THREAD

**Issue by panda0603** [react-native-community/react-native-webview#1303]
**Bug description:**
just updated to latest IOS 13.4.1, 
text selection within webview is not working anymore. 
Worked fine until 13.3

**To Reproduce:**
Upgrade to latest iOS version 13.4.1

**Comment by asdelatoile** [comment]
Solution for me. Add **allowsLinkPreview={true}** https://github.com/react-native-community/react-native-webview/issues/1275#issuecomment-606359190

**Comment by hoanganhnh2009** [comment]
> Solution for me. Add **allowsLinkPreview={true}** [#1275 (comment)](https://github.com/react-native-community/react-native-webview/issues/1275#issuecomment-606359190)

Work for me
