### ISSUE TITLE
This package uses Deprecated API Usage as per new Apple Policy from April 2020

### ISSUE THREAD

**Issue by karan12990** [react-native-community/react-native-webview#1304]
While uploading build to Apple app store, getting error like below. 

![image](https://user-images.githubusercontent.com/6735468/78761592-73a2d180-79a0-11ea-95e8-17d66bc04278.png)

Any suggestions? 
Is this package good alternative (https://www.npmjs.com/package/react-native-wkwebview-reborn) ?

**Comment by cristianoccazinsp** [comment]
I don't think this library uses UIWebView anymore, it is probably another package using it.

`cd node_modules`
`grep -rl "UIWebView" .  `

**Comment by karan12990** [comment]
Thanks @cristianoccazinsp 

Finally, i realize that react-native it self using webview into the node_modules /react-native.

So i need upgrade my React native version. Without that not possible to upload app on App store.

**Comment by wildseansy** [comment]
@karan12990 - can have a post-install step maybe that removes react-native modules in node_modules that reference webview.  Haven't tried it but worth a shot.

**Comment by tanhao8** [comment]
What is the final solution? Forgive me for being a rookie

**Comment by karan12990** [comment]
I did not find any solution , so i have upgrade my whole project into newer version.

**Comment by jamonholmgren** [comment]
Shouldn’t be RN WebView if you’re using a recent version. Try the grep command above to find the offending package.
