### ISSUE TITLE
multiple webview hangs the app

### ISSUE THREAD

**Issue by PrasannaLearnyst** [react-native-community/react-native-webview#131]
```
import { WebView } from 'react-native-webview';

class Discussions extends Component {
  render() {
  let { htmlData } = this.props;
    return (
      <WebView
        source={{ html: htmlData }}
        style={{ marginTop: 20 }}
      />
    );
  }
}
```
I have list of discussions, where all the discussion data in html, if i loop through discussions > 20,
then the app crashes.

**Comment by Titozzz** [comment]
Hello, android or iOS ?

**Comment by PrasannaLearnyst** [comment]
@Titozzz  its Android

**Comment by Titozzz** [comment]
I'm not sure what would work the best for your use case

**Comment by jamonholmgren** [comment]
@PrasannaLearnyst Can you post a minimal app that reproduces this behavior and link it here? That will let us see what's happening easier. Thanks!

**Comment by feiooos** [comment]
We have the same problem in our codebase. Rendering multiple webviews, with heavy websites being loaded, I guess, are causing crashes for us.

I can't say for sure yet if it's because we simply load multiple webviews or if it has to have the combination of loading multiple webviews with heavy websites being loaded in them.

It would be great if someone could try out in an isolated test to see where the problem comes from. At the moment I personally can't spend much time with it.

**Comment by punksta** [comment]
we have similar problem in company I am working. Rendering many webview in flatlist with html is not working properly. List scrolls slow and sometimes it takes few seconds for flat list item to appear.
it happens only on low price android devices.

**Comment by jamonholmgren** [comment]
I was able to load 40 instances of WebView with source set to the https://www.mathjax.org/ website as mentioned above before I started having problems.

<img src="https://user-images.githubusercontent.com/1479215/50542183-1d739b80-0b6c-11e9-8286-38fd3f884385.png" width="200" />

It would be nice to have a way to replicate this issue reliably.

**Comment by punksta** [comment]
https://snack.expo.io/H1FUi4ffV
Here is demo. Webviews just render `hello` message.

I tested it on core webview and react-native-webview with react-native 0.57.8 and 0.57.0

On google emulators and nexus 5x screen is blinking sometimes, but it's rending somehow.
But on some devices the whole screen is just blank when you open it. you have to scroll down few webviews and up to make ui appear or pause and resume app few times. 
**I am using huawei p20 lite**

### real word app issue
I don't render so many webviews in the same time in production app. Usually there are 2-3 webview on single screen or list of 10-15 webviews. The production app issue is similar to this example. Either the whole container with webview is invisible or some parts of webview are not visible but present in rn inspector. Removing webview from ui makes it work good. Also scrolling up and down or app pausing and resuming helps.
#### real word app affected devices
- Samsung J6 2018 , 
- One plus 6 android 9,
- Moto Z play
- LG Stylus 2,
- huawei p20 lite
- etc..

hope it will help.

**Comment by Titozzz** [comment]
@punksta So are you having issues with the core webview or with the one from this repository. You can not demonstrate bugs with our webview on expo(snack) as this is a native module.

Are you talking about a possible regression between react-native 0.56 and react-native 0.57?

**Comment by punksta** [comment]
@Titozzz I am having problems with both webviews. https://snack.expo.io/H1FUi4ffV this example works same on core and repo's versions.
Downgrading from 0.57 to 0.56 with solved all issues.

**Comment by punksta** [comment]
@Titozzz https://github.com/punksta/rn-webview-performance-issue I just created native examples.

https://raw.githubusercontent.com/punksta/rn-webview-performance-issue/master/webview.webm demonstration video. You can notice that on react-native 0.57 screen is blinking and sometimes it's just blank. On devices from my list screen is blank most of the time.

**Comment by Titozzz** [comment]
oh ok I understand your issue if think. Use overflow: 'hidden' around the webviews, there is a bug since android 0.57 that makes webviewLoadingScreen overflow all over the screen.

**Comment by punksta** [comment]
@Titozzz hmm, that fixed my example. Thanks! Will check production app tomorrow. 
Could you share this bug reference if you know it?

**Comment by Titozzz** [comment]
https://github.com/react-native-community/react-native-webview/issues/194

**Comment by punksta** [comment]
@Titozzz Thanks. This bug is very annoying .

**Comment by jamonholmgren** [comment]
Looks like this has been resolved. Feel free to open a new issue if you're still experiencing issues.
