### ISSUE TITLE
injectedJavaScript prop does not working properly on iPhone 

### ISSUE THREAD

**Issue by Great-hijack** [react-native-community/react-native-webview#1310]
**Bug description:**
I want to catch email address when login button clicked. My code is working well on my android, but not on iPhone.
injectedJavaScript prop does not working properly on iPhone.

**To Reproduce:**
_**This code is working well on android, but not for iPhone.**_
```
handleOnMessage = (event) => {
  console.log(event.nativeEvent.data);
};

...
render() {
    const INJECTED_JAVASCRIPT = `
      try {
        var loginBtn = document.evaluate("//*[@id='root']/div[2]/div[2]/div/div[4]/button[1]", document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue;
        loginBtn.onclick = function() {
          var email = document.getElementById("email").value;
          window.ReactNativeWebView.postMessage(JSON.stringify({email: email}));
        };true;      
      } else {
        window.ReactNativeWebView.postMessage(JSON.stringify({error: "Why catch error"}));
      }`;

    return (
      <WebView
        ref={(r) => (this.webref = r)}
        source={{uri: this.state.url}}
        injectedJavaScript={INJECTED_JAVASCRIPT}
        onMessage={this.handleOnMessage}
        startInLoadingState={true}
        renderLoading={() => <Text>Loading...</Text>}
      />
    );
}
```
After running app, console logged "Why catch error".
Finally I found _loginBtn_ is null, but not sure why.
I was held with this issue for 3 days. It will be great if anybody can help me.

**Expected behavior:**
I get expected result "email: myemail@mail.com" on my android and it should be same on iPhone.

**Screenshots/Videos:**

**Environment:**
 - OS: MacOS
 - OS version: 10.15.3
 - react-native version: 0.62.1
 - react-native-webview version: 9.1.1

**Comment by shirakaba** [comment]
This is not a failure of `injectedJavaScript`, as indeed you are receiving the "Why catch error" response.

This is only failing because, as you say, `loginBtn` was found to be `null`. I think you should simplify the way that you get a reference to `loginBtn`, as maybe it's not cross-platform (i.e. it works on the Android browser, but not the iOS one). Can you not get a reference to the button more simply using `document.getElementById()`? Sorry, I'm not familiar with `document.evaluate()`, nor the limitations that you're working within for your particular webpage.

**Comment by Great-hijack** [comment]
@shirakaba 
I already tried to get a reference to the other elements using `document.getElementById()` but got null for all elements.

**Comment by shirakaba** [comment]
@Great-hijack Are you able to show us the webpage (`this.state.url`)? It's impossible to assist any further with this (which is a website-specific problem, rather than a WebView-specific problem) without knowing any more details.

**Comment by Great-hijack** [comment]
@shirakaba 
https://journal-dev-6f6f4.web.app/
I think it is not website-specific since getting all elements return null.
anyway, still need help

**Comment by shirakaba** [comment]
@Great-hijack 

Is the element you're looking for?

```html
<input aria-invalid="false" id="email" placeholder="Email Adress" type="email" class="MuiInputBase-input MuiInput-input jss20" value="">
```

It doesn't exist in the page's initial HTML code, so it clearly loads in *some time* later (but not clear when, exactly); so I think this may be a race condition.

First of all, what happens if you simply delay the code momentarily, like this?

```js
const INJECTED_JAVASCRIPT = `
  setTimeout(() => {
    try {
      var loginBtn = document.evaluate("//*[@id='root']/div[2]/div[2]/div/div[4]/button[1]", document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue;
      loginBtn.onclick = function() {
        var email = document.getElementById("email").value;
        window.ReactNativeWebView.postMessage(JSON.stringify({email: email}));
      };true;      
    } else {
      window.ReactNativeWebView.postMessage(JSON.stringify({error: "Why catch error"}));
    }
  }, 2500);
`;
```

**Comment by Great-hijack** [comment]
@shirakaba Thank you
It works but only one time.
If I input wrong credential and try again, it doesn't return expected result.
I mean I get null onward 2nd attempts.
about 2500, is it a magic number? why 2500? what about 1000 or 3000?

**Comment by shirakaba** [comment]
@Great-hijack

> about 2500, is it a magic number? why 2500? what about 1000 or 3000?

Yes, the 2500 is just a magic number to give the page some time to load. Any other number could equally work.

The webpage design is strange. The login button is unmounted by React DOM after you input some wrong credentials and click 'login'. So your original `onclick` handler is attached to a button that is no longer mounted in the DOM.

You can confirm this yourself; go into the Web Inspector and add an `id` property to the login button. You'll see that, after an unsuccessful login, the button's `id` property disappears. By storing a reference to it, you'll even see that it is no longer the same button as the original button.

So you'd need to re-attach the `onclick` handler to the latest 'version' of the button after every form submission to have a hope of this working. There are a few ways to achieve this, but you'd need to experiment. As it's all sounding a bit hacky, it's time to think about whether injecting JS into this login form is even the right approach in the first place.

I'm not sure why you're forwarding someone's login details from the website to the native app. It has security implications, and is likely not the right way to handle login. What exactly are you trying to achieve?

**Comment by Great-hijack** [comment]
>  the button's id property disappears

So if login button has specific id property, it will works?
> As it's all sounding a bit hacky, it's time to think about whether injecting JS into this login form is even the right approach in the first place.

This is not a kind of hack, I responsible for mobile dev while other mate is for webapp dev.

**Comment by shirakaba** [comment]
> So if login button has specific id property, it will works?

No, you’ll still need to re-attach the `onclick` handler to it each time it’s remounted, so the id won’t help much (because you don’t have a listener for when it’s being remounted).

Can’t the developer of the mobile app add the logic that you need into the click handler of the button so that it will be in place each time the button is remounted?
