### ISSUE TITLE
'navigationType' property is missing from the event passed to 'onNavigationStateChange' on Android

### ISSUE THREAD

**Issue by iancucatalin1993** [react-native-community/react-native-webview#1314]
**Bug description:**
The WebView navigation listener 'onNavigationStateChange' only has the following properties on Android
```
{
  canGoForward: false
  canGoBack: false
  title: ""
  loading: false
  url: "about:blank"
  target: 3723
}
```

According to the following library code fragments ```navigationType``` shoud be present and have one of the defined values:
```
export interface AndroidWebViewProps extends WebViewSharedProps {
    onNavigationStateChange?: (event: WebViewNavigation) => void;
.....
}
export interface WebViewNavigation extends WebViewNativeEvent {
    navigationType: 'click' | 'formsubmit' | 'backforward' | 'reload' | 'formresubmit' | 'other';
    mainDocumentURL?: string;
}
```

**As it is, there is no proper way that I know of to determine whether the user clicked on something to initiate a navigation, or the redirect was automatic as it often happens with social media embeds.**

I don't have an iOS build, but according to other iOS developers it seems to be working there.

**To Reproduce:**
Assign `onNavigationStateChange` listener to a WebView on Android. The property navigationType is missing entirely
```
<WebView
        onNavigationStateChange={this.onNavigationStateChange}
        {...this.props}
 />

onNavigationStateChange = (navState) =>
{
   //  typeof navState.navigationType === 'undefined'
}
```

**Expected behavior:**

```
onNavigationStateChange = (navState) =>
{
    if (navState.navigationType === 'click') {
        // User clicked something
    }
}
```

**Environment:**
 - OS: Android
 - OS version: any
 - react-native version: <= 0.62.2
 - react-native-webview version: <= 9.1.3

**Comment by DmitryFt** [comment]
Also having this issue, RN 0.63.3, RNWebview 10.9.2

**Comment by bastienJanon** [comment]
i'm facing the same issue. When the debugger is active event.navigationType return 'click' as expected but when debugger is off event.navigationType is undefined.

**Comment by JohnTsaiAndroid** [comment]
Any solutions?

**Comment by VanLaerAshley** [comment]
any solutions?

**Comment by VanLaerAshley** [comment]
This should be open

**Comment by peterdee** [comment]
Having the same issue with Android. iOS works fine.

I am using React Native with Expo (Expo SDK 40).

**Comment by erkie** [comment]
It's iOS only.  https://github.com/react-native-webview/react-native-webview/pull/1880

You can use my fork instead: https://github.com/react-native-webview/react-native-webview/pull/1881
