### ISSUE TITLE
Error:crypto.getRandomValues() not supported?

### ISSUE THREAD

**Issue by a4646054** [react-native-community/react-native-webview#1315]
**Bug description:**
![error](https://user-images.githubusercontent.com/63498123/79042241-6c8df480-7c28-11ea-87b2-7e01c8182752.png)

**To Reproduce:**

**Expected behavior:**

**Screenshots/Videos:**

**Environment:Error:crypto.getRandomValues() not supported?
 - OS:
 - OS version:android 9.0
 - react-native version:0.62.2
 - react-native-webview version:9.1.4

**Comment by mym0404** [comment]
How can you resolve this problem?? @a4646054

**Comment by abdul-rightapps** [comment]
How can you resolve this problem?? @a4646054

**Comment by mym0404** [comment]
This is duplicate with other issue in that, this is resolved with import react-native-grt-random-values

**Comment by nasreekar** [comment]
Did anyone manage to fix this issue?

**Comment by mym0404** [comment]
> Did anyone manage to fix this issue? 
> 
> 

see #1312
