### ISSUE TITLE
HTTPS error using static html

### ISSUE THREAD

**Issue by johnvalari** [react-native-community/react-native-webview#1317]
**Bug description:**

I'm getting an error from my Stripe Integration when using live. 
```
IntegrationError: Live Stripe.js integrations must use HTTPS.
```
I'm wondering if there is a way to set the WebView to https.

**To Reproduce:**

```
<WebView
  source={{
       html: stripeCheckoutHTML(clientSecret),
   }}
/>
```

**Environment:**
 - OS: Mac OS
 - OS version: 10.15.3
 - react-native version: 0.60.4
 - react-native-webview version:8.2.0

**Comment by rezvalari** [comment]
I was able to fix this by adding `baseUrl: ''`

**Comment by legend27sg** [comment]
Regarding android i found something on [https://developer.android.com/reference/android/webkit/WebView#loadDataWithBaseURL(java.lang.String,%20java.lang.String,%20java.lang.String,%20java.lang.String,%20java.lang.String)](url)

> If a valid HTTP or HTTPS base URL is not specified in baseUrl, then content loaded using this method will have a window.origin value of "null". This must not be considered to be a trusted origin by the application or by any JavaScript code running inside the WebView (for example, event sources in DOM event handlers or web messages), because malicious content can also create frames with a null origin. If you need to identify the main frame's origin in a trustworthy way, you should use a valid HTTP or HTTPS base URL to set the origin.

Instead of putting baseUrl: ''
I inserted my backend endpoint for baseUrl and its working for me

**Comment by bharding216** [comment]
@legend27sg thank you so much. Using the base url for my backend fixed it immediately.
