### ISSUE TITLE
Use of undeclared identifier '_ignoreSilentHardwareSwitch'

### ISSUE THREAD

**Issue by Sanglepp** [react-native-community/react-native-webview#1320]
**Bug description:**

After an update to version 9.2.0 the application failed to build. Getting the error "Use of undeclared identifier '_ignoreSilentHardwareSwitch'" RNCWebView.m

**To Reproduce:**

1. Update react-native-webview version to 9.2.0
2. Run pod install
3. Build the project
4. See the error

**Expected behavior:**

After the update, application should build without any errors from react-native-webview

**Environment:**
 - OS: iOS
 - OS version: 13.3
 - react-native version: 0.61.5
 - react-native-webview version: 9.2.0

**Comment by dmexs** [comment]
I'll echo that I had the same error that resolved with a downgrade to 9.1.4

Environment:
* OS: iOS
* OS version: 12.0
* react-native version: 0.61.3
* react-native-webview version: 9.2.0

**Comment by Sanglepp** [comment]
@dmexs I had to downgrade also to 9.1.4.

**Comment by waqas19921** [comment]
Wait for this https://github.com/react-native-community/react-native-webview/pull/1319 to be merged.

**Comment by iKuu01** [comment]
I downgrade 8.0.1 it works

**Comment by redrose2** [comment]
I downgrade to 9.1.4, it works.

**Comment by CyrusZei** [comment]
merged yet ?

**Comment by fanyui** [comment]
@ChrusZei I guess its not been merged. I just landed on that same error. Downgrading to 9.1.4

**Comment by Great-hijack** [comment]
I have been wondering with this issue for 2 days.
Now testing with 9.1.4.
But also waiting for update.

**Comment by Great-hijack** [comment]
![image](https://user-images.githubusercontent.com/57619523/79251773-31532600-7eb3-11ea-84ff-0d579b945482.png)

I tried with 9.1.4, but got same error.
Welcome any help :)

**Comment by Sanglepp** [comment]
@Great-hijack Your pod installation is probably still 9.2.0.

**Comment by Great-hijack** [comment]
@Sanglepp 
I removed ios/Pod and node_modules. And tried with "yarn install" and "cd ios & pod install".
What should I do?

**Comment by elkinjosetm** [comment]
I've got the same problem, but I was able to solve it by downgrading to `9.1.4`

**Comment by Great-hijack** [comment]
@elkinjosetm 
Could you guide me step by step how to downgrade to 9.1.4?

**Comment by Kusumoto** [comment]
I have a some problem, You can workaround to resolve this problem by change `"react-native-webview": "^9.1.4",` to `"react-native-webview": "~9.1.4",`

**Comment by elkinjosetm** [comment]
> @elkinjosetm
> Could you guide me step by step how to downgrade to 9.1.4?

Sure, first  just need to uninstall your current dependency. `yarn remove react-native-webview` and then you'll have to install it using an specific version: `yarn add react-native-webview@9.1.4`

**Comment by Great-hijack** [comment]
@elkinjosetm @Kusumoto  Thank you all.
I tried with `yarn add react-native-webview@^9.1.4`  which was my misunderstanding.
Thanks again.

**Comment by gregoryfm** [comment]
#1319 has been merged and released. 
Update to v9.2.1.

**Comment by Great-hijack** [comment]
@gregoryfm 
New issue with v9.2.1 on android.

![image](https://user-images.githubusercontent.com/57619523/79298559-0d73fc80-7f14-11ea-9e95-53de58b980eb.png)

**Comment by gregoryfm** [comment]
@Great-hijack look at these comments https://github.com/react-native-community/react-native-webview/issues/1312#issuecomment-611905017 and https://github.com/react-native-community/react-native-webview/issues/1312#issuecomment-611905691 it will help you.
