### ISSUE TITLE
White Blank on iOS method POST

### ISSUE THREAD

**Issue by achimbaggins** [react-native-community/react-native-webview#1323]
Hi guys I'm facing then issue when using WebView with POST method , everything run as expected for Android Platform. but WhiteBlank in iOS simulator and iOS devices.

is anyone have solve the issue?

I wrote the code like this:
```
<WebView
                                ref={'WEBVIEW_REF'}
                                onNavigationStateChange=
                                {this.onNavigationStateChange}
                                onLoad={() => this.setState({loadingURL:true})}
                                startInLoadingState={true}
                                style={{ flex:1}}
                                useWebKit
                                allowUniversalAccessFromFileURLs
                                mixedContentMode = "always"
                                originWhitelist = {['*']}
                                ignoreSslError={true}
                                source={{
                                    uri: redirect_url,
                                    method: 'POST',
                                    body: 'message='+token,
                                }}
                            />
```

**Comment by achimbaggins** [comment]
headers: { 'Content-Type': 'application/x-www-form-urlencoded', }

just added header solve the problem

**Comment by JamesKindyHub** [comment]
@achimbaggins can you post your working code?

I'm having the same issue but when I add in headers nothing changes.

`                    <WebView
                        onLoad={() => this.hideSpinner()}
                        style={{flex: 1}}
                        javaScriptEnabled={true}
                        domStorageEnabled={true}
                        renderError={(error) => console.log('error:' + error)}
                        source={{
                            uri: report_url, method: 'post', body:
                                'ref=' + params.guid + '&act=' + params.activity + '&access_token=' + this.state.userToken
                        }}
                        headers={ 'Content-Type', 'application/x-www-form-urlencoded' }
                    />`

**Comment by keremcubuk** [comment]
Hi @JamesKindyHub,

I'm having same problem about IOS POST method. This is my code block as below.

This code blocks work on **react-native-webview v6** in **IOS**, but it doesn't work on _v7 and above_. **_Android works well._**

```javascript
 componentDidMount() {
    const formData = new FormData();
    formData.append('customerToken', myToken);
    formData.append('menu_code', this.props.menuCode);
    formData.append('languageCode', this.state.language.toUpperCase());

    fetch(myRequestURL, {
      method: 'POST',
      headers: {
        Accept: 'application/json',
        'Content-Type': 'multipart/form-data',
      },
      body: formData,
    })
      .then(response => response.text())
      .then(text => {
        this.setState({ html: text });
      });
  }

  render() {
    return (
      <WebView
        useWebKit={false}
        originWhitelist={['*']}
        scalesPageToFit={false}
        source={{
          html: `<meta name="viewport" content="width=device-width, initial-scale=1">${this.state.html}`,
          baseUrl: myRequestURL,
        }}
        onLoadStart={() => showLoader()}
        onLoadEnd={() => dismissLoader()}
      />
    );
  }
```

**Enviroment Informations:**
- npmPackages:
    react: 16.13.1 => 16.13.1 
    react-native: 0.62.2 => 0.62.2 
- react-native-webview: 10.10.2
