### ISSUE TITLE
RNCWebView Crash - Completion handler was not called / presenting controller whose view is not in the window hierarchy

### ISSUE THREAD

**Issue by jxm2004** [react-native-community/react-native-webview#1325]
**Bug description:**
In the runJavaScriptAlertPanelWithMessage method, in RNCWebView, the following line of code can cause a crash:

[[self topViewController] presentViewController:alert animated:YES completion:NULL];

Presumably the same is possible in runJavaScriptConfirmPanelWithMessage & runJavaScriptTextInputPanelWithPrompt as well. TopViewController in the case of trying to select a file (photo/video/..) is UIImagePickerController, but it is dismissed as soon as the file selection is made, hence the crash below:

2020-04-16 20:27:22.715114-0400 homeDepot[47590:3894842] Warning: Attempt to present <UIAlertController: 0x10224f800> on <PUPhotoPickerHostViewController: 0x102238a00> whose view is not in the window hierarchy!
2020-04-16 20:27:22.721279-0400 homeDepot[47590:3894842] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Completion handler passed to -[RNCWebView webView:runJavaScriptAlertPanelWithMessage:initiatedByFrame:completionHandler:] was not called'

Top viewController in these cases should be the presentingViewController, and the alert should shown there.
 

**To Reproduce:**
Try to select a file that a particular server will not accept for some reason (file type, size of image, etc).

**Expected behavior:**
An alert should be displayed on the correct view. 

**Screenshots/Videos:**
Screenshot of what would be expected:
![wrongSizedImage](https://user-images.githubusercontent.com/21090566/79518530-5795d480-801f-11ea-80b2-f1a70c7f4085.PNG)

**Environment:**
 - OS: iOS
 - OS version: 13.3.1
 - react-native version: 0.60.5
 - react-native-webview version: 9.2.1 (NOTE: just updated it to 10.2.3)

**Proposed/Potential Solution**
The solution to me seems pretty clear, in the case of UIImagePickerController, return the presentingViewController and not the presented one. I've taken the liberty of doing the simple required change here:

https://github.com/jxm2004/react-native-webview/commit/66b86887831cbcbef99a5c79d9034f4d75081074

**Comment by hellosam1332** [comment]
Thanks this helped my problem. Hope it will be on next release

**Comment by FansPro** [comment]
Same error here.

**Comment by tellodaniel** [comment]
+1

**Comment by jxm2004** [comment]
This has now been merged in and is available in 10.4.1 and onwards 🎉; closing
