### ISSUE TITLE
Cannot access camera in IOS Devices .

### ISSUE THREAD

**Issue by kaissaroj** [react-native-community/react-native-webview#1326]
I am trying access a barcode scanner website in my react native app. I can open camera in android device but cannot access camera inside Webview in IOS device.

**Comment by thenameisdavid** [comment]
Sadly, this is still a limitation imposed upon us by Apple. To date, no solution exists which solely utilizes WKWebView.

**Comment by falay26** [comment]
I can not try it on a real device right now but this issue still exists in snack expo.

**Comment by Kulsoom2** [comment]
Yeah this issue is still here, any update on this?

**Comment by alubeck** [comment]
If the webview markup consists of `<input type="file" ... />` then for me it's the other way around. I'm getting presented the option to take a picture on iOS, but on Android I just see the gallery without a way to take a picture directly:

iOS: 12.4.5
Android: 7
rn-webview: 8.0.3
