### ISSUE TITLE
Open the App Store or Play market via webview

### ISSUE THREAD

**Issue by lordenas** [react-native-community/react-native-webview#1327]
When I try to follow the link in AppStore, I get the error "Error loading"
On Android, an error occurs when you click on the "Open in Playmarket.

<img width="315" alt="Screenshot at Apr 17 16-01-13" src="https://user-images.githubusercontent.com/15974195/79572252-4bfce900-80c5-11ea-9414-98ffb6bca2ba.png">

react-native-webview 8.2.1
react-native 0.61.5

link in html

```
< a href="https:/ /apps.apple.com/ru/app/google/id284815942">Update IOS</a >

< a href="https:/ /play.google.com/store/apps/details?id=com.google.android.googlequicksearchbox&hl=ru">Update Android</a >
```

**Comment by binhndicts** [comment]
You should override this `onShouldStartLoadWithRequest` method, use Linking.openUrl if the url match your case. Remember to return `false` to prevent webview continue loading the url

**Comment by lordenas** [comment]
> You should override this `onShouldStartLoadWithRequest` method, use Linking.openUrl if the url match your case. Remember to return `false` to prevent webview continue loading the url

Yes I know that. But we expected the store to be open. Thus, we wanted to force updated users.

**Comment by binhndicts** [comment]
@lordenas I don't understand what you meant. Do you call `Linking.openUrl`? AppStore/GooglePlay should be opened by the method if you pass the correct url.

**Comment by lordenas** [comment]
Links to the AppStore/Google Play are not registered in the app, but on an external web resource ( in html ).
We expected to open the App Store/Google Play app when opening the link via react-native-webview, but we get an error.

Try opening any Google Play page using reactor-native-webview. the site will prompt you to open the page in the GooglePlay app. But when you click this button, webview crashes with an error. This is most likely due to the fact that the platform (Android, IOS) is trying to replace the https://... link with market://details... and webview cannot open such links.
