### ISSUE TITLE
Replace uiwebview with kwwebview

### ISSUE THREAD

**Issue by tanhao8** [react-native-community/react-native-webview#1329]
React-native-webview version 8.0.1, submit the app to the app store and feedback that uiwebview will be eliminated. Do you have a solution?

**Comment by tanhao8** [comment]
help me,please

**Comment by tanhao8** [comment]
@jamonholmgren @Salakar @Titozzz @alloy @imownbey @react-native-community-bot @safaiyeh @Ehesp @jamonholmgren @empyrical @Salakar

**Comment by Salakar** [comment]
I heard that if you tag another 10 random people in this issue you'll get a much quicker response, don't  tell anyone though about this secret GitHub hack 🤫

Bonus hack; fill out the issue template and provide more details as it may be a dependency that using UIWebView rather than this library

**Comment by tanhao8** [comment]
@Salakar I'm sorry to use this way. Is uiwebview or kwwebview used in react native WebView 8.0.1?

**Comment by Salakar** [comment]
See https://github.com/react-native-community/react-native-webview/issues/1304
