### ISSUE TITLE
Remote uri and local uri

### ISSUE THREAD

**Issue by AnirudhSharmap7** [react-native-community/react-native-webview#1330]
Hi,
I am new to react-native and the webview component.
I have a webpage which is at a static IP.
When i pass the IP to the source prop ( uri object ) the webview renders.
My doubt is..
Is there a way to pass the local IP (i.e 192.168.0.101 (in this series))
when I am within the local network.
Or is there a way to do if else with the IP's (i.e remote and local) and pass to the URI.
I am really sorry if this question was asked before as i could not 
find the link.

regards,
Anirudh

**Comment by AnirudhSharmap7** [comment]
Sir,
i found a solution around the issue i had.
thank you for your support.
will get back when i run into more doubts.

**Comment by ugrdursun** [comment]
> Sir,
> i found a solution around the issue i had.
> thank you for your support.
> will get back when i run into more doubts.

How did you solve this ?

**Comment by digitlninja** [comment]
@ugrdursun that doesn't solve it for me?

I get `NSURLErrorDomain`.
how can I use an ip (of my pc) as the source? It loads on safari on my iphone, just need it to load in the app. @AnirudhSharmap7

**Comment by ugrdursun** [comment]
> @ugrdursun that doesn't solve it for me?
> 
> I get `NSURLErrorDomain`.
> how can I use an ip (of my pc) as the source? It loads on safari on my iphone, just need it to load in the app. @AnirudhSharmap7

Same happened to me, after adding http:// prefix it started working. Maybe you should restart development server of RN
