### ISSUE TITLE
Android crash：When I return to the normal page from a page with Webview

### ISSUE THREAD

**Issue by ceressteven** [react-native-community/react-native-webview#1338]
When I return to the normal page from a page with Webview,app got crash!
Environmental：
"react-native": "0.62.2",
"@react-navigation/stack": "^5.0.0",
"react-native-webview": "^8.1.2",

code:
<View style={{ flex: 1, backgroundColor: config.theme.backgroundColor }}>
{/* header */}
  <components.Angle />
  <View style={{ flex: 1, backgroundColor: config.theme.backgroundColor }}>
    <components.CustomWebView
      handleMessage={handleMessage}
      uri={url}
    />
  </View>
</View>

**Comment by kesha-antonov** [comment]
Fix here https://github.com/react-native-community/react-native-webview/pull/1298

**Comment by Neck1T** [comment]
"react-native": "^0.62.2",
"@react-navigation/native": "^5.1.6",
 "@react-navigation/stack": "^5.2.11",
"react-native-screens": "^2.5.0",
"react-native-webview": "^9.2.2"

Crash is still here if using
import { enableScreens } from 'react-native-screens';
enableScreens();

if not using this - it's ok

https://reactnavigation.org/docs/react-native-screens/

**Comment by Keplyx** [comment]
Can confirm this is happening on recent android versions with [react-native-screens](https://reactnavigation.org/docs/react-native-screens/) support enabled. Could reproduce on android 9+, but had no issue on android 7.

Disabling react-native-screens fixes the issue.

Using:
"react-native": "~0.61.5",
"react-native-webview": "^9.4.0",
"@react-navigation/native": "^5.2.2",
"@react-navigation/stack": "^5.2.17",
"react-native-screens": "^2.7.0",

**Comment by NappyPirate** [comment]
Confirmed as well on android 9+, disabling react-native-screens fixes the issue.

Using:
"react-native": "~0.61.4",
"react-native-webview": "^9.4.0",
"@react-navigation/native": "^5.1.3",
"@react-navigation/stack": "^5.2.6",
"react-native-screens": "^2.7.0"
