### ISSUE TITLE
Android: incognito vs. localStorage

### ISSUE THREAD

**Issue by okwast** [react-native-community/react-native-webview#1339]
Hello there,

thanks for taking your time 🙂

I have a question regarding the incognito prop.
We are using the WebView to access our Web project.
Our Web stores data in the localStorage.
I now want the WebView to have a fresh localStorage when opening the settings.
However setting `incognito` to `true` does not seem to help on Android as the localStorage still contains data.
On iOS it seems to be empty every time.

My code looks like this:
```
  <WebView
      style={{flex: 1}}
      source={{ uri: 'https://okwast.github.io/react-native-webview-localstorage-issue-showcase/' }}
      incognito={true}
    />
```

Is there a way to also have a fresh localStorage on Android, am I doing something wrong or is this a bug in the WebView for Android?

**To Reproduce:**
I created a demo project that can be found here: https://github.com/okwast/react-native-webview-localstorage-issue-showcase

It contains a RN project and a github pages website checking the localStorage.
The website can be accessed here: https://okwast.github.io/react-native-webview-localstorage-issue-showcase/

It shows a message whether the localStorage was emtpy or not.
When initially loading the App it should say the localStorage is emtpy.
When reloading the App it should stay like that.
On Android however it realizes there is content in the localStorage and tells you there is something.

**Environment:**
 - OS: Android
 - OS version: 9
 - react-native version: 0.61.5 / 0.62.2
 - react-native-webview version: 8.2.1 (newer versions don't compile for me)

**Comment by alexanderstrom** [comment]
Experience the same issue

**Comment by alexanderstrom** [comment]
@okwast There is a domStorageEnabled prop just for android. Fixed it for me.
https://github.com/react-native-community/react-native-webview/blob/master/docs/Reference.md#domstorageenabled

**Comment by okwast** [comment]
@alexanderstrom thanks for the hint, that looks great 👍 

I would love to try it now, sadly Corona hit us quite hard, so I don't know when/if I will be able to check on this :(

**Comment by guiled** [comment]
Hello, I am reopening this issue because the main purpose was : by using the incognito mode, the previous localStorage is still available and not cleared even if it should NOT be.
The solution based on setting `domStorageEnabled` at `false` does not fit the need as it disable the localStorage totally and then make webpages fails (because `localStorage`global object is null).
The final need is : incognito does not provide a clean `localStorage`
