### ISSUE TITLE
Webview stop working with gray screen

### ISSUE THREAD

**Issue by ashanjayasundara** [react-native-community/react-native-webview#1341]
**Bug description:**
[LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSAutoresizingMaskLayoutConstraint:0x6000034eb930 h=--& v=--& _UIToolbarContentView:0x7fe052d27f70.height == 0   (active)>",
    "<NSLayoutConstraint:0x6000034e22b0 V:|-(0)-[_UIButtonBarStackView:0x7fe052d25cd0]   (active, names: '|':_UIToolbarContentView:0x7fe052d27f70 )>",
    "<NSLayoutConstraint:0x6000034e2300 _UIButtonBarStackView:0x7fe052d25cd0.bottom == _UIToolbarContentView:0x7fe052d27f70.bottom   (active)>",
    "<NSLayoutConstraint:0x6000034f77a0 UIImageView:0x7fe055048830.centerY == _UIModernBarButton:0x7fe055048240.centerY   (active)>",
    "<NSLayoutConstraint:0x600003487f20 'IB_Baseline_Baseline' _UIModernBarButton:0x7fe055048240.lastBaseline == UILayoutGuide:0x600002eb07e0'UIViewLayoutMarginsGuide'.bottom   (active)>",
    "<NSLayoutConstraint:0x600003487f70 'IB_Top_Top' V:|-(>=0)-[_UIModernBarButton:0x7fe055048240]   (active, names: '|':_UIButtonBarButton:0x7fe055047c10 )>",
    "<NSLayoutConstraint:0x60000348aad0 'UIButtonBar.maximumAlignmentSize' _UIButtonBarButton:0x7fe055047c10.height == UILayoutGuide:0x600002ebbc60'UIViewLayoutMarginsGuide'.height   (active)>",
    "<NSLayoutConstraint:0x600003487070 'UIView-bottomMargin-guide-constraint' V:[UILayoutGuide:0x600002ebbc60'UIViewLayoutMarginsGuide']-(0)-|   (active, names: '|':_UIButtonBarStackView:0x7fe052d25cd0 )>",
    "<NSLayoutConstraint:0x600003487e80 'UIView-bottomMargin-guide-constraint' V:[UILayoutGuide:0x600002eb07e0'UIViewLayoutMarginsGuide']-(11)-|   (active, names: '|':_UIButtonBarButton:0x7fe055047c10 )>",
    "<NSLayoutConstraint:0x6000034e2170 'UIView-topMargin-guide-constraint' V:|-(0)-[UILayoutGuide:0x600002ebbc60'UIViewLayoutMarginsGuide']   (active, names: '|':_UIButtonBarStackView:0x7fe052d25cd0 )>"
)

Will attempt to recover by breaking constraint 

**Screenshots/Videos:**
![Screen Shot 2020-04-23 at 7 11 19 PM](https://user-images.githubusercontent.com/16848987/80105427-3a6c8300-8596-11ea-8ee3-705be54c07b1.png)

**Environment:**
 - OS: macOS
 - OS version: 10.15.4
 - react-native version: 0.62.2
 - react-native-webview version: 9.2.2

**Comment by hfarhanahmed** [comment]
I am facing the same warning and web view is not properly using callbacks. url is shown perfectly but I need the callbacks to get the data and to check if the response is success
