### ISSUE TITLE
Android - files are always downloaded? 

### ISSUE THREAD

**Issue by cristianoccazinsp** [react-native-community/react-native-webview#1342]
**Is your feature request related to a problem? If so, Please describe.**

Can we do something about files always getting downloaded on Android? Does the webview support file preview (e.g., for PDF files?). This creates a huge inconsistency with iOS which will plain and simple just render the PDF within the webview.

Apologies if there's a feature for this already, but I can't seem to find it anywhere.

**Describe the solutions you came up with**

Add a flag or white list of file extensions that shouldn't be downloaded.

**Comment by bunsha** [comment]
Android Webview cannot display PDF files. There is an issue related to this problem. You can view it from [this link][1]

There are multiple solutions to your problem, you can pick the most relevant one for yourself. 

1) Use [react-native-pdf-view][2] 

2) Use Google Docs as a viewer. Try to load this URL in your Webview `http://docs.google.com/gview?embedded=true&url=http://www.africau.edu/images/default/sample.pdf`

3) [Use Chrome Custom Tabs][3]. 


  [1]: https://github.com/facebook/react-native/issues/6488
  [2]: https://github.com/cnjon/react-native-pdf-view
  [3]: https://github.com/facebook/react-native/issues/6488#issuecomment-352557454

**Comment by cristianoccazinsp** [comment]
The docs embed viewer is actually quite bad and works half of the time.

The other two options are a nice alternative, I guess, but if you're going to modify your webpage so it works nicely with the app, why not just do a postMessage and have the app call the native Linking.open ? Doesn't that open chrome on Android?

**Comment by bunsha** [comment]
U can, but not all phones will parse pdf. For some reasons, on some phones pdf are parsed in a browser and on some of them not. Have no idea why.

**Comment by cdunkel** [comment]
@bunsha, do you know if react-native-pdf-view is still being maintained, or if there is now a better solution out there? Looking at their repo it looks like their last commit was in May 2018.
