### ISSUE TITLE
Task :app:mergeDexDebug FAILED

### ISSUE THREAD

**Issue by jeancarlos2020** [react-native-community/react-native-webview#1344]
Problems using react-native-camera

The plugin works correctly as long as no other plugin is installed I thought it was react-navigation
or Redux,
I had to install one by one until the plugin
react-native-camera
I throw the error
Task: app: mergeDexDebug FAILED
![image](https://user-images.githubusercontent.com/6289980/80181054-b8964d00-85c9-11ea-8fbb-750cd1786642.png)

**Comment by jeancarlos2020** [comment]
1) limpiar el gradle
cd android && gradlew clean
2) npm install --save react-native-webview
3) react-native install react-native-webview
=====tendra que el link dar success caso contrario verificar estos cambios=====
1) en el archivo android/settings.gradle
    rootProject.name = 'UELDVNews' despues de esto pegar
    include ':react-native-webview'
    project(':react-native-webview').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-webview/android')
2) en el archivo android/src/main/java/mainApplication.java
    import com.facebook.react.ReactApplication; despues de esto pegar
    import com.reactnativecommunity.webview.RNCWebViewPackage;
====Solucion para el error Task :app:mergeDexDebug FAILED=====
1) en el archivo android/app/build.gradle
    defaultConfig {
        multiDexEnabled true
    }
para ios
1) en el archivo ios/PodFile agregar
  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

**Comment by Rafay3198** [comment]
### At Path **android/app/build.gradle**

defaultConfig {
multiDexEnabled true
}

**Comment by thanhtungcmd** [comment]
@Rafay3198 Thank you, this working

**Comment by gersonbarbosa7** [comment]
> ### At Path **android/app/build.gradle**
> defaultConfig {
> `multiDexEnabled true` //Add this line
> }

This works for me. Thank so much @Rafay3198

**Comment by gostavee** [comment]
> ### At Path **android/app/build.gradle**
> defaultConfig {
> `multiDexEnabled true` //Add this line
> }

this should be added to the quick start guide, it took me long enough to find this solution, thanks @Rafay3198

**Comment by maxhaponenko** [comment]
> ### At Path **android/app/build.gradle**
> defaultConfig {
> `multiDexEnabled true` //Add this line
> }

Thank you! It helped!

**Comment by sergeydevhub** [comment]
> ### At Path **android/app/build.gradle**
> defaultConfig {
> `multiDexEnabled true` //Add this line
> }

Thanks man, it works!

**Comment by mirzahayat** [comment]
when i install react-native-html-to-pdf i got this error > Task :app:mergeDexDebug FAILED but i have already put it defaultConfig {
multiDexEnabled true //Add this line
} and also clean the gradlew. 

any one help me how to solve it.

**Comment by ahmad6242** [comment]
I also have this already.
multiDexEnabled true

It is still throwing this issue. anybody resolved it ?

**Comment by frank10gm** [comment]
I have this problem too, after upgrading from 0.62.2 to 0.63.2

**Comment by malharbhutto** [comment]
Try with add `implementation 'androidx.multidex:multidex:2.0.1'` in your `anroid/app/build.gradle` and if your already have this `implementation 'com.android.support:multidex:2.0.1'` replace it with upper one.

**Comment by AdSoNaTuRaL** [comment]
> ### At Path **android/app/build.gradle**
> defaultConfig {
> `multiDexEnabled true` //Add this line
> }

Works!!!

**Comment by christianjerry** [comment]
> 
> ### At Path **android/app/build.gradle**
> 
> defaultConfig {
> `multiDexEnabled true` //Add this line
> }

this should be added to the package documentation. working perfectly

**Comment by aljhunlegaspi** [comment]
> ### At Path **android/app/build.gradle**
> defaultConfig {
> `multiDexEnabled true` //Add this line
> }

worked for me, thank you!, saved me a lot of time figuring this out, kudos

**Comment by MSH786** [comment]
> `multiDexEnabled true` //Add this line

Thanks Man!

**Comment by adcastiblanco** [comment]
> ### At Path **android/app/build.gradle**
> defaultConfig {
> `multiDexEnabled true` //Add this line
> }

Thaaaaaaaaaaaaaanks!!!

**Comment by quirozcarlos** [comment]
> ### At Path **android/app/build.gradle**
> defaultConfig {
> `multiDexEnabled true` //Add this line
> }

Works!! thank you so much ❤️

**Comment by RaviKiranMakala** [comment]
> if you have already added `multiDexEnabled true` and still facing issue then
> Try with add `implementation 'androidx.multidex:multidex:2.0.1'` in your `anroid/app/build.gradle` and if your already have this `implementation 'com.android.support:multidex:2.0.1'` replace it with `implementation 'androidx.multidex:multidex:2.0.1'`.

I already had `multiDexEnabled true` and  `implementation 'androidx.multidex:multidex:2.0.1'` and replaced it with `implementation 'com.android.support:multidex:2.0.1'`. Still same issue.
I am using `react-native 0.61.5`

**Comment by RaviKiranMakala** [comment]
> > if you have already added `multiDexEnabled true` and still facing issue then
> > Try with add `implementation 'androidx.multidex:multidex:2.0.1'` in your `anroid/app/build.gradle` and if your already have this `implementation 'com.android.support:multidex:2.0.1'` replace it with `implementation 'androidx.multidex:multidex:2.0.1'`.
> 
> I already had `multiDexEnabled true` and `implementation 'androidx.multidex:multidex:2.0.1'` and replaced it with `implementation 'com.android.support:multidex:2.0.1'`. Still same issue.
> I am using `react-native 0.61.5`. Any help will be appreciated.


I added this lines in MainApplication.java, Now its Working 
`import androidx.multidex.MultiDexApplication;`

`public class MainApplication extends Application implements ReactApplication {` is replaced with 
`public class MainApplication extends MultiDexApplication implements ReactApplication {`

**Comment by swushi** [comment]
Already had `multiDexEnabled true` in the `build.gradle` Fix for me was:


`cd android && ./gradlew clean && cd ..`
`npm start -- --reset-cache`
`npm run android`

**Comment by ishanz22** [comment]
> if you have already added `multiDexEnabled true` and still facing issue then Try with add `implementation 'androidx.multidex:multidex:2.0.1'` in your `anroid/app/build.gradle` and if your already have this `implementation 'com.android.support:multidex:2.0.1'` replace it with `implementation 'androidx.multidex:multidex:2.0.1'`.

Works!! thank you so much ❤️

**Comment by theRealSheng** [comment]
This worked for me.

Add the below line in android/app/gradle.properties

`org.gradle.jvmargs=--add-opens java.base/java.io=ALL-UNNAMED.`

**Comment by crosskpixel** [comment]
@Rafay3198  how this guy find that solution, thanks very much, in my linux enviroment works fine without that, but now i use mac and that save me. thks.

**Comment by vjha125** [comment]
> import androidx.multidex.MultiDexApplication

where i have to add this

**Comment by jamesjames1122** [comment]
> ### At Path **android/app/build.gradle**
> 
> 
> 
> defaultConfig {
> 
> `multiDexEnabled true`                       //Add this line
> 
> }

@gdevalbertkin

**Comment by izuutech** [comment]
For me, what i did was to set the `multiDexEnabled true` then in my android level build.gradle i set
` androidXAnnotation = "1.2.0"
        androidXBrowser = "1.3.0"
kotlinVersion = "1.8.0" ` in the ext 
In the dependencies of the same file,  I added ` classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:${kotlinVersion}"` and it worked
