### ISSUE TITLE
On Android, cookie are not the same after killing and relaunching the app

### ISSUE THREAD

**Issue by mmorier** [react-native-community/react-native-webview#1345]
**Bug description:**
If you remove a cookie in the web view and then kill the application in the recent application list on Android. When you launch again the application, the cookie is still here.
He does the same if you set a cookie and kill the app few seconds after, the cookie will not be here.
It seems ok on iOS.

**To Reproduce:**
I created [this simple application](https://github.com/mmorier/rn-webview-cookie-bug) to explain and reproduce easily the issue.

**Expected behavior:**
The cookies of the web view after the relaunch are the same than before killing the application.

**Environment:**
 - OS: Android
 - OS version: all I guess. I tested on Android 10 device and on a Android 8 emulator
 - react-native version: all I guess. I tested on 0.61.5 and 0.62.2
 - react-native-webview version: I tested on 9.0.1 and 9.2.2

**Comment by mmorier** [comment]
still searching for solutions

**Comment by jpodpro** [comment]
cookies on android have had this bug for at least a year and a half. see #631

**Comment by FreeWong** [comment]
same issue hrere.still unable to resolve. 2020-09-18

**Comment by jpodpro** [comment]
still an issue with 11.0.0
