### ISSUE TITLE
Iframe inside a local html is only loading child page in android

### ISSUE THREAD

**Issue by bsjaffer** [react-native-community/react-native-webview#1347]
We are trying to develop an offline feature in which we will be downloading bunch of HTML files and load in local. We are facing a strange issue in webview  local HTML if it has a iframe. 
**When its loaded only iframe content is getting loaded in webview.**

Can you please let me know what could be the issue here ? 

![Screenshot_20200427-152216](https://user-images.githubusercontent.com/1895191/80359196-1d3bfb00-889b-11ea-99d0-c07c400423e7.png)

WebView
`    <WebView
        source={{
          uri: "file:///data/user/0/com.example/files/parent.html"
        }}
        onError={error => {
          console.log('WebView onError - ', error);
        }}
        allowsFullscreenVideo
        bounces={false}
        renderError={() => {
          return null;
        }}
        allowFileAccess={true}
        allowFileAccessFromFileURLs={true}
        allowingReadAccessToURL={true}
        allowUniversalAccessFromFileURLs={true}
        onMessage={event => {
          console.log('WebView onMessage- ', event);
        }}
        mediaPlaybackRequiresUserAction={false}
        allowsInlineMediaPlayback={true}
        javaScriptEnabled={true}
        domStorageEnabled={true}
        startInLoadingState={true}
        originWhitelist={['*']}
        mixedContentMode={'always'}
        style={{ flex: 1 }}
      />`

Parent.html
![image](https://user-images.githubusercontent.com/1895191/80359541-989dac80-889b-11ea-85f3-eb0f970bc55b.png)

Child.html

![image](https://user-images.githubusercontent.com/1895191/80359566-9e938d80-889b-11ea-82ed-f27a5b4168a9.png)

**Comment by calm-rad** [comment]
Also having this issue. Hoping for a solution

**Comment by bsjaffer** [comment]
stil searching for solution

**Comment by sandro971** [comment]
same problem

**Comment by DoGoodMore** [comment]
Did you solve it now? I had the same problem; I loaded the html via a local bundled resource, which worked fine on IOS devices, but on Android devices some content didn't render properly, but when I started a http server, and all content can be rendered normally,
