### ISSUE TITLE
Invariant Violation: Webview had been removed

### ISSUE THREAD

**Issue by dogeri28** [react-native-community/react-native-webview#1349]
**Bug description:**
 
I get the Invariant Violation: WebView has been removed from React Native. It can now be installed and imported from 'react-native-webview' instead of 'react-native' see https... 
 

**To Reproduce:**
I am not using the webview component but just to be sure. I followed the steps of installing the  "react-native-webview": "^9.3.0", and also changed the import statements in the node_modules  ( i know that is crazy to do this because the node_modules are regeneratedm but just to rule out thats the issue) 
and then i changed the i**import { WebView } from 'react-native'** to i**mport { WebView } from 'react-native-webview'** please help me i have been on this for almost 2 days
 

**Expected behavior:**
 
I expected the issue to be resolved as i followed the steps highlighted in the link on the error message
 

**Screenshots/Videos:**
 
<img width="347" alt="Screenshot 2020-04-27 at 20 20 14" src="https://user-images.githubusercontent.com/4926986/80411683-86843400-88c4-11ea-99bc-ff03b99114af.png">
 

**Environment:**
 - OS: iOS
 - OS version: 
 - react-native version: 0.6
 - react-native-webview version: 9.3.0

**Comment by ceressteven** [comment]
maybe you haven't add useWebKit

**Comment by dogeri28** [comment]
Please where is this added? (useWebKit)

As seen from the package.json details originally. I had no reference to the WebView, but after experiencing the issue without it then I added this line   "react-native-webview": "^9.3.0", and still no hope. then changed the import statement to import {WebView} from ** "react-native-webview"** in the node_modules


{
  "name": "MyProject",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "postinstall": "sh ./utils/fix.sh && npx jetify",
    "start": "react-native-scripts start",
    "test": "jest",
    "eject": "react-native-scripts eject",
    "android": "react-native-scripts android",
    "ios": "react-native-scripts ios"
  },
  "devDependencies": {
    "babel-jest": "23.6.0",
    "eslint": "4.16.0",
    "eslint-config-airbnb": "16.1.0",
    "eslint-plugin-import": "2.8.0",
    "eslint-plugin-jsx-a11y": "6.0.3",
    "eslint-plugin-react": "7.5.1",
    "jest": "23.6.0",
    "jetifier": "1.6.3",
    "metro-react-native-babel-preset": "0.51.0",
    "react-native-scripts": "1.10.0"
  },
  "dependencies": {
    "@react-native-community/async-storage": "1.5.1",
    "@react-native-community/netinfo": "4.1.3",
    "async": "2.6.1",
    "axios": "0.18.0",
    "babel-eslint": "10.0.1",
    "babel-plugin-transform-react-jsx-source": "6.22.0",
    "deprecated-react-native-listview": "0.0.6",
    "downloadjs": "1.4.7",
    "fbemitter": "2.1.1",
    "i18n-iso-countries": "3.7.8",
    "immutable": "4.0.0-rc.12",
    "lodash.get": "4.4.2",
    "lodash.isempty": "4.4.0",
    "native-base": "^2.13.8",
    "prop-types": "15.6.2",
    "qrcode": "1.3.2",
    "qs": "6.5.2",
    "react": "16.9.0",
    "react-native": "0.61.2",
    "react-native-easy-grid": "0.2.1",
    "react-native-elements": "1.1.0",
    "react-native-fbsdk": "1.0.4",
    "react-native-firebase": "^5.5.6",
    "react-native-google-places": "^3.1.2",
    "react-native-image-crop-picker": "0.25.0",
    "react-native-image-picker": "1.0.1",
    "react-native-material-ui": "1.30.1",
    "react-native-message-bar": "2.0.10",
    "react-native-paypal": "git+https://github.com/smarkets/react-native-paypal.git",
    "react-native-permissions": "1.2.0",
    "react-native-qrcode": "^0.2.7",
    "react-native-router-flux": "4.0.1",
    "react-native-share": "1.2.1",
    "react-native-view-shot": "^3.0.2",
    "react-redux": "5.1.0",
    "react-test-renderer": "16.6.3",
    "react-timer-mixin": "0.13.4",
    "redux": "4.0.1",
    "redux-form": "7.4.2",
    "redux-immutable": "4.0.0",
    "redux-logger": "3.0.6",
    "redux-persist": "5.10.0",
    "redux-thunk": "2.3.0",
    "tipsi-stripe": "^7.5.1"
  },
  "jest": {
    "preset": "react-native"
  },
  "rnpm": {
    "assets": [
      "./src/assets/fonts"
    ]
  }
}

**Comment by dogeri28** [comment]
@ceressteven  thank you for reaching out. the issue was react-native-qrcode library. Had to remove the deprecated library and use react-native-qrcode-svg
