### ISSUE TITLE
NSURLSchemeHandler prop for handling custom url schemes

### ISSUE THREAD

**Issue by ccorcos** [react-native-community/react-native-webview#135]
Since UIWebview is now deprecated, an alternative to NSURLProtocol for WKWebview is to use NSURLSchemeHandler. This lets you override the behavior of the webview and serve your own files. It would be awesome if this component had an API to use this feature.

**Comment by siddhantbenadikar** [comment]
Would this fix opening of iPhoneURLScheme_Reference/MapLinks? For example, right now `http://maps.apple.com/?q=<query>` does not open in apple maps.

**Comment by ccorcos** [comment]
PR here: https://github.com/react-native-community/react-native-webview/pull/784
