### ISSUE TITLE
Crash on Android App

### ISSUE THREAD

**Issue by MuhammadMattiullah** [react-native-community/react-native-webview#1351]
**Bug description:**

Android App crashes when rendering videos on webview

**To Reproduce:**

Add video's link to web view
```

  const makeIframeHTML = () => {
    const head = '<style>body{margin:0}</style><meta name="viewport" content="width=device-width,">';
    return `<!DOCTYPE html><html><head>${head}</head><body>${data.html}</body></html>`;
  };

  <WebView
      containerStyle={
        {
          width,
          alignSelf: 'center',
          alignContent: 'center',
        }
      }
      source={{
        baseUrl: data.provider_url,
        html: makeIframeHTML(),
      }}
      allowsInlineMediaPlayback
      allowsFullscreenVideo
      mediaPlaybackRequiresUserAction={false}
      mixedContentMode='always'
      scalesPageToFit
      originWhitelist={['*']}
      startInLoadingState
      renderLoading={() =>  <Spinner variant={Spinner.VARIANTS.SMALL} /> }
/>
```

**Expected behavior:**

The application should render videos on webview without any crash

**Environment:**
 - OS: Android
 - OS version: any
 - react-native-webview: 9.3.0,
 - react-native: 0.61.5,

**Comment by lmarcosss** [comment]
I have the same problem with this, when I press the goBack button.

**Comment by msriaz** [comment]
@MuhammadMattiullah 

Webview on android is crashing when it is wrapped in other views
Adding opcity 0.99 fix this crash 
Feel free to check these references. 
https://github.com/react-native-community/react-native-webview/issues/811
https://www.gitmemory.com/issue/react-native-community/react-native-webview/430/493976111
