### ISSUE TITLE
No visible @interface for 'NSHTTPURLResponse' declares the selector 'valueForHTTPHeaderField:'

### ISSUE THREAD

**Issue by joeljerushan** [react-native-community/react-native-webview#1353]
**Bug description:**
`No visible @interface for 'NSHTTPURLResponse' declares the selector 'valueForHTTPHeaderField:'` issue while run `react-native run-ios` or in `xCode`

**To Reproduce:**
Once i remove `react-native-webview` app works without issues.

**Expected behavior:**
open dynamic link when button click.

**Screenshots/Videos:**

![image](https://user-images.githubusercontent.com/10111309/80649390-8b491380-8a8f-11ea-8d17-0b62a38ca207.png)

**Environment:**
 - OS: macOS
 - OS version: 10.13.6
 - react-native version: "0.62.2
 - react-native-webview version: "^9.4.0"

**Comment by nabilalilipaly** [comment]
i got this error too

**Comment by jtich** [comment]
I am too. Does anyone have a solve for this?

**Comment by kurnal** [comment]
can someone post a solution I am experience this issue as well!

**Comment by rahulson** [comment]
@joeljerushan @kurnal  @jtich @nabilalilipaly 
Please run your code in Xcode 11+ version as **valueForHTTPHeaderField** supports iOS 13.0 + sdk

FYI
https://developer.apple.com/documentation/foundation/nshttpurlresponse/3240613-valueforhttpheaderfield?language=objc

**Comment by tyhour** [comment]
Please install with this version: yarn add react-native-webview@8.0.0 for Xcode 10.3 everything will work find. I wish this solution will help you.

**Comment by rayWille** [comment]
@rahulson 
You saved my day thanks a lot. It is better to upgrade to latest version then downgrade.

**Comment by joeljerushan** [comment]
@tyhour your solution helped me to fix this issue i'm closing this issue thank you.

**Comment by Pines-Cheng** [comment]
react-native-webview@8.0.0  works fine.

**Comment by 1453alabanda** [comment]
"react-native-webview": "^7.5.1" works fine

**Comment by grit96** [comment]
Could backwards compatibility be added for those still using Xcode 10?

**Comment by sq-ricardo-pereira** [comment]
SOLUTION (for me), rsrsrsrsrs
#ifdef __IPHONE_13_0
        if (@available(iOS 13.0, *)) {
           ...
        }
#endif

**Comment by jeafgilbert** [comment]
My solution (Mine is Xcode 10.1)

1) yarn add react-native-webview@8.0.0
2) cd iOS
3) pod install
4) yarn ios

Hope this helps!

**Comment by KennedyKeinstein** [comment]
> Please install with this version: yarn add react-native-webview@8.0.0 for Xcode 10.3 everything will work find. I wish this solution will help you.

Thanks! @tyhour you saved me!
