### ISSUE TITLE
Post request is not working in IOs (<11).

### ISSUE THREAD

**Issue by sonnt612** [react-native-community/react-native-webview#1355]
**Bug description:**
I faced with some problems with post request on old IOS OS (IOS 9.4, 10.3.1). When I try to send body to api but i can't

**To Reproduce:**
<WebView
          javaScriptEnabled ={true}
          source={{
            uri: `${Define.constants.serverAddr}/api/v1.0/shipper/reward`,
            method: "POST",
            headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
            body: `memberToken=${_.get(user, 'memberInfo.member.memberToken', '')}&region=${_.get(appSetting, 'regionNew', '')}&mode=${_.get(appSetting, 'mode', '')}`
          }}
          style={{marginTop: Platform.OS === 'ios' ? 0 : StatusBar.currentHeight}}
          onLoadEnd={() => {
            this.setState({
              isLoadDone: true
            })
          }}
        />

**Expected behavior:**

**Screenshots/Videos:**

**Environment:**
 - OS: ios
 - OS version: 10.3.1
 - react-native version: 0.61.5
 - react-native-webview version: 9.4.0

**Comment by focux** [comment]
Were you able to fix this? @sonnt612

**Comment by sonnt612** [comment]
> Were you able to fix this?

I use version 6.11.1 and add useWebKit={false}

**Comment by zabojad** [comment]
I'm having this issue right now on `"react-native-webview": "^13.12.3"` and cannot workaround it with `useWebKit={false}`... Has anyone found a solution?
