### ISSUE TITLE
Not supported the <math xmlns="http://www.w3.org/1998/Math/MathML"> formate in android 

### ISSUE THREAD

**Issue by shubhamawesome** [react-native-community/react-native-webview#1357]
**Bug description:**
Hi
I'm trying to display the below html text but not supported in Android but in iOS it work fine for me

`"<p><math xmlns=\"http://www.w3.org/1998/Math/MathML\"><mn>6</mn><msqrt><mn>79</mn></msqrt><mo>&#160;</mo><mo>+</mo><msup><mn>88</mn><mn>87</mn></msup><mo>&#160;</mo><mo>=</mo><mo>?</mo></math></p>\r\n\r\n<p>Testing</p>\r\n"`

**Expected behavior:**
<img width="150" alt="Screenshot 2020-05-01 at 9 35 25 PM" src="https://user-images.githubusercontent.com/61386037/80820241-2955ee80-8bf4-11ea-9163-682ad8f5b79c.png">

**Screenshots/Videos:**

**Environment:**
 - OS:
 - OS version:
 - react-native version:
 - react-native-webview version:

**Comment by leonardorpr** [comment]
Hi, @shubhamawesome 
I'm having the same problem, did you find any solution?
