### ISSUE TITLE
How to make AR work in React Native 

### ISSUE THREAD

**Issue by nikhilrayaprolu** [react-native-community/react-native-webview#1359]
How to make https://xr-spinosaurus.glitch.me/ work in a React Native WebView Component?

    import React, { Component } from 'react';
    import { WebView } from 'react-native';
    
    export default class MyWeb extends Component {
      render() {
        return (
          <WebView
            source={{uri: 'https://xr-spinosaurus.glitch.me/'}}
            style={{marginTop: 20}}
          />
        );
      }
    }

Right now adding this to react-native only shows VR option but not AR option.

If you access the link directly you could see VR and AR options but I couldn't find the AR option when running in a Web View component inside React-Native
But the same AR option is available if I directly access the link on an ARCore supported Device.

How to make this code also show the AR option in React-Native?

**Comment by hank121314** [comment]
Which platform did you use? Android or IOS?

**Comment by nikhilrayaprolu** [comment]
@hank121314 It's Android 9

**Comment by hank121314** [comment]
OK! I'll look into it

**Comment by hank121314** [comment]
Have you already added the android camera permission?
```
<uses-permission android:name="android.permission.CAMERA" />
```

**Comment by nikhilrayaprolu** [comment]
Yes, I provided the permissions

**Comment by nikhilrayaprolu** [comment]
This requires https://www.chromestatus.com/feature/5450241148977152 
`WebXR AR Module` flag to be enabled in case of chrome browser, but how about in case of the react-native-webview?

I think since the webview uses the chrome's engine (Inferred from `developer options >> WebView Implementation`), so I assume it should work even in case of React Native WebView.

**Comment by StefanoMartella** [comment]
@nikhilrayaprolu Hi, have you found a solution? Thank you in advance

**Comment by digvijay173** [comment]
@nikhilrayaprolu Have you got the solution?

**Comment by alromh87** [comment]
Any news on this, im intereted too

**Comment by ambojialur** [comment]
Anyone found the solution for this?

**Comment by nicomanzato** [comment]
Has anyone found a solution?

**Comment by loganknecht** [comment]
Has anyone found a solution regarding this?

**Comment by stoXmod** [comment]
Still have this issue. Has anyone found a solution for this?
