### ISSUE TITLE
WKWebView webkit property become to undefined

### ISSUE THREAD

**Issue by musicode** [react-native-community/react-native-webview#136]
RN version: 0.57.4

RNW version: 2.5.0

iOS WKWebView

After init, window has `webkit`property.

![image](https://user-images.githubusercontent.com/2732303/48406069-8941a680-e76e-11e8-923a-e29111c2c0cd.png)

then I open an image picker(react-native-image-picker) to select an image, the `webkit` property is undefined.

![image](https://user-images.githubusercontent.com/2732303/48406109-a7a7a200-e76e-11e8-9fee-236b79c02024.png)

@jamonholmgren please help me, the bug is so terrible.

**Comment by musicode** [comment]
@Titozzz

**Comment by petlys** [comment]
I also experience the same issue after opening a browser tab and closing it again (https://github.com/naoufal/react-native-safari-view)

**Comment by Titozzz** [comment]
That is super weird.

**Comment by lunarraid** [comment]
I am running into this issue as well. The message passing works perfectly until I trigger a google sign in (which I believe may pop up a webview in its implementation). After that, there is no longer a `webkit` property on `window` in the WebView.

**Comment by Titozzz** [comment]
Does #143 help ?

**Comment by lunarraid** [comment]
Yes, that does seem to resolve the issue.

**Comment by Titozzz** [comment]
Alright I'll merge it now then.
