### ISSUE TITLE
Lost connection with RN from WebView

### ISSUE THREAD

**Issue by jgill-evolvan** [react-native-community/react-native-webview#1360]
**Bug description:**
On android - we are losing connection with RN and webview. At one point it is not sending event from webView to RN. The same issue was exist on older versions too but then I used `*` in post message to make it working.
ex. window.postMessage('hello', '*');
but in latest version we have replace postmessage with newer one and it is supporting one parameter only
ex. window.ReactNativeWebView.postMessage('hello');

Please gimme solution asap.

**To Reproduce:**
You can reproduce this bug easily. Steps:
1. Create WebView with local file
2. Create button into webview file - which will send event to RN
3. Once you got event from webView we will navigate RN page to another page.
4. Navigate to previous page again and try to click same webView button, it will not send event to RN now.
On iOS this is working very fine but on Android it stopped working. I have spent lots of time to debug this but this didn't work.

**Expected behavior:**
When we navigated to any page and come back to same page - event should remain work and send data from WebView to RN.

**Environment:**
 - OS: Android
 - OS version: Any version
 - react-native version: latest
 - react-native-webview version: latest

**Comment by jgill-evolvan** [comment]
I found one more thing, above issue exist only if we are using WebView on multiple pages and navigated to another page from home page (note: both page having webview) - now when I navigated back to home page, it stopped sending event to RN from webview.

Can anyone help me on this? 
Thanks in advance.

**Comment by chrisbobbe** [comment]
Are you passing the `onMessage` prop? See https://github.com/react-native-community/react-native-webview/issues/1311.
