### ISSUE TITLE
Missing entitlement?

### ISSUE THREAD

**Issue by Zyphxion** [react-native-community/react-native-webview#1362]
**Bug description:**

When attempting display a WebView component with an external uri, nothing appears and I get an error in the console saying: 

`SandBoxPreviewer[38616:68190872] [assertion] Error acquiring assertion: <NSError: 0x600003e0ca80; domain: RBSAssertionErrorDomain; code: 2; reason: "Client is missing required entitlement"> {
    userInfo = {
        RBSAssertionAttribute = <RBSLegacyAttribute: 0x7fb72360fe90; requestedReason: FinishTaskUnbounded; reason: FinishTaskUnbounded; flags: PreventTaskSuspend>;
    }
}`

This is while running in a simulator.  I have not tried it on a device as of yet.  As far as I'm aware, the entitlement is meant to be toggled under App Sandbox under "Signing & Capabilities," which seems to be hidden in my version of Xcode, but I manually edited my .entitlements file to include both App Sandbox and com.apple.security.network.client to be toggled to YES.  This didn't seem to solve it, however.  In the above snippet, SandBoxPreviewer is my project name, for clarity.

Also curiously, attempting to display the webview component with some inline raw html gives me an error saying:

`Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service`

I have made sure to include the WebKit.framework in my build phases.

**Environment:**
 - OS: iOS, Xcode
 - OS version: 13
 - react-native version: 0.60.0
 - react-native-webview version: 9.4.0

**Comment by Sterling-Smith** [comment]
Hey @Zyphxion! Any update here?? 

I’m experiencing a similar issue.

**Comment by claudiahub** [comment]
still searching for solutions ...

**Comment by majirosstefan** [comment]
this should not be closed...
