### ISSUE TITLE
JQuery doesn't get injected inside a React Native WebView

### ISSUE THREAD

**Issue by alishehzad2017** [react-native-community/react-native-webview#1365]
**Bug description:**

I'm trying to remove the header from a WebView using the **injectedJavaScript()** function.

If I write my function in **pure JavaScript**, it **executes**:

`document.getElementsByClassName('site-header')[0].innerHTML="";`

However, if I write my function in **JQuery**, it doesn't **execute**:

`$('.site-header').remove();`

If I execute the JQUERY directly on https://www.ourworldindata.org/grapher/prevalence-of-undernourishment, it does indeed work.

**To Reproduce:**

https://snack.expo.io/@alishehzad/jquery-not-executing-on-webview

**Expected behavior:**

The header should be removed. 

**Environment:**
 - Tested on: Android, Android Emulator, iOS Simulator
 - react-native version: 0.61
 - react-native-webview version: 8.1.1

**Note:** It was working fine just yesterday. No idea what happened today!

**Comment by JacobCooley** [comment]
This is happening to me as well
