### ISSUE TITLE
Camera and Microphone Blocked

### ISSUE THREAD

**Issue by AlejoOrtega** [react-native-community/react-native-webview#1369]
Hi, i am trying to access camera and microphone throught react-native-webview. 

I already managed to connected them in some websites but in others i get the following message: 

>" Camera and microphone are Blocked. Go to your browser settings "

![example](https://user-images.githubusercontent.com/43015395/81331211-dacaa900-9066-11ea-82bb-a2d8dd6ac087.jpeg)

How can i fix this?

PD: I use react-native-permission@2.1.4 

**Environment:**
 - OS: Android 
 - OS Version: 10
 - react-native version: 0.59.9
 - react-native-webview version: 9.4.0

**Comment by JanedoeGVA** [comment]
Same here, 
Is there still no solution ? Thanks in advance

**Comment by osikes** [comment]
Same issue here on iOS.

**Comment by amsimoes** [comment]
Same issue happening on iOs, using `getUserMedia` API.

Is this fixable anyway?

**Comment by osikes** [comment]
So.. a suggestion the best way to get around it is to not use the web view. Instead leverage the in-app browser on iOS 'SFSafariBrowseController' and the Android equivalent. There are even react native wrappers for it, I used this one https://github.com/proyecto26/react-native-inappbrowser , and camera access mic access work just fine.

**Comment by amsimoes** [comment]
@osikes hmm alright, is there a way to "embed" it in the app?

I'm basically wrapping a whole website in a WebView and on one page it has a barcode scanner which uses getUserMedia. For this use case I think it wouldn't be possible/good to open a new browser window to communicate with a webview... is it possible?

<WebView> --- capture onPress ---> open <InAppBrowser> (could be with a dedicated subpage for the scanner)

<WebView> <--- code scan result --- <InAppBrowser>

At this point, probably would be easier to communicate with a native barcode scanner...

**Comment by osikes** [comment]
@amsimoes it completely depends on what you're trying to accomplish. For me, I was trying to preserve functionality in an existing website, by letting the user on my app still go to that webpage without leaving app (which SFSafariBrowseController accomplishes). 

If you're just trying to get basic barcode scanning functionality, then it's probably easier to just implement one of many react native libraries for that vs using a web view to a site that then opens a barcode scanner.

**Comment by amsimoes** [comment]
@osikes Yeah in your case it makes sense to use the InAppBrowser alternative.

My case is a bit different, my website is a retail platform which happens to have a subpage which lets the user input a number by scanning a barcode.

The whole website is intended to be wrapped in a WebView.

I'll now probably have to detect if the user is on that specific subpage (by its path/url probably) and then show a button which triggers a native BarcodeScanner (Expo BarcodeScanner library for example).
It wouldn't make sense/good UX to open a InAppBrowser over the specific webpage opened in a WebView... 

Now I have to understand how to communicate with my WebView (which is a React web app I'm making) from the native Barcode Scanner.

**Comment by amsimoes** [comment]
Hey @mangowi, I've not tried it yet but I think the best way for this to work is to inject a couple of javascript functions from RN to the website.

A bit like this: [Webviews and social authentication with React Native](https://codeburst.io/webviews-and-social-authentication-with-react-native-cfecf96ac7d7)

In this example, it requires making some changes on the website source, but for the scanner use case I think it may not be needed:

One function to listen to the click on the website's button, to trigger the native scanner.
The other function, would detect the scanner result and insert on the website input textbox.

All this gathered by `getElementById` or similar.

Hope it helps! If I get it done I can leave some feedback here as well

**Comment by mangowi** [comment]
@amsimoes ,  thank you man. I’ll try this.
