### ISSUE TITLE
Support loading local files on WebKitWebView iOS

### ISSUE THREAD

**Issue by gisellezeitoune** [react-native-community/react-native-webview#137]
Current Behavior

When I leave `useWebKit={true}` and use as `source={uri: <path to local pdf file>}` the pdf is never loaded. I've set originWhitelist to `{['*']}` but as far as I can tell there's no support for local files for the new webview yet.

Expected Behavior

Load and show the pdf on the webview (even if it's a local file and not an url)

Please add support for these. It is working with UIWebView.

**Comment by CubeSugar** [comment]
Need this feature as well. And I'm working on it.

**Comment by membla** [comment]
Was a longstanding iOS bug but fixed for iOS8+, should definitively be implemented here too:

https://stackoverflow.com/a/45536907/432990

**Comment by kklkit** [comment]
Definitely could use this feature.

Similar implementation:
https://github.com/CRAlpha/react-native-wkwebview

`<WKWebView source={{ file: RNFS.MainBundlePath + '/data/index.html', allowingReadAccessToURL: RNFS.MainBundlePath }} />`

I think we could start from here if this interface looks good enough.

**Comment by scarlz** [comment]
It seems as though agreeing an interface from the RN side is all that would prevent a pull request here, given that this is quite easily supported through `loadFileURL` and `allowingReadAccessToURL` on the native side.

**Comment by priteshpoddar** [comment]
+1

**Comment by jamonholmgren** [comment]
That interface looks fine to me, @Gary-KK / @scarlz . I'd be happy to review a PR that implements it.

**Comment by ionut-movila** [comment]
We would also need this feature: trying to load in webview a local cached image using react-native-fetch-blob

**Comment by adbs1** [comment]
Not sure if this is helpful to others but as a quick solution we changed the following line in RNCWKWebView.m's visitSource method. It opens access to the whole directory where the source.uri html file resides. We can then cache files in that directory and access them from the WebView:

We changed this:
[_webView loadFileURL:request.URL allowingReadAccessToURL:request.URL URLByDeletingLastPathComponent];

to this:
[_webView loadFileURL:request.URL allowingReadAccessToURL:[request.URL URLByDeletingLastPathComponent]];

**Comment by JakeRawr** [comment]
@adbs1 

Would you mind showing how your code for your `<WebView ... />`?

I changed to your `[_webView loadFileURL:request.URL allowingReadAccessToURL:[request.URL URLByDeletingLastPathComponent]];` but it's still not working

I used react-native-fs to download all the assets to `Documents`, and then display html by 
```
<WebView
source={{ uri: <Path/to/html> }}
/>
```

**Comment by adbs1** [comment]
Below is an untested stripped down version of my working code. It achieves the same as:

```<WKWebView source={{ file: RNFS.MainBundlePath + '/data/index.html', allowingReadAccessToURL: RNFS.MainBundlePath }} />`

It would be much better to pass the allowingReadAccessToURL value through (as per line above) so we can specify a different directory for our downloads and keep our html in the main bundle. I have a deadline though so can't look into it just yet. 

```
class MyComponent extends Component {
	constructor(props) {
		super(props);
		if(Platform.OS === 'ios') {
			var promises = [
				'index.html',
				'some_dependency.png'
			].map(async fileName => {

				const destPath = RNFS.DocumentDirectoryPath + '/NoCloud/';

				if (await exists(destPath + fileName)) {
					return;
				}
				return moveFile(RNFS.MainBundlePath + '/' + fileName, destPath + fileName);
			});

			Promise.all(promises).then(() => {
				this.setState({filesReady: true});
			}).catch((e) => {
				console.error(e);
			});
		}
	}
	render() {
		return (
			<View>
				{this.state.filesReady ?
					<WebView
						originWhitelist={['*']}
						source={{
							uri: Platform.OS === 'ios' ?
								RNFS.DocumentDirectoryPath + '/NoCloud/index.html'
								: 
								'file:///android_asset/index.html'
							}}
						cacheEnabled={false}
						javaScriptEnabled={true}
						allowFileAccess={true}
						useWebkit={true}
					/>
				: null}
			</View>
		);
	}
}
`

**Comment by colorgmi** [comment]
> @adbs1
> 
> Would you mind showing how your code for your `<WebView ... />`?
> 
> I changed to your `[_webView loadFileURL:request.URL allowingReadAccessToURL:[request.URL URLByDeletingLastPathComponent]];` but it's still not working
> 
> I used react-native-fs to download all the assets to `Documents`, and then display html by
> 
> ```
> <WebView
> source={{ uri: <Path/to/html> }}
> />
> ```
           source ={{ uri:     `${RNFetchBlob.fs.dirs.DocumentDir}/xxx/index.html`  }}
It works.

**Comment by sbayd** [comment]
+1 For the problem, 

@adbs1 I think your commit has solved the problem for me, what about opening a PR?

**Comment by JakeRawr** [comment]
@sbayd @colorgmi @adbs1 

Are you guys able to load js files? Image loads for me, but not js files

**Comment by colorgmi** [comment]
> @sbayd @colorgmi @adbs1
> 
> Are you guys able to load js files? Image loads for me, but not js files

Maybe your project (web stuff) structure is special, not normal shape.
You have to adjust.

**Comment by hsource** [comment]
#771 should also resolve this. Feel free to patch it into a branch or to just `yarn add https://github.com/hsource/react-native-webview.git#add-allowingReadAccessToURL-built

**Comment by Manigandan-Azure** [comment]
Any updates guys?

**Comment by hsource** [comment]
You should be able to do this via the `allowingReadAccessToURL` prop for files served from the local filesystem. This issue should be closed.
