### ISSUE TITLE
Prevent WebView from handling deeplink and allow to override via onShouldStartLoadWithRequest

### ISSUE THREAD

**Issue by capezzbr** [react-native-community/react-native-webview#1370]
**Bug description:**

I am loading a url in `WebView` that at some point redirects to a custom deeplink that I want to intercept in my app. The deeplinks looks like `com.mytestapp://result?success` and upon interception I want to be able to open a success screen

The issue I am facing is that `onShouldStartLoadWithRequest` is never invoked when navigating to `com.mytestapp://result?success`. Furthermore since I have no app that can handle the `com.mytestapp` scheme, a YellowBox warning is logged: `Can't open url: com.mytestapp://result?success`

**Expected behavior:**

I am expecting to be able to use `onShouldStartLoadWithRequest` to hijack the redirect, or at least have a way to tell `WebView` that I want to handle a specific scheme.

**Environment:**
 - OS: Android
 - OS version: 10
 - react-native version: 9.4.0
 - react-native-webview version: 0.62.0

**Comment by capezzbr** [comment]
As I opened the issue, I dug into the codebase and realized I can add my custom scheme to `originWhitelist`. That did solve the issue. Hopefully this will be useful in the future to someone else 😄

**Comment by cham1985** [comment]
> As I opened the issue, I dug into the codebase and realized I can add my custom scheme to `originWhitelist`. That did solve the issue. Hopefully this will be useful in the future to someone else 😄

Thank you for your answer
