### ISSUE TITLE
RNCWebViewManager cannot be cast to ViewGroupManager

### ISSUE THREAD

**Issue by macrobber** [react-native-community/react-native-webview#1372]
I am using WebView for one of my pages. I’ve added the
WebView from ‘react-native-webview’. App loads fine; however, when I open a page that uses the new call, I get the following error:

`Abi37_0_0.host.exp.exponent.modules.api.components.webview.RNCWebViewManager cannot be cast to abi30_0_0.com.facebook.react.uimanager.ViewGroupManager`

I’ve also deleted node-modules, npm-installed, run react-native link, and expo start -c - updated cli, deleted and re-installed expo on my app. Same error shows each time.

**Comment by sofianegargouri** [comment]
Same error here

**Comment by macrobber** [comment]
I found that having a <Text> field inside the WebView no longer works - which is fine.  For me, I just discovered that removing all other elements inside the WebView clears the issue up.  Hope this helps.

**Comment by sofianegargouri** [comment]
Well done mate !
Seems like Webview can't have any children

**Comment by Sterling-Smith** [comment]
You guys every experience this issue: https://github.com/react-native-community/react-native-webview/issues/1362

**Comment by floresvfer** [comment]
> I found that having a field inside the WebView no longer works - which is fine. For me, I just discovered that removing all other elements inside the WebView clears the issue up. Hope this helps.

So helpful, in my case i was trying to put my loader indicator inside WebView. To handle the loading state and show loading components, use the renderLoading and startInLoadingState props instead.

**Comment by eamankwah250** [comment]
Is your webview inside a view component? I had a similar issue and solved it by placing the webview inside a View component rather than a SafeAreaView
