### ISSUE TITLE
Property 'applicationNameForUserAgent' does not exist

### ISSUE THREAD

**Issue by vascofg** [react-native-community/react-native-webview#1375]
**Bug description:**
There seems to be a missing type on the Typescript definitions. The prop applicationNameForUserAgent is not recognized as a valid prop.

**To Reproduce:**
Try to define the prop on a WebView component

**Expected behavior:**
No Typescript errors

**Environment:**
 - OS: iOS / Android
 - react-native version: 0.61.5
 - react-native-webview version: 9.4.0
-  typescript version: 3.8.3

**Comment by Wedin** [comment]
There was a PR with a proposed fix in #1132, which looks like a great start

**Comment by TheAlmightyBob** [comment]
This should have been fixed via https://github.com/react-native-community/react-native-webview/pull/1542

Sorry I forgot to reference this issue in the PR.
