### ISSUE TITLE
Images and fonts not display in release mode in iOS

### ISSUE THREAD

**Issue by senzNirojan** [react-native-community/react-native-webview#1377]
**Bug description:**
I have a local html file which display some images and custom fonts. Everything is perfectly working in debug mode of iOS and both debug and release mode of android. But images and fonts not display in release mode of iOS. I think local assets are missing in the release bundle. I don't know how to resolve this issue and where should we need to add local assets for iOS. 
Assets for android are correctly placed in app/src/main/assets but I don't know where should we placed the assets for iOS. Currently all assets for iOS is in a folder I have created for the project.

**To Reproduce:**
The code for load file:

```
<WebView
                            source={Platform.OS === 'ios' ? require('../../ios/WebUI/AddFarmLocal.html')  : {uri: "file:///android_asset/AddFarmLocal.html"}}
                            ref={r => (this.webref = r)}
                            javaScriptEnabled={true} //Enable Javascript support
                            domStorageEnabled={true}  //For the Cache
                            originWhitelist={["*"]}
/>
```

And my html file code sample:

> 

        <div onclick="deleteFarm();" style="width: 33.3%">
            <img style="margin-right:auto; margin-left:auto; display: block; width: 18px; height: 20px; background: 0% 0% no-repeat padding-box; opacity: 1;"
                 src="deleteBin.png">
            <span style="vertical-align:middle; color: #757575; font-family: 'Poppins-Regular','sans-serif';"> Delete</span>
        </div>

And my folder structure: 
    -android
    -iOS
    -src
          -assets
             -all html files and assets

**Expected behavior:**
Correctly load local assets in release mode also.

**Screenshots/Videos:**
folder structure : 
<img width="311" alt="Screenshot 2020-05-12 at 14 27 05" src="https://user-images.githubusercontent.com/37321132/81664457-1dbcc000-945d-11ea-9de0-199b87fdb869.png">

In debug mode : 
![Simulator Screen Shot - iPhone 8 Plus - 2020-05-12 at 14 42 04](https://user-images.githubusercontent.com/37321132/81666001-0f6fa380-945f-11ea-87cd-d4fe5d817d5c.png)

In release mode : 
![Simulator Screen Shot - iPhone X - 2020-05-12 at 14 42 00](https://user-images.githubusercontent.com/37321132/81666011-14345780-945f-11ea-9cc4-059ef45331ae.png)

**Environment:**
 - OS: iOS
 - OS version: 11.4 or higher
 - react-native version: 0.60.4
 - react-native-webview version: 8.0.4

**Comment by luojiong** [comment]
Hi, has this problem been solved? I'm in the same situation

**Comment by senzNirojan** [comment]
No, I haven't fixed this issue using the local html file. Instead what i have done is, uploaded the html files in server and load that file in my application. This will fix your issue and this will fix some other issues as well related to the assets which you are using in your maps.

**Comment by suwu150** [comment]
Hi, has this problem been solved? I'm in the same situation

@luojiong

**Comment by Prashanth-K-25** [comment]
@senzNirojan  Hi, find any solution ?

**Comment by Prashanth-K-25** [comment]
@suwu150 

find any solution ?

**Comment by nirojan-0930** [comment]
> [@senzNirojan](https://github.com/senzNirojan) Hi, find any solution ?

https://github.com/react-native-webview/react-native-webview/issues/1377#issuecomment-710990810
I didn't find any solution; instead, I did this as I mentioned here.
