### ISSUE TITLE
URL Open Issues with Firebase Dynamic links

### ISSUE THREAD

**Issue by arcslash** [react-native-community/react-native-webview#1381]
I am trying to use firebase dynamic links to direct users webview interactions to pages on the android App and it works well on web browser on emulator but throwsup the following error when website was loaded in webview and user selected the url with the dynamic link

`Can't open url: intent://ncelltest.page.link/getapp#Intent;package=com.google.android.gms;action=com.google.firebase.dynamiclinks.VIEW_DYNAMIC_LINK;scheme=https;S.browser_fallback_url=https://play.google.com/store/apps/details%3Fid%3Dcom.mventus.ncell.activity;end;`

**Comment by isharaux** [comment]
There is a solution, But more like a work around so it seems like webview blocking up requests with "intent://" head, as a solution "intent://" can be added to whitelist of the WebView. check the code below,

```
 <WebView      
      originWhitelist={['intent://']}
      source={{ uri: 'http://10.0.2.2:3000/' }}/>  
```
But the user experience might not be that great as this makes the URL to be opened from the web browser and web browser will the one doing the navigation to the page inside the app

**Comment by bhadreshg-nimblechapps** [comment]
I have added some code for temporary solution.
Open WebViewShared.js file
Add below code
```
const arrayUrl = url.split(';');
var getUrl;
if (arrayUrl.length > 0) {
    const index = arrayUrl.findIndex((url) => url.includes('browser_fallback_url'))
    getUrl = arrayUrl[index].split('=')[1];
    getUrl = decodeURIComponent(getUrl);
    if (getUrl) {
        url = getUrl
    }
}
```
In createOnShouldStartLoadWithRequest variable return function after this
```
var url = nativeEvent.url, lockIdentifier = nativeEvent.lockIdentifier;
```

**Comment by thekingrenz23** [comment]
Did you solved it? your workaround is not working for me

**Comment by bhadreshg-nimblechapps** [comment]
> Did you solved it? your workaround is not working for me
Please check this solution, This is working for me.
https://github.com/react-native-webview/react-native-webview/issues/1209#issuecomment-661748784

**Comment by bhadreshg-nimblechapps** [comment]
> Did you solved it? your workaround is not working for me

Please check this solution, This will work.
https://github.com/react-native-webview/react-native-webview/issues/1209#issuecomment-661748784

**Comment by thekingrenz23** [comment]
> > Did you solved it? your workaround is not working for me
> 
> Please check this solution, This will work.
> [#1209 (comment)](https://github.com/react-native-webview/react-native-webview/issues/1209#issuecomment-661748784)

this does not work. 

Please refer to my question here https://stackoverflow.com/questions/64345797/how-to-open-url-with-scheme-intent-on-react-native

very much appreciated your answer

**Comment by matinzd** [comment]
This issue is not solved. For testing purpose you can test this link: https://forms.gle/n4kYs6KLhoaULBUi6

**Comment by namti** [comment]
I used `react-native-send-intent` to handle `intent:` 

```javascript
import SendIntentAndroid from 'react-native-send-intent';
```

```javascript
<WebView 
  originWhitelist={ ['intent:'] }
  onShouldStartLoadWithRequest={ request => {
    if(request.url.startsWith('intent:')){
        SendItentAndroid.openChromeIntent(request.url)
          .then(wasOpened => {
            if(wasOpened) this.props.navigation.goBack();
          })
        return false;
    } 
    return true;
  } }
/>
```
