### ISSUE TITLE
Improve Android alert/prompt behaviour?

### ISSUE THREAD

**Issue by cristianoccazinsp** [react-native-community/react-native-webview#1385]
Looks like using `window.prompt` or `window.alert` ends up with extremely ugly alerts.  Example (local html):

![image](https://user-images.githubusercontent.com/48869228/81991335-661fdd80-9617-11ea-9ae2-809167b4713d.png)

Is it possible to improve this? Afer doing some research, seems like it can be improved by using the Chrome client, something like...
```
webView.setWebChromeClient(new WebChromeClient() {

    @Override
    public boolean onJsAlert(WebView view, String url, String message, final JsResult result) {
        AlertDialog dialog = new AlertDialog.Builder(view.getContext()).
                setTitle("YourAlertTitle").
                setMessage(message).
                setPositiveButton("OK", new DialogInterface.OnClickListener() {
                    @Override
                    public void onClick(DialogInterface dialog, int which) {
                        //do nothing
                    }
                }).create();
        dialog.show();
        result.confirm();
        return true;
    } });
```

Further looking at the code, this library is already using the chrome client, so perhaps it is straight forward to implement:

https://github.com/react-native-community/react-native-webview/blob/master/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java#L706

https://github.com/react-native-community/react-native-webview/blob/master/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java#L717

So it would be a matter of implementing:
![image](https://user-images.githubusercontent.com/48869228/81991585-feb65d80-9617-11ea-977c-13ef85305df3.png)

**Comment by cristianoccazinsp** [comment]
Still an issue. Native alerts/prompts are awful on Android.

**Comment by cristianoccazinsp** [comment]
Wow, 2 months already, time flies! Can we re-open this? This is definitely still an issue.  Alert/Prompts are all nicely implement on iOS, while they look terrible on Android!

**Comment by saravanandm** [comment]
Any solution for this?

**Comment by OmegaNix** [comment]
I would like to report that it's July 2021 and Alert.alert() on Android is still too ugly for any commercial application kthx

**Comment by Proman4713** [comment]
I'd like to say that it's still as ugly as ever
