### ISSUE TITLE
Inline HTML not working

### ISSUE THREAD

**Issue by gpugems** [react-native-community/react-native-webview#1388]
**Bug description:**

Nothing rendered

**To Reproduce:**

import React, {Component} from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { WebView } from 'react-native-webview';

class App extends Component{`

    state = {
      commonHtml :
          "    <p  style=\"color:red\"> page content </p>\n" +
          "    <p  style=\"color:red\"> page content </p>\n" +
          "    <p  style=\"color:red\"> page content </p>\n" +
          "    <p  style=\"color:red\"> page content </p>\n" +
          "    <p  style=\"color:red\"> page content </p>\n" +
          "    <p  style=\"color:red\"> page content </p>\n" +
          "    <p  style=\"color:red\"> page content </p>\n"

    }

  componentDidMount() {
  }

  render() {
    const {commonHtml} = this.state;
    return (
        <View  style={styles.container}>
            <WebView originWhitelist={['*']} source={{ html:  commonHtml}} />
        </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});

export default  App`
**Expected behavior:**

**Screenshots/Videos:**

**Nothing rendered**

**Environment:**
 - OS: iOS
 - OS version: 13.4.1
 - react-native version: "react-native": "~0.61.5",
 - react-native-webview version: "react-native-webview": "^9.4.0"

**Comment by anctsys** [comment]
Hi

I have the same error nothing display

Bruno
