### ISSUE TITLE
How do I open a webview for authentication

### ISSUE THREAD

**Issue by Shanks0465** [react-native-community/react-native-webview#1389]
Can someone suggest or tell me how to open a authentication page on webview and once i get the access token send it back to the app and return to the app? How to capture cookies or headers from a website in webview?

**Comment by TommyLeong** [comment]
You can use react native cookie lib to and get all cookies out. From there loop the list and look for your cookie name.

**Comment by safaiyeh** [comment]
@Shanks0465 I wrote an article here on how to authenticate using WebView. Closing this issue, but let me know if you have any questions.

**Comment by dancomanlive** [comment]
@safaiyeh What is the link to the article you wrote?

**Comment by safaiyeh** [comment]
@dancomanlive https://dev.to/safaiyeh/react-native-authentication-with-webview-1nh

**Comment by gorvinsky** [comment]
> @dancomanlive https://dev.to/safaiyeh/react-native-authentication-with-webview-1nh

I've seen that article but I don't get what to do after the native side has gotten the cookie info? How do I make every request from then on to include the cookie header?
