### ISSUE TITLE
Error in Generating Release apk  (Debug apk generate successfully)

### ISSUE THREAD

**Issue by ashishgunjal** [react-native-community/react-native-webview#1390]
> Could not resolve all artifacts for configuration ':app:stageRuntimeClasspath'.
   > Could not resolve project :react-native-webview.
     Required by:
         project :app
      > Cannot choose between the following variants of project :react-native-webview:
          - debugAndroidTestCompile
          - debugAndroidTestRuntime
          - debugRuntime
          - debugUnitTestCompile
          - debugUnitTestRuntime
          - releaseRuntime
          - releaseUnitTestCompile
          - releaseUnitTestRuntime
        All of them match the consumer attributes:
          - Variant 'debugAndroidTestCompile' capability android:react-native-webview1:unspecified:
              - Unmatched attributes:
                  - Required com.android.build.api.attributes.BuildTypeAttr 'stage' but no value provided.
                  - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' but no value provided.
                  - Required org.gradle.usage 'java-runtime' but no value provided.
                  - Found org.jetbrains.kotlin.localToProject 'local to :react-native-webview' but wasn't required.
                  - Found org.jetbrains.kotlin.platform.type 'androidJvm' but wasn't required.
          - Variant 'debugAndroidTestRuntime' capability android:react-native-webview:unspecified:
              - Unmatched attributes:
                  - Required com.android.build.api.attributes.BuildTypeAttr 'stage' but no value provided.
                  - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' but no value provided.
                  - Required org.gradle.usage 'java-runtime' but no value provided.
                  - Found org.jetbrains.kotlin.localToProject 'local to :react-native-webview' but wasn't required.
                  - Found org.jetbrains.kotlin.platform.type 'androidJvm' but wasn't required.
          - Variant 'debugRuntime' capability android:react-native-webview:unspecified:
              - Unmatched attributes:
                  - Required com.android.build.api.attributes.BuildTypeAttr 'stage' but no value provided.
                  - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' but no value provided.
                  - Required org.gradle.usage 'java-runtime' but no value provided.
                  - Found org.jetbrains.kotlin.localToProject 'local to :react-native-webview' but wasn't required.
                  - Found org.jetbrains.kotlin.platform.type 'androidJvm' but wasn't required.
          - Variant 'debugUnitTestCompile' capability android:react-native-webview1:unspecified:
              - Unmatched attributes:
                  - Required com.android.build.api.attributes.BuildTypeAttr 'stage' but no value provided.
                  - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' but no value provided.
                  - Required org.gradle.usage 'java-runtime' but no value provided.
                  - Found org.jetbrains.kotlin.localToProject 'local to :react-native-webview' but wasn't required.
                  - Found org.jetbrains.kotlin.platform.type 'androidJvm' but wasn't required.
          - Variant 'debugUnitTestRuntime' capability android:react-native-webview:unspecified:
              - Unmatched attributes:
                  - Required com.android.build.api.attributes.BuildTypeAttr 'stage' but no value provided.
                  - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' but no value provided.
                  - Required org.gradle.usage 'java-runtime' but no value provided.
                  - Found org.jetbrains.kotlin.localToProject 'local to :react-native-webview' but wasn't required.
                  - Found org.jetbrains.kotlin.platform.type 'androidJvm' but wasn't required.
          - Variant 'releaseRuntime' capability android:react-native-webview:unspecified:
              - Unmatched attributes:
                  - Required com.android.build.api.attributes.BuildTypeAttr 'stage' but no value provided.
                  - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' but no value provided.
                  - Required org.gradle.usage 'java-runtime' but no value provided.
                  - Found org.jetbrains.kotlin.localToProject 'local to :react-native-webview' but wasn't required.
                  - Found org.jetbrains.kotlin.platform.type 'androidJvm' but wasn't required.
          - Variant 'releaseUnitTestCompile' capability android:react-native-webview:unspecified:
              - Unmatched attributes:
                  - Required com.android.build.api.attributes.BuildTypeAttr 'stage' but no value provided.
                  - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' but no value provided.
                  - Required org.gradle.usage 'java-runtime' but no value provided.
                  - Found org.jetbrains.kotlin.localToProject 'local to :react-native-webview' but wasn't required.
                  - Found org.jetbrains.kotlin.platform.type 'androidJvm' but wasn't required.
          - Variant 'releaseUnitTestRuntime' capability android:react-native-webview:unspecified:
              - Unmatched attributes:
                  - Required com.android.build.api.attributes.BuildTypeAttr 'stage' but no value provided.
                  - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' but no value provided.
                  - Required org.gradle.usage 'java-runtime' but no value provided.
                  - Found org.jetbrains.kotlin.localToProject 'local to :react-native-webview' but wasn't required.
                  - Found org.jetbrains.kotlin.platform.type 'androidJvm' but wasn't required.

 - react-native version:0.61.5
 - react-native-webview version: 8.0.0

**Comment by MahmoudShaeer** [comment]
+1
