### ISSUE TITLE
Webview Reload itself on image upload

### ISSUE THREAD

**Issue by waheedakhtar694** [react-native-community/react-native-webview#1391]
I am trying to upload an image from `react-native-webview`  version `9.4.0` on `IOS` but getting a wired issue with the IOS version `13.4.1`, every time when I take a picture from camera and tries to upload, webview gets reloaded, it's similar kind of issue #72  but it wasn't with the versions before `13.3.1` of ios.

**To Reproduce:**
Use the ios device with the version of 13.4.1 and tries to upload image from camera

**Expected behavior:**
The image should upload without any issue.

**Environment:**
 - OS: IOS
 - OS version: 13.4.1
 - react-native version: 0.61.2
 - react-native-webview version:9.4.0

**Comment by JamboProduction** [comment]
Me too but on Android. I am still facing this issue with react-native-webview version `11.6.6` on `Android 11` and react-native version `0.63.4` I am using. Any solution of this?

**Comment by ewindso** [comment]
Hm, any update? :)

**Comment by HimanshuRedDotApps** [comment]
any update?
