### ISSUE TITLE
Error: 'xxxxxx.js' cannot be loaded as its extension is not registered in assetExts

### ISSUE THREAD

**Issue by ChenRaul** [react-native-community/react-native-webview#1394]
Hello, everyone, now I have a problem, as described in the title, after I upgrade react-native to version 0.62, this problem occurred, the js file imported by local HTML files,and the webview loaded  html ,it worked android but no ios,you have this problem again?How did you solve it? Thanks,

**Environment:**
 - OS:IOS
 - react-native version:0.62.2
 - react-native-webview version:8.0.0

**Comment by ChenRaul** [comment]
Finally, I found the specific problem, which was probably that react-native-webview could not find js, CSS and other resource files imported outside of HTML as webview did before.I used the following url reference method successfully displayed, I hope it is useful for you!https://www.wddsss.com/main/displayArticle/297

**Comment by figureai** [comment]
I get this problem, how can I fix it ?

**Comment by ChenRaul** [comment]
> I get this problem, how can I fix it ?

look up

**Comment by fukemy** [comment]
im facing same issues, but i dont want to get network js + css file, how can i solve this?

**Comment by Girish-GAP** [comment]
I am still experiencing an issue. Do you have any solutions for a local JS file?
