### ISSUE TITLE
ReactNative WebView content height calculation working fine on iOS but on Android it gives more height than the actual content

### ISSUE THREAD

**Issue by sreekanth-14** [react-native-community/react-native-webview#1395]
I am using web view to load my rich text editor html content in react native. The problem is I need to render multiple webviews one after the other vertically. And webview need a explicit height to load content. So, after searching for some time I found https://medium.com/@fxwio/set-webview-height-to-the-height-of-html-content-react-native-2d696128c181 and it helped me to identify height based on content. The content height on iOS is working fine. But on Android if the actual content height is "296" it calculates as "2785". Please help me out of this.

**Environment:**
 - OS: Android
 - OS version: Pie
 - Expo SDK 37
 - react-native-webview version: 9.2.1

**Comment by buffge** [comment]
the same problem

**Comment by pssgo** [comment]
`<meta name="viewport" content="width=device-width">`

**Comment by lkwjohn** [comment]
> <meta name="viewport" content="width=device-width">

What do we do with this?

**Comment by lkwjohn** [comment]
> <meta name="viewport" content="width=device-width">

Where should the meta tag be added to the WebView?

**Comment by jsamr** [comment]
@sreekanth-14 @lkwjohn @buffge Might want to try this: https://formidable-webview.github.io/webshell/docs/autoheight/
