### ISSUE TITLE
Can't run-ios after adding WebView

### ISSUE THREAD

**Issue by kenobi91** [react-native-community/react-native-webview#1399]
**Bug description:**

Build fails after running npm run ios. If i remove package all works fine.

Error from console:

CompileC /Users/myUser/Library/Developer/Xcode/DerivedData/myProject-bgwkvkmywaoqbabwzvwzdbojmeux/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-webview.build/Objects-normal/x86_64/RNCWebView.o /Users/myUser/Projects/ProjectFolder/projectFolder/node_modules/react-native-webview/apple/RNCWebView.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

**To Reproduce:**

Added react.native-webview
cd ios/
pod install

tried re-run got error.
I already did search issues and solutions there like runing reactnative run-ios two time, restarting with clear cache, changing build system but none worked.

**Expected behavior:**

**Screenshots/Videos:**

**Environment:**
 - OS: iOS
 - OS version:
 - react-native version: 0.62.2
 - react-native-webview version: 9.4.0

**Comment by MaafiHanene** [comment]
I had the same issue. I downgrade to 9.1.2 and it works fine on IOS but does not on Android (I used the version 8.0.0 so that it works)

**Comment by jptwl** [comment]
i had the same issue.

**Comment by jptwl** [comment]
i try to upgrade xcode to 11.5 and it's works for me 

> **Bug description:**
> 
> Build fails after running npm run ios. If i remove package all works fine.
> 
> Error from console:
> 
> CompileC /Users/myUser/Library/Developer/Xcode/DerivedData/myProject-bgwkvkmywaoqbabwzvwzdbojmeux/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-webview.build/Objects-normal/x86_64/RNCWebView.o /Users/myUser/Projects/ProjectFolder/projectFolder/node_modules/react-native-webview/apple/RNCWebView.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
> (1 failure)
> 
> **To Reproduce:**
> 
> Added react.native-webview
> cd ios/
> pod install
> 
> tried re-run got error.
> I already did search issues and solutions there like runing reactnative run-ios two time, restarting with clear cache, changing build system but none worked.
> 
> **Expected behavior:**
> 
> **Screenshots/Videos:**
> 
> **Environment:**
> 
> * OS: iOS
> * OS version:
> * react-native version: 0.62.2
> * react-native-webview version: 9.4.0

i try to upgrade xcode to 11.5, and it's works for me

**Comment by designervoid** [comment]
same issue

**Comment by duc9a1234** [comment]
same issue... How to fix it?

**Comment by l0ne** [comment]
same issue

**Comment by vuhpquang** [comment]
same issue

**Comment by vuhpquang** [comment]
Please reopen this issue, I still cannot fix it

**Comment by henrykuzmick** [comment]
same issue...

**Comment by Csierram96** [comment]
same issue here

**Comment by NilsBaumgartner1994** [comment]
Same issue here:

```** BUILD FAILED **


The following build commands failed:
	CompileC /Users/nbaumgartner/Library/Developer/Xcode/DerivedData/KitchenSinkappnativebase-bpfbrtbdeasuupdzifzjdofwpxsd/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-webview.build/Objects-normal/x86_64/RNCWebView.o /Users/nbaumgartner/Documents/GitHub/KitchenBase/app/node_modules/react-native-webview/apple/RNCWebView.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)```

**Comment by kkureli** [comment]
I had the same problem when installed previous version problem was solved. npm install --save react-native-webview@11.2.3

**Comment by danidelgadoz** [comment]
Same issue

**Comment by pwaweru** [comment]
Installing the latest version of `react-native-webview` worked for me (` yarn add react-native-webview@latest`)

**Comment by hrithikgautham** [comment]
same issue. Im using react native 0.70.4
