### ISSUE TITLE
Itms-90809: deprecated API usage appears again in IOS upload build version

### ISSUE THREAD

**Issue by qqakashi** [react-native-community/react-native-webview#1411]
**Bug description:**

**To Reproduce:**

**Expected behavior:**

**Screenshots/Videos:**

**Environment:**
 - OS:mac os 
 - OS version:10.15.4
 - react-native version:0.62.2
 - react-native-webview version:9.0.2
   I'm not sure if it's WebView, because I didn't find uiwebview

**Comment by jamonholmgren** [comment]
Shouldn’t be WebView. Try this:

```
cd node_modules
grep -rl "UIWebView" .
```

**Comment by junnug** [comment]
same issue produce today kindly give me any solution.
@jamonholmgren
this example not working

https://github.com/react-native-webview/react-native-webview/issues/1411#issuecomment-647648650.
