### ISSUE TITLE
[ANDROID] react-native-webview:compileDebugJavaWithJavac BUILD ERROR on 10.2.1

### ISSUE THREAD

**Issue by panda0603** [react-native-community/react-native-webview#1415]
**Bug description:**
Hello, 
just upgraded to 10.2.1 from 9.4. 

I am getting following two errors when building android. 

```
.../node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java:1239: error: method setWebChromeClient(WebChromeClient) is already defined in class RNCWebView
    public void setWebChromeClient(WebChromeClient client) {
                ^


.../node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewModule.java:276: error: cannot find symbol
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
                                                    ^
  symbol:   variable Q
  location: class VERSION_CODES
```

I have done ./gradlew clean and reset npm cache, but same result. 

**Environment:**
 - OS: MacOS
 - OS version: 10.15.5
 - react-native version: 0.61.5
 - react-native-webview version: 10.2.1

**Comment by kesha-antonov** [comment]
https://github.com/react-native-community/react-native-webview/pull/1298

**Comment by Onlyward** [comment]
Same issue.

**Comment by yolinsoft** [comment]
I have the same problem

**Comment by RicardoBrito1938** [comment]
same issue here

**Comment by kbrandwijk** [comment]
The beauty of pushing stuff out of the core... 😑

**Comment by mikehardy** [comment]
@kbrandwijk I'm sure the project could use help fixing the CI that's not catching the android build breaks more than snarky comments. D o you have a PR to offer? Sincerely would help

**Comment by Jncls** [comment]
Same issue here using version 10.2.3:

`node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewModule.java:276: error: cannot find symbol
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
                                                    ^
  symbol:   variable Q
  location: class VERSION_CODES`

**Comment by mikehardy** [comment]
@Jncls you must change your project to at least compile SDK target 29, usually it's in the `ext` block of `android/build.gradle`

it brings in the new symbols but *crucially* will not alter how the platform or Google view your app for review or execution purposes so it is not a major change (as opposed to changing your *target* SDK - that needs careful consideration)

This was a breaking change for library consumers and was regrettably not marked as such, sorry for the trouble

**Comment by kbrandwijk** [comment]
@mikehardy It wasn't meant as a snarky comment, but as a sincere concern. As part of the Lean Core initiative, more and more features that are not considered 'core' functionality are being pushed out to community packages. The project I'm working on uses at least 4 of those by now, which are critical to our app, and used to be part of the core, and we've honestly seen a dramatic increase in issues with newly released versions of those community packages across the board. Semver violations, poor testing, regression issues.
And no, right now I do not have the time to submit a PR, I'm sorry.

**Comment by mikehardy** [comment]
> And no, right now I do not have the time to submit a PR, I'm sorry.

And so it goes

**Comment by Biditmangal** [comment]
I am still facing the same issue as mentioned in the title and not being able to find any solution.

I tried changing the SDK version but no help. Tried this on a new app but no help there either. Please let me know how to proceed further.
```
* What went wrong:
Execution failed for task ':react-native-webview:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

```
Versions:
OS: Windows
"react-native": "0.62.2",
"react-native-webview": "^10.2.3"

**Comment by catmans1** [comment]
My solution is change compile SDK target 29 in path `android/build.gradle`
```
ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        **compileSdkVersion = 29**
        **targetSdkVersion = 29**
    }
```

**Comment by Biditmangal** [comment]
> My solution is change compile SDK target 29 in path `android/build.gradle`
> ```
> ext {
>         buildToolsVersion = "28.0.3"
>         minSdkVersion = 16
>         compileSdkVersion = 29 // change from 28 -> 29
>         targetSdkVersion = 29 // change from 28 -> 29
>     }
> ```


Thanks for the help. Yes that is the issue with the 10.2.0 version and up and they dont seem to fix them.

**Comment by Biditmangal** [comment]
> @Biditmangal this is a closed issue, I would open a new issue with full details
> 
> Note that when you see something that says "see the compiler error output for details", you should probably post the details so someone has a chance to help. Without them, no help

Okay.

**Comment by kysung95** [comment]
> My solution is change compile SDK target 29 in path `android/build.gradle`
> 
> ```
> ext {
>         buildToolsVersion = "28.0.3"
>         minSdkVersion = 16
>         compileSdkVersion = 29 // change from 28 -> 29
>         targetSdkVersion = 29 // change from 28 -> 29
>     }
> ```

I love you

**Comment by tux1489** [comment]
> I am still facing the same issue as mentioned in the title and not being able to find any solution.
> 
> I tried changing the SDK version but no help. Tried this on a new app but no help there either. Please let me know how to proceed further.
> 
> ```
> * What went wrong:
> Execution failed for task ':react-native-webview:compileDebugJavaWithJavac'.
> > Compilation failed; see the compiler error output for details.
> ```
> 
> Versions:
> OS: Windows
> "react-native": "0.62.2",
> "react-native-webview": "^10.2.3"

try to do cd android && ./gradlew clean and run again works for me

**Comment by antonkalik** [comment]
> > I am still facing the same issue as mentioned in the title and not being able to find any solution.
> > I tried changing the SDK version but no help. Tried this on a new app but no help there either. Please let me know how to proceed further.
> > ```
> > * What went wrong:
> > Execution failed for task ':react-native-webview:compileDebugJavaWithJavac'.
> > > Compilation failed; see the compiler error output for details.
> > ```
> > 
> > 
> > Versions:
> > OS: Windows
> > "react-native": "0.62.2",
> > "react-native-webview": "^10.2.3"
> 
> try to do cd android && ./gradlew clean and run again works for me

cleaned gradlew and still facing same issue.

**Comment by mikehardy** [comment]
@antonkalik 
If you've done this


        compileSdkVersion = 29 // change from 28 -> 29
        targetSdkVersion = 29 // change from 28 -> 29

and it still doesn't work, even after making sure you have a clean build environment, then your project has some specific issue that defies everything I know about Java, Android SDKs, and gradle 🤷
