### ISSUE TITLE
Build.VERSION_CODES.Q not exist and setWebChromeClient write twice

### ISSUE THREAD

**Issue by tiankun** [react-native-community/react-native-webview#1416]
RNCWebViewModule：Build.VERSION_CODES.Q not exist

RNCWebViewManager：setWebChromeClient @Override  write twice

**Comment by smaris** [comment]
For the first issue I changed my build.gradle file (to compile with SDK 29):
```
    googlePlayServicesVersion = "17.0.0"
    buildToolsVersion = "28.0.3"
    minSdkVersion = 24
    compileSdkVersion = 29
    targetSdkVersion = 28
    supportLibVersion = "28.0.3"
```

**Comment by tapz** [comment]
I don't understand why this was published to NPM if it does not even compile.

**Comment by M1ke** [comment]
I encountered this, was hard to find what caused it. Downgrading to 10.1.0 fixed it.

**Comment by tapz** [comment]
This has nothing to do with RN version. The Q thing can be fixed by changing the sdk version, but two different setWebChromeClient functions is probably a merge error. After merge just published to NPM without testing.

**Comment by zachariahtimothy** [comment]
OK I must have a different issue for RN 0.62 or something because Android will not build with 10.1.0. Thanks @tapz !

**Comment by mikehardy** [comment]
If anyone could propose a PR that adds a github action that does an android build that would be HUGE :pray: :pray:  - we are the community. We need to help, and that's clearly what is needed here. Please?

I just merged the fix for the build break, it should release shortly I think, based on semver release bot (unsure, first merge here)

The build codes Q is just a project issue - you need to update. react-native template moved to target 29 so I believe it's time - should be in the breaking changes notes and have been a major version bump but it wasn't, more people watching PRs here and commenting could help that I think

This should be closed on master though and released soon, so I'm closing

**Comment by jamonholmgren** [comment]
I'll be more careful to build PRs before merging. Our philosophy in the past has been that if it breaks, we'll just roll it back, and that lets us have a much faster velocity (it's suuuuuper slow to test every PR manually). But the community WebView is a more important part of our ecosystem than ever before now that it's been removed from the main React Native package, so I'll modify my process to include building it on my machine. I may get some time to work on the CI later.

**Comment by scottmas** [comment]
Just installed the latest and I don't get `setWebChromeClient write twice` but I still do get the error that the symbol `Build.VERSION_CODES.Q` cannot be found.  What's the fix for that?

**Comment by mikehardy** [comment]
Also worth noting the default new-app template from react-native is compile *and* target 29 now. If the module got ahead of core that might be odd (but still likely okay) but even core is at these versions now, and for compile specifically (which does not impact how your app is treated by the platform during execution) it's a no-change. Just brings in fresh APIs

**Comment by scottmas** [comment]
It looks like that compile target change won't be landing as the default until RN 63 comes out:

https://react-native-community.github.io/upgrade-helper/?from=0.62.1&to=0.63.0-rc.1

You can see that part of this upgrade includes bumping the `compileSdkVersion`. 

My project is fine now that I've bumped that to 29, but it may be worth considering staying in sync with the bulk of the RN ecosystem which it looks like (for now) has a `compileSdkVersion` of 28. 🤷‍♂️ 

Would it be that hard to strip out the code that depends on version 29? It may be worth doing from an ease of installation perspective until a majority of the RN community is there. For instance, our project is still on RN 60 and it's likely going to be a while before we bump up.

**Comment by mikehardy** [comment]
I hear you - but I don't think it has utility to lag for compileSdkVersion, it really has no impact, though I would certainly hear an argument for targetSdkVersion.

Aside, 0.63 will be released any day (maybe today?) so it's not a far-future thing regardless.

Someone has to go first, webview moves at speed of web technologies similar to react-native so can pioneer a bit, unlike my other modules (device info) which move at device platform speed so would never pioneer. If any module's going to do it it's probably this one. So, worth considering, but I'd argue to push ahead on compileSdkVersion personally based on no-risk, possible-reward assessment.

To be clear, should have been a semver break with this exact line of reasoning laid out though. "Requires update to compileSdkVersion 29, please note this adds new symbols to your build but does not impact how Android devices or Play Store review view your app in anyway, as opposed to targetSdk changes"

**Comment by abbasmoosavi** [comment]
In android build.gradle ext tag to 
```java
buildToolsVersion = "29.0.0"
        minSdkVersion = 16
        compileSdkVersion = 29
        targetSdkVersion = 29
        supportLibVersion = "29.0.0"
```
it worked for me!
