### ISSUE TITLE
[ANDROID] 10.2.1 implicitly requires compileSdkVersion 29

### ISSUE THREAD

**Issue by fend25** [react-native-community/react-native-webview#1418]
**Bug description:**
Android config-related bug:
Version 10.2.1 doesn't compile with compileSdkVersion 28 or lower in root project.

Reason: In the PR #1384 there was added [new check](https://github.com/react-native-community/react-native-webview/blob/master/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewModule.java#L276) for android version Q. That's ok, necessary business logic. 

Android SDK of versions 28 and lower has no static field `Q` in static class `Build.VERSION_CODES`, which causes build error. This field is required for the PR. Author knew about it and set compileSdkVerion in the [gradle.properties](https://github.com/react-native-community/react-native-webview/blob/master/android/gradle.properties#L2) file to 29. 
But current [compileSdkVersion picking algorithm](https://github.com/react-native-community/react-native-webview/blob/master/android/build.gradle#L31) prefers root project's gradle settings. So, in webview's gradle gets lower compileSdkVersion on most current RN projects.

**Possible solution**
Change build.gradle's compileSdkVersion to gradle.properties' one, if it is secure.
Maybe @Karthz could propose some better solution.

**To Reproduce:**
Create RN app, set compileSdkVersion to 28, install react-native-webview (10.2.1), run `react-native run-android`

**Environment:**
 - OS: MacOS
 - OS version: 10.15
 - react-native version: 0.61.5
 - react-native-webview version: 10.2.1

**Comment by mikehardy** [comment]
This should be "fixed" with a simple PR to the changelog I think that marks it as a breaking change that the semver release bot picks up as a breaking change and an accompanying release note. The change is fine and react-native template itself is at 29 now, it just should have been marked breaking 

https://github.com/semantic-release/semantic-release

indicates a PR / commit that starts 'BREAKING CHANGE: ' will do the trick

PR happily accepted I am sure, the policy here is "breaking change is fine, will just be semver major"

**Comment by mikehardy** [comment]
@fend25 you're the reporter and the changes should be easy (docs PRs are handled nicely by a web-based workflow in github) - if you post up a PR I can scan it and merge+release I think

**Comment by jamonholmgren** [comment]
Yeah, this should have been marked breaking -- that's my bad. Apologies!
