### ISSUE TITLE
[Android] react-native-webview:compileDebugJavaWithJavac 10.2.2

### ISSUE THREAD

**Issue by puera** [react-native-community/react-native-webview#1419]
**Bug description:**
I am getting one error when build android

`cannot find symbol
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
                                                    ^
  symbol:   variable Q
  location: class VERSION_CODES
`
i try clean with ./gradlew clean and a new project but a have the same result

**Environment:**
 - OS: Linux 5.3 
 - OS version: Ubuntu 18.04.4 LTS (Bionic Beaver)
 - react-native version: 0.62.2
 - react-native-webview version: 10.2.2

**Comment by NoumanSakhawat** [comment]
did you find the solution? @puera

**Comment by puera** [comment]
> did you find the solution? @puera

nope, i trying everything but no success

**Comment by Prashantrao331** [comment]
Facing the same error with latest version

**Comment by bbm-design** [comment]
Got the same issue

[app]/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewModule.java:276: error: cannot find symbol
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
                                                    ^
  symbol:   variable Q
  location: class VERSION_CODES
Note: [app]/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: [app]/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error

FAILURE: Build failed with an exception.

**Comment by hgySandy** [comment]
The same error to you.

**Comment by hgySandy** [comment]
The same error ...

**Comment by dushyantss** [comment]
This issue is related to #1418 

To fix it, you need to update your compileSdkVersion to 29. While you are at it, might as well update the buildToolsVersion. You can do that by changing these lines in your `/android/build.gradle` file.
```
...
buildscript {
    ext {
        ...
        buildToolsVersion = "29.0.3"
        compileSdkVersion = 29
        ...
    }
...
```

**Comment by iarmankhan** [comment]
Thanks @dushyantss 
The error is gone after the changes!

**Comment by bbm-design** [comment]
Tried that fix, only getting raw html when using it with charts native (iOS works fine)
https://github.com/somonus/react-native-echarts

**Comment by puera** [comment]
> This issue is related to #1418
> 
> To fix it, you need to update your compileSdkVersion to 29. While you are at it, might as well update the buildToolsVersion. You can do that by changing these lines in your `/android/build.gradle` file.
> 
> ```
> ...
> buildscript {
>     ext {
>         ...
>         buildToolsVersion = "29.0.3"
>         compileSdkVersion = 29
>         ...
>     }
> ...
> ```

@dushyantss thanks , the changes really works!

**Comment by gavrichards** [comment]
I'm experiencing this error too.

Changing the SDK version to 29 goes against the setup instructions for React Native which specify you should use Android SDK Platform 28 and build tools 28.0.3.

For that reason I'm reluctant to make these changes. Could this package be fixed to continue supporting 28? I'll downgrade this package in the meantime.

**Comment by ilyausorov** [comment]
Yes, looks like this is introduced with v10.2.0 and am also downgrading to v10.1.1 in the meantime.

**Comment by phillipmiles** [comment]
Yup, downgrading v10.1.1 fixes it. I don't want to update the SDK from what react native has by default either.

**Comment by xuan9230** [comment]
Don't forget to properly remove & unlink old version when downgrading.

**Comment by adifdwimaulana** [comment]
> This issue is related to #1418
> 
> To fix it, you need to update your compileSdkVersion to 29. While you are at it, might as well update the buildToolsVersion. You can do that by changing these lines in your `/android/build.gradle` file.
> 
> ```
> ...
> buildscript {
>     ext {
>         ...
>         buildToolsVersion = "29.0.3"
>         compileSdkVersion = 29
>         ...
>     }
> ...
> ```

This is work for me, thanks !!

**Comment by Jeevan-Kishore** [comment]
Downgraded to v10.1.1, minor versions breaking the build set us back from deployments. Wasn't a pleasant experience.

**Comment by zhouwenqi** [comment]
thanks

**Comment by gavrichards** [comment]
I've not been able to test yet, but it looks like this latest release might address this issue?
https://github.com/react-native-community/react-native-webview/releases/tag/v10.3.2
