### ISSUE TITLE
Is it possible to load a page once and then injectJavascript?

### ISSUE THREAD

**Issue by viperfx** [react-native-community/react-native-webview#142]
I would like to embed webview in other react components, but they are inside of a router.

There, its causing a page load. I would like to avoid a page load, and load a url once, and then use injectJavascript to interact with that page.

**Comment by jamonholmgren** [comment]
Hi @viperfx, I'm not aware of a way to do this offhand. If you do figure it out please do update this issue with your solution!

**Comment by Titozzz** [comment]
I'm doing that within my app, so yeah that is perfectly doable. What you will end up doing is exposing some function to the window and calling it using injectJavascript.

Look at how I implemented a simple bridge here: https://github.com/react-native-community/react-native-webview/issues/66#issuecomment-425753877
