### ISSUE TITLE
on Android in --variant=release stopLoading() not work

### ISSUE THREAD

**Issue by uganof** [react-native-community/react-native-webview#1422]
hello,

**Environment:**

 - OS: Android
 - OS version: 9
 - react-native version: 0.62.2
 - react-native-webview version: 10.2.3

**Bug description:**

when I use this:

  handleNavigationStateChange = (event) => {
    if (!event.url) return;
    if (event.url) {
        if (! event.url.includes(gA.base_url)) {
          **this.webView.stopLoading();  // -> generate error net::err_cleartext_not_permitted**
          Linking.openURL(event.url);
      }
    }
  };
 

in debug mode work perfectly, but in release mode generate:

Error Loading Page
Domain: undefined
Error Code: -1
Description: net::ERR_CLEARTEXT_NOT_PERMITED

in ios work perfectly in debug or release mode
does anyone have an idea why?

**Comment by Josnic** [comment]
Hi!
I got the same error, but this solution work for me #1259 
Regards!
