### ISSUE TITLE
WebView does not work when react app bundles are injected in HTML string

### ISSUE THREAD

**Issue by prakulgupta** [react-native-community/react-native-webview#1424]
**Bug description:**
WebView does't execute the web react app js bundles when injected inside the HTML string as script.

**To Reproduce:**
Below, the htmlTemplate is the HTML document replica of simple react web app, as shown in screenshot 1.
I was expecting the WebView will render this web react app inside the android mobile. But it only shows "Hello Web View!". Refer Screenshot 2.

```
import * as React from "react";
import { View } from "react-native";
import { WebView } from "react-native-webview";


export const ReactContainer: React.FunctionComponent<> = (
) => {

  const htmlTemplate = `
      <!DOCTYPE html>
      <html>
        <head>
          <meta charset="utf-8">
          <link rel="manifest" href="http://192.168.29.92:5000/manifest.json">
          <link rel="shortcut icon" href="http://192.168.29.92:5000/favicon.ico">
        </head>
        <body>
	<div>Hello Web View!</div>
        <div id="root"></div>          
          <script src="http://192.168.29.92:5000/static/js/bundle.js"></script>
          <script src="http://192.168.29.92:5000/static/js/0.chunk.js"></script>
          <script src="http://192.168.29.92:5000/static/js/main.chunk.js"></script>
        </body>
      </html>
    `;

  return (
    <View style={{ width: "100%", height: 500 }}>
      {/* HTML string approach */}
      <WebView
        source={{ html: htmlTemplate }}
        javaScriptEnabled={true}
        originWhitelist={["*"]}
      ></WebView>      
    </View>
  );
};

```

**Note:**
While executing this whole flow, this local endpoint 192.168.29.92:5000 was running and it provides all the required js files. Also I don't see any exception being thrown from WebView.

**Screenshots/Videos:**
Screenshot 1
![image](https://user-images.githubusercontent.com/6064632/83338941-aacd9900-a2e6-11ea-9cce-b2d46d64eaaa.png)
Screenshot 2
![image](https://user-images.githubusercontent.com/6064632/83338955-c173f000-a2e6-11ea-8e1f-cd55785d3868.png)

**Environment:**
 - OS: Android 
 - OS version: R
 - "react-native": "^0.60.5 || ^0.61.5",
 - "react-native-webview": "^8.0.4",

Is this something not supported by WebView?

**Comment by ErnestGrey** [comment]
Having the same issue, has there been any updates on this at all?

**Comment by Jinbe-im** [comment]
Having the same issue, is it solved?

**Comment by coyjiv** [comment]
Same issue, any updates?

**Comment by eisodev** [comment]
Did you find out the culprit for this? We got the same problem now all of a sudden with no other changed than the bundle itself.
