### ISSUE TITLE
White blank screen when load website in a webview

### ISSUE THREAD

**Issue by cemthecebi** [react-native-community/react-native-webview#1426]
**Bug description:** The site that I directed with Webview is opened in the ios simulator, Although not working in the andorid simulator.

**To Reproduce:**     
`react-native init AwesomeProject`
`cd AwesomeProject`
`react-native run-android`

`&& my code`

[code](https://gist.github.com/cemthecebi/9e42a5ff21b3c6e2fcd96134eb794c65)

**Expected behavior:**.  Work same as ios simulator

**Screenshots/Videos:**

![Screen Shot 2020-06-01 at 01 21 55](https://user-images.githubusercontent.com/24392062/83364035-d3b56300-a3a6-11ea-9dd8-24036dfef9d6.png)
![Screen Shot 2020-06-01 at 01 22 16](https://user-images.githubusercontent.com/24392062/83364037-d9ab4400-a3a6-11ea-81bc-1cda10f57469.png)

**Environment:**
 - OS: macOS 
 - OS version: 10.15.3
 - react-native version: 0.62.2 
 - react-native-webview version: 10.2.3

**Comment by a112121788** [comment]
If yout want yout webview support http
you can add 
`android:networkSecurityConfig="@xml/network_security_config"` to AndroidManifest.xml。

**app/src/main/res/network_security_config.xml**
```xml
<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <base-config cleartextTrafficPermitted="true" />
</network-security-config>
```

**Comment by cemthecebi** [comment]
> webview support http

Sorry for missing information. I changed it to https, still noting changed, site is working with https.

**Comment by mlammert** [comment]
I am having the same issue but on Windows with Android.

OS:  Windows 10 
OS version: 10.0.18363
react-native version: 0.62.2
react-native-webview version: 10.2.3

```
<WebView automaticallyAdjustContentInsets={false}
         domStorageEnabled={true}
         javaScriptEnabled={true}
         onNavigationStateChange={this.onNavigationStateChange.bind(this)}
         originWhitelist={['*']}
         ref={this.WEBVIEW_REF}
         source={{uri: 'https://www.***.com/'}}
         startInLoadingState={true}
         style={styles.webViewContainer} />
```

All works great in my various Android emulators.

API 22 - Android 5.1
API 28 - Android 9.0
API 29 - Android 10.0

```
npx react-native run-android

BUILD SUCCESSFUL
```

However, when I package a release APK and install it on my Android 5.1 phone, all I get is a white screen.

```
npx react-native bundle --dev false --platform android --entry-file index.js --bundle-output ./android/app/src/main/assets/index.android.bundle --assets-dest ./android/app/src/main/res

cd android

gradlew assembleRelease

BUILD SUCCESSFUL
```
Any ideas are greatly appreciated!

**Comment by cemthecebi** [comment]
Hi! there are several solutions that I found for myself. @mlammert 

add this [code](https://gist.github.com/cemthecebi/c2bf6ad64afa0f0816b386f1c3d88842) snippet to

`\node_modules\react-native webview\android\src\main\java\com\reactnativecommunity\webview\RNCWebViewManager.java`

After that  in `AndroidManifest.xml` add these code snippets.

`    <uses-permission android:name="android.permission.INTERNET" />` 

and in the <application> add this one `android:usesCleartextTraffic="true">`

**Comment by mlammert** [comment]
I am using HTTPS. So, I am not sure our two issues are exactly the same.

I have implemented @a112121788 advice and it has not fixed anything.

**Comment by subodha** [comment]
This can be a webview size issue. I had the same issue and fixed by adding width and height to webview

`<WebView
      startInLoadingState={true} 
      style = {{marginTop: 20, width: Dimensions.get('window').width, height: Dimensions.get('window').height}} 
      source={{ uri: 'https://google.com/'}}  />`

**Comment by lorenhicks** [comment]
> This can be a webview size issue. I had the same issue and fixed by adding width and height to webview
> 
> `<WebView startInLoadingState={true} style = {{marginTop: 20, width: Dimensions.get('window').width, height: Dimensions.get('window').height}} source={{ uri: 'https://google.com/'}} />`

this works!!!!!!!!!!!!!

**Comment by Mahmoud-git** [comment]
> This can be a webview size issue. I had the same issue and fixed by adding width and height to webview
> 
> `<WebView startInLoadingState={true} style = {{marginTop: 20, width: Dimensions.get('window').width, height: Dimensions.get('window').height}} source={{ uri: 'https://google.com/'}} />`

thaaanx man you save my day

**Comment by Rod2012** [comment]
> This can be a webview size issue. I had the same issue and fixed by adding width and height to webview
> 
> `<WebView startInLoadingState={true} style = {{marginTop: 20, width: Dimensions.get('window').width, height: Dimensions.get('window').height}} source={{ uri: 'https://google.com/'}} />`

Yes, you right!
But if the Dimensions.get('window').height is greater than 588 the screen turns white after loading the URL, so I had to set the prop androidLayerType to software. I had to read all documentation to get the result expected
This worked for me (on android device of course) :
`<WebView source={uri} scalesPageToFit={true} androidLayerType={'software'} style={{flex:0,height:700}} />`

**Comment by nehalahmed929** [comment]
i solved this issue by setting height and width to containerStyle
<WebView startInLoadingState={true} containerStyle = {{marginTop: 20, width: Dimensions.get('window').width, height: Dimensions.get('window').height}} source={{ uri: 'https://google.com/'}} />

**Comment by Chronostyle** [comment]
> This can be a webview size issue. I had the same issue and fixed by adding width and height to webview
> 
> `<WebView startInLoadingState={true} style = {{marginTop: 20, width: Dimensions.get('window').width, height: Dimensions.get('window').height}} source={{ uri: 'https://google.com/'}} />`

thx man you're saving my time

**Comment by ClementLevesque** [comment]
> scalesPageToFit

As @Rod2012 wrote I noticed that I had a white screen when the height of my view was above my window height (640 in my case). But instead of his solution I had to set the property `androidLayerType` to "none". And now it works :)

**Comment by fahadmunir123** [comment]
I check all the above Comments
You just need to check a simple process.
![image](https://user-images.githubusercontent.com/48602480/183286912-6d4bc2ca-b1ea-48dd-8257-871bac485ed2.png)

**Comment by fahadmunir123** [comment]
This will direct open your webview in my case it opens Google.com Please check

**Comment by gnusiva** [comment]
Hi all, 

I faced a similar issue. solved it by adding flex:1 to the safe area view
```
<SafeAreaView style={{flex:1}}>
    <WebView source={{ uri: 'https://google.com' }} />
 </SafeAreaView>
```

**Comment by fahadmunir123** [comment]
export default function App() {

  return (
        <>

        <WebView source={{ uri: "https://google.com"}}/>
        </>

  );
}
