### ISSUE TITLE
onMessage is not called when app in background on iOS

### ISSUE THREAD

**Issue by xcxooxl** [react-native-community/react-native-webview#1428]
**Bug description:**
When the app is in the background, onMessage is not called on iOS,
or more correctly it is called but only after app is back in the foreground, for me it's troublesome because I need to local push notifications based on some of the events I get from onMessage.

feels like there's a queue of events that is only being triggered when the app is in the foreground
to reproduce I did alert(new Date()); and waited a minute after the event happened, The date displayed was the moment I opened the app and not when the event was fired.

**To Reproduce:**
1. Post message to webview when app is in the background;

**Expected behavior:**
The events will trigger also when the app is in the background so the user can be aware of events happening inside the app.

EDIT: 
after debugging in iOS I can see that didReceiveScriptMessage is not being called when the app is in the background

**Environment:**
 - OS: iOS
 - OS version: 12.4.6
 - react-native version: 0.61.5
 - react-native-webview version: 10.2.3

**Comment by bfelbo** [comment]
@xcxooxl did you find a solution for this?

**Comment by AlexHappyCode** [comment]
I am having exactly the same issue described except that the app is not even being put in the background. When I inject javascript, the postmessage does not occur until the next injection happens, at which point, it does both very quickly, and it continually happens every 5 injections or so on the same webview.
