### ISSUE TITLE
onMessage not working on Android

### ISSUE THREAD

**Issue by flikQ** [react-native-community/react-native-webview#1429]
When using onMessage to gather events being sent in real time from the WebView the data is received with no issues on iOS but doesn't work on Android, in fact is prevents the webview from progressing (the webview is actually an animation with objects moving at 30FPS, with the data being fed to the view every second).

Android webview is still.

The webview should play the animation and feed the required data to the onMessage function so we can render out that data provided.

IOS: https://d.pr/v/gJLVjV (video)
ANDROID: https://d.pr/i/Jyjjbc (capture)

**Environment:**
 - OS: Android
 - OS version: Pie
 - react-native version: 0.61.5
 - react-native-webview version: 8.1.0

**Comment by ali27001** [comment]
I cannot capture the value I sent from the web on android. Ios is working
