### ISSUE TITLE
Redirects not working properly on Android

### ISSUE THREAD

**Issue by timboektoe** [react-native-community/react-native-webview#1434]
**Bug description:**
On Android redirects are not handled correctly within react-native-webview. Redirects are not taking place while they are working correctly in normal browser and react-native-webview on ios.

The problem appears when executing the following steps on android react-native-webview:

1. navigate to https://mijn.uwv.nl/
2. click the leftmost button labeled 'DigiD Inloggen'
3. on android webview you will return to the same page in other browsers you are forwarded to the login page. (see also the github link underneath to reproduce the issue)

If I study the redirection flow in my desktop browser I see also that 'SET-COOKIE' is part of the http responses. Could it be that something goes wrong while setting the cookie?

**To Reproduce:**
Checkout:
https://github.com/timboektoe/react-native-webview-redirect-bug

1. npm install
2. expo start
3. run on ios --> you will be redirected correctly to login page after clicking leftmost 'DigiD Inloggen' button.
4 run on android you will be redirected back to the same page after clicking leftmost 'DigiD Inloggen' button.

**Expected behavior:**
On Android will be redirected to the login page like in all other browsers

**Screenshots/Videos:**
https://parser-prod.aqopi.com/extension/redirect-bug.mp4

**Environment:**
 - OS: Android
 - OS version: all Android versions
 - react-native version: all React native versions
 - react-native-webview version: 8.0 (probably earlier also, but discovered on 8.0)

**Comment by alexhidalgo** [comment]
Curious why there aren't more eyeballs on this. Would be a really useful feature. I can confirm it works fine on iOS and fails on Android.

**Comment by Balasnest** [comment]
I am also facing the exact issue in the only android. It was working with webView API of react native.

**Comment by timboektoe** [comment]
> I am also facing the exact issue in the only android. It was working with webView API of react native.

Yes rumour was that this issue was fixed a while ago, but the redirect issue still exists in situations with multiple redirects. Do you experience this problem in a situation with multiple redirects particularly?

**Comment by Balasnest** [comment]
Yes. Multiple redirects are happening.

**Comment by nmilcoff** [comment]
Did anyone manage to get this working? I'm having this issue with multiple redirects as well. iOS works fine without any tricks

**Comment by timboektoe** [comment]
There's a copy of this issue here: https://github.com/react-native-webview/react-native-webview/issues/1654

I only managed to get it working with tricks...... We would like to pay somebody to help us fix this. How can I find the right person for that?
