### ISSUE TITLE
If I run on different versions of Android phone, I get different chrome version in userAgent?

### ISSUE THREAD

**Issue by LuHugo** [react-native-community/react-native-webview#1439]
I read the description in the readme that the library replaces the built-in webview, but it doesn't seem to replace the android built-in webview on different versions of Android phones, as I got a different version of chrome.
I'm a little confused, does the replacement of built-in webview refer to the react-native built-in webview component or to the Android built-in webview?

When I package the apk file, the apk that introduces the react-native-webview component is almost the same size as the apk file that doesn't introduce the react-native-webview component, so can I assume that the component doesn't contain the chrome kernel, but uses the android system's built-in webview?

**Comment by LuHugo** [comment]
I searched for other issues and found that react-native-webview is dependent on the Android has a built-in webview. so if the version of Android is lower and the user Without updating the Android webview, then react-native-weview would be Versions that are older, then there is no guarantee that the web page will render consistently on all devices.

### Is there a way to embed the chrome kernel in a react native project?

**Comment by kingofdevs** [comment]
Yeah, I consider this issue is so important and urgent!
Hi, RN team.
Please give us the best solutions!
@LuHugo Did you try to implement custom webview ?
http://reactnative.dev/docs/custom-webview-android

**Comment by LuHugo** [comment]
@kingofdevs  Thank you for the reply. I'm just a front-end developer with close to zero skills in native development, and I don't know OC or Swift languages at all, so I'm Don't think I'm up to it.

**Comment by kingofdevs** [comment]
Please try this one.
https://medium.com/lazy-engineering/creating-an-embedded-browser-with-react-native-aea42b54740

**Comment by LuHugo** [comment]
@kingofdevs Thanks for sharing, I read it and realized it's not really embedded in the chromium kernel but still depends on the Android version. I'd like to get a full embed on Android that doesn't depend on the Android version chromium kernel webview. no easy way to do this so far, just prompting the user to upgrade. version of Android webview, but this is very annoying.

**Comment by angelop11** [comment]
@LuHugo  Did you find any other solution?

**Comment by raulfr99** [comment]
Did someone find a solution for this? Im building a react native app with a webview screen, but i got some errors on the website beacuse the old version of the browser.

**Comment by LuHugo** [comment]
@angelop11 I didn't find an easy solution, we just stopped being compatible with lower versions of Android.
