### ISSUE TITLE
YouTube full screen landscape in Android does not fit the whole screen (erratic behaviour when rotating device)

### ISSUE THREAD

**Issue by irisS-irisS** [react-native-community/react-native-webview#1444]
**Bug description:**
When tapping the fullscreen icon, the portrait mode shows black background. When rotating device, the image in landscape mode wont fit fullscreen. The behaviour is erratic when rotating the device again in different directions.

**To Reproduce:**
Tap on fullscreen icon and rotate device.

**Expected behavior:**
Video image to fulfill the whole screen in landscape mode. 

**Screenshots/Videos:**

![fullscreenVideo](https://user-images.githubusercontent.com/53441310/84045068-bd973c00-a97e-11ea-8538-e7a742b51eea.gif)

![tabletfullScreenVideo](https://user-images.githubusercontent.com/53441310/84045428-25e61d80-a97f-11ea-98e1-3fb854f7b1d8.gif)

**Environment:**
 - OS: Android 
 - OS version: 8, 9, 10
 - react-native version: 0.62.2
 - react-native-webview version: 9.4.0

**Comment by gfels6** [comment]
+1 
Also happening on the following Environment:
react-native 59.10
react-native-webview 9.0.1

Works fine on iOS.

**Comment by gfels6** [comment]
Still doesn't found a solution to this...

**Comment by Marcoswrc2** [comment]
Yes, same problem here. When i enable the fullscreen mode and return to normal size, the video looks strange.

**Comment by ktjd123** [comment]
Same problem here.,,

**Comment by datvt99** [comment]
Same problem.
