### ISSUE TITLE
Semver violation for peer dependency changes

### ISSUE THREAD

**Issue by elashpear** [react-native-community/react-native-webview#1445]
**Bug description:**
[Peer dependencies are generally considered part of a package's public API](https://github.com/semver/semver/issues/502). When a change is made (such as https://github.com/react-native-community/react-native-webview/commit/228f10d9176098dd75a5e44739c55b3200727ec4#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R32 ) that removes previously valid peerdep versions from the accepted range, it should be handled as a breaking change and trigger a major version bump. 

This will make it easier to track down versions that introduced a peerdep change as well as flag consumers that they will have to update their code to be compatible with the new library version. Thanks.

**To Reproduce:**
N/A

**Expected behavior:**
When removing valid ranges from `peerDependencies`, please bump the major version.

Also, as a side note, your latest version specifies peerdeps on
```
    "react": "16.11.0",
    "react-native": ">=0.60 <0.63"
```
However, react-native 0.60.x specifies an exact peerdep of `react@16.8.6`, and 0.61.x requires `react@16.9.0`, so this constraint is not satisfiable with any version of react-native less recent than 0.62.0.
**Screenshots/Videos:**
N/A

**Environment:**
N/A

**Comment by chrisbobbe** [comment]
Similarly, https://github.com/react-native-community/react-native-webview/commit/bf1d64571#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R29 (released in v8.0.5, a patch version) effectively brought the minimum supported React Native version to v0.61 (see https://github.com/facebook/react-native/commit/0ccedf396#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R84).

**Comment by chrisbobbe** [comment]
@github-actions bot, please don't close this yet—there's no sign a maintainer is aware of the issue.

**Comment by elashpear** [comment]
Boo :(

**Comment by safaiyeh** [comment]
Made a PR here
