### ISSUE TITLE
AMP Facebook Plugin Comments not works in WebView

### ISSUE THREAD

**Issue by davidcort** [react-native-community/react-native-webview#1448]
**Bug description:**

Facebook web page return an error when i try login in facebook for posting a comment.

**To Reproduce:**

1. Add the WebView component.
2. Passing an URL to WebView component
3. Wait to Facebook Plugin Comments finish loading
4. Press the login button for publish a comment
5. Open Google Chrome with the Linking function from React Native
6. Facebook returns white screens with only "1"

**Expected behavior:**

Successfull login in facebook page and post comments in comments box.

**Screenshots/Videos:**

Screens add: 
<img width="286" alt="Captura de Pantalla 2020-06-09 a la(s) 18 48 12" src="https://user-images.githubusercontent.com/6045573/84211990-42b74980-aa82-11ea-943a-85dd9e510000.png">
<img width="293" alt="Captura de Pantalla 2020-06-09 a la(s) 18 48 36" src="https://user-images.githubusercontent.com/6045573/84211992-464ad080-aa82-11ea-861f-bc477cc6a947.png">
<img width="298" alt="Captura de Pantalla 2020-06-09 a la(s) 18 48 50" src="https://user-images.githubusercontent.com/6045573/84211993-46e36700-aa82-11ea-90d8-122c2383e6de.png">

**Environment:**
 - OS: Android
 - OS version: 10
 - react-native version: 0.61.4
 - react-native-webview version: 10.2.3

Webview Code

`return(
            <WebView
                ref={(ref) => { this.webview = ref }}
                source={{ uri: urlNote }}
                originWhitelist={["*"]}
                userAgent="Mozilla/5.0 (Linux; Android 4.4.4; One Build/KTU8 4L.H4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.135 Mobile Safari/537.36"
                mediaPlaybackRequiresUserAction={true}
                sharedCookiesEnabled={true}
                thirdPartyCookiesEnabled={true}
                mixedContentMode='always'
                startInLoadingState={true}
                style={{ marginTop: isTablet ? -60 : -50 }}
                renderLoading={() => (
                    <ActivityIndicator
                        color='#29aae1'
                        size='large'
                        style={{ flex: 1, alignItems: 'center', justifyContent: 'flex-start' }}
                    />
                )}
                onLoadStart={syntheticEvent => this.paginateStack(syntheticEvent)}
                onNavigationStateChange={e => this.setState({ canGoBack: e.canGoBack })}
            />
        )`

**Comment by scaralfred** [comment]
Hello. Did you find any solution to this issue?

**Comment by davidcort** [comment]
> Hello @davidcort Did you find any solution to this issue?

No, my team decided remove it :(
