### ISSUE TITLE
Can't embed an Instagram post on iOS - works fine on Android

### ISSUE THREAD

**Issue by Razorholt** [react-native-community/react-native-webview#1449]
I can't embed an instagram post on iOS (no errors, just blank, not rendering) but it works fine on android. Am I missing something? A CORS issue?

Here is a simple example: `<blockquote class="instagram-media"><a href="https://www.instagram.com/p/CAp716Jjr6i/"></a></blockquote><script async defer src="https://platform.instagram.com/en_US/embeds.js"></script>`

UPDATE: I can embed twitter posts on both platforms just fine, just not instagram.

**Comment by Razorholt** [comment]
Solved it by adding ` baseUrl: "https://www.instagram.com"`

**Comment by ak40u** [comment]
> Solved it by adding ` baseUrl: "https://www.instagram.com"`

where did you add baseUrl?

**Comment by janstuemmel** [comment]
i think he ment changing `<script async defer src="//platform.instagram.com/en_US/embeds.js"></script>` to `<script async defer src="https://platform.instagram.com/en_US/embeds.js"></script>`. Worked for me...

**Comment by rodrigov03** [comment]
> > Solved it by adding ` baseUrl: "https://www.instagram.com"`
> 
> where did you add baseUrl?

Just like that
Worked for me, thanks!

<WebView
        source={{html: htmlStr, baseUrl: 'https://www.instagram.com'}}
/>

**Comment by Razorholt** [comment]
@rodrigov03 is right. Sorry @ak40u I didn't get a notification after you posted.

**Comment by hungnv1709** [comment]
> i think he ment changing `<script async defer src="//platform.instagram.com/en_US/embeds.js"></script>` to `<script async defer src="https://platform.instagram.com/en_US/embeds.js"></script>`. Worked for me...

thank god. you save my time.
its worked for me.

**Comment by jpope19** [comment]
anyone have a full example? I can't figure out how to get it to fill the width / height

**Comment by janstuemmel** [comment]
@jpope19 Your question is not related to this issue. If you want the native WebView to match the inner web height look at HeightObserver on MDN and pass the information to the native WebView for example...
