### ISSUE TITLE
react-native-webview take much time to load the url.

### ISSUE THREAD

**Issue by kruz123** [react-native-community/react-native-webview#1452]
**hello, i am using react-native-webview library in my project.
In android webview propely work and dont take more time 
but in iphone devices webview load the url take too much time(around 5 minute or more).
my issue is why in iphone device take too much time load the url
so how to solve ??**

below my code:
-----------------------------
import React, { Component } from 'react';
import { View, BackHandler, AppState, Keyboard, ActivityIndicator, ImageBackground, StatusBar, Text, TouchableOpacity, Dimensions } from 'react-native';

import styleTheme from './StyleSheet';
import { WebUrl } from './Config';

import SplashScreen from 'react-native-splash-screen'
import { WebView } from 'react-native-webview';
import { NetworkInfo } from "react-native-network-info";
// import PushNotification from 'react-native-push-notification';
// import firebase from 'react-native-firebase';
import DeviceInfo from 'react-native-device-info';
import NetInfo from '@react-native-community/netinfo';
import KeepAwake from 'react-native-keep-awake';
import CallDetectorManager from 'react-native-call-detection'

var appVersion, brand, deviceId, model, readableVersion, systemName, systemVersion, isTablet, hasNotch, type, apiLevel,
  manufacturer, maxMemory, totalMemory, userAgent, isEmulator, isLandscape, supported32BitAbis, supported64BitAbis, supportedAbis, getToken,
  batteryLevel, getCarrier, getFreeDiskStorage, getIpAddress, getIpV4Address, usedMemory, features, getDeviceInfoWithTokenJson = {};

export default class WebviewPlayStory extends Component {

  constructor(props) {
    super(props);
    this.state = {
      loadWebview: true,
      isInternet: true,
      deviceToken: '',
      ipAddress: '',
      deviceInfo: '',
      visibleHeight: Dimensions.get('window').height,
    }
    this.onWebViewMessage = this.onWebViewMessage.bind(this);

  }
  componentDidMount = async () => {
    SplashScreen.hide();
    StatusBar.setHidden(true);
    KeepAwake.activate();

    await this.fetchInternetState();

    BackHandler.addEventListener('hardwareBackPress', this.onBackPress);
    AppState.addEventListener('change', this.handleAppStateChange);

    await this.makeDeviceInfoJsonData();

    this.startListenerTapped();

  }

  UNSAFE_componentWillMount() {
    this.keyboardDidShowListener = Keyboard.addListener('keyboardDidShow', this.keyboardDidShow.bind(this))
    this.keyboardDidHideListener = Keyboard.addListener('keyboardDidHide', this.keyboardDidHide.bind(this))
  }

  componentWillUnmount() {
    BackHandler.removeEventListener('hardwareBackPress', this.onBackPress);
    AppState.removeEventListener('change', this.handleAppStateChange);

    this.callDetector && this.callDetector.dispose();

    this.keyboardDidShowListener.remove();
    this.keyboardDidHideListener.remove();
  }
  
  /*
  	some code here
	.........
	
	......
	...
	...
	..
	.
	.....
  */

 
  onReloadPress = async () => {
    await this.fetchInternetState();
  }

  noInternetView = () => {
    return (
      <ImageBackground
        source={require('../assets/image/loader_bg.png')}
        style={[styleTheme.backgroundImage, { display: this.state.isInternet === false ? 'flex' : 'none' }]}>

        <View style={styleTheme.noInternetContainer} >

          <Text style={styleTheme.noInternetTitle}>No Internet</Text>

          <Text style={styleTheme.noInternetSemiText}>Looks like you are not connected</Text>

          <Text style={[styleTheme.noInternetSemiText, { marginTop: 0 }]}>to the internet</Text>

          <TouchableOpacity style={styleTheme.noInternetReloadButton} onPress={() => this.onReloadPress()}>
            <Text style={styleTheme.noInternetReloadButtonText}>Reload</Text>
          </TouchableOpacity>

        </View>

      </ImageBackground>
    )
  }

   onLoadEnd = () => {
      this.setState({ loadWebview: false });
   }

  activityIndicatorView = () => {
    return (
      <ImageBackground
        source={require('../assets/image/loader_bg.png')}
        style={styleTheme.backgroundImage}>

        <ActivityIndicator
          color="#009688"
          size="large"
          style={styleTheme.ActivityIndicatorStyle} />

      </ImageBackground>
    )
  }

  errorView = () => {

    return (
      <ImageBackground
        source={require('../assets/image/loader_bg.png')}
        style={[styleTheme.backgroundImage, { display: this.state.isInternet === false ? 'flex' : 'none' }]}>

        <View style={styleTheme.noInternetContainer} >

          <Text style={styleTheme.noInternetSemiText}>Oops,there is something wrong!</Text>

          <Text style={[styleTheme.noInternetSemiText, { marginTop: 0 }]}>Please tap on Reload Button to try again</Text>

          <TouchableOpacity style={styleTheme.noInternetReloadButton} onPress={() => this.onReloadPress()}>
            <Text style={styleTheme.noInternetReloadButtonText}>Reload</Text>
          </TouchableOpacity>
        </View>

      </ImageBackground>
    )

  }

  render() {
    let { visibleHeight } = this.state;
    return (
      <View style={{ overflow: "hidden", opacity: 0.99, height: visibleHeight }}>

        <WebView style={{ display: this.state.isInternet === true ? 'flex' : 'none' }}
          ref={r => (this.WEBVIEW_REF = r)}
          source={{ uri: WebUrl }}
          bounces={false}
          cacheEnabled={false}
          scrollEnabled={false}
          javaScriptEnabled={true}
          domStorageEnabled={true}
          mediaPlaybackRequiresUserAction={false}
          javaScriptEnabledAndroid={true}
          scalesPageToFit={true}
          renderLoading={() => this.activityIndicatorView()}
          startInLoadingState={true}
          onMessage={this.onWebViewMessage}
          onLoadEnd={() => this.onLoadEnd()}
          onError={() => { this.WEBVIEW_REF.reload(); }}
          renderError={() => this.errorView()}
        />

        {
          this.noInternetView()
        }

      </View>

    )
  }
}

**Comment by kruz123** [comment]
issue is still there , not solve and not found any solutions pls help!!!!!!!!!!!!

**Comment by GobindaSaha** [comment]
Is there still no solution? My app stucks at loading webview everytime I open it.

**Comment by kruz123** [comment]
issue was solve 
can you pls share your code...

**Comment by cblaze22** [comment]
Same issue here, no timeout available. Taking 2 minutes to timeout and having the user wait for it to throw a timeout error is unacceptable.  Need a timeout option.
