### ISSUE TITLE
Build error: cannot convert argument 2 from 'int64_t' to 'const winrt::hstring

### ISSUE THREAD

**Issue by tero-paananen** [react-native-community/react-native-webview#1456]
**Bug description:**

Does not compile with RN Windows 0.61.11

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2664	'void winrt::ReactNativeWebView::implementation::ReactWebViewManager::DispatchCommand(const winrt::Windows::UI::Xaml::FrameworkElement &,const winrt::hstring &,const winrt::Microsoft::ReactNative::IJSValueReader &) noexcept': cannot convert argument 2 from 'int64_t' to 'const winrt::hstring &' (compiling source file ReactPackageProvider.cpp)	ReactNativeWebView	...\node_modules\react-native-webview\windows\ReactNativeWebView\Generated Files\winrt\Microsoft.ReactNative.h	2124	
```

**To Reproduce:**
1. npx react-native init HelloWorld --version 0.61.5
2. cd HelloWorld
3. npx react-native-windows-init --version 0.61.11 --language cs --overwrite
4. Add react-native-webview into project.json ("react-native-webview": "^10.2.3")
5. yarn install
6. Add ReactNativeWebview into solution
7. Add module into App.xaml.cs `PackageProviders.Add(new ReactNativeWebView.ReactPackageProvider());` before InitializeComponent();
8. Build debug & x64

**Expected behavior:**
Build success

**Environment:**
react-native-cli: 2.0.1
react-native: 0.61.5
react-native-windows: 0.61.11

System: OS: Windows 10 10.0.18363
CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
Memory: 20.37 GB / 31.89 GB Binaries:
Node: 12.9.1 - C:\Program Files\nodejs\node.EXE
Yarn: 1.21.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
npm: 6.10.2 - C:\Program Files\nodejs\npm.CMD
npmPackages:
react: 16.9.0 => 16.9.0
react-native: 0.61.5 => 0.61.5
react-native-windows: 0.61.11 => 0.61.11
react-native-webview: 10.2.3
Installed UWP SDKs:
10.0.14393.0
10.0.16299.0
10.0.17763.0
10.0.18362.0

**Comment by sonicbobcat85** [comment]
Same issue. Please advise.

**Comment by LionelHoudelier** [comment]
Same issue. Please advise too...

**Comment by tero-paananen** [comment]
Following setup seems to build on Windows:

"react-native": "0.62.2"
"react-native-windows": "0.62.4"
"react-native-webview": "^10.4.0"
