### ISSUE TITLE
'WebView: `source.headers` is not supported when using POST.' (Android)

### ISSUE THREAD

**Issue by rgreen33** [react-native-community/react-native-webview#1457]
**Bug description:**
iOS is working fine.  However, I am getting the following error when debugging app on Android:  'WebView: `source.headers` is not supported when using POST.'

This is occurring when debugging on a physical device (Pixel 3a XL - latest OS) and on the Android virtual device (Pixel 3a XL API 29)..

I did find a similar issue that has been closed...but, that closed issue has recent comments, asking for updates, as the issue does not seem to be resolved.

**To Reproduce:**
Below is a sample of the code that I am using:

      {
        const { navigation } = this.props;
        const itemURL = navigation.getParam('itemURL');

        let loginURL = itemURL;
        let header = {
          'X-Api-Key': ‘xxxx-xxxx-xxxx-xxxx’
        };
        let loginObj = {
          ‘myId': myID
        }
        let loginStr = JSON.stringify(loginObj);

        const sourceObj = {
          uri: loginURL,
          headers: header,
          body: loginStr,
          method: 'POST'
        }

        console.log(sourceObj);

        return (
          <WebView
            //Loading URL
            source={sourceObj}
            //Enable Javascript support
            javaScriptEnabled={true}
            //For the Cache
            domStorageEnabled={true}
            //View to show while loading the webpage
            renderLoading={this.ActivityIndicatorLoadingView}
            //Want to show the view or not
            startInLoadingState={true}
          />
        )
      }

**Expected Results**
POST data should be sent to page and then page should be displayed in WebView.

**Environment:**
System:
    OS: macOS 10.15.5
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 90.50 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.4.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.5 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3
      System Images: android-28 | Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64, android-28 | Google X86_ARM Intel x86 Atom, android-29 | Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_252 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^16.13.1 => 16.13.1 
    react-native: ^0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by ggittt** [comment]
Any updates ?

**Comment by KiranRadish** [comment]
Any updates on this?

**Comment by marshallcool** [comment]
why was the thread closed if the problem is not solved ?
