### ISSUE TITLE
<WebView /> does not load the web in the View on iOS and Android

### ISSUE THREAD

**Issue by kopax** [react-native-community/react-native-webview#1459]
**Bug description:**

I can't display any webview using `uri` nor `html` in source.

This is the expo documentation https://docs.expo.io/versions/latest/sdk/webview/, 
I did `expo install react-native-webview`

Within the snack, it works on android and ios as expected, but with real redevice, I keep having blank pages.

**To Reproduce:**
```js
import * as React from 'react';
import { Text, View, StyleSheet } from 'react-native';
import { WebView } from 'react-native-webview';

export default function App() {
  return (
    <WebView
      style={{ flex: 1, width: '100%' }}
     source={{ uri: 'https://www.google.fr' }} 
    />
  );
}
```

I also tried:

```jsx
<WebView
      style={{
        flex: 1,
        width: '100%',
        height: '100%',
        alignSelf: 'stretch',
      }}
      source={{
        uri: 'https://www.lemonde.fr',
      }}
      startInLoadingState={true}
      scalesPageToFit={true}
      javaScriptEnabled={true}
      domStorageEnabled={true}
      {...props}
/>
```

It's always an empty View.

Reproduction: https://snack.expo.io/@kopax/sponaneous-waffle

**Expected behavior:**

I expec to load https://www.google.fr on my real ios and android device

**Environment:**
 - OS: Debian
 - OS version: Sretch
 - react-native version: sdk36
 - react-native-webview version: latest
- iphone 6
- galaxy s9

**Comment by Luckygirlllll** [comment]
I have the same problem, how did you solve this?
