### ISSUE TITLE
CookieManager flush needed

### ISSUE THREAD

**Issue by perottilds** [react-native-community/react-native-webview#1463]
I believe [this](https://github.com/react-native-community/react-native-webview/issues/1345) is related to https://github.com/apache/cordova-android/issues/802#issuecomment-523376472
It only happens on Android because of the flush needed by CookieManager
https://developer.android.com/reference/android/webkit/CookieManager#flush()
I've been having trouble login in users and keeping their session and that's why.

I'm having trouble figuring out whether I should open an issue here or on [rnc-cookies](https://github.com/react-native-community/cookies).

The solution is to enable the flush api through the ref which seems kinda invasive. I could open a PR for that.

**Comment by TommyLeong** [comment]
@perottilds dont we use rn cookie to clear them? Hv u tried that and manage to clear them?

**Comment by perottilds** [comment]
@TommyLeong there is no exposed method to flush cookies
@luancurti has [this pr](https://github.com/react-native-community/cookies/pull/64) open for that matter

**Comment by TommyLeong** [comment]
Huhh? Did I understand the meaning of `flush()` here wrong? I was assuming this method to remove cookies from existing webview. From [Android Doc](https://developer.android.com/reference/android/webkit/CookieManager#flush()), it mentioned .

> Ensures all cookies currently accessible through the getCookie API are written to persistent storage

**Comment by perottilds** [comment]
Yes, it seems so.

**Comment by safaiyeh** [comment]
Bad naming on Android APIs part

**Comment by safaiyeh** [comment]
Landed with v4 of react-native-cookies! If that solved this, feel free to close this issue.

**Comment by perottilds** [comment]
Closing because rncookies had it implemented for this use case.
https://github.com/react-native-community/cookies/issues/58
