### ISSUE TITLE
onLoadProgress fires inconsistently or not at all when navigating

### ISSUE THREAD

**Issue by ortonomy** [react-native-community/react-native-webview#1470]
**Bug description:**

When loading a website (specifically [https://www.onigiri.store/blog](https://www.onigiri.store/blog)), the `onLoadProgress` method fires inconsistently. 

It ALWAYS fires consistently when the webview loads
It SOMETIMES fires when using a back or forward navigation
It NEVER fires clicking a link on the page

**To Reproduce:**
1. Load the website [https://www.onigiri.store/blog](https://www.onigiri.store/blog) into react native webview

**Expected behavior:**
I can implement a progress bar whenever navigation occurs, either triggered by webview or user click on the website.

**Screenshots/Videos:**

1. I just click on the 'health blog tab
2. I click on the shop link
3. I click on the health blog burge menu
4. I click on an article

Notice how the progress is only triggered for 2 of the 4 navigation events.

[webview_progress.mp4.zip](https://github.com/react-native-community/react-native-webview/files/4802572/webview_progress.mp4.zip)

**Environment:**
 - OS: `iOS`
 - OS version: `13`
 - react-native version:`0.62.2`
 - react-native-webview version: `10.3.1`

**Comment by chezsmithy** [comment]
Also seeing this issue. Any updates?

**Comment by ortonomy** [comment]
This is not fixed! Don't close it!

**Comment by hkar19** [comment]
i have this issue as well. 
for me, i am using rnWebview 9.0.2 and it run smoothly in iOS but not in android.
