### ISSUE TITLE
Can't download file when i click to download 

### ISSUE THREAD

**Issue by recepgums** [react-native-community/react-native-webview#1474]
![Screenshot_2020-06-20-22-04-12-667_com cubicle](https://user-images.githubusercontent.com/36725313/85209631-28af1e00-b342-11ea-9d69-20510f770faf.jpg)
 I got this error when i clicked download. Its working on normal mobile web browser and also on the web site but on the mobile application (which i just use this package) doesn't work. Is that web site problem or your package? Is there any way to fix it?

**Comment by fauzzi** [comment]
@recepgums  may I know you're all using the dependencies?  I have a similar issue for this, but I till try to update it to the latest version. Maybe have some issues with permission.

**Comment by recepgums** [comment]
@fauzzi  Here is,

`"dependencies": {
    "react": "16.11.0",
    "react-native": "0.62.2",
    "react-native-webview": "^9.4.0"
  },
  "devDependencies": {
    "@babel/core": "7.9.6",
    "@babel/runtime": "7.9.6",
    "@react-native-community/eslint-config": "0.0.5",
    "babel-jest": "24.9.0",
    "eslint": "6.8.0",
    "jest": "24.9.0",
    "metro-react-native-babel-preset": "0.58.0",
    "react-test-renderer": "16.11.0"
  },`


Well as i said its working fine on mobile browser. Do you think permission issue because of AndroidManifest file? or

**Comment by lfalkner** [comment]
@recepgums I'm not sure if you're still looking, or if this is specific to newer android versions for you, but we  ran into a similar issue, which we resolved by disabling [scoped storage](https://developer.android.com/about/versions/10/privacy/changes#scoped-storage) while we sort out what our strategy was to properly handle it. You can disable scoped storage by setting `android:requestLegacyExternalStorage="true"` in your AndroidManifest.xml. I hope that helps you :)
