### ISSUE TITLE
Invariant Violation: Text strings must be rendered within a <Text> component.

### ISSUE THREAD

**Issue by dinhtrong** [react-native-community/react-native-webview#1478]

**Comment by TerrerSandman** [comment]
I'm facing the same errors.

react-native-webview = ^10.9.0
react-native = 0.61.5

1. npm install --save react-native-webview
2. simply put `<WebView source={{ uri: 'https://www.example.com' }} />;`
3. error appear

**Comment by gyt95** [comment]
I also encountered the same problem and I finally found the reason is that the Usage Example contained a semicolon so that throw error.

```js
import React, { Component } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { WebView } from 'react-native-webview';

// ...
class MyWebComponent extends Component {
  render() {
    return <WebView source={{ uri: 'https://reactnative.dev/' }} />;   // here
  }
}
```

Solution:
Just remove the semicolon.
