### ISSUE TITLE
iOS background audio sound is muted but the audio player keep going

### ISSUE THREAD

**Issue by ibnukipa** [react-native-community/react-native-webview#1486]
**Bug description:**
I've setup the proper configuration:

<img width="894" alt="Screen Shot 2020-06-26 at 15 30 40" src="https://user-images.githubusercontent.com/12580174/85837239-ff6b1380-b7c1-11ea-8339-18d0c0ab18f8.png">

When I minimise the app, like 30s after that the sound is disappearing/gone but the audio player (on top of the screen) is keep going. It's more like the audio sound is being muted or something.

I can re-play it again from the player by toggling the pause and then play button

NOTE: it only occurs on the real device. It works perfectly on Simulator

**To Reproduce:**
Embed the Audio to the WebView

**Expected behavior:**
The audio sound is not muted

**Environment:**
 - OS: iOS
 - OS version: 13.5.1
 - react-native version: 0.61.5
 - react-native-webview version: 10.3.1

**Comment by Pierre-CLIND** [comment]
@ibnukipa did you find a solution?

**Comment by ibnukipa** [comment]
@Pierre-CLIND  no, I did not. turns out , this issue related to the iOS13 WKWebView. I've tried it on the latest iOS14 beta public and it works perfectly (did not change any codes)
