### ISSUE TITLE
Display the html source code on android when load local file, but working on iOS use the same code.

### ISSUE THREAD

**Issue by te3** [react-native-community/react-native-webview#1488]
```javascript
const html = require('@/assets/index.html');
<WebView source={html} />
```

**Environment:**
 - OS: android
 - OS version: 5.1.1
 - react-native version: 0.62.2
 - react-native-webview version: 10.3.2

**Comment by thinhlm** [comment]
I'm facing same issue

**Comment by ngtrungt** [comment]
I got same issue

**Comment by Jszy** [comment]
How to solve the same issue ?

**Comment by azha1983** [comment]
i'm looking the solution as well...coz stuck with fusionchart failed on android

**Comment by mofengfs** [comment]
> 我遇到了同样的问题，然后执行以下操作：
> 
> 1. 手动将HTML页面复制到android / app / src / main / assets文件夹
> 2. 将代码中的引用更改为file：/// android_asset而不是./或../
> 
> * 例如file：///android_asset/generic.html
> 
> 1. 使用：<WebView source = {{uri：'file：///android_asset/generic.html'}} />

What if it is an Expo user?

**Comment by mofengfs** [comment]
> I got same issue then I did as below:
> 
> 1. Manually copy the HTML pages to android/app/src/main/assets folder
> 2. Change the reference in code to file:///android_asset instead of ./ or ../
> 
> * For example file:///android_asset/generic.html
> 
> 1. Using: <WebView source={{ uri: 'file:///android_asset/generic.html' }} />

What if it is an Expo user?

**Comment by borasumer** [comment]
Why is this issue closed? I am still having the same issue.

**Comment by azha1983** [comment]
the solution only for react native cli not on expo
