### ISSUE TITLE
some of the secure pages are not loading on some Android 9

### ISSUE THREAD

**Issue by viswakarmalovekush** [react-native-community/react-native-webview#1489]
Hi,

I am facing issue while loading secure url on some android 9 devices, issue is that the page is not loading it is displaying while blank page, but I have done some changes in **RNCWebViewManager** class and it is working fine. below is the changes.

 @Override
  protected void addEventEmitters(ThemedReactContext reactContext, WebView view) {
    // Do not register default touch emitter and let WebView implementation handle touches
    
    try{
           view.setWebViewClient(new RNCWebViewClient());
          //new line
           view.setWebViewClient(new WebViewClient() {@Override public void onReceivedSslError(WebView v, SslErrorHandler handler, SslError er){ handler.proceed(); }});
        }catch(Exception e){
          e.printStackTrace();
        }
  }

can you please add this changes.

Thanks

**Comment by thephpjedi** [comment]
@viswakarmalovekush: Have you explored if the reason for the blank page is due to an invalid certificate or other SSL error?
