### ISSUE TITLE
Android cannot display the view of iframe,It seems to be caused by WebViewClient‘s shouldOverrideUrlLoading api

### ISSUE THREAD

**Issue by Mollet-Yuan** [react-native-community/react-native-webview#1496]
**Bug description:**

During the process of loading TradingView in WebView, I tried to load TradingView locally, but Android failed and IOS worked well

**To Reproduce:**

I found that react-native-webview does not support iframe on android

**Expected behavior:**

android ios display the tradingview,

**Screenshots/Videos:**

ios:
![image](https://user-images.githubusercontent.com/65003875/86229363-2fe7ee80-bbc2-11ea-9339-046b2864953a.png)
android:
![image](https://user-images.githubusercontent.com/65003875/86229428-47bf7280-bbc2-11ea-803d-1297c85e0547.png)

**repair plan:**

I've tried to find a solution from Android code, i found that it work on android native well, i found an api of WebViewClient (shouldOverrideUrlLoading ),  I delete those code in RNCWebViewManager.java 760:

    // @Override
    // public boolean shouldOverrideUrlLoading(WebView view, String url) {
    //   progressChangedFilter.setWaitingForCommandLoadUrl(true);
    //   dispatchEvent(
    //     view,
    //     new TopShouldStartLoadWithRequestEvent(
    //       view.getId(),
    //       createWebViewEvent(view, url)));
    //   return false;
    // }

    // @TargetApi(Build.VERSION_CODES.N)
    // @Override
    // public boolean shouldOverrideUrlLoading(WebView view, WebResourceRequest request) {
    //   final String url = request.getUrl().toString();
    //   return this.shouldOverrideUrlLoading(view, url);
    // }

then the tradingview show, but I don't know if I'm going to cause additional problems,
I hope react-native-webview can add an props to support or dis iframe。 please help me

**Environment:**
 - OS:android
 - OS version:android 9
 - react-native version:0.62.2
 - react-native-webview version:10.2.3

**Comment by tradebulls** [comment]
+1
