### ISSUE TITLE
MIGRATED: It is no longer possible (0.49-0.54) to retrieve Google AMP urls (#18442)

### ISSUE THREAD

**Issue by jamonholmgren** [react-native-community/react-native-webview#15]
Migrated from https://github.com/facebook/react-native/issues/18442.

@ksegla says:

---

 I have reviewed the documentation
  I have searched existing issues
  I am using the latest React Native version
Google AMP is now how most news articles are loaded when someone makes a query on Google. Up to 0.48.4, it was possible to detect and manage (bookmark, etc.) page changes in that setting. I was on 0.48.4 and recently made the jump to 0.54. And my app can no longer detect those urls. I believe it is because of the commit ffbd3db which went into effect starting from 0.49.

Environment
Environment:
OS: Windows 10
Node: 6.11.4
Yarn: Not Found
npm: 5.7.1
Watchman: Not Found
Xcode: N/A
Android Studio: Not Found

Packages: (wanted => installed)
react: 16.3.0-alpha.1 => 16.3.0-alpha.1
react-native: 0.54.0 => 0.54.0

Steps to Reproduce

import React, { Component } from 'react';
import { WebView } from 'react-native';

class MyWeb extends Component {

  onNavigationStateChange(navState) {
    alert(JSON.stringify(navState);
  }
  render() {
    return (
      <WebView
        source={{uri: 'https://www.google.ca/search?q=canada'}}
        onNavigationStateChange={ this.onNavigationStateChange.bind(this) }
        style={{marginTop: 20}}
      />
    );
  }
}

Use the component as a WebView and click on any news in the search results. It will likely be an AMP page. The first will fire the alert but with an outdated url. The subsequent pages won't do anything.

Expected Behavior
Google AMP pages url are detected. An alert is generated for every AMP page and with the right url (i.e., contains an "/amp/")

Actual Behavior
onNavigationStateChange() no longer detects change of url for pages like those from Google AMP. It used to, up to 0.48.4. This means those pages can no longer be directly bookmarked or simply managed.
This commit ffbd3db is likely the cause of this regression.

---

_More info on original thread_

**Comment by Salakar** [comment]
Hey @ksegla 👋 and anyone else with this issue - if this is still a big issue for yourselves please you could help us out and send up a PR based on [facebook/react-native#18548](https://github.com/facebook/react-native/pull/18548).

I'll go ahead and close this issue given its age and lack of activity. But if you'd like me to re-open please let me know.

Thanks
