### ISSUE TITLE
Exception thrown while executing UI block: -[__NSCFConstantString count]: unrecognized selector sent to instance **

### ISSUE THREAD

**Issue by umeshdhauni** [react-native-community/react-native-webview#1500]
**Bug description:**
I am using react-native-webview in my project but it's throwing the above error.

 <WebView
                    style={{ flex: 1 }}
                    useWebKit={true}
                    startInLoadingState={false} 
                    source={{ url: 'https://www.google.com' }}
                />

This is the code which i am using.
![Screen Shot 2020-07-06 at 9 47 53 PM](https://user-images.githubusercontent.com/21235981/86615652-5ea30200-bfd2-11ea-95a0-751e2eca5500.png)

**To Reproduce:**

**Expected behavior:**

**Screenshots/Videos:**

**Environment:**
 - OS:Mac OS
 - OS version: 10.15.5
 - react-native version:0.62.2
 - react-native-webview version:10.3.2

**Comment by BradMcEvilly** [comment]
Please do not stalebot me on this one. I have this issue, too and am trying to identify a solid solution.
