### ISSUE TITLE
Blank screen when using react-native-webview

### ISSUE THREAD

**Issue by hiimjustin000** [react-native-community/react-native-webview#1501]
**Bug description:** The screen is blank when I use react-native-webview

When I use react-native-webview, I get a blank screen when running an app. All that is left is a tiny red square at the top left corner, which isn't what is supposed to happen.

**To Reproduce:**

1. Use WebView in any way
2. The bug appears

**Expected behavior:**

For react-native-webview to, y'know, **work.**

**Screenshots/Videos:**

https://cdn.discordapp.com/attachments/365561999532228608/730282368060882964/unknown.png

**Environment:**
 - OS: Microsoft Windows
 - OS version: 10.0.18363.900
 - react-native version: 38.0.0
 - react-native-webview version: 9.4.0

**Comment by GreatAuk** [comment]
try `overflow: 'hidden'`
```
<View style={{ flex: 1, overflow: 'hidden' }}>
  <Webview />
</View>
```

**Comment by hiimjustin000** [comment]
Doesn't work.

**Comment by Synaric** [comment]
same issue, not work:
```
<WebView style={{flex: 1, overflow: 'hidden'}}
                 source={{ html: '<h1>Hello world</h1>' }} />
```

**Comment by hiimjustin000** [comment]
Update: It doesn't work on web, but everywhere else it works
