### ISSUE TITLE
Webview doesn't get any height if elements are before

### ISSUE THREAD

**Issue by drager** [react-native-community/react-native-webview#1502]
Hey! I'm trying to use react-native-webview to display some HTML/js/css content. However, I also want to display native views before and maybe after the webview. I.e. `<ScrollView><View>...</View><Webview /><View>...</View></ScrollView>`

But when I do this, the webview loses its height... I have tried making the webview position absolute with 100% height and 100% width. This makes it getting the right height, however now it will obviously be on top of the other content. Also it will take up all pointerEvents.

To reproduce simply do: `<ScrollView><View>...</View><Webview /><View>...</View></ScrollView>` and it will get no height at all.

**Comment by jsamr** [comment]
@drager Might want to try this: https://formidable-webview.github.io/webshell/docs/autoheight/
