### ISSUE TITLE
[Android] injectedJavaScript only works in Debug Mode

### ISSUE THREAD

**Issue by witalobenicio** [react-native-community/react-native-webview#1503]
**Bug description:**
My javascript is only injected when in debug mode on Android. In iOS works perfectly.

**To Reproduce:**
```javascript
<WebView
            source={{
              uri: this.state.webViewUri,
            }}
            ref={ref => {
              this.webView = ref;
            }}
            javaScriptEnabled
            domStorageEnabled
            onError={this.onError}
            onShouldStartLoadWithRequest={this.onShouldStartLoad}
            onMessage={this.onMessage}
            injectedJavaScript={myExtenseJavascript}
          />
```

**Expected behavior:**
Should load my javascript and show an alert.

**Environment:**
 - OS: Android
 - OS version: 8.1.0
 - react-native version: 0.62.2
 - react-native-webview version: 9.4.0

**Comment by witalobenicio** [comment]
The problem was in fact due to enable Hermes.
When Hermes is enabled it's not possible to use `myFunction.toString()`, so I was ending up with some weird function string.

**Comment by kashif-sk** [comment]
@witalobenicio can you please share how did you fix this

**Comment by witalobenicio** [comment]
@kashif-sk just write your function inside quotes instead transforming to string.
Hermes transforms your js code in native code, and the instructions passed to WebView are not recognized when using toString().

**Comment by kashif-sk** [comment]
@witalobenicio Thanks will check

**Comment by margox** [comment]
Thanks, you saved me and my project
