### ISSUE TITLE
Loading the dropdown options at the top of the webview UI, Expected behavior to load at the dropdown box

### ISSUE THREAD

**Issue by PavanKumar001** [react-native-community/react-native-webview#1507]
**Bug description:**

**To Reproduce:**

**Expected behavior:**

**Screenshots/Videos:**

**Environment:**
 - OS: Android 
 - OS version: Pie (9)
 - react-native version:sdk-36.0.1
 - react-native-webview version:^10.3.2

**Comment by PavanKumar001** [comment]
> **Bug description:**
> 
> **To Reproduce:**
> 
> **Expected behavior:**
> 
> **Screenshots/Videos:**
> 
> **Environment:**
> 
> * OS: Android
> * OS version: Pie (9)
> * react-native version:sdk-36.0.1
> * react-native-webview version:^10.3.2

**Comment by kamilluc** [comment]
still searching for solutions and if you found one, please open a pull request!
