### ISSUE TITLE
[iOS] WebView pauses XHR requests when in background

### ISSUE THREAD

**Issue by petlys** [react-native-community/react-native-webview#151]
**iOS WKWebView only!**

When having a React Native `<Dialog>` or anything else (a Safari browser tab for instance) in the foreground, the WebView halts/stops/pauses XHR requests on the webpage being displayed. 
The request is sent when the WebView returns to the foreground again.

This breaks some core functionality in our app, since we trigger a request in the webpage through a native action in a `<Dialog>` (utilising the `postMessage` API).

**Comment by trevorKirpaulRTS** [comment]
@petlys Did you ever resolve this issue or find a work-around for it?

**Comment by petlys** [comment]
@trevorKirpaulRTS Nope, ended up moving the network request to the native layer instead of the webpage being displayed in the WebView
