### ISSUE TITLE
WebView stops playing audio when app leaves the foreground

### ISSUE THREAD

**Issue by gyoung-panopto** [react-native-community/react-native-webview#1516]
**Bug description:**

In my WebView I'm playing a video, but when the app goes into the background the audio stops and the video pauses.

I have used expo-av Audio.setAudioModeAsync({ staysActiveInBackground: true }) to ensure that background playback is allowed, and it is working properly with native video playback, just not playback in the WebView.

Is this something that is supported in the WebView? Or will I have to use a native approach instead?

**To Reproduce:**

1. Point WebView to a source that plays video in html
2. Run the app and start playing the video
3. Press the home button to put the app in the background
4. Playback stops after a brief delay

**Expected behavior:**

Video should continue playing and audio should continue while the app is in the background, according to the audio mode set through Expo

**Environment:**
 - OS: Android
 - OS version: 10
 - react-native version: 0.62
 - react-native-webview version: 9.4.0

**Comment by Goszu** [comment]
still searching for solutions

**Comment by rohitsingh2410** [comment]
still searching for solutions

**Comment by smoothwastaken** [comment]
still searching for solutions

**Comment by tomyates** [comment]
Did anyone find a solution to this?
