### ISSUE TITLE
blank page if the page use react-spring

### ISSUE THREAD

**Issue by tudislei** [react-native-community/react-native-webview#1519]
Not sure if it is my special problem,
but seems spring is causing some kind of blank page on my Webview.

there was no error message at first,
after spending some time , I see an error :
 
TypeError: Object.entries is not a function

wonder if anyone has loaded a website with react-spring?  Thank you

**Comment by bulby97** [comment]
On some old Android versions Object.entries does not exist, you need to create a polyfill and put this code at the top of your js code :

```
// Polyfill for Object.entries
if (!Object.entries) {
  Object.entries = function(obj) {
    const ownProps = Object.keys(obj)
    let i = ownProps.length
    const resArray = new Array(i) // preallocate the Array
    while (i--) resArray[i] = [ownProps[i], obj[ownProps[i]]]

    return resArray
  }
}
```
