### ISSUE TITLE
Webview Canvas dissapears when changing width and height

### ISSUE THREAD

**Issue by Zurdge** [react-native-community/react-native-webview#1522]
#### Dependencies
```
"dependencies": {
    "react": "16.13.1",
    "react-native": "0.63.1",
    "react-native-webview": "^10.3.2"
  },
```
#### Device
- Android emulator

-----

### Hi folks 😸 

I've been trying to get a canvas to work inside ```react-native-webview``` and I'm getting some strange results

If I leave the canvas width and height as a small value such as ```256x256``` then I can draw to it just fine.
however if I change the dimensions by either
```
<canvas id='canvas' width="1024" height="1024"/>
```
or
```
canvas.width = 1024;
canvas.height = 1024;
```
then it disappears.

I'm a bit stumped why this is happening. Is the canvas something webview can't reproduce?

Here is a repo to a example project.
To reproduce the issue, edit src/html.js and set the width & height to a value greater than ```256x256```

https://github.com/Zurdge/React-Native-Webview-Broken-Example

- ```npm install```
- open in android studio and build
- ```npx react-native start``` 

| ```256x256``` ✔️ |      ```1024x1024``` ❌ |  
|----------|:-------------:|
| <img src="https://user-images.githubusercontent.com/10058489/87725074-7e95ab00-c7b4-11ea-9e33-701d2e605043.png" width="45%">| <img src="https://user-images.githubusercontent.com/10058489/87725233-d207f900-c7b4-11ea-8b88-6b554bc3e881.png" width="45%"> |

**Comment by BraveEvidence** [comment]
This might help https://www.youtube.com/watch?v=wKr1kxNccgo
