### ISSUE TITLE
injectedJavaScript no working

### ISSUE THREAD

**Issue by Linrasis** [react-native-community/react-native-webview#1554]
Hello,

**Bug description:**
I have UPGRADE my old app, for accept by Apple i need remove UIWebview, so i have update react-native-webview 6.0.0 to 10.3.2 but now injectedJavaScript no working..

My old code :
```
const disableZoom = "const meta = document.createElement('meta'); meta.setAttribute('content', 'initial-scale=1.0, maximum-scale=1.0'); meta.setAttribute('name', 'viewport'); document.getElementsByTagName('head')[0].appendChild(meta);";

<WebView
   style={stylesLive.webview}
   source={{uri: 'https://www.twitch.tv/embed/hebo/chat?parent=tiboy.fr'}}
   injectedJavaScript={disableZoom}
   scalesPageToFit={false}
   useWebKit={true}
/>
```

I have try :
```
const jsCode = "document.querySelector('.HeaderHero').style.backgroundColor = 'purple';";

<WebView
 ref={ref => {
  this.webview = ref;
 }}
 source={{ uri: 'https://reactnative.dev' }}
 javaScriptEnabledAndroid={true}
 injectedJavaScript={jsCode}
/>
```

How to pass code now? I would like to deactivate the zoom of the webview, especially when I select a field it zooms me all without zooming out after ... two days that I test, search all the possible posts on the net and test other codes ..

**Environment:**
 - OS: MAC OS X
 - OS version: 10.15.5
 - react-native version: 0.62.2
 - react-native-webview version: 10.3.2

**Comment by lrusso** [comment]
@Linrasis, the documentation in the **react-native-webview** repository about how the **injectedJavaScript** property works is outdated. Now you need to set an **onMessage** event (an empty one it's ok) in order to the code in **injectedJavaScript** property to be executed. Below you can see an example of this. Hope it may help you.

````javascript
    const runFirst =
        "let meta = document.createElement('meta'); meta.setAttribute('name', 'viewport'); meta.setAttribute('content', 'width=600'); document.getElementsByTagName('head')[0].appendChild(meta);"

    return (
        <WebView
            source={{ uri }}
            originWhitelist={['*']}
            startInLoadingState={true}
            onError={() => setError(true)}
            onMessage={(event) => {}}
            injectedJavaScript={runFirst}
        />
    )
````

**Comment by safaiyeh** [comment]
@lrusso thank you! Could you submit a PR to update the docs for this?

**Comment by Linrasis** [comment]
Thank's for this reply, work perfectly. Juste add :

`onMessage={(event) => {}}`

**Comment by alakdam07** [comment]
I have similar issue and  I even use `onMessage` but still it does not work. 

```
import React, { Component } from 'react';
import {
  Text,
  View,
  StyleSheet,
  TouchableHighlight,

} from 'react-native';

import { WebView } from 'react-native-webview';
let jsCode = `
    document.querySelector('.cBIlxL').style.display = 'none';
`;

export default class App extends Component {
  render() {
    return (
      <View style={localStyles.viroContainer}>

        <WebView
          source={{ uri: "https://www.s-kaupat.fi/sivu/usein-kysytyt-kysymykset" }}
          style={{ flex: 1 }}
           onMessage={() => {}}
          injectedJavaScript={jsCode}
          javaScriptEnabled={true}
        

        />

      </View>
    );
  }

}

var localStyles = StyleSheet.create({
  viroContainer: {
    flex: 1,
  },

});
```

**Comment by vishwa1937** [comment]
> @Linrasis, the documentation in the **react-native-webview** repository about how the **injectedJavaScript** property works is outdated. Now you need to set an **onMessage** event (an empty one it's ok) in order to the code within the **injectedJavaScript** property to be executed. Below you can see an example of this. Hope it may help you.
> 
> ```js
>     const runFirst =
>         "let meta = document.createElement('meta'); meta.setAttribute('name', 'viewport'); meta.setAttribute('content', 'width=600'); document.getElementsByTagName('head')[0].appendChild(meta);"
> 
>     return (
>         <WebView
>             source={{ uri }}
>             originWhitelist={['*']}
>             startInLoadingState={true}
>             onError={() => setError(true)}
>             onMessage={(event) => {}}
>             injectedJavaScript={runFirst}
>         />
>     )
> ```

Thank You @Irusso. This worked for me.
