### ISSUE TITLE
Hey, buddy, there's a way h5 can generate a 16MB buffer to send react-native React -native Console.log doesn't work and backfires

### ISSUE THREAD

**Issue by ShunKeJiang** [react-native-community/react-native-webview#1575]
Hey, buddy, there's a way h5 can generate a 16MB buffer to send react-native React -native Console.log doesn't work and backfires

**Comment by ortonomy** [comment]
@ShunKeJiang -- outside China, H5 doesn't mean anything. Perhaps explain what you're talking about.

**Comment by ShunKeJiang** [comment]
@ortonomy

**Comment by jacquesdev** [comment]
> @ShunKeJiang -- outside China, H5 doesn't mean anything. Perhaps explain what you're talking about.

outside China and the html specification
