### ISSUE TITLE
Support react-native 0.63

### ISSUE THREAD

**Issue by Tom32i** [react-native-community/react-native-webview#1581]
`react-native-webview` is curently locked on specific versions of `react` and `react-native` :

```json
"peerDependencies": {
    "react": "16.11.0",
    "react-native": ">=0.60 <0.63"
  },
```

Problem is I'd like to move my app on to `react@16.13.1` and `react-native@0.63` and can't right now since react-native-webview doesn't support it yet.

Is there a compatibility reason for that lock?
Is there any plan to move on to the latest versions of react and react-native?

Thanks.

**Comment by safaiyeh** [comment]
Thanks for the issue @Tom32i, opened a PR for this
