### ISSUE TITLE
[iOS] JS confirm causes a native crash

### ISSUE THREAD

**Issue by cristianoccazinsp** [react-native-community/react-native-webview#1585]
**Bug description:**

Out of the blue, using `confirm("test")` in a webview will raise the following native exception:

```
2020-08-21 12:36:59.614662-0300 zinspector3[4620:1558927] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Completion handler passed to -[RNCWebView webView:runJavaScriptConfirmPanelWithMessage:initiatedByFrame:completionHandler:] was not called'
*** First throw call stack:
(0x189435654 0x189157bcc 0x18932ba58 0x190ac0674 0x190b3a24c 0x190bb8ec8 0x189023a4c 0x102972b30 0x189023a4c 0x18cb11afc 0x18cb0fca8 0x18917404c 0x189173f44 0x1982c844c 0x1982f5d7c 0x1893b3ad8 0x1893b3a30 0x1893b31b8 0x1893ae1e8 0x1893adba8 0x19351d344 0x18d4e93e4 0x1029706e8 0x1892358f0)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

I have downgraded to 10.4.0 and the issue does not happen, I suspect the following PRs may have introduced the bug since it happens with 10.4.1 and 10.4.2, up until 10.7.0:
https://github.com/react-native-community/react-native-webview/pull/1567

**To Reproduce:**

`confirm("Hi")` in any webview.

**Expected behavior:**

No crash

**Screenshots/Videos:**

-

**Environment:**
 - OS: iOS
 - OS version: any version > 10
 - react-native version: 0.62.2
 - react-native-webview version: 10.4.1 to 10.7.0

**Comment by cristianoccazinsp** [comment]
I'm showing the webview within a Modal? Could that be causing issues?  Were you able to confirm the crash with a simple webview ?  Can't really update the library until this is addressed :(

**Comment by jxm2004** [comment]
Hmmm yeah, the webview within a modal seems like the winner; thought is that a modal can't present another modal.

Removing the && condition would not be proper, it is a correct check. The only reason it works without it for you is that the alert goes on the viewController presenting the modal with the webview I suppose, bit convoluted, maybe fortunate bug hah.

Could you make it so that the webview is not in a modal? Only thing that comes to mind really.

**Comment by cristianoccazinsp** [comment]
Well, everything else works fine, except confirms.  I would guess the way the code finds the right view/controller to present the alert is not the right one, hence the crash.

Other libraries just use `UIViewController *ctrl = RCTPresentedViewController()` to get the right view in the hierarchy.  Maybe the current recursive code is not right.

For instance, the code for the above is here https://github.com/facebook/react-native/blob/master/React/Base/RCTUtils.m#L556 and looks like the check is against `isBeingDismissed` rather than `isBeingPresented`.  Have you tried this?

**Comment by cristianoccazinsp** [comment]
@jxm2004 I have just tried the following update, without all the recursive calls from `topViewControllerWithRootViewController` and it seems to be working fine (no crash in a modal):

```
-(UIViewController *)topViewController{
    return RCTPresentedViewController();
//    UIViewController *controller = [self topViewControllerWithRootViewController:[self getCurrentWindow].rootViewController];
//    return controller;
}
```

Can you check if using this method to obtain the top view also works for your use case?  Which specific case were you trying to fix with this change? Perhaps I can reproduce it myself.

**Comment by jxm2004** [comment]
The PR was made to fix a bug I noticed in that one function, which happened to a few others as well. In a nutshell the bug was that the wrong view controller was being returned for displaying the alert due to it not being nil but not being presented. This happened in the case of selecting an image to upload. Full details here: https://github.com/react-native-community/react-native-webview/issues/1325

I made the PR to be as simple as possible, just using what was already there, but correcting that one glaring error. Your case just seems to be special. I did not design anything in this library, I am just a user of it such as yourself 😄. The change you are proposing seems a bit drastic and honestly I am not sure what all the implications would be (for better or worse). I would try to come up with something a little less drastic if possible.

**Comment by cristianoccazinsp** [comment]
It may look drastic, but internally it is really using a very similar logic, but implemented by the react-native team instead.

Do you have any public URL to test the file picker case?  Logically, the behaviour seems right, I agree with that.  I guess that iOS' views used for modals are not supposed to include alerts (as they are already always at the top of the hierarchy), but I don't really know how one would fix both cases.

I wish the responsible of the recursive logic could shine some light here as to why it was done that way instead of using react's own helper methods :(

**Comment by jxm2004** [comment]
Yeah, I had to fork this repo and roll with my own solution for a while alas. Didn't really get any insight on the issue I raised. After 3 months of waiting I just made a PR and it was pretty quickly looked at and approved. If you feel you have a decent solution, maybe go down that route, or you can try to directly mention one of the main maintainers?

Don't have a simple direct one for testing alas. Any site with an image upload capability (that uses UIImagePickerController) should suffice though. Can then just hack it to call the alert (aka, image upload fail for whatever reason).

**Comment by cristianoccazinsp** [comment]
I have traced down the code updates to support alerts and all this recursive attempts to find the best suitable view controller to this: https://github.com/react-native-community/react-native-webview/pull/188/files

@Titozzz @npm-ued maybe you guys can comment on the possible caveats of using `RCTPresentedViewController()` instead of all this code? Considering this was done 2 years ago, a bunch of things have probably changed.

**Comment by cristianoccazinsp** [comment]
@jxm2004  I have just reproduced your alert crash if the && check is not used, so I see what you're talking about.

I have also tried using `RCTPresentedViewController()` and removed all the redundant recursive calls and the crash is gone, and also my own issue with the modal is gone... I don't know what else could be tried to make sure this change is appropriate, but would definitely make the code much more readable.

**Comment by Titozzz** [comment]
Tbh if you find a better way to do stuff that was done before I'll merge, do not worry. Usually for feature users need I just try to make sure it work before meeting, not that this is the definitive best way to do it.

**Comment by cristianoccazinsp** [comment]
@Titozzz I understand that, and that's precisely what I'm trying to fix right now; both the new crash that's affecting me due to a previous update, while also making sure fixing this crash does not bring back @Titozzz 's crash. 

I don't know how comprehensive are the automated tests, but everything seems to be working fine with the change, no crashes so far.
