### ISSUE TITLE
MIGRATED: Some of webpages are not properly scaled when startInLoadingState is set to true (#20616)

### ISSUE THREAD

**Issue by Titozzz** [react-native-community/react-native-webview#16]
Migrated from facebook/react-native#20616.

@kyo504 says: 

---

If startInLoadingState is set to true in WebView component, layout is broken for some web pages.

---

_More info in original thread_

**Comment by jamonholmgren** [comment]
This is confirmed on latest. PR's welcome! @kyo504 

![image](https://user-images.githubusercontent.com/1479215/48683083-4b72c280-eb60-11e8-9198-11725c3d0eb2.png)

**Comment by Ehesp** [comment]
Given the age of this issue, please could we have a reproducible issue on the latest RN & Webview versions. Closing, will re-open once this is confirmed.
