### ISSUE TITLE
Invariant Violation: requireNativeComponent: "RNCWKWebView" was not found in the UIManager

### ISSUE THREAD

**Issue by ChaeWonKong** [react-native-community/react-native-webview#161]
I am using react-native-cli
I installed react-native-webview with npm not yarn.
I linked react-native-webview by this following command:
`react-native link react-native-webview`

I got this message:
`rnpm-install info Linking react-native-webview ios dependency
rnpm-install info Platform 'ios' module react-native-webview has been successfully linked
rnpm-install info Linking react-native-webview android dependency
rnpm-install info Platform 'android' module react-native-webview has been successfully linked`

Yet whenever I run "react-native run-ios" command, I got error
RNCWKWebView not found in the UIManager.

**Comment by fernandomatheus** [comment]
Maybe the link process is not being completed correctly for some reason on iOS.
Have you tried to link manually?

Go to ../node_modules/react-native-webview/ios and drag and drop the RNCWebView.xcodeproj to Libraries folder on Xcode, right after, Go to Build Phases tab (on Xcode) in the section "Link binary With libraries" add the `libRNCWebView.a` (inside Libraries/RNCWebView.xcodeproj/Products). Try to build and run

**Comment by ChaeWonKong** [comment]
> Maybe the link process is not being completed correctly for some reason on iOS.
> Have you tried to link manually?
> 
> Go to ../node_modules/react-native-webview/ios and drag and drop the RNCWebView.xcodeproj to Libraries folder on Xcode, right after, Go to Build Phases tab (on Xcode) in the section "Link binary With libraries" add the `libRNCWebView.a` (inside Libraries/RNCWebView.xcodeproj/Products). Try to build and run

Libraries folder on Xcode means Xcode folder in node_modules in my project??

**Comment by ChaeWonKong** [comment]
I did it as I told, but still got the same error message..

**Comment by fernandomatheus** [comment]
The libraries folder is not from node_modules, is inside the root project folder, if you open Yourproject.xcodeproj/Yourproject.xcworkspace you will see this folder

**Comment by ChaeWonKong** [comment]
I did it as I told. Yet my build failed.

`Build system information

error: Cycle in dependencies between targets 'gourmet' and 'RNCWebView'; building could produce unreliable results.
Cycle path: gourmet → RNCWebView → gourmet
Cycle details:
→ Target 'gourmet' has target dependency on Target 'RNCWebView'
→ Target 'RNCWebView': Libtool /Users/ChaewonKong/Desktop/dev/ReactNative/gourmet/ios/build/Build/Products/Debug-iphonesimulator/libRNCWebView.a normal x86_64
○ Target 'RNCWebView': Libtool /Users/ChaewonKong/Desktop/dev/ReactNative/gourmet/ios/build/Build/Products/Debug-iphonesimulator/libRNCWebView.a normal x86_64



** BUILD FAILED **`

**Comment by lassikin** [comment]
For me the react-native link did not run "pod install" in the ios folder of the project.
The main page in all practicality needs some info on this in troubleshooting part.

And a manual install section, preferably.

so a fix was to run "pod install" in the ios folder manually. If you don't have pod installed and in your project already look for some guide about it. This should really be mentioned on the install instructions especially now that facebook is forwarding people to use this project.


(I used yarn for the install)

**Comment by Titozzz** [comment]
I'm currently writing an article on medium to explain iOS react-native linking. I'll probably add a link to it inside the docs

**Comment by Titozzz** [comment]
@ZouHanuku is this https://github.com/react-native-community/react-native-webview/issues/140?

**Comment by ZouHanuku** [comment]
I'm not using expo, I've used the link command (successful). Still got the error.

**Comment by Titozzz** [comment]
what about this comment: https://github.com/react-native-community/react-native-webview/issues/140#issuecomment-441046969

**Comment by ZouHanuku** [comment]
These are the changes that occured after the linking: 

settings.gradle:
`
include ':react-native-webview'
project(':react-native-webview').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-webview/android')
`

build.gradle:
` compile project(':react-native-webview')`

MainApplication.java:
`import com.reactnativecommunity.webview.RNCWebViewPackage;`

Podfile:
`  pod 'react-native-webview', :path => '../node_modules/react-native-webview'`

**Comment by Titozzz** [comment]
exactly.

you need to add new RNCWebViewPackage() as said in the linked comment

**Comment by ZouHanuku** [comment]
Thank you! It's working now ;)

**Comment by liemdo** [comment]
It doesn't work for me in iOS but it works fine in Android.

**Comment by jamonholmgren** [comment]
Here is @Titozzz 's really great article:

https://engineering.brigad.co/demystifying-react-native-modules-linking-ae6c017a6b4a

**Comment by henrymoulton** [comment]
@lfalkner Did you manage to solve this issue?

**Comment by masako-yamada** [comment]
`react-native link react-native-webview` didn't work for Android in my case. (react-native-webview version is 3.2.1)

I needed to add `RNCWebViewPackage` to MainApplication by hand: 

    protected List<ReactPackage> getPackages() {
        return Arrays.asList(
                ...,
                new RNCWebViewPackage(),
                ...
        );
    }

I don't use Expo and my React Native version is 0.57.8

**Comment by Titozzz** [comment]
I've updated https://github.com/react-native-community/react-native-webview/blob/master/docs/Getting-Started.md#2-link-native-dependencies

**Comment by afilp** [comment]
The problem still exists, I have linked the project in Android, etc.

Used to work, not it does not. Something changed, maybe the updated firebase?

**Comment by Domingowen** [comment]
> > Maybe the link process is not being completed correctly for some reason on iOS.
> > Have you tried to link manually?
> > Go to ../node_modules/react-native-webview/ios and drag and drop the RNCWebView.xcodeproj to Libraries folder on Xcode, right after, Go to Build Phases tab (on Xcode) in the section "Link binary With libraries" add the `libRNCWebView.a` (inside Libraries/RNCWebView.xcodeproj/Products). Try to build and run
> 
> it doesn't work
> 
> str:
> 
> react-native init AwesomeProject
> cd AwesomeProject
> 
> npm i --save react-native-navigation
> npm i --save react-native-webview
> 
> react-native link
> 
> then manual linking according to your advice
> 
> then react-native run-ios
> 
> <img alt="screen shot 2019-01-29 at 17 28 37" width="389" src="https://user-images.githubusercontent.com/9949932/51919086-6a58c500-23eb-11e9-84d9-5468a497626c.png">
> 
> <img alt="screen shot 2019-01-29 at 17 28 27" width="749" src="https://user-images.githubusercontent.com/9949932/51919087-6a58c500-23eb-11e9-8248-8ad48c230dd5.png">
> 
> <img alt="screen shot 2019-01-29 at 17 28 05" width="739" src="https://user-images.githubusercontent.com/9949932/51919090-6af15b80-23eb-11e9-8d97-a04524f1b374.png">
> 
> <img alt="screen shot 2019-01-29 at 17 27 52" width="757" src="https://user-images.githubusercontent.com/9949932/51919093-6af15b80-23eb-11e9-9a84-772be96c9033.png">

you probably did not add it inside the MainApplication.java

import com.reactnativecommunity.webview.RNCWebViewPackage;

and add new RNCWebViewPackage() to the packages list.

This often fail if you change MainApplication too much (using wix native navigation for example)
this is other person answer

**Comment by gberg1** [comment]
Hi I'm having the same issue on iOS used npm to install react-native-webview and did the link command as well. I see what people are talking about in terms of dragging the node_modules/react-native-webview/RCNWebView.xcodeproj to the Libraries folder in XCode and then Go to Build Phases tab (on Xcode) in the section "Link binary With libraries" add the `libRNCWebView.a` (inside Libraries/RNCWebView.xcodeproj/Products). Try to build and run.

Wondering if that worked to fix the issue as mentioned above before I run that and potentially mess up my environment more. Can i get clarification please? This is for ios.

**Comment by gberg1** [comment]
Doing a manual pod install after linking the react-native-webview worked for me. i did run into this issue after running pod install though. resolved it with the top suggestion in the SO. https://stackoverflow.com/questions/50805753/duplicate-module-name-react-native

**Comment by gabrielhpugliese** [comment]
Does this still work on RN 0.59.x? I'm creating a project from scratch and facing this issue.

**Comment by Titozzz** [comment]
Everything should be working fine.

**Comment by anoopmk007** [comment]
```
cd ios
rm -rf Pods
pod install
```
This helped me from nvariant Violation: requireNativeComponent: "RNCWKWebView" was not found in the UIManager

**Comment by kingdavidmartins** [comment]
Thanks! @anoopmk007 

Fixed

**Comment by LyovOrlov** [comment]
Thanks! @anoopmk007 !!!
Fixed

**Comment by tkserver** [comment]
I don't use pod install. What do I do?

**Comment by Subway19** [comment]
+1 We don't use pod. What should we do?

**Comment by wafuwafu13** [comment]
expo install react-native-webview  

I can fix.

**Comment by luatnd** [comment]
You need to check if react-native-webview/ios folder contain RNCWKWebView file or with other name?
If other name then you need to use older version that has that file name inside ios folder.
I believe this is a bug of react-native-webview.
I also try to use v8.x, v7.x, there was error too...
So I comeback with v5.12, that has RNCUIWebView in my case.
