### ISSUE TITLE
Redirect not working

### ISSUE THREAD

**Issue by Nitro1231** [react-native-community/react-native-webview#1612]
I cannot redirect to the main page after google login. And one thing that I noticed is that the webview is actually navigating twice every time.

Although it has the redirect uri,
![image](https://user-images.githubusercontent.com/32705910/92144787-2d1fa900-ee52-11ea-9f1d-1d9d01d10311.png)

my webview just stays at "One moment please..." forever.
![image](https://user-images.githubusercontent.com/32705910/92144658-fba6dd80-ee51-11ea-983c-ced5b62eb26f.png)

As you can see, onNavigationStateChange shows duplicated navigation.
![image](https://user-images.githubusercontent.com/32705910/92144387-9a7f0a00-ee51-11ea-9981-28ea16b46b55.png)

It seems like the same things as before (https://github.com/facebook/react-native/issues/9201)
How can I fix that?

**Environment:**
 - OS:
 - OS version:
 - react-native version:
 - react-native-webview version:

**Comment by alimot22** [comment]
I have the same issue. I'm trying to use gapi for youtube API. but, it's stay at "one moment please"

**Comment by Nitro1231** [comment]
Good news for you, @alimot22.

`<GoogleLogin
        clientId={this.props.gData.id}
        buttonText={this.props.gData.text}
        onSuccess={this.props.getGoogleID}
        onFailure={this.props.getGoogleID}
        cookiePolicy={this.props.gData.cookiePolicy}
        **isSignedIn={true}
        uxMode='redirect'**
      />`

Try this code for your gapi.

I think the webview has some issues with a popup. So you have to change the UX mode to "redirect" to get out of the "one moment please" loop. After that, you will encounter another issue with the react-google-login module: it will not trigger the callback function (or onSuccess function) after redirect from the login page. Then you have to add "isSignedIn={true}" to make your google-login module trigger the callback function every time when your pages load.

**Comment by trithien98** [comment]
Hi @Nitro1231  , i facing this issue like you . i currently login facebook and google in embed webview . my code is 
`   <WebView
          javaScriptEnabled={true}
          originWhitelist={['*']}
          onMessage={(e) => getMessage(e)}
          userAgent="Mozilla/5.0 (Linux; Android 9; LG-H870 Build/PKQ1.190522.001) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/83.0.4103.106 Mobile Safari/537.36"
          useWebKit
          bounces={true}
          allowsInlineMediaPlayback={true}
          mediaPlaybackRequiresUserAction={false}
          source={{
            uri,
          }}
          ref={webview}
          style={styles.webView}
          onNavigationStateChange={handleNavigationChange}
          mixedContentMode="always"
          allowsFullscreenVideo={true}
          allowFileAccessFromFileURLs={true}
          allowingReadAccessToURL={true}
          allowsBackForwardNavigationGestures={true}
          allowUniversalAccessFromFileURLs={true}
          domStorageEnabled={true}
          setSupportMultipleWindows={true}
          javaScriptCanOpenWindowsAutomatically={true}
          thirdPartyCookiesEnabled={true}
          allowFileAccess={true}
        />`
        I try to login 2 platform is facebook and google the screen like you . i had adding the userAgent but not work .  https://prnt.sc/1hiqtxy . https://prnt.sc/1hird9f .Shoud i install some package like GoogleLogin or FacebookLogin to solves this problem .
