### ISSUE TITLE
Google Auth not working (disallowed user agent)

### ISSUE THREAD

**Issue by rifrayugo** [react-native-community/react-native-webview#162]
Hi,
i have a promblem todo google authentication using webview in android.
  React Native Environment Info:
    React Native Version: 0.57.4
    System:
      OS: Windows 10
      CPU: (8) x64 Intel(R) Xeon(R) CPU E5-1620 v4 @ 3.50GHz
      Memory: 21.29 GB / 31.91 GB
    Binaries:
      Yarn: 1.9.4 - C:\Users\Administrator\AppData\Roaming\npm\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs.
Setop reproduce:
1. create-create it <project-name)
2. open peoject whhich have google authentication in the website
3. embbed the url to open webview.
4. try to login using google authentication

![image](https://user-images.githubusercontent.com/17063809/48824954-7b0c0f80-ed98-11e8-87ab-cfb081027c8c.png)

**Comment by jamonholmgren** [comment]
I'm not able to reproduce this:

<img width="357" alt="android emulator - pixel_api_26 5554 2018-12-21 13-49-04" src="https://user-images.githubusercontent.com/1479215/50364981-3dc9a780-0527-11e9-8636-dcf322199551.png">

<img width="443" alt="iphone x - 12 1 2018-12-21 13-42-42" src="https://user-images.githubusercontent.com/1479215/50364812-86cd2c00-0526-11e9-9d08-9db76fc92188.png">

Let me know if it continues ... thanks!

**Comment by montaserfzy** [comment]
the same issues

**Comment by YajanaRao** [comment]
I am facing the same issue link to expo https://snack.expo.io/@yajana/new-snack

**Comment by tamhv** [comment]
the same issue

```
react native 0.61.5
react-native-webview 8.0.2 
```

**Comment by alimot22** [comment]
I have fix this issue by adding this userAgent to WebView
`userAgent="Mozilla/5.0 (Linux; Android 4.1.1; Galaxy Nexus Build/JRO03C) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.166 Mobile Safari/535.19"`

**Comment by anastely** [comment]
@alimot22  it's work for me :), 
I used it to google_redirect mine endpoint after user sign-in i want to get his response like Email,name,....  
How can i handle it?

**Comment by rizkiandrianto** [comment]
> I have fix this issue by adding this userAgent to WebView
> `userAgent="Mozilla/5.0 (Linux; Android 4.1.1; Galaxy Nexus Build/JRO03C) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.166 Mobile Safari/535.19"`

Can we use real User agent?

**Comment by rayasrahiman** [comment]
> I have fix this issue by adding this userAgent to WebView
> 
> `userAgent="Mozilla/5.0 (Linux; Android 4.1.1; Galaxy Nexus Build/JRO03C) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.166 Mobile Safari/535.19"`

Hello there can you please share your code? I'm stuck since many days I have used expo cli and was trying to login through Google on ios it worked fine but Android I end up with this error 403 disallowed useragent

**Comment by Bernard996** [comment]
> I have fix this issue by adding this userAgent to WebView
> `userAgent="Mozilla/5.0 (Linux; Android 4.1.1; Galaxy Nexus Build/JRO03C) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.166 Mobile Safari/535.19"`

I tried it but when I insert my email I get the error:
"This browser or app may not be secure. Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in." How can I fix it?

**Comment by trithien98** [comment]
> > I have fix this issue by adding this userAgent to WebView
> > `userAgent="Mozilla/5.0 (Linux; Android 4.1.1; Galaxy Nexus Build/JRO03C) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.166 Mobile Safari/535.19"`
> 
> I tried it but when I insert my email I get the error:
> "This browser or app may not be secure. Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in." How can I fix it?

try remove Mobile inside userAgent

**Comment by ali27001** [comment]
userAgent="Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; AS; rv:11.0) like Gecko" 
 added it is working but  Email alerts that they're logged in with a Windows device. This is a problem for users. They may think that their passwords have been stolen because they feel like they are using different devices (ios).

what to do in this situation?

**Comment by wjlee2020** [comment]
> 

couldn't you just do a quick ternary inside the userAgent property? 
`userAgent={Platform.OS === 'android' ? 'Chrome/18.0.1025.133 Mobile Safari/535.19' : 'AppleWebKit/602.1.50 (KHTML, like Gecko) CriOS/56.0.2924.75'}`

**Comment by anniewey** [comment]
Anyone knows how to login into google from Google Docs form? I've added the user agent using `DeviceInfo.getUserAgent()` but still doesn't work in my case. The login doesn't sync.

**My use case:**
1. Open google doc url in webview
2. Click 'sign in to google'
3. App open third party browser and loaded the google doc url (but already sign in)

**Comment by justin-crocus** [comment]
> > 
> 
> couldn't you just do a quick ternary inside the userAgent property? `userAgent={Platform.OS === 'android' ? 'Chrome/18.0.1025.133 Mobile Safari/535.19' : 'AppleWebKit/602.1.50 (KHTML, like Gecko) CriOS/56.0.2924.75'}`

Does anyone know why userAgent from `DeviceInfo.getUserAgent()` doesn't work but this works?

**Comment by wjlee2020** [comment]
> 

i'm not sure if it's related (not sure if I understood your question), but if it's the case of the webview opening up other windows, you could try setting the `setSupportMultipleWindows` prop on the `Webview` to `false`. This will prevent the webview trying to open other windows.

**Comment by wjlee2020** [comment]
> Anyone knows how to login into google from Google Docs form? I've added the user agent using `DeviceInfo.getUserAgent()` but still doesn't work in my case. The login doesn't sync.
> 
> **My use case:**
> 
> 1. Open google doc url in webview
> 2. Click 'sign in to google'
> 3. App open browser app (chrome) and loaded the google doc url (but already sign in)

i'm not sure if it's related (not sure if I understood your question), but if it's the case of the webview opening up other windows, you could try setting the setSupportMultipleWindows prop on the Webview to false. This will prevent the webview trying to open other windows.

**Comment by SabaPablo** [comment]
> > couldn't you just do a quick ternary inside the userAgent property? `userAgent={Platform.OS === 'android' ? 'Chrome/18.0.1025.133 Mobile Safari/535.19' : 'AppleWebKit/602.1.50 (KHTML, like Gecko) CriOS/56.0.2924.75'}`
> 
> Does anyone know why userAgent from `DeviceInfo.getUserAgent()` doesn't work but this works?

I have the same problem.
I saw that getUserAgent() give `Mozilla/5.0 (Linux; Android 13; SM-A525M Build/TP1A.220624.014; wv) ..........`
the last word in braquets (wv) made that google disallow our user agent.

**Comment by pehjos** [comment]
> > 
> 
> couldn't you just do a quick ternary inside the userAgent property? `userAgent={Platform.OS === 'android' ? 'Chrome/18.0.1025.133 Mobile Safari/535.19' : 'AppleWebKit/602.1.50 (KHTML, like Gecko) CriOS/56.0.2924.75'}`

supper this works perfectly for both ios and android

**Comment by adammartiska** [comment]
I tried setting user agent as you did: 
`        userAgent={
          Platform.OS === "android"
            ? "Chrome/18.0.1025.133 Mobile Safari/535.19"
            : "AppleWebKit/602.1.50 (KHTML, like Gecko) CriOS/56.0.2924.75"
        }`
and it seems to be **working** on iOS Simulator, **but** when I try this from real device it still acts as native device, does anyone know where might be the problem?

**Comment by kundanthe** [comment]
> > 
> 
> couldn't you just do a quick ternary inside the userAgent property? `userAgent={Platform.OS === 'android' ? 'Chrome/18.0.1025.133 Mobile Safari/535.19' : 'AppleWebKit/602.1.50 (KHTML, like Gecko) CriOS/56.0.2924.75'}`

Its working on Android and IOS Device..

**Comment by sarthakpranesh** [comment]
> > 
> 
> couldn't you just do a quick ternary inside the userAgent property? `userAgent={Platform.OS === 'android' ? 'Chrome/18.0.1025.133 Mobile Safari/535.19' : 'AppleWebKit/602.1.50 (KHTML, like Gecko) CriOS/56.0.2924.75'}`


Has someone released an app using this or similar approach to Google Playstore for Google OAuth. I am thinking of using this solution in a production app but not very confident if Google Playstore team would approve such a solution.

**Comment by wjlee2020** [comment]
> > > 
> > 
> > 
> > couldn't you just do a quick ternary inside the userAgent property? `userAgent={Platform.OS === 'android' ? 'Chrome/18.0.1025.133 Mobile Safari/535.19' : 'AppleWebKit/602.1.50 (KHTML, like Gecko) CriOS/56.0.2924.75'}`
> 
> Has someone released an app using this or similar approach to Google Playstore for Google OAuth. I am thinking of using this solution in a production app but not very confident if Google Playstore team would approve such a solution.

Tho it was a few years ago, my team and I had no issues deploying this. Also, app stores usually just checks whether or not the app runs and other things like account handling (if it has users at all).

**Comment by raahimkhan** [comment]
Facing same issue. Any solutions?

**Comment by kundanthe** [comment]
> > > 
> > 
> > 
> > couldn't you just do a quick ternary inside the userAgent property? `userAgent={Platform.OS === 'android' ? 'Chrome/18.0.1025.133 Mobile Safari/535.19' : 'AppleWebKit/602.1.50 (KHTML, like Gecko) CriOS/56.0.2924.75'}`
> 
> Has someone released an app using this or similar approach to Google Playstore for Google OAuth. I am thinking of using this solution in a production app but not very confident if Google Playstore team would approve such a solution.

Yes, it will work in some app we had used it and app are published on both store..

**Comment by raahimkhan** [comment]
> > > > 
> 
> > > 
> 
> > > 
> 
> > > couldn't you just do a quick ternary inside the userAgent property? `userAgent={Platform.OS === 'android' ? 'Chrome/18.0.1025.133 Mobile Safari/535.19' : 'AppleWebKit/602.1.50 (KHTML, like Gecko) CriOS/56.0.2924.75'}`
> 
> > 
> 
> > Has someone released an app using this or similar approach to Google Playstore for Google OAuth. I am thinking of using this solution in a production app but not very confident if Google Playstore team would approve such a solution.
> 
> 
> 
> Yes, it will work in some app we had used it and app are published on both store..

Not working now. Tried this already.

**Comment by technoch1ef** [comment]
Setting the user agent helped, but now the website keep requesting captcha. Is there some other workaround for this?
