### ISSUE TITLE
After latest update WebView does throws error with onShouldStartLoadingWithRequest

### ISSUE THREAD

**Issue by randomco** [react-native-community/react-native-webview#1642]
Hi, I just updated to latest version of WebView (10.9.0) and I have been getting the following error everytime the WebView navigates to a new page:
Invariant Violation: Method onShouldStartLoadWithRequest does not exist on module WebViewMessageHandler4
I get the error whether or not I actually use the onShouldStartLoadWithRequest property. I am on latest version of react native (0.63.2)

**Comment by MossP** [comment]
File an error. Find the fix. Close the ticket.. Care to share your fix for everyone else?

**Comment by karthikpala** [comment]
@randomco  - I am also facing a similar issue, can you please share your resolution?

**Comment by MossP** [comment]
I'm still paying with this but it seems that it started at v10.8.3 rather than 10.9.0? Does that match with what you see @karthikpala ?

**Comment by randomco** [comment]
I went back to 10.3.3, no error.

**Comment by LionelHoudelier** [comment]
Hi all,
I fixed the problem in settings.gradle: there was 2 times the statement
`include ':react-native-webview'
project(':react-native-webview').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-webview/android')`
Since delete of one, i have no error.

**Comment by ombogdan** [comment]
same problem

**Comment by timothybowers** [comment]
same problem - and none of the above solution did anything to fix it.
