### ISSUE TITLE
Migrate Repository to Typescript

### ISSUE THREAD

**Issue by Titozzz** [react-native-community/react-native-webview#168]
We want to migrate the webview from flow to typescript.
This will allow easier maintaining as more and more people are now using VSCode.

Ideally we want to generate flow types from ts to allow people using flow a good experience.

@bruteforcecat @ccorcos

**Comment by bruteforcecat** [comment]
did u already start setting up typescript for it @ccorcos ?
If no, I could try this weekend

**Comment by ccorcos** [comment]
I can migrate the code to typescript if you guys can set things up. I tried setting it up with typescript, but what stopped me is that I don't know how to deal with the `.ios.js` and `.android.js` file endings in typescript. It can't resolve the types to two files at the same time...

**Comment by jamonholmgren** [comment]
@ccorcos I believe you can load them as straight JavaScript and not try to TypeScriptify them, right?

**Comment by Titozzz** [comment]
It's fine, I'm on it
