### ISSUE TITLE
android build failed with task :react-native-webview:compileDebugJavaWithJavac

### ISSUE THREAD

**Issue by FaiChou** [react-native-community/react-native-webview#174]
what I have done:

```
$ yarn add react-native-webview
$ react-native link react-native-webview
```

In android-studio after sync then I make project  failed:

```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':react-native-webview:compileDebugJavaWithJavac'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
```

- I have cleaned project
- I have removed ~/.gradle/caches
- I have removed project .gradle folder

```
    compileSdkVersion 27
    buildToolsVersion "27.0.3"
```

**Comment by FaiChou** [comment]
![image](https://user-images.githubusercontent.com/18500846/49131186-288b9f80-f312-11e8-9ad7-c882bcd69300.png)

**Comment by Titozzz** [comment]
What is your react native and Android studio version ?

**Comment by wjwarren** [comment]
@FaiChou Do you use [Jetpack and/or AndroidX](https://developer.android.com/jetpack/androidx/)? If so, that's what is causing your errors. (It was for me anyway.)

**Comment by FaiChou** [comment]
@Titozzz 

Here's the environment

```
Environment:
  OS: macOS 10.14.1
  Node: 11.2.0
  Yarn: 1.7.0
  npm: 6.4.1
  Watchman: 4.9.0
  Xcode: Xcode 10.1 Build version 10B61
  Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4
```

I fixed it by removing the `annotation` in `/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewModule.java` : 

```
-import android.support.annotation.RequiresApi;
+// import android.support.annotation.RequiresApi;

-  @RequiresApi(api = Build.VERSION_CODES.LOLLIPOP)
+//   @RequiresApi(api = Build.VERSION_CODES.LOLLIPOP)
```

**Comment by FaiChou** [comment]
My demo project can build success, and I diff them, there are a little difference in `app.iml`.

In project's` app.iml` which failed built contains `support-annotations:23`, but in demo's contains `support-annotations:27`.

**Comment by Titozzz** [comment]
The minimum supported version for the webview is react-native 0.57, your gradle files are probably messing with the webview config. You can edit the code to get it to work, but I won't have time to help @FaiChou

**Comment by Titozzz** [comment]
Please link your gradle file if you want me to take a (quick) look

**Comment by FaiChou** [comment]
here is my fork commit https://github.com/FaiChou/react-native-webview/commit/0c98b1acd6524bf0853f5600efd7ab6735772d77

**Comment by Titozzz** [comment]
Not really, before 0.57 most people import WebView from react-native directly.
Not supporting versions below has several advantages.

Any reasons you can't update to 0.57 that would justify this package to work on lower versions?

**Comment by Joao-Leite** [comment]
Hi,

Im having the same problem running on react 0,57,1. after ejecting from expo

"....
 None of the following functions can be called with the arguments supplied:
protected/*protected and package*/ constructor Event<T : Event<(raw) Event<*>>!>() defined in com.facebook.react.uimanager.events.Event
protected/*protected and package*/ constructor Event<T : Event<(raw) Event<*>>!>(p0: Int, p1: Long) defined in com.facebook.react.uimanager.events.Event


* What went wrong:
Execution failed for task ':react-native-webview:compileDebugKotlin'
"
