### ISSUE TITLE
Use AndroidX instead of Support Library

### ISSUE THREAD

**Issue by wjwarren** [react-native-community/react-native-webview#176]
AndroidX will replace the Support Libraries.

> AndroidX is the open-source project that the Android team uses to develop, test, package, version and release libraries within Jetpack.
>
> AndroidX is a major improvement to the original Android Support Library. Like the Support Library, AndroidX ships separately from the Android OS and provides backwards-compatibility across Android releases. AndroidX fully replaces the Support Library by providing feature parity and new libraries.

See: https://developer.android.com/jetpack/androidx/

**Comment by Titozzz** [comment]
This is cool !

**Comment by Ehesp** [comment]
We'll look into this feature request once React Native lands support Android X. Thanks, will close for now due to the volume of open issues.
