### ISSUE TITLE
Android-Studio: ReactBuildConfig.DEBUG = false when debug, disallowing debugging

### ISSUE THREAD

**Issue by ccorcos** [react-native-community/react-native-webview#180]
I'm not about to inpsect the webview from chrome://inspect on Android. Any ideas?

**Comment by ccorcos** [comment]
I see this in Android Studio, but there are errors all over the place so its hard to debug.

```java
    if (ReactBuildConfig.DEBUG && Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
      WebView.setWebContentsDebuggingEnabled(true);
    }
```

**Comment by ccorcos** [comment]
Well it turns out `ReactBuildConfig.DEBUG` is false.... Any ideas how to make that true when I press play in Android Studio?

**Comment by Titozzz** [comment]
you should not go to chrome://inspect, but to remote devices.

We have a guide to explain all this: https://github.com/react-native-community/react-native-webview/blob/master/docs/Debugging.md

**Comment by ccorcos** [comment]
It explains `WebView.setWebContentsDebuggingEnabled(true);` but it doesn't explain how to configure android studio to build the app with `ReactBuildConfig.DEBUG = true`.

**Comment by Titozzz** [comment]
I did not need to change anything else.
Don't you see your device with Chrome remote devices?

**Comment by ccorcos** [comment]
If you run from Android Studio (not `react-native start`) then`ReactBuildConfig.DEBUG = false`

**Comment by jamonholmgren** [comment]
Did you figure this out @ccorcos ?

**Comment by ccorcos** [comment]
Nope

**Comment by JeremyColton** [comment]
Has anyone worked out how to set 'ReactBuildConfig.DEBUG' to true? I also need to set this via Expo.
