### ISSUE TITLE
UIWebView get covered with keyboard on iphone6/ios12.1

### ISSUE THREAD

**Issue by mmaschenko** [react-native-community/react-native-webview#183]
For some reason UIWebview gets messed up specifically on ios 12.1 after update. I have webview with textinput in bottom, and it's getting covered with keyboard. If i use WKWebView textinput is put too much away from keyboard and can be fixed with this code, but it's a bad solution in general

[UIView animateWithDuration:0 animations:^{
      self.webView.scrollView.contentOffset = CGPointMake(0, 0);
  }];

**Comment by jamonholmgren** [comment]
We're tracking this problem in #193 now -- closing in favor of that.

https://github.com/react-native-community/react-native-webview/issues/193#issuecomment-447513485
