### ISSUE TITLE
onShouldStartLoadWithRequest don't work on Android

### ISSUE THREAD

**Issue by suiyunpiaoliu** [react-native-community/react-native-webview#185]
onShouldStartLoadWithRequest don't work on Android when the first url load -- v2.14.0

**Comment by Titozzz** [comment]
Yeah this was document in the pull request.
I agree that we need to find a way to match iOS functionality, but it's going to bit a bit tricky probably @maxammann

**Comment by maxammann** [comment]
Will think about how we could do it.

I think we maybe should not allow to cancel the first load. Not sure what to display instead of the actual content.

**Comment by daoan1412** [comment]
I think that we can use shouldInterceptRequest instead shouldOverrideUrlLoading.

**Comment by daoan1412** [comment]
I try use shouldInterceptRequest to block advertisement host on android native and it work. 
```Java
 mWebView.setWebViewClient(new WebViewClient() {
            @Override
            public boolean shouldOverrideUrlLoading(WebView view, String url) {

                view.loadUrl(url);
                return true;
            }

            @Override
            public WebResourceResponse shouldInterceptRequest(final WebView view, String url) {
                if (adsHostList.contains(url)) {
                    return createEmptyResource();
                } else {
                    return null;
                }
            }

            public WebResourceResponse createEmptyResource() {
                return new WebResourceResponse("text/plain", "utf-8", new ByteArrayInputStream("".getBytes()));
            }
        });
