### ISSUE TITLE
I hope listening to the loading fail （500 or 404 or 401 ）

### ISSUE THREAD

**Issue by cuibeihong** [react-native-community/react-native-webview#189]
My current plan ：（iOS）
add WKNavigationDelegate in RNCWKWebView.m

- (void)webView:(WKWebView *)webView decidePolicyForNavigationResponse:(WKNavigationResponse *)navigationResponse decisionHandler:(void (^)(WKNavigationResponsePolicy))decisionHandler{
  if ([navigationResponse.response isKindOfClass:[NSHTTPURLResponse class]]) {
    
    NSHTTPURLResponse * response = (NSHTTPURLResponse *)navigationResponse.response;
    if (response.statusCode == 401 || response.statusCode == 500 || response.statusCode == 404) {
      if (_onLoadingError) {
        NSMutableDictionary<NSString *, id> *event = [self baseEvent];
        [event addEntriesFromDictionary:@{
                                          @"didFailProvisionalNavigation": @YES,
                                          @"code": @(response.statusCode),
                                          }];
        _onLoadingError(event);
      }
    }
  }
  decisionHandler(WKNavigationResponsePolicyAllow);
}

Is there a better way to do it？

**Comment by TheAlmightyBob** [comment]
Have you tried this code already? I _think_ that the call to `decisionHandler(WKNavigationResponsePolicyAllow)` will allow the page (e.g. the 404 error page) to successfully load and thus reset the `react-native-webview` error state. So if your app is using something like `renderError` then you might see your own error screen quickly appear and disappear.

(but if your app is just handling `onError` as a one-time notification to go spin off some other logic, not caring when the error state gets cleared, then this might be fine)

Also note that this won't just fire for the top-level page. If the main page you're loading succeeds but then has an embedded resource that gets a 404, you'll get the same error. (again depending on your scenario that may not be a problem)
