### ISSUE TITLE
Is it possible to open a browser like Chrome or Safari by javascript 'window.open'?

### ISSUE THREAD

**Issue by JinHoSo** [react-native-community/react-native-webview#190]
Hi,
Is it possible to open a browser like Chrome or Safari by javascript 'window.open'?

**Comment by shukerullah** [comment]
`window.open` is working when `useWebKit` is set to false.

Here is example:
```
<WebView
  source={{
    html: `
    <!DOCTYPE html>
    <html>
      <body>
        <p>Click the button to open a new browser window.</p>
        <button onclick="myFunction()">Try it</button>
        <script>
          function myFunction() {
            window.open("https://www.w3schools.com");
          }
        </script>
      </body>
    </html>
    `
  }}
  ref={ref => {
    this.webView = ref;
  }}
  useWebKit={false}
  onNavigationStateChange={event => {
    if (event.url.startsWith("http")) {
      this.webView.stopLoading();
      this.webView.goBack();
      openURL(event.url);
    }
  }}
/>
```

**Comment by maamounapprise** [comment]
is there an actual solution? The script above doesn't open a safari view.

**Comment by Titozzz** [comment]
You can send a message to react-native and use Linking module to do that if you want

**Comment by elirangoshen** [comment]
i need this feature as well as some 3rd party service open it automatically.. 
in android there is 2 props related  in webview settings : 
setJavaScriptCanOpenWindowsAutomatically
and 
setSupportMultipleWindows

after it should support window.open, if it works, can i open PR for that ?

**Comment by bova80** [comment]
> i need this feature as well as some 3rd party service open it automatically..
> in android there is 2 props related in webview settings :
> setJavaScriptCanOpenWindowsAutomatically
> and
> setSupportMultipleWindows
> 
> after it should support window.open, if it works, can i open PR for that ?

was this support added?  how can one do this?
