### ISSUE TITLE
iOS 12 Keyboard dismiss, viewport shifted

### ISSUE THREAD

**Issue by fbacker** [react-native-community/react-native-webview#193]
I'm experience the same issue as this post. https://github.com/apache/cordova-ios/issues/417#issuecomment-431296703

Example.
I fill a login form with values. Close the keyboard (not clicking keyboard submit button). 
Then clicking on the actual login button. Then the hitareas are offset and I will hit another button.

**Comment by smathson** [comment]
Correct, this is a known bug in WKWebView on iOS 12. https://openradar.appspot.com/radar?id=5018321736957952

**Comment by jamonholmgren** [comment]
This issue was originally fixed in #134 (and deployed in 2.8.0) but we reverted it in #210 (available in 2.14.3) because of #201.

If someone wants to take a stab at fixing this issue again, you can use #134 as a base, but figure out how to not break #201 again.

**Comment by jamonholmgren** [comment]
cc @iamtommcc and @ryanlntn

**Comment by cem2ran** [comment]
A temporary fix/hack worth mentioning in case others run into this problem:
https://github.com/apache/cordova-ios/issues/417#issuecomment-467690772

Question is if this temporary fix should be shipped with `react-native-webview` until it's fixed natively or at least documented? @jamonholmgren

**Comment by jamonholmgren** [comment]
@cem2ran This should be fixed in #296.

**Comment by cem2ran** [comment]
@jamonholmgren That's great! Is there a reason why this issue is still open then?

**Comment by Titozzz** [comment]
Nope

**Comment by MichaelIT** [comment]
I make a patch for it.https://github.com/MichaelIT/patch-ios12-webview-keyboard
```
npm add patch-ios12-webview-keyboard --save
import 'patch-ios12-webview-keyboard'
```

**Comment by linxianxi** [comment]
Again, there will be a white part at the bottom.
<img width="370" alt="image" src="https://user-images.githubusercontent.com/47104575/175482204-801385be-8614-452c-a5ed-e65721c4b585.png">
