### ISSUE TITLE
White Screen when loading content

### ISSUE THREAD

**Issue by oliverdolgener** [react-native-community/react-native-webview#194]
I've noticed an annoying bug when loading html content. There was an issue in the RN Core WebView.
I could solve this problem using the `overflow: 'hidden'` trick but I thought this could be fixed internally.

https://github.com/facebook/react-native/issues/21939

**Comment by Titozzz** [comment]
I agree with you 100% on this. I've found the hidden fix but not proud of it 😛

**Comment by enahum** [comment]
With the latest version of react-native-webview and RN 0.58.4 and even after wrapping the WebView in an `overflow: 'hidden'` I still get a white screen attempting to load an url. it works fine in iOS with and without the overflow trick.

I falled back to the WebView component of RN only for Android for the time being. Sadly I do not know much about Android to try and fix this myself and submit a PR, but will look at this thread closely.

Let me know if you have any other ideas.

**Comment by Titozzz** [comment]
If your bug was due to overflow, you would also need it with the core webview so your issue lies somewhere else

**Comment by enahum** [comment]
Well it is working with the core webview, so I guess there is something weird going on with the library then?

here is the code that displays the webview https://github.com/mattermost/mattermost-mobile/blob/release-1.16/app/screens/sso/sso.js and I must say that release is using `react-native-webview@2.5.0` and `react-native@0.57.4` and was working just fine.

**Comment by Titozzz** [comment]
No error messages in logcat or anything?

**Comment by enahum** [comment]
Nothing in logcat...  I reverted back to use `2.5.0` and is working again.. will look into it further and I'll report back if I find something

**Comment by dylancompanjen** [comment]
This issue still exists. Switched back to WebView from RN for the time being.

**Comment by socca1157** [comment]
This issue should not be closed, it's still very much an active issue. Closing it is disingenuous.
