### ISSUE TITLE
Drop support for UIWebView

### ISSUE THREAD

**Issue by jamonholmgren** [react-native-community/react-native-webview#2]
@Titozzz asked me if we could drop support for UIWebView in this package, and I had already [mentioned this](https://github.com/react-native-community/discussions-and-proposals/pull/3#issuecomment-419610408) in the RFC. When testing this package, there are several issues with UIWebView, so it makes sense to drop support for it.

My proposal is to leave UIWebView in (for now) but not put engineering time into it, and in a few versions drop support for UIWebView entirely.

**Comment by jamonholmgren** [comment]
This package now uses WKWebView by default instead of UIWebView (per #3). I'll leave this issue open, as we'll want to fully drop support for UIWebView at some point.

**Comment by Titozzz** [comment]
Great 🎉

**Comment by Titozzz** [comment]
Dup of #312
