### ISSUE TITLE
WKWebView stays in loading state with injectedJavaScript 

### ISSUE THREAD

**Issue by stammbach** [react-native-community/react-native-webview#200]
Hello, I'm using the injectedJavaScript to inject custom CSS into my WebView to hide the default page header.

```
var rule = '.page-header { display: none !important; }';
var css = document.createElement('style');
css.type = 'text/css';
if(css.styleSheet) css.styleSheet.cssText = rule;
else css.appendChild(document.createTextNode(rule));
document.getElementsByTagName("head")[0].appendChild(css);
```
Combining that with the default useWebKit option and the WebView will stay in loading state.
The onLoadProgress event even returns progress: 1 which should be 100% if I'm assuming that correctly. I've already made sure the JS is working on Safari / WK. 

When switching back to the UIWebView everything works as expected.

**Comment by Titozzz** [comment]
please use debbugging to inspect the webview and see what's wrong with it

**Comment by stammbach** [comment]
@Titozzz thanks for the debugging information, thats actually really handy... but that just confirms what I already said. Nothing is loading anymore. No errors. I can even inspect my injected style tags in the head section. But the WebView component stays in loading state and renders my loading component. Disabling webkit and everything works as expected, just not as fast.

**Comment by Titozzz** [comment]
Ok, can you try using react-native own webview with useWebkit={true} to see if any change to this repo broke it ?

**Comment by jamonholmgren** [comment]
@stammbach You may have run into the same bug @ryanlntn ran into. Check out this PR which hasn't been merged yet: https://github.com/react-native-community/react-native-webview/pull/179

**Comment by stammbach** [comment]
@Titozzz @jamonholmgren yeah, it's exactly the same thing. Working without startInLoadingState or by adding 'true' at the end of my JS injection string. Thank you all for the quick help.

**Comment by jamonholmgren** [comment]
Glad to hear!
