### ISSUE TITLE
[Android] Persist cookies

### ISSUE THREAD

**Issue by tigo0** [react-native-community/react-native-webview#207]
Hey. Thanks for the great work.
If I am not missing anything, currently the cookies are not persisted on Android if we kill the app. This improvement seems to be available on iOS (I am using https://github.com/react-native-community/react-native-webview/pull/138), and would be great to have it for Android as well. As of now, any workarounds for this? Thanks.

**Comment by mpcen** [comment]
Experiencing the same. This is super broken

**Comment by jamonholmgren** [comment]
@tigo0 Thanks for reporting! We would love to have Android support as well but need someone to help implement it. Perhaps @mpcen would like to take a stab at it. ;)

**Comment by jamonholmgren** [comment]
Actually, @ifsnow said he has an Android implementation. So once that's pushed up we can test that as well.

**Comment by tigo0** [comment]
Thanks @jamonholmgren, sounds awesome. Looking forward to @ifsnow solution. Thanks

**Comment by cyb3rsalih** [comment]
Looking forward this feature!

**Comment by gorvinsky** [comment]
Hi, any progress on this feature? Because the cookies are still erased after the app is closed.

**Environment:**

- OS: Android
- react-native version: 0.59.5
- react-native-webview version: 5.7.0

**Comment by veermangat** [comment]
Facing the same issue. My observation has been that if I browser around a little bit on the webview then the webview remembers cookies when the app is killed and launched again.

**Comment by veermangat** [comment]
I use react-native-cookies to store cookies after a fetch call. And have set sharedCookiesEnabled on. 

This works on iOS but on android webview the user is logged out.

**Comment by jamonholmgren** [comment]
I ran a simple test and wasn't able to replicate:

Screencast: https://www.loom.com/share/422c73ec01354edc846608e9f09671a7

App.js:

```jsx
import React, { Component } from "react";
import { WebView } from "react-native-webview";

export default class App extends Component<Props> {
  render() {
    return <WebView source={{ uri: "https://review.discourse.org" }} />;
  }
}
```

Steps I took:

1. Loaded the app in a Pixel2 emulator
2. Logged into that discourse forum
3. Killed the app
4. Opened the app
5. Observed I was still logged in

Can you tell me how I might replicate this behavior?

React Native: 0.59.8
React Native WebView: 5.11.0
Android Pixel 2 API 28

**Comment by veermangat** [comment]
My scenario is slightly different, I am authenticating the user in the react-native part of the app using a fetch call and then loading the WebView.

Which now seems to be working. Sorry about the confusion. Will carry on testing the same. Might be specific to an android version or phone. 


```js
import CookieManager from 'react-native-cookies'

// Making a fetch call to authenticate the user and then storing the cookies using react-native-cookies

  const result = await fetch('my host', {
    method: 'POST',
    headers: {
      'Content-Type': 'multipart/form-data; charset=utf-8',
    },
    body: formData,
  })

  const data = await result.json()

  let cookies = result.headers.get('set-cookie')

  if (Platform.OS === 'ios') {
    cookies = { 'Set-Cookie': cookies }
  }
 
  await CookieManager.setFromResponse('my host', cookies)
```

```js
import { WebView } from 'react-native-webview'

// Session is valid in the webview, both on iOS and Android

<WebView
  source={{ uri: 'my host' }}
  thirdPartyCookiesEnabled
  sharedCookiesEnabled
/>
```

Does seem to work pretty well on iOS. And on the limited android devices and simulators I have tested on.

**Comment by roeycohen** [comment]
I believe this is happening only if you kill the app right after the cookie is set, before "Android cookie manager" gets the chance to flush cookies.

**Comment by mattdamon108** [comment]
I have the same issue as @roeycohen mentioned. If I close the app right after logging in from memory, the app got logged out after reopening the app. It seems to happen only I close the app right after logging in as fast as possible.

**Comment by roeycohen** [comment]
hi @mattdamon108, you might find CookieManager.flush() helpful for making sure the cookie is stored immediately:
https://github.com/react-native-cookies/cookies

**Comment by allan-simon** [comment]
@TheAlmightyBob  I don't know if you have the possibility to reopen this issue as it is still here

Also if it may help, my company is ready to sponsor the fix of this issue (through freelance work or other means)

**Comment by TheAlmightyBob** [comment]
@allan-simon I'm not familiar with this issue and it seems there are a couple different things discussed here over the years. I would recommend opening a new issue and providing a repro.
