### ISSUE TITLE
MIGRATED: unable to load local assets or from CDNs along with window.postMessage not working in iOS release build (#20226)

### ISSUE THREAD

**Issue by jamonholmgren** [react-native-community/react-native-webview#21]
Migrated from https://github.com/facebook/react-native/issues/20226.

@sja1n says:

---

Environment
React Native Environment Info:
System:
OS: macOS High Sierra 10.13.5
CPU: x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
Memory: 310.16 MB / 8.00 GB
Shell: 5.3 - /bin/zsh
Binaries:
Node: 8.11.1 - /usr/local/bin/node
Yarn: 1.5.1 - /usr/local/bin/yarn
npm: 5.6.0 - /usr/local/bin/npm
Watchman: 4.9.0 - /usr/local/bin/watchman
SDKs:
iOS SDK:
Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
Android SDK:
Build Tools: 26.0.3, 27.0.3
API Levels: 26, 27
IDEs:
Android Studio: 3.1 AI-173.4819257
Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
npmPackages:
react: 16.4.1 => 16.4.1
react-native: ^0.56.0 => 0.56.0
npmGlobalPackages:
create-react-native-app: 1.0.0
react-native-cli: 2.0.1

Description
I am using webview to display chart for my app using chartjs and jquery library I am able to view charts fine in iOS debug mode but in release config, all I get is a white screen, I tried to check if atleast window.postMessage was working using setinterval code in my .html file, but I dont get any response from webview.

To check for window.postMessage I have also tried to possible solution from issue , still its not working

I have tried to inject the complete html code as well instead of serving the html as local asset file, still not success.

This issue is only present in iOS, works perfectly fine for android.

---

**Comment by Skilltrades** [comment]
Any solution to this...I need to resolve this urgent, was working fine in react-native 0.48.0, upgraded to 0.57.8. Not webView content shows up in simulator but not in release mode..

**Comment by sja1n** [comment]
None of the solutions worked for me so I setup an endpoint from backend which return the same page with all cdn code and it worked fine.

**Comment by Salakar** [comment]
Hey all :wave: thanks for reporting this issue. Unfortunately, without a reproduction (a repo we can clone and see the unexpected behaviour) we're pretty limited in how we can help sorry. 

I'll go ahead and close this issue given that there's been no further activity for a few months. 

If you want this re-opened please let me know and help us out with a reproduction.
