### ISSUE TITLE
[iOS WKWebView] crash on iOS 9.x due to WKWebView bug where it tries to use scrollView.delegate while being deallocated. 

### ISSUE THREAD

**Issue by malonguwa** [react-native-community/react-native-webview#213]
@Titozzz @NeilChan 
This is a old issue for WKWebView happens in iOS 9, due to WKWebView bug where it tries to use scrollView.delegate while being deallocated. 

Crash log from iOS 9.x
- [WKScrollView _updateDelegate] + 229  <-- (try to use scrollView.delegate after WKWebView dealloc)
- | WebKit | -[WKWebView dealloc] + 267

I already see other people's solution for this issue by `scrollView.delegate = nil `

But in our RN webView's current WKWebView.m,

Should I do something like this to avoid the WKWebView bug in iOS 9.x ?

```
- (void)removeFromSuperview
{
    if (_webView) {
        _webView.scrollView.delegate = nil;
        _webView.UIDelegate = nil;
        _webView.navigationDelegate = nil;
        [_webView.configuration.userContentController removeScriptMessageHandlerForName:MessageHanderName];
        [_webView removeObserver:self forKeyPath:@"estimatedProgress"];
        [_webView removeFromSuperview];
        _webView = nil;
    }

    [super removeFromSuperview];
}

```

**Comment by Titozzz** [comment]
I know this issue is painful for you but please let's keep the focus in one thread #150 !

@NeilChan Can you have a look at this issue ?

**Comment by NeilChan** [comment]
@Titozzz OK. It's a webkit bug in iOS9. I will try to fix it and submit a PR later.

**Comment by Titozzz** [comment]
Thank you so much

**Comment by jerolimov** [comment]
@malonguwa @NeilChan I created PR #342 to fix this and another iOS 9 issue.

If would be also easy and great if you can test and verify my PR. You find some instructions to test my branch in your project in the PR #342. Thank you.
