### ISSUE TITLE
Accept headers

### ISSUE THREAD

**Issue by ed-sparkes** [react-native-community/react-native-webview#215]
Accept headers specified in source are being overwritten by the webview and therefore not being honored. I have an api which returns pdf documents and checks the accept header for application/pdf. Despite specifying the header in the source of the WebView it appears the header is being replaced before making to my api with the following values "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8" (id=80)" and my api is dimissing the request with a 406 Not allowed. Is it possible to either allow the headers specified in the source to honored in the request or update the override to include application/pdf given the webviewer supports the rendering of pdfs? 

Many thanks, Ed 

```jsx
  <WebView
    useWebKit={true}
    bounces={false}
    scrollEnabled={false}
    source={{
        uri: url,
        headers: {
            Accept: 'application/pdf',
            Authorization: 'Bearer ' + this.state.token
         }
    }} />
```

**Comment by mpcen** [comment]
I'm experiencing a similar issue but with cookies:

I'm specifying a cookie value but when I call get() to fetch my current cookies within onLoadStart, onLoad or onNavigationStateChange, the cookie differs from what I manually specified in source header.

**Comment by chaudhryjunaid** [comment]
@jamonholmgren any indication when the PR will get merged?

**Comment by davux** [comment]
Does this issue still exist in recent version?
