### ISSUE TITLE
postMessage works on emulator but not on phone

### ISSUE THREAD

**Issue by tapir** [react-native-community/react-native-webview#221]
```js
try {
	function whenRNPostMessageReady(cb) {
		if(postMessage.length === 1) {
			cb();
		} else {
			setTimeout(function() {
				whenRNPostMessageReady(cb);
			}, 1000);
		}
	}
	whenRNPostMessageReady(function() {
		window.parent.postMessage('test-data-as-string', '*');
	});
}
catch(err) {
	document.getElementById("errr").innerHTML = err.message;
}
```

Above is my script block in the page I'm viewing from webview which is defined as below:

```xml
<WebView
	ref = {(ref) => {this.webViewRef = ref;}}
	startInLoadingState = {true}
	scrollEnabled = {false}
	useWebKit = {true}
	onMessage = {(e) => console.warn(e.nativeEvent.data)}
	source = {{uri: 'http://my-page-url'}}
/>
```

Works perfectly in emulator but does not work nor gives any error on my One Plus 5T (Oreo)

Any ideas?

**Comment by Titozzz** [comment]
i'm not sure, I have a Oneplus 3T and everything is fine. Can you give me any more informations ?

**Comment by tapir** [comment]
Bad news, it's not only One Plus 5T. I've tried with Galaxy S8 and it's the same.
Here is the smallest possible reproducable file and screenshots of both OnePlus 5T, Galaxy S8 and Emulator. 
How can I better help debug this?
```js
import React, {Component} from 'react';
import {WebView} from 'react-native-webview';

const page = `
<html>
<head>
<script>
try {
	function whenRNPostMessageReady(cb) {
		if(postMessage.length === 1) {
			cb();
		} else {
			setTimeout(function() {
				whenRNPostMessageReady(cb);
			}, 1000);
		}
	}
	whenRNPostMessageReady(function() {
		window.parent.postMessage('test-data-as-string', '*');
	});
}
catch(err) {
	document.getElementById('errr').innerHTML = err.message;
}
</script>
</head>
<body>
	<div id='errr'>...</div>
</body>
</html>`;

type Props = {};
export default class App extends Component<Props> {
  render() {
    return (
		<WebView
			ref = {(ref) => {this.webViewRef = ref;}}
			startInLoadingState = {true}
			scrollEnabled = {false}
			useWebKit = {true}
			onMessage = {(e) => console.warn(e.nativeEvent.data)}
			source = {{html: page}}
		/>
    );
  }
}
```
![screenshot from 2019-01-02 14-01-52](https://user-images.githubusercontent.com/223984/50589434-a6097900-0e97-11e9-85af-ab2dfbdeca50.png)
![photo_2019-01-02_14-05-41](https://user-images.githubusercontent.com/223984/50589449-b91c4900-0e97-11e9-9998-32a69f6851d1.jpg)
![photo_2019-01-02_14-05-38](https://user-images.githubusercontent.com/223984/50589452-bc173980-0e97-11e9-8473-551380ad0a6d.jpg)

**Comment by Titozzz** [comment]
Can you try window.postMessage('test-data-as-string', '*'); ?

**Comment by tapir** [comment]
Already did. Doesn't work either.

**Comment by tapir** [comment]
Changed the example to window.postMessage as well to avoid confusion

**Comment by Titozzz** [comment]
I've been able to reproduce the issue with your code. But the thing is it's working perfectly fine inside my app and I do a lot of postMessage stuff. So I'm a bit confused.

Here's how I do: 

```
const injectedJavascript = `(function() {
  window.WebViewBridge = {
    onMessage: function() {
      return null;
    },
    send: function(data) {
      window.postMessage(data, '*');
    },
  };
  var event = new Event('WebViewBridge');
  window.dispatchEvent(event);
})()`;

const generateOnMessageFunction = data =>
  `(function() {
    window.WebViewBridge.onMessage(${JSON.stringify(data)});
  })()`;
```

Then to send to web (web is free to listen by overriding window.WebViewBridge.onMessage):
```
sendMessageToWebView = message => {
    this.webView.current.injectJavaScript(generateOnMessageFunction(message));
  };
```

And web can send stuff to native by:
```
window.WebViewBridge.send(message);
```

**Comment by tapir** [comment]
Unfortunately your example doesn't work for me at all. Not even in emulator. I've noticed you didn't the the workaround delay thing where RN-Webview bridge is not live yet. But even then it doesn't fire up a message for me. Here is how I've tried to run it.

```js
import React, {Component} from 'react';
import {WebView} from 'react-native-webview';

const page = `
<html>
<head>
<script>
	(function() {
		window.WebViewBridge = {
			onMessage: function() {
				return null;
			},
			send: function(data) {
				window.postMessage(data, '*');
			},
		};
		var event = new Event('WebViewBridge');
		window.dispatchEvent(event);
	})();
	document.addEventListener('DOMContentLoaded', function(event) {
		try {
			window.WebViewBridge.send('test-data');
		}
		catch(err) {
			document.getElementById('errr').innerHTML = err.message;
		}
	});
</script>
</head>
<body>
	<div id='errr'>...</div>
</body>
</html>`;

const js = `;`;

type Props = {};
export default class App extends Component<Props> {
  render() {
    return (
		<WebView
			onMessage = {(e) => console.warn(e.nativeEvent.data)}
			source = {{html: page}}
		/>
    );
  }
}
```

**Comment by tapir** [comment]
Had to use react-native-webview-bridge for now which is using an older version of WebView.

Hoping this gets fixed soon. Maybe a common working client side JS should be injected by default before everything else. Leaving this open. Let me know if you want me to test something.

**Comment by jamonholmgren** [comment]
@tapir I've replicated the problem using your steps as well. Made this a bug.

If anyone wants to tackle it, there's a good replication step posted above.

**Comment by Titozzz** [comment]
Well we are already working on postMessage implementation, as we now the current implementation is really bad. #104

**Comment by abendi** [comment]
Could it be that `if(postMessage.length === 1) { ... }` breaks on newer Chrome versions and that your real device and emulator have different Chrome versions?
see: https://github.com/facebook/react-native/issues/11594#issuecomment-436338661

**Comment by tapir** [comment]
> Could it be that `if(postMessage.length === 1) { ... }` breaks on newer Chrome versions and that your real device and emulator have different Chrome versions?
> see: [facebook/react-native#11594 (comment)](https://github.com/facebook/react-native/issues/11594#issuecomment-436338661)

tried with `postMessage.toString().includes('__REACT_WEB_VIEW_BRIDGE')` still doesn't work

**Comment by abendi** [comment]
You can also try. This always waits for 2 seconds after the page has loaded.
```
window.onload = function() { 
  setTimeout(function() {
    window.parent.postMessage('test-data-as-string', '*');
  }, 2000);
};
```

**Comment by tapir** [comment]
How does that help? Initial example waits as much as necessary. It's recursive.

**Comment by abendi** [comment]
They are not the same, because some Chrome versions might report `postMessage.length === 1` falsely. On those versions the callback in recursive example gets called immediately when in reality the postMessage bridge is not actually ready.
Last example waits a constant time and does not rely on versioning. Try it out to exclude that case.

**Comment by tapir** [comment]
Didn't work unfortunately

**Comment by tapir** [comment]
Is there a way to send message from RN to WebView though? I don't see it in the documentations

**Comment by tapir** [comment]
Works like a charm!

**Comment by koofka** [comment]
@tapir Any chance you could share your generateMessage function?  We are currently running into the same issue where it works perfectly in the simulator but not on the phone deploys.

**Comment by tapir** [comment]
@koofka I'm directly using the `window.ReactNativeWebview.postMessage(strData)` method. Nothing else. No timeouts nothing.
Are you sure you're on version 5.0.0? Also notice the small letter 'v' in 'Webview'. It's been wrongly documented as `window.ReactNativeWebView.postMessage` but later was fixed.

**Comment by koofka** [comment]
@tapir Yep we added those fixes, Im wondering about the other direction for messaging into the webview.  The only code that has worked for that so far for us has been :  
```
 generateOnMessageFunction = (action, payload) =>
    `(function() {
      var event = new CustomEvent('WebViewBridge', {detail: {
          action: ${JSON.stringify(action)},
          payload: ${JSON.stringify(payload)},
        }
      });
      window.dispatchEvent(event);
    })()`
`

```
and then a corresponding window listener in the webview

**Comment by tapir** [comment]
Ah sorry, I've used it like this in my app
```
sendToWebview(msg) {
	const { webview } = this.refs;
	webview.postMessage(msg)
};

<WebView
	ref = "webview" // you need this for above to work
	...
	...
	source = {{uri: this.uri}}/>
```

and like below in the html served by webview
```
			document.addEventListener('message', function (event) {
				// do your thing here with event.data
			});
```

**Comment by koofka** [comment]
interesting.  Thanks for the help will give it a shot.
