### ISSUE TITLE
Popups Do Not Appear in React Native WebView

### ISSUE THREAD

**Issue by Shivendra30** [react-native-community/react-native-webview#223]
I've seen multiple questions regarding this on StackOverflow but unfortunately, none of them have been solved.

In my case, I'm using PayuMoney inside a WebView to execute a transaction. Payumoney by default opens up a new window while processing a transaction which is not visible inside the react native's webview but is apparently visible in mobile browsers.

According to this answer - Enable Popups in React Native WebView, I added

```
// To enable these by default
WebSettings settings = webView.getSettings();
settings.setJavaScriptCanOpenWindowsAutomatically(true);
settings.setSupportMultipleWindows(true); 
And also this,

//To add these as valid props for the WebView Component
@ReactProp(name = "javaScriptCanOpenWindowsAutomatically")
  public void setJavaScriptCanOpenWindowsAutomatically(WebView view, boolean isCan) {
    view.getSettings().setJavaScriptCanOpenWindowsAutomatically(isCan);
  }

  @ReactProp(name = "supportMultipleWindows")
  public void setSupportMultipleWindows(WebView view, boolean supports) {
    view.getSettings().setSupportMultipleWindows(supports);
  } 
```
Additionally, I have also tried multiple npm packages which provide different implementations of WebView but nothing seems to work.

What is the best way to enable this feature?

**Comment by Titozzz** [comment]
I'm not able to help you developing new features right now, but if you find a way I will gladly help to review and merge.

**Comment by jerolimov** [comment]
@Shivendra30 @hasgarAOT Can you test if #270 works for you?

**Comment by Cordazar** [comment]
@jerolimov 	#270 	fixes my issue with facebook login that opens a modal.

**Comment by kishanshettyb** [comment]
@Shivendra30 I am also facing the same problem using razor pay payment gateway.

**Comment by hasgarAOT** [comment]
@kishanshettyb i was also facing the same. at last i integrated razerpay sdk with webview with postMessage

**Comment by Shivendra30** [comment]
So when working with PayuMoney, I stopped using the popup based Bolt integration (as they call it) and went for the other type of execution which does not use a popup but instead redirects the user.

I filled in the necessary fields using injectedJavascript prop of the WebView. Since this worked for me, I stopped banging my head on this issue. I haven't tried this for some time now. 
Seems like #270 should work though

**Comment by Shivendra30** [comment]
@kishanshettyb See the library react-native-razorpay. It is very straightforward. I just implemented it a couple of days back

**Comment by arjun-mepperi** [comment]
> @kishanshettyb See the library react-native-razorpay. It is very straightforward. I just implemented it a couple of days back

Hey,
How Did You Do It For Payumoney? Can U Explain

**Comment by Shivendra30** [comment]
@arjun-mepperi You can go to [this](https://developer.payumoney.com/redirect/) link and make a simple HTML and JS-based Redirect Checkout - https://developer.payumoney.com/redirect/.

I deployed this in Heroku by the way. 

After that, you can open that page in your WebView in react-native and inject the required information in the form using javascript DOM manipulation. You can do this by using the `injectedJavascript` prop.

For s step-by-step demo, you can see these videos - https://www.youtube.com/playlist?list=PL3-PKAGi7JdgZx8_r6a0d5VzTqgeNUmfo
It includes similar integration but with PayTm. However, you'll understand how to link the web-based payment gateway with your WebView

**Comment by crscaballero** [comment]
> @jerolimov #270 fixes my issue with facebook login that opens a modal.

Hi @Cordazar how did you solve that, I'm having exactly that problem

**Comment by Ajay1432** [comment]
> @jerolimov #270 fixes my issue with facebook login that opens a modal.

Can you tell me what did you changed? I'm having the same issue.
