### ISSUE TITLE
Can't Use Local Files (Android)

### ISSUE THREAD

**Issue by dmacpro91** [react-native-community/react-native-webview#2268]
**Bug description:**
When providing a file URI to source like below, iOS works perfectly while Android crashes inside DownloadManager.java since the URI isn't 'http' or 'https'.  Not sure why it's trying to download anything.

`<WebView
        source={{uri: Platform.OS === 'ios' ? filePath : androidFilePath}}
        originWhitelist={['file://']}
      />`

**Screenshots/Videos:**

<img width="1114" alt="Screen Shot 2021-12-01 at 12 51 59 PM" src="https://user-images.githubusercontent.com/2788893/144287504-500e604c-922e-4993-b8d9-f29bc99acbbb.png">

**Environment:**
 - OS: Android
 - OS version: 12
 - react-native version: 66.1
 - react-native-webview version: 11.15

**Comment by And111rey** [comment]
'file://' try use. 'file:///'  
or 
 source={
          Platform.OS === 'ios'
            ? require('../../assets/<SOME_FOLDER>/index.html')
            : { uri: 'file:///android_asset/<SOME_FOLDER>' }

**Comment by And111rey** [comment]
you should using  ...file:///android_asset....

**Comment by fukemy** [comment]
@And111rey  not working too me, can u help?
<img width="330" alt="Screen Shot 2022-11-22 at 15 19 42" src="https://user-images.githubusercontent.com/8202437/203261811-7e91f2c6-dc8b-43c9-9fa4-59f980ea080a.png">
<img width="811" alt="Screen Shot 2022-11-22 at 15 19 37" src="https://user-images.githubusercontent.com/8202437/203261843-90223caf-1cbb-4994-9eec-a104a466e3dc.png">
