### ISSUE TITLE
iframe within webview with wrong src crashes app

### ISSUE THREAD

**Issue by HerrX2000** [react-native-community/react-native-webview#230]
When the source of the iframe starts with // instead of https:// it crashes the app with the error massage: [GPhoto Image](https://photos.app.goo.gl/pyrbBFUwscxQpHUy9)

This is an example code:

```
render() {
    return (
        <WebView
        originWhitelist={['*']}
        javaScriptEnabled={true}
        source={{
            html: `<!DOCTYPE html>
            <html><head><meta charset="utf-8"/></head>
            <body>
            <iframe width="560" height="314" src="//www.youtube.com/embed/BYt8NvgDxYo?feature=share" allowfullscreen="allowfullscreen">
            </iframe>`
            }}
        />

    );

    }
}
```

package:

```
"dependencies": {
    "moment": "^2.23.0",
    "react": "16.6.3",
    "react-native": "0.57.8",
    "react-native-elements": "^0.19.1",
    "react-native-fast-image": "^5.1.1",
    "react-native-gesture-handler": "^1.0.12",
    "react-native-vector-icons": "^6.1.0",
    "react-native-webview": "^2.14.3",
    "react-navigation": "^3.0.9"
  },
```

Seams like a bug to me.

**Comment by Ehesp** [comment]
Using `//` will load the protocol as file I believe. Any external requests should be with http/https. Your image is also no longer working. Feel free to carry on the conversation if you have anymore updates.

**Comment by HerrX2000** [comment]
I know it should be http(s) but crashing the app with maliciously placed code on some website via XSS isn't good. I don't know if this behaviour is fixed in a more recent webview version.
