### ISSUE TITLE
[Android] WebRTC permission request

### ISSUE THREAD

**Issue by Javascript-Ninja** [react-native-community/react-native-webview#231]
Android WebView is missing `onPermissionRequest` handler, when the webpage call `navigator.mediaDevices.getUserMedia()` function, you will get a `PermissionDenied` error, even though all necessary permissions set on AndroidManifest.xml.

**Comment by chenkaiC4** [comment]
@Javascript-Ninja 
does this code work at your project?

i have copy the diff code of yours, all the permission is allowed, but the camera video is not show.

i have set the permisson `AndroidManifest.xml` too.

the camera device property, such as label is empty.

**Comment by chenkaiC4** [comment]
@Javascript-Ninja hi, i have got the video, 🥂 .

**Comment by Javascript-Ninja** [comment]
@Titozzz @jamonholmgren Can you merge the PR?

**Comment by chenkaiC4** [comment]
@Titozzz @jamonholmgren this PR seems work well, hope to merge to master

**Comment by ASteinheiser** [comment]
@Javascript-Ninja I tried out your forked branch, and it seemed to work at first. However, after closing the app and re-opening, the page with the webcam just fails silently. Before it was at least giving me an error: "Permission not granted" or something.

**Comment by Titozzz** [comment]
Please add this comment in the PR so that I can keep track 😊

**Comment by nakinthorn** [comment]
> @Javascript-Ninja I tried out your forked branch, and it seemed to work at first. However, after closing the app and re-opening, the page with the webcam just fails silently. Before it was at least giving me an error: "Permission not granted" or something.

Yep, I found like you
at the first time after install it work
but after clear app and open again it not work anymore

**Comment by nakinthorn** [comment]
> Please add this comment in the PR so that I can keep track 😊

at the first time after install it work
but after clear app and open again it not work anymore

**Comment by Titozzz** [comment]
@Javascript-Ninja Any idea?

**Comment by Javascript-Ninja** [comment]
#719

**Comment by Hamawis** [comment]
Its not working for me.

**Comment by riteshdange** [comment]
> @Javascript-Ninja hi, i have got the video, 🥂 .

can you please tell me how did you solve this issue because i install the latest webview library still and also in manifestfile still getting permission denied.....

**Comment by SunXinFei** [comment]
same issue
