### ISSUE TITLE
webview doesn't resize images in the content to fit the mobile screen

### ISSUE THREAD

**Issue by Nermin-K** [react-native-community/react-native-webview#234]
I use WebView from "react-native-webview" and I'm trying to make the web content fit into the mobile screen but images don't fit at all causing horizontal scrolling.  
I used `scalesPageToFit={true}` but it didn't help.
I also tried `style={{ flex: 1, width: Dimensions.get('window').width}}` and `style={{ flex: 1, width:'100%', alignSelf: 'stretch' }}` but I didn't get any changes. 
I tried `scrollEnabled={false}` but nothing works.

Is there any other solution for this problem? It's really ugly!

- "react-native": "0.57.8"

- "react": "16.6.3"

- "react-native-webview": "^2.14.3"

- android

- redmi note 4 - android version 7.0

- windows 10

**Comment by fempyrean** [comment]
I solved this issue adding this to what I was rendering in the webview.

`<style>
    img {
	display: block;
	max-width: 100%;
	height: auto;
	}
</style>`

**Comment by girish54321** [comment]
> I solved this issue adding this to what I was rendering in the webview.
> 
> `<style> img { display: block; max-width: 100%; height: auto; } </style>`
> 
> To make it more clear, let's say that I have a variable called content that contains what I want to render on the webview.
> 
> `let content = webviewContent;`
> 
> `content = '<style></style>' + content;`

works nicely

**Comment by kevidigi** [comment]
Can someone clarify how these style tags are applied to the webview?

**Comment by girish54321** [comment]
This woks for me 

const style = `<style> img { display: block; max-width: ${
  WIDTH - 26
}; height: auto;}
body {
  -webkit-touch-callout: none;
  -webkit-user-select: none;
  -khtml-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  user-select: none;
} </style>`;

 source={{
                html: `
                <html>
                  <body>
                  ${style + article.html_content}
              </body></html>`,
              }}

**Comment by kevidigi** [comment]
What if I'm using source={{ uri: <address> }}? Can this only apply the styling to local HTML??

**Comment by girish54321** [comment]
@kevidigi yes only for local HTML
