### ISSUE TITLE
decelerationRate should be 'normal' by default

### ISSUE THREAD

**Issue by petekp** [react-native-community/react-native-webview#236]
The default acceleration rate in iOS webviews was changed to 'normal' a couple major versions ago or so (see [UIScrollViewDecelerationRate docs](https://developer.apple.com/documentation/uikit/uiscrollviewdecelerationrate?language=objc) and [webkit changelog](https://trac.webkit.org/changeset/211197/webkit),

`react-native-webview`'s current default is `decelerationRate: 'fast'`, which is the slower, less native feeling deceleration.

Happy to submit a PR to update this.

More info on this history of this change in webkit: https://www.macobserver.com/analysis/apple-plans-change-scrolling-safari/

**Comment by petekp** [comment]
This is an issue upstream in RN itself. Closing and opening issue there.

**Comment by chrisbobbe** [comment]
> This is an issue upstream in RN itself. Closing and opening issue there.

Looks like this was https://github.com/facebook/react-native/issues/22900. Did you track down whether it was an issue in `react-native-webview` or `react-native`? 🙂 It's fine if not, I can take a closer look.

**Comment by petekp** [comment]
@chrisbobbe I didn't follow up on this, if you want to take a look :)

**Comment by triztian** [comment]
This is still an issue in 2023
