### ISSUE TITLE
Instructions on building from source?

### ISSUE THREAD

**Issue by jordansexton** [react-native-community/react-native-webview#237]
I performed a clone and yarn install. I opened the project from `RNCWebView.xcodeproj` (I didn't see the .xcworkspace file at first), and I got an error when building:

```
.... /react-native-webview/ios/RNCUIWebView.h:1:9: 'React/RCTView.h' file not found
```

I then opened `﻿RNCWebView.xcworkspace` and got this:

<img width="532" alt="screen shot 2019-01-08 at 7 46 45 pm" src="https://user-images.githubusercontent.com/1173161/50870571-28090e80-137e-11e9-92be-81a06ec8d595.png">

Are there any instructions on how to build and test the library on its own?

**Comment by vovkasm** [comment]
Is this what you want? https://github.com/react-native-community/react-native-webview/blob/master/docs/Contributing.md#how-to-test-changes

**Comment by Titozzz** [comment]
Do not open the xcworkspace but use xcodeproj instead. We need to remove the workspace I think
