### ISSUE TITLE
 Back to open session last visited

### ISSUE THREAD

**Issue by renan5by5** [react-native-community/react-native-webview#246]
Hello,

I call a url with chat in the webview, I send a body with the POST method to pass the registration data, but when I come back and enter the chat again I need to return the conversation that I was open last time.

Can anyone ever do this?

**Comment by Andreyco** [comment]
I would pass state thru URL params, e.g `http://mychat.app.com/activeConversation={id}` and adjust web app to understand such state.

**Comment by renan5by5** [comment]
@Andreyco 
the web app is not under my control, it's a production site that can not be changed for that need = \
I outlined this, leaving the screen always first in navigations
