### ISSUE TITLE
MIGRATED: Cookie not working with Payment Geteway. (#20470)

### ISSUE THREAD

**Issue by jamonholmgren** [react-native-community/react-native-webview#25]
Migrated from https://github.com/facebook/react-native/issues/20470

@abdelhakimkotti says:

---

Environment
React Native Environment Info:
System:
OS: macOS High Sierra
CPU: 2,53 GHz Intel Core i5
Memory: 8 Go 1067 MHz DDR3
IDEs:
Android Studio: Version 3.0
Xcode: Version 9.2

Description
Am implementing party payment gateway in a webview And when the user got redirected to the result page, i got a message saying that "cookies are not enabled in the browser ".
To access the payment pages you need to have enabled cookie.

Code
     <WebView 
          source={{ uri: this.state.url }}
          scalesPageToFit={true} 
          javaScriptEnabled={true}
          thirdPartyCookiesEnabled={true} 
          onNavigationStateChange={this.onNavigationStateChange} 
     />
Reproducible Demo
For iOS:
https://developer.apple.com/documentation/foundation/nshttpcookiestorage/1418390-cookies?language=objc

For Android:
https://developer.android.com/reference/java/net/CookieStore

---

**Comment by Salakar** [comment]
Hey @abdelhakimkotti I'm going to go ahead and close this given that progress is being in #181 for this and the age of this issue.

If you need this to remain open for whatever reason please let me know, otherwise please follow along with the PR mentioned above.
