### ISSUE TITLE
[android] Manifest merger failed : android:exported needs to be explicitly specified for <activity>.

### ISSUE THREAD

**Issue by couchcryptid** [react-native-community/react-native-webview#2500]
**Bug description:**
When building in a bare expo SDK 45 project with React Native 0.68 which targets Android 12, build fails with the following error:
> Manifest merger failed : android:exported needs to be explicitly specified for <activity>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.

**To Reproduce:**
1. Init new expo project and eject.
2. Install react-native-webview
3. run `npm run android` / `yarn android`

**Expected behavior:**

I expect android to build successfully.

**Environment:**
 - OS: Apple
 - OS version: 12.3.1
 - react-native version: 0.68.2
 - react-native-webview version: 11.18.2

**Comment by schematis** [comment]
I'm closing this for further investigation on my end. The error may not be coming from this library as the logs are unclear and it may need another library to conflict with.
