### ISSUE TITLE
OnShouldStartLoadWithRequests should be more detailed and show more requests(at least have the option to).

### ISSUE THREAD

**Issue by sgebr01** [react-native-community/react-native-webview#2520]
**Is your feature request related to a problem? If so, Please describe.**
I am trying to implement adblocking in a webview, and the onShouldStartLoadWithRequest function would've been exactly what I would need for this to happen, but the requests that I get back aren't detailed enough for me to do so. For example, if I were to load www.youtube.com, the only request that I get back is https://m.youtube.com/. This is for sure not the only resource being loaded. It should show us requests for videos, images, and other resources that the page is trying to load, not just the page itself. If this could be implemented would be great.

**Describe the solutions you came up with**
There are no solutions that I have came up with or found so far.

**Additional context**

**Comment by TheAlmightyBob** [comment]
You can create native customizations of React Native WebView on [Android](https://github.com/react-native-webview/react-native-webview/blob/master/docs/Custom-Android.md) and [iOS](https://github.com/react-native-webview/react-native-webview/blob/master/docs/Custom-iOS.md). What you probably want on Android is `shouldInterceptRequest`.

However, I'm not sure that what you want exists for iOS. There's [WKURLSchemeHandler](https://developer.apple.com/documentation/webkit/wkurlschemehandler?language=objc), but that may not work for handling non-custom schemes like https.

**Comment by jamninetyfive** [comment]
> 好，谢谢！这看起来应该适用于 Android。至于 iOS，我会继续寻找并在此处发布一些内容，如果我找到了什么。

have you sloved this ?
