### ISSUE TITLE
https urls show blank screen in Android

### ISSUE THREAD

**Issue by DovletAmanov** [react-native-community/react-native-webview#259]
I'm having issue with calling some https urls in Android. Other urls works fine. Probably it stems from ssl issues. I have tried almost all solutions but unfortunately nothing changed. It shows white screen when WebView is activated. Is there any way to do something like "ignoreSslStuff"? Thanks in advance

- react: 16.6.3
- react-native: 0.57.8
- react-native-webview: 3.1.2

**Comment by DovletAmanov** [comment]
Reason was ssl certificate configurations. Now it works without problem.

**Comment by ManigandanRaamanathan** [comment]
any other solution?

**Comment by Dante-dan** [comment]
I have the same problem, then i found the solution like [this](https://zhuanlan.zhihu.com/p/33033496).
```javascript
// path: /src/main/java/com/facebook/react/views/webview/ReactWebViewManager.java.
// override the sslError
@Override
public void onReceivedSslError(WebView view, SslErrorHandler handler, SslError error) {
   // before: handler.cancel();
  handler.proceed();
}
```

but i can't found this code in `react-native 0.57`  and `react-native-webview  5.7`

**Comment by Dante-dan** [comment]
> any other solution?

you can custom the android webview like [this](https://github.com/react-native-community/react-native-webview/blob/master/docs/Custom-Android.md) and someone try [it](https://github.com/react-native-community/react-native-webview/issues/537)

**Comment by DovletAmanov** [comment]
Overriding sslError makes it work but, it is NOT secure way to solve this issue. By the way, Google refuses to upload your app if you overrided sslError like that.

**Comment by Dante-dan** [comment]
> Overriding sslError makes it work but, it is NOT secure way to solve this issue. By the way, Google refuses to upload your app if you overrided sslError like that.

right! thanks

**Comment by eXist-FraGGer** [comment]
Any solution?

**Comment by a88053443** [comment]
@Dante-dan Can you give an example?
