### ISSUE TITLE
[Feature Request] Do not automatically download files on Android

### ISSUE THREAD

**Issue by Pingou** [react-native-community/react-native-webview#262]
Since 2.15.0 files are automatically downloaded when clicking file links.
It would be great to be able to disable this behavior.

**Comment by Pingou** [comment]
@Titozzz Do nothing, as was the case with the previous versions of Webview.
In my case for example I check the url, and internally download the file if necessary.
I am not saying it would be the optimal behavior for most people, but it would be nice to have a flag to disable to automated download.

**Comment by Titozzz** [comment]
sure, would it also need to be disabled on iOS ?

**Comment by Titozzz** [comment]
Please submit a Pull request then 😄

**Comment by smathson** [comment]
@Pingou What method are you using to check the URL? If you use `onShouldStartLoadWithRequest` to intercept the URL, handle the download yourself and return false, the download request will never hit the WebView and you won't have to worry about the default behavior.

**Comment by Pingou** [comment]
@Titozzz Will do if I find some time, that should be a quick fix.

@smathson Good idea, but actually in my situation it's a bit more complicated than checking the url, I need to get the file type, so I actually start to download each url myself to check, and stop when I get the header. I have no way of knowing immediately if the webview should load the url or not, unless I can deduce the file type from the url.

**Comment by Ehesp** [comment]
Due to inactivity I'll close this issue. Please provide a PR / example of how this can be achieved and we'll investigate further.

**Comment by shimangdian** [comment]
When will this feature be added?

**Comment by CostachescuCristinel** [comment]
Hi, I have the same issue, but I am unable to stop the WebView from ever doing anything even if I force return false:

```
<WebView onShouldStartLoadWithRequest={() => false} />
```
The WebView still starts the download of PDF files (and I assume, any other downloadable file type).

Can someone advice what should I do?
Right now Android starts downloading the same file over-and-over every time the page is displayed, terrible UX...
