### ISSUE TITLE
postMessage causes web view to reload on iOS

### ISSUE THREAD

**Issue by danprince** [react-native-community/react-native-webview#263]
The mechanism used for sending a message from the Web View context to the React Native context on iOS seems to involve triggering a full page reload by setting `window.location`.

https://github.com/react-native-community/react-native-webview/blob/6c911952c553700f372520b314c9e715dae70af0/ios/RNCUIWebView.m#L310-L314

Is there any way to post a message up without losing all the state on the current page?

**Comment by danprince** [comment]
Thanks @Titozzz!

Sorry, I might not have explained clearly enough. The content inside the web view _is_ a single page application, with its own routing layer.

The problem is that whenever that single page app tries to post a message to the native side, the routing gets messed up, because the page reloads at a different url.

What I'm trying to figure out is whether that's intentional, or whether there's an alternate way to message the native app, without reloading the page at all.

**Comment by danprince** [comment]
Here's an example:

* The development version of the embedded web app is running on `localhost:8080`
* Render a webview with `source: { uri: "http://localhost:8080" }`
* Use the web app to navigate to another view (e.g. `http://localhost:8080/profile`)
* Try to `postMessage` to the native app to log a specific interaction
* `postMessage` runs `window.location = "..."` and the page reloads
* The web view is no longer showing `http://localhost:8080/profile`

**Comment by Titozzz** [comment]
I'm not aware of such behavior on my Single page app, however please note that there is a rewrite of postMessage ongoing so it might help with your issues ... I understand your example but could you provide a reproduction ?

**Comment by Titozzz** [comment]
Are you using WKWebview or UIWebview?

**Comment by danprince** [comment]
Using whichever one is exported as `WebView` (pretty sure it's `WKWebView`) with the latest versions of `react-native-webview` and whatever expo currently considers to be `react-native`.

**Comment by Titozzz** [comment]
Are you using expo ?

**Comment by danprince** [comment]
Yeah, but even after ejecting from Expo to use this library, it doesn't look like the `postMessage`/`processQueue` implementation changes at all.

**Comment by Titozzz** [comment]
Implementation changes with WKWebview so it might help. you can try directly on expo with useWebkit={true} (it's the default on this repository but not on react-native)

**Comment by joshh01** [comment]
Did you come up with a solution to this problem? I'm encountering the same issue
