### ISSUE TITLE
IOS12.1:  Error evaluating injectedJavaScript: This is possibly due to an unsupported return type. on simulator phone6

### ISSUE THREAD

**Issue by fantasy525** [react-native-community/react-native-webview#269]
on simulator iPhone6,I inject javascript string,but I got error:
```
const strToJson=`
      window.parseToJson=function(data){
        return JSON.parse(data.replace(/^"|"$/,"'"));
      }
    `;

<WebView
		useWebKit={true}
		javaScriptEnabled={true}
		injectedJavaScript={strToJson}
		ref={this.webview} 
                onLoadEnd={this.onFinished}
		onMessage={this.handleMessage}
		style={{flex:1}}
		source={{uri:uri}}
	/>
```

**Comment by carlmagumpara** [comment]
same problem here

**Comment by jamonholmgren** [comment]
Try appending `true` to the end of your string.

```js
const strToJson = `
  window.parseToJson=function(data){
    return JSON.parse(data.replace(/^"|"$/,"'"));
  }
  true;
`;
```

We should probably automatically append `true` to the end of injected JavaScript for people.

**Comment by jamonholmgren** [comment]
Related to #200.

**Comment by jqn** [comment]
@jamonholmgren I think this could be improved in terms of better documentation. I ran into this issue and it took me about an hour to figure out what the documentation meant by "Make sure the string evaluates to a valid type (`true` works) and doesn't otherwise throw an exception".

Perhaps an example would be better for clarity.

In my case this is what I was doing wrong: 

```
  _injectJS = () => {
    const script = `
      window.ReactNativeWebView.postMessage(window.location.search);
    `;
    if (this.searchWebview) {
      this.searchWebview.injectJavaScript(script);
    }
    true;
  };
```
and I continued to get the same error described in this issue. In the end I realized I forgot to set the onMessage prop in the WebView and setting it solved the problem.

**Comment by Titozzz** [comment]
Feel free to submit a PR for the docs

**Comment by matthewfbenjamin** [comment]
@jqn What did you set your `onMessage` prop to?

**Comment by NestedLooper** [comment]
If you want to get a better idea of what is happening when the JS is evaluated, you can modify the evaluateJS method of RNCWKWebView.m with some logs:

```
- (void)evaluateJS:(NSString *)js
          thenCall: (void (^)(NSString*)) callback
{
  [self.webView evaluateJavaScript: js completionHandler: ^(id result, NSError *error) {
    if (error == nil) {
      if (callback != nil) {
        callback([NSString stringWithFormat:@"%@", result]);
      }
    } else {
      RCTLogInfo(@"Class: %@", [js class]); //add
      RCTLogInfo(@"JS: %@", js); //add
      RCTLogInfo(@"Error: %@", [error localizedDescription]); //add
      RCTLogError(@"Error evaluating injectedJavaScript: This is possibly due to an unsupported return type. Try adding true to the end of your injectedJavaScript string.");
    }
  }];
}
```
In my case, I got back 'Error: A JavaScript exception occurred'.
I think it is most likely due to me using jQuery in my js, which can't be evaluated properly.

**Comment by sapjax** [comment]
> If you want to get a better idea of what is happening when the JS is evaluated, you can modify the evaluateJS method of RNCWKWebView.m with some logs:
> 
> ```
> - (void)evaluateJS:(NSString *)js
>           thenCall: (void (^)(NSString*)) callback
> {
>   [self.webView evaluateJavaScript: js completionHandler: ^(id result, NSError *error) {
>     if (error == nil) {
>       if (callback != nil) {
>         callback([NSString stringWithFormat:@"%@", result]);
>       }
>     } else {
>       RCTLogInfo(@"JS: %@", js); //add
>       RCTLogInfo(@"Error: %@", [error localizedDescription]); //add
>       RCTLogError(@"Error evaluating injectedJavaScript: This is possibly due to an unsupported return type. Try adding true to the end of your injectedJavaScript string.");
>     }
>   }];
> }
> ```
> 
> *edit - no need to evaluate typeof/class. It will always be a string.
> 
> In my case, I got back 'Error: A JavaScript exception occurred'.
> I think it is most likely due to me using jQuery in my js which can't be evaluated properly.

```
error	NSError *	domain: @"WKErrorDomain" - code: 3	0x0000600002d6de00
The WKWebView was invalidated
```

**Comment by vUdav** [comment]
I have some problem with this code:

```
const html = `
    <form method='POST' action='/some-action-url/' name='payment' >
      <input type='hidden' name='sum' value='100'/>
    </form>
  `;

const injectedJavaScript = `
  document.payment.submit();
  true;
`;

return (
  <WebView
    useWebKit={true}
    javaScriptEnabled={true}
    source={{ html }}
    injectedJavaScript={injectedJavaScript}
  />
);
```

I get an error `Error evaluating injectedJavaScript`. If I use this async hack `setTimeout(function() { document.payment.submit() }, 1);` then is resolve this error. But I think this is bad practice.
