### ISSUE TITLE
MIGRATED: WebView doesn't support `width: 100%` and `alignSelf: stretch` (#20551)

### ISSUE THREAD

**Issue by jamonholmgren** [react-native-community/react-native-webview#27]
Migrated from https://github.com/facebook/react-native/issues/20551

@sesm says:

---

Environment
Environment:
OS: macOS High Sierra 10.13.4
Node: 8.11.3
Yarn: 1.7.0
npm: 5.6.0
Watchman: 4.9.0
Xcode: Xcode 9.2 Build version 9C40b
Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
react: 16.3.2 => 16.3.2
react-native: 0.55.4 => 0.55.4

Also reproducible on latest version of react-native on Expo.

Description
WebView doesn't support width: 100% and alignSelf: stretch. The only way to horizontally stretch a WebView is to set explicit width.

Reproducible Demo
https://snack.expo.io/rk8HNfLSQ
In this example width: 100% and alignSelf: stretch work perfectly well on View but don't work on WebView.

---

_More details on original issue thread._

**Comment by tarangill** [comment]
Still searching for a solution.

**Comment by Andriiklymiuk** [comment]
Yep, it is still a problem

**Comment by student-t** [comment]
No solution?

**Comment by gustawdaniel-acaisoft** [comment]
This issue should be reopen. I can reproduce this bug with these packages

```
  "dependencies": {
    "expo": "~44.0.0",
    "expo-status-bar": "~1.2.0",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-native": "0.64.3",
    "react-native-web": "0.17.1",
    "react-native-webview": "11.15.0"
  },
```

**Comment by Jaarson** [comment]
This works:
```
<WebView containerStyle={{ width: '100%' }} source={{ html: '<h1>Hello world</h1>' }} />
```
