### ISSUE TITLE
onMessage not triggering

### ISSUE THREAD

**Issue by linnett** [react-native-community/react-native-webview#272]
`onMessage` isn't triggering when I send a `window.postMessage` from the webview.

Code:
```
<WebView
  ref={(ref) => {
    this.child = ref;
  }}
  onLoad={() => {
    if (loaded) return;
    this.setState({ loaded: true });
    this.child.onMessage = this.onMessageHandler;
  }}
  startInLoadingState
  renderLoading={() => <Loader />}
  useWebKit={false}
  javaScriptEnabled
  source={source}
/>
```

I am attempting to use this method of setting a `loaded` state due to a well spoken about issue with postMessage where the error `Setting onMessage on a WebView overrides existing values of window.postMessage, but a previous value was defined.` appears (as per https://github.com/facebook/react-native/issues/10865).  

I have also attempted the method of injecting JavaScript (as per https://github.com/facebook/react-native/issues/10865#issuecomment-269847703).

Finally, I attempted  adding `onMessage={loaded ? this.onMessageHandler : null}`.

All are failing.

Any help would be greatly appreciated! 

React Native: 0.56.0
react-native-webview: 3.2.1

**Comment by ralesiupgrade** [comment]
you may want to see https://github.com/react-native-community/react-native-webview/pull/243

Im having similar problem with no solution as well. Looks like its only a dev mode problem though so you may want to check your app in release mode and see if it works

**Comment by linnett** [comment]
Nice one :)

**Comment by dev-newton** [comment]
Try with this...... ReactNativeWebView.postMessage(JSON.stringify(resp))
