### ISSUE TITLE
ability to focus webview

### ISSUE THREAD

**Issue by alidcastano** [react-native-community/react-native-webview#278]
I'm trying to embed an editor inside a webview, but clicking on the webview itself does not seem to focus it (so that the keyboard can open and user can edit). Is it possible to focus the webview?

*note: editing inside webview works on the simulator (where I can type via desktop keyboard).*

**Comment by jaulz** [comment]
I might look for something similar... on iPhone I need to tap the WebView first to gain focus and only the second tap is actually triggering a tap in the WebView. Though on iPad the very first tap is handled by the WebView.

**Comment by Slapbox** [comment]
This would be such an enormous deal for usability, I can't overstate it. Webviews are often used to wrap editors and if you can't focus the Webview for the user things just feel terrible.

**Comment by jamonholmgren** [comment]
We would love someone to take the initiative on this and make a PR! ❤️

**Comment by Wilson-Lim** [comment]
We need this feature too.

**Comment by jamonholmgren** [comment]
There's a pull request in progress now for this, #540. Help testing it would be amazing @Wilson-Lim, @Slapbox , @jaulz, @alidcastano ! Thanks to @ericlewis

**Comment by Slapbox** [comment]
Unfortunately I can't test this (using Expo still at the moment) but thanks so much to @ericlewis for the PR to @jamonholmgren for keeping on top of everything!

**Comment by jaulz** [comment]
@ericlewis @jamonholmgren thanks! I'm not an expert in Objective C so please excuse my question but would this piece of code also be reusable for a `focus` method on the WebView?

**Comment by ericlewis** [comment]
Do you mean UIWebView? Technically, you should only need to expose this already existing prop. If you mean androids webview, then no it’s not reusable there. 

Sent via Superhuman iOS ( https://sprh.mn/?vip=ericlewis777@gmail.com )

**Comment by ericlewis** [comment]
@jaulz or do you mean a method you can call to “focus” the webview? There is no method to call in this case (I’m not sure how that would work either) what this allows is for the *javascript* in the webview to call focus on a text element and the keyboard will display without user interaction. This isn’t enabled by default on iOS.

**Comment by Slapbox** [comment]
@ericlewis - I can programatically focus _within_ a Webview as is, but that's not enough to get the keyboard to appear unless the user has already focused the Webview itself. Both the Webview AND a text editable element on the page must be focused for the keyboard to show. Once a Webview has been focused once, focusing an inner element seems to be enough to show the keyboard.

All of that is the case for Android at least.

**Comment by ericlewis** [comment]
Gotcha. Yeah, on iOS this allows the User to skip the step of needing to focus (tap) the WebView. I will see if I can get this to work on droid too.

Sent via Superhuman ( https://sprh.mn/?vip=ericlewis777@gmail.com )

**Comment by jamonholmgren** [comment]
I assume #540 solves your problem, @alidcastano ? If so, we can close this.

**Comment by Slapbox** [comment]
@jamonholmgren #540 doesn't yet resolve the problem in my view.

**Comment by alidcastano** [comment]
i, unfortunately, haven't had a chance to check but will go ahead and close this issue - thanks @amonholmgren (and @ericlewis!)

**Comment by ericlewis** [comment]
@Slapbox if you want to open an android specific issue- go ahead! #540 was iOS only.

**Comment by gianpaj** [comment]
Just asking here in case a miracle is possible.
Is there any way to automatically focus on an input field inside iframe?
I don't control the iframe as it's the bank credit card iframe.

**Comment by ericlewis** [comment]
You could inject your own JavaScript that looks for the ID or class of the desired input then have it focus once DOM is ready. Use the injectedJavascript prop. 

Sent via Superhuman iOS ( https://sprh.mn/?vip=ericlewis777@gmail.com )

**Comment by maxKimoby** [comment]
Is there any way this could prop could be implemented on android? If not, how can I programmatically show they keyboard when an input has focus in the webview? I tried `this.webView.requestFocus()` but this is not working.

**Comment by Slapbox** [comment]
There's no way to programmatically focus the webview on Android. I think this feature is _desperately needed_.

**Comment by rmanalo-getdevs** [comment]
Focus still not working in android

**Comment by Slapbox** [comment]
I advise everybody to move this discussion over to #1172

Indeed, focusing is still not implemented on Android - so this really shouldn't have been closed - but it is.
