### ISSUE TITLE
Couldn't load big static html on Android

### ISSUE THREAD

**Issue by cordosvictor** [react-native-community/react-native-webview#283]
I'm dealing with big static htmls and it doesn't load the content. The only thing it shows is a loading spinner (startInLoadingState being true)

**Comment by swarnsingh** [comment]
I am facing the same kind of issue while loading large content in Android. 
In my case, I have two web views & based on the condition I need to switch between the web view. It's working fine for the first time but when switching to another web view, it's giving the below error. Working fine in ios. 
Getting - 
code: -15
description : "net::ERR_INSUFFICIENT_RESOURCES".

**Comment by Ehesp** [comment]
Please could you provide a reproduction for this issue and we'll take a look. Closing for now.
