### ISSUE TITLE
Any way to disable opening pages in external browser, e.g. popup ads?

### ISSUE THREAD

**Issue by vladim0105** [react-native-community/react-native-webview#284]
I know that it was possible to do so in electron by setting the "open new window/page" command to do nothing, is there a similar way in webview? Reason why I want this is that some embeds open a popup (or pop under) ad whenever the user clicks on it, which is really annoying.

**Comment by Titozzz** [comment]
You can use : https://github.com/react-native-community/react-native-webview/blob/master/docs/Reference.md#onshouldstartloadwithrequest

**Comment by vladim0105** [comment]
> You can use : https://github.com/react-native-community/react-native-webview/blob/master/docs/Reference.md#onshouldstartloadwithrequest

It is only for ios, and I have tried the android `onNavigationStateChange()` but it seems to only allow me to block redirects, but does not let me block opening the external browser and then loading a page there.

**Comment by Titozzz** [comment]
It has been ported to android : #107 , Docs have not been updated, that's a mistake.

**Comment by vladim0105** [comment]
Thanks, it works! I hope `onNavigationStateChange()` will be ported to windows, once the windows compatibility is ready :)

**Comment by Titozzz** [comment]
So about that, I'll edit the readme, windows is on standby right now so if you want to submit a pull request to add support I'd love to help merging it
