### ISSUE TITLE
Implement Ad Block in webview

### ISSUE THREAD

**Issue by ankur-sardar** [react-native-community/react-native-webview#286]
Can you please suggest me any way to implement Ad Block feature for the webview

**Comment by Momazo7u7** [comment]
You can use onShouldStartLoadWithRequest wich is supported on ios and android(Finally :"U) , you can have a "blacklist" or whitelist of domains and compare it to the redirection url and abort// continue using regex.  As an alternative you could inject some javascript that shoul override the function of window.open and alert(), and href.location, to the webview, the downside is that some websites doen't work at all with that.
