### ISSUE TITLE
All videos show as black screen, audio only, on Android

### ISSUE THREAD

**Issue by jkustan** [react-native-community/react-native-webview#290]
Created brand new react-native project (doesn't matter 0.57 or 0.58), only code is in App.js:
```
  render() {
    return (
     <WebViewExample/>
     );
  }
```
and
```
const WebViewExample = () => {
   return (
    <WebView
        source={{ uri: "https://www.youtube.com" }}
      />
   )
}
```
Run in an emulator (brand new), shows youtube full screen (as expected). Click a video => audio starts but video is black.

Note when I create a new Android Studio project (also with just a single webview pointing to youtube), the video shows fine. So this is something with the react-native stack.

This is happening in our app but the lab conditions above hopefully will let someone reproduce easily.  I'm attaching 2 projects -- one is the straight-up Android Studio project that shows the video fine in the emulator, and the other is a vanilla RN 0.58 app with the react-native-webview, audio but no video.

I'm using Pixel 2 (26) although same behavior on a physical device.

Any help would be GREATLY appreciated!

[MyReactNative.zip](https://github.com/react-native-community/react-native-webview/files/2806546/MyReactNative.zip)
[MyWebviewApp.zip](https://github.com/react-native-community/react-native-webview/files/2806547/MyWebviewApp.zip)

_Originally posted by @jkustan in https://github.com/react-native-community/react-native-webview/issues/172#issuecomment-458439967_

**Comment by Momazo7u7** [comment]
might be device-related  , i have a phone with lineage os , the videos also returns audio but no video , unless i put the phone in landscape mode and use fullscreen. Try using other device

**Comment by smathson** [comment]
@jkustan Thanks for creating a new issue about this and including a detailed report. So far I’ve been unable to reproduce this on anything but an emulator and just chalked it up to emulator issues since those things are pretty flaky to begin with. Could you include some more detail about the physical devices you are seeing this on? Anything that looks related in the logs on that device when the video starts playing?

**Comment by Titozzz** [comment]
@smathson Thanks, you are right

**Comment by sidVaidya** [comment]
@Titozzz have you found a solution for this issue?
