### ISSUE TITLE
This happens when calling android.applicationVariants, android.libraryVariants or android.testVariants

### ISSUE THREAD

**Issue by oguzhandemiroz** [react-native-community/react-native-webview#292]
Error: 
> Android tasks have already been created.
This happens when calling android.applicationVariants,
android.libraryVariants or android.testVariants.
Once these methods are called, it is not possible to
continue configuring the model.

------------------------------------------------------

**There is no problem with iOS.** On Android is constantly failed Gradle Sync. The latest version is installed but still not. I updated React-Native from 0.56.0 to 0.58.3 and it continues to give the same error. But the problem is solved when I uninstall it.

[https://ibb.co/cL56qHR](url) Open File --> [https://ibb.co/d5YhZJ4](url) 

------------------

>  React Native Environment Info:
    System:
      OS: macOS 10.14.2
      CPU: (8) x64 Intel(R) Core(TM) i7-3635QM CPU @ 2.40GHz
      Memory: 120.50 MB / 8.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.2.0 - /usr/local/bin/node
      Yarn: 1.6.0 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.1 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 27, 28
        Build Tools: 23.0.1, 23.0.3, 25.0.2, 25.0.3, 26.0.1, 26.0.3, 27.0.3, 28.0.1, 28.0.2, 28.0.3
        System Images: android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.1 AI-173.4720617
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.4.1 => 16.4.1 
      react-native: ^0.58.3 => 0.58.3 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

**Comment by oguzhandemiroz** [comment]
@Titozzz

**Comment by Titozzz** [comment]
Try invalidating cache

**Comment by lucidtheory** [comment]
running into this same issue

```
* Where:
Build file '/Users/ezinator/Desktop/client/android/build.gradle' line: 50

* What went wrong:
A problem occurred configuring project ':react-native-webview'.
> Failed to notify project evaluation listener.
   > Android tasks have already been created.
     This happens when calling android.applicationVariants,
     android.libraryVariants or android.testVariants.
     Once these methods are called, it is not possible to
     continue configuring the model.
   > Android tasks have already been created.
     This happens when calling android.applicationVariants,
     android.libraryVariants or android.testVariants.
     Once these methods are called, it is not possible to
     continue configuring the model.
   > Android tasks have already been created.
     This happens when calling android.applicationVariants,
     android.libraryVariants or android.testVariants.
     Once these methods are called, it is not possible to
     continue configuring the model.
   > Android tasks have already been created.
     This happens when calling android.applicationVariants,
     android.libraryVariants or android.testVariants.
     Once these methods are called, it is not possible to
     continue configuring the model.
   > Android tasks have already been created.
     This happens when calling android.applicationVariants,
     android.libraryVariants or android.testVariants.
     Once these methods are called, it is not possible to
     continue configuring the model.
   > Android tasks have already been created.
     This happens when calling android.applicationVariants,
     android.libraryVariants or android.testVariants.
     Once these methods are called, it is not possible to
     continue configuring the model.
   > Android tasks have already been created.
     This happens when calling android.applicationVariants,
     android.libraryVariants or android.testVariants.
     Once these methods are called, it is not possible to
     continue configuring the model.
   > Android tasks have already been created.
     This happens when calling android.applicationVariants,
     android.libraryVariants or android.testVariants.
     Once these methods are called, it is not possible to

```

will keep tinkering but already tried invalidating and restarting with no success

**Comment by Titozzz** [comment]
@salakar have you ever since this issue on your repo ?

**Comment by Titozzz** [comment]
@salakar have you ever seen this issue on your repo ?

**Comment by lucidtheory** [comment]
https://github.com/lucidtheory/webviewTest


This repo recreates the issue I'm having.

Steps:
-init new react native project
-install this lib
-add 
```
subprojects {
  project.configurations.all {
      afterEvaluate {project ->
        if (project.hasProperty("android")) {
            android {
                compileSdkVersion 28
                buildToolsVersion '28.0.2'
            }
        }
    }
  }
}
```
to app level `build.gradle`
-run `cd android && ./gradlew assembleRelease`


and the above crash happens

**Comment by lucidtheory** [comment]
Update: 

```
        if (project.hasProperty("android") && !project.name.equals('react-native-webview')) {
            println project.name
            android {
                compileSdkVersion rootProject.ext.compileSdkVersion
                buildToolsVersion rootProject.ext.buildToolsVersion
            }
        }
```

so I was able to get the build to run by essentially skipping the subprojects conditional for react-native-webview.

This seems a bit hacky. I'm curious if there is something in the repo that isn't allowing it to run this script the same way all the other repos we are using do. So it's not a fix but a workaround.

**Comment by Salakar** [comment]
There's some issues on mine with grade 4.7+ - so maybe related if the grade version being used here is higher than RNs default of 4.6 @Titozzz

I've not looked into the issues any further yet 🙈

**Comment by Titozzz** [comment]
I'm in the process of updating my own project to use SDK 28 so I guess I'll know soon

**Comment by Salakar** [comment]
I've updated to SDK 28 locally and have had no build issues; @lucidtheory you should use `beforeEvaluate` instead of `afterEvaluate` - which will successfully build. 

On a side note / off topic, specifying the `buildToolsVersion` is not really needed and will generally be ignored and default to the one bundled with gradle; e.g. gradle `4.10.0` comes with `28.0.3`
