### ISSUE TITLE
Downloading a URI starting with blob:http://... on android crashes the app

### ISSUE THREAD

**Issue by chaudhryjunaid** [react-native-community/react-native-webview#295]
I have a webview on Android that attempts to download an embedded pdf file via a blob URL. However, the app crashes on such attempt.

**Comment by jamonholmgren** [comment]
Hi @chaudhryjunaid , can you provide a minimal reproduceable repo so we can see this happening?

**Comment by marexv** [comment]
I have the same issue. Need some help with that repo @jamonholmgren?

**Comment by mobitar** [comment]
On iOS, navigating to a blob via `window.location.href = blobUrl` will show the file within the webview, but I haven't found a way to get the file to actually download and save to the user's photos or files. (Using the method to create a temporary `a` tag and and then `a.click()` has no effect.)

This answer has a workaround, although not too elegant:
https://stackoverflow.com/questions/45065085/how-to-read-a-blob-data-url-in-wkwebview

In case you want to test this, you could create a blob link in JS with this:

```javascript
 downloadData(useNavigation = false) {
    var link = document.createElement('a');
    link.setAttribute('download', "foo.json");
    var url = window.URL.createObjectURL(new Blob([JSON.stringify({foo: "bar"})], {type: 'text/json'}));
    link.href = url;
    if(useNavigation) {
      window.location.href = link.href;
    } else {
      document.body.appendChild(link);
      link.click();
      link.remove();
    }
  }
```

`useNavigation` is for React Native, since `link.click()` doesn't do anything.

**Comment by nyalsadiq** [comment]
I'm having the same problem, any update on this?

**Comment by memelie** [comment]
I am facing the same issue! @jamonholmgren any help?

**Comment by JesperBry** [comment]
I'm facing the same issue, any update on this? 
I've noticed that files represented as a blob, don't get a path and the app crashes. However it works with image-files represented as blobs, but not with pdf's.

**Comment by fvidalarcon** [comment]
me sumo al post, esoy enfrentando e mismo problema...

`java.lang.IllegalArgumentException: Can only download HTTP/HTTPS URIs: blob:`

`@Override
            public void onDownloadStart(String url, String userAgent, String contentDisposition, String mimetype, long contentLength) {
                final DownloadManager.Request request = new DownloadManager.Request(Uri.parse(url));
                request.allowScanningByMediaScanner();
                request.setMimeType(mimetype);`

**Comment by aszenz** [comment]
@jamonholmgren 

Here's an example to reproduce it:

```
    <View style={{ flex: 1 }}>
      <WebView
        source={{
          uri: 'https://codepen.io/vidhill/pen/bNPEmX'
        }}
        javaScriptEnabled
        allowFileAccess
        mixedContentMode={'always'}
        domStorageEnabled
        textZoom={150}
      />
    </View>
```

The embedded codepen url has a link (Download JSON) which should download a json file, but the app crashes on clicking the link.

**Comment by daniily000** [comment]
Same problem. Any news?

**Comment by bbuttam** [comment]
I'm having the same problem, any update on this?

**Comment by DaniGo-1** [comment]
¿Alguien encontró alguna solución?

**Comment by razaadeel** [comment]
Facing the same issue. Anyone found the solution?

**Comment by jack-salvona-dynasty** [comment]
Also currently facing this issue, with PDF, Excel & CSV blob downloads

**Comment by bpfeiffer187** [comment]
I am also facing this same issue. Anyone have an anticipated date for a fix?

**Comment by bendadaniel** [comment]
+1

**Comment by donysukardi** [comment]
Still searching for solutions

**Comment by jamonholmgren** [comment]
Thanks to @aszenz for the [minimal repro](https://github.com/react-native-community/react-native-webview/issues/295#issuecomment-532716315). If someone wants to tackle fixing this problem, I'm happy to review the PR!

**Comment by lamendaviesa** [comment]
Hi! 
Try to add this:


Hi! @jamonholmgren @aszenz  probe to do that.

<WebView
        allowFileAccess
        originWhitelist={['https://*', 'blob:*']}
        javaScriptEnabled       
        source={{
          uri: 'https://codepen.io/vidhill/pen/bNPEmX'
        }}
      />

 **It works in iOS, I have problems in Android.**

Error Android: 
java.lang.IllegalArgumentException: Can only download HTTP/HTTPS URIs: blob:https://familiados.com/65829a53-1c51-4369-96da-61ff6d8f3094
        at android.app.DownloadManager$Request.<init>(DownloadManager.java:459)
        at com.reactnativecommunity.webview.RNCWebViewManager$2.onDownloadStart(RNCWebViewManager.java:205)
        at ic.a(PG:548)

**Comment by aszenz** [comment]
@lamendaviesa 
The problem is not specific to this package, instead the Android Download Manager only accepts http and https download uris. 
So blob uris needs to be converted into a base64 string in JS and then that base64 string has to be written on the download path using Android Java APIs.

**Comment by lamendaviesa** [comment]
@aszenz Thanks!!

**Comment by lamendaviesa** [comment]
@aszenz Thanks!

**Comment by KA-32** [comment]
why is this issue closed ?

**Comment by SamiChab** [comment]
Still looking for an answer to this... Can someone help?

**Comment by adiXcodr** [comment]
Could anybody find a solution?

**Comment by shivammaindola** [comment]
Has anybody got the solution?

**Comment by Cosmonaut191** [comment]
Any leads?

**Comment by gogul-ct** [comment]
Any solution?

**Comment by BassamRazzaq100** [comment]
I have the same problem unable to download pdf file. 
After alot of search. I figure out that website is use the following code script to get the downloaded data.
columns: [
                        {data: 'id', name: 'id'},
                        {data: 'patient_name', name: 'patient_name'},
                        {data: 'email', name: 'email'},
                        {data: 'phone', name: 'phone'},
                        {data: 'consultation_type', name: 'consultation_type'},
                        {data: 'category', name: 'category'},
                        {data: 'address', name: 'address'},
                        {data: 'state', name: 'state'},
                        {data: 'date', name: 'date'},
                ]

**Comment by eshernandez** [comment]
Any solution?

**Comment by Vitor-Conti** [comment]
Any Updates? Why is this closed!

**Comment by ZubairAkber** [comment]
I am also facing the same issue, any luck !
