### ISSUE TITLE
Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.11.

### ISSUE THREAD

**Issue by shrekuu** [react-native-community/react-native-webview#299]
I initialized a react-native app with `react-native init xxx` and installed the latest(v4.1.0).  Android Studio could not complete sync. it says:

![image](https://user-images.githubusercontent.com/3136026/52098439-f34d4780-2609-11e9-87a2-58c47aa74607.png)

When I run `react-antive run-android` from console, it says something similar.

![image](https://user-images.githubusercontent.com/3136026/52098321-79b55980-2609-11e9-8464-dae0bf671d1e.png)

I tried to `wget` the kotlin gradle plugin, it was not there. :'(

![image](https://user-images.githubusercontent.com/3136026/52098483-1bd54180-260a-11e9-8f64-d4af5845a105.png)

### How to reproduce?
* Just initialize a react-native(0.58) app
* Run `yarn install react-native-webview` .  // version 4.1.0
* run `react-native run-android`

So this is a deadlink:
https://dl.google.com/dl/android/maven2/org/jetbrains/kotlin/kotlin-gradle-plugin/1.3.11/kotlin-gradle-plugin-1.3.11.pom

I find it's here.
https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-gradle-plugin/1.3.11/kotlin-gradle-plugin-1.3.11.pom

Please Note version 1.3.20 is also available.
https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-gradle-plugin/1.3.20/kotlin-gradle-plugin-1.3.20.pom

**Comment by kwoktung** [comment]
怎么解决这个问题的啊？

**Comment by shrekuu** [comment]
@kwoktung  我移除了配置在 android studio 里的所有关于代理的东西后就好了。

**Comment by TylerPin** [comment]
For my case I hit 
'Gradle: org.jetbrains.kotlin:kotlin-stdlib:1.3.31@jar' already disposed 
I deleted .idea file inside /android , and file-> invalidate caches and restart.
https://stackoverflow.com/a/30707747/1809335

Posting here in case anyone hit the same error

**Comment by wanghe826** [comment]
> For my case I hit
> 'Gradle: org.jetbrains.kotlin:kotlin-stdlib:1.3.31@jar' already disposed
> I deleted .idea file inside /android , and file-> invalidate caches and restart.
> https://stackoverflow.com/a/30707747/1809335
> 
> Posting here in case anyone hit the same error

Saved me, thanks very much !!

**Comment by Damoness** [comment]
> For my case I hit
> 'Gradle: org.jetbrains.kotlin:kotlin-stdlib:1.3.31@jar' already disposed
> I deleted .idea file inside /android , and file-> invalidate caches and restart.
> https://stackoverflow.com/a/30707747/1809335
> 
> Posting here in case anyone hit the same error

Thank you

**Comment by luvnish19** [comment]
Li

> For my case I hit 'Gradle: org.jetbrains.kotlin:kotlin-stdlib:1.3.31@jar' already disposed I deleted .idea file inside /android , and file-> invalidate caches and restart. https://stackoverflow.com/a/30707747/1809335
> 
> Posting here in case anyone hit the same error

Life saving answer
