### ISSUE TITLE
Android: WebView in loading state takes all the screen (can't set height or position)

### ISSUE THREAD

**Issue by llostris** [react-native-community/react-native-webview#301]
We're trying to render a WebView on the screen, leaving a little space at the top for app action bar. However the loading screen from the WebView takes the whole screen, covering the top bar. The same thing happens if we use a custom loading screen (using `renderLoading` prop) or the default one.

I was looking at react-native-community/react-native-webview#216 thinking as it might be related, however none of the suggestion in that issue helped (setting `flex: 0` or `flex: null` didn't change anything), and this problem occurrs only when it comes to the loading screen and only on Android.

Wat the webview screen looks like:
<img width="306" alt="screen shot 2019-02-01 at 2 05 22 pm" src="https://user-images.githubusercontent.com/5892357/52127634-8d24ec80-262a-11e9-926d-bc5fa6e6a2a9.png">
What we expect to see at the top:
<img width="316" alt="screen shot 2019-02-01 at 2 05 47 pm" src="https://user-images.githubusercontent.com/5892357/52127635-8d24ec80-262a-11e9-9ca7-bd3c3513709b.png">

Code rendering the webview and the loading screen:
```
render() {
    let content = (
        <WebView style={styles.webView}
                 originWhitelist={['*']}
                 startInLoadingState={true}
                 // renderLoading={this.renderWebViewLoading}
                 source={this.state.request}/>
      );

    return (
      <SafeAreaView style={styles.container}>
        <NavigationEvents
          onWillFocus={() => this.buildWebViewSource()}/>
        <View style={styles.topBar}>
          <TouchableOpacity onPress={this.close}>
            <Nomicon icon={Nomicon.icons.dismiss}
                     allowFontScaling={false}
                     style={styles.closeButton}/>
          </TouchableOpacity>
        </View>
        {content}
      </SafeAreaView>
    );
  }
```

Styles:
```
 const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  topBar: {
    height: 30,
  },
  closeButton: {
    marginLeft: 15,
    fontSize: 20,
    color: grey60,
  },
  webView: {
    width: width,
    flex: 1,
  },

});
```

**Comment by Titozzz** [comment]
There is a bug since RN 0.57 that makes webview loading overlay everything, just wrap you webview inside a view with overflow: 'hidden'

**Comment by XpressElectricals** [comment]
> There is a bug since RN 0.57 that makes webview loading overlay everything, just wrap you webview inside a view with overflow: 'hidden'

Thanks a lot. Saved my day.
