### ISSUE TITLE
[5.0.0] PostMessage - discrepancy between release notes and source files

### ISSUE THREAD

**Issue by abendi** [react-native-community/react-native-webview#304]
I was super excited to try out this new postMessage implementation, to see if I could finally reach messages sent from the html side. Unfortunately I could not.
Then I checked the committed files and noticed that in the release notes it says: 
`Instead of using window.postMessage(data, *), please now use window.ReactNativeWebView.postMessage(data).`

But in source files it says `JAVASCRIPT_INTERFACE = "ReactNativeWebview"`. Letter "**v**" is not capitalized.

I changed my postMessage calls to `window.ReactNativeWebview.postMessage` but unfortunately it still didn't solve my problem. Thought I'd point it out anyway, if it matters.
@Titozzz

**Comment by Titozzz** [comment]
Thanks I'll check

**Comment by abendi** [comment]
I'm glad I could contribute, my first open-source contribution after all. :stuck_out_tongue:

Too bad the new postMessage implementation didn't fix the problem for me. For some reason I never receive the messages using the new API, but still receive messages using the old way e.g. `setTimeout(function () { window.postMessage(data, "*") }, 1000)`.

**Comment by Titozzz** [comment]
Are you sure you re-built native ?

**Comment by Titozzz** [comment]
@koofka I'm going to release a new version to fix the lower case issue, let's keep WebView everywhere.

**Comment by abendi** [comment]
> 
> 
> Are you sure you re-built native ?

Haha, now that I think about it, no, I only upgraded the node_modules package, but didn't re-install the app on the device. Classic Friday evening.
I'll try your suggestion and get back to you. Thanks. :100:

**Comment by Titozzz** [comment]
@abendi Yeah that Friday was really hard on me too haha. Released the fix. Thank you all for fast reporting

**Comment by abendi** [comment]
> > Are you sure you re-built native ?
> 
> Haha, now that I think about it, no, I only upgraded the node_modules package, but didn't re-install the app on the device. Classic Friday evening.
> I'll try your suggestion and get back to you. Thanks. 💯

After rebuilding the app, everything worked as intended! 💐 Finally we can rip out the hacky postMessage workarounds. Thank you for the suggestion and a quick fix.
