### ISSUE TITLE
Components are hidden on real-android-device with WebView

### ISSUE THREAD

**Issue by in4core** [react-native-community/react-native-webview#309]
```
<View style={{ flex:1 }}>
                <Text style={{color:'red'}}>Test it</Text>
                <WebView
                source={{ uri: 'https://github.com/react-native-community/react-native-webview/blob/master/docs/Reference.md#renderloading'  }}
                startInLoadingState = {true}
                renderLoading = { this.renderLoad }
                onLoadEnd = { this.onLoadEnd.bind(this) }
                style = {{ flex : 1}}
                />
            </View>
```
There is sample - text not shown after WV was loaded.  Some times - text shown.  Also if we use "html" instead of uri - text never show. 
RN 0.58.3 , WV latest

**Comment by in4core** [comment]
Also : if we rotate the device - text will shown

**Comment by AlexejKutsko** [comment]
Try this.

```
<View style={{ flex:1 }}>
                <Text style={{color:'red'}}>Test it</Text>
                <View style={{overflow: 'hidden'}}>
                    <WebView
                        source={{ uri: 'https://github.com/react-native-community/react-native-webview/blob/master/docs/Reference.md#renderloading'  }}
                        startInLoadingState = {true}
                        style = {{ flex : 1}}
                    />
                </View>
            </View>
```


 But you need calculate height webview

**Comment by in4core** [comment]
> Try this.
> 
> ```
> <View style={{ flex:1 }}>
>                 <Text style={{color:'red'}}>Test it</Text>
>                 <View style={{overflow: 'hidden'}}>
>                     <WebView
>                         source={{ uri: 'https://github.com/react-native-community/react-native-webview/blob/master/docs/Reference.md#renderloading'  }}
>                         startInLoadingState = {true}
>                         style = {{ flex : 1}}
>                     />
>                 </View>
>             </View>
> ```
> But you need calculate height webview

Алексей -  это баг все же, а не фича. Планируете править?

**Comment by AlexejKutsko** [comment]
Да, это баг. Мне надо было закрыть проблему. Если это правильное решение проблемы то достаточно в WebViev.android.js в `styles.container` добавить `overflow: 'hidden'`

**Comment by in4core** [comment]
> Да, это баг. Мне надо было закрыть проблему. Если это правильное решение проблемы то достаточно в WebViev.android.js в `styles.container` добавить `overflow: 'hidden'`

```
<View style={styles.flexContainer}>
                <ScreenHeader navigation = { this.props.navigation } header = {this.state.header}/>
                <View style={{ overflow : 'hidden'}}>
                    <WebView
                    source={{ html : this.state.data.body }}
                    startInLoadingState = {true}
                    renderLoading = { this.renderLoad }
                    onLoadEnd = { this.onLoadEnd }
                    style = {{flex : 1, height : 500, width : 400}}
                    ref = { v => this.vebView = v}
                    />
                </View>
            </View>
```
In this case - webView not shown, but other components are shown

**Comment by in4core** [comment]
any suggestions ?

**Comment by sultanularefin** [comment]
@in4core Which mobile phone are you using?

**Comment by sultanularefin** [comment]
I have the same problem when running one my phone (Xiaomi), I tried newer react-native packages but it didn't work on my phone. later I saw this link and performed accordingly and the problem is gone.
https://github.com/react-native-community/react-native-webview#troubleshooting

**Comment by in4core** [comment]
<View style={{overflow: 'hidden', flex : 1}}>  - full fix.  But if u using only <View style={{overflow: 'hidden'}}>  as developer say, - it doesnt work.

**Comment by Titozzz** [comment]
See #2 here : https://github.com/react-native-community/react-native-webview#troubleshooting
