### ISSUE TITLE
[TODO] After Removing UIWebView. (ITMS-90809)

### ISSUE THREAD

**Issue by Titozzz** [react-native-community/react-native-webview#312]
UIWebView is going to be removed as it has been deprecated forever: https://developer.apple.com/documentation/uikit/uiwebview?language=objc

If there are missing features, please comment on this thread and I'll update this comment.
Unless there are real reasons to keep it alive a bit more it will be dropped soon.

EDIT: 29/08/2019 - https://github.com/react-native-community/react-native-webview/issues/819
> ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

This probably means we will have to remove it soon. I'll update the todo and we should all try to close as much as possible

- [ ] cookie management
- [ ] Check #150
- [x] Local files loading issues #137 fonts / resources (fixed in 6.10.0)
- [x] Scale issues? (might be fixed by https://github.com/react-native-community/react-native-webview/issues/312#issuecomment-476553973)
- [ ] anything else?

EDIT: UIWebView has been removed in 7.0.1

**Comment by hippotz** [comment]
For users with devices on iOS 9 and 10 we are stuck using UIWebView because we don't have full control of WKWebView cookies until iOS 11.

**Comment by jerolimov** [comment]
Same here. Our current scenario is to login into an API with `fetch` which sets a cookie. This cookies are also (automatically) available within the UIWebView, not in WKWebView. I played already a little bit with `WKCookieStore`. But this iOS API is only available on iOS 11+.

**Comment by PratibhaSomashekhara** [comment]
Even I have same issue. The authentication works with a fetch call and the server sets a cookie with a http response header. This cookie is then automatically available within the UIWebView, but not in WKWebView.  I want to use WKWebView not UIWebView. I am using iOS 11.4 
#314 . If someone could help me on this then it would be great help

**Comment by PratibhaSomashekhara** [comment]
> Same here. Our current scenario is, that we have a (react) native login screen. The authentification works with a `fetch` call and the server sets a cookie with a http response header. This cookie is then automatically available within the UIWebView, but not in WKWebView. I played already a little bit with `WKCookieStore`. But this iOS API is only available on iOS 11+.

I am using IOS 11.4 but still cookie is not available in WKWebView.

**Comment by PratibhaSomashekhara** [comment]
> UIWebView

My concern is not about UIWebView. I am using WKWebView and cookie is not available inside the WKWebView. I could have used UIWebView but e.nativeEvent.data is coming as  "Object object"  as WebView accepts only string. 
However  to resolve this issue,  I started using  WKWebView by making useWebKit={true} and then my e.nativeEvent.data  comings as expected. example data={name:xyz}
but problem is that cookie is not available within the WKWebView and session gets expired even though i m using IOS 11+.

**Comment by Titozzz** [comment]
We need to work on cookies ✅

**Comment by Titozzz** [comment]
Would something like https://github.com/react-native-community/react-native-webview/pull/175 help @PratibhaSomashekhara @jerolimov @hippotz?

**Comment by hippotz** [comment]
It looks like that PR would help with adding cookies into WKWebView by setting them through JS, but my use case is the reverse of that. I have to read & delete cookies from the WKWebView that are marked HttpOnly so a javascript solution won't work. I don't know if any solution is possible according to apple's docs.

I just looked and we have like 0.1% sessions on iOS < 11. I don't think my use case is worth worrying about! haha

**Comment by jamonholmgren** [comment]
In my opinion, anyone who needs to support UIWebView can use the latest version of this library that still includes it and lock to that version.

**Comment by jmheik** [comment]
We fall back to UIWebView for iOS9 users because of [this bug](https://github.com/react-native-community/react-native-webview/issues/150).

**Comment by PratibhaSomashekhara** [comment]
> Would something like #175 help @PratibhaSomashekhara @jerolimov @hippotz?
> 
> This is >11.0 and <11.0

I tried with PR  #175. still cookies are not available inside the WKWebView. My use case is very simple. my authentication works with a fetch call and the server sets a cookie with a http response header and returns url. 
 I m passing  same  url  into the WKWebView Component and here cookie is not available inside my WKWebView and getting session expired .

**Comment by ralesiupgrade** [comment]
When we use `WKWebView` it doesn't seem to persist any `httponly cookie` so auth doesn't work for us. We have a api that sets the cookie and that is persisted for the life of the session.

**Comment by PratibhaSomashekhara** [comment]
> When we use `WKWebView` it doesn't seem to persist any `httponly cookie` so auth doesn't work for us. We have a api that sets the cookie and that is persisted for the life of the session.

@ralesiupgrade do you have any idea how it could be  resolved ??

**Comment by ralesiupgrade** [comment]
Well `UIWebView` works so whatever thats doing lol. I assume `UIWebView` is just passing all cookies along. Ill take a look at the code and try to see what i find

**Comment by ralesiupgrade** [comment]
hey @PratibhaSomashekhara so https://github.com/react-native-community/react-native-webview/pull/175 did work but only after i tweaked it, I think its the prop for `sharedCookiesEnabled` not being set?

**Comment by HarikaSabbella** [comment]
I'm also noticing that when I remove `useWebKit={false}` the custom font family that I'm passing into the HTML is not being used to render the content in WebView:
```
const HEAD = `
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8">
${getWebViewScaleMetaTag()}
<style type="text/css">
body {
  margin: 10px;
  padding: 0;
  font: 18px 'SourceSansPro-Regular';
}
strong {
  color: ${Colors.faded_blue};
  font: 18px 'SourceSansPro-SemiBold';
  display: block;
  margin-top: 30px;
}
sup { font-size: 9px; }
</style>
</head>
`;

const body = `<!DOCTYPE html />${html.replace('<html>', `<html>${HEAD}`)}`;

<WebView
          originWhitelist={['*']}
          style={styles.webView}
          javaScriptEnabled
          onMessage={(...args) => { this.onBridgeMessage(...args); }}
          source={{ html: body, baseUrl: '' }}
/>
```

**Comment by marconett** [comment]
missing feature for me would be #137.

loading images with wkwebview doesn't work if the image is located in the local file-system (the apps "Documents" directory).
i can only reproduce the problem on device, it works on simulator. loading images from bundle-assets works as well.

**Comment by Titozzz** [comment]
But is it working with UIWebView?

**Comment by marconett** [comment]
> But is it working with UIWebView?

yes

**Comment by GokulDharumar** [comment]
Any updates on the wkwebview sessions issue? We are still not seeing the session not getting carried over the webview.. We are using flag set to false as below

<WebView
                useWebKit={false}/>

**Comment by jamonholmgren** [comment]
@GokulDharumar Do #175 and #181 address the issue you're having, or is it something else?

**Comment by GokulDharumar** [comment]
@jamonholmgren Yes in our web project we are checking for httpession. Looks like when we use useWebKit={false} httpsession getting transferred from our login page to home page. But when we  don't use the flag... the httpsession is not getting transferred to the webview from login screen. I even updated to 5.30 version but with no luck.

Thanks

**Comment by Titozzz** [comment]
@marconett does #403 fixes your issue?

**Comment by marconett** [comment]
@Titozzz just tested it, doesn't fix my problem. the html file itself loads fine, it's images references in html (`<img src="...">`) that aren't.

**Comment by Titozzz** [comment]
@marconett Alright thanks for testing :)

**Comment by GokulDharumar** [comment]
@jamonholmgren Hi any updates on the httpsession issue. We are blocked on iOS for now. Android its working fine

**Comment by jamonholmgren** [comment]
@GokulDharumar Did you test with the branch in #181?

**Comment by fdobre** [comment]
@Titozzz I have a big amount of problems with styles when I enable the webkit:
https://github.com/react-native-community/react-native-webview/issues/447

I still cannot find a way to make the styles scale and work ok. I updated the webview to it's latest version 5.4.2 and still cannot find solutions even for the basic css styles like font-size and font-family.

**Comment by adrienharnay** [comment]
@fdobre Hey, could you try this and tell me how it goes `<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"} />`?

**Comment by fdobre** [comment]
> @fdobre Hey, could you try this and tell me how it goes `<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"} />`?

This seems to work perfect on simulator. I will run some tests on real device and come back with more feedback.

**Comment by robertying** [comment]
I use cookies to open PDF in WebView. 

First I use `fetch` to get my cookies and open WebView afterwards.

It took me hours before finding this issue and realize `WebView` does share cookies with `fetch`, since they are implemented both in native stacks... But not for `WKWebView`!

Changing to `UIWebView` successfully resolved the problem. Guess we may still be stuck at UIWebView for a while.

**Comment by Johncy1997** [comment]
```
<WebView
            source={{uri:PAYMENT_INDEX_URL}}
            scalesPageToFit={false}
            style={{backgroundColor:textColors.white,width:windowWidth,height:windowHeight}}
            onNavigationStateChange={this._onNavigationStateChange.bind(this)}
            javaScriptEnabled = {true}
            domStorageEnabled = {true}
            startInLoadingState={true}
            ref={this.WEBVIEW_REF}
            thirdPartyCookiesEnabled={true}
            useWebKit={true}
            />
```

Here, I am trying to display the website where Amazon payment gateway integrated. But the thing is after logged in to amazon account, it always shows *The session has ended.Please click amazon pay button to sign in again.*. So i thought it may be webview not passing cookies. Someone tell me some possible solution.

**Comment by GokulDharumar** [comment]
@jamonholmgren Cookies are not getting transferred if we don't use useWebKit={false}. We even updated to the latest version 5.8.2. We trying to read the cookies from login page into the home page but it is not working

**Comment by hedikasmanto** [comment]
@GokulDharumar and @Johncy1997 

I had found this cookies problem too, and had solved with add params like this :
<WebView
useWebKit
sharedCookiesEnabled
... />

Source : https://github.com/react-native-community/react-native-webview/blob/master/docs/Reference.md#sharedcookiesenabled

**Comment by GokulDharumar** [comment]
@Johncy1997 Thanks for the message... i think we figured out the issue. we are using https://github.com/joeferraro/react-native-cookies... looks like we have to set up a different way for reading cookies. It works now... thanks for the response

**Comment by Metroidaron** [comment]
Hello,  I too am experiencing this bug where useWebKit does not share its cookies with the react-native instance; Please see the code below for an example of my use case. 

Are there plans to resolve this bug?  It appears that the library mentioned by GokulDharumar (https://github.com/joeferraro/react-native-cookies) may solve the issue but I have not attempted to implement it; and also that library does not appear to be maintained at this time. 

This web view steps through the process of authenticating my users; it's in the background and not displayed to users.  Unfortunately I have to utilize a web view and not a fetch due to how the authentication process is configured; client side redirects. 
```jsx
<ReactNativeWebView
  useWebKit={true}
  sharedCookiesEnabled={true}
  ...Many other Props
  />
/* 
  Auth redirects this web view 7 or 8 times.
  at the end of the redirects, auth cookies have been set
*/
```

Else ware in the codebase.  The fetches I make to api endpoints are receiving a not authorized error because the WebKit web view is not sharing the auth cookies it received from the auth process, with the react native based cookies; UIWebView's do share their cookies successfully;  Other web views in my application are authenticated which indicates that sharedCookiesEnabled is working; but is only sharing with other web views.
```jsx
fetch('apiEndpointUrl', {headers}).then( response => { 
/* Here the response is an error message that the user is not authorized */ 
});
```

**Comment by laurent22** [comment]
Please don't remove UIWebView just yet as it is needed to go around this bug: https://github.com/react-native-community/react-native-webview/issues/376

In my case, with `useWebKit={false}` and `scalesPageToFit={false}`, the view looks as expected:

<img width="164" alt="Capture d’écran 2019-06-14 à 07 35 02" src="https://user-images.githubusercontent.com/1285584/59488496-9d21c800-8e77-11e9-8511-4a6a65aff151.png">

However, with `useWebKit={true}` and `scalesPageToFit={false}`, the zoom is not right.

<img width="164" alt="Capture d’écran 2019-06-14 à 07 36 07" src="https://user-images.githubusercontent.com/1285584/59488512-a874f380-8e77-11e9-97d7-53d9cb5f3526.png">

Either way, the behaviour of `scalesPageToFit` should be consistent between the WebKit and UIWebView implementation, or at least there should be some way to get the old behaviour back if needed. Currently it doesn't seem possible at all to get the right result using WebKit.

**Comment by hedikasmanto** [comment]
@laurent22 

I have solved my problem about using this component, and here are how to solve.. Hope them works on your case

1. Please make sure your cookie have right domain and path. I have found RN WebView on Android can't get cookie if domain is null. On my case.. I have to inject "Set-Cookie" on my backend script for same cookie name with no domain (null) and defined domain for make web, ios, and android working
```
writer.println("Set-Cookie:Token="+token+"; path=/; domain="+domain);
writer.println("Set-Cookie:Token="+token+"; path=/;");
```
2. For zoom problem, I have solve that issue with add viewport meta tag
```
<meta name="viewport" content="width=device-width, initial-scale=1">
```

And here is my WebView props

```
<RNWebView
      useWebKit
      sharedCookiesEnabled
      thirdPartyCookiesEnabled
      mixedContentMode='always'
      javaScriptEnabled
      originWhitelist={['*']}
      source={sourceProps}
      {...props}
    />
```

**Comment by laurent22** [comment]
Thank you @hedikasmanto, this has indeed fixed the issue, at least on iOS. I will check on Android too.

**Comment by laurent22** [comment]
Another reason to keep UIWebView is that it is able to load local images on both iOS and Android, while WebKit cannot on iOS (but it can in Android).

For example, this code works fine in UIWebView:

	const source = {
		html: '<img src="./image.jpg"/>',
		baseUrl: 'file://' + documentDir + '/',
	};

	return <WebView
		useWebKit={false}
		source={source}
		originWhitelist={['file://*', './*', 'http://*', 'https://*']}
		mixedContentMode="always"
		allowFileAccess={true}
	/>

But with `useWebKit={true}` on iOS it doesn't work.

So please keep UIWebView for now, because being able to load images is crucial for our app [Joplin](https://github.com/laurent22/joplin).

**Comment by dbquarrel** [comment]
> Please don't remove UIWebView just yet as it is needed to go around this bug: #376
> 
> In my case, with `useWebKit={false}` and `scalesPageToFit={false}`, the view looks as expected:
> 
> <img alt="Capture d’écran 2019-06-14 à 07 35 02" width="164" src="https://user-images.githubusercontent.com/1285584/59488496-9d21c800-8e77-11e9-8511-4a6a65aff151.png">
> 
> However, with `useWebKit={true}` and `scalesPageToFit={false}`, the zoom is not right.
> 
> <img alt="Capture d’écran 2019-06-14 à 07 36 07" width="164" src="https://user-images.githubusercontent.com/1285584/59488512-a874f380-8e77-11e9-97d7-53d9cb5f3526.png">
> 
> Either way, the behaviour of `scalesPageToFit` should be consistent between the WebKit and UIWebView implementation, or at least there should be some way to get the old behaviour back if needed. Currently it doesn't seem possible at all to get the right result using WebKit.

You might want to see if the code has a <meta viewport> set up. Without that being set, WKWebView will not scale the resulting HTML page correctly.

    <meta name="viewport" content="initial-scale=1.0">

Is what you want to make sure is in the HTML.

Notes: I don't use react, I just got here because I am having various problems with WKWebView in my app, including XPC failures in this object locking the whole app and the fact that it first-time loads about 4x slower than UIWebView due to the cross process communication. There is no good solution for that other than to create a UIWebView before you need it, now this "memory saving implementation" has to hang around forever even when you're not using it because it's too slow to create and destroy on demand.

Good luck everyone.

**Comment by JeremyBradshaw7** [comment]
Need `useWebKit={false}` on iOS for loading custom fonts from local resources.

**Comment by lmeireles** [comment]
Stuck with `useWebKit={false}` as well because of fonts in local resources on iOS, in Android it's working perfectly though.

**Comment by a-kapitonenko** [comment]
Scroll in WebView without `useWebKit={false}` stops quickly. It has a negative effect on User Experience.

**Comment by oleksandr-dziuban** [comment]
@Titozzz I have researched how to enable `scalesPageToFit ` for iOS and found easy solution:
We can emulate scalesPageToFit={true} for iOS: if user passed scalesPageToFit={true} we can just wrap HTML with <html><body></body><html> with meta tag which scales page to fit.
Tested on iOS, works fine, I'm using this way to show pure WEB SVG code in WebView and I need to show it embedded and scaled to bounded box:

```
import React from 'react';
import { WebView } from 'react-native-webview';
import PropTypes from 'prop-types';

/**
 * Wrap SVG string with basic HTML file structure
 * Add meta viewport to zoom to fit the webview scene
 */
const getPreviewHtml = (svg) => (`
  <html lang="en">
    <head>
      <title>SVG preview</title>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <style>
        html, body {
          margin: 0;
          padding: 0;
          height: 100%;
          width: 100%;
          overflow: hidden;
          background-color: transparent;
        }
        svg {
          position: fixed;
          top: 0;
          left: 0;
          height: 100%;
          width: 100%;
          overflow: hidden;
        }
      </style>
    </head>
    <body>
      ${svg}
    </body>
  </html>
`);

const SvgPreview = (props) => (
  <WebView
    source={{ html: getPreviewHtml(props.svg) }}
    style={props.style}
    originWhitelist={['*']}
  />
);

SvgPreview.propTypes = {
  svg: PropTypes.string.isRequired,
  style: PropTypes.oneOfType([
    PropTypes.string, PropTypes.object,
  ]),
};

SvgPreview.defaultProps = {
  style: undefined,
};

export default SvgPreview;
```

**Comment by TranDinhKhang** [comment]
Has this issue fixed? Our app on Apple Store won't be able to be published :( .

**Comment by caioedut** [comment]
Viewport works perfectly on android, but on iOS, are not working for some pages:
![IMG_4318](https://user-images.githubusercontent.com/7034336/64999861-bb0c2800-d8bf-11e9-87b5-215c50e4237d.PNG)

**Comment by alubeck** [comment]
@TranDinhKhang There is no UIWebView usage anymore since version 7.0.1. 

Does your app maybe use Firebase? They have still UIWebView implemented in FirebaseAuth Pods. This probably causes still the deprecated warning by Apple.

**Comment by manish-jain-1** [comment]
I am using `react-native-webview: 5.3.1` and `WKWebView` not working with cookies with `react-native-cookies`.  Here's my sample:

```
               <WebView
                    automaticallyAdjustContentInsets={false}
                    style={styles.webView}
                    source={{ uri: sourceUrl }}
                    javaScriptEnabled
                    domStorageEnabled
                    decelerationRate="normal"
                    startInLoadingState
                    scalesPageToFit
                    useWebKit={true}
                    sharedCookiesEnabled={true}
                    thirdPartyCookiesEnabled
                />
```

Any ideas what is missing?

**Comment by externalshawnhong** [comment]
I'm also facing 

> We need to work on cookies ✅

Any updates on the cookies?

**Comment by CharlesMenier** [comment]
> Hello, I too am experiencing this bug where useWebKit does not share its cookies with the react-native instance; Please see the code below for an example of my use case.
> 
> Are there plans to resolve this bug? It appears that the library mentioned by GokulDharumar (https://github.com/joeferraro/react-native-cookies) may solve the issue but I have not attempted to implement it; and also that library does not appear to be maintained at this time.
> 
> This web view steps through the process of authenticating my users; it's in the background and not displayed to users. Unfortunately I have to utilize a web view and not a fetch due to how the authentication process is configured; client side redirects.
> 
> ```js-jsx
> <ReactNativeWebView
>   useWebKit={true}
>   sharedCookiesEnabled={true}
>   ...Many other Props
>   />
> /* 
>   Auth redirects this web view 7 or 8 times.
>   at the end of the redirects, auth cookies have been set
> */
> ```
> 
> Else ware in the codebase. The fetches I make to api endpoints are receiving a not authorized error because the WebKit web view is not sharing the auth cookies it received from the auth process, with the react native based cookies; UIWebView's do share their cookies successfully; Other web views in my application are authenticated which indicates that sharedCookiesEnabled is working; but is only sharing with other web views.
> 
> ```js-jsx
> fetch('apiEndpointUrl', {headers}).then( response => { 
> /* Here the response is an error message that the user is not authorized */ 
> });
> ```

I'm facing the same problem, did you find any workaround to fix it ?

**Comment by flashman2** [comment]
WKWebView seems still can't load images when use local html file as described [here](https://github.com/react-native-community/react-native-webview/issues/312#issuecomment-503754654) 
And UIWebView is already deprecated. Very frustrating because this is critial feature for our app. :(

**Comment by haivn822** [comment]
> @Johncy1997 Thanks for the message... i think we figured out the issue. we are using https://github.com/joeferraro/react-native-cookies... looks like we have to set up a different way for reading cookies. It works now... thanks for the response

hello, could you tell me the different way you set up for reading cookies? 
tks

**Comment by laurent22** [comment]
> EDIT: UIWebView has been removed in 7.0.1

So there are still pending issues but it was removed anyway?

**Comment by flashman2** [comment]
> So there are still pending issues but it was removed anyway?

Exactly :(

**Comment by marconett** [comment]
@laurent22 i'm having the same potential problem with a couple of my apps. until the deprecation in april for new apps and december for existing apps (https://developer.apple.com/news/?id=12232019b), you're fine just using and older version of this lib.

i haven't tested it yet, but https://github.com/react-native-community/react-native-webview/issues/137#issuecomment-542790814 claims that the issue was fixed in 6.10.0. did you test that?

someone also posted a smart workaround here: https://github.com/react-native-community/react-native-webview/issues/1179#issuecomment-588383090

given that the fix from #137 doesn't work and apple deprecating uiwebivew for new apps in a month from now, it would be awesome to get a heads up from @Titozzz (or other maintainers), if we can expect this to be looked into, or if we need to start looking for workarounds.

**Comment by JeremyBradshaw7** [comment]
> given that apple will deprecate uiwebivew for new apps in a month from now

That's only brand new apps is it, rather than upgrade to existing apps? I'll have to keep using v6.x in our existing app until there's a workaround for using local resources in the latest version, hopefully I can without apple rejecting new builds.

**Comment by ZeerakHameem32** [comment]
I saw some of us are still facing this issue, [this](https://github.com/react-native-community/react-native-webview/issues/819#issuecomment-596946722) is how I managed to resolve this. Hope this helps someone.

**Comment by marconett** [comment]
I looked into the local content loading problem. Didn't find a perfect solution, but a couple of workarounds, please see https://github.com/react-native-community/react-native-webview/issues/1179#issuecomment-597187252.

**Comment by tanhao8** [comment]
提交到appstore uiwebVIew已经过时了，请问怎么解决呢？

**Comment by tanhao8** [comment]
Submitting to Appstore uiwebview is out of date. How can I solve it?

**Comment by bneigher** [comment]
hey maintainers, we only have a few more days until new apps won't be able to submit to the app store with your library.  Can we reopen this?  Would be willing to help as I'm sure others would be too

**Comment by benjipott** [comment]
@bneigher , you can just yarn patch-package to update the lib directly

**Comment by luco** [comment]
Im also getting this. Using version 9.4.0

**Comment by jamonholmgren** [comment]
Hey all, apologies for the radio silence here. We're a bit overextended as maintainers, but I'm here now looking into this.

**Comment by jamonholmgren** [comment]
@bneigher @benjipott @luco Can you give me more information about what the issue is? UIWebView is not in this code base anymore, so you shouldn't be getting rejected for it.

**Comment by MoOx** [comment]
If I am correct rejecting will only start in December this year. For now it's just a warning.

**Comment by charkour** [comment]
@MoOx I believe my new app was rejected right after uploading it to App Store Connect. The build was uploaded, Apple sent me an email regarding UIWebView, and my build disappeared from App Store Connect. It is possible apps already in the App Store will not be rejected until December but I do not know.

**Comment by luco** [comment]
@jamonholmgren Sure, my issue was with an older firebase version. Upgrading it fixed the issue.

**Comment by paulmasters** [comment]
Any update on this?
https://github.com/react-native-community/react-native-webview/issues/1053
It still seems to be broken
