### ISSUE TITLE
getViewManagerConfig is not a function in ejected expo project

### ISSUE THREAD

**Issue by maxkordiyak** [react-native-community/react-native-webview#316]
i created new project using `expo init` then immediately `expo eject` following the second option `ExpoKit: I'll create or log in with an Expo account to use React Native and the Expo SDK`
i'm getting this error after any interaction with the webview

has anyone ever encountered the same issue before?
![error](https://user-images.githubusercontent.com/17858349/52273099-6b40a800-2951-11e9-8a07-8a5c357cddd8.png)

**Comment by Titozzz** [comment]
What is your react-native version?

**Comment by maxkordiyak** [comment]
react-native version was the one specified by expo:
` "react-native": "https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz"`
but after i came across [this solution](https://github.com/wix/react-native-navigation/issues/314#issuecomment-426770444) i changed it to `"react-native": "~0.55.2"`

**Comment by Titozzz** [comment]
this webview only support 0.57 and higher so it is probably related, any reason not to upgrade?

**Comment by maxkordiyak** [comment]
i tried initializing project and ejecting again, ran `react-native link react-native-webview` and after clicking webview ui element i get this error
![error1](https://user-images.githubusercontent.com/17858349/52277032-66cdbc80-295c-11e9-8da6-21524ae0ebb5.png)

**Comment by Titozzz** [comment]
You are right, From 5.0.3, react-native 0.58 is needed 🤔 . I not sure what would be the best approach

**Comment by Titozzz** [comment]
In the meantime, I'll at least update readme and package.json.

**Comment by Titozzz** [comment]
I'll fix soon

**Comment by Titozzz** [comment]
Released 5.0.5
