### ISSUE TITLE
ios webview backgroundColor is always white

### ISSUE THREAD

**Issue by imelos** [react-native-community/react-native-webview#318]
`style={{ backgroundColor: '#000' }}` or `style={{ backgroundColor: 'black' }}`  doesn't  work in ios. WebView still remains the white.

**Comment by jamonholmgren** [comment]
Can you provide a reproduction app so we can easily see this happening?

**Comment by imelos** [comment]
> Can you provide a reproduction app so we can easily see this happening?

https://snack.expo.io/rkXyxQdVE 
I omitted WebView's `source` prop for demonstration purposes

**Comment by Jimmy-YMJ** [comment]
Here is my code
react native version 0.58.4
react-native-webview version 5.2.0

```jsx
import React, { Component } from 'react';
import { Text, View, TouchableOpacity } from 'react-native';
import { WebView } from 'react-native-webview';

const webViewBackgroundColor = '#23577E';

export default class App extends Component {
  constructor(props) {
    super(props);
    this.state = {
      showWebView: false,
    };
  }
  renderWebView() {
    if (!this.state.showWebView) return null;
    return (
      <WebView
        style={{ height: 200, backgroundColor: webViewBackgroundColor }}
        source={{ html: `<!DOCTYPE html><html lang="en"><body style="background-color: ${webViewBackgroundColor};color: white;font-size: 30px;"><h1>Hey</h1></body></html>` }}
      />
    );
  }
  render() {
    const { showWebView } = this.state;
    return (
      <View style={{
        flex: 1,
        backgroundColor: 'rgb(71,174,255)'
      }}>
        <View style={{ height: 200, justifyContent: 'center', alignItems: 'center' }}>
          <TouchableOpacity
            style={{ backgroundColor: '#841584' }}
            onPress={() => this.setState({ showWebView: !showWebView })}>
            <Text>Toggle</Text>
          </TouchableOpacity>
        </View>
        <View style={{ flex: 1, backgroundColor: webViewBackgroundColor }}>
          {this.renderWebView()}
        </View>
      </View>
    );
  }
}
````
Set the View(direct container of WebView), WebView and html background color to #23577E, background color should not change when toggle the WebView element, but it changed.

**Comment by elyngved** [comment]
I found a possible workaround for this when using a URI. I render a WebView component, hiding it with styling, but it's still mounted so it can load the web page. I inject JS code that posts a message back to the React handler, which then unhides webview. This JS is executed on window.onLoad (I think?).

This way I can configure my desired background color on the container which is shown before page load. I haven't experienced a white flash with this technique, but I also haven't tested it in production. Curious to see if it works for others.

```js
const injectedJavaScript = `
window.ReactNativeWebView.postMessage('pageLoaded');
true;
`;

class WebViewScreen extends Component {
  state = {
    loaded: false
  }

  webViewMessageHandler = (event) => {
    if (event.nativeEvent.data === 'pageLoaded') {
      this.setState({
        loaded: true
      })
    }
  }

  render() {
    return (
      <SafeAreaView style={{ backgroundColor: '#000' }}>
        <WebView
          style={this.state.loaded || { flex: 0, height: 0, opacity: 0 }}
          originWhiteList={['*']}
          source={{ uri: 'http://www.google.com' }}
          injectedJavaScript={injectedJavaScript}
          onMessage={this.webViewMessageHandler}
        />
      </SafeAreaView>
    )
  }
}
```

**Comment by jamonholmgren** [comment]
Thanks for the repro! I'd love to see a PR helping us fix this. Happy to test when you do.

**Comment by CubeSugar** [comment]
# about @elyngved 's workaround:

General Speaking, there is no need to set webview invisible during loading by using `{flex: 0}` yourself. WebView handles visibility by itself, see these [lines](https://github.com/react-native-community/react-native-webview/blob/455e22e3b3b4d4751e4f114409a7e89416e1cfdd/js/WebView.ios.js#L214-L221) at __js/WebView.ios.js__:

```
    const webViewStyles = [styles.container, styles.webView, this.props.style];
    if (
      this.state.viewState === WebViewState.LOADING ||
      this.state.viewState === WebViewState.ERROR
    ) {
      // if we're in either LOADING or ERROR states, don't show the webView
      webViewStyles.push(styles.hidden);
    }
```

# a simple solution to change webview's backgroundColor

1. set the webview's `backgroundColor` to 'transparent`
2. webview will use/inherit the background color of it's super container. 
3. change the container view's `backgroundColor` to what u want.

Try the demo:

```typescript
import React from 'react';
import {
    View,
    Text,
    StyleSheet,
} from 'react-native';
import {WebView} from 'react-native-webview';

interface AppProps {
};

interface AppState {
    webviewBackgroundColor: string;
};

export default class App extends React.Component<AppProps, AppState> {
    constructor(props) {
        super(props);
        this.state = {
            webviewBackgroundColor: 'transparent',
        }
    }
    render() {
        const {
            webviewBackgroundColor,
        } = this.state;
        return (
            <View style={{flex: 1, backgroundColor: 'purple'}}>
                <WebView
                    //useWebKit={false}
                    style={{flex: 1, backgroundColor: webviewBackgroundColor}}
                    source={{uri: 'https://google.com'}}
                    onLoad={() => {
                        this.setState(() => {
                            return {
                                webviewBackgroundColor: 'white', // override container's backgroundColor
                            }
                        })
                    }}
                />
            </View>
        );
    }
};
```

**Comment by dsemenov** [comment]
react-native version 0.59.9
react-native-webview version 5.12.0

@CubeSugar Thank you for the solution! But for me it always starts with the white background before becoming transparent, resulting in an unpleasant flickering. Especially annoying on dark backgrounds. Is there anything I can do to avoid it?

```javascript
<View style={{ flex: 1, backgroundColor: 'purple' }}>
    <WebView
        source={{ uri: 'https://google.com' }}
        style={{
            flex: 1,
            backgroundColor: 'transparent',
        }}
    />
</View>
```

![Jun-20-2019 12-41-13](https://user-images.githubusercontent.com/27815/59843731-6eb15a80-9359-11e9-9ef1-f3f7a1599653.gif)

@Titozzz Sorry, may I ask why this was closed?

**Comment by marconucara** [comment]
react-native version 0.60.0
react-native-webview version 6.3.1

Same white flickering problem for me. Avoided using opacity 0 while loading, but this is a bit ugly.

**Comment by bhaavika** [comment]
@marconucara, I am using the same react native and react native webview version as yours and setting the opacity to 0 adds the background color I want but then nothing loads of the webview, I mean the HTML content of the webview is now hidden by the opacity.

Please help, this white screen flickering issue is really annoying.

**Comment by marconucara** [comment]
> @marconucara, I am using the same react native and react native webview version as yours and setting the opacity to 0 adds the background color I want but then nothing loads of the webview, I mean the HTML content of the webview is now hidden by the opacity.
> 
> Please help, this white screen flickering issue is really annoying.

You should change opacity after first loading, that's how I do it:

In View wrapper:
`opacity: this.state.loaded ? 1 : 0,` <- `loaded` initial value is `false`

In WebView:

```
  onLoadEnd={(e) => {
    if (!this.state.loaded) {
      this.setState({ loaded: true });
    }
  }}
```

**Comment by Visakeswaran** [comment]
For those of you still facing this issue, I found a workaround by injecting JS into by webview
`<WebView
                  originWhitelist={['*']}
                  style={{
                    resizeMode: 'cover',
                  }}
                  source={{url}}
                  injectedJavaScript={`window.document.querySelector('body').style.backgroundColor = 'red'`}
/>`

**Comment by twiking** [comment]
> react-native version 0.59.9
> react-native-webview version 5.12.0
> 
> @CubeSugar Thank you for the solution! But for me it always starts with the white background before becoming transparent, resulting in an unpleasant flickering. Especially annoying on dark backgrounds. Is there anything I can do to avoid it?
> 
> ```js
> <View style={{ flex: 1, backgroundColor: 'purple' }}>
>     <WebView
>         source={{ uri: 'https://google.com' }}
>         style={{
>             flex: 1,
>             backgroundColor: 'transparent',
>         }}
>     />
> </View>
> ```
> 
> ![Jun-20-2019 12-41-13](https://user-images.githubusercontent.com/27815/59843731-6eb15a80-9359-11e9-9ef1-f3f7a1599653.gif)
> 
> @Titozzz Sorry, may I ask why this was closed?

This fix solved my issue after days of debugging. Thanks!

**Comment by twiking** [comment]
> I found a possible workaround for this when using a URI. I render a WebView component, hiding it with styling, but it's still mounted so it can load the web page. I inject JS code that posts a message back to the React handler, which then unhides webview. This JS is executed on window.onLoad (I think?).
> 
> This way I can configure my desired background color on the container which is shown before page load. I haven't experienced a white flash with this technique, but I also haven't tested it in production. Curious to see if it works for others.
> 
> ```js
> const injectedJavaScript = `
> window.ReactNativeWebView.postMessage('pageLoaded');
> true;
> `;
> 
> class WebViewScreen extends Component {
>   state = {
>     loaded: false
>   }
> 
>   webViewMessageHandler = (event) => {
>     if (event.nativeEvent.data === 'pageLoaded') {
>       this.setState({
>         loaded: true
>       })
>     }
>   }
> 
>   render() {
>     return (
>       <SafeAreaView style={{ backgroundColor: '#000' }}>
>         <WebView
>           style={this.state.loaded || { flex: 0, height: 0, opacity: 0 }}
>           originWhiteList={['*']}
>           source={{ uri: 'http://www.google.com' }}
>           injectedJavaScript={injectedJavaScript}
>           onMessage={this.webViewMessageHandler}
>         />
>       </SafeAreaView>
>     )
>   }
> }
> ```

This fix finally solved my issue after days of debugging 👍

**Comment by erkie** [comment]
I found this thread because I was using `startInLoadingState={true}` and found that the default `renderLoading` renders a spinning indicator with a white background.

https://github.com/react-native-webview/react-native-webview/blob/master/src/WebView.styles.ts#L24

Using a custom `renderLoading` callback fixed the majority of white flashes for me.

**Comment by Andrew-Chen-Wang** [comment]
For anyone who uses `source: {html: '' }` or is willing to just download the html and use `source: {html: '' }`, then you can add in a string along with your source html:

```html
${darkMode ? '<meta name="color-scheme" content="dark light">' : ''}
```

Combine that string with the html you're about to inject. The meta tag should be inside a head tag (though IIRC it can also be in a body tag, though it's been awhile since I tried).

**Comment by Andrew-Chen-Wang** [comment]
Anyone who is wondering how to use Erkie's solution, add this prop in your WebView component:

```javascript
import {ActivityIndicator} from 'react-native';
<WebView startInLoadingState={true} renderLoading={() => <ActivityIndicator size="large" />} />
```

**Comment by fdcgoncalves** [comment]
`import React from 'react';
import { useState } from 'react';
import { View, StyleSheet, ActivityIndicator } from 'react-native';
import { WebView } from 'react-native-webview';


export default function WebviewScreen() {
  const [show, setShow] = useState(false);

  return (
    <View style={styles.container}>
      <WebView
        startInLoadingState={true}
        renderLoading={() => <ActivityIndicator color="#FFFFFF" style={styles.loader} />}
        style={[styles.container, { display: show ? 'flex' : 'none' }]}
        source={{ uri: 'https://www.google.com/' }}
        onLoad={() => setShow(true)}
      />
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "red"
  },
  loader: {
    flex: 1
  },
});`

**Comment by hengsok** [comment]
> ```js
> import React from 'react';
> import { useState } from 'react';
> import { View, StyleSheet, ActivityIndicator } from 'react-native';
> import { WebView } from 'react-native-webview';
> 
> 
> export default function WebviewScreen() {
>   const [show, setShow] = useState(false);
> 
>   return (
>     <View style={styles.container}>
>       <WebView
>         startInLoadingState={true}
>         renderLoading={() => <ActivityIndicator color="#FFFFFF" style={styles.loader} />}
>         style={[styles.container, { display: show ? 'flex' : 'none' }]}
>         source={{ uri: 'https://www.google.com/' }}
>         onLoad={() => setShow(true)}
>       />
>     </View>
>   );
> };
> 
> const styles = StyleSheet.create({
>   container: {
>     flex: 1,
>     backgroundColor: "red"
>   },
>   loader: {
>     flex: 1
>   },
> });
> ```

Best solution that works!

**Comment by imyzf** [comment]
I met the same problem. And there is a property `opaque` for WkWebView to make background transparent. I find RNWebView to set opaque depending on backgroundColor's alpha (https://github.com/react-native-webview/react-native-webview/blob/master/apple/RNCWebViewImpl.m#L679). 

So just pass `<WebView style={{ backgroundColor: 'rgba(255, 255, 255, 0)' }} />`  to fix it. If you don't want the background to be transparent, you can pass `rgba(xxx, yyy, zzz, 0.999)`.

**Comment by nikodunk** [comment]
> <WebView style={{ backgroundColor: 'rgba(255, 255, 255, 0)' }} />

This worked wonderfully for me just now, no other solutions or hacks necessary. Thank you!
