### ISSUE TITLE
Not allowed to load local resource when using source: htmlString

### ISSUE THREAD

**Issue by Mukul-Sharma** [react-native-community/react-native-webview#319]
Web page is located in DocumentDir and tries to access files with absolute path but in the same folder, it works when using source with uri parameter but failed when using source html: htmlString, Could someone point me in the right direction for this? Already spent two hours looking :(

**Comment by Mukul-Sharma** [comment]
Solve by using baseUrl

**Comment by Bernabe-Felix** [comment]
@Mukul-Sharma Could you put a screenshot of the solution? Thanks!

**Comment by jamonholmgren** [comment]
I'd really like it if you wanted to write up a guide and send a PR to our docs!
