### ISSUE TITLE
Setting onMessage on a WebView overrides existing values of window.postMessage

### ISSUE THREAD

**Issue by hxiongg** [react-native-community/react-native-webview#324]
Using v5.0.6 with RN 0.57.29
I get the above titled error whenever the webview opens. Changing the uri to https://www.google.com doesn't post a problem. Is it because the current uri is being redirected?

``` js
const injectedJavascript = `window.ReactNativeWebView.postMessage('hi');`;
onMessage(event) {
    console.log(event.nativeEvent.data);
  }
<WebView useWebKit={false} source={{ uri: 'https://login.microsoftonline.com/' }}
 injectedJavaScript={injectedJavascript} onMessage={this.onMessage} />
```

**Comment by Titozzz** [comment]
You sure you rebuilt native after updating?

**Comment by tapir** [comment]
It's `window.ReactNativeWebview.postMessage` not `window.ReactNativeWebView.postMessage`

**Comment by Titozzz** [comment]
@tapir I was only ReactNativeWebview by mistake in 5.0.0 and was fixed instantly to ReactNativeWebview as specified in the patch notes.

Please also avoid this kind of messages. I maintain this in my free time without any remuneration, calling my work ridiculous is just... w/e

**Comment by tapir** [comment]
> @tapir I was only ReactNativeWebview by mistake in 5.0.0 and was fixed instantly to ReactNativeWebview as specified in the patch notes.
> 
> Please also avoid this kind of messages. I maintain this in my free time without any remuneration, calling my work ridiculous is just... w/e

Definitely didn't want to call your *work* ridiculous. I'm sorry it sounded that way. I do appreciate your work. It's just that I value compatibility above everything else and was surprised to notice it by *chance*.

**Comment by bhagwandas** [comment]
Saved my day. Could not notice that in version 5.0.0 and documentation, this is spelt differently.

@Titozzz Thanks a lot for maintaining it. I see that you have been very active in helping all of us here.
