### ISSUE TITLE
Using  assets fonts in webview css on ios

### ISSUE THREAD

**Issue by punksta** [react-native-community/react-native-webview#326]
Hello
I am trying to load a font from app assets

```
type fontFormats = "ttf" | "otf";

export const generateAssetsFontCss = (
	fontFamily: string,
	fileFormat: fontFormats = "ttf"
) => {
	const fileName = Platform.select({
		ios: `file:///assets/fonts/${fontFamily}.${fileFormat}`,
		android: `file:///android_asset/fonts/${fontFamily}.${fileFormat}`
	});

	return `@font-face {
		font-family: '${fontFamily}';
		src: url("${fileName}")
}`;
};
```

```
<WebView
	style={{height: 100, width: 100}}
	onLoadEnd={e => alert(JSON.stringify({error: e.nativeEvent}))}
	onError={e =>
		alert(
			JSON.stringify({
				error: e.nativeEvent
			})
		)
	}
	onMessage={e =>
		alert(
			JSON.stringify({
				message: e.nativeEvent
			})
		)
	}
	originWhitelist={['*']}
	mixedContentMode={"always"}
	useWebKit={true}
	startInLoadingState={true}
	injectedJavaScript={generateInjectCssScript(
		generateAssetsFontCss("fontName", "otf")
	)}
	source={{
		html: `<div style='font-family: fontName; font-size: 21px'>custom font</div>
			<div style='font-size: 21px'>default font</div>`
	}}/>
```
it's working fine on android, but not on ios. 
I am getting the error `Not allowed to load local resource: file:///assets/fonts/fontName.otf`
the font is linked and available in react-native styles.

I tried using this css:
`src: local('${fontFamily}'),url('${fontFamily}.${fileFormat}');` 
I didn't have error in this case, but font didn't apply to text. I also tried some solutions form stackoverflow and related issues.

**Comment by HarikaSabbella** [comment]
Seeing same issue as above--is there a fix for this?

**Comment by punksta** [comment]
@HarikaSabbella when you use "useWebKit={true}` are they rendered? Is `SourceSansPro-SemiBold` a font you added using "react-native link"?

**Comment by HarikaSabbella** [comment]
@punksta The screen is still rendered, however, in iOS, it is rendered using some other font instead of the specified `SourceSansPro-SemiBold` font.  In Android, content is rendered correctly with the `SourceSansPro-SemiBold` font.

**Comment by punksta** [comment]
@Titozzz Hi, you don't now workaround for ios? it seems you are ios developer.

**Comment by punksta** [comment]
the problem I have is: our app has multiple fonts for different languages. and I want webview to read them from native assets. Nether from from base64, nor from api to minimize app size and improve performance.

**Comment by zarcode** [comment]
+1

**Comment by ljuborados** [comment]
Had the same issue, managed to get around it by using base64 fonts, not really the same as the bundled assets but it works!

**Comment by nguyen95** [comment]
I had the same issue. Does anyone have any solution?

**Comment by punksta** [comment]
This function worked for us in rn 0.57 
```
type fontFormats = "ttf" | "otf";

/**
 * example of usage:
  
  const originalHtml = "<div/>"
  const css = generateAssetsFontCss("Roboto-Dark", "ttf")
 
  const html = addCssToHtml(originalHtml, css)
 * 
 * @param fontFileName - font name in resources
 * @param fileFormat - ttf or otf
 * @returns {string} - css for webview
 */
export const generateAssetsFontCss = (
	fontFileName: string,
	fileFormat: fontFormats = "ttf"
) => {
	const fileUri = Platform.select({
		ios: `${fontFileName}.${fileFormat}`,
		android: `file:///android_asset/fonts/${fontFileName}.${fileFormat}`
	});

	return `
	@font-face {
        	font-family: '${fontFileName}';
        src: local('${fontFileName}'), url('${fileUri}') format('${
		fileFormat === "ttf" ? "truetype" : "opentype"
	}');
	}
	`;
};
```

**Comment by nguyen95** [comment]
@punksta  It work! Thank you so much! I think this line is the hit point: 
src: local('${fontFileName}'), url('${fileUri}') format('${fileFormat === "ttf" ? "truetype" : "opentype"}');
It is the same way Google suggested

**Comment by SaeedZhiany** [comment]
@punksta 

below is my html style section that is going to render in webview but my font isn't bind to the page again. (this is for android, I didn't test for ios yet (with `file:///FONT_NAME.ttf`))

Can you please share a complete code of your solution? (include those props that you have passed to webview component)

Another question: Is your solution works on both Android and IOS platforms?

```
<style media="screen" type="text/css">
    @font-face {
        font-family: 'moein';
        font-style: normal;
        src: local('moein'), url("file:///android_asset/fonts/FONT_NAME.ttf") format("truetype");
    }
</style>
```

**Comment by SaeedZhiany** [comment]
@punksta 

below is my html style section that is going to render in webview but my font isn't bind to the page again. (this is for android, I didn't test for ios yet (with `file:///FONT_NAME.ttf`))

Can you please share a complete code of your solution? (include those props that you have passed to webview component)

Another question: Is your solution works on both Android and IOS platforms?

```
<style media="screen" type="text/css">
    @font-face {
        font-family: 'FONT_NAME';
        font-style: normal;
        src: local('FONT_NAME'), url("file:///android_asset/fonts/FONT_NAME.ttf") format("truetype");
    }
</style>
```

**Comment by gsanchez10** [comment]
hello @punksta, how do you add that function?

**Comment by ersefuril** [comment]
Does anyone succeeded to do the trick from @punksta with a recent version of react-native-webview on iOS ?
Looks like the only workaround is to use inline base64 font or set `source={{baseUrl: "", html: "..."}}` which is not nice at all.

**Comment by maduraherath8** [comment]
> Does anyone succeeded to do the trick from @punksta with a recent version of react-native-webview on iOS ?
> Looks like the only workaround is to use inline base64 font or set `source={{baseUrl: "", html: "..."}}` which is not nice at all.

is it working?

**Comment by darknessproduction** [comment]
Made it working. Tested only on IOS
```
import React from 'react'
import { useEffect, useState } from 'react'
import { Platform } from 'react-native'
import AutoHeightWebView from 'react-native-autoheight-webview'

export const generateAssetsFontCss = (fontFileName, fileFormat) => {
    const fileUri = Platform.select({
        ios: `${fontFileName}.${fileFormat}`,
        android: `file:///android_asset/fonts/${fontFileName}.${fileFormat}`
    });

    return `
    @font-face {
            font-family: '${fontFileName}';
        src: local('${fontFileName}'), url('${fileUri}') format('${
        fileFormat === "ttf" ? "truetype" : "opentype"
    }');
    }
    `;
}

export const generateWebViewText = (title, width) => {
    const css = generateAssetsFontCss("Montserrat-Bold", "ttf")
    let str = `<html><head><style type="text/css">`+css+`</style></head><body>
    <h1 style="width: `+width+`px;font-size: 24px;line-height: 29px;font-family: 'Montserrat-Bold';background: -webkit-linear-gradient(#45E994, #23BCBA);-webkit-background-clip: text;-webkit-text-fill-color: transparent;">
    `+title+`
    </h1>
    </body></html>`;
    return <AutoHeightWebView source={{baseUrl: "", html: str}} />
}
```

**Comment by trajano** [comment]
@darknessproduction  where do you store your fonts?

**Comment by darknessproduction** [comment]
@trajano 
ProjectFolder/assets/fonts/
ProjectFolder/react-native.config.js

react-native.config.js
```
module.exports = {
  project: {
    ios: {},
    android: {}, // grouped into "project"
  },
  assets: ["./assets/fonts/"], // stays the same
};
```

**Comment by darknessproduction** [comment]
ttfs

**Comment by trajano** [comment]
> @trajano
> ProjectFolder/assets/fonts/
> ProjectFolder/react-native.config.js
> 
> react-native.config.js
> 
> ```
> module.exports = {
>   project: {
>     ios: {},
>     android: {}, // grouped into "project"
>   },
>   assets: ["./assets/fonts/"], // stays the same
> };
> ```

thanks.  so you're not using expo-google-fonts.  I actually got the iOS one to work, just have to find out the equivalent for Android

**Comment by Martinlindblad** [comment]
What worked for me: 
  
```
const HEAD = `
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8">
<style type="text/css">
@font-face {
      font-family: "Roboto";
      src: local('Roboto'), url('https://fonts.cdnfonts.com/s/12165/Roboto-Regular.woff') format('woff');
}
body {
 padding: 50 20 20 30;
 font-family: 'Roboto';
 background-color: #E5E5E5;
 font-size: xx-large;
}
</style>
</head>
`;
  const body = `<!DOCTYPE html />${yourHTML.replace(
    '<html>',
    `<html>${HEAD}`,
  )}`;`

  <WebView
   source={{
        html: body,
    }} />
```
          
It is possible to use your local path as src aswell.

**Comment by jerinwega** [comment]
peeps why complicate? rather than trying so hard to use the downloaded font... just
    @import url('https://fonts.googleapis.com/css2?family=Lato:wght@400;700&display=swap'); (any font)
to your css style and use it like  
font-family: 'Lato', sans-serif;
font-weight: 700;

**Comment by trajano** [comment]
@jerinwega https://wicki.io/posts/2022-02-goodbye-google-fonts-data-privacy-gdpr/

**Comment by jerinwega** [comment]
> @jerinwega https://wicki.io/posts/2022-02-goodbye-google-fonts-data-privacy-gdpr/

seriously !

**Comment by redionSpace** [comment]
export const injectedStyle = `<head>
  <style>
@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@500&display=swap');
    body {
      margin-left: 24px;
      margin-right: 24px;
    }
    * {
      font-size: 1.9rem !important;
      color: white !important;
      margin: 0 !important;
      padding: 0 !important;
   font-family: 'Poppins', sans-serif !important;
    }
  </style>
</head>`;

 <WebView
          originWhitelist={['*']}
          contentContainerStyle={styles.contentContainerStyle}
          useWebKit={true} // not sure this plays a role
          onMessage={onWebViewMessage}
          source={{
            html: injectedStyle + '<span>' + value + '</>' || '',
          }}
          style={{
            backgroundColor: Colors.transparent,
          }}
          scrollEnabled={false}
          nestedScrollEnabled={false}
        />

**Comment by trajano** [comment]
@redionSpace the OP wanted it from the assets not from remote.  His reason may be the same as me https://github.com/react-native-webview/react-native-webview/issues/326#issuecomment-1379876499

In my case I did work around the legal issue by serving the font from my own servers rather than Google.
