### ISSUE TITLE
Support Android file upload

### ISSUE THREAD

**Issue by Titozzz** [react-native-community/react-native-webview#33]
There are already a lot of forks of the official webview to support that feature, there is no reason not to add it to that repo.

Let review all of them and we can discuss about implementation here.

**Comment by jamonholmgren** [comment]
One reference is `react-native-webview-android`: https://github.com/lucasferreira/react-native-webview-android#note-about-html-file-input-files-upload

**Comment by andreipfeiffer** [comment]
@Titozzz do you have any good development workflow on how to use react-native-webview package in an example RN project, but from an external folder?
