### ISSUE TITLE
onLongPress?

### ISSUE THREAD

**Issue by pepya2** [react-native-community/react-native-webview#331]
have looked everywhere how to implement onLongPress in react-native-webview, unfortunately no one has posted a solution on how to do it.. i would like to trigger custom context menu (just a modal) on link long press since currently, onLongPress even on links nothing happens, doesn't navigate to that link. In short, onLongPress doesn't do click event nor show any context menus.

I have even wrapped WebView inside a View, and wrapped a View inside TouchableWithoutFeedback, so that i can trigger onLongPress, this also has issues - WebView doesn't scroll..

is there any way around this?..

**Comment by Ehesp** [comment]
This would need to be handled within the website loaded inside of the webview - the website needs to detect the long press and use [event](https://github.com/react-native-community/react-native-webview/blob/master/docs/Reference.md#onmessage) handler.
