### ISSUE TITLE
Request for maintainers to not break backward compatibility in ways that are impossible by developers to debug

### ISSUE THREAD

**Issue by tapir** [react-native-community/react-native-webview#334]
With version 5.0.1 `window.ReactNativeWebview` is renamed to `window.ReactNativeWebView`.
I understand that the first one is a mistake but it doesn't make it right for developers to just change it.

Think for a second from the perspective of the developers. It's such a small change that it's almost impossible to notice. If I haven't looked at commits I wouldn't notice it at all and I've spent hours on iOS why it stopped working again.
This is frustrating not because it's a typo but because how it's handled. The correct way to handle it would be to create an alias so that both versions would work. Then it could be deprecated and documented properly (communicated to developers).

This might look like a rant from an angry developer who just spent hours debugging a silly thing but it really is not. I'm just trying to hopefully convince some of you that *not* breaking compatibility is not necessarily a lost art and in today's conditions is still a very nice thing to have.

**Comment by Titozzz** [comment]
Literally, 5.0.0 has been up for 2 hours. I fixed it during the night to make sure no one would have these issues hopefully. I even deprecated 5.0.0 from NPM so you would get a warning by using it. I'm sorry for any inconvenience caused but the changelog mentioned the right way to spell it from the start. I even have detailed patch notes for everything...

I guess next time I'll do 6.0.0 😞

**Comment by tapir** [comment]
Understood. I was waiting for postMessage fix for a very long time so It was an instant update to 5.0.0 for me. Possibly I'm the only one affected by this :)
