### ISSUE TITLE
determine if bridge is ready

### ISSUE THREAD

**Issue by weepy** [react-native-community/react-native-webview#339]
Sorry if a duplicate, but can't make sense of the other issues. I have iOS RN app with a webview and recently I was using the `postMessage.length == 1` trick to determine if the bridge was ready, but now it doesn't work (i.e. it always returns 2) ... 

Did something change ? ...

**Comment by Titozzz** [comment]
Yes. We no longer override window.postMessage to keep thing clean. You can watch window.ReactNativeWebView(.postMessage). Please see https://github.com/react-native-community/react-native-webview/releases/tag/v5.0.0
