### ISSUE TITLE
Loading state different behaviour iOS / Android

### ISSUE THREAD

**Issue by mtt87** [react-native-community/react-native-webview#343]
We noticed the loading activity indicator when `startInLoadingState` is set to `true` was behaving differently
- with iOS it stays there correctly until the page is fully loaded
- with Android it stays for just a few milliseconds then disappears

I've added `console.log(this.state.viewState)` on the render of `WebView.android.js` and `WebView.ios.js` and basically there is a different behaviour

To reproduce
```js
<WebView
  onLoadStart={() => console.log('load start')}
  onLoadEnd={() => console.log('load end')}
  onLoadProgress={(e) => console.log('progress', e.nativeEvent.progress)}
  source={{ uri: 'https://www.google.com' }}
/>
```

On iOS it will show just 2 states `LOADING` and `IDLE` when the page has finished to load.
![screenshot 2019-02-14 at 18 05 53](https://user-images.githubusercontent.com/2150927/52807435-5d8ecf00-3083-11e9-8bfb-92d3f0d6992a.png)

On Android it shows `LOADING` and then just after a few milliseconds `IDLE` but then again `IDLE` at the end.
![screenshot 2019-02-14 at 18 05 25](https://user-images.githubusercontent.com/2150927/52807498-8747f600-3083-11e9-8444-3bc663d508e5.png)

Also the methods `onLoadStart` and `onLoadEnd` seem to be inconsistent in what they output.

Tested with both `react-native@0.57.8`
```
        buildToolsVersion = "27.0.3"
        minSdkVersion = 16
        compileSdkVersion = 27
        targetSdkVersion = 26
        supportLibVersion = "27.1.1"
```

and `react-native@0.58.4`
```
    ext {
        buildToolsVersion = "28.0.2"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 27
        supportLibVersion = "28.0.0"
    }
```

This package `react-native-webview@5.2.0`

**Comment by Titozzz** [comment]
Hello, thanks for the detailed issue. If you wish to contribute even more, feel free to submit a pull request, or maybe someone else can do it 😊

**Comment by mtt87** [comment]
Sure, this was what we found out today after some investigation.

The only downside is that both me and my colleague are JS devs with almost zero knowledge of native Android platform so we got a bit scared this might be outside our skills, but surely we will have a look and see if we can spot the issue.

Any tips on where to investigate further or read specific Android documentation would be great.

Thank you

**Comment by cjcheshire** [comment]
Hey @Titozzz (colleague of @mtt87 here).

I have found if we introduce a setState in the start method it fixes our issue.

```
  onLoadingStart = (event: WebViewNavigationEvent) => {
    const onLoadStart = this.props.onLoadStart;
    onLoadStart && onLoadStart(event);
    this.setState({
      viewState: WebViewState.LOADING,
    });
    this.updateNavigationState(event);
  };
```
Whilst this fixes the issue (and sort of makes sense) an alarm bell is ringing in my head that something outside of JS is triggering the idle state. Especially as iOS doesn't require the state setup like the above.

Happy to PR if you think the above is okay.

**Comment by Titozzz** [comment]
Well I think we would need to better understand why the state changes only on Android instead of patching. I'll try to dig a bit. 

By the way the navigation state is managed purely JS side even if it is triggered from the native side so you should be able to debug by logging everywhere the state changes

**Comment by cjcheshire** [comment]
Yea I figured it didn’t really solve the real issue. @mtt87 console output attachment shows IDLE but no load after a new request. IDLE is set on finish or error so something is telling it it’s done but once a new page is triggered to load it doesn’t set the LOADING again.

**Comment by smathson** [comment]
Looked into this today and it looks like the WebViewClient's `onPageFinished` is not the event to be hooking into to know when the page and all included JS execution/rendering is concluded. See: https://stackoverflow.com/a/14611465

Looks like a better way to handle this would be to call `emitFinishEvent` when the WebChromeClient `onProgressChanged` reaches 100. I don't have the time to try and implement and test this at the moment, but maybe it will help someone who does.

**Comment by XingtianXin** [comment]
same issue on Android 9 device.

`        <WebView
          style={styles.webviewArea}
          originWhitelist={['*']}
          startInLoadingState
          javaScriptEnabled
          automaticallyAdjustContentInsets
          allowUniversalAccessFromFileURLs
          onLoad={() => {
            console.warn('onLoad :'+ xxtcount)
            xxtcount= xxtcount +1
          }}
          onLoadEnd={() => console.warn('onLoadEnd')}
          onLoadStart={() => console.warn('onLoadStart ')}
          onLoadProgress={(e) => console.warn('progress', e.nativeEvent.progress)}
          source={{uri:faqUrlValue,method: 'GET',headers: faqHeaders}}
          renderLoading={() => {
            console.warn('renderLoading ')
            return <ActivityIndicator size="large" color="#0000ff" />
          }}
          {...prop}
        />`
the  print log order is below 
`readerloading
renderLoading
onLoadStart
onLoad
onLoadEnd
progress 0.1000000149
progress 0.21999999
onLoadStart
progress 1
progress 1
onLoad
onLoadEnd`

i don't know why the onLoad lifecycle functions run twice.
device: samsung note8 
platform: android 9.0
react-native: 0.59.10
react-native-webview: 5.12.1

**Comment by frags51** [comment]
Still looking for solutions!

**Comment by dcisneros94** [comment]
If anyone has any solutions towards fixing the timing on android, please share.
