### ISSUE TITLE
SafariViewController replacement component

### ISSUE THREAD

**Issue by SamSaffron** [react-native-community/react-native-webview#345]
SafariViewController is a giant problem, Apple have been working on it for years yet basics like this are still broken:

https://stackoverflow.com/questions/52848408/are-there-any-workaround-to-avoid-sfsafariviewcontroller-from-hiding-fixed-posit

Additionally there are cookie issues and more that make SVC a pretty rough ride for embedders. 

Replacing SVC with webview is not a drop-in thing, cause you need to recreate the collapsing navigation which is not trivial. 

I was wondering if it is within the scope of this project to create an SVC clone that can easily be dropped into projects and simply fix the many year old SVC issues?

Since we highly depend on SVC for https://github.com/discourse/DiscourseMobile this is work we would be happy to sponsor financially so hit me up if you are wanting to take this up (either as part of this project if approved or in a separate one) https://samsaffron.com/about

**Comment by Titozzz** [comment]
Hello I think this belongs into another repository as this is a different native component to achieve a different goal..
