### ISSUE TITLE
Improve extensibility on Android

### ISSUE THREAD

**Issue by jeluard** [react-native-community/react-native-webview#346]
It would be nice to make sure the default `RNCWebViewManager` can be extended in a deeper and cleaner way.

Some suggestions:

* relax visibility of internal static classes to allow extension by public classes (e.g. `RNCWebViewManager.RNCWebView`)
* rely on generics to reduce the need of casts

**Comment by Ehesp** [comment]
Due to inactivity I'll close this issue. Please feel free to continue the conversation, or submit a PR and we'll review 👍
