### ISSUE TITLE
Viewport width is not respected

### ISSUE THREAD

**Issue by Return-1** [react-native-community/react-native-webview#349]
### Platform: Android

The viewport meta tag does not seem to be supported in its entirety. While zooming is properly disabled, changing the width property makes a difference on a webview on android developed natively but not through this component

```<meta name=“viewport” content=“width=405 user-scalable=no”/>```

PS : The idea behind the fixed 405 is that its an appropriate width on which the UI looks sensible on mobile

**Comment by Return-1** [comment]
It seems like `scalesPageToFit` set to false resolves the issue on Android. Im still unsure as to what it does under the hood but im leaving this here for future reference

**Comment by Titozzz** [comment]
Does #275  help fixing your bug ?

**Comment by Return-1** [comment]
i'd consider the issue to be fixed. im unsure as to why though. i'll mark the issue as closed
