### ISSUE TITLE
Reload by changing source

### ISSUE THREAD

**Issue by expressiveco** [react-native-community/react-native-webview#350]
It is possible to get webview reloaded by changing an unrelated property of source. Even it is refreshed for same url.
``` js
render()
{
return (
<WebView source={{uri: this.state.url, forceReload:this.state.forceReload}} />);
}

refreshWebview()
{
this.setState({forceReload:!this.state.forceReload});
}
```
So, how could this be possible? Changing some other property of webview does not trigger refresh.

Component renders always but it does not re-create the native webview always but just when that unrelated property of source changes I think. I am just curious about internals.

**Comment by Titozzz** [comment]
Sorry, I'm not sure about what you are trying to achieve 🤔

**Comment by expressiveco** [comment]
Actually, i understand what is happening. I was toggling the value of WebView.bounces to get WebView refreshed but it has no effect on Android because it is only available for IOS Android WebView.
So, it does not change the rendered Native WebView so nothing is updated.

So, when i try with some other property like geolocationEnabled, it worked.

Thus, i think, similarly, changing some property on source makes it treated as a change to source object and causes an update.

**Comment by expressiveco** [comment]
@Titozzz could you please check [https://stackoverflow.com/questions/54738360/how-does-react-native-props-diffing-work](https://stackoverflow.com/questions/54738360/how-does-react-native-props-diffing-work)
