### ISSUE TITLE
Mouse Support For WebView ??

### ISSUE THREAD

**Issue by Rob2k9** [react-native-community/react-native-webview#351]
I have the webview installed in my android TV application witch i have tested on the amazon fire stick and nvidia shield but its almost impossible to navigate 

I have looked at other browsers avalable for both platforms and i can see that on the shield the right joystick can be moved to create a mouse pointer on screen for selecting eliments and the same can happen on firestick with the use of the mouse toggle app i have also see other apps such as AFTV Downloader using a mouse function in there browser to allow for better navigation

is this possible in react-native-webview or would it be possible to have added to this great modual ?

**Comment by Ehesp** [comment]
Hello - I'm not sure this is in scope for this module. PRs are welcome however it's not something we'll be able to proactively look into.
