### ISSUE TITLE
onNavigationStateChange not called when programmatically calling webviewRef.goBack()

### ISSUE THREAD

**Issue by chaudhryjunaid** [react-native-community/react-native-webview#354]
Consequently I cannot maintain an updated value for canGoBack for backHandler.

**Comment by chaudhryjunaid** [comment]
This happens for some urls and not for others. I'm investigating what specifics cause this.

**Comment by Titozzz** [comment]
related to #291? or to #24?

**Comment by chaudhryjunaid** [comment]
it's definitely not #24. May be it is #291 but not sure since not sure what's happening inside the browser. I think the urls are distinct. goBack() doesn't fire for some of the cases.

**Comment by chaudhryjunaid** [comment]
What's pushstate routing @Titozzz ? I'll try to get back to you if you explain what's in #291?

**Comment by chaudhryjunaid** [comment]
Yes, it's push state routing. It's actually Pjax! @Titozzz is there no option other than `postMessage`?

**Comment by yamgemy** [comment]
The boolean value of canGoBack is available at `onLoadEnd `and `onLoad` and i am using it to handle `goBack()` fine.
```
<WebView
  source={{ uri: 'https://facebook.github.io/react-native' }}
  onLoadEnd={syntheticEvent => {
    const { nativeEvent } = syntheticEvent;
    this.setState({canGoBack:nativeEvent.canGoBack});
  }}
/>
```

**Comment by kaushikwavhal** [comment]
I am still searching for solutions for this issue.
