### ISSUE TITLE
Android postMessage does not working

### ISSUE THREAD

**Issue by peymancyb** [react-native-community/react-native-webview#356]
Hello, i am sending message from webview to react native , but from react native the message does not send to the webview

**Comment by cristianomesquita** [comment]
send like that: window.ReactNativeWebView.postMessage

**Comment by peymancyb** [comment]
@cristianomesquita  thank you for the response, I have use `window.ReactNativeWebView.postMessage` for sending messages from webview to react native, but from the react native part i can not send messages to the webview.

**Comment by lifan-github** [comment]
The same problem

**Comment by tbenr** [comment]
same here

**Comment by sadvit** [comment]
I have the same issue for iOS 

Call webView.postMessage don't lead to fire 'message' event inside webView

Version:
react-native-webview@5.2.0
react-native@0.58.4

**Comment by sadvit** [comment]
I've got the solution 

Inside webView we need to use:

this.window.addEventListener('message', ....) ----- It's worked for me right now
instead of 
this.document.addEventListener('message', ....) ---- it's worked in older version for me

Good luck!

**Comment by iddan** [comment]
`window` works for me as well. This is a breaking change from past implementation!!!

**Comment by SuGod** [comment]
I have the same problem. `onMessage` cannot receive messages. Switch to the webview on react-native and it should work.

"react-native-webview": "^5.2.1",
"react": "16.6.3",
"react-native": "0.58.4",

**Comment by iddan** [comment]
For people coming here: `document` for Android, `window` for iOS

**Comment by fauno** [comment]
Hi, I'm trying to send messages from the WebView to Android but onMessage isn't triggered.  I can see the initial "Hi!" and the view is filled with "hi" every second to test js inside the WebView, but the console doesn't show anything.  I'm using RN 0.57.7 with WV 5.2.1, also tried `document` as @iddan says but it doesn't work either...

```javascript
import React, { Component } from 'react';
import { WebView } from 'react-native-webview';

export class Registro extends Component {
  render () {
    return (
      <WebView
        style={{ flex: 1 }}
        onMessage={data => console.log(data)}
        onError={error => console.log(error)}
        cacheEnabled={false}
        allowsLinkPreview={false}
        originWhitelist={['*']}
        javaScriptEnabled={true}
        source={{ html: '<html><body><h1>Hi!</h1><script type="text/javascript">setInterval(function() { document.write(" hi"); document.ReactNativeWebView.postMessage("hi");}, 1000);</script></body></html>' }}
        />
    );
  }
}
```

**Comment by fauno** [comment]
nevermind, got it to work with `onMessage={event => console.log(event.nativeEvent.data)}` :)

**Comment by romreed** [comment]
@fauno not work for me 
can you show me please full example
 "react-native-webview": "^5.2.1"
 "react-native": "0.58.4",
`<WebView
                                    mixedContentMode='always'
                                    source={{
                                        uri: this.state.chosenCityUrl,
                                        "Accept-Language": navigator.language,
                                        "User-Agent": Platform.OS,
                                    }}
                                    javaScriptEnabled={true}
                                    ref={(b) => this._bridge = b}
                                    style={styles.webView}
                                    onError={(error) =>{ console.log("error",error); return NetInfo.isConnected.fetch().done(isConnected => this.setState({isConnected}))}}
                                    onLoadEnd={() => this.onLoadEnd()}
                                    renderError={() => this.renderError()}
                                    onNavigationStateChange={this._onNavigationStateChange.bind(this)}
                                    // onMessage={event => console.log(event)}
                                    domStorageEnabled={true}
                                    originWhitelist={['*']}
                                    allowsLinkPreview={false}
                                     injectedJavaScript='
                                    setInterval(function() { document.postMessage("hi"); document.ReactNativeWebView.postMessage("hi", "*");
                                    window.postMessage("hi"); window.ReactNativeWebView.postMessage("hi", "*");
                                    }, 1000);
                                     alert("start");'
                                />`

**Comment by punksta** [comment]
https://github.com/react-native-community/react-native-webview/blob/master/docs/Guide.md#communicating-between-js-and-native
you can find `injectJavaScript` useful. @peymancyb

**Comment by peymancyb** [comment]
Thank you @punksta but what i need is postMessage feature and still this feature does not work on android devices

**Comment by Titozzz** [comment]
You can literally replicate the undocumented postMessage functionality by following the guide above. 🤔 If you want to receive a message on the window you can inject a function that does just that.

**Comment by fauno** [comment]
romreed <notifications@github.com> writes:
> // onMessage={event => console.log(event)}

just 2 extra cents.  i spent a few hours wondering why this wasn't
working and for some reason `console.log(event)` doesn't log anything,
but `console.log(event.nativeEvent.data)` does.

**Comment by romreed** [comment]
@fauno Thank you. I not check your idea but all begin work. I am not understand reason.

"react": "16.6.3",
    "react-native": "0.57.7",
    "react-native-webview": "^5.2.1"
`
<WebView
                                    source={{
                                        uri: HOME_URL,
                                        "Accept-Language": navigator.language,
                                        "User-Agent": Platform.OS,
                                    }}
                                    javaScriptEnabled={true}
                                    ref={(b) => this._bridge = b}
                                    style={styles.webView}
                                    onError={(error) => {
                                        console.log("error", error);
                                        return NetInfo.isConnected.fetch().done(isConnected => this.setState({isConnected}))
                                    }}
                                    onMessage={event => console.log(event.nativeEvent.data)}
                                    injectedJavaScript="document.addEventListener('scroll', function (event) {window.ReactNativeWebView.postMessage(JSON.stringify(document.getElementsByClassName('topconteiner')[0].scrollTop));},true);true;"/>
`

**Comment by Titozzz** [comment]
@romreed "topconteiner" seems like a typo, could this be the issue?

**Comment by romreed** [comment]
@Titozzz It's just for my site. You can use 
```javascript
injectedJavaScript="document.addEventListener('scroll', function (event) {window.ReactNativeWebView.postMessage(JSON.stringify(document.documentElement.scrollTop||document.body.scrollTop));}"
```

**Comment by dhrupalG** [comment]
issue the code

**Comment by mausworks** [comment]
> For people coming here: `document` for Android, `window` for iOS

WHY!?

**Comment by Frindecent** [comment]
to **send** an event to **ios webview** use listener as window.addEventListener in your ios html.
to **send** an event to **android webview** use listener as document.addEventListener in your android html.

to **recieve** an event in **ios and android - react native** use as window.ReactNativeWebView.postMessage(data); in your html.

**Comment by ankitwandx** [comment]
in android webview,  `document.addEventListener` does not work for me. I have to use `window.addEventListener`. BUT, they **MessageEvent** that I receive, do not have the data sent from RN. 

`
window.addEventListener("message", function (event) {
console.log(event.data) // null
...
`

**Comment by donaldking** [comment]
For anyone struggling with this, here is an elegant solution:

```Javascript
      const receiver = isUIWebView() ? window : document;
      receiver.addEventListener('message', data => {
       // do something
      });
```

**Comment by n0umankhan** [comment]
this is how i am sending my message to webview

`if (Platform.OS !== 'android') {
      webviewref.current.postMessage('start');
    } else {
      const postmessage = `window.postMessage('start','*'); true`;
      webviewref.current.injectJavaScript(postmessage);
    }`

just keep in mind that you have to pass domain parameter "*" or "domain.com" while posting message. it's good if you can pass for IOS as well but yeah it will work in this way too.

and this is how i'm receiving message in webview
`
window.addEventListener(
				'message',
				message => {
					if (message.data === 'start') {
						setTimeout(() => {
							startGame();
						}, 500);
					}
				},
				false
			);
`

**Comment by ticketapp** [comment]
> For anyone struggling with this, here is an elegant solution:
> 
> ```js
>       const isUIWebView = () => {
>         return navigator.userAgent.toLowerCase().match(/\(ip.*applewebkit(?!.*(version|crios))/)
>       };
> 
>       const receiver = isUIWebView() ? window : document;
> 
>       receiver.addEventListener('message', data => {
>        // do something
>       });
> ```

Thanks buddy, it saved me a lot a times :)

**Comment by YangShaoXiong** [comment]
> For people coming here: `document` for Android, `window` for iOS
thanks a lot

**Comment by mausworks** [comment]
Here's a simplified version of the same code. To note with the old code: `String.match` returns an array of matches (or `null`). This code just sets a boolean value.

```
const isUIWebView = /\(ip.*applewebkit(?!.*(version|crios))/i.test(navigator.userAgent);
const receiver = isUIWebView ? window : document;

receiver.addEventListener('message', data => { });
```

**Comment by andreialecu** [comment]
You can also just attach the event handler to both instead of trying to detect the user agent.

```js
[window, document].forEach(
  el => el.addEventListener('message', (e) => {
    
  }
);
```

**Comment by terryatgithub** [comment]
> to **send** an event to **ios webview** use listener as window.addEventListener in your ios html. to **send** an event to **android webview** use listener as document.addEventListener in your android html.
> 
> to **recieve** an event in **ios and android - react native** use as window.ReactNativeWebView.postMessage(data); in your html.



> to **send** an event to **ios webview** use listener as window.addEventListener in your ios html. to **send** an event to **android webview** use listener as document.addEventListener in your android html.
> 
> to **recieve** an event in **ios and android - react native** use as window.ReactNativeWebView.postMessage(data); in your html.

you saved my day.

**Comment by omerkarakose** [comment]
Hello, this issue is closed but we found another solution. Both android and iOS can work with like below:

`window.addDocumentListener('message', onMessage, true)`

Third boolean parameter is default false, when we pass it true it's working on android too.

Reference: https://www.w3schools.com/jsref/met_document_addeventlistener.asp

**Comment by rileymiller** [comment]
> Hello, this issue is closed but we found another solution. Both android and iOS can work with like below:
> 
> `window.addDocumentListener('message', onMessage, true)`
> 
> Third boolean parameter is default false, when we pass it true it's working on android too.
> 
> Reference: https://www.w3schools.com/jsref/met_document_addeventlistener.asp

Think you meant `window.addEventListener('message', onMessage, true)`

Updating to ^^ got things working on iOS and android for us if anyone is stumbling upon this issue

**Comment by bmeeder22** [comment]
Hello, 

After trying these different approaches: 
`window.addEventListener('message', onMessage, true)`

and 

`document.addEventListener('message', onMessage)`

Neither of these are working for being able to `postMessage` to android.

**Comment by inf3rnus** [comment]
Same problem

**Comment by inf3rnus** [comment]
> 

Hey, FYI, try this out, seems to be working for me 

```
webViewRef.current.injectJavaScript(`
              window.ReactNativeWebView.postMessage(JSON.stringify({ works: "LOWER HERE" }));
              `);
```

**Comment by lumpenop** [comment]
> 



> Hello,
> 
> After trying these different approaches: `window.addEventListener('message', onMessage, true)`
> 
> and
> 
> `document.addEventListener('message', onMessage)`
> 
> Neither of these are working for being able to `postMessage` to android.

Hey, try this on Android and iOS

window.addEventListener("message",(e) => alert(String(e.data)), true);

**Comment by mamicrose** [comment]
> For anyone struggling with this, here is an elegant solution:
> 
> ```js
>       const isUIWebView = () => {
>         return navigator.userAgent.toLowerCase().match(/\(ip.*applewebkit(?!.*(version|crios))/)
>       };
> 
>       const receiver = isUIWebView() ? window : document;
> 
>       receiver.addEventListener('message', data => {
>        // do something
>       });
> ```

where do we add this?

**Comment by AMoktar** [comment]
> Hello, this issue is closed but we found another solution. Both android and iOS can work with like below:
> 
> `window.addEventListener('message', onMessage, true)`
> 
> Third boolean parameter is default false, when we pass it true it's working on android too.
> 
> Reference: https://www.w3schools.com/jsref/met_document_addeventlistener.asp
> 
> Edit : Thanks @rileymiller to fix typing

this worked for me.
thanks @omerkarakose

**Comment by MarieAngeLeslie** [comment]
> Hello, this issue is closed but we found another solution. Both android and iOS can work with like below:
> 
> `window.addEventListener('message', onMessage, true)`
> 
> Third boolean parameter is default false, when we pass it true it's working on android too.
> 
> Reference: https://www.w3schools.com/jsref/met_document_addeventlistener.asp
> 
> Edit : Thanks @rileymiller to fix typing


This 100% work for me in 2024 (by adding 3rd parameter 'true')

**Comment by NeverGone97** [comment]
add 2  this line to webview work for me 
javaScriptEnabled={true}
domStorageEnabled={true}
