### ISSUE TITLE
Migrate Documentation

### ISSUE THREAD

**Issue by jamonholmgren** [react-native-community/react-native-webview#36]
Documentation is currently contained here:

https://facebook.github.io/react-native/docs/webview

We should migrate all existing WebView documentation to this repository soon.

My personal preference is that we create a folder (`./docs`) of markdown documents so that pull requests can contain documentation updates as well. I'm happy to discuss other alternatives, though. This is an example of another project I created where we did that: https://github.com/infinitered/ProMotion/tree/master/docs/Reference

**Comment by Titozzz** [comment]
I think we should use some tool to have a nice looking documentation instead of just some MD files, I know there are plenty out there, I'm thinking we could use gitbook, as it's free for oss

**Comment by jamonholmgren** [comment]
I've used tools like that before (including gitbook). They're pretty nice, but in my opinion we should hold off until we see a real need for it, and stay with a simple docs folder until then.
