### ISSUE TITLE
Auto focus & zoom in - iOS issue

### ISSUE THREAD

**Issue by mydesweb** [react-native-community/react-native-webview#365]
1. open the URL in the webview (OK)
2. close the app
3. reopen the app from background (THE PROBLEM HERE) - the webview will automatically open the keyboard, the first input get focus and zoom in is made 

`      <WebView
                    useWebKit={true}
                    style={{flex: 1, backgroundColor: '#fff'}}
                    source={{uri: 'https://www.mydavy.ie'}}
                    startInLoadingState={true}
                    renderLoading={this.renderLoading}
                />`

![ezgif com-resize](https://user-images.githubusercontent.com/5901386/53571447-a2c9fb00-3b71-11e9-9126-02154b3591d1.gif)

**Comment by legion-zver** [comment]
@mydesweb You can track the transition to the background mode and lock (or unmount) WebView

**Comment by mydesweb** [comment]
@legion-zver I agree with you, I can do this as a workaround for the moment but I think that is a issue with the webview that should be fixed in feature

**Comment by tallpants** [comment]
@mydesweb does this happen on Android too? Or just iOS?

**Comment by mydesweb** [comment]
@tallpants on Android is working just fine, the first field input get focus but no zoom in and the keyboard is shown only if I click on the field

**Comment by jamonholmgren** [comment]
Thanks @mydesweb ; any ideas on how this might be fixed?

**Comment by CubeSugar** [comment]
I notice that at the bottom of [login page](https://www.mydavy.ie/login.htm) source codes, there is a line:

  `$("#username").focus(); `

This may be the reason webview auto focus & zoom.

--- 

Steps to reproduce:

1. touch a __index.html__ file, and append codes below:

```html
<!DOCTYPE html>
<html>
<head>
  <title></title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=10">
  <script src="https://cdn.staticfile.org/jquery/1.10.2/jquery.min.js">
  </script>
</head>
<body>
  <input type="text" id="username" value="Text field.">
  <script>
	$(document).ready(function() {
		$("#username").focus();  // target line
	});
  </script>
</body>
</html>
```

2. start a file server, by using `python -m SimpleHTTPServer 30001` or other ways u prefer.

3. open iOS Safari

  - check `http://<your-ip>:30001/`
  - enter background
  - reopen Safari

4. comment the **target line** and repeat step 3.

**Comment by legion-zver** [comment]
@mydesweb If you set useWebkit = {false} The problem remains?

**Comment by mydesweb** [comment]
@legion-zver I noticed that only if I explicitly set useWebKit={false} (which is weird) auto focus & zoom will not happen, but on click on any input it is the same behavior. I had a chance to test the same scenario on a native implementation (actually I rewrite the app on react native) and it is working well, but I can't say how they did the implementation because I am not an iOS dev

**Comment by Titozzz** [comment]
2 solutions: 
https://stackoverflow.com/a/6394497/4022333
---
https://stackoverflow.com/a/13706151/4022333

**Comment by mydesweb** [comment]
@Titozzz are you sure that there is a no flag/option for the web view to disable scaling? and why if if I explicitly set useWebKit={false} works different ?

**Comment by annjawn** [comment]
This is a problem and what if the page is a Google form? The form behaves properly in Android Webview but in iOS it simply zooms in as soon as a form field is in focus. Also, from what I see `useWebkit` isn't a prop anymore. And none of the stackoverflow solutions would work in this case.

**Comment by potatoengineer** [comment]
Any update to this? Having an issue where my login form is zooming in when tapping an input field and after hitting **Done** to dismiss the keyboard the form shifts to the right and it gets clipped.

**Comment by anujraghuvanshi** [comment]
I am using content editable html in webview and getting issue like this. When I tap on any line of paragraph, the webview zooms and set itself to fit the page. And I dont want this behaviour. Any suggestions ? How I can fix it ?

I tried setting the meta tag, yet its not fixed.

I don't want it to auto zoom but I want user can do it manually.

Any other workaround/helps ?

**Comment by regalstreak** [comment]
https://stackoverflow.com/a/64685265/6740333

Worked for me. Probably try setting the empty `onMessage` handler
