### ISSUE TITLE
onMessage function doesn't call but calls from default RN

### ISSUE THREAD

**Issue by iagorm** [react-native-community/react-native-webview#367]
## Description
I tried to call onMessage function and it doesn't trigger, the sample in front end: 
```window.postMessage(JSON.stringify({ loading: true }));```

In this package the onMessage doesn't call but when I import the WebView from 'react-native' it works, also `onShouldStartLoadWithRequest` doesn't work.

## Version
Package version: 5.2.1
React Native version: 0.58.0

## Reproduce problem:

Simply render an html with ```window.postMessage(JSON.stringify({ loading: true }));``` and try to get the data from `onMessage`.

**Comment by iagorm** [comment]
if call ```["ReactNativeWebView"]postMessage(JSON.stringify({ loading: true }));``` instead, it will work.

**Comment by Carl0395** [comment]
I worked with `window.ReactNativeWebView.postMessage(JSON.stringify({ loading: true }));`

**Comment by iagorm** [comment]
> I worked with `window.ReactNativeWebView.postMessage(JSON.stringify({ loading: true }));`

@Carl0395 You can do this either, I was just following the code inside of the library.
