### ISSUE TITLE
Webview.postMessage has inconsistent behavior on android and ios

### ISSUE THREAD

**Issue by wangxu724** [react-native-community/react-native-webview#369]
Trying to post message from react native to webview and the behavior is inconsistent.
Looking at the code found the cause:
on iOS, in RNCWKWebView.m, function 'postMessage', it's
window.dispatchEvent

on Android, in RNCWebViewManager.java, function 'receiveCommand', it's
document.dispatchEvent

Please make it consistent.

**Comment by Titozzz** [comment]
I'm going to remove postMessage in favor of injectJavascript postMessage is not even documented and offer less customization

**Comment by timhonders** [comment]
For future reference, this is how we fixed this using injectJavaScript:

const javascript = `(function() {
	try {
	 var event = new MessageEvent('message', {
			"data": "Youre data here",
			"origin": "*"
		});
		document.dispatchEvent(event);
	} catch (e) {

	}
})()`;

this.webview.injectJavaScript(javascript);
