### ISSUE TITLE
iOS app cannot scrolling after upgrade to react-native-webview v5.2.3

### ISSUE THREAD

**Issue by thanhcuong1990** [react-native-community/react-native-webview#371]
Hi, 
I cannot scrolling webview after upgrade to the last version 5.2.3.
My app using react-native 0.58.6
I've to rollback to version 5.2.1 to make it works.

**Comment by Titozzz** [comment]
Thanks for the report, let me test, might be because of https://github.com/react-native-community/react-native-webview/pull/158
