### ISSUE TITLE
react-native-webview onScroll Listener 

### ISSUE THREAD

**Issue by romreed** [react-native-community/react-native-webview#374]
I'm try to set handler onscroll but nothing happend. 
*  "react-native-webview": "^5.2.1"
*  "react-native": "0.57.7"

> <WebView
                                        source={{
                                            uri: this.state.chosenCityUrl,
                                            "Accept-Language": navigator.language,
                                            "User-Agent": Platform.OS,
                                        }}
                                        javaScriptEnabled={true}
                                        ref={(b) => this._bridge = b}
                                        injectedJavaScript="window.onscroll=function(){alert("Not WORK");}"
//injectedJavaScript='window.addEventListener("scroll", function(e) { alert("Not WORK"); });
                                    />

**Comment by guhungry** [comment]
injectedJavaScript="window.onscroll=function(){alert("Not WORK");};true;"

Please add `;true;` because `injectedJavaScript` need to eval as true

**Comment by romreed** [comment]
@guhungry Thank you for answer but nothing change.

`  <WebView
                                        source={{
                                            uri: this.state.chosenCityUrl,
                                        }}
                                        javaScriptEnabled={true}
                                        ref={(b) => this._bridge = b}
                                        style={styles.webView}
                                      injectedJavaScript="window.onscroll=function(){alert('Not WORK');};true;"
                                    />`

**Comment by jamonholmgren** [comment]
@romreed I confirmed that your code did indeed work. (I used a different website, of course.)

![image](https://user-images.githubusercontent.com/1479215/53937830-23ea2c00-4063-11e9-9d97-0d30e0dfba60.png)

**Comment by romreed** [comment]
@jamonholmgren I don't know why but this work for me
```javascript
<WebView
                                    source={{
                                        uri: this.state.chosenCityUrl,
                                        "Accept-Language": navigator.language,
                                        "User-Agent": Platform.OS,
                                    }}
                                    javaScriptEnabled={true}
                                    ref={(b) => this._bridge = b}
                                    style={styles.webView}
                                    onError={(error) => {
                                        console.log("error", error);
                                        return NetInfo.isConnected.fetch().done(isConnected => this.setState({isConnected}))
                                    }}
                                    onLoadEnd={(e) => this.onLoadEnd(e)}
                                    renderError={() => this.renderError()}
                                    onNavigationStateChange={this._onNavigationStateChange.bind(this)}
                                    onMessage={event => this.onMessage(event)}
                                    injectedJavaScript="setTimeout(() => {document.addEventListener('scroll', function (event) {window.ReactNativeWebView.postMessage(JSON.stringify(document.getElementsByClassName('topconteiner')[0].scrollTop));},true);}, 300);true;"
                                />
