### ISSUE TITLE
Compiling Android Issue: "Unable to resolve dependency"

### ISSUE THREAD

**Issue by dccarmo** [react-native-community/react-native-webview#375]
When running the app on the emulator it works fine, but when compiling a new build (or when opening the app on Android Studio), I get:

```
ERROR: Unable to resolve dependency for ':app@staging/compileClasspath': Could not resolve project :react-native-webview.
```

So `staging` is a new `buildType` we created ourselves, and we haven't had any troubles with other third party libs.

Any idea what we're doing wrong?

**Comment by Titozzz** [comment]
Not really, but maybe someone else will :)

**Comment by lunarraid** [comment]
I just started running into this after upgrading to react native 0.5.9, which requires a gradle upgrade.

**Comment by cdn34** [comment]
I'm also having a similar issue: `Unable to resolve dependency for ':app@releaseStaging/compileClasspath': Could not resolve project :react-native-webview.`

**Comment by Titozzz** [comment]
@Salakar? Any idea?

Could you give provide a complete reproduction?

**Comment by lunarraid** [comment]
The only way I was able to get around this was by not including `debug` as a fallback in my staging build type in `android/app/build.gradle`. It now looks like this:
```
    buildTypes {

        debug {
            debuggable true
            ...
        }

        staging {
            initWith debug
            signingConfig configType
            matchingFallbacks = ['release']
        }
    }
```

**Comment by Salakar** [comment]
@dccarmo @lunarraid any chance you could provide a reproduction repo that I could clone and take a look at? Hard to triage without this

**Comment by humphriest** [comment]
Getting the same error. Any progress?

Using React Native 58.2
React Native Webview: 5.6.1

**Comment by songxiaoliang** [comment]
Getting the same error. Any progress?

**Comment by Titozzz** [comment]
Guys, we asked for a reproduction..? No need to +1

**Comment by apue** [comment]
ok, I tried in this way, although worked but not recommended:
I've added all the new build types to react-native-webview/android/build.gradle
btw my gradle version is 4.7, on 4.6 there's no such issue however buck needs gradle 4.7

**Comment by ccorcos** [comment]
I think this might have to do with version conflicts between `react-native-webview`, `react-native`, and `react-native-firebase` (at least in my case).

I'm not sure how it works though, I'm seeing two different versions defined in this library:

    <orderEntry type="library" name="Gradle: com.squareup.okhttp:okhttp:2.5.0@jar" level="project" />
    <orderEntry type="library" name="Gradle: com.squareup.okhttp3:okhttp:3.1.2@jar" level="project" />

**Comment by hushicai** [comment]
same issue

react native 0.59.10
react-native-web 7.4.3
