### ISSUE TITLE
scalesPageToFit makes text tiny

### ISSUE THREAD

**Issue by jaspervanbrian** [react-native-community/react-native-webview#376]
Okay, I have installed `react-native-webview@5.2.1` a while back and I loaded Twitter Widget inside it, and it feels "mobile-like".

After I updated to `react-native-webview@5.2.4`, it made the texts in the webview tiny and it looked like you're on a desktop.

I read PR #275. Do we have the capability to set `setUseWideViewPort: true` or `setLoadWithOverviewMode: true` in React Native? It would be a great function to have

# ** version <= 5.2.1 **
![screenshot_20190301-225918_1](https://user-images.githubusercontent.com/24638813/53647915-86b18100-3c79-11e9-91d7-a98bb61e642a.jpg)

# ** version > 5.2.1 **
![screenshot_20190301-230101_1](https://user-images.githubusercontent.com/24638813/53647943-98932400-3c79-11e9-8525-77fd38fb4768.jpg)

**Comment by jamonholmgren** [comment]
Hey @jaspervanbrian , those two methods will follow the `scalesPageToFit` prop. See here:

https://github.com/react-native-community/react-native-webview/blob/a661df1ffcfdd4b2eb1b82dd05005541897b784e/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java#L565-L566

**Comment by geekazoid-at** [comment]
I can confirm the behaviour described by @jaspervanbrian and actually I don't understand the comment. I downgraded to work around the issue for now.

**Comment by keenubee** [comment]
For 5.2.4 on Android i used `scalesPageToFit={false}` as a workaround.
But for iOS with WKWebKit enabled it doesn't work so i'm using `useWebKit={false}` additionally.
I think it is something that should be fixed.

**Comment by jamonholmgren** [comment]
Could someone post a minimal repro we can copy & paste to see the behavior? Or, better yet, a PR fixing the issue with a test plan so we can test & release it?

With only a couple of part-time maintainers, it becomes difficult to keep up with the dozens of issues we get filed every week, so anything you can do to make our lives easier is greatly appreciated.

**Comment by laurent22** [comment]
@jamonholmgren, we also have this problem in [Joplin](https://github.com/laurent22/joplin). I don't have a minimal repro to provide unfortunately, as I think it might be a combination of the CSS applied to the body and text content of the view.

For us it happens consistently in Joplin: if you try to build the app in iOS, and add `useWebKit={true}` [here](https://github.com/laurent22/joplin/blob/7d6959e9e4e489c4decfeb4bd9f046f45fa899b9/ReactNativeClient/lib/components/note-body-viewer.js#L168) you'll see that the scaling is not right.

With `useWebKit={false}` and `scalesPageToFit={false}`, the view looks as expected:

<img width="164" alt="Capture d’écran 2019-06-14 à 07 35 02" src="https://user-images.githubusercontent.com/1285584/59488496-9d21c800-8e77-11e9-8511-4a6a65aff151.png">

However, with `useWebKit={true}` and `scalesPageToFit={false}`, the zoom is not right.

<img width="164" alt="Capture d’écran 2019-06-14 à 07 36 07" src="https://user-images.githubusercontent.com/1285584/59488512-a874f380-8e77-11e9-97d7-53d9cb5f3526.png">

Currently it doesn't seem possible to get the right result using WebKit.

**Comment by superandrew213** [comment]
Try adding `<meta name="viewport" content="width=device-width, initial-scale=1 />` and setting `scalesPageToFit={Platform.select({ android: false})`

**Comment by ChettaDarkkill** [comment]
@laurent22 thank you it work for me .
