### ISSUE TITLE
File upload, HTML capture attribute not working

### ISSUE THREAD

**Issue by worldhugo** [react-native-community/react-native-webview#378]
Hi,

using capture="camera" not working properly on Android (not tested on iOS). Normally, the camera app should automatically start, but with the react-native-webview I have to "choose an action" (between "camera app" and "my files").

Thanks,

Hugo

**Comment by andreipfeiffer** [comment]
I see this as being a nice enhancement.

The `capture` attribute has 3 possible values, as described in the standard https://www.w3.org/TR/html-media-capture/#the-capture-attribute:

```
<input type="file" accept="image/*" capture>
<input type="file" accept="image/*" capture="user">
<input type="file" accept="image/*" capture="environment">
```

Also, the `capture` attribute is not very well supported at the moment:
https://caniuse.com/#feat=html-media-capture

**Comment by jamonholmgren** [comment]
This would be nice, for sure.

**Comment by maple10001** [comment]
Tested on `ios`, upload btn always opens the camera. Would love to see it works on `android`.

**Comment by eisenheim94** [comment]
It is still not working on Android as might. On iOS it works fine.

Also, without this "captured" attribute on Android it opens only media library, so there is no option to take a picture with camera.

**Comment by coisnepe** [comment]
Running into this issue also. I know nothing about Android development but isn't it simply because the capture method is missing? Looks like there are only file picker methods:

https://github.com/react-native-webview/react-native-webview/blob/816c4a403814bbb4014efeccfc818d90cf3dea64/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java#L1173

**Comment by munawirrahman** [comment]
Hi Folks,

Seems like this issue still happening in android

**Comment by herujest** [comment]
this issue still happening in android

**Comment by syahirdev** [comment]
Hi, any updates on this? The issue still happening in android.

**Comment by jlapp9** [comment]
Does #2954 solve this?

**Comment by robxyy** [comment]
> Does #2954 solve this?

Yes, but `user` or `environment` is not supported, it's blocked by [FileChooserParams](https://developer.android.com/reference/android/webkit/WebChromeClient.FileChooserParams) - no capture value provided.
