### ISSUE TITLE
android webview's clear api are missing

### ISSUE THREAD

**Issue by punksta** [react-native-community/react-native-webview#380]
I find these methods useful, but they are missing in the rn webview.

- `clearFormData` Removes the autocomplete popup from the currently focused form field, if present.  https://developer.android.com/reference/android/webkit/WebView.html#clearFormData()
- `clearFormData` Clears any saved data for web forms. https://developer.android.com/reference/android/webkit/WebViewDatabase.html#clearFormData()
- `clearCache` Clears the resource cache. Note that the cache is per-application, so this will clear the cache for all WebViews used. https://developer.android.com/reference/android/webkit/WebView.html#clearCache(boolean)
- `clearHistory` Tells this WebView to clear its internal back/forward list. https://developer.android.com/reference/android/webkit/WebView.html#clearHistory()

I am not sure about ios alternatives api, but I can prepare pl for android.

related:
https://github.com/facebook/react-native/issues/20944
https://github.com/facebook/react-native/issues/20555

**Comment by jamonholmgren** [comment]
Hey @punksta, thanks for submitting this issue. I'm okay with you creating a PR that implements these methods for use only on Android. (If people need it on iOS, they can implement that and submit a PR.)

**Comment by punksta** [comment]
@jamonholmgren 
I am not sure what is best strategy for platform specific api implementation. I think we shouldn't generalize them for both platforms. We can ended up with multiple methods which does nothing at one platform and  something at others. Util classes `WebviewAndroidUtil.js` and `WebviewIosUtil.js` looks much better for me.

**Comment by BettyJJ** [comment]
These are really useful features. Hope someone can review the PR and accept it!

**Comment by hkar19** [comment]
is there any update on this feature?
