### ISSUE TITLE
testID not propagated on iOS?

### ISSUE THREAD

**Issue by ziomanlio** [react-native-community/react-native-webview#384]
Unlike the Android's _WebView.android.js_ class, the iOS's _WebView.ios.js_ class does not propagate `testID` to `NativeWebView`. So I can't select WebView when running my tests in iOS.
Any solution? 
Thank you

-----------
RN v0.58.3
react-native-webview v4.0.0

**Comment by Titozzz** [comment]
#206 related maybe

**Comment by jamonholmgren** [comment]
We would love a PR that fixes this, @ziomanlio !

**Comment by CubeSugar** [comment]
- about original view props

In my opinion, the way to set original view props by using 

```testID={this.props.testID}```(like pr #402 ) 

or 

```someProp={this.props.someProp}```

is not the best practice.  

@ziomanlio needs `testID` this time, someone may need more other props somewhen.

#206 may be one of the ways to solve problems.  

- workaround

U can set `testID` by using prop [NativeConfig](https://github.com/react-native-community/react-native-webview/blob/master/docs/Reference.md#nativeconfig)

demo:

```jsx
<WebView
    {...otherProps}
    nativeConfig={{
        props: {
            testID: "some string",
        },
  }}
/>
```

**Comment by ziomanlio** [comment]
> * about original view props
> 
> In my opinion, the way to set original view props by using
> 
> `testID={this.props.testID}`(like pr #402 )
> 
> or
> 
> `someProp={this.props.someProp}`
> 
> is not the best practice.
> 
> @ziomanlio needs `testID` this time, someone may need more other props somewhen.
> 
> #206 may be one of the ways to solve problems.
> 
> * workaround
> 
> U can set `testID` by using prop [NativeConfig](https://github.com/react-native-community/react-native-webview/blob/master/docs/Reference.md#nativeconfig)
> 
> demo:
> 
> ```js-jsx
> <WebView
>     {...otherProps}
>     nativeConfig={{
>         props: {
>             testID: "some string",
>         },
>   }}
> />
> ```

Thank you @CubeSugar ! I will temporarily fix my issue using this workaround.

**Comment by Titozzz** [comment]
This will be fixed very soon actually, doing lasts checks before release
