### ISSUE TITLE
[Feature Request] API to set cookies on webview

### ISSUE THREAD

**Issue by zackzachariah** [react-native-community/react-native-webview#387]
Currently, both platforms offer the ability to set custom cookies on their webviews.
* iOS 2-11: [`NSHTTPCookieStorage`](https://developer.apple.com/documentation/foundation/nshttpcookiestorage) for `UIWebView`
* iOS 11+: [`WKHTTPCookieStore`](https://developer.apple.com/documentation/webkit/wkhttpcookiestore) for `WKWebView`
* Android: [`CookieManager`](https://developer.android.com/reference/android/webkit/CookieManager)

While it's possible to set a cookie using the `injectedJavaScript` property on the `WebView` component, I think it would be cleaner (and more "secure feeling") to provide an API for calling into the various cookie storage or manager classes and setting the cookie in the app's sandboxed cookie storage before the webview loads.

Thoughts?

**Comment by jamonholmgren** [comment]
Hey @zackzachariah , thanks for the issue. Does [react-native-cookies](https://github.com/joeferraro/react-native-cookies) do what you're looking to do, or is it insufficient?

**Comment by zackzachariah** [comment]
Hey @jamonholmgren,

Unfortunately `react-native-cookies` has a few issues:
1. It doesn't have support for adding arbitrary cookies on Android. (It only supports that feature on iOS.)
2. Its Issues indicate that there are various issues on `master`, including crashes and outdated versions of gradle and npm.
3. Its README indicates that it's been abandoned and so I shouldn't expect fixes for 1 and 2.

**Comment by gzzo** [comment]
I'm also looking for this feature, and I also find `react-native-cookies` insufficient.  

Another point is that since that project is abandoned, `master` is way ahead of the release on npm, which doesn't support WKWebView.

**Comment by zackzachariah** [comment]
Oh good spot @gzzo - I didn't even think to check the diff between github and npm...

**Comment by gagan144** [comment]
So, is there any way to set cookies for webview before the page actually loads? I need to set a cookie before the call to remote page is made, so that the server can use that cookie, do some processing and then return the html.

**Comment by zackzachariah** [comment]
@gagan144 there is in native code but not (yet) in this package or in any that I know of. This issue is a request to build bridging to the native code to enable that.

**Comment by Titozzz** [comment]
#175 should address the issue

**Comment by Diwei-Chen** [comment]
Hi, not sure if this is related, but if my javascript code includes `document.cookie = ...` then it throws _Failed to set the 'cookie' property on 'Document'_ error as per:
![Screen Shot 2019-08-15 at 1 51 05 pm](https://user-images.githubusercontent.com/26317142/63071782-069b8100-bf64-11e9-9db2-6ec40043b5ce.png)

Is there anything I am missing?

**Comment by EdgarHSM** [comment]
> Hi, not sure if this is related, but on Android, if my javascript code includes `document.cookie = ...` then it throws _Failed to set the 'cookie' property on 'Document'_ error as per:
> ![Screen Shot 2019-08-15 at 1 51 05 pm](https://user-images.githubusercontent.com/26317142/63071782-069b8100-bf64-11e9-9db2-6ec40043b5ce.png)
> 
> The code works fine on iOS.
> 
> Any ideas, please?

@Diwei-Chen did you find a solution for this problem? I'm getting the exact same DOMException

**Comment by jamonholmgren** [comment]
@EdgarHSM Check out my new guide (linked just above this) and try the other way of sending cookies to the server. It might help you out.
