### ISSUE TITLE
Manual Installation 

### ISSUE THREAD

**Issue by laukaichung** [react-native-community/react-native-webview#39]
`react-native link` doesn't always work on `MainActivity.java` after installing `react-native-navigation`.  

Can you provide documentation for manual installation? I want to make sure there's nothing missing after running `react-native link react-native-webview`.

By the way, I can confirm that [this issue](https://github.com/facebook/react-native/issues/10865) is resolved with this repository on IOS.

**Comment by Titozzz** [comment]
Can you extend what you mean by doesn't always work ?
It would be interesting to know what is you react-native version too, as 0.57 shipped with some gradle changes

**Comment by stonecold123** [comment]
`react-native link` doesn't add `RCTWebViewPackage` to `MainActivity.java`. I have to add it manually. The second version of `react-native-navigation` ([Document](https://wix.github.io/react-native-navigation/v2/#/docs/Installing)) changes a lot of stuff in  `MainActivity.java` so running `react-native link` may not work as expected.

````
import com.reactnativenavigation.NavigationApplication;
import com.reactnativecommunity.webview.RCTWebViewPackage;

public class MainApplication extends NavigationApplication {

      @Override
      public List<ReactPackage> createAdditionalReactPackages() {
          return Arrays.<ReactPackage>asList(
             new RCTWebViewPackage()
          );
      }

}
````

**Comment by Titozzz** [comment]
Oh yeah, of course I remember this from when I was using react native navigation, but that is the same with all the packages, you need to edit MainActivity manually. Please submit an issue with react-native directly to see for a proposal to make the cli compatible with more setups such as react-native-navigation, even tho it seems hard to do.

We will document manual link steps in a near future. If anyone wants to do it before me, feel free :)

**Comment by jamonholmgren** [comment]
@stonecold123 This would be a great opportunity for you to help out the community and document the steps you're taking to get this working! We would really appreciate the help. This is a community-driven repo and everybody pitching in is what will make it awesome. <3

**Comment by Titozzz** [comment]
I've updated https://github.com/react-native-community/react-native-webview/blob/master/docs/Getting-Started.md#2-link-native-dependencies
