### ISSUE TITLE
Request object is missing properties on Android

### ISSUE THREAD

**Issue by el-lsan** [react-native-community/react-native-webview#390]
Based on https://github.com/react-native-community/react-native-webview/blob/master/docs/Reference.md#onshouldstartloadwithrequest I should get following properties inside request object:

```
title
url
loading
target
canGoBack
canGoForward
lockIdentifier
navigationType
``` 

However on Android, it only includes `navigationType` and `url`.

Here's my debug output in IOS:
```
canGoBack: false
canGoForward: false
loading: false
lockIdentifier: 2193813847
navigationType: "click"
target: 5539
title: ""
url: "https://google.com/"
```

And here's on Android for the exact same code and action:

```
navigationType: "other"
url: "https://google.com/"
```

So in case you want to limit `onshouldstartloadwithrequest`  to only `navigationType: "click"` like following code, it would fail on Android:

```
openExternalLink(req) {
  if (req.navigationType && req.navigationType !== 'click') {
    return true;
  }

  if (req.url && helper.isValidURL(req.url)) {
    Linking.openURL(req.url);
    return false;
  }
  return true;
}

<WebView
  source={{ html: this.state.html }}
  javaScriptEnabled
  domStorageEnabled
  onShouldStartLoadWithRequest={this.openExternalLink}
/>
```

**Comment by jamonholmgren** [comment]
@el-lsan You're right. The documentation should be updated to reflect that. Would you want to do that and submit a PR?

If someone wants to work on making these properties more consistent across iOS and Android, here's the relevant code:

https://github.com/react-native-community/react-native-webview/blob/6e059e9c55cf3a8ab6870f137920c2997b901b07/android/src/main/java/com/reactnativecommunity/webview/events/TopShouldStartLoadWithRequestEvent.java#L36-L37

**Comment by jamonholmgren** [comment]
Actually, I just saw #385, which is addressing this issue.

**Comment by punksta** [comment]
@jamonholmgren yes, I've fixed exactly this issue in the pl

**Comment by Titozzz** [comment]
Fixed in 5.3.1

**Comment by el-lsan** [comment]
@Titozzz `navigationType` is still inconsistent.
On IOS I get `click` but on Android is `other`.

**Comment by punksta** [comment]
@el-lsan that's another problem: https://github.com/react-native-community/react-native-webview/issues/381

as far I know it's impossible to distinguish clicks from other request events on android. 
I'm using 
```
const isClick = Platforms.select( {
   ios: event.type === "click", 
   android: event.type ==="other" && event.progress === 100
})
```
it works in most of my cases.

**Comment by el-lsan** [comment]
@punksta I see.
Thanks for the info. 🙌

**Comment by el-lsan** [comment]
@punksta I just tried to use your solution but I don't see any `event.progress`.
FYI i'm using: 
```
"react": "^16.8.4",
"react-native": "^0.59.0",
"react-native-webview": "^5.3.1",
```
These are the properties I get:
```
canGoBack
canGoForward
loading
navigationType
target
title
url
```

**Comment by punksta** [comment]
@el-lsan `loading !== false`
