### ISSUE TITLE
window.ReactNativeWebView.postMessage causes error on webview side

### ISSUE THREAD

**Issue by nagaokashi** [react-native-community/react-native-webview#391]
##VERSION
```
"dependencies": {
    "react": "16.6.3",
    "react-native": "0.58.1",
    "react-native-webview": "git+https://github.com/react-native-community/react-native-webview.git",
  },

```
I'm using laravel php framework for Webview side which is located on localhost.
The communication between react native side and webview are all fine.
But I got this error when opened website with PC browser.
`ReactNativeWebViewBridge.js:91 rnBridge send failed Cannot read property 'postMessage' of undefined`

This is source code on webview side
```
....
var msgObj = {
                   targetFunc: targetFunc,
                   data: data || {},
                   msgId: guid(),
               };

               var msg = JSON.stringify(msgObj);

               promiseChain = promiseChain.then(function () {
                   return new Promise(function (resolve, reject) {
                       console.log("sending message " + msgObj.targetFunc);

                       promises[msgObj.msgId] = {resolve: resolve, reject: reject};
                       callbacks[msgObj.msgId] = {
                           onsuccess: success,
                           onerror: error
                       };

                       window.ReactNativeWebView.postMessage(msg);  // For react-native-webview
                   })
               }).catch(function (e) {
                   console.error('rnBridge send failed ' + e.message);
               });
....
```

Source for native side
```
return (
	      	<SafeAreaView style={styles.container}>
		        <WebView
		        	ref={webview => {this.myWebView = webview;}}
			        useWebKit={true}	// WKWebView
			        source={{uri: URL_HOME}}
			        javaScriptEnabled={true}
			        cacheEnabled={false}
			        startInLoadingState={true}
			        onMessage={this.onWebViewMessage}
		       />
            />
	       	</SafeAreaView>
	    );
```

How to remove this error ?

I tried using `window.postMessage(msg, "*");` and then injectedJavaScript with
```
const injectedJavascript = `(function() {
  window.postMessage = function(data) {
    window.ReactNativeWebView.postMessage(data);
  };
})()`;
```
but the communication of react native and webview did not work.

**Comment by Titozzz** [comment]
You get the error when running the website with no react-native app, right?
React-native is the one responsible for injecting window with the ReactNativeWebView object, so if you need your website to run all by itself, just add security check by checking if ReactNativeWebView exists on window

**Comment by nagaokashi** [comment]
Oh yeah. I understood. 
Thanks.

**Comment by mayursarode4** [comment]
Hi,
I'm getting error as **"Uncaught TypeError: Cannot read property 'postMessage' of undefined"**
when calling from url where the response is inside php as,
<html>
      <head></head>
      <body>
        <script>
                      window.ReactNativeWebView.postMessage("Hello!")
         </script>
      </body>
      </html>

in RN:
return ( <View style = {{flex: 1}} >
      <WebView source = {{uri: url/test.php}}
          startInLoadingState={true}
          onLoadStart={() => {console.log("LOAD START");}}
          onLoadEnd={() => {console.log("LOAD END ");}}
          onMessage = {
            event => {
              const { getData } = event.nativeEvent.data
              console.log('handle message : ', getData)
              alert(getData);
            }
          }
      /> 
      </View>
    );

Response:
**handle message :  undefined**

Error:
**Uncaught TypeError: Cannot read property 'postMessage' of undefined
    at test.php:8**

**Comment by mayursarode4** [comment]
Hi,
I'm getting error as **"Uncaught TypeError: Cannot read property 'postMessage' of undefined"**
when calling from url where the response is inside php as,
<html>
      <head></head>
      <body>
        <script>
                      window.ReactNativeWebView.postMessage("Hello!")
         </script>
      </body>
      </html>

in RN:
return ( <View style = {{flex: 1}} >
      <WebView source = {{uri: url/test.php}}
          startInLoadingState={true}
          onLoadStart={() => {console.log("LOAD START");}}
          onLoadEnd={() => {console.log("LOAD END ");}}
          onMessage = {
            event => {
              const { getData } = event.nativeEvent.data
              console.log('handle message : ', getData)
              alert(getData);
            }
          }
      /> 
      </View>
    );

Response:
**handle message :  undefined**

Error:
**Uncaught TypeError: Cannot read property 'postMessage' of undefined
    at test.php:8**

**Comment by mayursarode4** [comment]
> Oh yeah. I understood.
> Thanks.

Can you put sample code here?

**Comment by ixre** [comment]
use below code resolve:
```
function postMessage(message,targetOrigin){
    (window["ReactNativeWebView"]||window).postMessage(message,targetOrigin);
}
```

**Comment by mayursarode4** [comment]
> use below code resolve:
> 
> ```
> function postMessage(message,targetOrigin){
>     (window["ReactNativeWebView"]||window).postMessage(message,targetOrigin);
> }
> ```

How? can you please show it with any example?

**Comment by favrio** [comment]
> > use below code resolve:
> > ```
> > function postMessage(message,targetOrigin){
> >     (window["ReactNativeWebView"]||window).postMessage(message,targetOrigin);
> > }
> > ```
> 
> How? can you please show it with any example?

Hi, i got into trouble with the same issue, finally i resolve this issue.
It's totally the window scope problem, plz make ensure you `window` is the window, so do not test this sdk in iframe(such as jsbin.com).

**Comment by kr4ckhe4d** [comment]
Just add a sanity check `window.ReactNativeWebView && window.ReactNativeWebView.postMessage("message", '*') `

**Comment by azmathikram11** [comment]
Hi all,
I am developing a React Native App that is using the web pages developed using Angular 9.

When We want to pass data from the web to the React Native we should use `window.ReactNativeWebView.postMessage()`. window.ReactNativeWebView.postMessage only accepts one argument which must be a string.

Eg: In the web I post a message which I want to send to the React Native app
` sendMessageToNative(){
    (window["ReactNativeWebView"]).postMessage("Hello Native");
  }`

To get this message in the React Native WebView is implemented the following code.
`<WebView
            ref={r => (this.webref = r)}
            source={{ uri: 'https://better-wolrd.com/rn-web' }}
            javaScriptEnabled={true}
            injectedJavaScript={runFirst}
            onMessage = {
              event => {
                //Get the data on selecting the hotel, partner id is passed from the web.
                const { data } = event.nativeEvent;
 // event.nativeEvent.data contains the data that we post from web
                alert('handle message : ', data)
              }
              }
            style={{ marginTop: 20 }}
            />`

**Comment by ali27001** [comment]
TypeError: Cannot read property 'postMessage' of undefined . If you get an error try this, it worked for me

let sendMessageToNative = () =>{
        window.ReactNativeWebView && window.ReactNativeWebView.postMessage("aliii", '*')
    }

**Comment by sunilchilami** [comment]
window["ReactNativeWebView"] && window["ReactNativeWebView"].postMessage(JSON.stringify({"change": false}))
i am sending post message to native & i used this above code in ngOnInIt or Route Change but messages are firing multiple times .that issue i m facing .that has to send single postmessage but each time throwing multi messages.please give me a solution thank you.

**Comment by sunilchilami** [comment]
> Hi all,
> I am developing a React Native App that is using the web pages developed using Angular 9.
> 
> When we want to pass data from the web to the React Native we should use `window.ReactNativeWebView.postMessage()`. window.ReactNativeWebView.postMessage only accepts one argument which must be a string.
> 
> Eg: In the web I post a message which I want to send to the React Native app
> ` sendMessageToNative(){ (window["ReactNativeWebView"]).postMessage("Hello Native"); }`
> 
> To get this message in the React Native WebView is implemented the following code in the onMessage event of WebView.
> ` onMessage = { event => { const { data } = event.nativeEvent; // event.nativeEvent.data contains the data that we post from web alert('handle message : ', data) }`

............................................................................................................................................................................................................................
      window["ReactNativeWebView"] && window["ReactNativeWebView"].postMessage(JSON.stringify({"change": false}))
i am sending post message to native & i used this above code in ngOnInIt or Route Change but messages are firing multiple times .that issue i m facing .that has to send single postmessage but each time throwing multi messages.please give me a solution thank you.
