### ISSUE TITLE
Load local html file

### ISSUE THREAD

**Issue by a1lu** [react-native-community/react-native-webview#392]
Hi,
I try to load my html page:

```
 <WebView
    style={{width: 300}}
    source={require('./foobar.html')}
    originWhitelist={['*']}
 />
```

But it does not render the content as html, but as text.

Thats my html file:
```
<html>
    <head>
        <title>Page Title</title>
    </head>
    <body>

        <h1>My First Heading</h1>
        <p>My first paragraph.</p>

    </body>
</html>

```

Any tips how to render the content?

**Comment by daoan1412** [comment]
convert foobar.html to foobar.js
```
export default function() { return `
<html>
    <head>
        <title>Page Title</title>
    </head>
    <body>

        <h1>My First Heading</h1>
        <p>My first paragraph.</p>

    </body>
</html>
`};
```

**Comment by a1lu** [comment]
@daoan1412 
thanks alot, though this did does not work for me.

But I got this working:

```
<WebView
    style={{width: 300}}
                        source={{html: require('./foobar.js')()}}
    originWhitelist={['*']}
 />
```

I need to add `html` for the source.

**Comment by AlexAba** [comment]
My html file use a css file, but it not working in this case.

**Comment by likepearl** [comment]
do you solve this issue?

**Comment by AlexAba** [comment]
Nope

**Comment by daoan1412** [comment]
**baseUrl**
 android: file:///android_asset/ 
 ios:  file://
Copy style.css to assets folder in /android.
Copy style.css to ios folder using xcode
```
 <link rel="stylesheet" type="text/css" href="style.css">
```

**Comment by likepearl** [comment]
> set **baseUrl** in react-native-webview
> android: file:///android_asset/
> ios: file://
> 
> * Copy yourstyle.css to assets folder in /android.
> * Copy yourstyle.css to ios folder using xcode.
> * In your.html file
> 
> ```
>  <link rel="stylesheet" type="text/css" href="yourstyle.css">
> ```
> 
> Or simple copy all yourstyle in css file to html
> 
> ```
>  <style>
>       img {
>         width: 90%;
>       }
> </style>
> ```

Thank you, it works.

**Comment by bhavya95** [comment]
if any one can help me with this, it is working in android
` const baseUrl =
    Platform.OS === 'ios'
      ? 'html-folder'
      : 'file:///android_asset/html-folder';
  const injectedJavascript = `(function() {
        window.postMessage = function(data) {
          window.ReactNativeWebView.postMessage(data);
        };
      })()`;
  return ( 
    <View style={{flex: 1}}>
      <WebView
        javaScriptEnabled={true}
        injectedJavaScript={injectedJavascript}
        style={{flex: 1}}
        source={{uri: `${baseUrl}/index.html`, baseUrl: baseUrl}}
        onMessage={(event) => {
          if (event.nativeEvent.data === 'Open Drawer') {
            navigation.openDrawer();
          }
        }}
       originWhiteList={['*']}
      />
    </View>
  );`

html-folder is added in android/app/src/main/assets/
this folder have index.html, js folder and assets folder, works perfectly in android

and for ios i have added the html-folder through Xcode by Adding files to project but it is not working
should the baseUrl be something else or need to add html-folder in another way?
@likepearl @daoan1412

**Comment by bhavya95** [comment]
Fixed it, while adding html-folder in Xcode using 'Adding files to project' option make sure 'Copy files if needed' should be unchecked
react-native : 0.63
react-native-webview : 10.3.2
