### ISSUE TITLE
Building for android "staging" buildType error: java.lang.NullPointerException (no error message)

### ISSUE THREAD

**Issue by psamd** [react-native-community/react-native-webview#398]
Hi, I am getting the following error when I try to generate APK using `./gradlew assembleStaging` or `./gradlew assembleRelease`:

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:processStagingManifest'.
> Could not resolve all task dependencies for configuration ':app:stagingRuntimeClasspath'.
   > Could not resolve project :react-native-webview.
     Required by:
         project :app
      > Could not select value from candidates [null, debug, release] using AlternateDisambiguationRule.BuildTypeRule.
         > java.lang.NullPointerException (no error message)
```

I am using the following versions:
```
react-native@0.57.8
react-native-webview@5.2.4
```

I use a staging buildType for my android builds.
```
staging {
    initWith release
    applicationIdSuffix ".staging"
    matchingFallbacks = ['release', 'debug']
    signingConfig signingConfigs.release
}
```

**Comment by psamd** [comment]
Solved!

In the buildType config, changing `matchingFallbacks = ['release', 'debug']` to `matchingFallbacks = ['release']` resolved the error.

The buildType config now looks like:
```
staging {
    initWith release
    applicationIdSuffix ".staging"
    matchingFallbacks = ['release']
    signingConfig signingConfigs.release
}
```
I still have no idea why its not taking multiple elements in the `matchingFallbacks` array.

**Comment by jacob-israel-turner** [comment]
Hey @psamd - did you every figure out why including the debug fallback broke this?  We're having this exact issue, but in a different project.

**Comment by psamd** [comment]
Hi @jacob-israel-turner - I did not try to figure it out as including debug fallback was not important to our app. So we just used the release fallback

**Comment by yassinecc** [comment]
I would avoid changing the matchingFallbacks that might affect other dependencies. 

In my case, I ended up replacing
`implementation project(':react-native-webview')`
by
`implementation project(path:':react-native-webview', configuration: 'default')`

**Comment by cyril94440** [comment]
Same issue for me, not able to fix it as I don't find any matching lines :(
