### ISSUE TITLE
if debugger is off, onMessage does not trigger. 

### ISSUE THREAD

**Issue by imdadhussain004** [react-native-community/react-native-webview#405]
I have migrated from code Webview to react-native-webview. 
followed the guide, now i need to communicate from webview to react-native. for that 
`<WebView 
.......
 onMessage={event => {
                    alert("hiiiiii"+event)
                    this._onMessage(event)
                }}
`
but i does not trigger.

**Comment by indapublic** [comment]
Probably, I have same issue.
```
"react-native-webview": "^5.3.0"
```

```
const injectedJavaScript = `function onBridgeReady(cb) {
      if (window.postMessage.length !== 1) {
        setTimeout(function() {
          onBridgeReady(cb)
        }, 100);
      } else {
        cb();
      }
    }
    onBridgeReady(function() {
      window.postMessage('works!', '*');
      alert('works!');
    });
    true;
    `;
```

I see alert but **onMessage** not fired

**Comment by imdadhussain004** [comment]
I have resolved it. Please let me see you onMessage function @indapublic

**Comment by indapublic** [comment]
```onMessage: event => {
        console.warn("onMessage");
      }```

for example

**Comment by imdadhussain004** [comment]
`onMessage={event => {
alert("calling onMessage"+event)
                    //this._onMessage(event)
                }}`


check if you are getting this alert

**Comment by indapublic** [comment]
As I said before onMessage not fired

**Comment by ifiokjr** [comment]
@imdadhussain004 how did you resolve it?

I'm having the same issue in my app. Works fine when in debug - but hangs and eventually crashes the app without debug.

**Comment by imdadhussain004** [comment]
@ifiokjr please share you onMessage() function. 
I was checking if json I'm getting from webview is valid or not, i commented that section and it started working

**Comment by ifiokjr** [comment]
Okay, I just figured it out. 

The app seems to crash when you try to log the event. 

```ts
private readonly onMessage = (event: NativeSyntheticEvent<WebViewMessage>) => {
    console.log('welcome to the jungle');
    const data = event.nativeEvent.data;
    console.log('native', event); // This line causes it to crash when not it debug mode
    this.setState({ message: 'message received ' + data }, () => {
      console.log('THIS IS AN EVENT', data);
      const num = parseInt(JSON.parse(data).message, 10);
      if (typeof num !== 'number' || num !== num || num === Infinity) {
        console.error('something went wrong with the number', num);

        return;
      }
      if (num >= MAX) {
        this.webView.current!.postMessage('STOP');
        return;
      }
      this.setState({ num, duration: Date.now() - this.state.started.getTime(), message: '' }, () =>
        this.webView.current!.postMessage(String(this.state.num + 1)),
      );
    });
  };
```

**Comment by ifiokjr** [comment]
@indapublic Looking at your code I believe the reason it isn't working is that you're using `window.postMessage` instead of `window.ReactNativeWebView.postMessage` within the `injectedJavascript` prop.

If you change it you should at least see the `onMessage` handler fire.

Also, it seems that logging the `event` causes the app to freeze as my message above suggests.

**Comment by indapublic** [comment]
@ifiokjr Yeah, i fixed it already. Thanks!

**Comment by BhaveshLakhpati** [comment]
i had the same issue. 2 solutions:
1. use window.ReactNativeWebView.postMessage insteam of window.postMessage
2. add event.isDefaultPrevented(true) in the first line of your onMessage method
