### ISSUE TITLE
NSURLErrorDomain - 1202 (Certificate)

### ISSUE THREAD

**Issue by MayeuldP** [react-native-community/react-native-webview#407]
Good afternoon, 
just saw this library today, I'm still and originally using `Webview from "react-native"`, then I saw your repo, so I wanted to give it a try. 
However, I'm stuck with this error when the Webview try to launch ⏬ 

<img width="200" alt="capture d ecran 2019-03-08 a 16 20 33" src="https://user-images.githubusercontent.com/15033774/54037397-5bb9b680-41be-11e9-9966-ed9ed76f1de2.png">

It's weird, 'cos I don't get this error with the original Component imported from `React-Native`... 
I tried to add an `NSExceptionDomains` field in my Info.plist, but didn't work... 
Does anyone have any ideas about how to resolve this, or for example, ignoring certificates restriction when Webview's loading ?

**Comment by Titozzz** [comment]
There is no reason it would be any different from the original component 🤔

**Comment by MayoudP** [comment]
Sorry, I actually lost the access to my original account (@MayeuldP ), so here I am again (sorry for the delay) :
 
I tried with the very basic example : 
```
return (
      <WebView
        source={{ uri: "https://facebook.github.io/react-native/" }}
      />
);
```

It's actually working well for Android, on Simulator and Real devices (both)
However on iOS, I get the same error with the screen that I added in the first post. 
```
Error loading page, Domain : NSURLErrorDomain, Error Code: 1202, 
The certificate for this server is invalid. 
You might be connecting to a server that i pretending to be "facebook.github.io"
which could put your confidential information at risk.
```

This is the kind of errors that I get in the log of the simulator : 
```
Mar 22 17:02:33  com.apple.CoreSimulator.SimDevice.235866FF-3DC6-4044-9A28-1A29BBDD3E97[39710] (com.apple.StreamingUnzipService): Unknown key for Boolean: EnableTransactions
Mar 22 17:02:33  com.apple.CoreSimulator.SimDevice.235866FF-3DC6-4044-9A28-1A29BBDD3E97[39710] (com.apple.StreamingUnzipService): Unknown key for Boolean: EnablePressuredExit
Mar 22 17:02:33  com.apple.CoreSimulator.SimDevice.235866FF-3DC6-4044-9A28-1A29BBDD3E97[39710] (com.apple.WebKit.Networking): Unknown key for Boolean: EnableTransactions
Mar 22 17:02:33  com.apple.CoreSimulator.SimDevice.235866FF-3DC6-4044-9A28-1A29BBDD3E97[39710] (com.apple.WebKit.Networking): Unknown key for Boolean: EnablePressuredExit
Mar 22 17:02:33  com.apple.CoreSimulator.SimDevice.235866FF-3DC6-4044-9A28-1A29BBDD3E97[39710] (com.apple.WebKit.Storage): Unknown key for Boolean: EnableTransactions
Mar 22 17:02:33  com.apple.CoreSimulator.SimDevice.235866FF-3DC6-4044-9A28-1A29BBDD3E97[39710] (com.apple.WebKit.Storage): Unknown key for Boolean: EnablePressuredExit
Mar 22 17:02:33  com.apple.CoreSimulator.SimDevice.235866FF-3DC6-4044-9A28-1A29BBDD3E97[39710] (com.apple.WebKit.WebContent): Unknown key for Boolean: EnableTransactions
Mar 22 17:02:33  com.apple.CoreSimulator.SimDevice.235866FF-3DC6-4044-9A28-1A29BBDD3E97[39710] (com.apple.WebKit.WebContent): Unknown key for Boolean: EnablePressuredExit
Mar 22 17:02:33  com.apple.CoreSimulator.SimDevice.235866FF-3DC6-4044-9A28-1A29BBDD3E97[39710] (com.apple.backboard.display.archive): Unknown key for Boolean: EnableTransactions
Mar 22 17:02:33  com.apple.CoreSimulator.SimDevice.235866FF-3DC6-4044-9A28-1A29BBDD3E97[39710] (com.apple.backboard.display.archive): Unknown key for Boolean: EnablePressuredExit
Mar 22 17:02:33  com.apple.CoreSimulator.SimDevice.235866FF-3DC6-4044-9A28-1A29BBDD3E97[39710] (com.apple.uifoundation-bundle-helper): Unknown key for Boolean: EnableTransactions
Mar 22 17:02:33  com.apple.CoreSimulator.SimDevice.235866FF-3DC6-4044-9A28-1A29BBDD3E97[39710] (com.apple.uifoundation-bundle-helper): Unknown key for Boolean: EnablePressuredExit
```



And here is the error that I get in the Chrome Debugger.

<img width="400" alt="Capture d’écran 2019-03-22 à 17 07 00" src="https://user-images.githubusercontent.com/48682041/54836671-01901980-4cc5-11e9-922a-1fc0ae8d7f12.png">


- [x] I, of course, checked that the librairies were both correctly linked for iOS and Android
- React-Native version : `0.55.3`
- Xcode Version : Xcode 10.1
- Simulator : iOS 12.1

I have the strange feeling that this problem has something to deal with xCode ... 🧐🤔

**Comment by fishkingsin** [comment]
in my experience, it only occurs on simulator

React Native Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
      Memory: 704.05 MB / 16.00 GB
      Shell: 3.0.0 - /usr/local/bin/fish
    Binaries:
      Node: 8.15.0 - ~/.nvm/versions/node/v8.15.0/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v8.15.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 21, 22, 23, 24, 25, 26, 27, 28
        Build Tools: 23.0.1, 23.0.3, 24.0.1, 25.0.0, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.2, 27.0.3, 28.0.2, 28.0.3
        System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.2/10E125 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.5 => 16.8.5
      react-native: 0.59.2 => 0.59.2
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-create-library: 3.1.2

**Comment by Titozzz** [comment]
This is working on my end. Are you sure the network you are connected to is safe? Please try with another network connection.

**Comment by MayoudP** [comment]
It appears that it didn't works on Simulator on another network connection, however it worked on a real device (iOS), weird and quite contraining but ok on the end... You can close the issue !

**Comment by Titozzz** [comment]
maybe you are using some weird VPN or something :)

**Comment by breadadams** [comment]
We've just updated to the community webview over that from react-native directly and started to get this issue.

It may only be on the simulator but it's a huge blocker as in one case we use a webview for some authentication in the 1st step of an app - and can't get around it without some hackish code inserting credentials to redux 😓

**Comment by Monte9** [comment]
I ran into this too. On simulator it gave me that ^^ error, but when I ran it on a iOS device the url loaded fine.

**Comment by MayoudP** [comment]
Glad to see that I'm finally not the only one ;)

**Comment by breadadams** [comment]
After having added the following to `NSAppTransportSecurity` in our target's Info.plist file:

```
<key>NSAllowsArbitraryLoads</key>
<true/>
```

And rebuilding the project, it seems to be working on the simulator again 🤞

**Comment by gorvinsky** [comment]
I'm having similar problem on both the simulator and the device. Below is the error that I get:
```
Error loading page
Domain: NSURLErrorDomain
Error Code: -1100
Description: The requested URL was not found on this server.
```
Let me know if you need more info from me to debug this.

**Comment by gorvinsky** [comment]
> I'm having similar problem on both the simulator and the device. Below is the error that I get:
> 
> ```
> Error loading page
> Domain: NSURLErrorDomain
> Error Code: -1100
> Description: The requested URL was not found on this server.
> ```
> 
> Let me know if you need more info from me to debug this.

So I have fixed my own issue following this [guide](https://medium.com/@snehabagri.90/reactnative-webview-with-local-content-c98a09340801). What I did wrong in the first place was creating the external folder and put in the web files physically via finder instead of adding them via Xcode.

**Comment by rokebrand** [comment]
If anyone else comes across this with error -1202, my problem was my antivirus was issuing invalid certificates to the simulator, open safari and surf to the website, if it has an issue, view certificate, if it says it's not trusted and you can see the certificate is by your antivirus, turn your antivirus off, hope this helps someone out there
![image_2019_06_18T10_47_36_947Z](https://user-images.githubusercontent.com/12936899/59676964-0e8bae80-91c9-11e9-9ee3-cf95698717b4.png)

**Comment by sckoh** [comment]
the community version is not working because it set useWebKit to true by default.
if u set useWebKit to false on community version.
it will be working

**Comment by makhoutdlw** [comment]
I have the same issue when trying to use my localhost server while developping.

**Comment by MayoudP** [comment]
> the community version is not working because it set useWebKit to true by default.
> if u set useWebKit to false on community version.
> it will be working

Did the trick ! Thank you Sir !

**Comment by Dylan0916** [comment]
> the community version is not working because it set useWebKit to true by default.
> if u set useWebKit to false on community version.
> it will be working

but if useWebKit set false will use `UIWebView`
`UIWebView` is deprecated and will be removed soon

what should I do...

**Comment by SmirnovM91** [comment]
Do you have any updates?

**Comment by jwbnw** [comment]
A solution that may work for some is to follow this documentation: https://github.com/react-native-community/react-native-webview/blob/master/docs/Custom-iOS.md#allowing-custom-cas-certifica-authorities-and-enabling-ssl-pinning. Some of that documentation is outdated so you'll have to play with it but it was able to help me find a working solution. More information can be found in this commit https://github.com/react-native-community/react-native-webview/commit/136fbd84915e20912d21370c254f5206b5661d67

**Comment by dhlalit** [comment]
Not working on simulator...try info.plist all the keys need to be added. giving sam error:he certificate for this server is invalid. You might be connecting to a server that is pretending to be “127.0.0.1” which could put your confidential information at risk. Also, tried using uploading and trusting same self signed certificate on simulator doesn't work. Also changes to localhost from '127.0.0.1'.
Doesn't work.

**Comment by alanko0202** [comment]
I have still experienced the same situation. Does anyone have the solution on this issue?

**Comment by cesar-oyarzun-m** [comment]
Having same issue, trying to use localhost and render the URL on the webview, it works if I do it directly in safari, but I get the exception using react native web view. Has anyone solved this problem running on simulator and localhost?

**Comment by 452MJ** [comment]
+1

**Comment by filipe-valente** [comment]
What solved it for me was accessing it on Safari in the simulator and accepting the warning to see the page. Then it worked inside the WebView.

**Comment by satish1020** [comment]
It took a lot of time for me to figure this out:

If we come across the certificate issue, while connecting the bank accounts (PFA is the attached screen shot).
It is because ‘' antivirus preventing iPhone simulator to browse any websites.I was able to fix this issue by the following steps:                                                                                                                                                     
1)   uninstall or turn off Antivirus in Mac.                                                                        
 2) erase all content and settings of simulator.                                               
3) restart mac.

**Comment by ajitsing** [comment]
I had the same problem on Android emulator. It worked by downgrading the version to `10.3.0`

**Comment by janelin99** [comment]
I had the same issue when VPN is on. Accepting the certificate on Safari doesn't help. I still got the issue with iOS simulator.

**Comment by FrancisLeigh** [comment]
Having same troubles have documented [here](https://github.com/react-native-webview/react-native-webview/issues/1647)

```
react: 16.13.1 => 16.13.1
react-native: 0.63.2 => 0.63.2
react-native-webview => ^10.9.2
```

**Comment by sgoelEbsco** [comment]
Hey everyone, Is there any update on the same. I have experienced this issue a couple of times.

**Comment by miteshdb** [comment]
Did anyone find any solution?

**Comment by LucasAndrad** [comment]
+1

**Comment by MyNameIsAlaa** [comment]
+1

**Comment by ChristopherGabba** [comment]
This may help some but not all...

If your WebView source is written like:
```typescript
        <RFWebView 
          source={{uri: "www.instagram.com" }} 
        />
```
change it to include `https://`:
```typescript
        <RFWebView 
          source={{uri: "https://www.instagram.com" }} 
        />
```
This fixed the problem for me at least...

**Comment by saike** [comment]
if you want to deal with a server hosted on your local Mac and load it in react-native-webview inside IOS simulator, you need to create root certificate with [https://github.com/FiloSottile/mkcert](mkcert) and then do things from: [https://stackoverflow.com/a/76756644/1330193](this answer). For me it works
