### ISSUE TITLE
`getModule()` throws exception with Custom Webview on Android

### ISSUE THREAD

**Issue by RangerMauve** [react-native-community/react-native-webview#408]
React-Native: ^0.58.5
React: 16.6.3
React-Native-WebView: ^5.2.3

I'm working on making a [custom webview](https://github.com/RangerMauve/datmobile/tree/master/android/app/src/main/java/com/datmobile/webview) based on the guide [in the docs](https://github.com/react-native-community/react-native-webview/blob/master/docs/Custom-Android.md).

It's working well in that it's loading my native code and executing my event handlers as I'd expect.

However, there's an exception being thrown within [onDownloadStart](https://github.com/react-native-community/react-native-webview/blob/master/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java#L462) in the DownloadListener inside the [getModule()](https://github.com/react-native-community/react-native-webview/blob/master/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java#L810) call.

The problem is that getModule() relies on there being a `mPackage` variable being set, which doesn't exist within my custom `RNCWebViewManager` implementation.

How should I work around this? Should I have my package initialize an instance of RNCWebViewModule and pass it in as a reference? Was there a step that I missed in the docs that's not obvious?

A bump in the right direction would be very much appreciated.

**Comment by RangerMauve** [comment]
I'm not sure why the downloadManager is even being invoked since I'm intercepting the request

**Comment by RangerMauve** [comment]
I've made some progress by removing the RNCWebView package from `MainApplication.java` and having `RNCWebViewManager` initiated within the package for my plugin.

Here's what it looks like:

```java
package com.datmobile.webview;

import com.facebook.react.bridge.NativeModule;
import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.uimanager.ViewManager;
import com.reactnativecommunity.webview.RNCWebViewManager;
import com.reactnativecommunity.webview.RNCWebViewModule;
import com.reactnativecommunity.webview.RNCWebViewPackage;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class ProtocolWebViewpackage extends RNCWebViewPackage {
    private RNCWebViewModule module;

    @Override
    public List<ViewManager> createViewManagers(ReactApplicationContext reactContext) {
        ProtocolWebViewManager mProtocolWebViewManager = new ProtocolWebViewManager();
        mProtocolWebViewManager.setPackage(this);

        RNCWebViewManager mRNCWebViewManager =  new RNCWebViewManager();
        mProtocolWebViewManager.setPackage(this);

        return Arrays.<ViewManager>asList(
                mProtocolWebViewManager,
                mRNCWebViewManager
        );
    }

    @Override
    public List<NativeModule> createNativeModules(ReactApplicationContext reactContext) {
        List<NativeModule> modulesList = new ArrayList<>();
        module = new RNCWebViewModule(reactContext);
        module.setPackage(this);
        modulesList.add(module);
        return modulesList;
    }

    public RNCWebViewModule getModule() {
        return module;
    }

}
```

Not sure if there's a better approach I could take here. 😅

**Comment by jamonholmgren** [comment]
Hey @RangerMauve, I'm not much help here and it's probably beyond the scope of this repo's issues, so I'll close this issue. I hope you're able to accomplish what you're looking to do though!
