### ISSUE TITLE
Dynamic height for html text

### ISSUE THREAD

**Issue by PayalDinc** [react-native-community/react-native-webview#413]
While using `WebView` we have to provide height. Is there any way such that `WebView` will be rendered based on HTML content for it?

Here are my lines of code :

```
 <View style={{flex: 1, flexDirection:'column'}}>
       <WebView
      originWhitelist={['*']}
      scalesPageToFit 
      startInLoadingState = {true}
      style = {[this.props.style,{flex : 1,borderWidth: 1, height: '100%'}]}
      mixedContentMode="always"
      automaticallyAdjustContentInsets={false}
      source = {this.props.isHTML ? {html :htmlText} : {uri : this.props.uri}}
      />   
      </View> 
```

**Comment by Titozzz** [comment]
No it is not possible

**Comment by iamdhj** [comment]
You can using ```postMessage``` and ```onMessage```
```
 onWebViewMessage = (event: WebViewMessageEvent) => {
    this.setState({webViewHeight: Number(event.nativeEvent.data)})
  }

  render() {
    return (
      <ScrollView>
        <WebView
          style={{ height: this.state.webViewHeight }}
          source={{html: '...'}}
          onMessage={this.onWebViewMessage}
          injectedJavaScript='window.ReactNativeWebView.postMessage(document.body.scrollHeight)'
        />
      </ScrollView>
    )
  }
```

**Comment by Titozzz** [comment]
Yeah sorry you can render, then resize it by sending the rendered size but it might flicker

**Comment by taylorkline** [comment]
Unfortunately with @iamdhj's solution, I am getting a height that is much larger than the actual content.

**Comment by hussainhspl** [comment]
@iamdhj  : event: WebViewMessageEvent is not allowed in js can we use only event ?

**Comment by iamdhj** [comment]
> 
> 
> @iamdhj : event: WebViewMessageEvent is not allowed in js can we use only event ?

Yeah we can, WebViewMessageEvent just typescript's declaration

**Comment by hussainhspl** [comment]
thanks

**Comment by hussainhspl** [comment]
@iamdhj : not working properly in iOS, height is same for every view when using loop

**Comment by hussainhspl** [comment]
> Unfortunately with @iamdhj's solution, I am getting a height that is much larger than the actual content.

on iOS ?

**Comment by iamdhj** [comment]
> 
> 
> @iamdhj : not working properly in iOS, height is same for every view when using loop

Build a component do the resize logic or post height and index in loop eg: `postMessage({ index, height })`

**Comment by pzxbc** [comment]
> Unfortunately with @iamdhj's solution, I am getting a height that is much larger than the actual content.

I have the same problem. the height is too much larger sometime

**Comment by hussainhspl** [comment]
use this below package
React Native WebView Autoheight

**Comment by safaiyeh** [comment]
interesting package @hussainhspl, that should be apart of this repo.

**Comment by hussainhspl** [comment]
yes it is different package but developed using same webView, the data you
want to print is in loop where each div is having different height then use
this auto height package else you can manage height using state.

**Comment by karltaylor** [comment]
> > Unfortunately with @iamdhj's solution, I am getting a height that is much larger than the actual content.
> 
> I have the same problem. the height is too much larger sometime

Also have this problem, the height returned is a lot larger than the actual content.

**Comment by archansel** [comment]
Wrap your html string inside `html` tag and set its meta viewport
```
const generateHtml = content => `
<!DOCTYPE html>\n
<html>
  <head>
    <title>Web View</title>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=320, user-scalable=no">
    <style type="text/css">
      body {
        margin: 0;
        padding: 0;
      }
    </style>
  </head>
  <body>
    ${content}
  </body>
</html>
`
```
this will generate correct height

**Comment by Yeab13** [comment]
@archansel Thank You so much

**Comment by hanzhangyu** [comment]
> > > Unfortunately with @iamdhj's solution, I am getting a height that is much larger than the actual content.
> > 
> > 
> > I have the same problem. the height is too much larger sometime
> 
> Also have this problem, the height returned is a lot larger than the actual content.

replace body.scrollHeight by container element`s clientHeight.

**Comment by xjdqq** [comment]
> > > > Unfortunately with @iamdhj's solution, I am getting a height that is much larger than the actual content.
> > > 
> > > 
> > > I have the same problem. the height is too much larger sometime
> > 
> > 
> > Also have this problem, the height returned is a lot larger than the actual content.
> 
> replace body.scrollHeight by container element`s clientHeight.

still have this problem

**Comment by xjdqq** [comment]
使用onLoadEnd={() => {
            ref.current.injectJavaScript(’javaScript代码‘);
          }}注入获取高度的javaScript代码，可以避免异常的高度

**Comment by ruofee** [comment]
I also have this problem, and why it? 😂

**Comment by xjdqq** [comment]
> I also have this problem, and why it? 😂

把设置高度的js代码放到  webView的onLoadEnd函数里执行 就没有那种问题了

**Comment by chunghn** [comment]
> > I also have this problem, and why it? 😂
> 
> 把设置高度的js代码放到 webView的onLoadEnd函数里执行 就没有那种问题了

Sir would you mind sharing your exact code instead? `ref.current.injectJavaScript(webViewScript)` seems not working for me.

**Comment by dinhbang** [comment]
> <style type="text/css">
>       body {
>         margin: 0;
>         padding: 0;
>       }
>     </style>

It is still wrong and very height.

**Comment by haopingfan** [comment]
> Wrap your html string inside `html` tag and set its meta viewport
> 
> ```
> const generateHtml = content => `
> <!DOCTYPE html>\n
> <html>
>   <head>
>     <title>Web View</title>
>     <meta http-equiv="content-type" content="text/html; charset=utf-8">
>     <meta name="viewport" content="width=320, user-scalable=no">
>     <style type="text/css">
>       body {
>         margin: 0;
>         padding: 0;
>       }
>     </style>
>   </head>
>   <body>
>     ${content}
>   </body>
> </html>
> `
> ```
> 
> this will generate correct height

This answer is awesome! But I also need to set `width=device-width` rather than hard code 320 get the correct height.
```
<meta name="viewport" content="width=device-width user-scalable=no">
```

**Comment by Stepan72** [comment]
> 使用onLoadEnd={() => { ref.current.injectJavaScript(’javaScript代码‘); }}注入获取高度的javaScript代码，可以避免异常的高度

I had problems with Android height (IOS works well).
After adding onLoadEnd as https://github.com/xjdqq adviced problem solved.


`{
  const webViewRef = useRef(null);

  const webViewScript = `
     (function() {
      window.ReactNativeWebView.postMessage(document.documentElement.scrollHeight);
    })()
  `;

  const [webViewHeight, setWebViewHeight] = useState(
    Dimensions.get('window').height,
  );

  return (
    <ScrollView style={{width: '100%'}} contentContainerStyle={{flexGrow: 1}}>
      <WebView
        ref={webViewRef}
        onShouldStartLoadWithRequest={onShouldStartLoadWithRequest}
        onNavigationStateChange={onNavigationStateChange}
        source={webViewSource}
        scrollEnabled={true}
        style={{
          marginHorizontal: 16,
          height: webViewHeight,
        }}
        onMessage={(event) => {
          setWebViewHeight(parseInt(event.nativeEvent.data));
        }}
        onLoadEnd={() => webViewRef.current.injectJavaScript(webViewScript)}
        showsVerticalScrollIndicator={false}
        javaScriptEnabled={true}
        injectedJavaScript={webViewScript}
        cacheEnabled={true}
      />
`

**Comment by LPitonakova** [comment]
Great solutions above, unfortunately, they don't work when you are using custom fonts or anything style- or java-script based that changes the final components height inside the html. We need to measure the height AFTER all components were loaded and this can be achieved by:

Inside render function:

```
<WebView
                  style={{ height: this.state.webViewHeight, backgroundColor: "transparent" }}
                  originWhitelist={['*']}
                  source={{ html: this._generateHtmlDocument(this.state.product.descriptionHtml, StyleConfig.FontSizes.SMALLER) }}
                  onMessage={this._onWebViewMessage}
                  scrollEnabled={false} cacheEnabled={false} pullToRefreshEnabled={false}
               />
```

Other functions (I am importing Google fonts which needs a few milliseconds to load:

```

_generateHtmlDocument = (content_, fontSize_) => {
      return `
         <!DOCTYPE html>\n
         <html>
         <head>
            <meta http-equiv="content-type" content="text/html; charset=utf-8">
            
            <meta name="viewport" content="width=${AFConstants.PAGE_WIDTH} user-scalable=no initial-scale=1">
            <style>
               @import url('https://fonts.googleapis.com/css2?family=Poppins&display=swap');
            </style>
            <style type="text/css">
               body {
                  margin: 0;
                  padding: 0;
                  font-family: "Poppins", sans-serif;
                  font-weight: 400;
                  font-style: normal;
                  font-size: ${fontSize_}px;
               }
            </style>
         </head>
         <body>
            <div id="test" style="display: block; background: #00FFFF">
               ${content_}
            </div>
            <div id="test2" style="display: block; height: 100px; background: #00FF"></div>
         </body>
         <script>
            window.addEventListener('load', function () {
               window.ReactNativeWebView.postMessage(document.body.scrollHeight)
            })
         </script>
         </html>
      `
   }

_onWebViewMessage = (event) => {
      this.setState({webViewHeight: Number(event.nativeEvent.data)})
   }
```

Notice that I am not injecting any JS through the webview, but I am triggering a message to ReactNative in the `window.addEventListener('load',`

**Comment by pavel-roj** [comment]
@LPitonakova We're using custom fonts as well, but the code is still measuring a very large height of around 7500 units during the load callback unless I add in an artificial timeout of around 1000ms in which case it returns the correct 1500 units. 

The weird thing is that this happens only when there is a FlatList after the WebView. Other components caused the problem as well but the results were inconsistent.

**Comment by LPitonakova** [comment]
@pavel-roj that's interesting, and it happens even with calling a react native event in the window's 'load' function? Have you tried setting the `this.state.webViewHeight` to something like 1000 to start with (on parent component load)?

**Comment by pavel-roj** [comment]
@LPitonakova Thanks for the reply, yes, an incorrect value is measured inside the load callback, but a correct one is measured with an artificial timeout of around 1000ms.

We've been using a smaller value of around 40 for the initial height, using 1000 results in the same bug. There must be something with the measuring logic that we're missing that breaks when there are other components after the webview -- although so far I've only been able to reproduce the issue consistently with a horizontal scrollable flat list. Other components seem mostly fine --- ScrollView after the WebView broke the flatlist as well, but not consistently.

I've tried using the autoheight hook from formidable webview as others have suggested and that works correctly without any issues, although the library was last updated 3 years ago. I haven't looked closely at their measuring logic, but the code is open source.

**Comment by pavel-roj** [comment]
This is probably a very naïve solution but if it helps anyone out, we've ended up using the 'resize' event instead of the 'load' event. Just be mindful that it will be called multiple times.

This script is inserted after the <body>
```
<script>
    window.addEventListener('resize', function() {
        window.ReactNativeWebView.postMessage(document.documentElement.scrollHeight);
    });
</script>
```

**Comment by khanhdevvn** [comment]
I was changed postMessage after content loaded by listened event load as below. So it rerender exactly height content !
 ` html: '<!DOCTYPE html><head>' +
        '<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1 "></head> <body>' +
        content
        + '</body><script> window.addEventListener("load", function () { window.ReactNativeWebView.postMessage(document.documentElement.scrollHeight); });</script></html>'
`

**Comment by JerakRus** [comment]
@pavel-roj  Thank you very much! The only solution that worked for android! But it doesn't work on iOS - it just doesn't get called. Therefore, you should add to html something like:
```
  <script>
    window.onload = () => window.ReactNativeWebView.postMessage(document.body.scrollHeight.toString())
    ${
      Platform.OS === 'android' &&
      'window.onresize = () => window.ReactNativeWebView.postMessage(document.body.scrollHeight.toString())'
    }
  </script>
```
In your onMessage handler function, add a check to avoid multiple calls, like:
```
  const handleMessage = (event: WebViewMessageEvent) => {
    const newHeignt = Number(event.nativeEvent.data)
    if (webviewHeight !== newHeignt) {
      setWebviewHeight(newHeignt)
    }
  }
```
And a small life hack from me: In iOS, if there are other components on the screen besides WebView that have margin or padding, the height is determined incorrectly. Add an initial height value of 1 instead of 0 and then it will work correctly.
```
const [webviewHeight, setWebviewHeight] = useState(1)
```
