### ISSUE TITLE
Pdf view can't load

### ISSUE THREAD

**Issue by Shivani12345** [react-native-community/react-native-webview#417]
How to show pdf in "react-native-webview ?. I put pdf file url in source but it shows me downloading toast and can't load pdf.Help me

**Comment by NMVikings** [comment]
Has the same issue on android as well. Reproduce every time on android on any device

**Comment by Titozzz** [comment]
You can't show PDFs on Android in the Webview
https://www.quora.com/Why-does-Chrome-on-Android-not-open-PDF-files-like-Chrome-on-Windows-Linux-can

**Comment by Dror-Bar** [comment]
@Titozzz 

> Both platforms will happily display any file content that it knows how to when linked (i.e. https://www.irs.gov/pub/irs-pdf/f1040.pdf)

From this [comment](https://github.com/react-native-community/react-native-webview/issues/280#issuecomment-458663977). Is there a miscommunication here?
