### ISSUE TITLE
WebView `onMessage` is not working in Android.

### ISSUE THREAD

**Issue by ashokadichill** [react-native-community/react-native-webview#422]
Package json:

-  "react": "16.6.3",
-  "react-native": "^0.58.5"
-  "react-native-webview": "^5.3.1"

Description :

WebView onMessage doesn't work on Android.

`

export default class TestContainer extends Component {

    sendPostMessage = () => setTimeout(() => {
        this.webView.postMessage('🤑 loaded')
    }, 100)
    
    render() {
        return (
            <SafeAreaView forceInset={{ top : 'always', bottom : 'always'}} style={{flex:1}}>
                <View style={{ width : '100%', height : '100%' }} >
                <WebView
                    javaScriptEnable={true}
                    onLoadEnd={this.sendPostMessage}
                    source={{html}}
                    ref={(component) => (this.webView = component)}
                    onMessage={this.handleMessage}
                    injectedJavaScript={" setTimeout(function(){ window.postMessage('asdsa', '*'); },1000); "} 
                />
                </View>
            </SafeAreaView>
        )
    }

    handleMessage = (event) => {
        Alert.alert('handle message')
        let msgData;
        try {
            msgData = JSON.parse(event.nativeEvent.data);
            console.log('WebViewLeaf : received message: ', msgData)
        } catch (err) {
          console.log('error',err);
        }
    };
    
} `

HTML

`<script> function sendData() { var text =document.getElementById("text").value; var dataToTransfer = JSON.stringify({ "description" : 'Return data from webview to react native', "data" : String(text) }) //react-native-webview window.ReactNativeWebView.postMessage(dataToTransfer) } //react-native-webview window.addEventListener("message", receiveMessage, false); //react-native document.addEventListener("message", receiveMessage, false); function receiveMessage(event) { alert('received data') document.getElementById('demo').innerHTML = JSON.parse(event.data).description } </script>`

**Comment by Titozzz** [comment]
In your injectedJavascript you are using window.postMessage, it has been removed: https://github.com/react-native-community/react-native-webview/releases/tag/v5.0.0

**Comment by ashokadichill** [comment]
It was my bad I am running HTML inside the app once it's published on the server. if I access via URI it works as expected.

**Comment by Titozzz** [comment]
Alright

**Comment by ashokadichill** [comment]
@Titozzz 
Hi, 
It just an information need 
I am redirecting to foodon.tst.com it will redirect to webon.tst.com for some reasons once user operation finished. 
will this work if I send data from webon.tst.com using
window.ReactNativeWebView.postMessage('get your data')
