### ISSUE TITLE
Webview inside Flatlist does not scroll smoothly 

### ISSUE THREAD

**Issue by cpojer** [react-native-community/react-native-webview#436]
* * *
  This issue was originally created by @KevinLoc as facebook/react-native#22550.
  * * *

  ## Environment
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
      Memory: 6.28 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.4 - /usr/local/bin/node
      npm: 5.6.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        API Levels: 21, 22, 23, 24, 25, 26, 27, 28
        Build Tools: 27.0.3, 28.0.2, 28.0.3
        System Images: android-23 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5014246
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0 
      react-native: 0.57.0 => 0.57.0 
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Description
The scrolling of Webview inside Flatlist does not run smoothly only in Android device (it works very well on IOS ). I have an array webviews, then in Flatlist, each renderItem I will have one Webview inside. Here is my simple Flatlist and renderContentRow

```jsx
  <View style={{ flex: 1 }} onLayout={this.onLayout}>
              <FlatList
                    data={listWebview}
                    bounces={false}
                    renderItem={this.renderContentRow}
                    keyExtractor={(item, index) => `${item.Id}-${index}`}
                    horizontal={true}
                    pagingEnabled
              >
              </ FlatList>
 </ View>

renderContentRow = (row) => {
    return (
        <View style={{
             width: deviceWidth - 40,
             height: deviceHeight - 230,
             backgroundColor: 'green'
       }}>
           <WebView
               originWhitelist={['*']}
               scalesPageToFit={true}
               source={{ uri: 'https://stackoverflow.com/questions/52929589/how-to-display-data-using-flatlist-and-webview-in-react-native' }}
           />
      </ View>
    )
}
```

**Comment by jamonholmgren** [comment]
@KevinLoc Can you try adding the following prop to your WebView and see if it helps?

`windowSize={3}`

If you're finding it doesn't render quickly enough as you scroll, experiment with `windowSize={5}`.

**Comment by punksta** [comment]
may be related to https://github.com/react-native-community/react-native-webview/issues/131
adding `overflow: 'hidden'` around web-view helped me

**Comment by yilakt** [comment]
What's the solution for this problem? I'm currently having this issue

**Comment by erkie** [comment]
this seems to still happen. did anyone find a solution or can we reopen this issue?

**Comment by praneeth-hiver** [comment]
Please re-open this issue

**Comment by vikrantnegi** [comment]
Any solution?

**Comment by batyrkulov** [comment]
Any solution?

**Comment by erkie** [comment]
@batyrkulov use https://github.com/callstack/react-native-pager-view if possible

**Comment by mahadevsempire** [comment]
any proper solution? facing the same issue with Android

**Comment by JuEunSung** [comment]
Any solution?

**Comment by Nensi9** [comment]
Any Solution for this issue?

**Comment by Avery1030** [comment]
I've been stuck on this problem for 2 days
