### ISSUE TITLE
[Android] Webview becoming blank when scrolling

### ISSUE THREAD

**Issue by ThibautGeriz** [react-native-community/react-native-webview#440]
First of all big thank for the lib.
I had the issue with the  [chrome update](https://github.com/react-native-community/react-native-webview/issues/429) So I updated my as suggested:

```js
<View style={{overflow: 'hidden', flex: 1}}>
   <webview source={{ html }} style={{ flex:1, opacity: 0.99}} />
</view>
```

Since the release, I had some report saying that when scrolling the webview, it is becoming blank. I could not reproduced the error, I am still gathering infos.
Anyone has any idea on what is happening here?

In the meantime, I might not use JS and use this lib: https://github.com/jsdf/react-native-htmlview

**Comment by Titozzz** [comment]
Chrome has been fixed so you should not worry about this anymore :)
