### ISSUE TITLE
[Android] No content will load when the WebView is not the root view

### ISSUE THREAD

**Issue by maxschmeling** [react-native-community/react-native-webview#444]
As per [this comment](https://github.com/react-native-community/react-native-webview/issues/224#issuecomment-475098688) on #224 I'm creating this issue with simple reproduction steps for the Android `WebView` display issue.

**STEPS**
1. Render a `WebView` as anything but the root view.
2. Set the source to anything valid that should load a visible page.

**EXPECTED**

The `WebView` should display the page.

**ACTUAL**

The `WebView` is rendered without content (if you set the background color of the component, you'll see it. But no rendered page content inside of it)

**CODE**

*Works*
```
import React from "react";
import { View } from "react-native";
import { WebView } from "react-native-webview";

export default function App() {
  return (
    <WebView source={{ uri: "https://example.com" }} />
  );
}
```

*Does not work*
```
import React from "react";
import { View } from "react-native";
import { WebView } from "react-native-webview";

export default function App() {
  return (
    <View>
      <WebView source={{ uri: "https://example.com" }} />
    </View>
  );
}
```

**Environment**

`react-native-webview@5.4.1`
```
    System:
      OS: macOS 10.14.3
      CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
      Memory: 991.44 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.3.0 - ~/.nvm/versions/node/v11.3.0/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v11.3.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.1 => 0.59.1 
    npmGlobalPackages:
      react-native-git-upgrade: 0.2.7
```

**Comment by Titozzz** [comment]
Well if your view does not have a height it won't be displayed 🤔 , add flex:1 to the view containing or a fixed height to the webview?

**Comment by maxschmeling** [comment]
Ah, good point. The reproduction attempt appeared to match what I was seeing in my real-world case so I assumed it was correct. But you're right, this wouldn't be visible either way. Working on a better reproduction.

**Comment by Titozzz** [comment]
Thanks 👍

**Comment by maxschmeling** [comment]
This isn't a reproduction of my issue, but I do find this odd and *possibly* could be related... when I set the width and height to be 200, the `WebView` is twice as tall as it is wide and appears to lose the background color on the bottom half (notice the scroll bar on the WebView)...

![image](https://user-images.githubusercontent.com/112691/54761941-197e7500-4bc1-11e9-8987-6cb61dd26ef2.png)

**Comment by Titozzz** [comment]
So there is this issue that since 0.56/0.57 don't remember they changed the way overflow works and it broke webview on android. Best way to use it actually is to leave it to it's default flex 1 and wrap inside a view with overflow:'hidden', and then you size that view however you need.

**Comment by maxschmeling** [comment]
I'm having difficulty reproducing this in a simple case. So now I'm not sure what's causing my issue. Maybe it's something about being inside `react-navigation` containers that's causing the issue. I'll keep playing with different configs and see if I can figure out what causes it.

I do know for sure though that it simply doesn't display the web content in my case even when the `WebView` itself is visible.

**Comment by Titozzz** [comment]
I'm using it with react-navigation without any problems but please if you have a repro, I'll try to give it a look

**Comment by maxschmeling** [comment]
In my real-world case, I did what you suggested above and wrapped the `WebView` in a correctly sized `View` and then set `flexGrow: 1` on the `WebView` and it seems to be working now. I'm going to play around a bit more and make sure that's actually the only thing that I did that caused it to start working. But I think this can be closed if that's the "correct" fix.

**Comment by Titozzz** [comment]
Alright, glad to hear. flexGrow on the webview should not be needed as it's already default.

**Comment by Qamarkh** [comment]
> Well if your view does not have a height it won't be displayed 🤔 , add flex:1 to the view containing or a fixed height to the webview?

Perfect bro , its work like a charm. Thank you.
