### ISSUE TITLE
When I use "inline html", can not load js file

### ISSUE THREAD

**Issue by GreatAuk** [react-native-community/react-native-webview#445]

**Comment by GreatAuk** [comment]
```
  render() {
    return (
      <View style={{ flex: 1 }}>
        <WebView
          source={{ html: `
            <!DOCTYPE html>
            <html lang="en">
              <head>
              </head>
              <body style="background-color: red">
                <button>Button</button>
                <script src="https://gw.alipayobjects.com/os/antv/assets/f2/3.3.7/f2.min.js"></script>
                <script>
                  document.body.innerHTML = JSON.stringify(F2)
                </script>
              </body>
            </html>
          ` }}
          onMessage={event => {
            alert(event.nativeEvent.data);
          }}
        />
      </View>
    );
  }
```

**Comment by harrisrobin** [comment]
Hi @GreatAuk, 
thanks for submitting an issue!

Is loading the js file the only issue?
Can you run any JS at all?

**Comment by GreatAuk** [comment]
> Hi @GreatAuk,
> thanks for submitting an issue!
> 
> Is loading the js file the only issue?
> Can you run any JS at all?

Yes, loading the js file is only issue. The global variable(F2) is undefined

**Comment by Titozzz** [comment]
Please connect to the webView by following the docs in the debugging session and see if there are any errors.

**Comment by GreatAuk** [comment]
> Please connect to the webView by following the docs in the debugging session and see if there are any errors.

Js file downloaded successfully，get a error : "ReferenceError: Can't find variable: F2"

**Comment by httol** [comment]
same issue.

**Comment by httol** [comment]
请问楼主，最后怎么解决的。

**Comment by svdo** [comment]
I’m seeing a problem that is maybe the same. I have a web view with inline html source and injectedJavaScript. The functions that I declare in that injected JavaScript are not available when I then try to call them using `injectJavaScript`. But when I assign them to `document` as a work around (`document.myFunction = myFunction`) I can call them on `document`...

**Comment by m1m6** [comment]
Same here, it works on ios, not on android

**Comment by maxKimoby** [comment]
I got the same issue, inline html is not accessible in the webView. However, when I included a script which methods are wrapped in an object, I can access it.

<img width="1277" alt="Screen Shot 2019-10-08 at 12 23 37 PM" src="https://user-images.githubusercontent.com/12074525/66414393-58421400-e9c7-11e9-97a9-12a364d4b259.png">
<img width="1270" alt="Screen Shot 2019-10-08 at 12 24 07 PM" src="https://user-images.githubusercontent.com/12074525/66414394-58daaa80-e9c7-11e9-9a7d-17ae68ef2176.png">

**Comment by Jakob-Koschel** [comment]
Issue still persists in `react-native-webview: 7.4.3` (Android only)

it is not possible to call/access any function/variables inserted with `injectedJavaScript` within `injectJavascript` calls.

This is broken:
```
  customJs = () => `
    const variable1 = "I am just a test";
    `;
...
<WebView
    ....
    injectedJavaScript={this.customJs()}
...
```

but when assigning them manually to `window` it works:

```
  customJs = () => `
    const variable1 = "I am just a test";
    window.variable1 = variable1;
    `;
...
<WebView
    ....
    injectedJavaScript={this.customJs()}
...
```

**Comment by ccfz** [comment]
Still an issue on version 9.1.4. Workarounds work!

**Comment by svdo** [comment]
> thanks for your tipp @svdo, however I think it would be better to put them under `window` than `document`.

Yeah you're probably right, can't verify right now but that makes sense.
