### ISSUE TITLE
[iOS] Unable to resolve module

### ISSUE THREAD

**Issue by mpochron** [react-native-community/react-native-webview#449]
![image](https://user-images.githubusercontent.com/7736131/54855777-f3a7bc00-4cf7-11e9-9708-2238784159b3.png)

This issue sill exists on 5.4 or newer.

RN: 0.59
Platform: iOS

Downgrade to 5.3.1 works.

**Comment by Titozzz** [comment]
This looks like a cache issue. Have you tried --reset-cache?

**Comment by elnygren** [comment]
try reinstalling and check the package isn't symlinked from somewhere else by npm (yep....)

at least that was my problemo and reinstalling solved the issue
