### ISSUE TITLE
Can you add the ability to get web page loading progress?

### ISSUE THREAD

**Issue by 2534290808** [react-native-community/react-native-webview#45]
Can you add the ability to get web page loading progress?

**Comment by jamonholmgren** [comment]
Yeah, you should be able to do that.

iOS: https://developer.apple.com/documentation/webkit/wkwebview/1415007-estimatedprogress
Android: onProgressChanged https://developer.android.com/reference/android/webkit/WebChromeClient

**Comment by Titozzz** [comment]
Closed by #53
