### ISSUE TITLE
App Crashes on iOS and Android when clicking on file upload input in webview

### ISSUE THREAD

**Issue by gshenar** [react-native-community/react-native-webview#458]
Has anybody seen an error like this before. When clicking on a file input to upload a file from within the webview, the app just crashes immediately. This wasn't happening on every decide but I couldn't identify and trends between ios/android or any specific versions of android. 

I believe I've added the appropriate permissions including 
`<uses-permission android:name="android.permission.CAMERA" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>`
and 
`<key>NSCameraUsageDescription</key>
	<string>$(PRODUCT_NAME) would like to use your camera for image uploads</string>
	<key>NSPhotoLibraryAddUsageDescription</key>
	<string>$(PRODUCT_NAME) would like to save photos to your photo gallery</string>
	<key>NSPhotoLibraryUsageDescription</key>
	<string>$(PRODUCT_NAME) would like access to your photo gallery for image uploads</string>`

**Comment by jonasantonelli** [comment]
It is happening here too!

**Comment by jonasantonelli** [comment]
On version 5.0.0 it works!

**Comment by gshenar** [comment]
We are on 5.3.0, could there have been a regression?

**Comment by JoeLeung32** [comment]
- react-native-webview@5.4.4 👎 
- react-native-webview@5.4.1 👎 
- react-native-webview@5.4.0 💯 
- react-native-webview@5.3.0 💯 

react: 16.8.2
react-native: 0.58.6

**Comment by Titozzz** [comment]
@sjchmiela looks like your commit might be the culprit. Can you have a look ?

If anyone else has time to investigate please do

Please stick with 5.4.0 until then.

**Comment by AndrzejSala** [comment]
Using 5.4.4 version and have the same problem.

Instant crash on file upload.

**Comment by gshenar** [comment]
Thanks for the help. Unfortunately this doesn't seem to have fixed the issue for us when upgrading to 5.4.6 with react native 0.58.5. Still crashing on android when clicking the file input, I'm not seeing any errors when running react-native android log or anything

**Comment by Titozzz** [comment]
Please make sure to reinstall the native side and not only the js

**Comment by lfaz** [comment]
It still crashes on file upload for Android on the latest version of react-native-webview! Anyone came with any solution for this? It's pretty annoying that it does crash on Android.

**Comment by MlikiMelek** [comment]
i still have the same problem

**Comment by AMoktar** [comment]
I'm facing the same problem too 
 "react": "17.0.1",
"react-dom": "17.0.1",
"react-native": "0.64.3",
"react-native-webview": "11.15.0",
