### ISSUE TITLE
Referer header is not passing to request

### ISSUE THREAD

**Issue by indapublic** [react-native-community/react-native-webview#460]
I have private vimeo video. It restricted by [domain-level privacy](https://vimeo.zendesk.com/hc/en-us/articles/115015677227-Troubleshoot-player-error-messages)

It works if request contains `Referer` header, but seems like `react-native-webview` not pass it

<img width="569" alt="Screenshot 2019-03-28 at 12 48 32" src="https://user-images.githubusercontent.com/856260/55127235-37b51980-515b-11e9-98a7-ea90eca8481c.png">

So I receive error on trying to play protected video

![Screenshot 2019-03-28 at 10 51 30](https://user-images.githubusercontent.com/856260/55121717-76d96f80-5147-11e9-80ff-e22b2fa7e822.png)

**Comment by indapublic** [comment]
Unfortunetaly I can't provide access to working area, so I just put my code here.

```
<WebView
	source={{
		uri
	}}
	javaScriptEnabled        
	startInLoadingState
	mixedContentMode="compatibility"
	thirdPartyCookiesEnabled
	allowUniversalAccessFromFileURLs
	style={styles.webView}
/>
```

Btw, it reproducible only for Android. IOS working well

**Comment by TMomemt** [comment]
As my solution, edit `RNCWebViewManager.java` like this

```
    @Override
    public boolean shouldOverrideUrlLoading(WebView view, String url) {
      dispatchEvent(view, new TopShouldStartLoadWithRequestEvent(view.getId(), url));
      if (/** your condition **/) {
        return true;
      }
      return false;
    }

    @TargetApi(Build.VERSION_CODES.N)
    @Override
    public boolean shouldOverrideUrlLoading(WebView view, WebResourceRequest request) {
      final String url = request.getUrl().toString();
      return this.shouldOverrideUrlLoading(view, url);
    }
```

and in js code `onShouldStartLoadWithRequest` callback you can't return any true or false still cause your losing refer.

**Comment by sibelius** [comment]
@TMomemt can you send a PR fixing this?

**Comment by sibelius** [comment]
@indapublic how did you debug this network request?

how are you passing `Referer` to WebView component?

**Comment by sibelius** [comment]
to make this work on android we need to hack on `shouldInterceptRequest`, and always add these custom headers

**Comment by TMomemt** [comment]
@sibelius My solution which needs custom code in java code is not a general solution.

I tend to change `shouldOverrideUrlLoading` to always return false , and remove [this function call](https://github.com/react-native-community/react-native-webview/blob/master/src/WebView.android.tsx#L206) or mark it as iOS only because it can not control webView's loading actually on Android like the early versions.

But I'm not experienced at Android platform,  I don't know if it will cause other problems.

**Comment by indapublic** [comment]
@sibelius I debugged this via React Native Debugger. `Refererer` header passed with `source.headers` or from parent page with vimeo link.

My solution was is force rerender if Webview should open vimeo player:

```
if (Platform.OS === "android") {
	webViewProps.onShouldStartLoadWithRequest = navigator => {        
		if (/player.vimeo.com/.test(navigator.url)) {          
			this.setState({ url: navigator.url });
			return false;
		} else {
			return true;
		}
	};
}
```

**Comment by BennyTian** [comment]
the same problem ...

**Comment by jojol** [comment]
edit RNCWebViewManager.java like this
 @Override
    public boolean shouldOverrideUrlLoading(WebView view, String url) {
      if (url.contains("https://wx.tenpay.com")){
        Map<String,String> map=new HashMap<String, String>();
        map.put("Referer", "https://www.reactnative.com");
        view.loadUrl(url,map);
        return true;
      }
      dispatchEvent(
        view,
        new TopShouldStartLoadWithRequestEvent(
          view.getId(),
          createWebViewEvent(view, url)));
      return true;
    }

**Comment by indapublic** [comment]
Not sure that issue should be closed because problem is actual.

**Comment by tangnguyenv** [comment]
@indapublic This issue still happens, any solutions for that?

**Comment by indapublic** [comment]
@tangnguyenv I rerendering webview for url which I need extra headers:

```
shouldStartLoadWithRequest = navigator => {
	if (Platform.OS === "android") {
		if (/player.vimeo.com/.test(navigator.url)) {
			this.setState({ url: navigator.url })

			return false
		}
	}

	return true
}
```

```
<WebView 
	source={{
		uri: url,
		headers: {
			referer: getBaseRootUrl(),
		},
	}}
	onShouldStartLoadWithRequest={this.shouldStartLoadWithRequest}
/>
```

**Comment by dattran-cxa** [comment]
Hi @indapublic , my referer should be previous url and `onShouldStartLoadWithRequest` has complex logic... Do we have anyway to resolve it in native code?

**Comment by tangnguyenv** [comment]
hi @indapublic , @sibelius .
Could we implement by this way:
```
@TargetApi(Build.VERSION_CODES.N)
@Override
public boolean shouldOverrideUrlLoading(WebView view, WebResourceRequest request) {
    final String url = request.getUrl().toString();
    PREVIOUS_URL = view.getOriginalUrl()();
    return this.shouldOverrideUrlLoading(view, url);
}
```

```
case COMMAND_LOAD_URL:
    if (args == null) {
        throw new RuntimeException("Arguments for loading an url are null!");
    }
    HashMap<String, String> headerMap = new HashMap<>();
    headerMap.put("referer", PREVIOUS_URL);
    root.loadUrl(args.getString(0), headerMap);
    break;
```

**Comment by indapublic** [comment]
@tangnguyenv You can make PR and I can test it

**Comment by tangnguyenv** [comment]
hi @indapublic , I've created a PR already, need you review it 
https://github.com/react-native-community/react-native-webview/pull/1130

**Comment by indapublic** [comment]
Thanks @tangnguyenv , i will check on this week

**Comment by indapublic** [comment]
Hi, @tangnguyenv 
Seems like my case (pass referer header to Vimeo for domain-restricted videos playback) is working well!

**Comment by indapublic** [comment]
But perhaps problem is wider. webview is not passing all headers

```
<Webview source={{
	uri: url,
	headers: {
		referer: getBaseRootUrl(),
                 someAnotherHeader: "foobar",
	},
}}
```

So only referer will be passed, isn't it? It's enough for me but probably not for others

**Comment by tangnv** [comment]
That's why I need you check carefully 😆 
Anw, when I debug I see `COMMAND_LOAD_URL` was triggered when click on WebView url. It doesn't impact to source headers, `setSource` will handle your case. Please help me double check

**Comment by huangnan78100** [comment]
I have a good way，can solve this problem：

1，'Referer' can be set by network request,  res.data is HTML code.
axios.get(‘http://www.xxx.xx’, {
                headers: {'Referer': 'xxx.xxx'}
            }).then((res)=>{
                    this.setState({
                        html: res.data
                    })
                }
2，Load the HTML code with the webView
<WebView source={{html: this.state.html}}
                     renderError={errorName=><Text>{errorName}</Text>}
                     onLoadStart={() => {}}
            />

**Comment by huangnan78100** [comment]
@indapublic @TMomemt @sibelius @BennyTian @jojol can you close the issues?

**Comment by indapublic** [comment]
@huangnan78100 And you will lose headers when will try to visit another url in webview. It's not solution

**Comment by huangnan78100** [comment]
> @huangnan78100 And you will lose headers when will try to visit another url in webview. It's not solution

Ok,   But I've achieved my goal by this way

**Comment by tangten** [comment]
@indapublic how's about my above solution?

**Comment by indapublic** [comment]
@tangten I thought I'm answered :) Your solution will pass only `referer` header. It's enough for me but not sure about others.

**Comment by tangten** [comment]
hmm, you're right. Let's me investigate more!

**Comment by ihwf** [comment]
I have this issue too, and @tangten way no work for me

**Comment by huangnan78100** [comment]
> I have this issue too, and @tangten way no work for me

do you try my way？

**Comment by jiahong96** [comment]
still cannot pass Referer header to webview on **react-native-webview** version **9.4.0**  🍡

**Comment by jiahong96** [comment]
> @tangnguyenv I rerendering webview for url which I need extra headers:
> 
> ```
> shouldStartLoadWithRequest = navigator => {
> 	if (Platform.OS === "android") {
> 		if (/player.vimeo.com/.test(navigator.url)) {
> 			this.setState({ url: navigator.url })
> 
> 			return false
> 		}
> 	}
> 
> 	return true
> }
> ```
> 
> ```
> <WebView 
> 	source={{
> 		uri: url,
> 		headers: {
> 			referer: getBaseRootUrl(),
> 		},
> 	}}
> 	onShouldStartLoadWithRequest={this.shouldStartLoadWithRequest}
> />
> ```

how about on first load? I can't pass `referer` header on first load

**Comment by indapublic** [comment]
@jiahong96 First passing should work. I have `react-native-webview@7.6.0` in my project.

**Comment by KingAmo** [comment]
@indapublic  https://github.com/react-native-community/react-native-webview/blob/master/docs/Reference.md#onshouldstartloadwithrequest
On Android,`onshouldstartloadwithrequest` is not called on the first load.

**Comment by indapublic** [comment]
@KingAmo will check it tomorrow on my project

**Comment by indapublic** [comment]
@KingAmo We don't need `onShouldStartLoadWithRequest` on the first load, so it's ok. `headers` should be defined for the first load.

**Comment by sumshare** [comment]
> @KingAmo We don't need `onShouldStartLoadWithRequest` on the first load, so it's ok. `headers` should be defined for the first load.

You can add other custom keys in headers when first load, but 'referer' is an exception in Android

**Comment by KingAmo** [comment]
> > @KingAmo We don't need `onShouldStartLoadWithRequest` on the first load, so it's ok. `headers` should be defined for the first load.
> 
> You can add other custom keys in headers when first load, but 'referer' is an exception in Android

that is the problem

**Comment by guemidiborhane** [comment]
i'm having the same issue, and it's crucial to have a referer header to use an API we heavily rely on

**Comment by kristian-nst** [comment]
Any solution to this in 2025?

**Comment by indapublic** [comment]
> Any solution to this in 2025?

Try [this](https://github.com/react-native-webview/react-native-webview/issues/460#issuecomment-491667485) @kristian-nst

**Comment by kristian-nst** [comment]
Seems just adding the headers worked 😅 The above example didn't for me.

```
      source={{
        uri: url,
        headers: {
          referer: 'https://my.app',
        },
      }}
```
