### ISSUE TITLE
After stopLoading, the whole webView can't trigger any press, only can scroll, on Android.

### ISSUE THREAD

**Issue by dwyanelin** [react-native-community/react-native-webview#461]
I write stopLoading in onNavigationStateChange to prevent redirect in webView, and do what I want. But After stopLoading, the whole webView can't trigger any press, only can scroll, on Android, recently.

please help me. thanks.

Below is what I do simplest:
command line:
expo init app
cd app
yarn run eject
yarn add react-native-webview
react-native link react-native-webview

package.json:
<pre>"dependencies": {
  "expo": "^32.0.0",
  "expokit": "32.0.7",
  "react": "16.5.0",
  "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",//react-native@0.57.1
  "react-native-webview": "^5.4.6"
}</pre>

app/build.gradle:
<pre>configurations.all {
  resolutionStrategy {
    force 'org.webkit:android-jsc:r224109'
    force 'com.android.support:appcompat-v7:27.1.1'
    force 'com.android.support:support-fragment:27.1.1'
    force 'com.android.support:animated-vector-drawable:27.1.1'
    force 'com.android.support:support-core-ui:27.1.1'
    force 'com.android.support:support-core-utils:27.1.1'
    force 'com.android.support:support-vector-drawable:27.1.1'
    force 'com.android.support:support-compat:27.1.1'
    force 'android.arch.lifecycle:runtime:1.1.0'
    force 'android.arch.lifecycle:livedata-core:1.1.0'
    force 'android.arch.lifecycle:viewmodel:1.1.0'
    force 'android.arch.lifecycle:common:1.1.0'
    force 'android.arch.core:runtime:1.1.0'
    force 'android.arch.core:common:1.1.0'
  }
}</pre>

App.js:
```
<WebView
  ref={ref=>this.webview=ref}
  source={{uri:anyUrl}}
  style={{marginTop:20}}
  onNavigationStateChange={e=>{
    if(!e.url.includes(anyUrl)){
      this.webview.stopLoading();
    }
  }}
/>
```

Thank you very much.

**Comment by Adrianotiger** [comment]
I was able to solve it, using  `onShouldStartLoadWithRequest`

**Comment by Eric013** [comment]
> onShouldStartLoadWithRequest

But not with Android :(

**Comment by Adrianotiger** [comment]
I am using Android 9 with expo 34 and it works (I think it was a bug last year, but it should work now).
