### ISSUE TITLE
Require purpose string for iOS "TestFlight"build

### ISSUE THREAD

**Issue by sahdev0** [react-native-community/react-native-webview#462]
Hello Team,

I am using "**react-native-webview**" to render html on Android and iOS. I have created the application and ready to create build, On Android I have successfully created the debug-build but on iOS, we can generate the ipa file and unable to upload into "**TestFlight**". As we can see this plugin using "**geolocation**" in background to fetch current location of web page on mobile web view (I have checked other 3rd party libraries and SDK but not found). But in my application, i'm not using any kind of permission related to location just render the html on available in **JSON** string format.

From **App Store** we are getting the Location related permission. The following email we are getting:

> Dear Developer,
> We identified one or more issues with a recent delivery for your app, "app-name". Please correct the following issues, then upload again. 
> "Missing Purpose String in Info.plist File. Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSLocationAlwaysUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting spring 2019, all apps submitted to the App Store that access user data will be required to include a purpose string.If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy)." 
> "Missing Purpose String in Info.plist File. Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSLocationWhenInUseUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting spring 2019, all apps submitted to the App Store that access user data will be required to include a purpose string **.If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs.** Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy)." 
> Best regards,
> The App Store Team
> 

They require **Purpose String ** for publish our app in iOS "**Info.plist**". Please provide us purpose string with a valid region.

Thanks

**Comment by Titozzz** [comment]
This is not related to Webview. However they added that to the latest RN template so you might need to add it.

**Comment by Titozzz** [comment]
https://github.com/facebook/react-native/issues/20879#issuecomment-421328071

**Comment by sahdev0** [comment]
Thanks @Titozzz , Let me check i this could solve my problem.
