### ISSUE TITLE
Blank screen on android

### ISSUE THREAD

**Issue by ceerqingting** [react-native-community/react-native-webview#466]
RN version: 0.58.6
react-native-webview version: ^5.3.1

show correct on emulator but bank screen on android phone

"overflow: hidden" not working

```
          <WebView
            useWebKit
            allowUniversalAccessFromFileURLs
            mixedContentMode="always"
            originWhitelist={['*']}
            source={{ uri: 'https://www.baidu.com' }}
          />

```

**Comment by giacomoalonzi** [comment]
Same issue here. "react-native": "0.55.2", "react-native-webview": "^5.7.0"

**Comment by ShooterArk** [comment]
I got the same blank view as well:
"react-native": "0.58.5",
"react-native-webview": "^5.7.0"

**Comment by chinavane** [comment]
I got the same blank view as well:
"react-native": "0.59.5",
 "react-native-webview": "5.12.0",

**Comment by chinavane** [comment]
I get the answer,should set webview width and height
`<WebView
          style = {{ width: Dimensions.get('window').width, height: Dimensions.get('window').height }}
          useWebKit
          allowUniversalAccessFromFileURLs
          mixedContentMode = "always"
          originWhitelist  = {['*']}
          source           = {{ uri: 'http://www.baidu.com' }}
        />`

**Comment by sxi-uiteam** [comment]
I got the same blank view as well:
"react-native": "0.59.8",
"react-native-webview": "5.12.1",

**Comment by jqueryalmeida** [comment]
I solved it by:
Opening http://localhost:8081/debugger-ui/ in the browser instead of the IP http://:8081/debugger-ui/
Reloading the app

**Comment by Champkinz** [comment]
@chinavane you solution fixed for me thanks

**Comment by selva8006black** [comment]
for me, adding flex:1 to parent solved this issue.
<View style={{flex: 1}}>
<WebView>...
</View>
