### ISSUE TITLE
Video Url returning as blob: in Android WebView

### ISSUE THREAD

**Issue by rangav** [react-native-community/react-native-webview#470]
Hi I need to get video url from the webpage.

i am injecting the javascript and getting the video src partial code below

```
var video = document.querySelector('video');
  var src= video.src;
window.ReactNativeWebView.postMessage(src);
```

i am getting below blob url on Android 
`
blob:https://www.dailymotion.com/2e668999-b208-462a-b45d-c9db71cd0435
`

where as on iOS i get actual url.
`https://www.dailymotion.com/cdn/manifest/video/x7547yj.m3u8?sec=a4zuF4CDMmfcYvzuxfoP2aDNwS_Wxjb7gdV-E74PQ18QxSyjdLc9s18xOBO4g7sx&progressive=1`

Is there a way to get actual video url on android? or how to convert blob url to normal url?

**Comment by Titozzz** [comment]
This depends only on the website and not really on the webview, there is nothing that can be done from this package. The webview only gives you what loaded inside.
