### ISSUE TITLE
[iOS] Load image downloaded previously

### ISSUE THREAD

**Issue by EstebanBP** [react-native-community/react-native-webview#471]
I have two types of local files: 
- Files of the app. Route is like `/var/containers/Bundle/Application/8B28041B-1575-46D5-A884-E817818FB7E9/MyApp.app/viewer/index.html` (RNFS.DocumentDirectoryPath)
- Files downloaded and stored by the user in the app. Route is like `/var/mobile/Containers/Data/Application/74C447A6-65DE-44FF-8CB0-79D4E09D59CC/Documents/myImage.jpg` (RNFS.MainBundlePath)

As soon as I try to reference a downloaded file from RNFS.MainBundlePath, e.g. 
`<img src="...." />`
I get this error:
`Failed to load resource: The operation couldn’t be completed. Operation not permitted`
```
<WebView
  javaScriptEnabled
  allowFileAccess
  originWhitelist={['*']}
  source={{ uri: `file://${rootPath}/index.html`, baseUrl: rootPath }}
/>
```

Using:
```
"react-native-webview": "^5.5.0"
"react-native-webview-bridge": "^0.40.1"
```

**Comment by Liestambeur** [comment]
I'm having the same issue. It seems to work on https://facebook.github.io/react-native/docs/webview but this will be removed soon.

**Comment by cdoshi** [comment]
@EstebanBP @Liestambeur We are facing the same issue in iOS. We save the files downloaded in the documents dir. If we load it using the webview that is part of the react-native core it works well but it fails to load the files for react-native-webview package.

**Comment by douglaslondrina** [comment]
Hey @EstebanBP , any luck on this? I'm having this problem for weeks now and can't find a way to make it work.

In my case, I'm downloading some files in the Cache folder, the HTML seams to load ok (seeing it on safari web inspector) but js files that are on different folders spam this same error.

I'll appreciate any info on this. Thanks.

**Comment by suwu150** [comment]
I'm having the same issue.
