### ISSUE TITLE
[iOS] Unable to set transparent background

### ISSUE THREAD

**Issue by maxschmeling** [react-native-community/react-native-webview#475]
After upgrading to `5.6.1` from `5.4.1` I'm no longer able to set a transparent background on a `WebView`.

I think it broke in 319a86e2361ac0161cbe2897a907d43b085029fc

The background is always white.

**Comment by maxschmeling** [comment]
I have confirmed that the commit I referenced is the cause and the specific line is https://github.com/react-native-community/react-native-webview/commit/319a86e2361ac0161cbe2897a907d43b085029fc#diff-a32cd1cea4d19bbfff56369224e62299R18 where the webview's container style has `backgroundColor` set to white.

**Comment by Ehesp** [comment]
Thanks for the report. Please could you send in a PR to remove this. @Titozzz do you know the reason for making the style change?

**Comment by maxschmeling** [comment]
I hadn't sent a PR yet because I wasn't sure of the reason for the change. I'm not sure if it's needed for something on Android.

If it's safe to remove, I'll submit a PR to remove the `backgroundColor` style.
