### ISSUE TITLE
WKWebView sound continues to play when ios app is in background

### ISSUE THREAD

**Issue by mailyokesh** [react-native-community/react-native-webview#480]
Hi,

My wkwebview sound in ios continues to play when app goes to background. This is not happening in android or when i use the inbuilt webview as part of react-native 0.58.6. I am converting my app to use this library for the first time as per the react native upgrade notes. Is there any setting I need to turn on to not allow sound playback in background? Am not able to find information either in README or in issue. Any help is appreciated. 

IOS: 12.2
React Native: 0.58.6

**Comment by annie-elequin** [comment]
I don't know if this is related,  but we have iframes with videos in them inside our webview. on iOS, when I leave the simulator and don't interact with it for a period of time (this period of time changes but it's rather long) audio from the videos on the screen will just...begin playing. The only way to then kill the audio is to kill the app and restart.

**Comment by olivierlebel** [comment]
did you find anything @mailyokesh ? I have the same issue.

**Comment by mailyokesh** [comment]
@olivierlebel no we have been experiencing this issue for a very long time. What we ended up doing in our production app is when app state changes just dont render the webview. We are having html games shown inside webview, so due to this every time app goes to background the game has to be reloaded resulting in very bad user experience.

**Comment by MrXyfir** [comment]
This is still an issue.
