### ISSUE TITLE
[iOS] Bug in handling of stopLoading (isLoading stays true)

### ISSUE THREAD

**Issue by winkelsdorf** [react-native-community/react-native-webview#481]
I am providing users with a refresh button which allows reloading _or_ stopping current loading.

During testing I discovered, that on iOS a WebView stopped with `stopLoading()` during a load process will never leave the `isLoading` state anymore (with or without using webKit).

## Steps to reproduce
- Load a larger website (or throttle your network connection)
- During this load call `stopLoading()`

## Expected
- Loading stopped, loading Activity not visible anymore. `isLoading` should revert back to `false`.

## Actual
- Activity spinner stays forever and `isLoading` never changes back to `false`.

## Details
A simple  ```onNavigationStateChange={(navState) => { console.log(navState) });``` is never fired on iOS when calling `stopLoading()`.

## Source

The problem lies in the `didFailLoadWithError` (UIWebView) / `didFailProvisionalNavigation` (WKWebView) method.

Both check for `NSURLErrorCancelled` but just return without setting the `isLoading` state or firing any events:

https://github.com/react-native-community/react-native-webview/blob/ee3a7c4d3430009c5c10db5cec1d09f683361b91/ios/RNCWKWebView.m#L578

https://github.com/react-native-community/react-native-webview/blob/ee3a7c4d3430009c5c10db5cec1d09f683361b91/ios/RNCUIWebView.m#L263

The source comment shows the misunderstanding:

> // NSURLErrorCancelled is reported when a page has a redirect OR if you load
> // a new URL in the WebView before the previous one came back. We can **just**
> // **ignore these** since they aren't real errors.

This is wrong! A cancelled navigation means that the loading state previously set *must* be reverted.

**Comment by Titozzz** [comment]
How would you differentiate redirects or new URL load from navigation cancellation then?

**Comment by winkelsdorf** [comment]
@Titozzz good catch if you want to prevent flickering of the activity view 👍  To do this `isLoading` must be eventually stopped in one of the other iOS event handlers, e.g. `didFail` or `didFinish` for `WKWebView` which are the endpoint delegate methods for any navigation.
