### ISSUE TITLE
Text overlaps when an url is opened via webview

### ISSUE THREAD

**Issue by mithunmo** [react-native-community/react-native-webview#482]
We have used react-native 0.59.3 and react-native-webview 5.6.2 and we are opening a link 
in the webview . But the text is getting overlapped . this is not seen in all phones. 

https://sway.office.com/avNiCY17DWGNC8iz?ref=Link

Attached screenshot
![Screenshot_20190405-171830](https://user-images.githubusercontent.com/5292670/55625663-1097c100-57c7-11e9-857c-1463ba53cee5.png)

Can some one guide  me. In some phones it is more and text is unreadable.

**Comment by mithunmo** [comment]
Hello,
How do i set the following property  in react native as per the following link 
https://stackoverflow.com/questions/16417614/android-webview-html-content-is-overlapping

webSettings.setLayoutAlgorithm(LayoutAlgorithm.TEXT_AUTOSIZING);

**Comment by Titozzz** [comment]
You need to add a prop for the webview that will take effect on android only. Please see how overScrollMode is implemented and do kindof the same :smile:

**Comment by dhananjay2011** [comment]
Hello,

How do I fix the text overlapping issue in Android?
We used react-native: 0.59.5, react-native-webview: 5.11.0
![thumbnail_Screenshot_2021-02-10-17-03-15-24_65591fcd56d744929b74172bd73afd45](https://user-images.githubusercontent.com/4868172/107607569-9efce980-6c5f-11eb-99a2-b48fc2b23002.jpeg)

**Comment by ekfaktldk11** [comment]
Its seem to quite a past issue.  I had a same problem recently, I solved it by ignoring styles 'line-height' & 'margin'. Oh, i used not <WebView />, <HTML /> ('react-native-render-html') instead. There is a prop 'ignoredStyles'.
