### ISSUE TITLE
[Question] Why isn't scalesPageToFit supported in WKWebView ?

### ISSUE THREAD

**Issue by rbadr** [react-native-community/react-native-webview#483]
Hello,

Coming from the legacy implementation of the webview in react native, I used to use scalesPageToFit prop to make the content scale to fit the view, unfortunately this behavior is no longer supported with the new WKWebView. 

Is there a reason it is not supported ? I can still use UIWebView but it is deprecated.

Thanks

**Comment by Titozzz** [comment]
https://forums.developer.apple.com/thread/112191 This is an Apple limitation. You can overcome it by adding https://github.com/react-native-community/react-native-webview/issues/447#issuecomment-477201365
