### ISSUE TITLE
[help wanted] [first issue] Adjusts the webview height according to the content

### ISSUE THREAD

**Issue by marcesdan** [react-native-community/react-native-webview#484]
Hello,

I has other contents above (flatlist) and up (app bar) my webview. And I'm not getting the webview to adjust to the height of the content. The webview shows nothing, unless manually set the height, in the webview style...

My root container 

```jsx
<ScrollView style={{flex: 1}}>
  <AppHeader title={content.title} />
   <Intro content={content.description} />
   <FlatList
    ...
    />
</ScrollView>
```

The component Intro with webview

```jsx
<View style={{flex: 1}}>
  <WebView
   source={{ html: this.props.content }}
  />
</View>
```

How could I achieve it? Any help would be appreciated.

**Comment by marcesdan** [comment]
I solved it using [react-native-autoheight-webview](https://github.com/iou90/react-native-autoheight-webview)

**Comment by MoudiZd** [comment]
@marcesdan But [react-native-autoheight-webview](https://github.com/iou90/react-native-autoheight-webview) is old and have bugs in stopLoading, so we need autoheight feature with this plugin instead of using another outdate plugin

**Comment by hungnq139** [comment]
@MoudiZd use originWhitelist={[]}
originWhitelist => "List of origin strings to allow being navigated to"

**Comment by jsamr** [comment]
You can try webshell `useAutoheight` hook for that purpose https://formidable-webview.github.io/webshell/docs/autoheight
