### ISSUE TITLE
[Android] Prevent deeplinking from triggering the Webview

### ISSUE THREAD

**Issue by TomerRon** [react-native-community/react-native-webview#488]
Hello,

I am currently trying to implement deeplinking into my react-native app, so users can get directed to the app when they click a link in an email.

My app uses a mix of webviews and native components. Essentially, there are two navigation routers (native and webview), and the app takes care of the navigation logic (should I redirect this page on the app level or on the webview level, should I show the webview or not, etc).

Here is the issue: when I click a link and my app opens, the Webview always redirects to that link (for some reason). It's strange, because I don't have any code written for this behavior - it just happens. That's a problem because I would like to handle this action myself. For example, 'My Profile' is a native component, so when a link to `/profile` is clicked I would like to navigate to the native 'My Profile' component - I don't want my Webview to redirect to `/profile`, which doesn't exist.

The handling of the link is easy enough using the `Linking` module of react-native, but the problem is that the Webview always kicks in and redirects to the link, which usually breaks the app. I would like to prevent the Webview from doing anything in this case, so I can handle the action myself.

Here is my Webview code:

```
<WebView
        source={{
          headers: this.props.headers,
          uri: this.initialUri,
        }}
        startInLoadingState={true}
        renderError={this.renderError}
        renderLoading={this.renderLoading}
        thirdPartyCookiesEnabled
        scrollEnabled={false}
        javaScriptEnabled={true}
        ref={this.webView}
      />
```

A common answer I see online is to use `onNavigationStateChange` to prevent the Webview from navigating:

```
<WebView
    onNavigationStateChange={navState => {
        console.log('nav state changed', navState)
        // I can use stopLoading() here to prevent the navigation
    }}
/>
```

However, strangely enough `onNavigationStateChange` **does not fire** in cases where a link is clicked. I expect to see the `console.log` when the Webview redirects me, but I don't, which means I can't prevent the Webview from loading the page.

Does anyone have any suggestions on how to solve this issue? Thanks in advance.

**Comment by TomerRon** [comment]
bump

**Comment by Titozzz** [comment]
Have you tried onShouldStartLoadWithUrl instead?

**Comment by TomerRon** [comment]
Sure, I just added this to the Webview:

```
onShouldStartLoadWithRequest={request => {
    console.log(request)
    return false
}}
```

However it doesn't seem to ever fire. I expect to see the `console.log` whenever a request is made, and I also expect the Webview to not load the request since I `return false`. However neither of these things happen.

**Comment by Titozzz** [comment]
I have no idea how you did your linking, but I don't think the webview would try to do this on its own 🤔

**Comment by TomerRon** [comment]
Yeah, it's a very strange behavior, and it happens even if I remove all my Linking logic... I'm still trying to find the piece of code that causes this to happen but I can't. My guess is this is a sneaky side effect caused by something totally unrelated. I guess I'll try doing this on a physical device and see if it also happens (I've only tried on the emulator so far).

**Comment by TomerRon** [comment]
Just tried it and I get the same result on a real device.

**Comment by oliverdolgener** [comment]
Yes, I can confirm that! We do the link handling ourselves but deeplinks like `mailto:` or `tel:` seem to ignore the `false` return value from `onShouldStartLoadWithRequest`

**Comment by jordangrant** [comment]
Need help on this, https://open.spotify.com/artist/4MCBfE4596Uoi2O4DtmEMz auto opens spotify :/

**Comment by pkf1994** [comment]
got the same, any progress?

**Comment by TomerRon** [comment]
Hey, my apologies, I actually solved this issue a long time ago but I forgot to come back and update the issue. I don't exactly remember what I did, but I do remember that it was a problem on my end that I had to fix. I will take a look at my git logs and give you an update if I find anything.

> Need help on this, https://open.spotify.com/artist/4MCBfE4596Uoi2O4DtmEMz auto opens spotify :/

I don't think there's anything you can do in this case. If a user installed the Spotify app on their phone, then `open.spotify.com` is registered as a deeplink. A wonky solution might be to modify the DOM to change all `open.spotify.com` links to something else, not sure if that's possible but worth a try.

**Comment by jordangrant** [comment]
@TomerRon my sh*tty solution for Spotify was using an archived version of the webpage to prevent the deep link from triggering 😅 We’ll see how long that takes to break, haha.

**Comment by ldco2016** [comment]
@TomerRon , will you be posting your solution? I am in a situation where I have a solution that works for iOS but not Android.

So far I have done this:

```
<WebViewAutoHeight
                key={s.Body.substr(10)}
                source={{
                  //prettier-ignore
                  html: `<body style="font-family: -apple-system, Roboto, sans-serif; background-color: ${lightTheme.grey2} !important; color: ${v2Colors.charcoalDarkest}; font-size: ${moderateScale(14, 0.2)}px;">${s.Body}</body>`
                }}
                onShouldStartLoadWithRequest={request => {
                  console.log(request);
                  return false;
                }}
                onNavigationStateChange={event => {
                  if (Platform.OS === "ios") {
                    if (event.url !== uri) {
                      Linking.openURL(event.url);
                    }
                  }
                }}
              />
```

In the console log I get the following:

```
{ navigationType: 'other',
      canGoForward: false,
      canGoBack: false,
      title: 'about:blank',
      loading: true,
      url: 'https://qa.nfib.com/advocacy/taxes/',
      target: 2847 }
```

That's what I got when I clicked the deep link on Android, so at this point I am unclear of the logic that should go within `onShouldStartLoadWithRequest`.

**Comment by haidar4243** [comment]
Basically, any click that opens a new tab Webview will try to open that link in your mobile application if you have that application. For example, I was using Facebook in my Webview, and whenever I used to go to my save posts screen and click on one of my saved posts it used to open in my Facebook app. I solved this issue by setting this prop ==>  setSupportMultipleWindows={false}.
