### ISSUE TITLE
Inject javascript code in onNavigationStateChange listener

### ISSUE THREAD

**Issue by gberg1** [react-native-community/react-native-webview#489]
Hi, I'm pretty stuck as I need to get the html body off of the webview but only after a redirection occurs triggering the onNavigationStateChange. When the webview initially loads, code flow goes into the onMessage listener, however its too early as I need to wait for user input before redirecting, which after user input then goes into my onNavigationStateChange listener and checks for the redirection url. It's at that point in time that I need to get a handle on the body of the html on the page. Any suggestions? Very stuck thanks! My code is:

_handleNavigationStateChange(webViewState) {
		if (webViewState && webViewState.url && webViewState.url.contains('REDIRECTED_URL') {
			// DO SOMETHING AFTER REDIRECTION;
		}
	}

_onMessage() {
     // TODO not sure what to do in _onMessage
}
render() {
let jscode = `	setTimeout(() => { // Need to wrap in setTimeout to get around unexpected return type err
        				

window.postMessage(document.getElementsByTagName('body').innerHTML)
    			}, 100);
`;

         <WebView 
	        source={{ uri: SOME_URL }}
	        javaScriptEnabled={true}
	        style={styles.webView}
	        ref="sfWebView"
	        onNavigationStateChange={(webViewState) => this._handleNavigationStateChange(webViewState)}
	        onMessage={this._onMessage()}
	        injectedJavaScript={jscode}
/>
}

**Comment by Titozzz** [comment]
I'm not sure I properly understand your problem 🤔
