### ISSUE TITLE
Cannot find module './lib/WebViewTypes'

### ISSUE THREAD

**Issue by annietsai** [react-native-community/react-native-webview#490]
When I run `yarn tsc`, I'm getting this error:

```
node_modules/react-native-webview/index.d.ts:3:54 - error TS2307: Cannot find module './lib/WebViewTypes'.
```

I think it might be related to this PR comment: https://github.com/react-native-community/react-native-webview/pull/171#discussion_r237049523

If I change `lib` to `src`, the error disappears, so I believe it has something to do with how `tsc` transpiles (or rather, isn't transpiling) the `src/` dir into `lib/`. At the end of the linked comment above, LinusU mentions that we should add `"prepare": "tsc"` to the package.json scripts, but I noticed this wasn't added into the package.json. Not sure if this has to do with my issue, but just musing aloud!

**Comment by Titozzz** [comment]
Hello, why are you trying to run this command?

This is supposed to be run when you clone from git, not when installing from npm

**Comment by annietsai** [comment]
Hello @Titozzz I'm running `yarn tsc` inside my repo where the `node_modules` that contains the `react-native-webview` package lives. We recently upgraded to React 16 and are in the process of upgrading the necessary types packages as well, so I just want to make sure that there aren't any type errors with this upgrade

**Comment by Titozzz** [comment]
How did you install react-native-webview into your project?

**Comment by annietsai** [comment]
We followed the steps in the guide here: https://github.com/react-native-community/react-native-webview/blob/master/docs/Getting-Started.md (essentially, the first two commands)

**Comment by Titozzz** [comment]
what are the folders inside of node_modules/react-native-webview 🤔 ?

**Comment by annietsai** [comment]
There are:

- .circleci
- .vscode
- android
- bin
- docs
- ios
- node_modules
- src

**Comment by Titozzz** [comment]
This makes no sense 🤔 can you give me the contents of your package.json?

**Comment by Titozzz** [comment]
When I install I have only
-ios
-android
-lib
which is the expected behavior. Looks like you somehow got the content of github instead of the npm package

**Comment by annietsai** [comment]
So inside our dependencies of the package.json we have:

```
"react-native-webview": "git+https://github.com/react-native-community/react-native-webview.git",
```

Maybe this is why we got the content of Github? Should this be different? 🤔

**Comment by Titozzz** [comment]
yeah that's what I thought.
Please run `yarn add react-native-webview@5.6.2`

**Comment by Titozzz** [comment]
It will update the current version to use latest instead of pulling code from github

**Comment by annietsai** [comment]
Thank you! @Titozzz
