### ISSUE TITLE
webView show only half screen

### ISSUE THREAD

**Issue by OrangeFlavoredColdCoffee** [react-native-community/react-native-webview#491]
![image](https://user-images.githubusercontent.com/15223345/55848782-b27d2c00-5b80-11e9-8d50-e02d9a8ed74d.png)

 "react-native-webview": "^5.2.1",
 "react-native": "^0.56.0",

![image](https://user-images.githubusercontent.com/15223345/55848852-038d2000-5b81-11e9-97d9-ce581e4e191b.png)

android work fine after add userAgent   but ios  not ,

I triedto add  useWebKit props , not work
can you give me some advice? thanks

**Comment by Andreyco** [comment]
Make sure `BaseView` fills screen height and `WebView` fill wrapping `BaseView` (e.g. `flex: 1` for both of them)

**Comment by stanleyoos** [comment]
Hello @OrangeFlavoredColdCoffee , have you found solution for this bug?
