### ISSUE TITLE
Remove console.warn statement(s)

### ISSUE THREAD

**Issue by nikolakanacki** [react-native-community/react-native-webview#492]
This line should be removed. It pops up on the display in development and it already can be handled by the `onError` and `onLoadEnd` props.

https://github.com/react-native-community/react-native-webview/blob/ee3a7c4d3430009c5c10db5cec1d09f683361b91/src/WebView.android.tsx#L165

**Comment by cristianoccazinsp** [comment]
Any update on this? This is causing some noise when logging is enabled. If anything, make it just a debug log.

**Comment by cristianoccazinsp** [comment]
I believe this is still a problem.
