### ISSUE TITLE
[iOS] different behaviour sharing cookies between WKWebView and fetch on simulator vs real device

### ISSUE THREAD

**Issue by edpaget** [react-native-community/react-native-webview#494]
I've noticed a difference in behaviour when using WKWebView with `useWebKit={true}` between the simulator and real device (an iPhone 5s running iOS 12.2 in this case).

Basically my App's initialization flow is:
* Login on a webview. 
* After successful logon webview sends an message to the App that it has logged in
* App uses React-Native's `fetch` to load some additional data

I'm expecting the cookie set on logon in the WebView to be used by `fetch` to make its requests and that works on Android and real iOS device, but not in the iOS simulator. 

I saw [this issue](https://github.com/CRAlpha/react-native-wkwebview/issues/144) on another WKWebView project and noticed some other discussion of WkWebView cookie handling and just wanted to make sure the behaviour I saw on the real device was what should happen. 

Thanks for maintaining this project!

**Comment by rogerkerse** [comment]
Same problem, fetch has no access to cookies on ios simulator still. I haven't tried real device

**Comment by rogerkerse** [comment]
I tried on real device as well and I got nothing. No cookies.
This is still quite a problem and blocks from upgrading to RN 0.60.x :/

**Comment by amiratak88** [comment]
I have the same issue. Cookies are sent on real device but not iOS simulator.
