### ISSUE TITLE
[Android] Geolocation takes longer time to return in WebView than native or browser

### ISSUE THREAD

**Issue by michaelcfl** [react-native-community/react-native-webview#495]
# Environment
- RN v0.58.6
- react-native-webview v5.3.0

# Android version tested (All real devices):
- 7.0
- 9.0

# Description
Used a WebView to wrap a page with html5 API `navigator.geolocation.getCurrentPosition` function call. It is working fine (return in <0.1s) in both `browser`, `iOS` (both `UIWebView` and `Safari`) and `android` (browser(chrome)). However, it takes noticeable long time (around 1-4s) to get the location information when using `webview` in `android`. 

# Code used
Webpage:
```
navigator.geolocation.getCurrentPosition(
        successHandler,
        errHandler,
        { enableHighAcuracy: true }
);
```

RN:
```
<WebView
            source={{ uri: myurl }}
            javaScriptEnabled={true}
            domStorageEnabled={true}
            startInLoadingState={true}
            geolocationEnabled={true}
            ref={ref => {
              this.webview = ref;
            }}
       }}
/>
```

# Step to reproduce
- Use the RN code above
- replace `myurl` with any webpage with geolocation function call, for example `https://mylocation.org/`
- build and test using an android devices

## Note
I believe this may related to the `Android` native WebView as I can reproduce the same result using native `android webview`

**Comment by Titozzz** [comment]
If this is related to android webview there is nothing we can do here, but submit a bug to android webview directly goo.gl/9qkbdn, please :)
