### ISSUE TITLE
onNavigationStateChange is called with different arguments 

### ISSUE THREAD

**Issue by paulxuca** [react-native-community/react-native-webview#504]
When called by another function on the JS side, it's called with `event.nativeEvent` <- Correct

https://github.com/react-native-community/react-native-webview/blob/master/src/WebView.ios.tsx#L205

When called by native side, it's called with `event` <- Incorrect

https://github.com/react-native-community/react-native-webview/blob/master/src/WebView.ios.tsx#L327

We should pass `this.updateNavigationState` as `onNavigationStateChange` into the `<Webview/>` component.

**Comment by TMomemt** [comment]
Same problem for `onLoadingStart` / `onLoadingFinish` / `onLoadingProgress` , in WebViewTypes.d.ts their parameter's type is `WebViewNativeEvent` but actually `NativeSyntheticEvent<WebViewNativeEvent>`

**Comment by TMomemt** [comment]
Same problem for `onLoadingProgress`.

In WebViewTypes.d.ts it's parameter is WebViewProgressEvent but actually NativeSyntheticEvent< WebViewProgressEvent >

**Comment by Titozzz** [comment]
Please submit PRs :)
