### ISSUE TITLE
Memory leak in iOS WebView communication

### ISSUE THREAD

**Issue by hypergeometric** [react-native-community/react-native-webview#505]
I'm investigating using a WebView for a long-lived worker process. However, I've noticed that the message passing via `injectJavaScript`/`window.ReactNativeWebView.postMessage` seems to leak memory.

I've created a simple repro at https://github.com/hypergeometric/WebViewLeak with the following App code.

```jsx
export default class App extends Component {
  state = { messageCount: 0 };

  render() {
    const html = `
      <html>
      <head></head>
      <body>
        <script>
          const message = "Hello!".repeat(1000000);
          setInterval(function () {
            window.ReactNativeWebView.postMessage(message);
          }, 1000);
        </script>
      </body>
      </html>
    `;

    return (
      <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
        <View style={{ height: 0 }}>
          <WebView
            originWhitelist={['*']}
            source={{ html }}
            onMessage={() => {
              this.setState(state => ({
                messageCount: state.messageCount + 1
              }));
            }}
          />
        </View>
        <Text style={{ fontSize: 20 }}>{this.state.messageCount}</Text>
      </View>
    );
  }
}
```

I'm sending ~6MB using `postMessage` every second but this seems to allocate memory that is never released, even after applying memory pressure in the simulator (the same happens on a physical device). The size of the message doesn't seem to matter in my testing, it just obviously affects the speed of memory consumption.

Profiler at startup:

<img width="243" alt="Screenshot 2019-04-16 at 12 54 52" src="https://user-images.githubusercontent.com/130065/56207512-da6c0400-6046-11e9-8e2e-7a000ce2eb3d.png">

Profiler at 30s:

<img width="250" alt="Screenshot 2019-04-16 at 12 47 18" src="https://user-images.githubusercontent.com/130065/56207227-210d2e80-6046-11e9-8d7c-8d3549d622b3.png">

Profiler at 60s:

<img width="250" alt="Screenshot 2019-04-16 at 12 47 51" src="https://user-images.githubusercontent.com/130065/56207241-266a7900-6046-11e9-93b3-b8599ddd3d02.png">

This also happens with `injectJavaScript` and both UIWebView and WKWebView.

I've found [this report](https://openradar.appspot.com/49722601) which I think is the same problem and points to an iOS issue. This obviously means I can't use a WebView as a long lived process if every message consumes memory. 

Does anyone with more experience than me know if there could be a bug in my usage or with `react-native-webview` that could be causing this or if we're at the mercy of an iOS bug?

**Comment by Titozzz** [comment]
This is very worrying. Have you tried profiling with chrome?

**Comment by Titozzz** [comment]
If the leak is on the native side you need xcode to debug this ofc

**Comment by prcode** [comment]
Hey guys, look at this:
If you change 
`const message = "Hello!".repeat(1000000);`
to
`var message = "Hello!".repeat(1000000);`

And then after 
`window.ReactNativeWebView.postMessage(message);`
you add
`message = undefined;`

There is no leak anymore. 

So, must be something related to const vars management.

**Comment by hypergeometric** [comment]
Yep that absolutely works! Fascinating.

Thanks so much for figuring this out!

**Comment by mvn-cuongle-dn** [comment]
@prcode 
Why we not code like this ?
`window.ReactNativeWebView.postMessage("Hello!".repeat(1000000));`
