### ISSUE TITLE
Commit a661df1ffcfdd4b2eb1b82dd05005541897b784e breaks page view

### ISSUE THREAD

**Issue by tapir** [react-native-community/react-native-webview#507]
So this is an old commit.
It basically changes how scalesPageToFit works. After this commit some of my pages became bigger than they should and horizontal/vertical scrolls have been enabled on the page. It took me hours to understand why this was happening until I've finally noticed I've updated the react-native-webview unwillingly.
Setting scalesPageToFit to false fixes it but I'm guessing default behaviour shouldn't change.

**Comment by Titozzz** [comment]
Are you using any meta tags to adapt your page layout? If not maybe you should add some. Such as initialScale and others

**Comment by tapir** [comment]
I have this on my pages
```
<meta content="width=device-width, initial-scale=1" name="viewport">
```
