### ISSUE TITLE
Some videos not playing in webview, but it allows to play on mute state.

### ISSUE THREAD

**Issue by CodeHunterDhi** [react-native-community/react-native-webview#510]
Some Videos are not playing in webview. But, when we mute and then click play button.
It starts playing the video.If we unmute, it pauses and prevents further click to play button.

**The code which I used is mentioned below.

<WebView source={{ uri: 'https://partner.aprrow.com/#/content?id=d5b4484fd95347f8a0c959f46152a3bca899' }} />**

Note : Youtube videos are playing perfectly 

Please help me to solve the issue...

**Comment by rxhivzero** [comment]
Try set webview mediaPlaybackRequiresUserActio={false}
