### ISSUE TITLE
Center content

### ISSUE THREAD

**Issue by F-Moody** [react-native-community/react-native-webview#512]
Hello there,
i have a webview with an svg image as source uri. The image is shown at the top of the webview and i'm trying to center it with no success.

`<WebView
                        ref={ref => this.webViewref = ref}
                        style={{
                            alignSelf:'center',
                            flex: 0,
                            height: '100%',
                            width: '100%',
                            display: this.state.svgReady ? undefined : 'none',
                            alignContent:'center',
                            textAlign:'center'
                        }}
                        source={this.props.source}
                        scalesPageToFit={true}
                        bounces={false}
                        javaScriptEnabled={false}
                     />`

**Comment by Titozzz** [comment]
Your code is sizing the webview to the size of its parent, it has no impact on the content loaded inside the webview. Either resize your webview, change the source svg file, or inject custom javascript inside the webview to style it
