### ISSUE TITLE
Can't display xls file instead of downloading on android.

### ISSUE THREAD

**Issue by Kstar0722** [react-native-community/react-native-webview#514]
Hey there! Thanks for your hard work on this package.

I want to display excel file instead of downloading on android.
so I tried to solution that @Titozzz mentioned to https://github.com/react-native-community/react-native-webview/issues/224#issuecomment-453536765 issue.

but I can still download file. not display.
Is there any solution?

Here's the example
`
<WebView
          ref={(ref) => (this.webViewRef = ref)}
          style={{ flex: 1 }}
          source={{ 
            uri: "http://www.lagotzki.de/pdftk/beispiel_neu.pdf",
            headers: {
              "Content-Type": "application/pdf",
              "Content-Disposition": "inline",
              filename: "beispiel_neu.pdf"
            }

          }}
          userAgent={userAgent}
          onLoadStart={this.onLoadStart}
          onLoadEnd={this.onLoadEnd}
          onNavigationStateChange={this.onNavigationStateChange}
/>
`

Here's the packages I am using.
"react": "16.6.1",
"react-native": "0.57.7",
"react-native-webview": "^5.7.0"

**Comment by Titozzz** [comment]
I don't know any solution to do that as even chrome browser would download the file. You might want to use another package to use an XLMS viewer

**Comment by Kstar0722** [comment]
@Titozzz, thanks for your reply.
but you know it opens in iPhone. please let me know why it's different working on iOS and Android

**Comment by Titozzz** [comment]
iPhone are capable of doing this natively, Android doesn't. I guess it's because apple didn't want you to install an app to do that and Google prefers you to choose
