### ISSUE TITLE
TypeError: Cannot use 'in' operator to search for 'method' in 9

### ISSUE THREAD

**Issue by vmarquet** [react-native-community/react-native-webview#518]
I had this code working in version 5.0.1:

```
<WebView
    source={require('page.html')}
/>
```

and in 5.7.0, it crashes on Android (still works on iOS):

<img width="392" alt="Capture d’écran 2019-04-20 à 23 26 58" src="https://user-images.githubusercontent.com/6226610/56463982-9d559800-63df-11e9-8179-dbda4ca5c70d.png">

I'm assuming that it happens because of [this line](https://github.com/react-native-community/react-native-webview/blob/24be864cebab84e31cf5cae229bd8cc7d9c09a3d/src/WebView.android.tsx#L254), introduced by the js to ts rewrite ([this commit](https://github.com/react-native-community/react-native-webview/commit/453b7dd3a0b821de6dd0578c5df7d4004d74f46c)).

It seems the author of this rewrite forgot to handle using `require` in the `source` prop.

I'm currently bypassing the problem this way:

```
<WebView
    source={{uri: Image.resolveAssetSource(require('page.html')).uri}}
/>
```

This should be fixed though and a test should be added to ensure it doesn't happen again.

**Comment by Titozzz** [comment]
@vmarquet Docs never specified you syntax should have worked which is why you encountered that issue.
See (docs)[https://github.com/react-native-community/react-native-webview/blob/master/docs/Reference.md#source].

Regarding 
> This should be fixed though and a test should be added to ensure it doesn't happen again. 

If you think changes need to be done in a repository, please submit a pull request, since you already spent time to track the bug, it's even more enjoyable.

**Comment by danielgindi** [comment]
@Titozzz This answer is a bit weird, as the code clearly tries to accept an Image identifier, but a bug precedes that piece of code and prevents it. So it clearly is a bug, no matter what the docs say...

**Comment by Titozzz** [comment]
You usually want to base your code on how it is documented, not implemented because the implementation can change any time

**Comment by vmarquet** [comment]
@Titozzz Because the documentation cannot change?

<img width="1183" alt="Capture d’écran 2019-04-29 à 14 06 06" src="https://user-images.githubusercontent.com/6226610/56895203-9fc38c00-6a88-11e9-9c7f-496ba8ad549d.png">

Do you really expect people to read the entire documentation and notice the api changes at every update? No, that's why you should not drop features silently, that's why properly managed projects have a changelog file, but there is none in this repository.

**Comment by Titozzz** [comment]
https://github.com/react-native-community/react-native-webview/releases

**Comment by paldepind** [comment]
I am also experiencing this issue after moving from the WebView in react-native to this WebView.

If I change [this line](https://github.com/react-native-community/react-native-webview/blob/24be864cebab84e31cf5cae229bd8cc7d9c09a3d/src/WebView.android.tsx#L254) as follows.

```diff
- if (source && 'method' in source) {
+ if (typeof source !== 'number' && source && 'method' in source) {
```

Then the problem goes away. However, then I simply run into [this bug](https://github.com/react-native-community/react-native-webview/issues/428) instead.

If `<WebView source={require('page.html')} />` is no longer supported is there then another way to load a local HTML file into a WebView?

**Comment by animaonline** [comment]
This should be reopened and looked into @Titozzz

**Comment by paldepind** [comment]
Here's a workaround we used to get around this issue after upgrading from Expo 32 (which includes the react-native webview) to Expo 33 (which includes react-native-webview):

1/ Create a Webpack setup that bundles our local HTML, JS, CSS and icons fonts into a single self-contained HTML file.
2/ Write a small script that creates a JS file of the form `export default "<html>.....</html>"` based on the HTML bundle.
3/ Simply import the JS file and load the HTML string into the WebView with `source={{ html: htmlString }}`.

In case this is useful to anyone I've shared the script and the Webpack setup in a Gist here: https://gist.github.com/paldepind/8cbc430575cd075144d291b0eff463fc

**Comment by Titozzz** [comment]
@paldepind what happens if you use 
```
<WebView source={{ html: require('page.html') }} />
```
?

**Comment by paldepind** [comment]
@Titozzz Thank you for the comment and the great work you do on react-native-webview.

Using `source={{ html: require('page.html') }}` does not work for me. `require` returns a number and on iOS I simply get a webview with that number as its content. On Android I get the error "Value for html cannot be cast from Double to String". It seems that the `html` property does not handle the resource id's returned by `require`.

**Comment by bfelbo** [comment]
> Here's a workaround we used to get around this issue after upgrading from Expo 32 (which includes the react-native webview) to Expo 33 (which includes react-native-webview):
> 
> 1/ Create a Webpack setup that bundles our local HTML, JS, CSS and icons fonts into a single self-contained HTML file. 2/ Write a small script that creates a JS file of the form `export default "<html>.....</html>"` based on the HTML bundle. 3/ Simply import the JS file and load the HTML string into the WebView with `source={{ html: htmlString }}`.
> 
> In case this is useful to anyone I've shared the script and the Webpack setup in a Gist here: https://gist.github.com/paldepind/8cbc430575cd075144d291b0eff463fc

Thanks a lot for sharing this @paldepind! 

It’s been two years and there’s been a lot of updates to this repo. I’d be curious to hear if your approach still works for you?
