### ISSUE TITLE
TypeError: undefined is not a function (evaluating '_react2.default.createRef()')

### ISSUE THREAD

**Issue by taimoorimran** [react-native-community/react-native-webview#519]
I am getting the following error while implementing a simple webView with red screen on android:

**TypeError: undefined is not a function (evaluating '_react2.default.createRef()')**

**Environment:**
 - OS: Android
 - OS version: Nougat - 7.0
 - react-native version: react-native: 0.52.0
- react-native-webview version: 5.7.0

**Comment by Titozzz** [comment]
This package needs react-native@0.57 at least to work properly. If you are below that, just import {WebView} from 'react-native' directly.
