### ISSUE TITLE
Android splash a blank screen when switch tabs in BottomTabNavigator

### ISSUE THREAD

**Issue by jinzunyue** [react-native-community/react-native-webview#523]
**Bug description:**
I'm using BottomTabNavigator of "react-navigation" as my UI fragment.One tab is a screen contains only webview,the others only contains a Text.But when i switch the tab from the others to the tab contains webview,the webview will always splash a blank screen,then show the html.The more complex the html is,the more the blank screen continue.

**To Reproduce:**

1. react-native init demo
2. npm install react-native-webview
3. npm install react-navigation
4. simplely create a bottomTabNavigator with two tabs,one contains a webview,the others contain whatever else
5. give a url which contain a lot of pictures or somethings to the webview. [Exam url](https://statics.dapp365.io/appIndex?lang=zn&source=eos)
6. react-native run-android
7. switch the other tab to the tab contains a webview,there is always a splash blank screen while it's ok on ios.

**Expected behavior:**

There is no any splash blank when switch tabs,like it behaves on ios.

**Screenshots/Videos:**

[187A17AECD215B476CC605CC1F26EABD.mp4.zip](https://github.com/react-native-community/react-native-webview/files/3106891/187A17AECD215B476CC605CC1F26EABD.mp4.zip)

**Environment:**
 - OS: mac
 - OS version: latest
 - react-native version: 0.59.0
 - react-native-webview version: 5.7.0
- react-navigation version: 3.8.1

**Comment by jinzunyue** [comment]
Anyone can help this?

**Comment by mmohtta** [comment]
+1
