### ISSUE TITLE
Not able to play embedded video of twitter and instagram in android

### ISSUE THREAD

**Issue by mmohtta** [react-native-community/react-native-webview#526]
Hi,
 I was trying to embed twitter and instagram feeds into my application. It works fine in IOS but not in Android.
Reproduce bug steps: 
1. Take any feed of twitter or instagram which consists of video.
2. Provide this feed as html to Webview.
3. It would render perfectly in both IOS and Android.
4. But when you try to play that video in Android. It won't.

Please provide solution

**Comment by arghyaExicube** [comment]
+1

**Comment by Titozzz** [comment]
Saying "please provide solution" isn't going to help sadly. You have to investigate more than that

**Comment by mmohtta** [comment]
I have investigated.
Events are not fired when we click on video player of embedded in android. Same work for iOS.

**Comment by Charlie-Hua** [comment]
@mmohtta have you try to mute the video and play? like mentioned in #510 ?

**Comment by karvulf** [comment]
Same problem, it would be awesome to fix that

**Comment by tijs** [comment]
@Titozzz i have setup a test repo showing this same issue: https://github.com/tijs/twitterVideoTest

To reproduce:

- clone repo, install deps, etc
- start the RN app on an android phone
- a tweet with a video will be shown
- if you tap play it will most likely show a screen to accept privacy & conditions
- if you agree it will display a blank screen

Could be specific to twitter but i've seen other reports about facebook video, etc as well so assuming this is related.

I've added parameters for enabling thrid party cookies, domstorage and tries with hardware acceleration on and off since this is mentioned a lot in other tickets about this issue for pure native webviews. No combination of parameters seems to help though.

**Comment by tijs** [comment]
I can reproduce the exact same issue in a pure native android project as well so might be an android/twitter limitation.. test repo here: https://github.com/tijs/twitterWebviewNative

**Comment by tijs** [comment]
Found a fix. Actually quite simple; adding the baseUrl for the widget (twitter, facebook, etc) will make the player work as expected, e.g.

`source={{ html: '<your embed snippet>', baseUrl: 'https://twitter.com' }}`

**Comment by Titozzz** [comment]
Thanks for the solution. If someone wants to document this I can merge a pr

**Comment by rossjohnsonMP** [comment]
I don't see how this is an acceptable solution - if you're embedding some html which has a twitter or instagram video embedded are you meant to loop over the html and check if it has one or the other? what if it has both?

**Comment by girish54321** [comment]
@tijs 
not working for me

`<WebView
            style={{ backgroundColor: "#55fcfc", width: 320, height: 500 }}
            originWhitelist={["*"]}
            source={{
              html: `<!DOCTYPE html>
        <head>
            <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
            <script type="text/javascript" src="https://platform.twitter.com/widgets.js"></script>
        </head>
        <html>
            <body>
            ${data.html_content}
            </body></html>`,
              baseUrl: "https://twitter.com",
            }}
            allowsInlineMediaPlayback={true}
            mediaPlaybackRequiresUserAction={false}
            domStorageEnabled={true}
            geolocationEnabled={true}
            javaScriptEnabled={true}
            sharedCookiesEnabled={true}
            thirdPartyCookiesEnabled={true}
            scrollEnabled={false}
          />`
