### ISSUE TITLE
symbol(s) not found for architecture x86_64 - libRNCWebView.a(RNCWKWebView.o)

### ISSUE THREAD

**Issue by vvusts** [react-native-community/react-native-webview#527]
**Bug description:**
Android work fine.
IOS build fine from xCode but if I run react-native run-ios from terminal I get:
```
Undefined symbols for architecture x86_64:

  "_OBJC_CLASS_$_RNCWKProcessPoolManager", referenced from:

      objc-class-ref in libRNCWebView.a(RNCWKWebView.o)

ld: symbol(s) not found for architecture x86_64

clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
I tried build clean, clear deriveData folder, kill metro, relink library, reinstall library.

**Expected behavior:**
That I can build project by react-native run-ios

**Environment:**
 - OS: Mojave
 - OS version: 10.14.2
 - react-native version: 0.57.8
 - react-native-webview version: 5.3.1

**Comment by shawnarneygit** [comment]
try changing to the legacy build system in your ios project settings if you are using xcode 10+.

**Comment by vvusts** [comment]
@shawnarneygit it works when I set it to legacy.
But is is stable solution or just a workaround?

**Comment by shawnarneygit** [comment]
that is the recommended solution.
