### ISSUE TITLE
Cookies are lost on iOS after application closing

### ISSUE THREAD

**Issue by alex-mironov** [react-native-community/react-native-webview#528]
Cookies seems to be lost after closing an application. Is it expected behaviour?

**Environment:**
 - OS: iOS
 - react-native version: 0.57.7
 - react-native-webview version: 5.2.4

**Comment by gorvinsky** [comment]
Having the same problem on Android.

**Environment:**

- OS: Android
- react-native version: 0.59.5
- react-native-webview version: 5.7.0

**Comment by GokulDharumar** [comment]
having the same problem on both android and ios

react native - .57.8
react-native-webview version - 5.3.0

**Comment by wildkatana** [comment]
Same :/

**Comment by nuriye** [comment]
I have the same Issue, I guess.
The Cookies are not lost directly after closing the App (swiping the App up in iOS) or after a restart of the Phone. But after some Time. The Cookie Lifetime is set to 10 Yrs, but the User gets logged out after Days/Weeks.

I wrote about the Problem here: https://stackoverflow.com/questions/56440239/react-native-webview-user-gets-logged-out-despite-10-year-login-cookie

**Comment by BettyJJ** [comment]
Seems like cookie used to be persisted. Maybe this bug appeared just recently?
https://github.com/react-native-community/react-native-webview/issues/207#issuecomment-498321766

**Comment by JustPassingThrough** [comment]
Any updates regarding this, it appears to happen at random but sometimes even after just a few hours.

**Comment by anurag060** [comment]
Any progress on this? There is no cookie issue in android. But in iOS, on closing the app, the cookie is getting automatically cleared it seems and the user will be landed on login screen on reopening the app, which is not acceptable.

**Comment by texmex44** [comment]
Same issue here

**Comment by texmex44** [comment]
You need to ensure that the cookies have an expiry date set on the server-side.
Cookies without an expiry date are considered 'session only' and will get cleared when you restart the app.

That worked for me

**Comment by vanyasem** [comment]
@texmex44 I have my cookies with proper expiry date. The cookies on the webview don't get cleared every time, but they do at random times (once per day or a couple of hours). looking for a possible solution, still..

**Comment by vanyasem** [comment]
We had a bug that sometime clearing PHPSESSID (which is a session only cookie) cleared the auth as well, resolving it fixed the issue indeed

**Comment by daanpape** [comment]
We also experience this problem

**Comment by nomi9995** [comment]
i have resolved issue and tested with php. you can check my solution here: https://stackoverflow.com/a/62071590/8079868

**Comment by adesh1167** [comment]
This may sound silly but I was facing same issue just today.  The session was persisting on Android but  not on IOS so I easily believed it was an issue with IOS.

but after hours of debugging, I realized it was my own mistake. I forgot to declare session_start() in my php file. But I'm still confused how android managed to work fine without that declaration.

**Comment by adesh1167** [comment]
Firstly, try to explain what exactly is the behavior you want so we can know if using cookies is the best option in the first place. Cookies might function perfectly in some scenarios for a website but might not be the case for an app.

**Comment by Joedmin** [comment]
I am making a mobile application for a website, that does not have one and since I cannot reverse engineer websocket comminucation to use the API, all I can do is to just use `WebView` and rely on it and the website to handle login cookies. The thing is that currently, the `WebView` will delete all of the website's cookies so I have to login each time after restarting the application.

**Comment by DSp4wN** [comment]
The issue is still there on android it keeps logging me out fir certain amount of time on first install whenever I kill the app and after certain time it starts working properly

Packages: 
"expo": "51.0.8",
"react": "18.2.0",
"react-native": "0.74.1",
"react-native-gesture-handler": "~2.16.1",
"react-native-webview": "^13.8.6"

**Comment by adesh1167** [comment]
I believe you already generate authentication token upon login. This authentication token is stored in the app's async storage. A copy of the token is also stored on the server along with the id of the account associated with it.

Whenever the app is opened again after being closed, the token is fetched from the async storage and a request is sent to the server with it. On the server,  you'll query the database with the token to know if it exists and you'll fetch the user id associated with it. You'll then create a new session. The php file doing the checks and creating the session must have session_srart() at the top. Then you'll set $_SESSION['id'] (or any other identifier you use)

With this, subsequent calls made from the app to the server will keep that same $_SESSION until the app is closed.

So in my case, the only mistake I made was omitting session_start() at the top of my php file. This made me logged in for first few API calls from the app then I noticed I wasn't logged in again on subsequent calls.

**Comment by smohadjer** [comment]
Why is this issue closed? I have the same problem. Cookies are gone from webview after app has been in background for a while!

**Comment by duskload** [comment]
Same here. 

1) Cookies are gone from Webview not only when you've been on the background for a while.
2) Cookies are gone if you shut down an app immediately after setting a cookie.

Point two can be resolved by just waiting for 20 seconds or more, I guess cookie is being preserved with some delay, like described [here](https://github.com/react-native-webview/react-native-webview/issues/207#issuecomment-720472845)

**Comment by EArminjon** [comment]
Maybe same as for Flutter InAppWebview : https://github.com/pichillilorenzo/flutter_inappwebview/issues/2355

Different techno but maybe that can help : 

- InAppWebview package call flush() after cookie creation/deletion, check that your package did same.
- On our InAppWebView widget, we call flush() in the dispose() method to force cookies sync between app and webview.
- On app start we call. flush() to force cookies sync between app and webview.

(As flush() didn't exist on iOS -> i call a fake setCookies() to force the synchronisation)

**Comment by weristwiegott** [comment]
> You need to ensure that the cookies have an expiry date set on the server-side. Cookies without an expiry date are considered 'session only' and will get cleared when you restart the app.
> 
> That worked for me

Thanks, mate. It worked for me too.
