### ISSUE TITLE
Cache expires before it should

### ISSUE THREAD

**Issue by co0redump** [react-native-community/react-native-webview#529]
**Bug description:**
When loading a url with a cache protocol in the response headers like:
```
cache-control: private, max-age=604800, must-revalidate
date: Tue, 23 Apr 2019 03:00:11 GMT
expires: Tue, 30 Apr 2019 03:00:11 GMT
```
The files will be cached for only several hours, not  a week as indicated in the response header.

**To Reproduce:**
Add a webview:
```
<WebView
    source={{ uri: this.props.url }}
    javaScriptEnabled={true}
    ...
/>
```
Make sure to load a source uri that has a long cache period setup.

Start the app, website will be loaded correctly
Set device to Airplane mode
Reload app, site will still be loaded correctly from cache
Wait several hours (I haven't pinpointed the exact time yet, but > 8 it seems)
Reload app, nothing will be loaded from cache now

**Expected behavior:**

Keep cache as long as the response headers indicate

**Screenshots/Videos:**

**Environment:**
 - OS: Android (Didn't test on iOS)
 - OS version: Android 9
 - react-native version: 0.59.5
 - react-native-webview version: 5.2.1 (will try upgrade, but changelogs say nothing about cache and it'll take several hours to test)

**Comment by Titozzz** [comment]
Thanks for the insights. If you find more infos I'm interested

**Comment by JakeRawr** [comment]
I'm actually interested in knowing how long the webview caches the files. 
Is it default to 7 days? and is there a way to set the limit?

**Comment by co0redump** [comment]
It's definitely not 7 days. I tested on both Android and iOS now and I get 1 day, even if the response headers are set to 7 days. I haven't found a solution yet to be able to keep cache for 7 days.
