### ISSUE TITLE
this.webview.injectJavaScript method not redirecting the page

### ISSUE THREAD

**Issue by ahmermunaf** [react-native-community/react-native-webview#530]
this.webview.injectJavaScript method not redirecting the page

code :

const newURL = 'https://facebook.github.io/react-native/';
const redirectTo = 'window.location = "' + newURL + '"';
this.webview.injectJavaScript(redirectTo);

I have also tried with true in the end of the script but no luck.

"react-native": "0.57.3"
"react-native-webview": "^5.6.2"

**Comment by Titozzz** [comment]
Please open the Webview console following the debugging guide and check if there are any errors
