### ISSUE TITLE
BackgroundColor in loadingState is always white

### ISSUE THREAD

**Issue by campsafari** [react-native-community/react-native-webview#532]
The backgroundColor does not set the backgroundColor of the loadingView.
This color is hardcoded to white. It works only when i set useWebKit={false}. Which leads to a white flash when the WebView is initializing.

**To Reproduce:**
<WebView
                        style={{ backgroundColor: '#000000' }}
                        ref={(ref) => this.webview = ref}
                        source={{ html }}
                        scrollEnabled={false}
                        mediaPlaybackRequiresUserAction={false}
                        allowsInlineMediaPlayback={true}
                        onShouldStartLoadWithRequest={this.onWebviewRedirect}
                    />
**Expected behavior:**

The background should be the color defined via backgroundColor when the Webview is initializing.

**Environment:**
 - OS: iOS
 - OS version: 11.4
 - react-native version: 0.59.3
 - react-native-webview version: 5.7.0

**Comment by Titozzz** [comment]
Can you adjust the loading behavior with the renderLoading prop ?

**Comment by campsafari** [comment]
@Titozzz ah i see, yes this does the trick (loading view is now green):
startInLoadingState={true}
renderLoading={() => <View style={{flex: 1, backgroundColor: 'green'}}></View>}
