### ISSUE TITLE
Invalid URI prop doesn't trigger onError or renderError callbacks

### ISSUE THREAD

**Issue by AndrewHenderson** [react-native-community/react-native-webview#533]
**Bug description:**
Providing an invalid [`source.uri`](https://github.com/react-native-community/react-native-webview/blob/master/docs/Reference.md#source) prop does not result in [`renderError`](https://github.com/react-native-community/react-native-webview/blob/master/docs/Reference.md#rendererror) or [`onError`](https://github.com/react-native-community/react-native-webview/blob/master/docs/Reference.md#onerror) being executed. Instead the WebView remains in the loading state and a `console.warn` for an unhandled promise rejection is displayed.

**To Reproduce:**
Use `test` as your uri prop.

```jsx
<WebView
    source={{ uri: 'test' }}
    onError={syntheticEvent => {
        const { nativeEvent } = syntheticEvent;
        console.warn('WebView error: ', nativeEvent);
    }}
    renderError={errorName => <Error name={errorName} />}
/>
```

**Expected behavior:**
Either `onError` or `renderError` should be executed.

**Screenshots/Videos:**
<img width="371" alt="Screen Shot 2019-04-26 at 11 43 56 AM" src="https://user-images.githubusercontent.com/1031565/56829532-d85d2e80-6818-11e9-9834-53f51bd69b54.png">

<img width="371" alt="Screen Shot 2019-04-25 at 11 43 56 AM" src="https://user-images.githubusercontent.com/1031565/56764605-fa43ac00-6759-11e9-94bd-22605597dcde.PNG">

**Environment:**
 - OS: macOS Mojave
 - OS version: 10.14.4
 - react-native version: 0.57.8
 - react-native-webview version: 5.6.0

**Comment by atlanteh** [comment]
Happens to me too. Can someone fix this?

**Comment by pauldcollins** [comment]
I am having the same problem, except the error shown seems to be different. The window containing the *WebView* opens fine, but there's an error message where the content should be:

`NoSuchKey The specified key does not exist file-that-does-not-exist.html?D4F655...`

And my React code:

```
renderError={errorName => console.log('ERROR', errorName)}
onError={syntheticEvent => {
    const { nativeEvent } = syntheticEvent;
    console.warn('WebView error: ', nativeEvent);
}}
```

Also testing in iOS simulator.

Thanks for any help.

**Comment by iamisathya** [comment]
+1

**Comment by benjaminreid** [comment]
Yep, I still hit this issue sadly.

**Comment by SirVeryBritish** [comment]
This is still an issue with version 8.0.3

**Comment by mikehardy** [comment]
This shouldn't be closed, it's still an issue.
If you try to load some invalid URL there appears to be no way to avoid the promise rejection warning ?

**Comment by rechard25846** [comment]
Any solution for this ?

**Comment by betopompolo** [comment]
+1

**Comment by Rajan-Savaliya-spt** [comment]
i still have this error........error handlling in react native webview

**Comment by enesbildiren95** [comment]
Any solution?

**Comment by monkora** [comment]
Still happening

**Comment by FatemeMirzaeii** [comment]
still

**Comment by The-Pr0grammer** [comment]
just ran into this. running react native on real device

When an invalid uri is given to webview I'm getting a warning instead of an error and my onError callback is expectedly not being fired.

**Comment by avasthi3july** [comment]
Hi Team, I need solution for the same as i have many use case of this scenario in my app. Kindly suggest asap.

WARN  Can't open url:

**Comment by jaynguyen89** [comment]
I ran into the same issue with WebView lately. Indeed, `onError` and `renderError` are not fired, **but `onHttpError` does fire**, you can use it to display your error messages.

**Comment by aleksips** [comment]
This is still an issue. Neither `onError` or `onHttpError` triggers on 404 or when the url is not resolved at all.

**Comment by nullpointer010** [comment]
Still no solution

**Comment by OrenMag** [comment]
Experiencing this as well. And as a related issue to this, I can't find a way to reload the webview once a wrond uri is given (webviewRef.reload() and changing source doesn't trigger reload of the webview)

**Comment by fukemy** [comment]
onerror never called on Android
