### ISSUE TITLE
Invariant Violation: requireNativeComponent: "RNCWebView" was not found in the UIManager.

### ISSUE THREAD

**Issue by james1888** [react-native-community/react-native-webview#534]
**Bug description:**

It's fine on iOS but on Android it's not working. I've check all the files from this [article](https://engineering.brigad.co/demystifying-react-native-modules-linking-964399ec731b). It's correct.

MainApplication.java
![image](https://user-images.githubusercontent.com/8617506/56780017-d2128680-6807-11e9-8c86-d74d96ecfeba.png)

build.gradle
![image](https://user-images.githubusercontent.com/8617506/56780070-13a33180-6808-11e9-8578-14acbac4c29d.png)

settings.gradle
![image](https://user-images.githubusercontent.com/8617506/56780046-ef475500-6807-11e9-895b-a695ca584b12.png)

**To Reproduce:**

**Expected behavior:**

**Screenshots/Videos:**

**Environment:**
 - OS: macOS
 - OS version: 10.14.4
 - react-native version: 0.58.6
 - react-native-webview version: ^5.7.1

**Comment by mxsxs2** [comment]
Did you run ```react-native link```?

**Comment by james1888** [comment]
Yes, I did.   
  
  
  

  
  

  
  
>

**Comment by aristofanio** [comment]
I am with the same problem!
react-native-cli: 2.0.1
react-native: 0.59.5
react-native-webview: 5.7.1

**Comment by james1888** [comment]
I found the problem in build.gradle there is a duplication implementation

![image](https://user-images.githubusercontent.com/8617506/56872722-6d993680-6a56-11e9-9181-1b10b10b85d4.png)

**Comment by sangyakhare** [comment]
I don't have any duplicate implementation in build.gradle, still I see the same error.

<img width="359" alt="Screen Shot 2019-05-02 at 8 25 32 AM" src="https://user-images.githubusercontent.com/49403660/57075154-fc56bf00-6cb3-11e9-9012-ff777d430727.png">

**Comment by sangyakhare** [comment]
I don't have any duplicate implementation in build.gradle, still I see the same error.
<img width="359" alt="Screen Shot 2019-05-02 at 8 25 32 AM" src="https://user-images.githubusercontent.com/49403660/57075406-bc440c00-6cb4-11e9-8721-ccf4ec7ed77e.png">

**Comment by V3RT1AG0** [comment]
Same here. I am running into the same issue on RN version 0.59.4.

**Comment by fariya12** [comment]
any solution found ??

**Comment by klawingco** [comment]
Dunno man, but I made it work with the following
1. react-native link 
2. react-native start --reset-cache
3. uninstall the app from the device
4. react-native run-android

The process fails and I get the error if I skip the step 3 :( but anyway it works if you uninstall

**Comment by sangyakhare** [comment]
I found out that when we do linking, packages are automatically added to getPackages() method in MainApplication.java. When I looked closely into this class there is one more getPackages() method in it. I tried putting the Webview package in that method as well and it worked. I had similar problem with Keychain and localization packages and copying those in this method also worked.
Here is my MainApplication.java look like.

public class MainApplication extends NavigationApplication {

  @Override
  protected ReactGateway createReactGateway() {
    ReactNativeHost host = new NavigationReactNativeHost(this, isDebug(), createAdditionalReactPackages()) {
      @Override
      protected String getJSMainModuleName() {
        return "index";
      }
    };
    return new ReactGateway(this, isDebug(), host);
  }
  @Override
  public boolean isDebug() {
    return BuildConfig.DEBUG;
  }

**// I added those packages manually here  
protected List<ReactPackage> getPackages() {
    // Add additional packages you require here
    // No need to add RnnPackage and MainReactPackage
    return Arrays.<ReactPackage>asList(
            // eg. new VectorIconsPackage()
            new ReactNativeLocalizationPackage(),
            new KeychainPackage(),
            new RNCWebViewPackage()
    );
  }**
  @Override
  public List<ReactPackage> createAdditionalReactPackages() {
    return getPackages();
  }

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }
    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
           _**//packages are automatically added here when we link them.**_
             new MainReactPackage(),
            new KeychainPackage(),
            new RNCWebViewPackage(),
            new ReactNativeLocalizationPackage(),
            new AsyncStoragePackage()//,
//            new SplashScreenReactPackage()
      );
    }

    @Override
    protected String getJSMainModuleName() {
      return "index";
    }
  };

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  @Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
  }
}

**Comment by rexleonem** [comment]
> Dunno man, but I made it work with the following
> 
> 1. react-native link
> 2. react-native start --reset-cache
> 3. uninstall the app from the device
> 4. react-native run-android
> 
> The process fails and I get the error if I skip the step 3 :( but anyway it works if you uninstall

It fixed my own problem, thanks for sharing!

**Comment by clamiax** [comment]
> I am with the same problem!
> react-native-cli: 2.0.1
> react-native: 0.59.5
> react-native-webview: 5.7.1.
> 
> I did `react-native link`.
> 
> [UPDATE]
> In my case, I did `react-native run-android & react-native run-ios` and worked!!!

This also worked for me. I assume something has been rebuilt with this command which was not done via `react-native start`. Thanks!

**Comment by samiede** [comment]
I still have this problem with React Native 60.5

**Comment by Sanan4li** [comment]
> I still have this problem with React Native 60.5

After hours of searching I fixed it by adding kotlinVersion=1.3.11 in gradle.properties which is located inside android folder.
But now, the webview does not load the website just shows a black page.

**Comment by Ukatane** [comment]
@klawingco thanks it worked for me

**Comment by paintmr** [comment]
Thank you@klawingco. It worked for me as well.
I use windows for Android
"react-native": "0.60.5",
"react-native-webview": "^7.5.1",

From react-native 0.60 autolinking will take care of the link step, so I just:
1) uninstall the app from the device
2) react-native run-android

Just for your guys' reference

**Comment by yaronlevi** [comment]
@Sanan4li Changing to 1.3.11 worked! 🙏
How did you even come up with that?

**Comment by CarlosMayoralMX** [comment]
What works for me was

**react-native link react-native-webview**
react-native start --reset-cache
uninstall the app from the device
react-native run-android

> Dunno man, but I made it work with the following
> 
> 1. react-native link
> 2. react-native start --reset-cache
> 3. uninstall the app from the device
> 4. react-native run-android
> 
> The process fails and I get the error if I skip the step 3 :( but anyway it works if you uninstall

**Comment by edem** [comment]
Every ways didn't work for me, so I resolved this issue with different approach.

Due to iTune reject UIWebView, I upgrade react-native-webview from 5.12.0 to 10.7.0.
The new version works on iOS, but in Android --> Invariant Violation: requireNativeComponent: "RNCWebView" was not found in the UIManager.

fortunately, I have two Apps as the same time. One base on RN-0.59.10, another base on RN-0.63.2
This error only occurred on 0.59, but everything was fine on 0.63.
I downgraded react-native-webview from 10.7.0 to 5.12.0 for RN-0.59.10, it was fixed.

So, if reinstall & relink didn't help you, try to downgrade it for your RN-0.59.

**Comment by DonavanMartin** [comment]
I past few hours to solve this issue... 

It's look that version react-native-webview@10.7.0 is compatible with RN 0.63 but not react-native-webview@10.8.0.

Thank you @edem

**Comment by diegovfeder** [comment]
I had a similar issue and fixed it by going to the project's android folder and running:

$ ./gradlew

**Comment by pk936** [comment]
Uninstall and then install the app from device worked for me

Credit @klawingco .

**Comment by geka412315** [comment]
update xcode
