### ISSUE TITLE
window.addEventListener('message') can not be triggered after using react-native-webview

### ISSUE THREAD

**Issue by httol** [react-native-community/react-native-webview#535]
"react": "16.8.3",
"react-native": "0.59.5"

after upgrade rn to 0.59.5, I use the react-native-webview which the office recommends.
the code below nested in a React project.
The issue is when React debug mode, the message event can be triggered, but when release mode nested in the react-native project, can not trigger the event.

please help me, thank you

```
componentDidMount() {
    window.addEventListener('message', e => {
        const { payload } = JSON.parse(e.data);
        this.renderChart(payload);
    });
}
```

**Comment by Ak10990** [comment]
What is the fix done here for Android ? @httol
