### ISSUE TITLE
Prevent deep linking to third party applications

### ISSUE THREAD

**Issue by kpaulus1997** [react-native-community/react-native-webview#541]
Is it possible to disable deep linking to other app, for instance if I have amazon installed on my device and open an amazon url with the web view it's pushing me to the amazon app, however I would like to open the amazon website inside the web view ?
Thanks for the help

**Comment by gaykov** [comment]
I was having a similar problem when WebView was trying to open `plaidlink://*` and I wasn't able to control it. And I noticed that if you add the 3rd party protocol to the `originWhitelist`, you'd be able to control it inside the `onShouldStartLoadWithRequest` function:

Something like:

```js
<WebView
  source={{ uri: generateLinkInitializationURL() }}
  onShouldStartLoadWithRequest={request => {
    if (request.url.startsWith('plaidlink')) {
      ...
      return false;
    }

    return true;
  }}
  originWhitelist={['https://*', 'plaidlink://*']}
/>
```

**Comment by dcalhoun** [comment]
The workaround provided by @gaykov worked for me. I used it to disable `mailto:` links found in a web view.

**Comment by Yahyaali1** [comment]
@dcalhoun Is there a workaround that does not disables the links rather makes sure that they are opened within the app webview ? (As asked in the original question that trying to make sure amazon.com opens within the webview not in the amazon app)

**Comment by dcalhoun** [comment]
@Yahyaali1 I'm not sure. To my knowledge, controlling whether a link opens the web browser or a different dedicated app is solely controlled by the user through long-pressing the link and selecting the desired app.

**Comment by mandersondesign** [comment]
@Yahyaali1 did you ever get this to work? I’m trying to default to the Spotify web player but it always opens the app.

**Comment by Yahyaali1** [comment]
@mandersondesign does the usecase involves user clicking a link from within webview page ? If so, I was not able to do much about that usecase.

**Comment by invyctus92** [comment]
has anyone solved it? i would like to avoid opening Facebook and instagram when visiting the relevant sites.

**Comment by Yahyaali1** [comment]
@invyctus92 Here is my finding on the use case. 
You can try to intercept the page load using ```onShouldStartLoadWithRequest``` by returning false to match specific url pattern and re render the webview with the new url. This technique is based on similar idea discussed in this [article]( https://www.bigbinary.com/blog/passing-request-headers-on-each-webview-request-in-react-native)

**Comment by adbalits** [comment]
Having this issue too

**Comment by JerakRus** [comment]
Hello everyone, I found a workaround for myself that worked for me. I had to make some native changes to the library and commit them using patch-package. In the file `node_modules / react-native-webview / apple / RNCWebView.m` it was like this:
```
  if (_onShouldStartLoadWithRequest) {
    NSMutableDictionary<NSString *, id> *event = [self baseEvent];
    [event addEntriesFromDictionary: @{
      @"url": (request.URL).absoluteString,
      @"mainDocumentURL": (request.mainDocumentURL).absoluteString,
      @"navigationType": navigationTypes[@(navigationType)],
      @"isTopFrame": @(isTopFrame)
    }];
    if (![self.delegate webView:self
      shouldStartLoadForRequest:event
                   withCallback:_onShouldStartLoadWithRequest]) {
      decisionHandler(WKNavigationActionPolicyCancel);
      return;
    }
  }
```
it became like this:
```
  if (_onShouldStartLoadWithRequest) {
    NSMutableDictionary<NSString *, id> *event = [self baseEvent];
    [event addEntriesFromDictionary: @{
      @"url": (request.URL).absoluteString,
      @"mainDocumentURL": (request.mainDocumentURL).absoluteString,
      @"navigationType": navigationTypes[@(navigationType)],
      @"isTopFrame": @(isTopFrame)
    }];
    if ([request.URL.host isEqualToString:@"instagram.com"]) {
      decisionHandler(WKNavigationActionPolicyAllow);
      return;
    }
    if (![self.delegate webView:self
      shouldStartLoadForRequest:event
                   withCallback:_onShouldStartLoadWithRequest]) {
      decisionHandler(WKNavigationActionPolicyCancel);
      return;
    }
  }
```
In my case, the changes are only needed for 'instagram', and they do not work perfectly, because instagram makes a tricky interception - and the direct link to the profile still opens in the application, but the rest of the pages work fine in the  `webview`. As you can see, you can write your own condition exactly to your needs, and possibly change the default one so that all requests are processed like this, but I don’t know what it will lead to. Maybe it can help someone.

**Comment by jeffBoom** [comment]
I was able to get this to work by looking at the event.navigationType. 

If a user 'clicked' on the link, that's what was causing it to open in the third party app. If they simply entered the url, it would open in the webview. So here's how i did it (setUri is just a state hook to update the uri and disabledList is just an array of domains i want to stop from opening externally).

`onShouldStartLoadWithRequest={(e: ShouldStartLoadRequest) => {
                        if (bcHtmlParser.getIsOnDisableList(e.url) && e.navigationType === 'click') {
                            setUri(e.url);
                            return false;
                        }
                        return true;
                    }}`

**Comment by obender** [comment]
We Still have the same issue...
https://github.com/react-native-webview/react-native-webview/issues/3435

**Comment by obender** [comment]
> onShouldStartLoadWithRequest={(e: ShouldStartLoadRequest) => { if (bcHtmlParser.getIsOnDisableList(e.url) && e.navigationType === 'click') { setUri(e.url); return false; } return true; }}

This actually worked !!!! 

Here is formatted example for other people 

`
const disabledList = ['example.com', 'unwanteddomain.com']; // Array of domains to block

const [uri, setUri] = useState(''); // State hook to update the URI

const onShouldStartLoadWithRequest = (event: ShouldStartLoadRequest) => {
  // Parse the URL from the event
  const urlHost = new URL(event.url).hostname;

  // Check if the URL host is in the disabled list and the navigation was triggered by a click
  if (disabledList.includes(urlHost) && event.navigationType === 'click') {
    setUri(event.url); // Update the state to the new URI
    return false; // Prevent loading the URL to block opening it externally
  }
  
  return true; // Allow loading URLs not in the disabled list or not clicked
};
`

**Comment by obender** [comment]
@jeffBoom any Idea why this fix worked? 
It's some http header that causes to open the app, because we still have some corner case on iOS that the app is opened even with your fix.....
The websites do 2 redirects and then the app opens, I tried to do the same trick , but then the webview not loading at all

**Comment by arieloO** [comment]
> > onShouldStartLoadWithRequest={(e: ShouldStartLoadRequest) => { if (bcHtmlParser.getIsOnDisableList(e.url) && e.navigationType === 'click') { setUri(e.url); return false; } return true; }}
> 
> This actually worked !!!!
> 
> Here is formatted example for other people
> 
> ```
> const disabledList = ['example.com', 'unwanteddomain.com']; // Array of domains to block
> 
> const [uri, setUri] = useState(''); // State hook to update the URI
> 
> const onShouldStartLoadWithRequest = (event: ShouldStartLoadRequest) => {
>   // Parse the URL from the event
>   const urlHost = new URL(event.url).hostname;
> 
>   // Check if the URL host is in the disabled list and the navigation was triggered by a click
>   if (disabledList.includes(urlHost) && event.navigationType === 'click') {
>     setUri(event.url); // Update the state to the new URI
>     return false; // Prevent loading the URL to block opening it externally
>   }
>   
>   return true; // Allow loading URLs not in the disabled list or not clicked
> };
> ```

This workaround only works for iOS, as android does not expose `navigationType`.
