### ISSUE TITLE
No audio on iphone but have on the ios simulator

### ISSUE THREAD

**Issue by LazzySloth** [react-native-community/react-native-webview#542]
I'm using Consruct 2 to make a html5 game and uses react native webview to run the game on iOS. The game's audio works perfectly on the iOS simulator but it's not working when running on an iphone. It was working fine a few weeks ago but suddenly fail after I update my iphone to iOS12.2.

**Comment by afilp** [comment]
Can you please reopen this? I have the same problem, no audio and sounds in HTML5 in iOS (while it is OK in Android). 

Thanks!
