### ISSUE TITLE
iOS WKWebView local file trust issues

### ISSUE THREAD

**Issue by xploSEoF** [react-native-community/react-native-webview#545]
**Bug description:**
There is no way to embed WKWebView on iOS devices with a local source from the document directory and allow for references to pull through.

Specifically, the issue can be seen in: https://github.com/react-native-community/react-native-webview/blob/master/ios/RNCWKWebView.m#L375
Here, the baseURL hasn't been authorised for access, so each request to a supporting file results in lots of "Operation not permitted" errors. It's a shame, because this works for Android, but iOS don't allow this method to work at all.

However, an alternative method would be to provide a file URL for the 'url', but this has an issue with this particular line: https://github.com/react-native-community/react-native-webview/blob/master/ios/RNCWKWebView.m#L396
The problem with this line is it specifies the file as the permission folder. Changing this to take a passed parameter if it exists fixes the problem.

**To Reproduce:**
Have your code download an html file into the documents folder, and the supporting css/js/images and what not. Then try to load the downloaded html file and the downloaded assets.

**Expected behavior:**
I'd expect it to load the assets

**Environment:**
 - OS: OSX / Windows10
 - OS version: 10.14.4 / 1803
 - react-native version: 0.57.8
 - react-native-webview version: 5.6.2

**Comment by alancwoo** [comment]
Strangely this seems to work in the simulator but not on hardware.

**Comment by xploSEoF** [comment]
> 
> 
> Strangely this seems to work in the simulator but not on hardware.

Based on all the searching of the web I did, there seems to be a common simulator issue when it comes to representing the permissions of a WKWebView.

Developing with a device has its advantages, even if it is a bit costly.

**Comment by xploSEoF** [comment]
Still searching for solutions...

A small lie, I have one I might submit, but it's not the nicest and would be inconsistent between ios and android.

**Comment by eventengineering** [comment]
Ah, #771 might have fixed it.
