### ISSUE TITLE
[Android] renderLoading doesn't work with redirects

### ISSUE THREAD

**Issue by tyleralves** [react-native-community/react-native-webview#547]
**Issue:**
When a redirect occurs, the [onLoadingFinish](https://github.com/react-native-community/react-native-webview/blob/319a86e2361ac0161cbe2897a907d43b085029fc/src/WebView.android.tsx#L173) method is triggered.

**Bug description:**
On Android, the `renderLoading` property stops rendering the loading component as soon as the redirect occurs instead of waiting until the final page loads.

**To Reproduce:**
1. Render the WebView with a source uri that redirects to another uri

ie: 

- "https://facebook.com" redirects to "https://m.facebook.com"
- "https://github.com/business" redirects to "https://github.com/enterprise"
- Sites using Oauth2 redirect uris

**Expected behavior:**
The `renderLoading` component should continue to be displayed until the final page has finished loading.

**Screenshots:**
<img width="1056" alt="Screen Shot 2019-04-30 at 5 31 39 PM" src="https://user-images.githubusercontent.com/13406078/57001514-e7701380-6b6d-11e9-8856-0b17c7cdffb1.png">

**Environment:**
 - OS: Android Pixel 2 Emulator
 - OS version: API 28, Android 9.0 (Google APIs), x86
 - react-native version: 0.58.6
 - react-native-webview version: 5.6.2

**Comment by wellcode** [comment]
Same issues
