### ISSUE TITLE
[Android] Local html file don't work on debug 

### ISSUE THREAD

**Issue by SnaiNeR** [react-native-community/react-native-webview#549]
Works on core RN's webview, but this package make this error:

> TypeError: TypeError: TypeError: source is not an Object. (evaluating ''method' in source')

with local file in source prop
`source={require('../index.html')}`

But works correctly with url in source prop
`source={{uri: 'http://mysite.com' }}`

Android Debug

**Comment by SnaiNeR** [comment]
#428 same thing

**Comment by imran1992** [comment]
Yes Same here.
I need to render local HTML file

**Comment by MaxToyberman** [comment]
@imran1992  so there is no possibility to load it locally ?

**Comment by sarathsaleem** [comment]
Is there any workaround solution for Android dev mode ?

**Comment by luckcoding** [comment]
I solved with this code:
```
source={platform.isIOS ? require('x.html') : { uri: 'file:///android_asset/x.html' }}
```

**Comment by Ycdm-xd** [comment]
@luckcoding I tried the same but it's showing an `ERR_FILE_NOT_FOUND`.
I did place my html file under `android/app/src/main/assets/` and I had the following done too:
`allowFileAccess={true}`
`domStorageEnabled={true}`
`javaScriptEnabled={true}`
Currently, I'm forced to keep loading my htmls statically, copying and pasting after every change (which is really painful)

**Comment by luckcoding** [comment]
@Ycdm-xd Maybe is the diffrent environment?
`package.json`
```
"react": "16.8.6",
"react-native": "0.60.4",
"react-native-webview": "^7.0.3"
```
use in
```
<WebView
  scrollEnabled={false}
  injectedJavaScript={injectedJavaScript}
  style={{ height }}
  scalesPageToFit={false}
  originWhitelist={['*']}
  source={platform.isIOS ? require('./antv.html') : {
    uri: 'file:///android_asset/antv.html'
  }}
/>
```
AndroidManifest.xml
```
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" />
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.DOWNLOAD_WITHOUT_NOTIFICATION" />
<uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES" />
```

**Comment by Ycdm-xd** [comment]
@luckcoding Okay actually worked! I think the AndroidManifest.xml permissions did the trick. Thanks so much!

**Comment by FarKotw** [comment]
>  html: this.state.content

Thank you. Been browsing internet to make this work. Had been either getting error cannot convert double to string or File not found errors.
