### ISSUE TITLE
WebView redirects into iFrame on Android

### ISSUE THREAD

**Issue by burak-koksal-jotform** [react-native-community/react-native-webview#560]
**Bug description:**

WebView Component redirects into iFrame(s) when serving from static resources on Android. 
Used props are: 
```
{
  source: {uri: 'file://<path/to/index.html>'}
  originWhitelist: ['*'],
  allowFileAccess: true
}
```
However it was working correctly on v.2.10.0. And [here is a fork](https://github.com/burak-koksal-jotform/react-native-webview/commits/2.10.0-jf) of working version that we're stuck to use in our original app in order to get the right behavior. 

**To Reproduce:**
[Here is the repo](https://github.com/burak-koksal-jotform/rncWebView) of an example app to reproduce error.
You can [download](https://www.jotform.com/uploads/burak/91174000715951/4330339118506455470/archive.zip) and examine the source code that i'm using in the example app

**Expected behavior:**
WebView shouldn't redirect into Iframe src on Android.  The view in the iOS Simulator is expected.

**Screenshots/Videos:**
Screenshots produced at latest version of react-native-webView (5.8.1)
Android: (incorrect) 
![and_5 8 1](https://user-images.githubusercontent.com/33414962/57295255-c4e07c00-70d2-11e9-9e0e-1cf9c02ea5a3.png)
iOS: (correct)
![iPhone_5 8 1](https://user-images.githubusercontent.com/33414962/57295299-da55a600-70d2-11e9-951c-cc1a78f488cf.png)

**Environment:**
 - OS: macOS Mojave
 - OS version: 10.14.4
 - react-native version: 0.59.5
 - react-native-webview version: > 2.10.0

**Comment by sbayd** [comment]
Still reproducible with,

- react-native: 59.8
- react-native-webview: 5.8.2

**Comment by pimentahodl** [comment]
We are also having the same problem

**Comment by knap1930** [comment]
same issue here.

**Comment by nicolasdet** [comment]
i have the same problem..  ?  have you found a solution ?

**Comment by DemonWu** [comment]
i have the same problem.. ? have you found a solution ?

**Comment by pluspol** [comment]
We might have found a fix for this. :) It seems that the iOS version contains a check preventing unwanted redirects of the main frame. The Android version doesn't check this.

The following change to `RNCWebViewManager.java` adding the main frame check seems to fix the issue:

```java
    @TargetApi(Build.VERSION_CODES.N)
    @Override
    public boolean shouldOverrideUrlLoading(WebView view, WebResourceRequest request) {
      if (!request.isForMainFrame()) {
        return false;
      }

      final String url = request.getUrl().toString();
      return this.shouldOverrideUrlLoading(view, url);
    }
```

**Comment by pluspol** [comment]
> The following change to `RNCWebViewManager.java` adding the main frame check seems to fix the issue.

Unfortunately this only applies to Android >= Nougat. Versions below use the method `public boolean shouldOverrideUrlLoading(WebView view, String url)` which doesn't include the request information. Maybe we can the the necessary information from somewhere else?

**Comment by jayfunk** [comment]
Experiencing the same issue. Using webview version 6.11.0.

**Comment by drager** [comment]
This is still an issue for an built APK using react-native-webview `10.9.2`. Please reopen again...

**Comment by tuyenbug** [comment]
> We might have found a fix for this. :) It seems that the iOS version contains a check preventing unwanted redirects of the main frame. The Android version doesn't check this.
> 
> The following change to `RNCWebViewManager.java` adding the main frame check seems to fix the issue:
> 
> ```java
>     @TargetApi(Build.VERSION_CODES.N)
>     @Override
>     public boolean shouldOverrideUrlLoading(WebView view, WebResourceRequest request) {
>       if (!request.isForMainFrame()) {
>         return false;
>       }
> 
>       final String url = request.getUrl().toString();
>       return this.shouldOverrideUrlLoading(view, url);
>     }
> ```

yes, it's working
