### ISSUE TITLE
Android: Vanilla android error page shown, despite setting renderError()

### ISSUE THREAD

**Issue by cjpete** [react-native-community/react-native-webview#563]
**Bug description:**

When using WebView with Android, there is a basic Android error page shown, alongside the content returned by renderError.

```
class WebView extends React.Component<WebViewProps> {
  webViewRef = null;
  reload = () => {
    if (this.webViewRef) {
      this.webViewRef.reload();
    }
  };
  render() {
    const { source } = this.props;
    return (
      <RNWebView
        ref={webView => (this.webViewRef = webView)}
        source={{ uri: 'blablabla_not_a_real_domain' }}
        dataDetectorTypes="none"
        useWebKit
        renderLoading={() => (
          <CenteredBlock>
            <ActivityIndicator />
          </CenteredBlock>
        )}
        renderError={(error, code, description) => {
          let errorMessage;
          if (Platform.OS === 'ios') {
            errorMessage = description;
          } else {
            errorMessage = 'Something went wrong whilst loading this content.';
          }
          return (
            <CenteredBlock>
              <CenteredRow>
                <WarningIcon width={32} height={32} />
              </CenteredRow>
              <Body centered>
                {errorMessage}
              </Body>
              <CenteredRow>
                <TextLink title="Retry" onPress={this.reload} />
              </CenteredRow>
            </CenteredBlock>
          );
        }}
        startInLoadingState
      />
    );
  }
}
```

**To Reproduce:**

**Expected behavior:**

Render only the content returned by the renderError prop.

**Screenshots/Videos:**

![image](https://user-images.githubusercontent.com/13134961/57360131-4e468b80-7171-11e9-841d-c08df6ab33c1.png)

**Environment:**
 - OS: MacOS / Android
 - OS version: Mojave / Nexus_5X_API_28_x86
 - react-native version: `0.58.6`
 - react-native-webview version: `5.8.1`

**Comment by Taym95** [comment]
Do you think it should return `errorMessage` without the vanilla android error page??

**Comment by cjpete** [comment]
> Do you think it should return `errorMessage` without the vanilla android error page??

I don't want this to be in the UI:

![image](https://user-images.githubusercontent.com/13134961/57361289-0a08ba80-7174-11e9-8e31-48c1c2e63157.png)

I would have expected that suppling a renderError prop would be a way to totally override any UI shown when there is an error.

**Comment by Taym95** [comment]
Yes got it, @Titozzz what do you think about this?

**Comment by cjpete** [comment]
@Taym95 @Titozzz any thoughts on this issue?

**Comment by woodpav** [comment]
To solve this issue make your `LoadingView` and `ErrorView` have `StyleSheet.absoluteFillObject`.

This is what the code looks like that renders the `WebView` on both iOS and Android:

    <View style={styles.container}>
      {webView}
      {otherView}
    </View>

The reason they do this is because `webView` handles the loading and error callbacks and then the `otherView` is generated based on the results of those callbacks. In other words, you can't just render the `otherView` because then the `webView` could never start loading via the `onLoadingStart` if you had an `LoadingView` rendered.

Another advantage of this approach is that it maintains your web navigation state between errors.

**Comment by cjpete** [comment]
@woodpav that workaround works for me. Thanks.

**Comment by MelanDawn** [comment]
I have got the same problem.
I find out the default method to solve the error loading in source code.
And the style named loadingOrErrorView can solve this problem.

![image](https://user-images.githubusercontent.com/13364603/61202492-3879b780-a71a-11e9-9d23-2d7a9ff5469d.png)

![image](https://user-images.githubusercontent.com/13364603/61202388-f8b2d000-a719-11e9-8a3b-46121c1872df.png)

![image](https://user-images.githubusercontent.com/13364603/61202424-0d8f6380-a71a-11e9-8b98-8f13c3975333.png)

**Comment by nwaughachukwuma** [comment]
@MelanDawn do you want to make a PR for this?

**Comment by TfADrama** [comment]
... is this forgotten?

**Comment by ec-harry** [comment]
... is this forgotten ? +1

**Comment by arcesoj** [comment]
@ec-harry you can custom your render message 

`renderError={() => {
                return (
                  <View
                    style={{
                      width: '100%',
                      height: '100%',
                      backgroundColor: 'white',
                      justifyContent: 'center',
                      alignItems: 'center',
                    }}
                  >
                    <Text style={{ color: 'black' }}>{'This is an error message'} </Text>
                  </View>
                );
              }}`

**Comment by puckey** [comment]
@arcesoj even if you add this, you still get a flash of what @cjpete is showing in their screenshot

**Comment by dorw123** [comment]
Hello, 

Any resolution on this issue ?

**Comment by dorw123** [comment]
I managed to work around something. Basically I introduced a white View with delayed hide so I can bypass that ugly native screen showing between transitions. 

Maybe someone can optimise this and translate it into a PR. 

```
      ....
      _this.state = {
            viewState: _this.props.startInLoadingState ? 'LOADING' : 'IDLE',
            lastErrorEvent: null,
            intermediateView: true
        };
       ....
        _this.reload = function () {
            _this.setState({
                viewState: 'LOADING',
                intermediateView: true
            });
            UIManager.dispatchViewManagerCommand(_this.getWebViewHandle(), _this.getCommands().reload, undefined);
        };
       ....
        _this.onLoadingStart = function (event) {
            var onLoadStart = _this.props.onLoadStart;
            var url = event.nativeEvent.url;
            _this.startUrl = url;
            if (onLoadStart) {
                onLoadStart(event);
            }
            _this.setState({
                intermediateView: true
            })
            _this.updateNavigationState(event);
        };
        _this.onLoadingError = function (event) {
            event.persist(); // persist this event because we need to store it
            var _a = _this.props, onError = _a.onError, onLoadEnd = _a.onLoadEnd;
            if (onError) {
                onError(event);
            }
            if (onLoadEnd) {
                onLoadEnd(event);
            }
            console.warn('Encountered an error loading page', event.nativeEvent);
            _this.setState({
                lastErrorEvent: event.nativeEvent,
                viewState: 'ERROR',
                intermediateView: true
            });
        };
       ....
        _this.onLoadingFinish = function (event) {
            var _a = _this.props, onLoad = _a.onLoad, onLoadEnd = _a.onLoadEnd;
            var url = event.nativeEvent.url;
            if (onLoad) {
                onLoad(event);
            }
            if (onLoadEnd) {
                onLoadEnd(event);
            }
            if (url === _this.startUrl) {
                _this.setState({
                    viewState: 'IDLE',
                });
            }
            var intermediateViewTimeout = setTimeout(() => {
                _this.setState({
                    intermediateView: false
                }, clearTimeout(intermediateViewTimeout))
            }, 250);
            _this.updateNavigationState(event);
        };

WebView.prototype.render = function () {
        var _a = this.props, onMessage = _a.onMessage, onShouldStartLoadWithRequestProp = _a.onShouldStartLoadWithRequest, originWhitelist = _a.originWhitelist, renderError = _a.renderError, renderLoading = _a.renderLoading, source = _a.source, style = _a.style, containerStyle = _a.containerStyle, _b = _a.nativeConfig, nativeConfig = _b === void 0 ? {} : _b, otherProps = __rest(_a, ["onMessage", "onShouldStartLoadWithRequest", "originWhitelist", "renderError", "renderLoading", "source", "style", "containerStyle", "nativeConfig"]);
        var otherView = null;
        var intermediateView = (
            <View style={
                {
                    position: 'absolute',
                    flex: 1,
                    justifyContent: 'center',
                    alignItems: 'center',
                    height: '100%',
                    width: '100%',
                    backgroundColor: 'white'
                }
            }></View>
        );
        if (this.state.viewState === 'LOADING') {
            otherView = (renderLoading || defaultRenderLoading)();
        }
        else if (this.state.viewState === 'ERROR') {
            var errorEvent = this.state.lastErrorEvent;
            invariant(errorEvent != null, 'lastErrorEvent expected to be non-null');
            otherView = (renderError || defaultRenderError)(errorEvent.domain, errorEvent.code, errorEvent.description);
        }
        else if (this.state.viewState !== 'IDLE') {
            console.error("RNCWebView invalid state encountered: " + this.state.viewState);
        }
        var webViewStyles = [styles.container, styles.webView, style];
        var webViewContainerStyle = [styles.container, containerStyle];
        if (typeof source !== "number" && source && 'method' in source) {
            if (source.method === 'POST' && source.headers) {
                console.warn('WebView: `source.headers` is not supported when using POST.');
            }
            else if (source.method === 'GET' && source.body) {
                console.warn('WebView: `source.body` is not supported when using GET.');
            }
        }
        var NativeWebView = nativeConfig.component || RNCWebView;
        var onShouldStartLoadWithRequest = createOnShouldStartLoadWithRequest(this.onShouldStartLoadWithRequestCallback, 
        // casting cause it's in the default props
        originWhitelist, onShouldStartLoadWithRequestProp);
        var webView = (<NativeWebView key="webViewKey" {...otherProps} messagingEnabled={typeof onMessage === 'function'} onLoadingError={this.onLoadingError} onLoadingFinish={this.onLoadingFinish} onLoadingProgress={this.onLoadingProgress} onLoadingStart={this.onLoadingStart} onHttpError={this.onHttpError} onMessage={this.onMessage} onShouldStartLoadWithRequest={onShouldStartLoadWithRequest} ref={this.webViewRef} 
        // TODO: find a better way to type this.
        source={resolveAssetSource(source)} style={webViewStyles} {...nativeConfig.props}/>);
        return (<View style={webViewContainerStyle}>
        {webView}
        {this.state.intermediateView ? intermediateView : null}
        {otherView}
      </View>);
    };
```

**Comment by PrijalBista** [comment]
#### WorkAround For Now:

This issue still persists and Ive spent 1-2 days trying to find a decent solution. As mentioned above the only way to solve this for now (work around solution) is by sort of overlaying a loader during that short time period when android's default error page is shown. The workaround that i have figured out is based of all the previous comments above. I am leaving it here in case others come looking for a good enough workaround to this:
Create a loader (with absoluteFill because we need to overlap webview with this loader):
``` js
//loader.js
import * as React from 'react';
import { View, StyleSheet, ActivityIndicator } from 'react-native';

export default function Loader() {
  return (
    <View style={[StyleSheet.absoluteFill, styles.container]}>
      <ActivityIndicator size="large" color="#8ec641" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
});
```
Create a error page (also with absoluteFil as mentioned by @woodpav on previous comment in this thread [here](https://github.com/react-native-webview/react-native-webview/issues/563#issuecomment-502410822) ). Here's a simple error page:
```js
//error.js
import * as React from 'react';
import { Text, View, StyleSheet, Image, Button } from 'react-native';

export default function NoInternet({retryHandler}) {
  return (
    <View style={[StyleSheet.absoluteFill, styles.container]}>
      <Text style={styles.paragraph}>
        Ops! Something went wrong while loading content.
      </Text>
      <Button title="Retry" onPress = {() => {retryHandler()}} />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  paragraph: {
    margin: 24,
    fontSize: 16,
    color: 'red',
    opacity: 0.5,
    textAlign: 'center',
  }
});
```
Now the actual trick on hiding the screen very similar to @dorw123 in previous comment in this thread [here](https://github.com/react-native-webview/react-native-webview/issues/563#issuecomment-645322497)
We will use webview's onLoadStart to show loader, and onLoadEnd to hide loader but the idea is use setTimeout to hide the loader after some amount of time. i.e For this we use a `_loading` state where we add our webview and use it to show hide loader. Here's how i did it:
```js
// App.js

import * as React from 'react';
import { View, Platform } from 'react-native';
import { WebView } from 'react-native-webview';
//
import Error from './components/Error';
import Loader from './components/Loader';

export default class App extends React.Component {
  constructor() {
    super();
  }

  state = {
    _loading: false,
  }

  _retry() {
    if(this.webView.ref) {
      this.webView.ref.reload();
    }
  }

  render() {
      let {  _loading } = this.state;
      return (
        <View style={{ flex:1 }}>
          <WebView
              source={{ uri: 'https://github.com' }}
 
             style={{ marginTop: 0 }}

              // set _loading state to true when loading starts
              onLoadStart = { () => {this.setState({_loading:true})} }

              onLoadEnd={(syntheticEvent) => {
                  // update component to be aware of loading status
                  const { nativeEvent } = syntheticEvent;
                  this.isLoading = nativeEvent.loading;
                  
                  // since this issue arise on android only. delay only on android platform
                  if(Platform.OS === 'android') {
                    // delay loader to hide default android webpage not available screen
                    setTimeout(() => {
                      this.setState({_loading:false})
                    }, 150);
                  } else {
                    this.setState({_loading:false})
                  }
              }}

              renderError={
                (errorName) => <Error retryHandler = {this._retry.bind(this)}/>
              }

              ref={(webView) => { this.webView.ref = webView; }}
              onNavigationStateChange={
                (navState) => { this.webView.canGoBack = navState.canGoBack;}
              }
            />
          {_loading && <Loader/> }
        </View>
      );
  }
}

``` 
Feel free to copy and test it out for yourselves. This workaround works for now and u can change the `150` on setTimeout() to any preferable value if u like. If there's any issue regarding this solution please let me know. :smiley:

**Comment by andres9508** [comment]
> #### WorkAround For Now:
> This issue still persists and Ive spent 1-2 days trying to find a decent solution. As mentioned above the only way to solve this for now (work around solution) is by sort of overlaying a loader during that short time period when android's default error page is shown. The workaround that i have figured out is based of all the previous comments above. I am leaving it here in case others come looking for a good enough workaround to this: Create a loader (with absoluteFill because we need to overlap webview with this loader):
> 
> ```js
> //components/loader.js
> import * as React from 'react';
> import { View, StyleSheet, ActivityIndicator } from 'react-native';
> 
> export default function Loader() {
>   return (
>     <View style={[StyleSheet.absoluteFill, styles.container]}>
>       <ActivityIndicator size="large" color="#8ec641" />
>     </View>
>   );
> }
> 
> const styles = StyleSheet.create({
>   container: {
>     flex: 1,
>     backgroundColor: 'white',
>     alignItems: 'center',
>     justifyContent: 'center',
>     padding: 24,
>   },
> });
> ```
> 
> Create a error page (also with absoluteFil as mentioned by @woodpav on previous comment in this thread [here](https://github.com/react-native-webview/react-native-webview/issues/563#issuecomment-502410822) ). Here's a simple error page:
> 
> ```js
> //components/error.js
> import * as React from 'react';
> import { Text, View, StyleSheet, Image, Button } from 'react-native';
> 
> export default function Error({retryHandler}) {
>   return (
>     <View style={[StyleSheet.absoluteFill, styles.container]}>
>       <Text style={styles.paragraph}>
>         Ops! Something went wrong while loading content.
>       </Text>
>       <Button title="Retry" onPress = {() => {retryHandler()}} />
>     </View>
>   );
> }
> 
> const styles = StyleSheet.create({
>   container: {
>     flex: 1,
>     backgroundColor: 'white',
>     alignItems: 'center',
>     justifyContent: 'center',
>     padding: 24,
>   },
>   paragraph: {
>     margin: 24,
>     fontSize: 16,
>     color: 'red',
>     opacity: 0.5,
>     textAlign: 'center',
>   }
> });
> ```
> 
> Now the actual trick on hiding the screen very similar to @dorw123 in previous comment in this thread [here](https://github.com/react-native-webview/react-native-webview/issues/563#issuecomment-645322497) We will use webview's onLoadStart to show loader, and onLoadEnd to hide loader but the idea is use setTimeout to hide the loader after some amount of time. i.e For this we use a `_loading` state where we add our webview and use it to show hide loader. Here's how i did it:
> 
> ```js
> // App.js
> 
> import * as React from 'react';
> import { View, Platform } from 'react-native';
> import { WebView } from 'react-native-webview';
> //
> import Error from './components/Error';
> import Loader from './components/Loader';
> 
> export default class App extends React.Component {
>   constructor() {
>     super();
>   }
> 
>   state = {
>     _loading: false,
>   }
> 
>   webView = {
>     canGoBack: false,
>     ref: null,
>   }
> 
>   _retry() {
>     if(this.webView.ref) {
>       this.webView.ref.reload();
>     }
>   }
> 
>   render() {
>       let {  _loading } = this.state;
>       return (
>         <View style={{ flex:1 }}>
>           <WebView
>               source={{ uri: 'https://github.com' }}
>  
>              style={{ marginTop: 0 }}
> 
>               // set _loading state to true when loading starts
>               onLoadStart = { () => {this.setState({_loading:true})} }
> 
>               onLoadEnd={(syntheticEvent) => {
>                   // update component to be aware of loading status
>                   const { nativeEvent } = syntheticEvent;
>                   this.isLoading = nativeEvent.loading;
>                   
>                   // since this issue arise on android only. delay only on android platform
>                   if(Platform.OS === 'android') {
>                     // delay loader to hide default android webpage not available screen
>                     setTimeout(() => {
>                       this.setState({_loading:false})
>                     }, 150);
>                   } else {
>                     this.setState({_loading:false})
>                   }
>               }}
> 
>               renderError={
>                 (errorName) => <Error retryHandler = {this._retry.bind(this)}/>
>               }
> 
>               ref={(webView) => { this.webView.ref = webView; }}
>             />
>           {_loading && <Loader/> }
>         </View>
>       );
>   }
> }
> ```
> 
> Feel free to copy and test it out for yourselves. This workaround works for now and u can change the `150` on setTimeout() to any preferable value if u like. If there's any issue regarding this solution please let me know. 😃

Es genial, llevaba mucho tiempo buscando la solucion a esto y no la encontraba por ningun lado pero me funciono perfecto.Gracias

**Comment by EminShahbazi** [comment]
... is this forgotten?

**Comment by tschai-yim** [comment]
I had the same issue when using invalid URLs that would trigger navigation changes in `onNavigationStateChange`:
```tsx
onNavigationStateChange={(state) => {
  if (state.url !== RETURN_URL) return;
  view.current?.stopLoading();
  goBack();
}}
```
The error page would flash even with `renderError` defined before the navigation animation finished.
In my use case, I solved it by switching to `onShouldStartLoadWithRequest` and preventing a load attempt entirely:
```tsx
onShouldStartLoadWithRequest={(request) => {
  if (request.url === RETURN_URL) {
    goBack();
    return false;
  }
  return true;
}}
```
