### ISSUE TITLE
React Native webview source target twitter.com . Can't load twitter homepage timeline

### ISSUE THREAD

**Issue by junjun16818** [react-native-community/react-native-webview#564]
It's work!

    <WebView
        source={{ uri: 'https://mobile.twitter.com' }}
    />
Not work!

    <WebView
        source={{ uri: 'https://mobile.twitter.com' }}
        onMessage={(event) => { console.warn(event.nativeEvent.data) }}
    />

![image](https://user-images.githubusercontent.com/955472/57361844-f67b4500-71af-11e9-8fc4-6e016a05cd1d.png)
I can't load the homepage just by adding the onMessage method
what should I do

**Comment by chellongCoder** [comment]
same issue
