### ISSUE TITLE
RNCWKWebView crashes with an NSInvalidArgumentException for didFinishNavigation

### ISSUE THREAD

**Issue by StefanWallin** [react-native-community/react-native-webview#568]
**Bug description:**

RNCKWKWebView crashes our app with an `NSInvalidArgumentException` for `didFinishNavigation` event.

Our app uses Webviews to display HTML adverts and thus do not have control over the code executing inside the Webview.

Here is a stacktrace with some information from sentry:
https://sentry.io/share/issue/1fb0a36375244d7d9cf94f13921427cd/

**To Reproduce:**

Unable to reproduce, we can see in sentry that we have 25k users in a 250k userbase have this problem approximately 40k times across the last 4 months.

**Expected behavior:**

We'd like to expect a documented error or a development warning to fire if something is misconfigured.

**Screenshots/Videos:**

Not applicable

**Environment:**
 - OS: iOS
 - OS version: 10-12.2
 - react-native version: 0.59.6
 - react-native-webview version: 2.13.0 - 5.7.1 (All the time we've been using it)

**Edits:**
1. The entire contents disappeared due to a github guide.
2. Update link

**Comment by Titozzz** [comment]
Can't load the sentry link

**Comment by StefanWallin** [comment]
Sorry for that! Link updated and should work.

**Comment by shukerullah** [comment]
@StefanWallin Hi, did you fix this issue?

**Comment by infapednekar** [comment]
@StefanWallin Were you able to resolve this issue?

**Comment by StefanWallin** [comment]
Unfortuneatley not working on this bug anymore, we've accepted it and I'm no longer on this project.

**Comment by infapednekar** [comment]
Got it. Thanks for the response
