### ISSUE TITLE
injectJavaScript method missing escape character

### ISSUE THREAD

**Issue by lovekobe24** [react-native-community/react-native-webview#569]
when i use injectJavaScript  ，webView inject loadzn function，loadzn function accept json string contains escape character。
`  var testspaiceJson={name: "zhangsan", age: "23", email: "<svg width=\"100%\" height=\"100%\" version=\"1.1\"\n" +
                    "xmlns=\"http://www.w3.org/2000/svg\">"};
           var jsonstr1=JSON.stringify(testspaiceJson);
           this.refs[WEBVIEW_REF].injectJavaScript(`loadzn('`+jsonstr1+`');true;`);`

in the html，i use JSON.parse,but i find failed. alert the parameter，it missing escape character '\'
`function loadzn(diagramString){
        alert(diagramString);
        var d = JSON.parse(diagramString);
}`

alert message is 
<img width="323" alt="屏幕快照 2019-05-13 上午11 33 28" src="https://user-images.githubusercontent.com/19279810/57594530-255c3700-7573-11e9-827d-b058ce9c1905.png">

hope someone can help me

**Comment by Nantris** [comment]
I'm facing the same problem and the source of this is obscure to say the least.
