### ISSUE TITLE
Allow CORS

### ISSUE THREAD

**Issue by mhingston** [react-native-community/react-native-webview#570]
**Bug description:**
Unable to configure CORS.

**To Reproduce:**

_App.js_
```javascript
import React, { Component } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { WebView } from 'react-native-webview';

// ...
class MyWebComponent extends Component {
  render() {
    return (
      <WebView
        source={{uri:"file:///android_asset/index.html"}}
        allowFileAccess={true}
        originWhitelist={["*"]}
      />
    );
  }
}
```

_android/app/src/main/assets/index.html_

```html
<script>
fetch("test.json")
.then(() => alert("got response"))
.catch(error => alert(error.message))
</script>
```

_android/app/src/main/assets/test.json_

```json
{
    "success": true
}
```

**Expected behavior:**

Able to request cross origin resource.

**Environment:**
 - OS: Windows
 - OS version: 10 Pro (1809)
 - react-native version: 0.59
 - react-native-webview version: 5.8.1

**Comment by Taym95** [comment]
Try to add `mode:'cors'` to request.

**Comment by mhingston** [comment]
Thanks @Taym95

I've added the mode to the request as below, still getting `TypeError: Failed to fetch`

_android/app/src/main/assets/index.html_

```html
<script>
fetch("test.json", {mode: "cors"})
.then(() => alert("got response"))
.catch(error => alert(error.message))
</script>
```

**Comment by gorvinsky** [comment]
I'm actually having CORS issue on iOS only. Android is fine.

**Comment by mhingston** [comment]
I had to use a work around to get it working. I wrapped fetch and utilized `window.ReactNativeWebView.postMessage` in the webview to pass a message to RN when the resource is local and then use RNFS to read the local file and encode it as base 64 before passing it back to the webview using a callback via `injectJavaScript`.

**Comment by gorvinsky** [comment]
Some more details for my case. I followed this [guide](https://medium.com/@snehabagri.90/reactnative-webview-with-local-content-c98a09340801) to load a local React web bundled with the React Native app.

It works fine on Android but on iOS, it encountered CORS error when the React web tried to call a cross origin API. The error is as follow:

```
Failed to load resource: Cross-origin redirection to https://somedomain.com/login denied by Cross-Origin Resource Sharing policy: Origin null is not allowed by Access-Control-Allow-Origin.
```

And this is what the code looks like:

```
<WebView
    source={{ uri: indexUrl }}
    onLoadProgress={e => console.log(e.nativeEvent.progress)}
    allowsBackForwardNavigationGestures={true}
    originWhitelist={['*']}
    mixedContentMode="always"
    domStorageEnabled={true}
    allowFileAccess={true}
    allowUniversalAccessFromFileURLs={true}
    onError={syntheticEvent => {
        const { nativeEvent } = syntheticEvent;
        console.warn('WebView error: ', nativeEvent);
    }}
/>
```

**Comment by mhingston** [comment]
Possibly another workaround... [https://github.com/futurepress/react-native-static-server](react-native-static-server).

**Comment by gorvinsky** [comment]
As the error is about Origin header being null, I tried to set the Origin header in the ``source`` property but it didn't work. I even tried setting a custom header and still it didn't show. 

This is the sample code of setting the custom header:
```
<WebView
    source={{
        uri: './index.html',
        headers: { 'myheader': 'testing' },
    }}
/>
```

And it seems that there a few open issues regarding the headers as well:
#4 
#215 
#315 
#460

**Comment by clemensmol** [comment]
still searching for solutions

**Comment by anjaneyulukinnara** [comment]
if anyone comes here, here is the code that worked for me
allowUniversalAccessFromFileURLs= {true} for IOS

**Comment by cristianoccazinsp** [comment]
@anjaneyulukinnara that didn't work for me, I still get CORS issues, sadly. Any other ideas?

**Comment by Aure77** [comment]
Any update/solution ?

**Comment by ThaJay** [comment]
Any steps advised to debug this?

**Comment by arditdaku** [comment]
+1

**Comment by rschoenbichler** [comment]
+1
