### ISSUE TITLE
[Bug] StatusBar disappears on WebView unmount

### ISSUE THREAD

**Issue by kesha-antonov** [react-native-community/react-native-webview#572]
Hey!
After upgrading from ```5.7.2``` to ```5.8.2``` I have this bug.
I think it's introduced in ```5.8.1``` (https://github.com/react-native-community/react-native-webview/commit/c2914a8)

**Bug description:**

When WebView unmounts the StatusBar disappears. Even though I don't play any videos. Just showing images.

**Expected behavior:**

WebView should not affect StatusBar.

**Environment:**
 - OS: iOS
 - OS version: 12.1
 - react-native version: 0.59.8
 - react-native-webview version: 5.8.2

**Comment by jvandenaardweg** [comment]
Experiencing the same
