### ISSUE TITLE
Record Audio permissions for android not working as expected

### ISSUE THREAD

**Issue by niranjan-b-prajapati** [react-native-community/react-native-webview#574]
**Bug description:**
I have a weblink which i need to integrate for recording audio, even after allowing recording permissions in android it gives error. The same link works properly on mobile chrome.
Wondering what is happening differently in webview that it is not allowing to record audio. It gives `Error getting audio` as the error message.

Following is the url for testing audio recorder :
`https://webaudiodemos.appspot.com/AudioRecorder/index.html`

Following are the permissions used in android :
```
<uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
<uses-permission android:name="android.permission.RECORD_AUDIO" />
```

**Expected behavior:**
If the Url works properly on mobile chrome browser it should work in webview also.

Can anyone please help me get through this issue. its really critical for me to find solution to this.

**Environment:**
 - OS: Android
 - OS version: 7.1.1
 - react-native version: 0.59.5
 - react-native-webview version: 5.8.2

**Comment by rshaikhcornerstone** [comment]
I am also getting same problem. App is opening file manager for fetching audio files. It should open audio recorder. Please reply this soon.

**Comment by henriquegomes6** [comment]
I'm also having the same problem
