### ISSUE TITLE
fullscreen landscape mode support 

### ISSUE THREAD

**Issue by Josephdias92** [react-native-community/react-native-webview#586]
Hello im currently using version 5.9.1. i was waiting for fullscreen-video support for webview so when the user clicks on embedded youtube link it suppose to open fullscreen in landscape mode. currently it opens youtube in fullscreen in portrait mode.

**Comment by dvicory** [comment]
If a user rotates their device it will switch to landscape mode. Originally, I did have it force landscape, but some people wanted fullscreen portrait videos, so I left it up to users to rotate.

Do you have some ideas that will please both camps?

**Comment by Josephdias92** [comment]
> If a user rotates their device it will switch to landscape mode. Originally, I did have it force landscape, but some people wanted fullscreen portrait videos, so I left it up to users to rotate.
> 
> Do you have some ideas that will please both camps?

I tried turning on the auto rotota and pressing the full-screen button on YouTube player it didn't rotate. Also tthere is no way for the user to exit the full-screen except pressing the back button.
We can set a flag in webview options to force auto rotate, just like how we have to allow fullscreen

**Comment by dvicory** [comment]
What device/OS are you on? Auto rotation worked for me on quite a few combinations.

There's quite a few possibilities we could allow... forcing landscape or portrait, "suggesting" landscape or portrait (user could still rotate to a different orientation), or do nothing (like it is currently).

I saw in some other react-native WebView forks that handled fullscreen they emitted events instead. What do you think of that API instead of declaratively choosing orientation behavior?

**Comment by Josephdias92** [comment]
I'm using one plus 5t. Android version 9.
I feel declarative is more suitable in this case. Otherwise I will have to select full-screen button of YouTube add click handler and then call force rotate API. It will make mine and others life alot difficult 🙈☹️

**Comment by dvicory** [comment]
I can look into this in the next week.

**Comment by ouabing** [comment]
I use [react-native-orientation-locker](https://github.com/wonday/react-native-orientation-locker) to change the orientation when the webview changes to fullscreen mode. What I'm seeking for is how to get notified when it enters/exits fullscreen mode.

**Comment by ouabing** [comment]
@Josephdias92  My current workaround is changing the Java code to emit events in onShowCustomView and onHideCustomView ([see code here](https://github.com/ouabing/react-native-webview/commit/606a24c97b0328488750ff78f37d0c0ea7490a12)). Then you can listen to it to call rorate API.

I think exposing callbacks for exiting/entering instead of providing solutions for rotating will be more reasonable. There are still other problems can be solved using callbacks, like custom Back handling in fullscreen mode.

**Comment by dvicory** [comment]
@ouabing I'm curious what kind of things you would want to do with custom back handling. Without doing anything special, back button closes the fullscreen video. If you intercepted that and it works as expected, users would be prevented from minimizing the video unless they press the fullscreen button. Unless that's your goal or you also want a method to be able to minimize the video on-demand (which wouldn't be hard).

I'm also a little worried how reliable/glitchy appearing an event would be versus declaratively specifying behavior. If we had an event, the video would go fullscreen, and potentially be rotated immediately via rotation API after some frames have already rendered.

**Comment by ouabing** [comment]
@dvicory Sorry for the mess to introduce another problem. On some device supporting navigation gesture, swiping back in fullscreen mode will lead to black screen, so I have to disable the back handler in the callbacks.

I agree with you that callbacks may lead to some unexpected behavior. The current iOS rotation behavior is not declarative, will it make people confused If the Android rotation API is not match the iOS implementation?

**Comment by Josephdias92** [comment]
Hello. Any update on this issue ?😃

**Comment by earlyCloud** [comment]
Any update on this issue ?

**Comment by ouabing** [comment]
Guys you can try [my fork](https://github.com/ouabing/react-native-webview) as a temporary solution.

My fork simply emits `WebViewPlayVideoFullScreenStart` and `WebViewPlayVideoFullScreenEnd` events, you can subscribe them like this:

```
import Orientation from 'react-native-orientation-locker'

class YourComponent extends PureComponent {

  constructor(props) {
    super(props)
    if (Platform.OS === 'android') {
      DeviceEventEmitter.addListener(
        'WebViewPlayVideoFullScreenStart',
        this.handleVideoStart,
      )
      DeviceEventEmitter.addListener(
        'WebViewPlayVideoFullScreenEnd',
        this.handleVideoEnd,
      )
    }
  }

  public componentWillUnmount() {
    if (Platform.OS === 'android') {
      DeviceEventEmitter.removeListener(
        'WebViewPlayVideoFullScreenStart',
        this.handleVideoStart,
      )
      DeviceEventEmitter.removeListener(
        'WebViewPlayVideoFullScreenEnd',
        this.handleVideoEnd,
      )
    }
  }

  private handleVideoStart = () => {
    Orientation.lockToLandscape()
  }

  private handleVideoEnd = () => {
    Orientation.lockToPortrait()
  }
}
```

I also exposed a native method `exitFullScreen`, if you run into crash issue when swiping back in full screen mode, you can register your own BackHandler listener and call `exitFullScreen` explicitly.

**Comment by earlyCloud** [comment]
> 
> 
> Guys you can try [my fork](https://github.com/ouabing/react-native-webview) as a temporary solution.
> 
> My fork simply emits `WebViewPlayVideoFullScreenStart` and `WebViewPlayVideoFullScreenEnd` events, you can subscribe them like this:
> 
> ```
> import Orientation from 'react-native-orientation-locker'
> 
> class YourComponent extends PureComponent {
> 
>   constructor(props) {
>     super(props)
>     if (Platform.OS === 'android') {
>       DeviceEventEmitter.addListener(
>         'WebViewPlayVideoFullScreenStart',
>         this.handleVideoStart,
>       )
>       DeviceEventEmitter.addListener(
>         'WebViewPlayVideoFullScreenEnd',
>         this.handleVideoEnd,
>       )
>     }
>   }
> 
>   public componentWillUnmount() {
>     if (Platform.OS === 'android') {
>       DeviceEventEmitter.removeListener(
>         'WebViewPlayVideoFullScreenStart',
>         this.handleVideoStart,
>       )
>       DeviceEventEmitter.removeListener(
>         'WebViewPlayVideoFullScreenEnd',
>         this.handleVideoEnd,
>       )
>     }
>   }
> 
>   private handleVideoStart = () => {
>     Orientation.lockToLandscape()
>   }
> 
>   private handleVideoEnd = () => {
>     Orientation.lockToPortrait()
>   }
> }
> ```
> 
> I also exposed a native method `exitFullScreen`, if you run into crash issue when swiping back in full screen mode, you can register your own BackHandler listener and call `exitFullScreen` explicitly.

Thanks for the reply. I actually tried it but got stuck with issue [#580](https://github.com/react-native-community/react-native-webview/issues/580)

**Comment by ouabing** [comment]
@earlyCloud Yeah my fork is a 6.x version which is already migrated to AndroidX. If you are still using RN 0.59, you can try using [Jetifier](https://github.com/mikehardy/jetifier) with `yarn jetify -r` to convert AndroidX dependencies back to support libs.

**Comment by aTastyT0ast** [comment]
Is there any update on this? Using a fork not really a solution for us right now.

**Comment by nguyen95** [comment]
Is there a solution for this problem? Set a flag in webview options is needed.

**Comment by carlosvini** [comment]
When the video is fullscreen and I manually rotate the device the video exits fullscreen mode.
I was willing to fork the lib and send an event as suggested in one of the comments. But unfortunately when I programatically change it to Portrait the video leaves fullscreen mode just like it does when you manually rotate the device.

Anyone got a solution? 

Tested this on a new app, with react-native: 0.60.5 and react-native-webview: ^6.9.0.

**Comment by hweister** [comment]
by setting below in AndroidManifest.xml file, it seems resolve the problem:
`
android:configChanges="keyboard|keyboardHidden|screenSize|orientation"
android:screenOrientation="portrait"
`
Now when video in fullscreen mode, it can set to both landscape and portrait mode. when exit video full screen mode, app still locked in portrait mode.

**Comment by Loxrie** [comment]
Are there some dependencies external to AndroidManifest.xml and react-native-webview that may stop this working?  E.g. Android OS etc.  

`
Android OS: 8.0.0
React Native: 0.60.5
React Native Webview: 7.4.3
`

The video I have embedded from youtube briefly renders in portrait mode then closes down and returns to portrait mode at the top of the webview with the embedded youtube section returned to its original unclicked state.

iOS behaviour has always been fine.

**Comment by suman98** [comment]
s
