### ISSUE TITLE
keyboardDisplayRequiresUserAction acts as if it's always false

### ISSUE THREAD

**Issue by fungilation** [react-native-community/react-native-webview#595]
**Bug description:**
I've tested `keyboardDisplayRequiresUserAction` set to true, false or unset. On test uri https://www.macrotrends.net/2616/president-trump-stock-market-performance, input box is always focused and keyboard always opens without user interactivity.

I tested this to be true on iPhone X on 12.3, iOS simulators 12.2 and 11.4.

**To Reproduce:**
```js
<WebView
  keyboardDisplayRequiresUserAction={true}
  useWebKit={true}
  originWhitelist={['*']}
  source={{ uri: 'https://www.macrotrends.net/2616/president-trump-stock-market-performance' }}
/>
```

**Expected behavior:**
`WebView` should behave this way only if `keyboardDisplayRequiresUserAction={false}` explicitly

**Screenshots/Videos:**
![image](https://user-images.githubusercontent.com/3803466/58338906-7256cd80-7dfd-11e9-8c35-9dfc65cffc3b.png)

**Environment:**
 - OS: iOS
 - OS version: 12.2, 12.3, 11.4
 - react-native version: 0.59.8
 - react-native-webview version: 6.1.0

**Comment by fungilation** [comment]
Related: https://github.com/react-native-community/react-native-webview/pull/540

**Comment by fungilation** [comment]
I figured out what the bug is but not how to fix it, I don't know objc.

I have multiple webviews. First webview had `keyboardDisplayRequiresUserAction={false}`, subsequent webviews have `keyboardDisplayRequiresUserAction={true}`. The first webview is the culprit, that if 1 has the prop set to false, any subsequent webviews would behave as if it's false regardless of what `keyboardDisplayRequiresUserAction` is set to on subsequent webviews. This is bugged.

I worked around by simply not trying to programmatically activate keyboard in first webview, and set all webview's `keyboardDisplayRequiresUserAction` to `true`. This works fine, all webviews cannot activate keyboard without user action.

**Comment by navata** [comment]
keyboardDisplayRequiresUserAction not working in UIWebView -_-

**Comment by lilasquared** [comment]
Pretty sure I just came across this issue and its almost 3 years later.  Any chance this was ever looked at?

**Comment by kristinadarroch** [comment]
This is still an issue...
