### ISSUE TITLE
Do not display data in Android

### ISSUE THREAD

**Issue by namhd1992** [react-native-community/react-native-webview#597]
I use code demo  show web 'https://infinite.red' but it not show

![60805761_2124635657649333_5727260622026964992_n](https://user-images.githubusercontent.com/33983591/58340171-69a1de00-7e75-11e9-9e78-a0db5ffecb81.jpg)
![image1](https://user-images.githubusercontent.com/33983591/58340227-85a57f80-7e75-11e9-89a3-97e74f322667.png)

**Environment:**
 - OS: samsung A50
 - OS version: Android 9.0
 - "react": "16.8.3",
 - "react-native": "0.59.8",
 - react-native-webview version: ^5.10.0

**Comment by mjfiandaca** [comment]
I believe you need the prop to whitelist the website; it worked once I put in
 originWhitelist={['*']}

**Comment by namhd1992** [comment]
@mjfiandaca I install react-native-webview and react-native-admob happening an error.
![abcs](https://user-images.githubusercontent.com/33983591/58361750-08046280-7ebb-11e9-822e-1866db3da3e7.png)
