### ISSUE TITLE
MIGRATED: html select element not working in WebView on android tablets (#12070)

### ISSUE THREAD

**Issue by jamonholmgren** [react-native-community/react-native-webview#6]
Migrated from: https://github.com/facebook/react-native/issues/12070

@miestr says:

---
Description
The select element with regular ng-options is not working correctly on Android tablets: the options are not displayed on click/touch.
My react-native app contains a simple WebView which loads a simple url, for example http://www.w3schools.com/bootstrap/bootstrap_forms_inputs.asp
The webpage contains a select element at the bottom, but when I click on it, no options are displayed. At the same time, the multiple select DOES work. The issue found only on Android tablets. On android phones it works.

Reproduction
Create a simple react-native app with simple WebView in it, src prop set to http://www.w3schools.com/bootstrap/bootstrap_forms_inputs.asp. Scroll down to selects with dropdown options and click on simple select. Btw, the select DOES work when another input text is in focus (keyboard up).
This is a sample app , but the bug is not reproducable on rnplay because there is no Android tablet.

Additional Information
React Native version: 0.40.0, react-native-cli version 2.0.1
Platform: bug found on real tablets with Android 5.0.1. Android 5.1.1, tablet emulator with Android 6.0
Operating System: Windows
---

_More details on the original thread_

**Comment by viv3kk** [comment]
do we have any solution or work around for this?

**Comment by Titozzz** [comment]
Not yet, if you find anything, feel free to open a pull request, we'd love that

**Comment by tehOPEologist** [comment]
would really like to hear the status of this bug, as it's fragmenting my new react-native app being deployed, since my critical pages with select elements won't work on android tablet

**Comment by tehOPEologist** [comment]
in the interim until this issue is resolved from this package itself, i went ahead and applied a hacky fix so i can deploy my app to android tablets.  an outline for others to use in the short-term is below:

the main problem is that the dropdown is rendering behind the webview, which doesn't tell the webview to relayout and show the dropdown on top of the webview when a select is tapped.  to get around this problem, i force a relayout by increasing the width of the parent container of the webview (we have it wrapped in a scrollview so people can pull to refresh) by 1, then immediately put it back to its original width.  i do this by using state to manage the width style property on the scrollview and put the width back to normal in the callback of the setState() method, so toggling the width change is synchronous and consistent.

**Comment by bernardmma** [comment]
Any update on this? I tried the interim solution that @tehOPEologist provided, but didn't end up working out for me.

**Comment by nandiniparimi1107** [comment]
@tehOPEologist could you please share the code?

**Comment by tehOPEologist** [comment]
@nandiniparimi1107 unfortunately i cannot, but my above description of the hack should be enough to create your own workaround for this current issue.  this issue shouldn't be closed until a true resolution is found for this problem.

**Comment by muhammad-nauman** [comment]
still searching for solution

**Comment by swallville** [comment]
Any solution?

**Comment by SkyTreasure** [comment]
Hi @3jedgcm ,
I added this 
` <WebView
            source={{html: sampleHTML}}
            style={{width: wp('80'), height: hp('40')}}
          />
          <FixWebView />`
But still not facing the same issue? Would appreciate your help?

**Comment by akolliy1** [comment]
It's crazy for a few years now, there hasn't been a solution to this issue. And I haven't seen a workaround. 
>Basically, I am trying to query a deep Node Span Element(by class name) of an external link(page). I could get a result for the anchor link query and even got a result that wasn't related to the anchor query. But Querying by span returns nothing.
NOTE: There's a lot of span on that particular page

```
const script = (store) => `!(function() {
  document.body.style.backgroundColor = 'red';
  
  var $$ = function (selector, parent) {
    return Array.prototype.slice.call((parent ? parent : document).querySelectorAll(selector));
  };

  // NOTE: This page has a lot  of span elements
  // here's the query, querying by span returns nothing.
  var all_itemDescs = $$('a.sc-product-link span');

  if ( all_itemDescs ) {
   for ( var i in all_itemDescs ) {
      window.alert(all_itemDescs[i]);
    }
  }

  true
})();
`

<WebView
     ref={WEBVIEW_REF}
     source={{ uri: `${ isCheckout ? store.cartLink : store.link }` }}
     injectedJavaScript={isCheckout ? script(store) : ""}
     javaScriptEnabled
     onMessage={onMessage}
     injectedJavaScriptForMainFrameOnly={false}
     javaScriptEnabledAndroid={true}
     renderLoading={LoadingIndicatorView}
     startInLoadingState={true}
/>
 ```
