### ISSUE TITLE
Video in fullscreen - multiple rotations causes blackscreen (Android)

### ISSUE THREAD

**Issue by karvulf** [react-native-community/react-native-webview#600]
**Bug description:**

If I have a video in fullscreen in Android and I rotate my phone, sometimes the screen gets black, but I can still hear the sound of the video.

**To Reproduce:**

Just put a YouTube-video in the webview and allow fullscreen. After that rotate your phone multiple time s and the screen gets black.

**Expected behavior:**

It shouldn't get blackscreen.

**Environment:**
- Samsung Galaxy S7
 - OS: Android
 - OS version: 8.0
 - react-native version: 0.59.8
 - react-native-webview version: 5.10.0

**Comment by a-ryazanov** [comment]
I have the same problem, but it appears when exiting full-screen mode.

**Comment by matteodanelli** [comment]
Same problem here, when app recovers from background.
