### ISSUE TITLE
Android: Facebook-videos are not playable in webview

### ISSUE THREAD

**Issue by karvulf** [react-native-community/react-native-webview#601]
**Bug description:**

If I have Facebook-video in my webview, it isn't playable.

**To Reproduce:**

Just put a facebook-video in the webview and try to click play.

**Expected behavior:**

It should play the video instead of doing nothing.

**Environment:**
 - OS: Android
 - OS version: 8.0
 - react-native version: 0.59.8
 - react-native-webview version: 5.10.0

**Comment by tijs** [comment]
@karvulf you might want to try this fix; https://github.com/react-native-community/react-native-webview/issues/526#issuecomment-496853121

**Comment by karvulf** [comment]
Yes that seems to work, thank you @tijs
