### ISSUE TITLE
location.reload() not working in Android

### ISSUE THREAD

**Issue by Kelvin9393** [react-native-community/react-native-webview#602]
**Bug description:**
return location.reload() in javascript code not trigger / responding in Android webview. It works fine in react-native official webview. Am I missed out something?

**To Reproduce:**

**Expected behavior:**
It webview should reload itself.

**Screenshots/Videos:**

**Environment:**
 - OS: Android
 - OS version: 7
 - react-native version: 0.59.8
 - react-native-webview version: 5.10.0

**Comment by suhaotian** [comment]
```js
location.href = location.href
```

**Comment by devdebajyotidas** [comment]
The issue still persists on Android. reload() works in iOS though.

**Comment by DylanWolfframm** [comment]
The issue is still a thing in 2022 :(

**Comment by ayhandoslu** [comment]
`location.href = location.origin + location.pathname + location.search`
worked for us.

**Comment by kangchao2015** [comment]
> `location.href = location.origin + location.pathname + location.search` worked for us.

also works for me
