### ISSUE TITLE
WKWebView sometimes freezes on loading YouTube video

### ISSUE THREAD

**Issue by ghsdh3409** [react-native-community/react-native-webview#605]
**Bug description:**

* WKWebView sometimes freezes on loading video from YoutTube website.
* In this case, all of the touch event on webview are ignored and then the video is loading (buffering) infinitely.
* After a few seconds later (about 20~30secs?), pending touch events(ignored before) work suddenly.
* This case is also raised on static HTML using YouTube iFrame.
* This case is raised more frequently on the simulator.

**To Reproduce:**

* Simply add webview like below.
```js
<WebView
  source={{ uri: 'https://www.youtube.com/watch?v=NQczxsrnixs' }}
  allowsInlineMediaPlayback
  mediaPlaybackRequiresUserAction={false}
  automaticallyAdjustContentInsets={false}
  useWebKit
/>
```
* Reload app several times on **simulator**, then video is loading infinitely and touch events are ignored. (WebView is freezing).

**Expected behavior:**

* **Always** works normally.

**Screenshots/Videos:**

![May-29-2019 11-40-00](https://user-images.githubusercontent.com/6203798/58525458-c5b68a80-8206-11e9-8d97-ae856d6fbd9e.gif)

**Environment:**
 - OS: iOS
 - OS version: 12.2
 - react-native version: 0.59.8
 - react-native-webview version: 5.10.0

**Comment by ghsdh3409** [comment]
I implemented the same app by using swift (ios native app). It has the same issue. So, I think that this repository has no responsibility for an issue.

**Comment by ohtangza** [comment]
@ghsdh3409 Why was this issue closed?

**Comment by ghsdh3409** [comment]
@ohtangza Please see comment above.
