### ISSUE TITLE
Disable Text Selection

### ISSUE THREAD

**Issue by alz10** [react-native-community/react-native-webview#607]
**Is your feature request related to a problem? If so, Please describe.**

I'm using react-navigation to do drawer navigation unfortunately everytime i swipe right to open the drawer, the text in Webview gets selected and it is annoying because the selection text (Copy, Share, Select All) overlap to the drawer. I'm asking if you can implement a disableTextSelection feature

**Describe the solutions you came up with**

None yet

**Additional context**

None

**Comment by Adroit-hadjor** [comment]
any solution cause its getting really annoying,ive tried everything.Someone please help me

**Comment by brian-perlego** [comment]
Hello,
You can add this CSS to disable the context menu on iOS
```
body {
  -webkit-touch-callout: none;
  -webkit-user-select: none;
  -khtml-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  user-select: none;
}
```

**Comment by Albert0405** [comment]
> Hello,
> You can add this CSS to disable the context menu on iOS
> 
> ```
> body {
>   -webkit-touch-callout: none;
>   -webkit-user-select: none;
>   -khtml-user-select: none;
>   -moz-user-select: none;
>   -ms-user-select: none;
>   user-select: none;
> }
> ```

Ill try this one, Thanks

**Comment by bbeckk** [comment]
same issue. Have you solved it? @Albert0405

**Comment by rockneverdies55** [comment]
In addition to `* { -webkit-user-select: none; }` I had to have `input, select { -webkit-user-select: auto !important;` so user could type input on ios.

**Comment by bbeckk** [comment]
@rockneverdies55  where should those css be added?

**Comment by brian-perlego** [comment]
In your content css, you can inject it with `this.webViewRef.injectJavaScript()` if you're loading a remote file.

**Comment by bbeckk** [comment]
@brian-perlego I didn't get it. Should I add it inside react native project?

**Comment by brian-perlego** [comment]
Create a ref to your webview `<WebView ref={ref => { this.webViewRef = ref }} />` and then insert the css with this:
`this.webViewRef.injectJavaScript("document.body.style = ...")`

**Comment by vaishnikhil17** [comment]
Use injectedJavascript to disable text selection 
const INJECTEDJAVASCRIPT = "document.body.style.userSelect = 'none'";
<WebView
   source={{uri: "https://www.google.com/"}}
   injectedJavaScript={INJECTEDJAVASCRIPT}
   style={{flex: 1}}
/>

**Comment by Stevemoretz** [comment]
> const INJECTEDJAVASCRIPT = "document.body.style.userSelect = 'none'";

Don't use `const` that's es6 and it might not be supported you should use `var` instead.
