### ISSUE TITLE
v5.10.0 mixedContentMode='always' no effect

### ISSUE THREAD

**Issue by andrei-m-code** [react-native-community/react-native-webview#608]
**MixedContentMode='aways' doesn't allow unsecure HTTP websites**

**To Reproduce:**
Try any http website source with mixedContentMode='always' attribute.  Actual: ERR_CLEAR_TEXT_NOT_PERMITTED error.

**Expected behavior:**
Website opens just fine.

**Screenshots/Videos:**
![Screenshot_1559144893](https://user-images.githubusercontent.com/5212280/58571569-006cf280-8208-11e9-8d25-1fbc287010b7.png)

**Environment:**
 - OS version: Windows 10/ Android L
 - react-native version: 0.59.8
 - react-native-webview version: 5.10.0

**Comment by MikeThuchchai** [comment]
Hello, could you try this

add 
```
<application
    ....
    android:usesCleartextTraffic="true"
    ....>
```
on 
`android/app/src/main/AndroidManifest.xml`

according to
https://stackoverflow.com/questions/52707918/webview-showing-err-cleartext-not-permitted-although-site-is-https
