### ISSUE TITLE
Preventing videos playing when app is background (Especially Android, Youtube video)

### ISSUE THREAD

**Issue by cereme** [react-native-community/react-native-webview#610]
**Is your feature request related to a problem? If so, Please describe.**
My Android app displays youtube videos with react-native-webview, and is rejected from Google Play Store. The reason was "Device and Network abuse" and it appears when Youtube video can be played when the app is background.

**Describe the solutions you came up with**
I wrote the code in ```RNCWebViewManager.java```:
```java
protected static class RNCWebView extends WebView implements LifecycleEventListener {
//...
    @Override
    public void onHostResume() {
      super.onResume();
    }

    @Override
    public void onHostPause() {
      super.onPause();
    }
```
and I solved my problem.
I think adding "disableBackgroundPlaying" props and enabling my code above will work.

**Comment by thebergamo** [comment]
There is any PR to add this feature?

**Comment by cereme** [comment]
I couldn't find test case, "background media playing" in my devices(Android 8, 9), except Google Play Store's approval. Cause I'm not Android developer, if someone has good idea on that, please let me know or PR!

**Comment by thebergamo** [comment]
In your case @cereme  did you forked this module and wrote that code inside? I'm dealing with same problem with Play Store.

I'm not sure if I should write a entire custom WebView just to add those method or if I should just fork it and use it like that for now.

**Comment by cereme** [comment]
@thebergamo

> In your case @cereme did you forked this module and wrote that code inside? I'm dealing with same problem with Play Store.

Yes, I forked and wrote that code insdie and resolved Play Store issue

**Comment by freesongs** [comment]
Hello, Can I have more information about this app that plays video in background which is something I am looking for? I don;t care about Google app, as this is needed for private use. Thanks!
