### ISSUE TITLE
Youtube video in WebView: StatusBar is gone after fullscreen (iOS 12)

### ISSUE THREAD

**Issue by sebk** [react-native-community/react-native-webview#62]
- [ x] Review the documentation: https://facebook.github.io/react-native
  - [ x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x ] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Environment
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
      Memory: 529.69 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.11.2 - /usr/local/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 6.1.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0
      react-native: 0.57.1 => 0.57.1
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

## Description
I'm including a youtube video via a WebView.

Code snippet:

```
<WebView 
  style={styles.videoWebView}
  source={{uri: 'https://www.youtube.com/embed/tgbNymZ7vqY?playsinline=1'}}
  allowsInlineMediaPlayback={true}
/>
```

When the video comes **back from fullscreen the StatusBar is gone**.

This happens since iOS 12. On iOS 11 this problem doesn't occure (technically in iOS 11 there is also a StatusBar disappear problem, but a little bit different, and I would like to focus on iOS 12 only for now).

## Reproducible Demo
A react-native project can be found here: 
https://github.com/sebk/RN-WebViewTest

**Comment by congnd** [comment]
same with me. any update?

**Comment by Titozzz** [comment]
This project mostly depends on community to address the issues, we are trying to help to precess and review as fast as possible everything, however we can't be full time on this! I hope someone can submit a PR, and I'll be happy to get it merged

**Comment by malonguwa** [comment]
@sebk @congnd 
Maybe give a try for this code? 
```
import { StatusBar } from 'react-native';
StatusBar.setHidden(false) 

```
I found the solution in here, but I have not tested myself yet... please let me know if it is working :P
https://github.com/react-native-community/react-native-video/issues/591

**Comment by sebk** [comment]
Kind of...The problem is to know when to hide and when to show the StatusBar. In the App I want to show the Bar. Only when the video is in fullscreen the bar should be hidden. I have to know when the video goes into fullscreen and when it leaves it. The question is: When do I call `setHidden(false)` and when `setHidden(true)`?

On iOS I found a native solution:

`- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  ...
[[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(videoExitFullScreen:) name:@"UIWindowDidBecomeHiddenNotification" object:nil];
...
}

- (void)videoExitFullScreen:(id)sender
{
  [[UIApplication sharedApplication] setStatusBarHidden:NO animated:YES];
}`

**Comment by mahavirvataliya** [comment]
@sebk Thanks its working

**Comment by partiellkorrekt** [comment]
I am still having this issue in version 6.3.0
