### ISSUE TITLE
renderLoading only shows for initial load.

### ISSUE THREAD

**Issue by jpodpro** [react-native-community/react-native-webview#622]
**Bug description:**
the render loading template shows on initial webview load. however when navigating within the webview i would expect to see it again while the webview is again in a loading state. instead no loading indication happens.

**Environment:**
 - OS: Android and iOS, multiple versions tested.
 - react-native version: 0.57.8
 - react-native-webview version: 5.2.1

**Comment by xbenjii** [comment]
It's not ideal but you can hack around this with

```
constructor() {
  this.webview = React.createRef();
}
render() {
  <WebView
    ref={this.webview}
    source={...}
    onLoadStart={() => this.webview.current.setState({ viewState: "LOADING" })}
  />
}
```

**Comment by MedeaMelana** [comment]
[xbenjii's hack](https://github.com/react-native-webview/react-native-webview/issues/622#issuecomment-529404709) doesn't seem to work (anymore), at least not on iOS. I'd like to reopen this feature request please.
