### ISSUE TITLE
When I run :   rect-native run-android ， FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by MrJYJ** [react-native-community/react-native-webview#627]
When I run :   rect-native run-android
> Configure project :react-native-webview 
:react-native-webview:reactNativeAndroidRoot C:\Users\Administrator\Desktop\reactNative\supervisor\node_modules\react-native\android

> Task :react-native-webview:compileDebugJavaWithJavac FAILED
C:\Users\Administrator\Desktop\reactNative\supervisor\node_modules\react-native-webview\android\src\main\java\com\reactnativecommunity\webview\RNCWebViewManager.java:452: 错误: 无法将枚举 ScrollEventType中的方法 getJSEventName应用到给定类型;
    export.put(ScrollEventType.getJSEventName(ScrollEventType.SCROLL), MapBuilder.of("registrationName", "onScroll"));
                              ^
Need: No parameters
Find: ScrollEventType
Reason: The actual parameter list is different from the formal parameter list in length
注: C:\Users\Administrator\Desktop\reactNative\supervisor\node_modules\react-native-webview\android\src\main\java\com\reactnativecommunity\webview\RNCWebViewManager.java使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: C:\Users\Administrator\Desktop\reactNative\supervisor\node_modules\react-native-webview\android\src\main\java\com\reactnativecommunity\webview\RNCWebViewManager.java使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
1 个错误

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-webview:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 19s
130 actionable tasks: 5 executed, 125 up-to-date
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html

**Environment:**
    "react": "16.5.0",
    "react-native": "0.57.2",
   "react-native-webview": "^5.9.1",

I try to upgrade to  "react-native-webview": "^6.0.2",  But mistakes can also occur.

**Comment by ShrihariBhat** [comment]
same error cant able build

**Comment by JeremyBradshaw7** [comment]
I got this too with 5.11.0 and 5.10.0 but 5.9.0 didn't seem to have the same issue.

**Comment by zmangola** [comment]
upgrade react-native to 0.57.8
