### ISSUE TITLE
 rect-native run-android build fail with exception

### ISSUE THREAD

**Issue by ShrihariBhat** [react-native-community/react-native-webview#628]
> Task :react-native-webview:compileDebugJavaWithJavac 
Note: /home/shrihari/ezrealtor/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/shrihari/ezrealtor/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

**FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-webview:transformClassesAndResourcesWithPrepareIntermediateJarsForDebug'.
> java.lang.RuntimeException: java.util.zip.ZipException: duplicate entry: com/reactnativecommunity/webview/events/TopLoadingErrorEvent.class**

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s
227 actionable tasks: 195 executed, 32 up-to-date
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html

Command failed: ./gradlew installDebug

Error: Command failed: ./gradlew installDebug
    at checkExecSyncError (child_process.js:637:11)
    at Object.execFileSync (child_process.js:655:13)
    at runOnAllDevices (/home/shrihari/ezrealtor/node_modules/react-native/local-cli/runAndroid/runAndroid.js:299:19)
    at buildAndRun (/home/shrihari/ezrealtor/node_modules/react-native/local-cli/runAndroid/runAndroid.js:135:12)
    at isPackagerRunning.then.result (/home/shrihari/ezrealtor/node_modules/react-native/local-cli/runAndroid/runAndroid.js:65:12)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)

**Comment by MayoudP** [comment]
Same here !

**Comment by osvald0** [comment]
Delete the build folder and try again.

**Comment by linnett** [comment]
Yep, same error on `5.11.0`. Deleted build folder and still not working

**Comment by Titozzz** [comment]
@linnett did you delete android/build or android/app/build?

I just ran:
```
react-native init test
cd test
yarn add react-native-webview@5.11.0
react-native link react-native-webview
react-native run-android
```

Closing this as there is no clear reproduction and is probably related to build cache and not the library. If you provide a reproduction we can reopen and look into it.

**Comment by linnett** [comment]
@Titozzz Sure, that works for new projects. But what about upgrading the existing package? I'm upgrading from `5.2.1` to `5.11.0` and despite deleting the build folders, I'm still getting the following error.

> Task :react-native-webview:transformClassesAndResourcesWithPrepareIntermediateJarsForDebug FAILED

**Comment by linnett** [comment]
Is anyone going to acknowledge this?

**Comment by colorgmi** [comment]
```shell
cd ./android;
./gradlew clean;
```
I don't exactly understand what's going on, but above code make it away.

**Comment by tamurayk** [comment]
I had the same problem.

In my case it was solved in the following.

add `googlePlayServicesVersion = '16.+'` In `android/build.gradle`

```
ext {
    googlePlayServicesVersion = '16.+' // add this line
```

See: https://github.com/facebook/react-native/issues/25293#issuecomment-503157853

**Comment by liganghui** [comment]
> I had the same problem.
> 
> In my case it was solved in the following.
> 
> add `googlePlayServicesVersion = '16.+'` In `android/build.gradle`
> 
> ```
> ext {
>     googlePlayServicesVersion = '16.+' // add this line
> ```
> 
> See: [facebook/react-native#25293 (comment)](https://github.com/facebook/react-native/issues/25293#issuecomment-503157853)

Thanks !
