### ISSUE TITLE
[Questions]: How can get cookie which is set in webview in react-native?

### ISSUE THREAD

**Issue by subhendukundu** [react-native-community/react-native-webview#629]
I am trying to retrieve user entered zipcode which is added to the cookie in the webview. How do I get it? I have tried react-native-cookies which is getting an empty object not the user entered zipcode.
```
import CookieManager from 'react-native-cookies';

componentWillMount() {
    CookieManager.get('https://www.example.com')
    .then((res) => {
      console.log('CookieManager.get from webkit-view =>', res);
    });
  }
}

<WebView
  style={styles.webview}
  source={{ uri: 'https://www.example.com' }}
  injectedJavaScript={INJECTED_JAVASCRIPT}
  mixedContentMode="compatibility"
  javaScriptEnabled
  domStorageEnabled
  thirdPartyCookiesEnabled
  sharedCookiesEnabled
  originWhitelist={['*']}
/>
```
I am trying out in iOS simulator. I see https://github.com/react-native-community/react-native-webview/pull/175 as merged but cant figure out how to use it.

**Comment by tmaly1980** [comment]
Any luck with this? I'm noticing that I can't delete cookies on iOS, even though sharedCookiesEnabled is set.

**Comment by TiagoHellebrandt** [comment]
You can use the `injectedJavaScript` or `injectJavaScript` method as per the [documentation](https://github.com/react-native-community/react-native-webview/blob/master/docs/Guide.md#communicating-between-js-and-native) 

    const getCookiesJS = "ReactNativeWebView.postMessage(document.cookie)";
    return (
      <WebView 
          ref={ref => this._webview = ref}
          injectedJavaScript={getCookiesJS}
          onMessage={event => console.log(event.nativeEvent.data)}
          source={{ uri: "https://www.example.com" }}
          javaScriptEnabled={true}
      />
    );

**Comment by aiyuchen** [comment]
@TiagoHellebrandt Can't get HTTPOnly Cookies

**Comment by hengkx** [comment]
how to resolve?

**Comment by Mhd-Emad** [comment]
Try this way, it's working fine
https://dev.to/safaiyeh/react-native-authentication-with-webview-1nh
