### ISSUE TITLE
Can not saved images on Webview.

### ISSUE THREAD

**Issue by ru88s** [react-native-community/react-native-webview#63]
Can not saved images on Webview.
Long tap does not display the menu.
Please fix this.

I asked a question here.
https://github.com/expo/expo/issues/2236

**Comment by jamonholmgren** [comment]
Hey @ru88s, it appears that it works on my machine with a bare React Native install.

![image](https://user-images.githubusercontent.com/1479215/46252340-783a1180-c41c-11e8-8700-5c052f21760f.png)

I haven't tried Android yet, though.

**Comment by Titozzz** [comment]
Probably does not work on Android for the same kind of reasons than upload is not working...yet

**Comment by ru88s** [comment]
@Titozzz Oh, I understand. Thank you.
