### ISSUE TITLE
Jquery ajax in webview javascript file not working

### ISSUE THREAD

**Issue by CuppaLabs** [react-native-community/react-native-webview#635]
**Bug description:**

When i try to make a jquery ajax call inside a javascript file in the webview html page, it throw an error as below 

<img width="318" alt="Screenshot 2019-06-12 at 9 38 07 PM" src="https://user-images.githubusercontent.com/3957664/59367771-6e61ff80-8d5a-11e9-9040-75c0a9a75177.png">

**To Reproduce:**

**Expected behavior:**

**Screenshots/Videos:**

**Environment:**
 - OS:
 - OS version:
 - react-native version:
 - react-native-webview version:

**Comment by m1m6** [comment]
same here

**Comment by 2xSamurai** [comment]
@CuppaLabs @m1m6 did you guys find any solution for this. I'm also stuck here.

**Comment by mrkencable** [comment]
I'm trying to use WebView in a production app, and I can't get XMLHTTP or $.Ajax calls to work in android webview... they work perfectly in desktop browser
what's the workaround ?

**Comment by theZappr** [comment]
Yup we are also trying to use this as well but no joy :(
