### ISSUE TITLE
`window.history` API does not generate events on iOS

### ISSUE THREAD

**Issue by swansontec** [react-native-community/react-native-webview#640]
# Problem

Web pages can use the `window.history` API to manipulate the back button & browser location without reloading the page. This is a popular technique in modern apps, and should work correctly in the `WebView` component.

On iOS however, navigating this way doesn't generate any events. This means there is no way for the host application to update the document URL or back button behavior, leading to a broken user experience.

## To reproduce

Visit the [demo page](https://www.swansontec.com/temp/history/a.html). The "push" buttons create virtual history entries, and the "back" and "forward" buttons navigate using the `window.history` API.

* In a browser, you can watch the address bar and browser history change.
* In an Android WebView, these navigation actions generate `onLoad`, `onLoadEnd`, & `onNavigationStateChange` events.
* In an iOS WKWebView, these navigation actions don't trigger any events (the bug).

## Expected behavior

API's like `window.history.pushState` should trigger the same events on iOS as they do on Android (like `onNavigationStateChange`).

## Environment:
 - OS: iOS 11
 - react-native version: 0.59
 - react-native-webview version: 5.8.2

**Comment by swansontec** [comment]
## Possible solution 1: Match Android behavior

If iOS were to generate the appropriate `onNavigationStateChange` events for non-navigation history changes, this would allow existing apps to keep working.

The current way to implement a smart back button is to capture a `canGoBack` flag using the `onNavigationStateChange` callback:

```javascript
<WebView
  onNavigationStateChange={navState => {
      this.canGoBack = navState.canGoBack
  }}
  ref={element => {
      this.webView = element
  }}
/>
```

Now, the back button handler can use `this.canGoBack` to decide whether to go back within the page, or leave the scene:

```javascript
onBackButtonPress () {
  if (this.webView && this.canGoBack) {
    this.webView.goBack()
  } else {
    this.props.navigation.pop() // Return to the main app
  }
}
```

This solution isn't great, though, both the end-user has to do extra book-keeping to track the `canGoBack` flag.

I also tried implementing this solution in #641, but it was harder than expected, and my solution stil has issues. Getting this work 100% will be hard.

## Possible solution 2: Provide a `canGoBack` flag

Perhaps the `WebView` could track the `canGoBack` flag on its own, exposing it as a property. This would prevent the user from having to implement an `onNavigationStateChange` callback:

```javascript
onBackButtonPress () {
  if (this.webView && this.webView.canGoBack) {
    this.webView.goBack()
  } else {
    this.props.navigation.pop() // Return to the main app
  }
}
```

On the native side, Android already has everything it needs to implement this. For iOS, it might be possible to use KVO to track the native `canGoBack` flag and mirror that up into Javascript. This could be a much simpler solution that trying to emulate the `onLoadingFinished` event.

If I close #641 and try implementing solution 2, would that seem reasonable?

**Comment by swansontec** [comment]
Duplicate of #24.

**Comment by KingAmo** [comment]
in my case, `window.history` API does not generate events either in android,  what is the problem。。。
