### ISSUE TITLE
I can not download the image in the page with Android webview.

### ISSUE THREAD

**Issue by ru88s** [react-native-community/react-native-webview#644]
I can not download the image in the page with Android webview.
I want you to be able to save by long tap.
I am using Expo SDK33.

**Comment by firofame** [comment]
@ru88s did you find a solution?

I have the same issue with `"react-native": "0.60.4"`, `"react-native-webview": "^5.12.1"`

**Comment by ru88s** [comment]
@firofame No, I have not found it yet.
