### ISSUE TITLE
serviceWorker API not available?

### ISSUE THREAD

**Issue by mhingston** [react-native-community/react-native-webview#645]
**Bug description:**
navigator.serviceWorker API unavailable within webview. User agent reported by the webview: Mozilla/5.0 (Linux; Android 9; ONEPLUS A3010 Build/PQ2A.190305.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/72.0.3626.121 Mobile Safari/537.36

**To Reproduce:**
```
<WebView
        source={{ html: `<script>alert(navigator.serviceWorker)</script>` }}
      />
```
**Expected behavior:**
navigator.serviceWorker API should be available from [Android Webview 40](https://chromereleases.googleblog.com/2015/03/android-webview-update.html)?

**Environment:**
 - OS: Android
 - OS version: 9
 - react-native version: 0.59.9
 - react-native-webview version: 5.12.0

**Comment by magbicaleman** [comment]
@mhingston did you end up resolving this somehow, or choosing another platform?

**Comment by indapublic** [comment]
```
react-native: 0.61.2
react-native-webview: 7.6.0
```

Still not supported

**Comment by vasanthhr** [comment]
service worker worked if I install as debug mode.

But it didn't work if I install apk via adb command . 
Any solution to make it work on react-native webview?

**Comment by wentokay** [comment]
`navigator.serviceWorker` won't be available via inline HTML

it can only be used on a webpage that's loaded over SSL, i.e.

```typescript
<WebView source={{ uri: "https://somewherehostingtheserviceworker.com" }} />
```
