### ISSUE TITLE
Display custom context menu entries for text selection

### ISSUE THREAD

**Issue by poltak** [react-native-community/react-native-webview#647]
**Is your feature request related to a problem? If so, Please describe.**

I'd like to be able to run my own code for the text I select on different webpages within the webview via the popup context menu. Currently the possible options there seems to be limited to whatever the default system options are.

**Describe the solutions you came up with**

Solutions would be to either:
- enable adding of new entries to the default context menu
- showing our own context menu made up only of defined entries

**Additional context**

- There was this closed, but unresolved, issue on the `react-native` repo with the same idea: https://github.com/facebook/react-native/issues/19111
- The last post in there links to this package to customize context menu entries. It works great for general text, but does not work with `<WebView>`: https://github.com/Astrocoders/react-native-selectable-text
- I found some stackoverflow answers detailing how to do this in native code. Alas I am not experienced with native mobile development, and they very well may be not be relevant answers anymore going by the dates. Android (https://stackoverflow.com/a/22391169) and iOS (https://stackoverflow.com/a/3596414).

Thanks for your time, and please let me know if you need any more information.

**Comment by mahdidavoodi7** [comment]
@poltak Did you find anything mate ?

**Comment by poltak** [comment]
Sorry, but no @mahdidavoodi7. We are no longer using WebView in our app, so have abandoned looking for a solution to this.

**Comment by aliazizi** [comment]
Is any update for this?

**Comment by friendRU** [comment]
@aliazizi hi, I have found some info. We are going to try to use this approach (there are several tabs inside to understand the decision better) - https://www.one-tab.com/page/G1CUcfXjRsyFJaVXkz2yWQ

**Comment by dzcpy** [comment]
Any updates?

**Comment by dzcpy** [comment]
https://medium.com/flutter-community/inappwebview-the-real-power-of-webviews-in-flutter-c6d52374209d
If you search for "Custom context menus" on this page, there is a way to do similar  things with `https://pub.dev/packages/flutter_inappwebview` in flutter. Maybe there's a way to borrow some code there and make it work for React Native Webview?
