### ISSUE TITLE
Add support for AllowFileAccessFromFileURLs (Android)

### ISSUE THREAD

**Issue by femiveys** [react-native-community/react-native-webview#654]
There is support for [allowUniversalAccessFromFileURLs](https://github.com/react-native-community/react-native-webview/blob/master/docs/Reference.md#allowUniversalAccessFromFileURLs), but not for allowFileAccessFromFileURLs.

Opening a local file (file://) works fine on iOS, but not in Android. On Android it is needed to set this flag. See [Android API](https://developer.android.com/reference/android/webkit/WebSettings.html#setAllowFileAccessFromFileURLs(boolean))

It seems like a small fix to support this.

**Comment by femiveys** [comment]
@all-contributors please add @femiveys for code

**Comment by Titozzz** [comment]
I can't find the Pull request related to this?

**Comment by femiveys** [comment]
I tried to push it but I don't have permission

Op do 20 jun. 2019 om 14:33 schreef Thibault Malbranche <
notifications@github.com>:

**Comment by Titozzz** [comment]
you need to fork and create a pull request from your fork :)

**Comment by elliotstokes** [comment]
Im happy to put a pr in for this if no one else is started it?

**Comment by femiveys** [comment]
I have done a PR for this: https://github.com/react-native-community/react-native-webview/pull/695

**Comment by AlexUzan** [comment]
@femiveys `WebView` already has the prop `allowFileAccess` to do this

**Comment by femiveys** [comment]
I don't think that's the case:
[setAllowFileAccess](https://developer.android.com/reference/android/webkit/WebSettings.html#setAllowFileAccess(boolean)) and [setAllowFileAccessFromFileURLs](https://developer.android.com/reference/android/webkit/WebSettings.html#setAllowFileAccessFromFileURLs(boolean)) are 2 different things. See links to Android API.

**Comment by AlexUzan** [comment]
You're right, my bad.
