### ISSUE TITLE
Unable to load local file on Android

### ISSUE THREAD

**Issue by femiveys** [react-native-community/react-native-webview#656]
When trying to open a local webpage from tyhe local file system (using `file://`) it works on iOS, but on Android we get an error:

```
Encountered an error loading page:
{
  canGoBack: false,
  canGoForward: false,
  code: -1,
  description: "net::ERR_ACCESS_DENIED",
  loading: false,
  target: 165,
  title: "Webpagina niet beschikbaar",
  url: "file:///data/user/0/com.twipepocv4/cache/data/36/Page-313.html",
}

```

This is my code:

```typescript
      <WebView
        originWhitelist={['*']}
        allowFileAccess={true}
        source={{uri: "file:///data/user/0/<myapp>/cache/data/36/Page-319.html"}}
        domStorageEnabled={true}
        allowUniversalAccessFromFileURLs={true}
        allowFileAccessFromFileURLs={true}
      />

```
I believe this has something to do with AllowFileAccessFromFileURLs but I can't get it to work.
Should any other permission be set?

**Comment by elliotstokes** [comment]
I'm also seeing this error. It started happening when we upgraded to react native 0.59. Could this be related? https://github.com/expo/expo/issues/2402#issuecomment-443726662

**Comment by stephenkopylov** [comment]
Facing the same error from time to time

**Comment by mayursarode4** [comment]
You guys are not doing properly,
Proper ways is as follows:
First install it using (If not installed),
**npm install --save react-native-webview** // inside project root directory
**react-native link react-native-webview** // it will link WebView with iOS and Android

```
import React, { Component } from 'react';
import { WebView } from 'react-native-webview';
import {LocalHtml} from './project-root/html/demo.html'; // path of your file starts with "./"

class MyInlineWeb extends Component {
  render() {
    return (
      <WebView
        originWhitelist={['*']}
        source={{ html: LocalHtml }} // here it will render your html content and load on webview.
        javaScriptEnabled={true}
        domStorageEnabled={true}
        useWebKit={true}
        startInLoadingState={true}

      />
    );
  }
}
```

I hope this will help you guys.

**Comment by AlexUzan** [comment]
So I ran into the same issue. What solved it for me was to add the prop `allowFileAccess` in the WebView (and also don't forget to ask the permission `READ_EXTERNAL_STORAGE`)

**Comment by mayursarode4** [comment]
> So I ran into the same issue. What solved it for me was to add the prop `allowFileAccess` in the WebView (and also don't forget to ask the permission `READ_EXTERNAL_STORAGE`)

It doesn't require to use prop "allowFileAccess", you try above code, it will work perfectly.

**Comment by jstnbchnn** [comment]
> You guys are not doing properly,
> Proper ways is as follows:
> First install it using (If not installed),
> **npm install --save react-native-webview** // inside project root directory
> **react-native link react-native-webview** // it will link WebView with iOS and Android
> 
> ```
> import React, { Component } from 'react';
> import { WebView } from 'react-native-webview';
> import {LocalHtml} from './project-root/html/demo.html'; // path of your file starts with "./"
> _// as per above example replace it with above LocalHtml_
> _//import {LocalHtmlText} from './data/user/0/com.twipepocv4/cache/data/36/Page-313.html';_
> 
> class MyInlineWeb extends Component {
>   render() {
>     return (
>       <WebView
>         originWhitelist={['*']}
>         source={{ html: LocalHtml }} // here it will render your html content and load on webview.
>         javaScriptEnabled={true}
>         domStorageEnabled={true}
>         useWebKit={true}
>         startInLoadingState={true}
> 
>       />
>     );
>   }
> }
> ```
> 
> I hope this will help you guys.

What if your path to the html is dynamic? And you don't know the exact file path at build.

**Comment by Shan7anu** [comment]
@femiveys 


**Navigate to node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java**

Change the following lines: 
```

settings.setAllowFileAccess(true);
settings.setAllowContentAccess(true);
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN) {
    settings.setAllowFileAccessFromFileURLs(true);
    setAllowUniversalAccessFromFileURLs(webView, true);
}


```
By default, these props will be false, make it **true** and you're good to go. :)

**Comment by imran1992** [comment]
> > You guys are not doing properly,
> > Proper ways is as follows:
> > First install it using (If not installed),
> > **npm install --save react-native-webview** // inside project root directory
> > **react-native link react-native-webview** // it will link WebView with iOS and Android
> > ```
> > import React, { Component } from 'react';
> > import { WebView } from 'react-native-webview';
> > import {LocalHtml} from './project-root/html/demo.html'; // path of your file starts with "./"
> > _// as per above example replace it with above LocalHtml_
> > _//import {LocalHtmlText} from './data/user/0/com.twipepocv4/cache/data/36/Page-313.html';_
> > 
> > class MyInlineWeb extends Component {
> >   render() {
> >     return (
> >       <WebView
> >         originWhitelist={['*']}
> >         source={{ html: LocalHtml }} // here it will render your html content and load on webview.
> >         javaScriptEnabled={true}
> >         domStorageEnabled={true}
> >         useWebKit={true}
> >         startInLoadingState={true}
> > 
> >       />
> >     );
> >   }
> > }
> > ```
> > 
> > 
> > I hope this will help you
> 
> @mayursarode4
> What if your path to the html is dynamic? And you don't know the exact file path at build.

I tried this. But got Empty white screen.
I need to render a html page which import local assests and javascript code in it.

**Comment by zhouping3** [comment]
I also encountered the same problem @imran1992 
`expo: v34.0.1
react-native-webview: v5.12.0
expo-cli: v3.0.4`

**Comment by mayursarode4** [comment]
> I also encountered the same problem @imran1992
> `expo: v34.0.1 react-native-webview: v5.12.0 expo-cli: v3.0.4`

Try above solution by @imran1992 it will help you solve your issue
for react-native: 0.60.+ version's doesn't require linking for libraries as it have auto linking feature, you just need to install the libraries and build and run the project.
### My version details are,

react-native info
info Fetching system and libraries information...
System:
    OS: Linux 4.4 Ubuntu 16.04.6 LTS (Xenial Xerus)
    CPU: (4) x64 Intel(R) Core(TM) i5-4440S CPU @ 2.80GHz
    Memory: 8.86 GB / 15.57 GB
    Shell: 4.3.48 - /bin/bash
  Binaries:
    Node: 12.4.0 - ~/.nvm/versions/node/v12.4.0/bin/node
    npm: 6.9.0 - ~/.nvm/versions/node/v12.4.0/bin/npm
  SDKs:
    Android SDK:
      API Levels: 21, 22, 23, 25, 26, 27, 28
      Build Tools: 21.1.2, 25.0.0, 25.0.2, 25.0.3, 27.0.3, 28.0.2, 28.0.3
      System Images: android-25 | Google Play Intel x86 Atom, android-28 | Intel x86 Atom, android-28 |Intel x86 Atom_64
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.4 => 0.60.4
  npmGlobalPackages:
    react-native-cli: 2.0.1

I'm not using expo-cli, so don't know about it

**Comment by imran1992** [comment]
There is only one solution for me.
I convert all the local assets into 'base64'
And use that base64 string as sourece for img, mp3 and even JavaScript file. And past whole html into source of webview. And it work.
I mean source={{html:`<htm>.......</html>}}
And the whole string become 3MB file.....

**Comment by sirmong** [comment]
It works 50/50. Sometimes my locally storaged html renders and sometimes I get ACCESS_DENIED error. Is there any solution?

**Comment by rotoxl** [comment]
Hi,
I've managed to load a local, downloaded file stored at  `/Users/rotoxl/Library/Developer/CoreSimulator/Devices/987C6DE3-29BB-4197-B22E-DC4A550C9E40/data/Containers/Data/Application/A0BAD256-CCBE-4F89-A1DB-D635F6532A57/Documents/course123/lesson320/file.html`.

Please read the complete answer at [issues/746#issuecomment-524291199](https://github.com/react-native-community/react-native-webview/issues/746#issuecomment-524291199)

**Comment by tjensen** [comment]
@Shan7anu said:

> **Navigate to node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java**
> 
> Change the following lines:
> 
> ```
> 
> settings.setAllowFileAccess(true);
> settings.setAllowContentAccess(true);
> if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN) {
>     settings.setAllowFileAccessFromFileURLs(true);
>     setAllowUniversalAccessFromFileURLs(webView, true);
> }
> ```
> 
> By default, these props will be false, make it **true** and you're good to go. :)

While this is not a fix that I would be comfortable putting into my production code, it does point to the underlying problem, which is that the order in which the WebView props are set may not be deterministic. I added `System.out.println` calls to the `setSource` and `setAllowFileAccess` methods in RNCWebViewManager.java (version 6.11.1), and when the WebView failed to load the local file URL, it was clear that the `setSource` method was called before `setAllowFileAccess` was called, so the page was being loaded before the `allowFileAccess` prop was applied.

It seems like there needs to be a mechanism to store the prop values but not actually call `loadUrl`/`loadDataWithBaseURL` until after **all** props have been stored and their settings have been applied to the `WebSettings` object for the current WebView instance.

**Comment by hsource** [comment]
@tjensen is exactly right.

## Problem

`react-native-webview` on Android handles the `allowFileAccess`
and `allowUniversalAccessFromFileURLs` by calling
`view.getSetings().setAllowFileAccess()` in the Java code:
https://github.com/react-native-community/react-native-webview/blob/47e9a0b/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java#L484

At the same time, setting `source` calls `view.loadUrl()`. This results
in a race where if `view.loadUrl()` executes before the security settings
are updated, the page-load will fail.

## Workaround

We don't load your local file until we're sure the correct permissions have been set on the WebView.

On the component you have that renders `<WebView source={...}>`:

1. Create a state variable in the constructor or the class
```tsx
this.state = { renderedOnce: false };
```

2. In `componentDidMount`, set that variable to be `true`
```tsx
componentDidMount() {
  this.setState({ renderedOnce: true });
}
```

3. When rendering, render your file only when `renderedOnce` is true:
```tsx
render() {
  return <WebView source={renderedOnce ? { uri: indexHtmlPath } : undefined} />;
}
```

**Comment by ALEEF02** [comment]
@hsource Thank you so much! I've done so much research to try and fix this issue and this is the only thing that works. Much appreciated!! :D

**Comment by vgorte** [comment]
I use functional components and had no luck with replacing the ```componentDidMount``` with a ```useEffect```.  However, I got the solution from @hsource to work by updating the ```setRenderedOnce ``` in a function that I pass to the webview's ```onLoad``` prop: 

```javascript

const [renderedOnce, setRenderedOnce] = useState(false);

const updateSource = () => {
    setRenderedOnce(true);
 };

<WebView
    originWhitelist={['*']}
    source={renderedOnce ? {uri: localHTML} : undefined}
    style={{flex: 1}}
    allowFileAccess={true}
    allowUniversalAccessFromFileURLs={true}
    allowingReadAccessToURL={workingDir}
    onLoad={updateSource}
/>
```

**Comment by sunnylqm** [comment]
This issue should remain reopen

**Comment by yaoonline** [comment]
This is my working solution - integration of fusioncharts for Android and IOS with React Native + EXPO!

import FusionCharts from "react-native-fusioncharts";
import * as FileSystem from "expo-file-system";
import { Asset } from "expo-asset";

  
const [htmlPage, setHtmlPage] = useState(null);

const getHTML = useCallback(async () => {
    const indexHtml = Asset.fromModule(
      require("../../../assets/fusioncharts.html")
    );
    await indexHtml.downloadAsync();
    const HTMLFile = await FileSystem.readAsStringAsync(indexHtml.localUri);
    setHtmlPage(HTMLFile);
}, []);

useEffect(() => {
    getHTML();
}, [getHTML]);


return (
....
        {htmlPage != null && (
          <FusionCharts
            type={state.type}
            width={state.width}
            height={state.height}
            dataFormat={state.dataFormat}
            dataSource={state.dataSource}
            libraryPath={{ html: htmlPage }}
          />
        )}
....
);

**Comment by hrtest-dev** [comment]
@yaoonline can you please post the entire code? This seems not working to me. Thanks

**Comment by hrtest-dev** [comment]
I still get an error on android, @femiveys did you manage to get it working?

**Comment by yaoonline** [comment]
I only use hooks and no classes, so use useEffect and useCallback in this way!
This code works for displaying local HTML pages on both IOS and Android.


import React, { useState, useEffect, useCallback } from 'react';
import { StyleSheet, View } from 'react-native';
import FusionCharts from 'react-native-fusioncharts';
import * as FileSystem from 'expo-file-system';
import { Asset } from 'expo-asset';

....... here different code does not concern the main idea of the solution

const [libraryPath, setLibraryPath] = useState(null);
  const getLibraryPath = useCallback(async () => {
    const indexHtml = await Asset.fromModule(
      require('../../../../assets/fusioncharts.html')
    ).downloadAsync();
    return await FileSystem.readAsStringAsync(indexHtml.localUri);
  });

  useEffect(() => {
    async function setData() {
      Promise.all([dataFetch, schemaFetch]).then(async (res) => {
        setState({ ...state, dataJson: res[0], schemaJson: res[1] });
        setLibraryPath({ html: await getLibraryPath() });
      });
    }
    setData();
  }, []);

  return (
    <View style={styles.container}>
      <View style={styles.chartContainer}>
        <FusionCharts
          dataJson={state.dataJson}
          schemaJson={state.schemaJson}
          type={state.type}
          width={state.width}
          height={state.height}
          dataFormat={state.dataFormat}
          dataSource={state.dataSource}
          libraryPath={libraryPath}
        />
      </View>
    </View>
  );

**Comment by hrtest-dev** [comment]
thank you for your reply @yaoonline !

**Comment by byron1st** [comment]
I tried all solutions suggested above, but `ERR_ACCESS_DENIED` problem occurs. In my case, I download and save a file to my app's cache directory (e.g. `file:///data/user/0/.../cache/5f8f.../downloaded.pdf`) and try to open this file using WebView. My WebView code is:

```
<WebView
  source={{ uri: file.uri }}
  startInLoadingState
  originWhitelist={['file://']}
  allowUniversalAccessFromFileURLs={true}
  allowFileAccess={true}
/>
```

On iOS, it works fine. However, on Android, it prints ERR_ACCESS_DENIED.
I've tried the solution put `renderOnce` state but it did not work for me.

Any other solution to solve my problem? Thanks, in advance. If you need more code to investigate, please let me know.

**Comment by lapico** [comment]
This worked with a local uri like this (only tested in dev) :

```
import {useAssets} from 'expo-asset';
import {Platform} from 'react-native';
import {WebView} from 'react-native-webview';
...
  const [assets] = useAssets([require('../../../assets/myhtml.html')]);
  const htmlAsset = assets?.[0];
...
      <WebView
        source={
          htmlAsset
            ? {
                uri:
                  Platform.OS === 'android'
                    ? htmlAsset.localUri
                    : htmlAsset.uri,
              }
            : undefined
        }
        onMessage={event => {
          console.log(JSON.parse(event.nativeEvent.data));
        }}
        startInLoadingState={true}
        originWhitelist={['*']}
        allowFileAccess={true}
        allowUniversalAccessFromFileURLs={true}
      />
...
```

Using expo-asset and this trick : https://github.com/react-native-webview/react-native-webview/issues/656#issuecomment-551312436

**Comment by developeromI89** [comment]
I am trying below but no luck

`render() {
    return (
        <View style={styles.container}>
          <WebView
            allowFileAccessFromFileURLs={true}
            allowFileAccess={true}
            bounces={false}
            scrollEnabled={false} 
            source={{ uri:"file:///android_asset/pdf/sample.pdf",baseUrl:"file:///android_asset/pdf/"}}
            />

        </View>
      );
    }
`
Any Suggestions?

**Comment by Shan7anu** [comment]
@developeromI89 if you only want to open PDFs you can use `'[react-native-view-pdf](https://www.npmjs.com/package/react-native-view-pdf)`'

Or you can use append your WebView url like this: 
`"https://docs.google.com/gview?embedded=true&url=$url"`

**Comment by judare** [comment]
> I use functional components and hooks and got the solution from @hsource to work by updating the `setRenderedOnce ` in a function that I pass to the webview's `onLoad` prop:
> 
> ```js
> const [renderedOnce, setRenderedOnce] = useState(false);
> 
> const updateSource = () => {
>     setRenderedOnce(true);
>  };
> 
> return(
>    <WebView
>        originWhitelist={['*']}
>        source={renderedOnce ? {uri: localHTML} : undefined}
>        style={{flex: 1}}
>        allowFileAccess={true}
>        allowUniversalAccessFromFileURLs={true}
>        onLoad={updateSource}
>    />)
> ```

For new versions, you have to change it for:

`source={renderedOnce ? {uri: localHTML} : { uri: null }}`

**Comment by meabed** [comment]
this still an issue - should be open.

**Comment by markalanevans** [comment]
I'm having a similar issue. 

We use react native and webview to a react web app. 

We get intermitted failures on file uploads on Android only.

So a user wants to change their headshot, by tapping the <inpu> element in the webview.
it pop up the media picker a file object is returned and then we try to uploaded it to our servers. But for the same file, over and over again, we get an error reading the file. But the error is not helpful its just an object that say { isTrusted: true }.

**Comment by kristensala** [comment]
> > I use functional components and hooks and got the solution from @hsource to work by updating the `setRenderedOnce ` in a function that I pass to the webview's `onLoad` prop:
> > ```js
> > const [renderedOnce, setRenderedOnce] = useState(false);
> > 
> > const updateSource = () => {
> >     setRenderedOnce(true);
> >  };
> > 
> > return(
> >    <WebView
> >        originWhitelist={['*']}
> >        source={renderedOnce ? {uri: localHTML} : undefined}
> >        style={{flex: 1}}
> >        allowFileAccess={true}
> >        allowUniversalAccessFromFileURLs={true}
> >        onLoad={updateSource}
> >    />)
> > ```
> 
> For new versions, you have to change it for:
> 
> `source={renderedOnce ? {uri: localHTML} : { uri: null }}`

This still threw me an error. It seem that the onLoad method does not get triggered
My solution was this:
`source={renderedOnce ? {uri: htmlPath}: {html: '<div></div>'}}`

First I render just and empty html (div) and then the onLoad gets triggered and then load the actual HTML

**Comment by YUOrz233** [comment]
> > > I use functional components and hooks and got the solution from [@hsource](https://github.com/hsource) to work by updating the `setRenderedOnce ` in a function that I pass to the webview's `onLoad` prop:
> > > const [renderedOnce, setRenderedOnce] = useState(false);
> > > 
> > > const updateSource = () => {
> > >     setRenderedOnce(true);
> > >  };
> > > 
> > > return(
> > >    <WebView
> > >        originWhitelist={['*']}
> > >        source={renderedOnce ? {uri: localHTML} : undefined}
> > >        style={{flex: 1}}
> > >        allowFileAccess={true}
> > >        allowUniversalAccessFromFileURLs={true}
> > >        onLoad={updateSource}
> > >    />)
> > 
> > 
> > For new versions, you have to change it for:
> > `source={renderedOnce ? {uri: localHTML} : { uri: null }}`
> 
> This still threw me an error. It seem that the onLoad method does not get triggered My solution was this: `source={renderedOnce ? {uri: htmlPath}: {html: '<div></div>'}}`
> 
> First I render just and empty html (div) and then the onLoad gets triggered and then load the actual HTML


`source={renderedOnce ? {uri: htmlPath}: {html: '<div></div>'}}`
This solution also avoids the situation where onLoad's `e.nativeEvent. canGoBack` is true when jumping to the local HTML homepage.


Because in my case, before jumping to the local HTML homepage, onLoad will first print "url: 'about: blank'"
`
{
    "canGoForward": false,
    "loading": false,
    "title": "data:text/html;charset=utf-8;base64,",
    "canGoBack": false,
    "url": "about:blank",
    "target": 997
}
`
Then, for the local HTML homepage , `e.nativeEvent. canGoBack` is true
`
{
    "canGoForward": false,
    "loading": false,
    "title": "xxx",
    "canGoBack": true,
    "url": "file:///data/user/0/xxx/files/xxx/index.html#/home",
    "target": 997
}
`
