### ISSUE TITLE
Uncaught TypeError: Cannot read property 'postMessage' of undefined     at test.php:8

### ISSUE THREAD

**Issue by mayursarode4** [react-native-community/react-native-webview#657]
Hi,
I'm getting error as **"Uncaught TypeError: Cannot read property 'postMessage' of undefined"**
when calling from url where the response is inside **php** as,
<html>
      <head></head>
      <body>
        <script>
                      window.ReactNativeWebView.postMessage("Hello!");
         </script>
      </body>
      </html>

**in RN:**
return ( <View style = {{flex: 1}} >
      <WebView source = {{uri: url/test.php}}
          startInLoadingState={true}
          onLoadStart={() => {console.log("LOAD START");}}
          onLoadEnd={() => {console.log("LOAD END ");}}
          onMessage = {
            event => {
              const { getData } = event.nativeEvent.data
              console.log('handle message : ', getData)
              alert(getData);
            }
          }
      /> 
</View>   );

Response:
**handle message :  undefined**

Error:
**Uncaught TypeError: Cannot read property 'postMessage' of undefined
    at test.php:8**

**Environment:**
 - react-native-cli: 2.0.1
 - react-native: 0.59.8
 - react-native-webview version: 5.10.0
 - react-native-gesture-handler: 1.2.2

**Comment by favrio** [comment]
Same issue here

**Comment by favrio** [comment]
Hi, i got into trouble with the same issue, finally i resolve this issue.
It's totally the window scope problem, plz make ensure you window is the window, so do not test this sdk in iframe(such as jsbin.com).

**Comment by mayursarode4** [comment]
> Hi, i got into trouble with the same issue, finally i resolve this issue.
> It's totally the window scope problem, plz make ensure you window is the window, so do not test this sdk in iframe(such as jsbin.com).

Means? can you show it some example!

**Comment by favrio** [comment]
```
const html = `

<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>JS Bin</title>
</head>
<body>
  <button id="btn">Test +1</button>
  
  <script>
    document.getElementById('btn').onclick = () => {
      window.ReactNativeWebView.postMessage('msg from the webview');
    }
  </script>
</body>
</html>
`

const App = () => {
  return (
    <SafeAreaView style={{ flex: 1 }}>
      <WebView
        style={{ height: 300, width: '100%' }}
        source={{ html: html }}
        onMessage={event => {
          console.log(event.nativeEvent.data)
        }}
      />
    </SafeAreaView>
  )
}

```

I just test the sample code by using `source` html props.

My env is 0.60.3,and the latest webview version.
