### ISSUE TITLE
onShouldStartLoadWithRequest and onMessage didn't work together in iOS

### ISSUE THREAD

**Issue by OvsTim** [react-native-community/react-native-webview#658]
Hello, i try to implement autoheight WebView with custom link handling. I forked old libriary and replaced old WebView with this WebView. My repo is here [https://github.com/OvsTim/react-native-webview-autoheight](url) and it's folly worked in Android.  Example code : 

    import AutoHeightWebView from 'react-native-webview-autoheight';
    ...some views here
    <AutoHeightWebView    
    originWhitelist={['*']}   
    source={{html: this.state.text}}   
    style={{ backgroundColor: "transparent"}}   
     />
    ...some views here

**Bug description:**
In iOS i can't use both onMessage and onShouldStartLoadWithRequest props. If i remove onShouldStartLoadWithRequest prop, it became autoheight, but i can't handle links my on html. and if i remove onMessage prop, it will be impossible to make it autoheight.

**To Reproduce:**
You can use my repo and code above, pass into this.state.text some html with links. it should work on Android, but if you try to make the same on iOS, you will get white screen(it maybe work when you open it first time and/or with debugger, but there are white screen in release) ((

**Expected behavior:**
It should work on both platforms the same way. 

**Environment:**
 - OS: Mac OS
 - OS version: Mojave 
 - react-native version:0.58.6
 - react-native-webview version:^5.11.0

**Comment by jsamr** [comment]
You can try webshell `useAutoheight` hook for that purpose https://formidable-webview.github.io/webshell/docs/autoheight
