### ISSUE TITLE
Loading a large image directly won't scale correctly

### ISSUE THREAD

**Issue by bobjflong** [react-native-community/react-native-webview#660]
**Bug description:**

When loading a large image directly, it appears impossible to scale it to fit the screen.

**To Reproduce:**

Given:

```javascript
const App = () => (
  <SafeAreaView>
    <View style={{ width: "100%", height: "100%" }}>
      <WebView
        scalesPageToFit
        source={{
          uri:
            "https://raw.githubusercontent.com/bobjflong/repro-scaling-bug/master/image.jpg",
        }}
      />
    </View>
  </SafeAreaView>
)
```

.. the image appears zoomed in, and the user cannot zoom out. There doesn't seem to be any way provided to change the scaling behavior.

I tried injecting javascript, to add a meta tag with scaling information. However this doesn't seem to work as it appears that the javascript won't be injected unless we are loading a bonafide HTML document.

I tried the `scalesPageToFit` prop and that also doesn't do it.

I also tried the `useWebkit` prop with no success.

**Expected behavior:**

I'd expect the default scaling to fit the image within the screen. This seems to happen by default in both https://github.com/naoufal/react-native-safari-view and https://github.com/CRAlpha/react-native-wkwebview

At the least, I'd expect the user to be able to zoom out and view the full image.

**Screenshots/Videos:**

Showing the zoomed behavior:

![webview](https://user-images.githubusercontent.com/2264896/59871190-ef298880-9364-11e9-8d57-cff810096baf.png)

For contrast, in `react-native-safari-view`:

![safari view](https://user-images.githubusercontent.com/2264896/59871328-51828900-9365-11e9-8d8b-950a2c8e65ca.png)

**Environment:**
 - OS: iOS
 - OS version: 12.3.1
 - react-native version: 0.59.0
 - react-native-webview version: 5.12.0

**Comment by rochapablo** [comment]
any update on this?

**Comment by bobjflong** [comment]
Still searching for solutions. We've moved to using `UIDocumentInteractionController` to view the images.
