### ISSUE TITLE
onload functions are not called (window.onload, image.onload)

### ISSUE THREAD

**Issue by allthetime** [react-native-community/react-native-webview#662]
Hi, I am loading a WebView like this:

     <WebView 
       style={{
         height: height,
         width: width,
       }}
       originWhitelist={['*']}
       javaScriptEnabled={true}
       source={ require('./canvas.html') }
     />

Where canvas.html is something like this:

    <html>
    <body>
       <script>

           alert('start script')

           window.onload = function(){ alert('page loaded') }

            var image = new Image();
            image.src = 'https://i.imgur.com/kIfWE05.jpg'
            image.onload = function(){ alert('image loaded') }

       </script>
    </body>
    </html>

Neither of these onload functions ever complete. But the first alert works meaning that the javascript is working in part. I can also load an image with a simple <img> tag so I know that is fine. It's just the onload event that never happens.

**Environment:**
 - OS: macOS
 - OS version: 10.14.5
 - react-native version:  0.59.9
 - react-native-webview version: ^5.12.0

**Comment by deepakverma4** [comment]
@allthetime i'm facing this issue too. how you resolved it?

**Comment by feliperugai** [comment]
Still having this issue.

**Comment by Atheane** [comment]
same here
