### ISSUE TITLE
something wrong while opening new tab

### ISSUE THREAD

**Issue by rawris** [react-native-community/react-native-webview#666]
Hi,
I have been trying to connect Razorpay checkout form in my web and for some reason whenever I click on Pay button the screen goes white. I'm guessing that target _blank is causing some problem.

Library version: ^5.12.0

Below You can find the code

```
<script src="https://checkout.razorpay.com/v1/checkout.js"></script>
<script>
    window.addEventListener('error', function(event) { 
      window.ReactNativeWebView.postMessage(JSON.stringify(event)); 
});
                                                var options = {
                                                    "key": "${rzr_key_id}",
                                                    "amount": ${this.state.shoppingOptions.amount},
                                                    "name": "${this.state.shoppingOptions.name}",
                                                    "description": "Purchase Description",
                                                    "prefill": {
                                                        "name": "${this.state.shoppingOptions.name}",
                                                        "email": "${this.state.shoppingOptions.email}",
                                                        "contact": "${this.state.shoppingOptions.phoneNumber}"
                                                    },
                                                    "theme": {
                                                        "color": "#fc9c04"
                                                    },
                                                    "handler": function (response){
                                                        alert('hello');
                                                        window.ReactNativeWebView.postMessage('payment id');
                                                    }
                                                };
                                                var rzp1 = new window.Razorpay(options);
                                                rzp1.open();
</script>
```

**Comment by kahunacohen** [comment]
I also see this. What happens at least in ios is that the link is no longer openable. The link just doesn't respond. I used a simple example:

`<a href="https://www.google.com">google</a>` which works.

If I put in `<a href="https://www.google.com" target="_blank">` the link simply doesn't work.

**Comment by kahunacohen** [comment]
This also happens in android.

**Comment by kahunacohen** [comment]
This seems like  https://github.com/react-native-community/react-native-webview/issues/139. Regression bug?

**Comment by fbaprojetos** [comment]
I'm using expo. When I click on a link that contains the "_blank" attribute, the expo simply stops running ...

**Comment by liam-mylo** [comment]
still searching for solutions

**Comment by indapublic** [comment]
Same

**Comment by nmarshCG** [comment]
I'm actually still experiencing this bug in iOS.

I opened up the pod and started poking around, none of the WKNavigationAction methods are invoked when clicking on these links, _except_ when incognito = true or cacheEnabled={false}.  Changing this setting seems to make these links work just fine.

This appears to be related to whether the app uses the nonPersistentDataStore - I can confirm that if I alter the pod to use that datastore the _blank links will work, but this solution doesn't work for us long term.
