### ISSUE TITLE
Website not available net::ERR_FAILED

### ISSUE THREAD

**Issue by balsloev** [react-native-community/react-native-webview#671]
**Bug description:**
The first time I open my app the website loads correctly in the WebView. Then I go to the homescreen and after a while I return to the app and gets the following error:

```
Website not available
The website at https://www.mydomain.com?param=value could not be loaded because:
net::ERR_FAILED
```

Has anyone seen this error before? 

Here is some logs from Android Studio that may or my not be related/useful.
```
2019-06-24 10:59:11.233 16101-16166/? W/cr_ChildProcLH: Create a new ChildConnectionAllocator with package name = com.android.chrome, sandboxed = true
2019-06-24 10:59:11.237 16101-16101/? I/cr_BrowserStartup: Initializing chromium process, singleProcess=false
2019-06-24 10:59:11.239 16101-16101/? W/ResourceType: Failure getting entry for 0x7f130537 (t=18 e=1335) (error -2147483647)

2019-06-24 10:59:11.241 16169-16169/? E//system/bin/webview_zygote32: failed to make and chown /acct/uid_99051: Permission denied
2019-06-24 10:59:11.241 16169-16169/? E/Zygote: createProcessGroup(99051, 0) failed: Permission denied

2019-06-24 10:59:11.244 16169-16169/? W//system/bin/webview_zygote32: Using default instruction set features for ARM CPU variant (cortex-a9) using conservative defaults
2019-06-24 10:59:11.248 1700-6616/? I/ActivityManager: Start proc 16169:com.android.chrome:sandboxed_process0/u0i51 for webview_service dk.MYAPPNAME.app/org.chromium.content.app.SandboxedProcessService0
2019-06-24 10:59:11.264 1991-1991/? I/chatty: uid=10016(u0_a16) com.android.systemui identical 1 line
2019-06-24 10:59:11.265 16169-16169/? I/SamplingProfilerIntegration: Profiling disabled.
2019-06-24 10:59:11.289 16197-16197/? E/asset: setgid: Operation not permitted
```

**To Reproduce:**
I have only been able to reproduce this error in release - not in debug. This error happens after loading the app the first time, then leaving it and return to the app after a few hours. 
Maybe it is related to cache. 

The problem persist when I force quit the app. If I reinstall the app it is working for a while. 
This URL is loading fine in the phones native browser (Google Chrome).

**Expected behavior:**
Website should fully load. 

**Screenshots/Videos:**
![error](https://user-images.githubusercontent.com/6825080/59999797-25b41b80-9663-11e9-83aa-c9a3ea2676f9.jpg)

**Environment:**
 - OS: Android (Huawei P20 Pro and multiple other Android phones)
 - OS version: Android 8
 - Browser: Google Chrome 75.0.3770.101 (code 377010137) 
 - react-native version: 59.3
 - react-native-webview version: 5.6.2

**Comment by hkanizawa** [comment]
I'm facing the exact same problem using the "react-native-webview-bridge".

The behavior is exactly the same and started to happen in production apps that were working fine for months.

I guess it may be related to an Android's Google Chrome update, but I can't found yet.

Actually, this problem started last week and I thought I had fixed by changing the cache configuration in my website's service worker file, but yesterday it comes back.

I had more than 50 customer's apps with this problem. 😬

**Comment by balsloev** [comment]
> Actually, this problem started last week and I thought I had fixed by changing the cache configuration in my website's service worker file, but yesterday it comes back.

Are you loading a PWA-website inside the WebView. If so, what framework is it using?

**Comment by hkanizawa** [comment]
My PWA-website doesn't use any framework. It was developed just using JS, and jQuery on the front-end.

**Comment by balsloev** [comment]
@hkanizawa Google Chrome 74 made [some changes](https://developers.google.com/web/updates/2019/03/nic73#pwas-everywhere) to PWA support in the latest release. I'm not sure if it is related.

**Comment by hkanizawa** [comment]
@balsloev I've removed the serviceworker.js file when my website is accessing by React Native and clean my CDN cache.

It seems solved here, let's see if my customers stop complain.

**Comment by balsloev** [comment]
@hkanizawa [okay I found a fix](https://github.com/vuejs-templates/webpack/issues/446#issuecomment-278503745) for this issue!

It looks like a broken service worker stalled the website. 
I solved it by using the [injectedJavascript](https://github.com/react-native-community/react-native-webview/blob/master/docs/Guide.md#the-injectedjavascript-prop) prop in my WebView to inject the follow lines of code:
```
navigator.serviceWorker.getRegistrations().then(function(registrations) {
   for (let registration of registrations) {
       registration.unregister();
   }
});
```
I will deploy to production now and see if it solves the issue for my customers.

**Comment by rakshans1** [comment]
This happened with chrome 75 release.

https://bugs.chromium.org/p/chromium/issues/detail?id=977784

**Comment by balsloev** [comment]
The client decided to skip this fix and wait for the Google Chrome patch to roll out in the coming days.
I will close the issue.

**Comment by arwindraj** [comment]
@balsloev is your temporary fix working?

**Comment by arunreenamohan-creator** [comment]
> @hkanizawa [okay I found a temporary fix](https://github.com/vuejs-templates/webpack/issues/446#issuecomment-278503745) for this issue!
> 
> It looks like a broken service worker stalled the website.
> I solved it by using the [injectedJavascript](https://github.com/react-native-community/react-native-webview/blob/master/docs/Guide.md#the-injectedjavascript-prop) prop in my WebView to inject the following lines of code:
> 
> ```js
> navigator.serviceWorker.getRegistrations().then(function(registrations) {
>    for (let registration of registrations) {
>        registration.unregister();
>    }
> });
> ```
> 
> I will deploy to production now and see if it solves the issue for our customers as well.

where is to place this code in react native

**Comment by arunreenamohan-creator** [comment]
> @hkanizawa [okay I found a temporary fix](https://github.com/vuejs-templates/webpack/issues/446#issuecomment-278503745) for this issue!
> 
> It looks like a broken service worker stalled the website.
> I solved it by using the [injectedJavascript](https://github.com/react-native-community/react-native-webview/blob/master/docs/Guide.md#the-injectedjavascript-prop) prop in my WebView to inject the following lines of code:
> 
> ```js
> navigator.serviceWorker.getRegistrations().then(function(registrations) {
>    for (let registration of registrations) {
>        registration.unregister();
>    }
> });
> ```
> 
> I will deploy to production now and see if it solves the issue for our customers as well.

where is to place this code.. pls help me..

**Comment by Asad520** [comment]
Facing the same issue in the production environment.
Was anybody able to fix it somehow?

**Comment by KambleSudhirSejal** [comment]
I am facing the same issue  of net::ERR_FAILED

ERROR:socket_posix.cc(93)] CreatePlatformSocket() failed: Machine is not on the network (64)
2024-06-11 13:25:21.875  9850-10623 chromium                com.example.fitizenproject           W  [WARNING:net_errors_posix.cc(127)] Unknown error Machine is not on the network (64) mapped to net::ERR_FAILED
2024-06-11 13:25:21.898  9850-10008 VRI[DashBoardActivity]  com.example.fitizenproject           D  Received frameCommittedCallback lastAttemptedDrawFrameNum=1 didProduceBuffer=true syncBuffer=false
2024-06-11 13:25:21.900  9850-10008 Parcel                  com.example.fitizenproject           W  Expecting binder but got null!
2024-06-11 13:25:21.900  9850-9850  VRI[DashBoardActivity]  com.example.fitizenproject           D  draw finished.
2024-06-11 13:25:21.933  9850-9850  Quality                 com.example.fitizenproject           I  Skipped: false 5 cost 89.530975 refreshRate 16597652 bit true processName com.example.fitizenproject
2024-06-11 13:25:21.963  9850-9850  WebView                 com.example.fitizenproject           E  Failed to load URL: net::ERR_FAILED 

This error is shown in my  Android studio logcat

**Comment by jmarquezruiz** [comment]
#//

> > [@hkanizawa](https://github.com/hkanizawa) [okay I found a temporary fix](https://github.com/vuejs-templates/webpack/issues/446#issuecomment-278503745) for this issue!
> > It looks like a broken service worker stalled the website.
> > I solved it by using the [injectedJavascript](https://github.com/react-native-community/react-native-webview/blob/master/docs/Guide.md#the-injectedjavascript-prop) prop in my WebView to inject the following lines of code:
> > navigator.serviceWorker.getRegistrations().then(function(registrations) {
> >    for (let registration of registrations) {
> >        registration.unregister();
> >    }
> > });
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I will deploy to production now and see if it solves the issue for our customers as well.
> 
> where is to place this code.. pls help me..

const injectScript = `
    document.querySelectorAll("video").forEach(video => {
      video.removeAttribute("controls");
      video.setAttribute("playsinline", "true");
    });

    // Unregister service workers
    navigator.serviceWorker.getRegistrations().then(function(registrations) {
     for (let registration of registrations) {
       registration.unregister();
     }
    });
  `;

  To inject js in react native webview you can create a const inside the component and then pass like a propto the webview like this:
`const injectScript = `
    document.querySelectorAll("video").forEach(video => {
      video.removeAttribute("controls");
      video.setAttribute("playsinline", "true");
    });

    // Unregister service workers
    navigator.serviceWorker.getRegistrations().then(function(registrations) {
     for (let registration of registrations) {
       registration.unregister();
     }
    });
  `;

  return (
    <SafeAreaView style={styles.safeContainer}>
      <View style={styles.container}>
        {
          app.safeMode ?
            <StatusBar backgroundColor='transparent' /> : null
        }

        <StatusBar backgroundColor='auto' />

        <WebView
          androidLayerType='hardware'
          ref={webViewRef}
          source={{ uri: app.uri }}
          style={styles.webview}
          onLoad={() => getCurrentUrl()}
          onMessage={handleWebViewMessage}
          allowsInlineMediaPlayback={true}
          injectedJavaScript={injectScript}
        />
      </View>
    </SafeAreaView>
  );`
