### ISSUE TITLE
Would tbs be supported?

### ISSUE THREAD

**Issue by taoqf** [react-native-community/react-native-webview#675]
**Is your feature request related to a problem? If so, Please describe.**

Webview could not run under android version 5, it has some compatibility issues. even some doesn't support es6.

**Describe the solutions you came up with**

Is it possible to add [tbs](https://x5.tencent.com/tbs/index.html) as an option?

**Additional context**

**Comment by domingowensnsoft** [comment]
I think the community will consider add TBS services, because webview used in china has something problem in xiaomi oppo vivo

**Comment by taoqf** [comment]
Seeking for help.
