### ISSUE TITLE
Missing repo tags

### ISSUE THREAD

**Issue by happy-thorny** [react-native-community/react-native-webview#682]
**Bug description:**

After #680 will be fixed a new `pod install` error will occur: `fatal: Remote branch v5.11.0 not found in upstream origin`. This happens because CocoaPods downloads specified tag sources from this repo during pods installation and this repo does not have tags for v5.12.0, v5.11.0, v5.10.0 and v5.9.1. Please make tags for these versions.

**To Reproduce:**

Same as for #680

**Expected behavior:**

No error occurred

**Environment:**
 - OS: any
 - OS version: any
 - react-native version: any
 - react-native-webview version: 5.11.0 for example

**Comment by Titozzz** [comment]
alright thanks
