### ISSUE TITLE
'React/RCTView.h' file not found after upgrading to RN 0.58.9

### ISSUE THREAD

**Issue by ndejesus1227** [react-native-community/react-native-webview#683]
**Bug description:**

I had no issues with webview until I upgraded to Rn 0.58.9. I've tried removing with yarn, unlinking/linking, cleaning builds from Xcode. I always get the same thing.

**Expected behavior:**

Build successfully

**Environment:**
React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
      Memory: 501.47 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.5.0 - ~/.nvm/versions/node/v10.5.0/bin/node
      Yarn: 1.10.1 - ~/.nvm/versions/node/v10.5.0/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.5.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 23.0.1, 23.0.2, 23.0.3, 25.0.2, 26.0.2, 26.0.3, 27.0.3, 28.0.3
        System Images: android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64, android-26 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.8 => 0.59.8 
    npmGlobalPackages:
      react-native-git-upgrade: 0.2.7
      react-native-rename: 2.2.2

**Comment by turkle12** [comment]
Hi, I'm getting the same error. 
I installed using yarn and linked but came across the error `Invariant Violation: requireNativeComponent: "RNCWKWebView" was not found in the UIManager.`. 

I manually added the RNCWKWebView.xcodeproj to the XCode Libraries and now I've run into this problem.

**Comment by turkle12** [comment]
It looks like the issue was fixed by running CMD + Option + Shift + K instead of the `Clean build folder` option in the XCode window

**Comment by tapz** [comment]
Can't find the xcodeproj file in node_module. So nothing to manually add to my Xcode project. Why doesn't yarn fetch the file?

**Comment by mayu3c** [comment]
@tapz @ndejesus1227 i had similar issue with RN v0.59.10. pod install has some issue with the latest RN version.
So i manually added(drag n drop) RNCWebView.xcodeproj inside the xcode Library folder. then it compiles.Hope it helps .

**Comment by ndejesus1227** [comment]
I pretty much did what @mayu3c said, thank you

**Comment by dolphin6868** [comment]
> Hi, I'm getting the same error.
> I installed using yarn and linked but came across the error `Invariant Violation: requireNativeComponent: "RNCWKWebView" was not found in the UIManager.`.
> 
> I manually added the RNCWKWebView.xcodeproj to the XCode Libraries and now I've run into this problem.
> 
> Has there been a fix?

I am getting the same error in react-native 0.61.5 and react-native-webview 8.0.1.Please help !!
