### ISSUE TITLE
Randomly crash and slow response onMessage in non-debug mode

### ISSUE THREAD

**Issue by ilotte99** [react-native-community/react-native-webview#685]
Hi, I am using this react native webview and make navigation between webview page and react native page using postMessage and onMessage method. They are working great in debug mode. However, in the non-debug mode and released apk, they perform really slow takes around 15-20 second (compared to debug mode that only takes time less than 1 second) and also sometimes it doesn't work and make app crash. I have read some issues about onMessage methods in debug mode and try do some stuff but it still doesn't work. Please help and fix this bug.

This is my webview code
```
<WebView
          style={{ flex: 1 }}
          source={{
            uri: this.state.uri
          }}
          injectedJavaScript={injectHTML}
          ref={r => (this.webref = r)}
          originWhitelist={["*"]}
          useWebKit={true}
          domStorageEnabled={true}
          javaScriptEnabled={true}
          allowUniversalAccessFromFileURLs={true}
          sharedCookiesEnabled={true}
          thirdPartyCookiesEnabled={true}
          allowFileAccess={true}
          onMessage={event => {
            console.log(event);
            alert(event);
            if (event.nativeEvent.data === "Setting") {
              this.props.navigation.navigate("Setting");
            } else if (event.nativeEvent.data === "PushNotification") {
              this.props.navigation.navigate("PushNotification");
            }
          }} />
```

Post message methods:
`window.ReactNativeWebView.postMessage(\"PushNotification\")`

**Environment:**
 - OS: Android
 - OS version: 7.0
 - react-native version: "0.59.8"
 - react-native-webview version: "^6.3.0"

**Comment by zaixiaoqu** [comment]
Hello, I have the same question. Have you solved it?

**Comment by NeliHarbuzava** [comment]
I am subscribing to this, have the same

**Comment by sandeepsukumaran** [comment]
Does removing `console.log(event)` inside `onMessage` help? That did the trick for me. Found [here](https://github.com/react-native-community/react-native-webview/issues/593#issuecomment-525157815).

**Comment by westerly** [comment]
Thanks much @sandeepsukumaran I had a `console.log(event)` inside `onLoadStart`. After I removed it, things started to work properly.
