### ISSUE TITLE
Html containing reference js and css files is not loaded correctly in ios debug mode,erro like "MIME types are not allowed when 'X-Content-Type: nosniff' is given"

### ISSUE THREAD

**Issue by Ruanyang2015** [react-native-community/react-native-webview#686]
**Bug description:**

**To Reproduce:**
In debug mode, I introduced a local html file on the ios emulator, which loads html well, but the css and js files referenced in the html file are not loaded correctly, and this error is reported.:
**[Error] Did not load script at 'http://localhost:8081/assets/src/RichTextEditor/jquery-3.1.1.min.js' because non script MIME types are not allowed when 'X-Content-Type: nosniff' is given.**

**Expected behavior:**
Expect it to load test.js correctly;
![image](https://user-images.githubusercontent.com/13889247/60311992-1fd47800-998c-11e9-9a2d-8d83a2bdfa8d.png)

**Screenshots/Videos:**

![image](https://user-images.githubusercontent.com/13889247/60311699-fe26c100-998a-11e9-80b2-abdfa4f788c4.png)

![image](https://user-images.githubusercontent.com/13889247/60311875-a89ee400-998b-11e9-8027-0a48f9e0f2c2.png)

![image](https://user-images.githubusercontent.com/13889247/60311674-e3ece300-998a-11e9-9e92-6e0c8bdbf957.png)

**Environment:**
 - OS:ios
 - OS version:10.0
 - react-version: "6.8.3,
 - react-native: 0.59.9,
 - react-native-webview: ^5.12.0

**Comment by MaxToyberman** [comment]
@Ruanyang2015 did you find a solution ? my solution was to injectJavaScript

**Comment by MaxToyberman** [comment]
@Ruanyang2015  My solution was to bundle the js and css and put it in the <script></script> and <style></style>
scripts accordingly.

**Comment by leonardobaggio** [comment]
still happening

**Comment by leonardobaggio** [comment]
lol I just got ignored by the bot. this issue should not be closed as it has not been resolved.
