### ISSUE TITLE
iOS: possibility to (pre)render off screen webviews

### ISSUE THREAD

**Issue by Liestambeur** [react-native-community/react-native-webview#696]
Hi,

Use case: a swiper with X WebViews.

When having multiple WebViews in a swiper, swiping to the next WebView results in a flicker since the next WebView is not loaded/rendered yet.
This is not the case in the 'old' WebView of react-native (https://facebook.github.io/react-native/docs/webview).
I understand that this is a good optimisation but shouldn't this be an option? since in some use-cases it might be useful that the content is already loaded.

I investigated already a bit and the method "didMoveToWindow" is only called once the WebView starts to be on screen. This is triggered by the "addSubview" method in "react_updateClippedSubviewsWithClipRect".

Lies

**Comment by adimshev** [comment]
+1

**Comment by goleary** [comment]
I'm curious if y'all have come up with any workarounds for this?  Also, @Liestambeur why did you close out this request?  I'd love this.

The behavior of the webview differs between iOS & Android (where the `WebView` will load even if it's off screen).  It would be great if developers could decide whether they want the content to load when it's offscreen.
