### ISSUE TITLE
ReactNativeWebView gets renamed as ReactABI33_0_0NativeWebView

### ISSUE THREAD

**Issue by rakibtg** [react-native-community/react-native-webview#699]
In iPhone* simulators the `window.ReactNativeWebView` will be renamed as `window.ReactABI33_0_0NativeWebView`! So `window.ReactNativeWebView.postMessage` is undefined but `window.ReactABI33_0_0NativeWebView.postMessage` works as expected.

<img width="1112" alt="Screenshot 2019-07-05 at 10 47 17 AM" src="https://user-images.githubusercontent.com/5412730/60698703-80c2f980-9f12-11e9-9193-505e9bab9790.png">

Am i missing something? This is my code took from the example:

```
import React, { Component } from 'react';
import { View } from 'react-native';
import { WebView } from 'react-native-webview';

export default class App extends Component {
  render() {
    const html = `
      <html>
      <head></head>
      <body>
        <script>
          setTimeout(function () {
            window.ReactNativeWebView.postMessage("Hello!")
          }, 2000)
        </script>
      </body>
      </html>
    `;

    return (
      <View style={{ flex: 1 }}>
        <WebView
          source={{ html }}
          onMessage={event => {
            alert(event.nativeEvent.data);
          }}
        />
      </View>
    );
  }
}
```

**Environment:**
 - OS: macOS Mojave
 - OS version: Mac 10.14.3
 - react-native version: sdk-33.0.0
 - react-native-webview version: expo-sdk-33.0.0

**Comment by brentvatne** [comment]
this is resolved in the expo client on device and will ship on our next simulator update :) sorry for the hassle

here's a temporary workaround: https://github.com/expo/expo/issues/4463#issuecomment-499743757

**Comment by n-sviridenko** [comment]
@rakibtg thanks for highlighting this issue!
