### ISSUE TITLE
MIGRATED: Webview is not executing my JavaScript from the web page on Android? (#14754)

### ISSUE THREAD

**Issue by jamonholmgren** [react-native-community/react-native-webview#7]
MIgrated from https://github.com/facebook/react-native/issues/14754

@andrisole92 says:

---

Description
When I open WebView on Android emulator or real device it does not execute JavaScript. I have run simple Android App in Android Studio and it worked there.

Reproduction Steps
Just create a new app and add this WebView to it

Sample Code

```jsx
<WebView
  style={[styles.flex]} //styles
  javaScriptEnabled={true} //enabling JavaScript
  source={{uri: 'http://partners.zeew.eu/'}} //Url
/>
```

Solution
Can you please check it and say what is wrong?

Additional Information
React Native version: 0.45.1
Platform: Android ( not sure about iOS )
Development Operating System: Windows
Build tools: Android Studio: Nexus 5x edited_api_25 Android 6.0 Google APIs, Nexus 5 API level 26, Android 8.0.0

---

_More info on the original issue thread_

**Comment by ChenLi0830** [comment]
@jamonholmgren ios simulator? The author of the issue reported **Android**

**Comment by m1m6** [comment]
same here

**Comment by ignasirv** [comment]
Reopen please, the issue is with Android

**Comment by ZeeshanAhmadKhalil** [comment]
I am having the same issue and i have only 2 days in my Final Year Project internal presentation.

**Comment by ramisalem** [comment]
any soluations for this issue?
