### ISSUE TITLE
[Android] history.length 0 if userAgent is set on Android

### ISSUE THREAD

**Issue by defghy** [react-native-community/react-native-webview#700]
**Bug description:**
When set `userAgent` in Android, `window.history.length` is 0. 
Then jump to 2nd page, `history.length` change to 1. 
At this time `history.go(-1)` not work.
Try some other url make same result.

if I delete `userAgent`, everything is ok.

**To Reproduce:**
```
          <WebView
            ref={(view) => { this.webView = view }}
            automaticallyAdjustContentInsets
            source={{ uri: this.webUrl }}
            userAgent={`myrn`}
          />
```

**Screenshots/Videos:**
![image](https://user-images.githubusercontent.com/5386958/60755312-89095a80-a020-11e9-8167-d957b8e5b4da.png)

**Expected behavior:**
`history.length` should be 1 when open initial page

**Environment:**
 - OS: Android
 - OS version: 6.0.1
 - react-native version: 0.59.9
 - react-native-webview version: 6.3.1

**Comment by manhn96** [comment]
Did you find a solution for this ?
I'm facing the same problem as you do

**Comment by defghy** [comment]
> Did you find a solution for this ?
> I'm facing the same problem as you do

Use search parameter instead of userAgent to detect env
like this
`
https://aaa.com?platform=mall
`

**Comment by caigehui** [comment]
same issue here, any solution?

**Comment by caigehui** [comment]
> > Did you find a solution for this ?
> > I'm facing the same problem as you do
> 
> Use search parameter instead of userAgent to detect env
> like this
> `https://aaa.com?platform=mall`

use `userAgent` instead of `applicationNameForUserAgent`, it works for me

**Comment by SliverYuki** [comment]
> > > Did you find a solution for this ?
> > > I'm facing the same problem as you do
> > 
> > 
> > Use search parameter instead of userAgent to detect env
> > like this
> > `https://aaa.com?platform=mall`
> 
> use `userAgent` instead of `applicationNameForUserAgent`, it works for me

Excuse me, did you mean to use `applicationNameForUserAgent`？
