### ISSUE TITLE
After one hour  in the background, return to the front desk, WKWebview displays a blank screen

### ISSUE THREAD

**Issue by bashen1** [react-native-community/react-native-webview#701]
**Bug description:**

After one hour  in the background, return to the front desk, WKWebview displays a blank screen。

According to this article, it should be that the rendering process of wkwebview crashes.

[https://www.jianshu.com/p/de67f5a752b6](https://www.jianshu.com/p/de67f5a752b6)

**To Reproduce:**

**Expected behavior:**

**Screenshots/Videos:**

**Environment:**
 - OS: iOS
 - OS version: 12.3.1
 - react-native version: 0.59.9
 - react-native-webview version: 5.12.1

**Comment by kefyru** [comment]
The same problem on rn 0.60.5, web-view 7.0.2

**Comment by vnitMendapara** [comment]
Any one found solution? I have same problem.

**Comment by alessandro-bottamedi** [comment]
Same problem with rn 0.61.5 and react-native-webview 8.2.1 on iOS

**Comment by alancwoo** [comment]
I'm also experiencing the same issue:

```
"react-native": "0.63.1",
"react-native-webview": "^10.3.2"
```

Returning to the app after some time, the webview will be empty until a refresh.

**Comment by Cigan12** [comment]
Same issue:
