### ISSUE TITLE
when I post message (window.location) Not getting nativeEvent other data in  Android platform both Emulator and hardware devices.

### ISSUE THREAD

**Issue by devudr** [react-native-community/react-native-webview#702]
**Bug description:**
when I post message (window.location) Not getting nativeEvent and other data in  Android platform both Emulator and hardware devices.

**To Reproduce:**
const INJECTED_JAVASCRIPT = `(function() {
    window.ReactNativeWebView.postMessage(JSON.stringify(window.location));
})();`;

<WebView
  source={{ uri: 'https://facebook.github.io/react-native' }}
  injectedJavaScript={INJECTED_JAVASCRIPT}
  onMessage={this.onMessage}
/>

onMessage = (e) => {
 console.log(e.nativeEvent)
}

**Expected behavior:**

**Environment:**
 - OS:Android
 - OS version:8.0
 - react-native version:0.59.5
 - react-native-webview version:5.12.1

**Comment by phatnextfunc** [comment]
Yes, I have a similar case.
onMessage did not triggering in release mode but worked in debug mode
Could someone help me please?

**Comment by huynguyen2903** [comment]
The same problem. Did anyone know how to solve this?

**Comment by Mr-nan** [comment]
The same problem. Did anyone know how to solve this?

**Comment by renguixin** [comment]
The same problem. Did anyone know how to solve this?

**Comment by adophper** [comment]
same problem,ios is good.
