### ISSUE TITLE
have nestedScrollEnabled like scrollview

### ISSUE THREAD

**Issue by neilzhengzx** [react-native-community/react-native-webview#710]
sometimes, webView will be in a scroll view. but now webView can not scroll when in a scroll view.
android WebView has do it  just add one line in class file
```
mWebview.setNestedScrollingEnabled(true);
```
in ios ,webView always can scroll when in a scroll view.
Can react-native-webview suppot it?

**Comment by GH974** [comment]
Hi, do you have a solution?

**Comment by neilzhengzx** [comment]
not have. i want  react-native-webview suppot it.

**Comment by NameNull** [comment]
the same suggestion, or the other solution?

**Comment by neilzhengzx** [comment]
I find the lastest release resloved this question. Waiting for release.

**Comment by neilzhengzx** [comment]
i test the  lastest release, not reslove the question.

**Comment by hkar19** [comment]
Hi, does this one have solution yet?

**Comment by krlosgomez** [comment]
Hi, open this, it need a solution.
