### ISSUE TITLE
PDF File View on Android

### ISSUE THREAD

**Issue by fuzunspm** [react-native-community/react-native-webview#714]
**Is your feature request related to a problem? If so, Please describe.**

On iOS it can preview/display pdf files but on Android it downloads the file for links end with .pdf. Having an option to choose could be very useful

**Comment by MaximMatsuk** [comment]
@fuzunspm May be you know how download pdfs on ios? More information in this issue https://github.com/react-native-community/react-native-webview/issues/729

**Comment by shahen94** [comment]
+ Any progress on this?

**Comment by leeprobert** [comment]
+1 I need to render a PDF either from a local file or from a URL.

**Comment by dungnguyentri3110** [comment]
any solution else??

**Comment by Atuldhaka** [comment]
Not able to view the pdf on android please give a workaround for that.
