### ISSUE TITLE
React native iOS webview app reload on photo upload through camera or gallery useWebKit={true}

### ISSUE THREAD

**Issue by viv3kk** [react-native-community/react-native-webview#72]
Environment
React Native Environment Info:
System:
OS: macOS High Sierra 10.13.6
CPU: x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
Memory: 1.61 GB / 16.00 GB
Shell: 3.2.57 - /bin/bash
Binaries:
Node: 10.6.0 - /usr/local/bin/node
npm: 6.4.1 - /usr/local/bin/npm
Watchman: 4.9.0 - /usr/local/bin/watchman
SDKs:
iOS SDK:
Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
IDEs:
Android Studio: 2.3 AI-162.4069837
Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
npmPackages:
react: 16.5.0 => 16.5.0
react-native: 0.57.2 => 0.57.2
npmGlobalPackages:
create-react-native-app: 1.0.0
react-native-cli: 2.0.1

Iphone 6 physical device and simulators
RN: 0.57.2

Description
React native iOS webview app reload on photo upload through camera or gallery.

When trying to upload photo the webview screen reload to the base url. The same is is working for RN 0.56.

I am using webview with `useWebKit={true}`

```
<WebView
                  useWebKit={true}
                  ref={r => this.webview = r}
                  javaScriptEnabled={true}
                  source={{uri:uri_source}}
                  onMessage={this.msgHandler.bind(this)}
                  onNavigationStateChange={this.onNavigationStateChange.bind(this)}
                  onLoadEnd={this.onLoadEnd.bind(this)}
                  onLoadStart={this.onLoadStart.bind(this)}
                  onError={this.onErrorLoad_Webview.bind(this)}
                  domStorageEnabled={true}
                  startInLoadingState={true}
                  mixedContentMode={'compatibility'}
                  mediaPlaybackRequiresUserAction={true}
                  allowUniversalAccessFromFileURLs={true}
                  //renderLoading={this.renderLoading.bind(this)}
                  //scalesPageToFit={true}
              />
```

**Comment by Titozzz** [comment]
Hello, If you want to submit a pull request, i'd be happy to review

**Comment by fangasvsass** [comment]
WKWebview only

**Comment by fangasvsass** [comment]
on WKWebview screen alert react-native modal  WKWebview will reload

**Comment by garrettm** [comment]
I'm also seeing this issue

**Comment by garrettm** [comment]
Sometimes it even appears that the webview content is rendered twice

**Comment by NeilChan** [comment]
I think it is the same problem with this.
https://github.com/react-native-community/react-native-webview/issues/81#issue-370428707

**Comment by Titozzz** [comment]
I agree @NeilChan

**Comment by SeokHoBu** [comment]
I write version 6.0.2 and the same issue arises. Is it fixed? @Titozzz

**Comment by appify-waheed** [comment]
I am still facing this issue with version `8.1.2` on `IPad 13.3.1` version

**Comment by JamboProduction** [comment]
Me too but on Android. I am still facing this issue with react-native-webview version `11.6.6` on `Android 11` and react-native version `0.63.4` I am using. Any solution of this?
