### ISSUE TITLE
[ios] specifying originWhitelist to ['http://.*', 'https://.*'] jumps to browser

### ISSUE THREAD

**Issue by jayshah123** [react-native-community/react-native-webview#724]
**Bug description:**

When specifying prop in WebView:
```
          originWhitelist={['http://.*', 'https://.*']}
```
The webview directly opens the site in the browser in IOS.
Works fine in android.

**To Reproduce:**
Specify origin whitelist as above in your webview prop.

**Expected behavior:**
WebView should stay and open the web page.

**Screenshots/Videos:**
WIll add soon.

**Environment:**
 - OS: Mac OS High sierra
 - OS version:
 - react-native version: 0.59.8
 - react-native-webview version: 5.12.1

**Comment by imsantoshyadav** [comment]
@jayshah123 have you found out any solution for this issue

**Comment by jayshah123** [comment]
Nope

**Comment by asrytis** [comment]
`originWhitelist={['http://*', 'https://*']}` 👈 this worked for me on both iOS & Android (RN 0.59.9). Note the absence of `.`

**Comment by Ibrahimkara92** [comment]
I solved the problem
In the node modules file we open the apple file inside the react-native-webwiew file and open RNCWebView.m
We need to make some additions here
if (_onShouldStartLoadWithRequest) {
NSMutableDictionary<NSString *, id> *event = [self baseEvent];
[event addEntriesFromDictionary: @{
@"url": (request.URL).absoluteString,
@"mainDocumentURL": (request.mainDocumentURL).absoluteString,
@"navigationType": navigationTypes[@(navigationType)]
}];
if (![self.delegate webView:self
shouldStartLoadForRequest:event
withCallback:_onShouldStartLoadWithRequest]) {
decisionHandler(WKNavigationActionPolicyCancel);
return;
}
}

such lines
if (_onShouldStartLoadWithRequest) {
NSMutableDictionary<NSString *, id> *event = [self baseEvent];
[event addEntriesFromDictionary: @{
@"url": (request.URL).absoluteString,
@"mainDocumentURL": (request.mainDocumentURL).absoluteString,
@"navigationType": navigationTypes[@(navigationType)]
}];
if (!navigationAction.targetFrame.isMainFrame){
decisionHandler(WKNavigationActionPolicyAllow);
return;
}
if (![self.delegate webView:self
shouldStartLoadForRequest:event
withCallback:_onShouldStartLoadWithRequest]) {
decisionHandler(WKNavigationActionPolicyCancel);
return;
}
}
we have to change it this way
