### ISSUE TITLE
Build failure on Android. Build success on iOS.

### ISSUE THREAD

**Issue by gabriellim** [react-native-community/react-native-webview#725]
**Bug description:**
Hi react-native-community,
- I am unable to build my react-native app on Android but it is working on iOS.
- This is the error:

> FAILURE: Build failed with an exception.
What went wrong:
Could not determine the dependencies of task ':app:lintVitalStagingrelease'.
> Could not resolve all task dependencies for configuration ':app:stagingreleaseRuntimeClasspath'.
   > Could not resolve project :react-native-webview.
     Required by:
         project :app
      > Could not select value from candidates [null, debug, release] using AlternateDisambiguationRule.BuildTypeRule.
         > java.lang.NullPointerException (no error message)

I have read other bug reports, some suggest updating my RN version to 57 or 58 but I would like to avoid potential breaking changes unless the upgrade is critical.

I have also removed node modules, reinstalled them with `npm ci` and ran `react-native link`

**Environment:**
 - OS: macOS
 - OS version: 10.13.6
 - react-native version: 0.56.0
 - react-native-webview version: 5.12.1

**Comment by hannojg** [comment]
We receive the same error when trying to build our project in CI.

**Comment by gabriellim** [comment]
Help, please. @Titozzz @jamonholmgren @StephenGrider

**Comment by eliaslecomte** [comment]
We had the same problem yesterday using react-native-webview 5.12.1 and react-native 57.

_I strongly believe react native libraries should not use kotlin as this complicates usage for apps that do not use kotlin (most of them, as they are building apps in javascript..) as this is the main reason why integrating fails._

I was able to integrate the lib with the following changes:

1. Add kotlinVersion to android/build.gradle kotlinVersion = '1.3.41' (android/build.gradle)

`buildscript {
     ext {
         buildToolsVersion = "27.0.3"
         minSdkVersion = 21
         compileSdkVersion = 27
         targetSdkVersion = 27
         supportLibVersion = "27.1.1"
         **kotlinVersion = '1.3.41'**
     }
}`

2. Add kotlin gradle plugin (android/build.gradle)

`buildscript {
    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.0'
    }
}`

3. Add matchingFallback to non debug build types (android/app/build.gradle)

`android {
    buildTypes: {
        client: {
            matchingFallbacks = ['client', 'debug']
        }
        release: {
            matchingFallbacks = ['release', 'debug']
        }
    }
}`


Note: I am using:
* gradle wrapper 4.10.1 (distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.1-all.zip in gradle-wrapper.properties)
* build tools 27.0.3 (buildScript.ext.buildToolsVersion = '27.0.3' in build.gradle)
* gradle 3.3.0 (buildscript.dependencies { classpath 'com.android.tools.build:gradle:3.3.0' } in build.gradle)
