### ISSUE TITLE
Get LocalStorage from WebView

### ISSUE THREAD

**Issue by fernandomatheus** [react-native-community/react-native-webview#73]
Is there any way to get localStorage/sessionStorage itens from `<WebView />` loaded site ?

**Comment by jamonholmgren** [comment]
@fernandomatheus Got what you needed here?

**Comment by fernandomatheus** [comment]
@jamonholmgren Not actually. I'm using an alternative way for getting the WebView data...

**Comment by vishal9950** [comment]
@fernandomatheus Can you share the alternative way. I kind of have the same use case.

**Comment by JasonXiang2014** [comment]
I am looking for an answer for this question, and got a  library https://github.com/wootwoot1234/react-native-webkit-localstorage-reader, it's main thought is to find the data that  stored in file System directly, unfortunately it can't work in both android and IOS. @fernandomatheus Can you share the alternative way too?

**Comment by JasonXiang2014** [comment]
I find an alternative way 。It seems like this : 
<WebView
        ref={ref => this.webView = ref}
        source={{ uri }}
        javaScriptEnabled={true}
        domStorageEnabled={true}
        allowFileAccess={true}
        ref={(r) => { this.webview = r }}
        onLoadEnd={() => this.onLoadEnd()}
        injectedJavaScript={patchPostMessageJsCode}
        onMessage={(e) => this.handleMessage(e)}
        onNavigationStateChange={(navState) => { this.setState({ canGoBack: navState.canGoBack, }) }}
      />
 onLoadEnd(){
    const msg = { event: 'content', data } // you can get the data from AsyncStorage 
    this.webview.postMessage(JSON.stringify(msg)) // send message to webview
}
handleMessage(e){
     const  data  = JSON.parse(e.nativeEvent.data) // get the data from webview
}

in html：
window.onload = function() {
      document.addEventListener('message', function(e) {
        var event = JSON.parse(e.data);
        switch(event['event']) {
          case 'content':
            localStorage.setItem('xxx',18)
          break;
        }
      });
    };

window.postMessage(JSON.stringify({
        type: type, 
        data:localStorage.get('xxx')
      }));

**Comment by AndreyPatseiko** [comment]
@JasonXiang2014 used the same approach. But have problem with IOS platform. Because in iOS stored data from LocalStorage can be removed by the OS, when running out of memory. And if you try get data from local storage you can get null in IOS.

**Comment by wobsoriano** [comment]
[injectedJavaScript](https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#injectedjavascript) and [window.ReactNativeWebView.postMessage](https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#postmessagestr) should do the job.

```jsx
import { WebView } from 'react-native-webview';

const INJECTED_JAVASCRIPT = `(function() {
  const tokenLocalStorage = window.localStorage.getItem('token');
  window.ReactNativeWebView.postMessage(tokenLocalStorage);
})();`;

export default function App() {
  const onMessage = (payload) => {
    console.log('payload', payload);
  };

  return (
    <View style={styles.container}>
      <StatusBar style="auto" />
      <WebView
        source={{ uri: 'https://somewebsite.com/login' }}
        injectedJavaScript={INJECTED_JAVASCRIPT}
        onMessage={onMessage}
      />
    </View>
  );
}
```

Payload sample:

```
Object {
  "nativeEvent": Object {
    "canGoBack": true,
    "canGoForward": false,
    "data": "your_localstorage_value",
    "loading": false,
    "target": 3,
    "title": "Coil",
    "url": "https://somewebsite.com",
  },
}
```

**Comment by kkkasio** [comment]
> [injectedJavaScript](https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#injectedjavascript) and [window.ReactNativeWebView.postMessage](https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#postmessagestr) should do the job.
> 
> ```js
> import { WebView } from 'react-native-webview';
> 
> const INJECTED_JAVASCRIPT = `(function() {
>   const tokenLocalStorage = window.localStorage.getItem('token');
>   window.ReactNativeWebView.postMessage(tokenLocalStorage);
> })();`;
> 
> export default function App() {
>   const onMessage = (payload) => {
>     console.log('payload', payload);
>   };
> 
>   return (
>     <View style={styles.container}>
>       <StatusBar style="auto" />
>       <WebView
>         source={{ uri: 'https://somewebsite.com/login' }}
>         injectedJavaScript={INJECTED_JAVASCRIPT}
>         onMessage={onMessage}
>       />
>     </View>
>   );
> }
> ```
> 
> Payload sample:
> 
> ```
> Object {
>   "nativeEvent": Object {
>     "canGoBack": true,
>     "canGoForward": false,
>     "data": "your_localstorage_value",
>     "loading": false,
>     "target": 3,
>     "title": "Coil",
>     "url": "https://somewebsite.com",
>   },
> }
> ```
> 
> Works on both Android and iOS.

works fine tanks!
