### ISSUE TITLE
Autolinking for React Native > 0.60

### ISSUE THREAD

**Issue by vikalpjain** [react-native-community/react-native-webview#732]
React Native now supports Autolinking of libraries. But the installation instructions for this library still says that we need to run react-native link command. Will we be updating the library to support autolinking?

**Comment by recursiveKirs** [comment]
This had me confused aswell. Here is a screencap of the error you get when you try to build with a React Native project that used the Webview.

<img width="991" alt="Screen Shot 2019-07-22 at 12 55 34 PM" src="https://user-images.githubusercontent.com/19338303/61649801-277ff780-ac80-11e9-90ec-13624ac0042f.png">

**Comment by Titozzz** [comment]
I'll update the docs
