### ISSUE TITLE
Go back after auto redirect

### ISSUE THREAD

**Issue by zatsepinvl** [react-native-community/react-native-webview#733]
**Bug description:**
`webView.goBack()` doesn`t return to previous page if there was auto redirect to the third page.

**To Reproduce:**
1. Open link, say site A. (sorry, can not provide real examples, case happens with web resource in the private network)
2. Click on weblink that redirects to site B that automatically redirects to site C.
3. Invoke `webView.goBack()`

**Expected behavior:**
Go back to  site A.

**Actual behavior:**
Go to site B and automatically redirect to C - infinite loop.

**Environment:**
 - OS: Android
 - OS version: Android 9
 - react-native version: 0.59.8
 - react-native-webview version: 5.11.0

**Comment by JulianaCP** [comment]
Were you able to solve this? I am having the same problem.

**Comment by Gundam0079** [comment]
same problem+1   
How to fix?

**Comment by philipp65** [comment]
got stuck for too long with this...it's not a pure RN `WebView` issue. Did a workaround which looks simplified like this:

```javascript
   onNavigationChange = (navState, url) => {
        ...
            if (this.urlparse(url) === this.lastBackUrl) {
                if (this.lastFullBackUrl !== url) {
                    this.backCnt--;
                }
            } else {
                this.backCnt = -1;
            }

            this.lastBackUrl = this.urlparse(url);
            this.lastFullBackUrl = url;
    };

...

    urlparse = (url) => {
        url = url.replace("https://", "");
        url = url.replace("http://", "");
        url = url.replace("www.", "");
        url = url.replace("mobil.", "");
        url = url.split("#")[0];

        return url;
    };

...

goBack = () => {
        this.webview.injectJavaScript(`window.history.go(` + this.backCnt + `);`);
    };
```

**Comment by gssj85** [comment]
> got stuck for too long with this...it's not a pure RN `WebView` issue. Did a workaround which looks simplified like this:
> 
> ```js
>    onNavigationChange = (navState, url) => {
>         ...
>             if (this.urlparse(url) === this.lastBackUrl) {
>                 if (this.lastFullBackUrl !== url) {
>                     this.backCnt--;
>                 }
>             } else {
>                 this.backCnt = -1;
>             }
> 
>             this.lastBackUrl = this.urlparse(url);
>             this.lastFullBackUrl = url;
>     };
> 
> ...
> 
>     urlparse = (url) => {
>         url = url.replace("https://", "");
>         url = url.replace("http://", "");
>         url = url.replace("www.", "");
>         url = url.replace("mobil.", "");
>         url = url.split("#")[0];
> 
>         return url;
>     };
> 
> ...
> 
> goBack = () => {
>         this.webview.injectJavaScript(`window.history.go(` + this.backCnt + `);`);
>     };
> ```

I know it's been a year but I'm new to RN and it's my first work with this language, could you elaborate a bit your answer? if you still alive hehe

lastBackUrl --> from where this variable is coming?

**Comment by philipp65** [comment]
Hi, sorry for the delayed response.
I think it was a global variable from the component.
The main thing I did was counting the redirects caused by mobile, protocol and anchors - and then going back exact the same amount.
The real pain was that dependent on internet connection and/or device speed, sometimes redirects got pushed to the history and sometimes not. I haven't evaluated updates since more than a year on this repo, maybe they already got rid of it.
