### ISSUE TITLE
Allow fullscreen video in Android

### ISSUE THREAD

**Issue by wendelfreitas** [react-native-community/react-native-webview#734]
Hello everyone, videos inside a page not allowed fullscreen mode, this happens with vimeo and youtube.

**Bug description:**
The button to put full screen does not appear in the vimeo videos and youtube in OS Android (in IOS works normally). A test was done with the package react-native-android-fullscreen-webview-video and fullscreen works correctly, but this library does not have the function to select mobile files in the input file.

**To Reproduce:**
Enter a page that has youtube or vimeo videos, the fullscreen button will not appear

**Obs**
This error happens even with the release specifically made to fix this: https://github.com/react-native-community/react-native-webview/releases/tag/v5.9.0

**Environment:**
 - react-native version: 0.59.10
 - react-native-webview version: 5.9.1

**Comment by Silverdisc** [comment]
Make sure to set the allowsFullscreenVideo prop to true. I just ran into this as well, but it turned out I had simply overlooked this prop. Works fine for me on 5.12.1 .

**Comment by wendelfreitas** [comment]
@Silverdisc oh, sorry... Works fine for me too. Thanks dude :heart:

**Comment by mikaoelitiana** [comment]
It didn't work for me on a View where WebView doesn't have full screen height. Any Idea?

**Comment by rafaelbpa** [comment]
did you make it work @mikaoelitiana ? any workaround? same problem here

**Comment by bkoether** [comment]
@mikaoelitiana @rafaelbpa were you able to solve the issue? I ran into the same problem with the latest version

**Comment by rafaelbpa** [comment]
Hi @bkoether . We changed our route that use this lib to **modal** instead of using a component modal.
Our route was something like:
```
const WebViewStack = createStackNavigator({
  WebView,
}, {
  mode: 'modal',
  headerMode: 'none',
  initialRouteName: 'WebView',
  defaultNavigationOptions: {
    gesturesEnabled: false,
  },
})
```

Apparently, if we don't change this on our route, the react-native puts his modal on top of react-native-webview (only in android).
