### ISSUE TITLE
Webview not working in hermes

### ISSUE THREAD

**Issue by deceive3w** [react-native-community/react-native-webview#736]
**Bug description:**
i am load static html give me blank result when using hermes, its work when not using hermes

**To Reproduce:**

my html: 

> <html>
>                     <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=0" />
>                     <style media="screen" type="text/css">
>                     #container {
>                         width:100%;
>                         height:100%;
>                         top:0;
>                         left:0;
>                         right:0;
>                         bottom:0;
>                         position:absolute;
>                         user-select: none;
>                         -webkit-user-select: none;
>                     }
>                     </style>
>                     <head>
>                         <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
>                         ${this.props.stock ? '<script src="https://code.highcharts.com/stock/highstock.js"></script>'
>                                       : '<script src="https://code.highcharts.com/highcharts.js"></script>'}
>                         ${this.props.more ? '<script src="https://code.highcharts.com/highcharts-more.js"></script>'
>                                       : ''}
>                         ${this.props.guage ? '<script src="https://code.highcharts.com/modules/solid-gauge.js"></script>'
>                                       : ''}
>                         <script src="https://code.highcharts.com/modules/exporting.js"></script>
>                         <script>
>                         var chart;
>                         $(function () {
>                             Highcharts.setOptions(${JSON.stringify(this.props.options)});
>                             chart = Highcharts.${this.props.stock ? 'stockChart' : 'chart'}('container', `,
>             end:`           );
>                         });
>                         </script>
>                     </head>
>                     <body>
>                         <div id="container">
>                         </div>
>                     </body>
>                 </html>
> 

my code: 

>   ```
> <WebView
>    onLayout={this.reRenderWebView}
>    style={styles.full}>                  
>    originWhitelist={['*']}
>    source={{ html: concatHTML, baseUrl: 'web/' }}
>    javaScriptEnabled={true}
>    domStorageEnabled={true}
>    calesPageToFit={true}
>    scrollEnabled={false}
>    automaticallyAdjustContentInsets={true}
>    ref={(ref)=>this.props.webviewRef(ref)}
>    {...this.props}
>  />
```

*Environment:**
 - OS: Android
 - OS version: 8
 - react-native version: 60.4
 - react-native-webview version: 6.3.1

**Comment by deceive3w** [comment]
any solution ?

**Comment by jambanagar** [comment]
@deceive3w Did you find a solution for this? I am stuck with the same issue, a blank screen....
