### ISSUE TITLE
 Need a feature to Clear cache 

### ISSUE THREAD

**Issue by arunalexanderKefi** [react-native-community/react-native-webview#737]
**Is your feature request related to a problem? If so, Please describe.**

**Describe the solutions you came up with**

**Additional context**

**Comment by arunalexanderKefi** [comment]
I can't clear the cache from the web view I used a 3rd party package react-native-cookies it is not working properly

**Comment by gorvinsky** [comment]
I'm using react-native-webview to load a react site that uses react-cookie. I have a problem deleting cookie on iOS device. But I am able to call native API from web so it would be great if there is a method to clear cache and cookie.

**Comment by Collin3** [comment]
Have you tried using the [incognito](https://github.com/react-native-community/react-native-webview/blob/master/docs/Reference.md#incognito) prop? That will clear cookies when you open the WebView. Support for Android incognito will be available once #524 gets approved/merged.

**Comment by gorvinsky** [comment]
> Have you tried using the [incognito](https://github.com/react-native-community/react-native-webview/blob/master/docs/Reference.md#incognito) prop? That will clear cookies when you open the WebView. Support for Android incognito will be available once #524 gets approved/merged.

Nope. That won't help with my scenario. I need to be able to clear cache and cookie when I want. Not everytime I close the webview.

**Comment by MakhouT** [comment]
@Collin3 Does the incognito prop also work for android?
As the platform shows: iOS WKWebView

Can confirm it is working beautifully in iOS.

**Comment by MakhouT** [comment]
@Collin3 just tested on android. It's not working there. Also need a solution for android platform.

**Comment by MakhouT** [comment]
Just saw the PR for android. Need to be a bit more patient :)

**Comment by EternalChildren** [comment]
Isn't it a way to perform cleanup? Clean up the cache by calling at any time.

**Comment by hungdev** [comment]
@Titozzz why do you close this topic? The problem has not been resolved.

**Comment by MoiShO** [comment]
// https://facebook.github.io/react-native/docs/webview
// doc https://github.com/react-native-community/react-native-webview
import { WebView } from 'react-native-webview';

**Comment by blueberry6401** [comment]
I saw clearCache method for Android, is there anyway to achieve the same thing on iOS?

**Comment by heron2014** [comment]
Hi guys, I posted my solution in the stackoverflow https://stackoverflow.com/questions/57158559/want-to-clear-cache-from-webview-in-react-native-cookiemanager-clearall-not-w/72546943#72546943

**Comment by kvlknctk** [comment]
We need to take advantage of the webview cache feature. Users who have logged in can log in without having to enter a password again. Incognito tab destroys all these features. We need to clear the webview cache when the user logs out of the application.

the incognito tab suggestion is ridiculous in this scenario.

**Comment by rf1804** [comment]
For iOS https://www.npmjs.com/package/react-native-webview-ios-cache-clear
For android https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#clearCachebool

@arunalexanderKefi @gorvinsky @hungdev @iammuhammadumar @deepak-sweeten @hardywu @DavitVosk @abitling @Collin3 @rossenv @MakhouT @MaximeConan @preetb123 @asashay @hkar19 @dwesty17 @oscarCrespo @kvlknctk @ihafkenschiel @jlm0
