### ISSUE TITLE
RN 60+ support

### ISSUE THREAD

**Issue by dbarner1** [react-native-community/react-native-webview#741]
Long time listener, first time caller.  Big fan.  🙏 

Looks like the webview needs to update to support RN 60. 

```
npm ERR! peer dep missing: react-native@>=0.57 <0.60, required by react-native-webview@6.3.1
```

May be a simple upgrade of package.json to:

```
  "peerDependencies": {
    "react": "^16.0",
    "react-native": ">=0.57 <0.61"
  },
```

...would just need to QA.

**Comment by dbarner1** [comment]
Still searching for solution

**Comment by Titozzz** [comment]
current support is defined as 60+ so this should have been closed
