### ISSUE TITLE
posting a message to webview doesnt work

### ISSUE THREAD

**Issue by MaxToyberman** [react-native-community/react-native-webview#742]
Hi !
I was sending a message to my WebView like this : 
```
    this.myWebView.postMessage(
      JSON.stringify({
        messageType: "handleServerResponse",
        responseData: json,
        requestId
      })
    );
```

but after the upgrade it has stopped working, and now i'm trying to use the `injectJavaScript` instead.

This is what i am trying to do : 
```
    const injectedJS= `
      window.postMessage("${JSON.stringify({
        messageType: "handleServerResponse",
        responseData: json,
        requestId
      })}"); 
    true;`
   this.myWebView.injectJavaScript(injectedJS)
```

but the message is not received on the WebView side,
communication from the WebView to the app it self by using 
 window.ReactNativeWebView.postMessage(data);
is working fine.

please help

**Comment by MaxToyberman** [comment]
ok, i have found a solution but i am not sure this is the best way.

        this. myWebView.injectJavaScript(`
        (function(){
          window.postMessage('${data}','*');
        })();
        true;
        `)

**Comment by httol** [comment]
https://github.com/react-native-community/react-native-webview/issues/422#issuecomment-473268779

**Comment by httol** [comment]
So what your question is?
https://github.com/react-native-community/react-native-webview/issues/422#issuecomment-473268779

**Comment by MaxToyberman** [comment]
@happy-thorny i'm not sure that this is the best way to do it.

**Comment by paldepind** [comment]
@MaxToyberman `this.myWebView.postMessage` should still work? In the [readme](https://github.com/react-native-community/react-native-webview#versioning) removing it is only listed as an upcoming change.

**Comment by adophper** [comment]
@MaxToyberman  my web page did not receive the message sent by the app.
```
  this. myWebView.injectJavaScript(`
    (function(){
      window.postMessage('${data}','*');
    })();
    true;
    `)
```

**Comment by Titozzz** [comment]
@MaxToyberman Your method is the good one. Please note that the website you are trying to communicate with could also expose functions on the window to allow you manipulate it without using postMessage, (ofc only if you manage the website too) :)
