### ISSUE TITLE
WebView Scroll android not working

### ISSUE THREAD

**Issue by mezalejandro** [react-native-community/react-native-webview#743]
**Bug description:**

On iOS scroll it's working but android not.
```
<WebView
                    key={key}
                    source={{ html: }}
                    startInLoadingState={true}
                    renderLoading={() => (
                      <View
                        style={{
                          flex: 1,
                          alignItems: "center",
                          justifyContent: "center",
                          alignItems: "center"
                        }}
                      >
                        <ActivityIndicator
                          size="small"
                          color="#000"
                        />
                      </View>
                    )}
                    style={{ width: '100%', height: Dimensions.get("window").height, flex: 1 }}
                    automaticallyAdjustContentInsets={false}
                    javaScriptEnabled={true}
                    domStorageEnabled={true}
                    decelerationRate="normal"
                    startInLoadingState={true}
                    scalesPageToFit={true}
                    scrollEnabled={true}
                    useWebKit={true}
                  />
```

**Environment:**
 - react-native version: 0.59.9
 - react-native-webview version: ^5.6.1

**Comment by vvusts** [comment]
Is your webview wrapped inside scrollview maybe?

**Comment by mezalejandro** [comment]
> Is your webview wrapped inside scrollview maybe?

The only way the scroll works is this way:

`<ScrollView contentContainerStyle={{ flexGrow: 1 }}>
        <WebView source={{ uri: 'https://github.com/react-native-community/react-native-webview/issues/22' }}
                 style={{ height: 100 }}/>
        <WebView source={{ uri: 'https://bbc.co.uk/news' }} style={{ height: 100 }}/>
      </ScrollView>`

I can't get a bigger stop just 100

**Comment by gasolin** [comment]
@mezalejandro is it like a dup of #22 ?

**Comment by mezalejandro** [comment]
I solved with this library https://github.com/iou90/react-native-autoheight-webview#readme
