### ISSUE TITLE
No way to load a local HTML file in the webview on Android

### ISSUE THREAD

**Issue by DaniAkash** [react-native-community/react-native-webview#746]
**Bug description:**
I have a file with name `index.html`. I'm trying to load the file into the webview. However, there seems to be no option for it in android.

**To Reproduce:**

On iOS I tried:
```js
const myHtml = require("./index.html");

// In Render
<WebView
  ref={this._webViewRef}
  source={myHtml}
/>
```
It worked perfectly fine. However on Android it threw `TypeError: Cannot use 'in' operator to search for 'method'` So, I tried manually resolving the asset uri like I used to do for Images,

```
<WebView
  ref={this._webViewRef}
  source={{uri: Image.resolveAssetSource(myHtml).uri}}
/>
```

However it directly loads the file HTML source instead of the actual webpage.

**Expected behavior:**
```js
const myHtml = require("./index.html");

// In Render
<WebView
  ref={this._webViewRef}
  source={myHtml}
/>
```
The above code should just load the webpage on both android and iOS I guess...

**Environment:**
 - OS: macOS 
 - OS version: 10.14 (18A391)
 - react-native version: 0.60.3
 - react-native-webview version: 5.12.1

**Comment by httol** [comment]
On Android,you should use 
**Release**
` { uri: "file:///android_asset/YOUR FILE"}`
**Dev**
`require(...)`
And you should put you html file in android/app/src/main/asstes

**Comment by DaniAkash** [comment]
Shouldn't this be documented?

**Comment by paldepind** [comment]
Per [this comment](https://github.com/react-native-community/react-native-webview/issues/518#issuecomment-485426228) using `<WebView source={require('page.html')} />` is not supported by react-native-webview. So, indeed, there seems to be no official way to load a local HTML file in the webview.

It would be really nice if using `require` with `source` could work like it did with the webview previously included in react-native. We can't currently upgrade react-native due to this problem.

**Comment by jtreat3** [comment]
My team is caught between a rock and hard place because loading bundled HTML with the original Webview chokes on SVGs and disables the gyroscope, but doing it with React-Native-Webview doesn't render the HTML at all. If there's any chance of fixing local HTML, it would make a huge difference.

**Comment by httol** [comment]
Try to change all your external css  js inline the html file. Maybe this worked. I try it and worked. So I think not like preciously, react-native - webview do not support external reaource reference.

**Comment by jrose989** [comment]
I've been messing around a bit trying to get this to work. 
This seems to be working on iOS and Android, hopefully someone else can confirm it works for them too?

```
import { Image } from 'react-native';

const source = require('./page.html')
const webviewSource = Image.resolveAssetSource(source);

<WebView
  source={webviewSource}
/>
```

**Comment by reubert22** [comment]
I found an workaround here:
**iOS** -> You can just import the file you want and put it on source, like that:
```
import WebViewFile from "../../../components/.../index.html";

<WebView source={WebViewFile} />
```
**Android** -> You can do that:
```
<WebView source={{
    html: require("../../../components/.../index.js")()
}} />
```
And remember to do pass your local `html` file inside the `index.js`:
```
module.exports = function() {
  return `
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" class="perfect-scrollbar-on">
<head> ..... </head>`;};
```

**Both**
```
<WebView
    originWhitelist={["*"]}
    allowFileAccess={true}
    source={
      Platform.OS === "android"
        ? {
            html: require("../../../components/.../index.js")()
          }
        : WebViewFile
    }
    domStorageEnabled={true}
    allowUniversalAccessFromFileURLs={true}
    allowFileAccessFromFileURLs={true}
    mixedContentMode="always"
  />
```

**Comment by DaniAkash** [comment]
@jrose989 it is not working for me

**Comment by DaniAkash** [comment]
@reubert22 your method relies on using the HTML as a template string inside a js file. It works but I'd like a more direct way like @httol mentioned.

**Comment by rikkitissier** [comment]
This is what I've done (I'm using Expo libraries, adjust as needed):

```
const file = await AssetUtils.resolveAsync(require("path_to_your_local_file"));
const fileContents = await FileSystem.readAsStringAsync(file.localUri);
this._editorHtml = fileContents;
...
<WebView source={{ html: this._editorHtml }} ... />
```

**Comment by zhouping3** [comment]
@rikkitissier Can you provide more code about 'AssetUtils.resolveAsync'? I encountered the problem with expo 33

**Comment by rikkitissier** [comment]
@zhouping3 It's part of this package (which I don't think is included in Expo by default) https://www.npmjs.com/package/expo-asset-utils

**Comment by jrose989** [comment]
@DaniAkash sorry missed your comment, I'm not sure why it wouldn't work, including more code based on the full component. Might be because we have the html in the assets folder?

I've got it working using the following on ios/android in debug and release builds with the following:

```
const debugSource = require('../assets/index.html); // required for bundling
const releaseSourcePrefix = Platform.OS === 'android' ? 'file:///android_asset' : './assets';
const releaseSource = { uri: `${releaseSourcePrefix}/assets/index.html` };
const webViewSource = Image.resolveAssetSource(global.__DEV__ ? debugSource : releaseSource);
```

and  in your render:
```
<WebView
  source={webViewSource}
  originWhitelist={['*']}
  useWebKit
/>
```

You need to copy the html/js etc to the correct locations for the html to be included in the release builds.
iOS you need to add the folder + files under the 'Resources' group (in Xcode I have Resources/assets/index.html with all related js/css)
Android the files need to be copied to android/app/src/main/assets/

Hope this helps

**Comment by sheydarezaee** [comment]
Any of these solutions work for anyone? 
I have a problem of display of webview with static html content on and off, it shows the content one time, and on reload it shows a white screen and then shows the content on another reload randomly, anyone has this issue?

**Comment by sunnylqm** [comment]
![webview html](https://user-images.githubusercontent.com/615282/63481307-a9558180-c4c7-11e9-867d-ececf1d60028.jpg)
And remember to drag the html into Xcode and android/app/src/main/asstes

**Comment by rotoxl** [comment]
I think this is solved, isn't it? I've managed to download & unzip a folder, then show the contained html (from `/Users/rotoxl/Library/Developer/CoreSimulator/Devices/987C6DE3-29BB-4197-B22E-DC4A550C9E40/data/Containers/Data/Application/A0BAD256-CCBE-4F89-A1DB-D635F6532A57/Documents/course123/lesson320/file.html`). The html even has relative images (also contained in the zip file).

` 
<WebView
       scalesPageToFit={false}
       source={{ uri: this.state.contentURL }}
       originWhitelist={["*"]}
       style={{ flex: 1, }}
       />
`

`originWhitelist` did the trick, I still haven't tested it on a real device

**Comment by DaniAkash** [comment]
@rotoxl To show html in android apps, the best way is to bundle the html into the android app assets. This is currently being used in my library [React Native Draftjs Editor](https://github.com/DaniAkash/react-native-draftjs/blob/master/index.js#L113). I think this should be documented in this repository...

**Comment by rotoxl** [comment]
Hi @DaniAkash,

my content is meant to be dynamic, so bundled html is not an option for me. But, ok, I understand my usecase does not match yours.

**Comment by DaniAkash** [comment]
@rotoxl can u test in on an android device and let me know if your approach works?

**Comment by rotoxl** [comment]
@DaniAkash:

ups...  it's not working on an android device (webview is blank), but it does work on an iOS device. I'm gonna try if any other known hack works. Sorry for the misinformation

**Comment by DaniAkash** [comment]
Thanks for verifying it @rotoxl

**Comment by bulby97** [comment]
Please see https://github.com/react-native-community/react-native-webview/issues/667#issuecomment-526868371

**Comment by httol** [comment]
@mukeshsharma1201  Try to make the js file inline the html. Not use external file.

**Comment by bulby97** [comment]
> I am not able to view HTML file on iOS as well. I am trying to import a local js file using `<script src="./highcharts.js"></script>` but I see blank screen. 
> 
> And this error `'resources/highcharts/highcharts.js' cannot be loaded as its extension is not registered in assetExts`

You cannot do that. You need to build your files inline. Please look at my starter kit for using webview with react-native :

https://github.com/springload/react-native-webview-react-webpack-starter-kit

**Comment by wantg** [comment]
if (Platform.OS === 'ios') {

this.setState({ webViewSource: errorView });

} else {

fetch(Image.resolveAssetSource(errorView).uri)
    .then(response => response.text())
    .then(body => {
        this.setState({ webViewSource: { html: body } });
    });

}

**Comment by rotoxl** [comment]
> @DaniAkash:
> 
> ups... it's not working on an android device (webview is blank), but it does work on an iOS device. I'm gonna try if any other known hack works. Sorry for the misinformation

Hi again,

I have recently been able to achieve this on both Android and iOS, I can't say what was wrong, I think the `file://` protocol was missing. My actual code is 
`
<WebView                      
    source={{ uri: 'file://'+this.state.contentURL }}
    originWhitelist={["*"]}
    style={{ flex: 1, }}
                        
    domStorageEnabled={true}
    javaScriptEnabled={true}
    allowFileAccess={true}
    allowUniversalAccessFromFileURLs={true}
                        
    useWebKit={true}
    scalesPageToFit={true}
    />
`

**Comment by DaniAkash** [comment]
Thanks for letting me know. Will try this from my side as well...

**Comment by sheydarezaee** [comment]
Here is what I did after quite time I spent on figuring it out, and it works fine for both iOS and Android:

````
import React, { Component } from 'react'
import propTypes from 'prop-types'
import { View, Linking, AppState } from 'react-native'
import { WebView } from 'react-native-webview'
import styles from './WebAd.Styles'

export class WebAd extends Component {
  constructor(props) {
    super(props)
    this.state = {
      appState: AppState.currentState,
      key: 1,
      isWebviewUrlChanged: false,
    }
  }

  componentDidMount() {
    AppState.addEventListener('change', this._handleAppStateChange)
  }

  componentWillUnmount() {
    AppState.removeEventListener('change', this._handleAppStateChange)
  }

  _handleAppStateChange = nextAppState => {
    if (this.state.appState.match(/inactive|background/) && nextAppState === 'active') {
      this.renderWebviewToInitialUrl()
    }

    if (this.state.appState.match(/active|foreground/) && nextAppState === 'background') {
      this.renderWebviewToInitialUrl()
    }

    this.setState({ appState: nextAppState })
  }

  renderWebviewToInitialUrl = () => {
    if (this.state.isWebviewUrlChanged) {
      this.setState(prevState => {
        return { key: prevState.key + 1, isWebviewUrlChanged: false }
      })
    }
  }

  render() {
    const { halfAd } = this.props
    return (
      <View style={[styles.card, { flex: 1 }]}>
        <WebView
          ref={ref => {
            this.webview = ref
          }}
          style={[styles.card, { flex: 0 }]}
          source={{ html: `${halfAd.rendered}` }}
          onNavigationStateChange={event => {
            if (event.url !== 'about:blank') {
              Linking.openURL(event.url)
              this.setState({ isWebviewUrlChanged: true })
            }
          }}
          overScrollMode="content"
          scrollEnabled={false}
          useWebKit
          renderError={() => <View />}
          originWhitelist={['*']}
          javaScriptEnabled
          cacheEnabled
          domStorageEnabled
          key={this.state.key}
        />
      </View>
    )
  }
}

WebAd.propTypes = {
  halfAd: propTypes.shape({
    link: propTypes.string,
    image: propTypes.string,
    rendered: propTypes.string,
    tempalte: propTypes.string,
  }),
}

WebAd.defaultProps = {
  halfAd: undefined,
}
````
With using `key`, you will be able to stop loading of the webview when opening the link and returning back to the app. Hope this helps.

**Comment by Aequitas737** [comment]
@rikkitissier I can render an Html file using your suggestion but it seems that none of the script tags work in that case. Any suggestions?

**Comment by nonotest** [comment]
hey guys - this used to work for me on IoS (not android) but since useWebKit is gone it just wont load certain js files...
have looked at allowingReadAccessToURL but it didnt change anything..
any ideas?

**Comment by assetcorp** [comment]
> I've been messing around a bit trying to get this to work.
> This seems to be working on iOS and Android, hopefully someone else can confirm it works for them too?
> 
> ```
> import { Image } from 'react-native';
> 
> const source = require('./page.html')
> const webviewSource = Image.resolveAssetSource(source);
> 
> <WebView
>   source={webviewSource}
> />
> ```

This would only load the HTML source code

**Comment by avlisesac** [comment]
> 🎉 This issue has been resolved in version 7.4.4 🎉
> 
> The release is available on:
> 
> * [npm package (@latest dist-tag)](https://www.npmjs.com/package/react-native-webview)
> * [GitHub release](https://github.com/react-native-community/react-native-webview/releases/tag/v7.4.4)
> 
> Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot 📦🚀
This release does not resolve the issue for me.

**Comment by divyangsolanki** [comment]
Error: 'resources/signature.js' cannot be loaded as its extension is not registered in assetExts
at /signExmpl/node_modules/metro/src/Assets.js:358:13
at Generator.next ()
at asyncGeneratorStep (/signExmpl/node_modules/metro/src/Assets.js:52:24)
at _next (/signExmpl/node_modules/metro/src/Assets.js:72:9)
at /signExmpl/node_modules/metro/src/Assets.js:77:7
at new Promise ()
at /signExmpl/node_modules/metro/src/Assets.js:69:12
at getAsset (/signExmpl/node_modules/metro/src/Assets.js:337:20)
at /signExmpl/node_modules/metro/src/Server.js:992:28
at Generator.next ()
I am getting above error because my html file contains
<script type="text/javascript" src="../resources/signature.js"></script>

Please help me to find the solution. I am using react native 0.61 version.

**Comment by mkamyszek** [comment]
> `originWhitelist` did the trick, I still haven't tested it on a real device

App in TestFlight works with this added.

**Comment by likepearl** [comment]
> file

Does it work?  I'm managing to download  a folder, then show the contained html, The html even has js and css files(also contained in the zip file).

**Comment by likepearl** [comment]
@rotoxl  Does it work? I'm managing to download a folder, then show the contained html, The html even has js and css files(also contained in the zip file).

**Comment by assetcorp** [comment]
@likepearl did you try it? What was the outcome?

**Comment by likepearl** [comment]
> @likepearl did you try it? What was the outcome?

Blank page

**Comment by fujianjin6471** [comment]
> On Android,you should use
> **Release**
> ` { uri: "file:///android_asset/YOUR FILE"}`
> **Dev**
> `require(...)`
> And you should put you html file in android/app/src/main/asstes

Both dev and realease use `{ uri: "file:///android_asset/YOUR FILE"}` now

**Comment by hashinclude72** [comment]
so i have to keep multiples copies of html file , one in `android/app/src/main/asstes` and one for ios?

**Comment by DaniAkash** [comment]
@hashinclude72 yeah that seems to be the case

**Comment by vendeza** [comment]
I think at now the best resolving is using html string in component file :

```
const html = <p>Test string</p>

<WebView   source={{html: html}}/>

```
That resolve works for IOS and for Android.
Can write code in html file, formate  and then copy to js component file. I know If you have huge html file it is really headaches, you'll get a lot of code. But it work.

**Comment by supportartoon** [comment]
> On Android,you should use
> **Release**
> ` { uri: "file:///android_asset/YOUR FILE"}`
> **Dev**
> `require(...)`
> And you should put you html file in android/app/src/main/asstes

Thanks Man, It's Working

**Comment by indiedotkim** [comment]
If anyone ever comes across this thread and wonders why their `injectedJavaScript` seems unable to load files from `file:///android_assets/...`, here's why:

You have to include `source={{ html: '' }}` as argument for `WebView`. Otherwise the file-lookup will just not work.

Example:

    <WebView originWhitelist={["*"]}
        allowFileAccess={true}
        allowUniversalAccessFromFileURLs={true}
        allowFileAccessFromFileURLs={true}
        domStorageEnabled={false}
        injectedJavaScript={`
            YOUR_JAVASCRIPT WHERE YOU USE file:///...
        `}
        source={{ html: '' }} />

**Comment by haveamission** [comment]
No resolution worked for me locally (I may put more time into it later), so I just used my CDN and served it remotely.

It would be nice if this eventually had a simple and elegant solution for every platform.

**Comment by fausto-GJS** [comment]
Tentei todo tipo de  solução  e só tive êxito depois de realizar algumas linhas de código.

Para quem tiver problema com a Webview tanto local quanto externo, vá no arquivo **AndroidManisfest.xml** e insira estas linhas de código.

<manifest package="org.unimodules.interfaces.permissions">
<uses-permission android:name="android.permission.INTERNET"/>
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
</manifest>


salve a alteração e agora crie um arquivo .js para testar 


import React from 'react';
import { WebView } from 'react-native-webview';
import { View} from 'react-native';

export default function App() {
  const initialHTMLContent = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title></title>
  <meta name="author" content="">
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<h1>Hello world 2021</h1>
</body>
</html>`;
  return (
    <View style={{width:300,height:300}}>
      <WebView
        originWhitelist={['*']}
        javaScriptEnabled={true}
        domStorageEnabled={true}
        source={{
          html: initialHTMLContent
        }}/>
    </View>
  );
}





Pela minha experiência ele funciona emulando direto no celular, se usar o browser ele não aparece nada.
mas já é algo...

**Comment by shahanija** [comment]
> Any of these solutions work for anyone? I have a problem of display of webview with static html content on and off, it shows the content one time, and on reload it shows a white screen and then shows the content on another reload randomly, anyone has this issue?

Did you find any solution ? Please let me know. I am stuck with this issue

**Comment by Whitewashed4** [comment]
> > Any of these solutions work for anyone? I have a problem of display of webview with static html content on and off, it shows the content one time, and on reload it shows a white screen and then shows the content on another reload randomly, anyone has this issue?
> 
> Did you find any solution ? Please let me know. I am stuck with this issue





https://preposteroustryst.github.io/lease639/
