### ISSUE TITLE
UNKNOWN_URL_SCHEME error on Android only?

### ISSUE THREAD

**Issue by GollyJer** [react-native-community/react-native-webview#750]
- react-native: `0.59.8`
 - react-native-webview: `0.11.5`

I have a very simple webview.
```typescript
<WebView
  source={{ uri: authZeroUrl(authMode, nonce) }}
  originWhitelist={['*']}
  onNavigationStateChange={response => checkForToken(response)}
/>
```

But when a response comes back on Android I get the following error.
```
WebView error: , Object {
  "canGoBack": false,
  "canGoForward": false,
  "code": -10,
  "description": "net::ERR_UNKNOWN_URL_SCHEME",
  "loading": false,
  "target": 105,
  "title": "Sign In with Auth0",
  "url": "exp://tv-7as.awesomelabs.awesome-chat-app.exp.direct:80/redirect#access_token=RqaE{more stuff after this}
```
Because it works in iOS maybe it has something to do with the native side of the code?
I'm not exactly sure how to troubleshoot this issue. Any ideas would be super helpful.

Thanks!

**Comment by Titozzz** [comment]
react-native-webview: 0.11.5

This version does not even exists

regarding your issue, looks like you are trying to open an url starting with exp:// and android does not support this

**Comment by bulby97** [comment]
@GollyJer How did you fix it ? I'm having the same issue trying to load a local html file using uri.

**Comment by Findiglay** [comment]
I'm getting the same issue with Medium urls. Looks like the url is being converted to an app link `medium://p/`.

**Comment by Cartas** [comment]
Same issue for me, when the website I am viewing is trying to trigger another app.  It works perfectly fine on iOS (and with the old Expo webview).  Is there any solution yet?

**Comment by Visakeswaran** [comment]
Any updates on the issues ?

**Comment by WPSeven** [comment]
![Screenshot_20200605-155452](https://user-images.githubusercontent.com/8923057/83860776-b9340e80-a745-11ea-9fe8-3fb8224a55ea.png)

Same issue for me, when trying to trigger another app from Expo webview on android. Is there any solution yet?

**Comment by kranthi1216** [comment]
Hi i am using intent://app....... url which is showing above error
using SDK 30 in Android in react native
any help?

**Comment by hepoblet** [comment]
Hello! I have this problem when trying to open a link from firebase dynamic links on iOS
someone solve it?

**Comment by dhelbegor** [comment]
Anyone found a solution for this error? having the same here. looks like they closed the issue without a solution

**Comment by kranthi1216** [comment]
> Anyone found a solution for this error? having the same here. looks like they closed the issue without a solution

For me, the problem was fixed after I added an SSL certificate to the app.
