### ISSUE TITLE
add ignoreSslError prop

### ISSUE THREAD

**Issue by SaeedZhiany** [react-native-community/react-native-webview#752]
**Is your feature request related to a problem? If so, Please describe.**
In RN core's webview library we had an option to ignore ssl errors that come in handy.
but this library hasn't such feature 

**Describe the solutions you came up with**
honestly, I have no idea right now for a solution but really need it soon.

**Additional context**

**Comment by SaeedZhiany** [comment]
@Titozzz 
have you any plan on this?

**Comment by witalobenicio** [comment]
This would be a nice feature. Please reopen!

**Comment by klower** [comment]
I also hope that you can reopen this request

**Comment by SaeedZhiany** [comment]
@Titozzz

this issue has been closed without getting enough attention.

is there any plan on this? please reopen it.

**Comment by SaeedZhiany** [comment]
@Titozzz

is there any plan on this? please reopen it.

**Comment by SaeedZhiany** [comment]
it seems there is [a related PR for this](https://github.com/react-native-community/react-native-webview/pull/1142)
