### ISSUE TITLE
App crashes both on Android and iOS when input type text receives focus in webview

### ISSUE THREAD

**Issue by sangyakhare** [react-native-community/react-native-webview#753]
**Bug description:**
a web page loads successfully but as soon as input type text receives focus on webpage keyboard appears and app crashes both on Android and iOS giving 2 different error messages.
Please see the attached videos.
Here is my render method. What I am doing wrong?

render() {
    return (
      <View style={{flex:1, paddingTop:40}} >
        <KeyboardAvoidingView style={{flex:1}} behavior="padding" enabled>
        <WebView 
        source={{uri: 'http://jsonviewer.stack.hu/'}}
        style={styles.container}
        javaScriptEnabled={true}
        domStorageEnabled={true}
        startInLoadingState={true}
        keyboardDismissMode={'none'}
        useWebKit={true}
        automaticallyAdjustContentInsets={true}
        />
        </KeyboardAvoidingView>
      </View>
    )
  }

**To Reproduce:**

**Expected behavior:**

**Screenshots/Videos:**

**Environment:**
 - OS: Android and iOS
 - OS version:
 - react-native version: 0.59.0
 - react-native-webview version: 5.8.2
![webview-crash-keyboard-iOS](https://user-images.githubusercontent.com/49403660/62223614-428aef80-b383-11e9-8305-232954173c58.gif)
![webview-crash-keyboard-android](https://user-images.githubusercontent.com/49403660/62223652-5171a200-b383-11e9-8842-56c3cf585c1b.gif)

**Comment by Titozzz** [comment]
No idea about what happening 🤔

**Comment by bestmazzo** [comment]
@sangyakhare Are you using react-navigation ? I'm experiencing the same issue whenever the screen including  Webview is on a stackNavigation and there are more than 2 steps (stacked views) to reach it.

**Comment by sangyakhare** [comment]
@bestmazzo I am using wix react-native-navigation v2. And your observation is right. It is happening on Modal as well as on a stacked screen. Both involve 2 steps. I see keyboard appearing for a fraction of second and then the error occurs. Looks to me that the issue is with keyboard sliding content above to make space for itself. Not sure how to resolve it. :(
It happens when I click inside the input field in Webview, to write something.

**Comment by sangyakhare** [comment]
Did anyone find any resolution on this?

**Comment by sangyakhare** [comment]
@bestmazzo did you find any work around?

**Comment by sangyakhare** [comment]
@Titozzz looks like when the keyboard tries to scroll the screen something with the calculation is causing this problem on both the platforms. And it is the bridge issue.

**Comment by NicoBru31** [comment]
Hi @sangyakhare  and @bestmazzo , did you solved this issue ? I have same error as yours
