### ISSUE TITLE
Can not embed in <view/>

### ISSUE THREAD

**Issue by 1767083130** [react-native-community/react-native-webview#757]
Can not embed in view
It's OK:
    `<WebView ref="webView" source={{uri: 'https://www.baidu.com'}} />
`
it  does not worked :
```
   <View>
     <WebView ref="webView" source={{uri: 'https://www.baidu.com'}} />
   </View>
```

environments:
    "react": "16.8.6"
    "react-native": "0.60.4"
    "react-native-webview":  5.12.1
   os: windows

who can help me? thanks

**Comment by omjimehrotra** [comment]
Following code snippet works for me:

```
<View style={{ flex: 1, justifyContent: 'flex-end' }}>
        <WebView
          source={{ uri: 'file:///android_asset/termandcondition.html' }}
          style={{ flex: 1 }}
          javaScriptEnabled
          domStorageEnabled
        />
 </View>
```

**Comment by arminsal1** [comment]
Still searching for solutions
