### ISSUE TITLE
WebView has been removed from ReactNative #174

### ISSUE THREAD

**Issue by srhtylmz19** [react-native-community/react-native-webview#758]
WebView has been removed from ReactNative error in my simulator but i dont use webview at all

**Comment by allanmgdev** [comment]
I have the same error, if i find some thing i help you

**Comment by Khademl** [comment]
I am getting same error in react-native@0.60.4. If you find something related for solving this error, Kindly help.

**Comment by jeremaihloo** [comment]
I am getting same error in react-native@0.60.4 too. Using my phone xiaomi 9.

**Comment by jeremaihloo** [comment]
> I am getting same error in react-native@0.60.4 too. Using my phone xiaomi 9.

I solved this problem by upgrade react-native-gesture-handler from v1.0.15 to v1.3.0 which is latest version.

**Comment by Rushabhgedam** [comment]
[Solved] While am getting the same issue I have found the Library for WebView - [here](https://www.npmjs.com/package/react-native-webview)
resolved the issue.

**Comment by datht-gh** [comment]
Dear all, The my problem was solved. My case:  I search in my project keyword: "WebView" in **react-native-qrcode** module has a deprecated declare WebView  like:
`
var {
    View,
    WebView,
    Platform
} = require('react-native');`

and i replace by newest code: https://github.com/datht-gh/react-native-qrcode.
Hope resolve this issue.

**Comment by mahgolfa** [comment]
> > I am getting same error in react-native@0.60.4 too. Using my phone xiaomi 9.
> 
> I solved this problem by upgrade react-native-gesture-handler from v1.0.15 to v1.3.0 which is latest version.

you saved my life!

**Comment by srhtylmz19** [comment]
issue closed by accepted answer .

**Comment by Saneesh** [comment]
No WebView needed: https://www.npmjs.com/package/react-native-qrcode-image
