### ISSUE TITLE
applicationNameForUserAgent not working in android

### ISSUE THREAD

**Issue by carlmagumpara** [react-native-community/react-native-webview#759]
**Bug description:**

applicationNameForUserAgent not working in android

        <WebView
          source={{ 
            uri: this.state.site_url
          }}
          onNavigationStateChange={this.onNavigationStateChange.bind(this)}
          javaScriptEnabled={true}
          domStorageEnabled={true}
          startInLoadingState={true}
          style={{
            flex: 1
          }}
          applicationNameForUserAgent={'DemoApp/1.1.0'}
        />
**To Reproduce:**

**Expected behavior:**

show user agent with DemoApp/1.1.0

**Screenshots/Videos:**

![Screenshot_20190805-185625_LexMeet!](https://user-images.githubusercontent.com/14119484/62460064-8df23300-b7b3-11e9-99a1-ae4e2f83c4e9.jpg)

**Environment:**
 - OS: Android
 - OS version: Android 9 Pie
 - react-native version: 0.60.4
 - react-native-webview version: 5.12.1

**Comment by carlmagumpara** [comment]
oh sorry, i just update it to latest version.

**Comment by pizzahutmachine** [comment]
I am having issues with the exact same thing, I am working on top of Expo and have used the latest version of webview.
