### ISSUE TITLE
Add web support

### ISSUE THREAD

**Issue by necolas** [react-native-community/react-native-webview#76]
Include a `*.web.js` export to provide an implementation for React Native for Web. There's an existing community attempt here https://github.com/react-native-web-community/react-native-web-webview

**Comment by Titozzz** [comment]
Please open a pull request ❤️

**Comment by piranna** [comment]
Do you find it better to have it with the actual code in this repo, or using the `react-native-web-webview` as a dependency?

**Comment by piranna** [comment]
Also, maybe support for `react-native-dom` should be added?

**Comment by necolas** [comment]
Please put actual code in the repo so other people can help maintain it as the API evolves.

**Comment by Titozzz** [comment]
I'd love to see support for web and Dom. Code should be on this repo tho.

**Comment by jamonholmgren** [comment]
![2k99zm](https://user-images.githubusercontent.com/1479215/47044612-89399100-d145-11e8-88bb-f1d2ea950023.jpg)

**Comment by necolas** [comment]
Yes, they do.

**Comment by tehOPEologist** [comment]
has there been any traction on this?  there's certainly a need for this, and not having to alias another package and just be able to use the official package for webviews across platforms is certainly better than the current way.  plus, the suggested repo doesn't look like it's been updated in over a year, and doesn't seem to have been updated after this package got removed from the react-native core package.

**Comment by piranna** [comment]
still searching for solutions

**Comment by piranna** [comment]
The point is that's fake, because there's already an implementation at https://github.com/react-native-web-community/react-native-web-webview... :-/

**Comment by piranna** [comment]
Can this be re-open? We have provided a solution...

**Comment by oxbits** [comment]
@piranna 

did react-native-web-webview work for you?

**Comment by piranna** [comment]
Yes, It did, in fact I think did some contributions too

**Comment by oxbits** [comment]
thank you, im gonna try it out ! 

😺

**Comment by oxbits** [comment]
@piranna 

i got the react-native-web-webview to work

but i have to change between these two import statements to get the webview to work in web & native [ android & io ] 

`import WebView from 'WebView';`
and
`import { WebView } from 'react-native-webview';`

how do you deal with this ?

**Comment by piranna** [comment]
I define alias in the webpack config file.

**Comment by oxbits** [comment]
this is my config:

```
const createExpoWebpackConfigAsync = require('@expo/webpack-config');

const rule = {
  test: /postMock.html$/,
  use: {
    loader: 'file-loader',
    options: {
      name: '[name].[ext]',
    },
  },
};

module.exports = async function(env, argv) {
  const config = await createExpoWebpackConfigAsync(env, argv);

  config.resolve.alias['WebView'] = 'react-native-web-webview';

  module.rules = [rule,]

  return config;
};
```

and my hello react-native-web-webview `App.js`: 
```
import React from 'react';
// import { WebView } from 'react-native-webview';
import WebView from 'WebView';

export default function App() {
  return (
    <WebView
        source={{uri: 'https://example.com'}}
        style={{marginTop: 20}}
      />
  );
}
```

what would i have to do to make this also work in native [ android & ios ]

**Comment by oxbits** [comment]
@piranna 

this is my webpack config:
```
const createExpoWebpackConfigAsync = require('@expo/webpack-config');

const rule = {
  test: /postMock.html$/,
  use: {
    loader: 'file-loader',
    options: {
      name: '[name].[ext]',
    },
  },
};

module.exports = async function(env, argv) {
  const config = await createExpoWebpackConfigAsync(env, argv);

  config.resolve.alias['WebView'] = 'react-native-web-webview';

  module.rules = [rule,]

  return config;
};
```

and my hello react-native-web-webview `App.js`: 
```
import React from 'react';
// import { WebView } from 'react-native-webview';
import WebView from 'WebView';

export default function App() {
  return (
    <WebView
        source={{uri: 'https://example.com'}}
        style={{marginTop: 20}}
      />
  );
}
```

what would i have to do to make this also work in native [ android & ios ] ?

**Comment by piranna** [comment]
> what would i have to do to make this also work in native [ android & ios ] ?

First of all, stop using Expo.

**Comment by oxbits** [comment]
i usually do not

the above is ejected 

i was experimenting 

anything else ?

**Comment by oxbits** [comment]
@piranna 

like would the above code work if i was not using expo and thats it ?

**Comment by piranna** [comment]
> like would the above code work if i was not using expo and thats it ?

Yes, it should be working. Maybe the export is badly defined in the package... do a pull-request, it's a quick fix.

**Comment by oxbits** [comment]
this really helps 

thank you!

**Comment by oxbits** [comment]
@piranna 

when you say `Maybe the export is badly defined in the package`

are you referring to `expo` or `react-native-webview` or `react-native-web-webview` ?

which specific export are you referring to ? [ and you mean the export not the webpack config right ? ]

**Comment by piranna** [comment]
> `react-native-webview` or `react-native-web-webview` ?

Any of both. I think they should export the component both as default and as normal export.

**Comment by oxbits** [comment]
@piranna

the entire file from
https://github.com/react-native-community/react-native-webview/blob/master/src/WebView.tsx
```
import { WebView } from 'react-native';

export { WebView };
export default WebView;
```
( ☝️ is this the right file ? )

the only export not in a storybook from `react-native-web-webview`:
https://github.com/react-native-web-community/react-native-web-webview/blob/master/src/index.js
```
export default class extends Component {
...(the rest of the component)...
}
```

i changed it locally to this:
```
export default class WebView extends Component {
...(the rest of the component)...
}

export { WebView };
```

my hello world example above continues to work for web but the native webview still does not work it displays a white screen

is that what you meant to do or did i misunderstand ?

**Comment by piranna** [comment]
Yes, that's what I said, it should be working now...

**Comment by oxbits** [comment]
@piranna 

its not working the way i setup my example

i believe its something in expo even though its ejected

i usually do `react-native init` apps but i have never been able to get `react-native-web` working

expo has `react-native-web` working out of the box

im encouraged by the fact that the about example works but i cant figure out how the code branches for native and web 

like where is the place that it should branch per?:
• web poinst to `react-native-web-webview`
• native points to `react-native-webview`

feels like im so close since they both work one at a time if i simple change the import

**Comment by piranna** [comment]
I've never used Expo, for multiplatform projects with web and mobile I use [re-start](https://github.com/react-everywhere/re-start).

**Comment by oxbits** [comment]
oh wow thats cool !

thank you for sharing that link !

**Comment by piranna** [comment]
You are welcome :-)

**Comment by oxbits** [comment]
😿 i tried to get re-start ( react everywhere ) to work, no luck 😿
😿 i tried to get vanilla react-native init app to work with react-native-web, no luck 😿

then i figured out how to branch the imports in the code ! :
```
import React from 'react';
import { Platform } from 'react-native';
import { WebView as RNWebView } from 'react-native-webview';
import WWebView from 'WebView';

const WebView = Platform.OS === 'web' ? WWebView : RNWebView;

export default function App() {
  return (
    <WebView
        source={{uri: 'https://example.com'}}
      />
  );
}
```

finally it works !

😺

i plan to continue to figure out the other approaches but this is working and im stoked !

thanks again for everything ! 

hope to catch up soon

**Comment by piranna** [comment]
Congrats! :-D

**Comment by jjg77** [comment]
@oxbits 
Where do you see WWebView anywhere in 'react-native-webview'?  I tried your solution but it's not working for me.

**Comment by ur-gh** [comment]
@oxbits 
Thanks for sharing.. Wondering if you were able to make WebView work with expo on Web. I observed the same thing as you above - it works on Android but not on Web. I am using expo currently.
