### ISSUE TITLE
baseUrl pointing to local folder not working on iOS

### ISSUE THREAD

**Issue by JeremyBradshaw7** [react-native-community/react-native-webview#764]
We have some functionality in our app where we can allow users to download image resources to a local folder (when online) and then continue to use the screens (some of which are based on webview) to show the content even when offline. Since we migrated across to the community webview this offline capability is no longer working.

**Bug description:**
WebView that was part of React Native handled baseUrl pointing to local file:// folder. But on migrating to this community webview I'm getting an error thrown.

**To Reproduce:**
Store resources to be rendered in local folder. Render webview source eg (on simulator):
```
source: {
  baseUrl: "file:///Users/jwb/Library/Developer/CoreSimulator/Devices/2CF9CCA3-AB7F-43A6-83A5-998A3449F035/data/Containers/Data/Application/2667E941-4537-4481-B177-9941617466D9/Library/Caches/"
  html: "<img src="./3/7da43eaf-5c28-432a-8202-d37ebac6b9b4.png" />"
}
```
(irrelevant html around img tag removed)

Error thrown:
```
Possible Unhandled Promise Rejection (id: 0):
Error: Unable to open URL: file:///Users/jwb/Library/Developer/CoreSimulator/Devices/2CF9CCA3-AB7F-43A6-83A5-998A3449F035/data/Containers/Data/Application/2667E941-4537-4481-B177-9941617466D9/Library/Caches/
Error: Unable to open URL: file:///Users/jwb/Library/Developer/CoreSimulator/Devices/2CF9CCA3-AB7F-43A6-83A5-998A3449F035/data/Containers/Data/Application/2667E941-4537-4481-B177-9941617466D9/Library/Caches/
    at createErrorFromErrorData (blob:http://localhost:8081/ce126a5e-8b66-4390-8340-deb30ebe8ac2:2135:17)
    at blob:http://localhost:8081/ce126a5e-8b66-4390-8340-deb30ebe8ac2:2087:27
    at MessageQueue.__invokeCallback (blob:http://localhost:8081/ce126a5e-8b66-4390-8340-deb30ebe8ac2:2654:18)
    at blob:http://localhost:8081/ce126a5e-8b66-4390-8340-deb30ebe8ac2:2385:18
    at MessageQueue.__guard (blob:http://localhost:8081/ce126a5e-8b66-4390-8340-deb30ebe8ac2:2558:13)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (blob:http://localhost:8081/ce126a5e-8b66-4390-8340-deb30ebe8ac2:2384:14)
    at http://localhost:8081/debugger-ui/debuggerWorker.js:80:58
```
and webview shows loading spinner forever. It does this even if there are no html resources, it's the baseUrl that throws it.

WebView:
```
          <WebView
            startInLoadingState={true}
            injectedJavaScript={js}
            onMessage={(event) => this._onMessage(event)}
            ref={(ref) => this.webviewRef = ref}
            useWebKit={false} // needed to load local font on ios
            key={this.state.refreshKey}
            source={source}
            mixedContentMode={'compatibility'}
            scrollEnabled={true}
            javaScriptEnabled={true}
            domStorageEnabled={true}
            allowsInlineMediaPlayback={false}
            mediaPlaybackRequiresUserAction={false}
            onError={this.onError.bind(this)}
            allowFileAccess={true}
          />
```

**Expected behavior:**
Local resources are rendered without error, as React Native WebView did.

**Environment:**
 - OS: iOS 11
 - react-native version: 0.59.10
 - react-native-webview version: 5.12.0

It works OK on Android.

**Comment by JeremyBradshaw7** [comment]
No movement on this? It's a blocker for us.

**Comment by JeremyBradshaw7** [comment]
In playing with it I think I found a solution. Add this to the WebView props:

`originWhitelist={['*']}`

**Comment by JonathanVeg** [comment]
> In playing with it I think I found a solution. Add this to the WebView props:
> 
> `originWhitelist={['*']}`
> 
> I wont close unless can confirm this is the answer, and why.

It saved me after an entire day looking for the answer! Thanks!
