### ISSUE TITLE
cannot unlink react-native-webview

### ISSUE THREAD

**Issue by Pranit-Harekar** [react-native-community/react-native-webview#766]
When tried to unlink the dependency,
```sh
react-native unlink react-native-webview
```

I got following error,
```log
error Project "react-native-webview" is not a react-native library
```

Prior to that I made sure that the dependency is actually linked properly,

![image](https://user-images.githubusercontent.com/17886017/62641481-aaa47d00-b911-11e9-84e1-befe64e8625e.png)

**Comment by dan10gc** [comment]
I have the same issue, I am able to link successfully but unable to unlink.
