### ISSUE TITLE
Allowing all origins breaks url schemes

### ISSUE THREAD

**Issue by StevenPurn** [react-native-community/react-native-webview#767]
**Bug description:**
If you have allowed all origins via the `originWhitelist` prop, the web view will not be able to correctly handle url schemes. Since you need to set `originWhitelist={['*']}` to support static HTML this means it isn't currently possible to support url schemes in static HTML. 

**To Reproduce:**
Test on this snack by scrolling down a bit in each webview and trying the example mailtto links.
https://snack.expo.io/By-IH5u7S

**Expected behavior:**
In both web views I would expect the user's email app to open with the data from the mailto link. On both Android and iOS the first webview is giving an error. On Android, the second webview behaves as expected. On iOS the second webview would likely behave as expected but their simulator doesn't include the mail app.

**Environment:**
 - OS: Android, iOS
- react-native version: 0.59.8
 - react-native-webview version: 6.8.0

**Comment by gbhrdt** [comment]
Removing the star and using `originWhitelist={["https://*", "http://*", "file://*", "sms://*", "tel://*"]}`  worked for me
