### ISSUE TITLE
Calendar file(.ics) download not working on ios

### ISSUE THREAD

**Issue by letaptravek** [react-native-community/react-native-webview#768]
**Bug description:**

I want to download example.ics file on iOS to allow users to add calendar event. When I click on the link nothing happens on iOS. 

For eg. <a href="https://example-files.online-convert.com/misc/ics/example.ics">Add to calendar</a>

Here is how I have implemented WebView

<WebView
                ref={r => (this.webref = r)}
                source={{uri: 'https://www.online-convert.com/file-format/ics'}}
                style={{marginTop:0}}
                geolocationEnabled={true}
                javaScriptEnabled={true}
                allowUniversalAccessFromFileURLs={true}
                allowFileAccess={true}
                onMessage={m => this.onMessage(m)}
            />

Added permission on iOS as well

`<key>NSCalendarsUsageDescription</key>
<string>See your scheduled appointments in calendar</string>
<key>NSPhotoLibraryAddUsageDescription</key>
<string>Save pictures for certain activities.</string>`

**FYI: It Works on Android.**

**To Reproduce:**

**Expected behavior:**

**Screenshots/Videos:**

**Environment:**
 - OS: MAC
 - OS version: 10.14.5
 - react-native version:0.59.9
 - react-native-webview version:5.12.1

**Comment by SudoPlz** [comment]
Same as https://github.com/react-native-community/react-native-webview/issues/998#issuecomment-644241041
