### ISSUE TITLE
webview load some page is incomplete

### ISSUE THREAD

**Issue by leoyb** [react-native-community/react-native-webview#77]
i used webview to open a url like "https://m.pandafun.io", the page can not display complete.

# Environment
```
OS:  macOS Sierra 10.13.6
Node:  8.9.1
Yarn:  0.24.5
npm:  5.4.0

Packages: (wanted => installed)
react-native: 0.53.0
react: 16.3.1
```

## Steps to Reproduce

1.WebView opens https://m.pandafun.io.

## Expected Behavior
the page can display complete.

## Actual Behavior
the page can not display complete.

## Reproducible Demo
```
<WebView
  onNavigationStateChange={this.onNavigationStateChange.bind(this)}
  source={{uri:"https://m.pandafun.io"}}
  domStorageEnabled={true}
  javaScriptEnabled={true}
/>
```

**Comment by ryanlntn** [comment]
@jamonholmgren It looks like it might be. @leoyb can you try adding `useWebKit={false}` to props?

**Comment by jamonholmgren** [comment]
Seems like it worked on my machine:

![image](https://user-images.githubusercontent.com/1479215/47042490-3c06f080-d140-11e8-9007-0463cd07c0b8.png)

**Comment by leoyb** [comment]
@jamonholmgren  Thank you very much for getting your reply, I found out because I used the “startInLoadingState={true}” attribute.
<img width="496" alt="wechatimg36" src="https://user-images.githubusercontent.com/10185166/47057002-68c71080-d1f1-11e8-9bda-a511f8cd5e0b.png">
I deleted this attribute, it works for me.

**Comment by ryanlntn** [comment]
That was the same case for me. Have you tried with `startInLoadingState={true}` and `useWebKit={false}`?

**Comment by leoyb** [comment]
i tried with startInLoadingState={true} and useWebKit={false}, it dose not work for me.

**Comment by ryanlntn** [comment]
Interesting. I was able to get `startInLoadingState` working with webView but not webKit. When I opened Safari to inspect it looked like a bing tracking pixel was failing to resolve and that was causing the whole request to hang. I'm wondering if there might be something similar happening with that page?

**Comment by leoyb** [comment]
Well, maybe as you said

**Comment by jamonholmgren** [comment]
For now, I'm going to close this, but if you run into other problems please feel free to file another issue.
