### ISSUE TITLE
Deep Link cannot be intercepted in method onShouldStartLoadWithRequest

### ISSUE THREAD

**Issue by DonaldGuo** [react-native-community/react-native-webview#772]
**Bug description:**
Deep Link cannot be intercepted in method onShouldStartLoadWithRequest. Although it returned false, the application was called up.
```
<WebView
    ...
    onShouldStartLoadWithRequest = {this._onShouldStartLoadWithRequest.bind(this)}
    />
```
```
    _onShouldStartLoadWithRequest = (event) => {
        let url =event.url;
        if(url.indexOf("alipay://")>-1 || url.indexOf("alipays://")>-1) {
            Log.info("-----------------------------------_onShouldStartLoadWithRequest return false url = " + url);
            return false;
        }
        return true;
    }
```

**To Reproduce:**

**Expected behavior:**
I need to intercept deep link and deal with them myself.

**Screenshots/Videos:**

**Environment:**
 - OS: Android
 - OS version: Android 8.0 Oreo
 - react-native version: 0.59.8
 - react-native-webview version: 5.12.0

**Comment by jannikbuschke** [comment]
I might have the same problem.
`onShouldStartLoadWithRequest` and `navigationStateChangedHandler` are not called when click on links

**Comment by baugarten** [comment]
@DonaldGuo @jannikbuschke have you two found any solutions for this issue? I'm trying to intercept a link such as `plaidlink://hostname?params=value` but none of the callbacks I try are called...

**Comment by DonaldGuo** [comment]
> @DonaldGuo @jannikbuschke have you two found any solutions for this issue? I'm trying to intercept a link such as `plaidlink://hostname?params=value` but none of the callbacks I try are called...

I copy module file into project and change the code  on the Android platform. (I don't know how to change for iOS)

Judge url in com.reactnativecommunity.webview.RNCWebViewManager.RNCWebViewClient.shouldOverrideUrlLoading(WebView, String) function

And return true for target url

**Comment by anibalajt** [comment]
> @DonaldGuo @jannikbuschke have you two found any solutions for this issue? I'm trying to intercept a link such as `plaidlink://hostname?params=value` but none of the callbacks I try are called...

@baugarten  

I had the same problem and I solved it with this
```
	<WebView
		source={{ uri }}
                 onShouldStartLoadWithRequest={request => {
			return request.url.startsWith(request.url);
		}}
                 onNavigationStateChange={event => {
			if (event.url.indexOf("yourdeeplionk") > -1) {
		}
	/>
```

**Comment by anibalajt** [comment]
try to follow this
https://medium.com/@anibalajt/react-native-deep-linking-ios-android-4f24d762d0a8

**Comment by WilliamBlais** [comment]
Same problem here, anyone found a solution?

**Comment by Overtorment** [comment]
someone mentioned in other ticket that you should whitelist your scheme first, and then it will work

```
originWhitelist={['*']}
```

**Comment by manoj-fareye** [comment]
@Overtorment tried with your suggestion. It works, Thanks

**Comment by carlcon** [comment]
> someone mentioned in other ticket that you should whitelist your scheme first, and then it will work
> 
> ```
> originWhitelist={['*']}
> ```

It works! Thank you!!!
