### ISSUE TITLE
Webview not loading requested site

### ISSUE THREAD

**Issue by MihkelPuusepp** [react-native-community/react-native-webview#775]
**Bug description:**

React-native-webview does not open requested page. It loads the webview. OnLoadStart and onLoadEnd are triggered but webview does not show anything.

I created a test app in Expo snack. Added just react-native-webview.
Tried on Expo 33 and Expo 34. Both give same result.

App.js
```
import * as React from "react";
import { View } from "react-native";
import RNWebView from "react-native-webview";

export default class App extends React.Component {
  render() {
    return (
      <View style={{ flex: 1, backgroundColor: "red", padding: 10 }}>
        <RNWebView
          style={{ flex: 1 }}
          source={{ uri: "www.google.com" }}
          onLoadEnd={() => console.log("OnLoadEnd")}
          onLoadStart={() => console.log("OnLoadStart")}
          onError={err => console.log({ err })}
        />
      </View>
    );
  }
}
```

package.json dependencies
 ```
"dependencies": {
    "expo": "^33.0.0",
    "react": "16.8.3",
    "react-native": "https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz",
    "react-native-paper": "2.16.0",
    "react-native-webview": "^6.9.0"
  }
```

**Comment by Jhonte** [comment]
Having the same, works in debug mode with iOS simulator for some reason...

**Comment by tafkanator** [comment]
if you change url to include protocol (https://) then it loads. Weird thing with this example is that no error is given and form my experience i sometimes get same result even if protocol is included.

**Comment by gitcion** [comment]
i have the same question

**Comment by emirdeliz** [comment]
I have a problem with webview. Because some reason the webview does not render content if the protocol is not https.
