### ISSUE TITLE
Access the window Object

### ISSUE THREAD

**Issue by elcitrovmtgrande** [react-native-community/react-native-webview#781]
Hello,

I want to use the Tone.js library for one of my projects. But Tone.js do use the Web Audio API. I had the idea of using an invisible WebView as a bridge to manipulate Tone.js. But in order to succeed, I should be able to access the window object of my WebView from my React Native parent component.

Is there any chance to succeed ? Does it exist kind of method like WebView.window to get the window object of the page loaded into my WebView ? 

Thank you

**Comment by ChrisWiles** [comment]
So is there a method to access the window object?
