### ISSUE TITLE
Is there any kind of autoplay=false for videos?

### ISSUE THREAD

**Issue by rochapablo** [react-native-community/react-native-webview#782]
**Is your feature request related to a problem? If so, Please describe.**

I'm not sure if this should be already working. I've tried `mediaPlaybackRequiresUserAction` setting `false/true` but none of them seems to have affect. And in my case, the video it always open automatically.

**Describe the solutions you came up with**

This is what I have tried:

```
<WebView
        {...this.props}
        mediaPlaybackRequiresUserAction={true} // true or false seems to have no change
        onError={this.onError}
        source={{ uri: this.props.uri }}
        style={this.props.style || styles.webView}
      />
```

**Additional context**

**Working on iOS**

**my packages**

```
"react": "16.9.0",
"react-native": "0.60.4",
"react-native-webview": "^6.9.0",
```

https://stackoverflow.com/questions/53707490/how-to-disable-auto-play-in-webview-react-native

**Comment by rochapablo** [comment]
It seems that `html:'<video` did the trick.

```
<WebView
    {...this.props}
    onError={this.onError}
    source={{
        html: `
        <video width="100%" height="100%" style="background-color:${styles.webView.backgroundColor}" controls>
            <source src="${this.props.uri}" type="video/mp4">
        </video>
        `,
    }}
    style={this.props.style || styles.webView}
/>
```

**Comment by rkstar** [comment]
this is still a problem. ticket should not be closed.
