### ISSUE TITLE
WebView stops rendering when exiting app immediately after source changes

### ISSUE THREAD

**Issue by sparrowDom** [react-native-community/react-native-webview#786]
**Bug description:**
When a user send application to background immediately (0.5-3 seconds) after new `source` react prop is supplied to `WebView` component the browser component is stuck with either a white screen or partially render web page that is non inter-actable. 

This bug is a bit sporadic and does not happen every time. This can be reproducible with both `WKWebView` and `UIWebView` modes.

**To Reproduce:**
- have application with webView in foreground
- trigger a new page load (in the video switching the current network changes the `source` property and issues a new page load
- exit the application
- re-enter the application

**Expected behaviour:**
Browser component to not be stuck. 

**Screenshots/Videos:**
[Youtube Video](https://www.youtube.com/watch?v=_g1m1vZOHAM):
- 0-3 sec -> browser acting normally
- 5 sec -> clicking on button changes WebView's source
- 7 sec -> exit application
- 9 sec -> re-enter application 
- 8-15 sec -> browser stuck only rendering first 1.5 screen heights of the page. Can not interact with elements in browser
- 18 sec -> exit app, re-open app. New page loads normally

**Environment:**
 - OS: IOS
 - OS version: 12.4
 - react-native version: 0.59.9
 - react-native-webview version: 5.12.0

**Comment by micahalcorn** [comment]
Please keep alive 😕
