### ISSUE TITLE
Webviews not visible on screen suddenly never load their HTML content

### ISSUE THREAD

**Issue by Slapbox** [react-native-community/react-native-webview#788]
**Bug description:**
This was previously working, but suddenly doesn't for me. When a component containing a Webview is mounted, but not visible on the screen, it won't load HTML content, seems like 95% of the time in `production`. Oddly, in `development`, it _usually_ works properly, which makes debugging this phantom issue nearly impossible.

**To Reproduce:**
```js
<View
  style={{
    display: 'none',
    flex: -1,
    height: 0,
    width: 0,
    zIndex: -100,
  }}>
  <WebView
    style={{ flex: 1 }}
    useWebkit
    ref={this.myWebview}
    originWhitelist={['*']}
    source={{
      html: this.myHtml,
      baseUrl: '',
    }}
  />
</View>
```

Removing `display: 'none'` has no effect, and setting a `height` and `width` of `1px` does not resolve the issue.

**Expected behavior:**
The Webview should load the `source` when the component containing the Webview is mounted. When I ensure the Webview is visible it loads the content, but again, only 95% of the time.

**Screenshots/Videos:**
None, Webview is intentionally not visible.

**Environment:**
 - OS: `Android`
 - OS version: `9` 
 - react-native version: `59.8 (Expo SDK34)`
 - react-native-webview version: `5.12.0`

**Additional Details:**
This issue is really difficult to debug, because it only fails to load the HTML about 95% of the time when hidden. When the Webview is visible, it only succeeds in loading the HTML ~95%. I can't find any consistent place to begin debugging because I can't reproduce the issue with 100% success.

The **_only_** changes to my project since this suddenly became an issue were upgrading Expo from 33 to 34, and upgrading `react-native-webview` from `5.8.1` to `5.12.0`. I tried downgrading to `5.8.1`, but the issue is there too.

If this is an intentional changes or there's some throttling applied to Webviews that aren't visible to the user, I don't see it mentioned anywhere for either project

**Comment by Slapbox** [comment]
Hard to say with certainty what made the difference here, but I have gotten my code to run properly now. I think the key was wrapping in a `View` styled like this instead:

```js
<View
  style={{
    overflow: 'hidden',
    maxHeight: 0,
    maxWidth: 0,
    flex: 1,
  }}>
```

Who knows though, strangest issue.

**Comment by jinhale** [comment]
As far as I can tell setting the parent container to `flex: 1` is what fixes it.

Here is a broken example:
```
    <View>
      <WebView
        originWhitelist={['*']}
        source={{ html: '<h1>This is a static HTML source!</h1>' }}
      />
    </View>
```

Here is a working example: 
```
    <View
      style={{
        flex: 1,
      }}
    >
      <WebView
        originWhitelist={['*']}
        source={{ html: '<h1>This is a static HTML source!</h1>' }}
      />
    </View>
```

**Comment by michaelVictoriaDev** [comment]
any update ?

**Comment by Slapbox** [comment]
@michaelVictoriaDev - no luck with the list of styles I posted? I feel pretty confident that this worked with merely `flex: 1` prior to `5.12.x`. Since you're seeing this issue I'll reopen my issue.

**Comment by marcodafonseca** [comment]
> @michaelVictoriaDev - no luck with the list of styles I posted? I feel pretty confident that this worked with merely `flex: 1` prior to `5.12.x`, so I wonder what changed by `5.12.x`. Since you're seeing this issue I'll reopen my issue.

Your `flex: 1` seems to still do the trick (for me at least anyway). However, I found it ONLY works when applied to the outer most View tag that the WebView resides in. Wrapping the WebView inside of a View directly doesn't seem to work.

The following did not work for me:
`<View>
    <Text>Some Label</Text>
    <View style={{ flex: 1}}>
        <WebView source={{ html: '<h1>Some Heading</h1>' }}></WebView>
    </View>
</View>`

The following did work for me:
`<View style={{ flex: 1}}>
    <Text>Some Label</Text>
    <WebView source={{ html: '<h1>Some Heading</h1>' }}></WebView>
</View>`

**Comment by sk92129** [comment]
I have tried the combinations mentioned above but the inline html content still seems empty or not visible.
https://github.com/sk92129/webviewmodal

**Comment by Slapbox** [comment]
@sk92129 I set a background color on the HTML within the webview, like bright red, and then kept messing with rules until I managed to find some hint of it, and worked from there. Sorry I can't be of more help.

**Comment by Slapbox** [comment]
Probably a different issue - but I just came back to my code today and suddenly Webviews never load again. Tried clearing `node_modules` and Yarn cache, clearing Metro and Haste caches, uninstalling and reinstalling the app, loading previous commits, but nothing works. The only thing I haven't tried is a new emulator. All the rest of our code works fine, and it worked fine last night when I stopped my work for the night. Baffling.

**Comment by passivedragon** [comment]
I just happened to stumble over some react-native, and while trying to mess around with the basic examples I've also run into this issue. For me, however, I haven't gotten a webview to show up at all yet so far.

**Comment by VityaSchel** [comment]
It's loading, but not rendered. Expo dev client

**Comment by elabayoub** [comment]
for me it was removing `flex: 1;` that fixed it.

**Comment by sirus-max** [comment]
explicitly give height and width to the webview like
```
<WebView source={{ uri: 'https://www.google.com' }} style={{height:300, width:200}} />
```
then it becomes visible

**Comment by dennyboechat-idexx** [comment]
You may want to try this:
```
const { height, width } = Dimensions.get('window');

  return (
    <SafeAreaView>
      <WebView
        style={{ height, width }}
        source={{
          uri: 'some site url',
        }}
      />
    </SafeAreaView>
  );
```
