### ISSUE TITLE
Build falilure on iOS: library not found for -lRNCWebView

### ISSUE THREAD

**Issue by H-Shafiei** [react-native-community/react-native-webview#793]
**Bug description:**

I have tried to update my react-native version from 0.59.10 to 0.60.5. When I build the iOS version it throws an error:
`ld: library not found for -lRNCWebView
clang: error: linker command failed with exit code 1 (use -v to see invocation)`
I have tried to link it manually or ad the pod in Podfile explicitly but the error remains.

**Environment:**
 - OS: macOS
 - OS version: Mojave
 - react-native version: 0.60.5
 - react-native-webview version: 6.9.0

**Comment by MLY123** [comment]
我的和你的一样，但是我手动链接之后OK了，我这边的问题是用它发消息接受不到

**Comment by H-Shafiei** [comment]
The issue is solved. The problem was libRNCWebView.a was linked while it should be removed from linked libraries. 
P.S: For upgrading it is better to unlink all libraries before upgrading and then start upgrading.

**Comment by rajnishrajput** [comment]
you need to install webview - 
npm install --save react-native-webview
react-native link react-native-webview
