### ISSUE TITLE
Android: Blank screen when several redirects and onLoadStart defined

### ISSUE THREAD

**Issue by gianlucaparadise** [react-native-community/react-native-webview#796]
**Bug description:**

An URI that generates several redirects will result in a blank screen. This happnes only when `onLoadStarted` is defined and a debugger is not attached. When a debugger is attached or `onLoadStarted` is not defined, it correctly works.

**To Reproduce:**

[Repo](https://github.com/gianlucaparadise/react-native-webview-issue) to reproduce the bug.

**Expected behavior:**

I expect to see the webpage correctly loaded and displayed.

**Screenshots/Videos:**

N/A

**Environment:**
 - OS: Android
 - OS version: 9 (on emulator)
 - react-native version: 0.60.5
 - react-native-webview version: 6.9.0

**Notes:**
I also tried the following conbination with the following outcome:

1. Uri `https://accounts.spotify.com/it/login/`
    * **N.B.** This uri doesn't perform any redirect
    * Outcome: always works

2. Uri `https://www.spotify.com/it/account/overview/`
    * **N.B.** This uri performs several redirects
    * Outcome (see table below):

| OnLoadStart defined? | Debugger attached? |       Works?        |
|:--------------------:|:------------------:|:-------------------:|
|          No          |         Yes        |        ✅Yes        |
|          No          |         No         |        ✅Yes        |
|          Yes         |         Yes        |        ✅Yes        |
|          Yes         |         No         | ❌No (Blank screen) |

**Comment by neelrocketbots** [comment]
Hi is there any updates on this issue? It is affecting me as well
