### ISSUE TITLE
How can I open apk file I just download from Webview?

### ISSUE THREAD

**Issue by zhuliminl** [react-native-community/react-native-webview#798]
I am trying to use react-native-webview to download Android apk file. It could download apk file actually!

**But How can I know when file is download success and get file path or automatically install the apk file I just download?**

is there any good ideal to make it happen? very thanks

**Comment by zhuiye** [comment]
add following permission  in  AndroidManifest.xml , 
```
<uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES"/>
```

**Comment by ahsan-abrar** [comment]
@zhuliminl hi, can you please share the code how you download apk file in webview
