### ISSUE TITLE
How to list/close tabs? [Android]

### ISSUE THREAD

**Issue by jejopl** [react-native-community/react-native-webview#800]
I was surprised when I debugged the app in chrome I saw that my app has opened multiple tabs. Is there a way to close those tabs? I couldn't find the solution on the Internet. I don't even know the other way how to check how many tabs are opened except for using Chrome -> connected devices for debugging

Here's a screen from Chrome -> connected devices:

![react-native-tabs](https://user-images.githubusercontent.com/32012330/63580190-8fce3b80-c594-11e9-9d00-b6646bf41449.png)

Is there a way to list/close those tabs?

Here's my render function:

```
   return (
      <WebView
        source={{ uri: this.state.url }}
        style={{
          width: "100%",
          flex: 3,
          flexWrap: "wrap",
          backgroundColor: this.webView.bgColor
        }}
        ref={webView => {
          this.webView.ref = webView;
        }}
        onMessage={e => this.onMessage(e)}
        onLoadProgress={e => this.onLoad(e.nativeEvent)}
        onLoadEnd={() => this.props.removeSplashScreen()}
        renderError={() => this.loadingError()}
        onNavigationStateChange={this.onUrlChange}
        javaScriptEnabled={true}
        domStorageEnabled={true}
        startInLoadingState={false}
        mixedContentMode="always"
        key={this.state.key}
      />
    );
  }
}
```

**Comment by iamisathya** [comment]
+1
