### ISSUE TITLE
lint failed

### ISSUE THREAD

**Issue by vinurs** [react-native-community/react-native-webview#802]
> Task :react-native-webview:lint FAILED
Ran lint on variant release: 11 issues found
Ran lint on variant debug: 11 issues found
Wrote HTML report to file:///Users/vinurs/system-configuration/work/glm/GlmApp/node_modules/react-native-webview/android/build/reports/lint-results.html
Wrote XML report to file:///Users/vinurs/system-configuration/work/glm/GlmApp/node_modules/react-native-webview/android/build/reports/lint-results.xml

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-webview:lint'.
> Lint found errors in the project; aborting build.

  Fix the issues identified by lint, or add the following to your build script to proceed with errors:
  ...
  android {
      lintOptions {
          abortOnError false
      }
  }
  ...

  The first 3 errors (out of 4) were:
  /Users/vinurs/system-configuration/work/glm/GlmApp/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java:369: Error: Call requires API level 21 (current min is 16): android.webkit.CookieManager#removeAllCookies [NewApi]
      CookieManager.getInstance().removeAllCookies(null);
                                  ~~~~~~~~~~~~~~~~
  /Users/vinurs/system-configuration/work/glm/GlmApp/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java:780: Error: Call requires API level 21 (current min is 16): android.webkit.PermissionRequest#getResources [NewApi]
        String[] requestedResources = request.getResources();
                                              ~~~~~~~~~~~~
  /Users/vinurs/system-configuration/work/glm/GlmApp/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java:804: Error: Call requires API level 21 (current min is 16): android.webkit.PermissionRequest#deny [NewApi]
          request.deny();
                  ~~~~

**Comment by vinurs** [comment]
this need to set the min sdk version to 21

**Comment by TakaKeiji** [comment]
> 
> 
> this need to set the min sdk version to 21

Same issue here, i've changed the minSdkVersion to 21, and still getting the error...

**Comment by TakaKeiji** [comment]
> 
> 
> > this need to set the min sdk version to 21
> 
> Same issue here, i've changed the minSdkVersion to 21, and still getting the error...

I've managed to solve this issue updating to the lastest graddle version with Android studio, keeping minSdkVersion to 21 and cleaning the build folder.

**Comment by vinurs** [comment]
everytime u npm add pkg or yarn add pkg, u need to re-edit the file node_modules/react-native-webview/android/build.gradle to modify the minSdkVersion to 21

**Comment by TakaKeiji** [comment]
> everytime u npm add pkg or yarn add pkg, u need to re-edit the file node_modules/react-native-webview/android/build.gradle to modify the minSdkVersion to 21

The way you explain that, sounds like a bug... But thanks to explain it 👍

**Comment by jasong-peakbagger** [comment]
I too am seeing this issue and it is corrected by changing minSdkVersion to 21 in the react-native-webview gradle file. My challenge has been with our CI build job. Since the project is built from scratch every time, the gradle file doesnt exist until "gradle build" command is run. I'm presuming Ill need to:
- Ignore linting errors on first "gradle build" run.
- Modify the file after it is created.
- Then run "gradle lint" to ensure that linting is passing.

Anyone else working around this in a build job?

**Comment by vinurs** [comment]
in my build script, i add this:
```
sed -i "s/minSdkVersion 16/minSdkVersion 21/g" node_modules/react-native-webview/android/build.gradle
```

**Comment by jasong-peakbagger** [comment]
Thanks! @vinurs Love one liners. Here was another way I came up in case it helps others. 

`lint.doFirst {
    def rnWebviewGradleFile = new File("$rootDir/../node_modules/react-native-webview/android/build.gradle")
    ant.replace(file: rnWebviewGradleFile, token: "minSdkVersion 16", value: "minSdkVersion 21")
}`

**Comment by vantb9x** [comment]
hi @vinurs Did you change minSdkVersion in app/build.gradlew in your project?
I add your line into my gradlew but when it build, it shows:
/node_modules/react-native-webview/android/build/intermediates/library_manifest/debug/AndroidManifest.xml as the library might be using APIs not available in 16
