### ISSUE TITLE
how can i remote debug webview in chrome developer tools

### ISSUE THREAD

**Issue by buruoyanyang** [react-native-community/react-native-webview#803]
Can we debug our webview in chrome developer tools, use by url : chrome://inspect/#devices .
It looks like there is no doc for it, so it is not supported?

**Comment by Titozzz** [comment]
Have you read docs/Debugging.md ....?

**Comment by buruoyanyang** [comment]
> Have you read docs/Debugging.md ....?

I am so sorry...thanks
