### ISSUE TITLE
HTTPS iFrames not loading inside local HTML file

### ISSUE THREAD

**Issue by joarwilk** [react-native-community/react-native-webview#804]
Hey, this is mostly for documentation purposes in case anyone else comes across the same issue.

**Bug description:**
https iframes loaded inside an HTML file loaded locally will fail to load.

**Expected behavior:**
The https iframe should load its content.

**Environment:**
 - react-native version: 0.59.3
 - react-native-webview version: 6.9.0

# Solution
Host your HTML on any host which supports SSL (like S3). The iframes will load and work as expected.

If anyone has a different solution let me know.

**Comment by lapico** [comment]
Thanks for your issue, it helped.

I made in work with a local uri like this :

```
import {useAssets} from 'expo-asset';
import {Platform} from 'react-native';
import {WebView} from 'react-native-webview';
...
  const [assets] = useAssets([require('../../../assets/myhtml.html')]);
  const htmlAsset = assets?.[0];
...
      <WebView
        source={
          htmlAsset
            ? {
                uri:
                  Platform.OS === 'android'
                    ? htmlAsset.localUri
                    : htmlAsset.uri,
              }
            : undefined
        }
        onMessage={event => {
          console.log(JSON.parse(event.nativeEvent.data));
        }}
        startInLoadingState={true}
        originWhitelist={['*']}
        allowFileAccess={true}
        allowUniversalAccessFromFileURLs={true}
      />
...
```
