### ISSUE TITLE
How to remove white bar on top of webview?

### ISSUE THREAD

**Issue by expouic** [react-native-community/react-native-webview#808]
When I open any page within Webview, a white bar appears at the top of the screen.

I've already include UIViewControllerBasedStatusBarAppearance (true and false) in my Info.plist file but the changes not as I expected. This only affects the visibility of first line of the picture (date time and battery percentage)

**Screenshots/Videos:**
![image](https://i.imgur.com/Za6BoLX.png)

My current code to invoke WebView

```
<WebView
originWhitelist={['*']}
ref={c => {this.WebView = c;}}
source={{uri: "http://localhost/my-page.html"}}
style={{flex:1, width: '100%', height: '100%'}}
/>
```

**Environment:**
 - OS: macOS Mojave
 - OS version: 10.14.6
 - react-native version: 0.60
 - react-native-webview version: ^6.90

**Comment by expouic** [comment]
My mistake!
To hide header i need to add  ```header:null``` on navigationOptions of router!

**Comment by drbarto** [comment]
Hey @expouic I have the same issue you described, but I don't know how to apply your fix. Is `navigationOptions` something from another framework (probably `react-native-navigation`)?

**Comment by expouic** [comment]
@drbarto you are correct. On react-native-navigation when you create the routes of your app.

ex:
```
  return createDrawerNavigator(
    {
      StartScreen: {
        screen: StartScreen,
      },
    },
    {
      headerMode: 'none',
      cardShadowEnabled: false,
      unmountInactiveRoutes: true,
      initialRouteName: 'StrartScreen',
      contentComponent: MainMenu,
    },
  );
```

**Comment by drbarto** [comment]
@expouic thanks for the quick reply :) So the fix is not applicable for me, but happy that it worked for you 👍
