### ISSUE TITLE
Android is crashing when "WebView" is wrapped by "View"

### ISSUE THREAD

**Issue by pavermakov** [react-native-community/react-native-webview#811]
**Bug description:**
I have an autosized webview that works perfectly on ios:

```
import React, { useState } from "react";
import { View } from "react-native";
import { WebView } from "react-native-webview";
import PropTypes from "prop-types";

const BODY_TAG_PATTERN = /<\/ *body>/;

const code = `
    <style>
        body, html {
            margin: 0;
            padding: 0;
        }
    </style>

    <script>
        window.ReactNativeWebView.postMessage(document.body.scrollHeight, '*');
    </script>
`;

const injectCode = (html) => {
    return html.replace(BODY_TAG_PATTERN, `${code}</body>`);
};

const WebViewAutoHeight = ({ html, style }) => {
    const [contentHeight, setContentHeight] = useState(1);

    const adjustHeight = (event) => {
        setContentHeight(parseInt(event.nativeEvent.data));
    };

    if (!html) {
        throw new Error("At this moment, WebViewAutoHeight only supports html files");
    }

    if (!BODY_TAG_PATTERN.test(html)) {
        throw new Error(`Cannot find </body> from: ${html}`);
    }

    return (
        <View style={[style, { height: contentHeight }]}>
            <WebView
                source={{ html: injectCode(html) }}
                onMessage={adjustHeight}
            />
        </View>
    );
};

WebViewAutoHeight.propTypes = {
    html: PropTypes.string.isRequired,
    style: PropTypes.any
};

WebViewAutoHeight.defaultProps = {
    style: null
};

export default WebViewAutoHeight;
```
However, when I try to use it on android, the app crashes without a message. Then I decided to remove everything and replaced the render method with the following:

```
<View>
   <WebView
        source={{ uri: 'https://infinite.red' }}
        style={{ marginTop: 20 }}
   />
</View>
```

but it was still crashing. Then I removed the outer view element and it worked!

**Expected behavior:**
The android app should not crash

**Environment:**
 - OS: macOS Mojave
 - OS version: 10.14.5
 - react-native version: 0.59.8
 - react-native-webview version: 6.9.0

**Comment by Rendfold** [comment]
What was the solution?

**Comment by Renji3** [comment]
@Rendfold I managed to come across this link in my research: https://www.gitmemory.com/issue/react-native-community/react-native-webview/430/493976111

Apperently this bug can be fixed by changing the Opacity of the webviwe to 0.99 instead of the default value of 1. Setting the overflow value to "hidden" prevents that the background will be visible.

This worked for me as a fix
Altho the androud crash did only appeare when I pressed the back button and by this dismissed the screen. I am also using react navigation which probably played a role as well.

**Comment by pmm1** [comment]
I had the same issue and it worked to set the opacity to 0.99 - Absolutely ridiculous that this works however, makes absolutely no sense.

**Comment by jonsaich** [comment]
Just spent far too long working on a solution for this. I didn't get any of the above solutions to work, however setting `androidHardwareAccelerationDisabled={true}` on the WebView did work.

**Comment by machadolucasvp** [comment]
@jonsaich and @pmm1 solutions work for me but i prefer `androidHardwareAccelerationDisabled={true}` less error prone, some developer can be confused about the opacity solution and accidentaly remove it..

**Comment by Ashutosh8127** [comment]
thanks @jonsaich

**Comment by Anna18921** [comment]
> As soluções @jonsaich e @ pmm1 funcionam para mim, mas eu prefiro `androidHardwareAccelerationDisabled={true}`. Menos sujeito a erros, alguns desenvolvedores podem ficar confusos sobre a solução de opacidade e removê-la acidentalmente.
> 
> Atualizando: bem `androidHardwareAccelerationDisabled={true}`, no meu caso tem uma grande desvantagem de desempenho, agora estou usando a solução de opacidade ...

thanks, problem revolved

**Comment by spsaucier-bakkt** [comment]
In our case, `androidHardwareAccelerationDisabled={true}` worked, while `opacity: 0.99` _did not_. We have had to apply this fix to all webviews in our app. This issue was easiest to reproduce on LG Stylo 6 and Google Pixel devices.

**Comment by sooakim** [comment]
```jsx
<View
   renderToHardwareTextureAndroid={true}>
   <WebView
        source={{ uri: 'https://infinite.red' }}
        style={{ marginTop: 20 }}
   />
</View>
```
In my case, I fixed it by adding `renderToHardwareTextureAndroid={true}` on it's parent View.

**Comment by JuanDavidLopez95** [comment]
Hi all,

I am using Expo SDK v40 as well as react navigation. I was running into this very same error but was able to fix the issue by setting the `androidHardwareAccelerationDisabled` property on the WebView component to be true.

**Comment by lostintime** [comment]
Had the same issue, Expo SDK v40 both: `androidHardwareAccelerationDisabled` and `{ opacity: 0.99, overflow: 'hidden' }` solutions fixed app crashing but `androidHardwareAccelerationDisabled` adds visible lags to webview rendering, @Renji3, @jonsaich jonsaich thanks for the fix.

**Comment by prakashtank** [comment]
> Just spent far too long working on a solution for this. I didn't get any of the above solutions to work, however setting `androidHardwareAccelerationDisabled={true}` on the WebView did work.

Thank you, its work, save my time.

**Comment by zachnicoll** [comment]
Can confirm that applying styles `{ opacity: 0.99, overflow: 'hidden' }` to the WebView fixed this issue for me.

`androidHardwareAccelerationDisabled={true}` stopped the crashing but the video was black. You could press the play button but not see the video at all.

Very peculiar....

**Comment by luluanacarla** [comment]
> Just spent far too long working on a solution for this. I didn't get any of the above solutions to work, however setting `androidHardwareAccelerationDisabled={true}` on the WebView did work.

It worked like a charm! thanks :)

**Comment by praneeth-hiver** [comment]
> Just spent far too long working on a solution for this. I didn't get any of the above solutions to work, however setting `androidHardwareAccelerationDisabled={true}` on the WebView did work.

androidHardwareAccelerationDisabled did work for me but few webviews didn't load after setting this to true. Moved to the opacity solution. Just in case if anyone else is facing the same.

**Comment by DinsmoreDesign** [comment]
I'm on 11.13.0 and none of these fixes work 😢

**Comment by KapelPTronic** [comment]
Same problem like @DinsmoreDesign !!

**Comment by CodingLime** [comment]
I'm on 11.6.2 and also none of these fixes are working for me.

**Comment by MineSlim** [comment]
no one found a fix yet? i'm having the same problem, the opacity trick is not working, neither the hardware acceleration one.

**Comment by luiztools** [comment]
WebView with style={{ opacity: 0.99, overflow: 'hidden' }} worked for me too, thanks for this thread!

**Comment by Tracer1337** [comment]
Using ``androidLayerType="software`` solves the problem, but performance becomes horrible this way. Another workaround is to unmount the webview when leaving the screen, but this comes with its own problems.

**Comment by vertazzar** [comment]
I managed to fix this by setting view style to, webview ^11.17.1

```
        <View
          style={{
            height: window.height,
            width: window.width,
            maxHeight: '100%',
          }}>
          <WebView source={{uri: route.params.url}} />
        </View>
```

**Comment by syed-imam** [comment]
setting style={{ opacity: 0.99, overflow: 'hidden' }} on the webview fixes the crash on android for us as well

**Comment by TripleSteak88** [comment]
I have the same issue and tried all the mentionned solutions, but only the androidLayerType="software" shared by @Tracer1337 worked. Thanks!

**Comment by dex-labs** [comment]
using `androidLayerType="software"` or `androidHardwareAccelerationDisabled={true}` seem to fix it,

**Comment by linxianxi** [comment]
opacity=0.99 or react-navigation animationEnabled=false works for me.
androidLayerType="software" has a very bad impact on performances.

**Comment by iabdulrahmanjo** [comment]
changing the animation type in react navigation v6 from `default` in android to something similar like `fade_from_bottom`. works for me.

example:
`animation: Platform.OS === 'android' ? 'fade_from_bottom' : 'default',`

**Comment by nguyenrazona** [comment]
For those who are big suffered by this problem!
I've tried all of the above remedies, but none of them work in RN 0.69 and React Navigation 6.
So I've used "transitionEnd" event of React Navigation, I've solved this.
Below is my worked code.

// React component class file
constructor(props) {
super(props)
this.state = {
isWebViewLoaded: false,
}

props.navigation.addListener('transitionEnd', () => {
    this.setState({ isWebViewLoaded: true })
})

props.navigation.addListener('beforeRemove', () => {
  this.setState({ isWebViewLoaded: false })
})
}

render() {
return (
<View style={{ flex: 1, position: 'relative' }}>
{this.state.isWebViewLoaded && (
<WebView
source={{
uri: 'https://google.com/',
headers: { 'Cache-Control': 'no-cache' },
}}
renderError={() => {
return (
<View
style={{
flex: 1,
alignItems: 'center',
justifyContent: 'center',
}}
>
Network connection error.

)
}}
/>
)}

)

// package.json file
"@react-navigation/native": "^6.0.11",
"@react-navigation/native-stack": "^6.7.0",
"@react-navigation/stack": "^6.2.2",
"react": "18.2.0",
"react-native": "0.69.1",
"react-native-gesture-handler": "^2.5.0",
"react-native-screens": "^3.15.0",
"react-native-webview": "^11.22.7"

**Comment by BDDev** [comment]
We use a hidden webview in our authentication process. After logging in, we navigate the user to another screen. Then we get this crash on android. We are using react-navigation v5.

We were already using the `androidHardwareAccelerationDisabled` prop fix until upgrading React Native from 63 to 66. 

At v66, none of the above solutions in this issue worked. However, we noticed that our wrapper `componentWillUnmount` lifecycle method wasn't getting called. 

So our solution was to have our parent screen component listen to react-navigation events: `transitionEnd` & `blur` to keep a `hasNavigationTransitioned` boolean:
```ts
useEffect(() => navigation.addListener('transitionEnd', () => {
  setHasNavigationTransitioned(true);
}), [navigation, setHasNavigationTransitioned]);

useEffect(() => navigation.addListener('blur', () => { 
  setHasNavigationTransitioned(false);
}), [navigation, setHasNavigationTransitioned]);
```


Then, use that boolean to conditionally render the WebView:
```jsx
            <View style={styles.hideMe}>
                {hasNavigationTransitioned ? (
                    <WebView
                        source={{ uri }}
                        androidHardwareAccelerationDisabled
                    />
                ) : null}
            </View>
```

**Comment by jaanisfehling** [comment]
Not working with any of the above solutions using React Native 0.71.1, not even @BDDev's answer.
The only way it seems to work is not wrapping the WebView component in any other component. The only way I could implement other UI components was through the header.

**Comment by 17Amir17** [comment]
@BDDev's solution worked for me without `androidHardwareAccelerationDisabled`

**Comment by white-room** [comment]
> ```js
> <View
>    renderToHardwareTextureAndroid={true}>
>    <WebView
>         source={{ uri: 'https://infinite.red' }}
>         style={{ marginTop: 20 }}
>    />
> </View>
> ```
> 
> In my case, I fixed it by adding `renderToHardwareTextureAndroid={true}` on it's parent View.

This is what worked for us with the least perf hit. Thanks @sooakim!

**Comment by bipul-yadav-1** [comment]
Solved by using flex:1 in View and WebView style.

**Comment by bruiz-keepup** [comment]
> ```js
> <View
>    renderToHardwareTextureAndroid={true}>
>    <WebView
>         source={{ uri: 'https://infinite.red' }}
>         style={{ marginTop: 20 }}
>    />
> </View>
> ```
> 
> In my case, I fixed it by adding `renderToHardwareTextureAndroid={true}` on it's parent View.

Thanks

**Comment by hoangdvAT** [comment]
> 

You saved my day :D

**Comment by Dat-Mobile** [comment]
```
useEffect(() => navigation.addListener('transitionEnd', () => {
  setHasNavigationTransitioned(true);
}), [navigation, setHasNavigationTransitioned]);

useEffect(() => navigation.addListener('blur', () => { 
  setHasNavigationTransitioned(false);
}), [navigation, setHasNavigationTransitioned]);
```
Thanks @BDDev the solution works
This should be a big problem to address, crash still happen in 2023

**Comment by Jolteon18** [comment]
If your WebView is also inside in a ScrollView, add to the scrollview this: `overScrollMode="never"`
it fixed it in my case

**Comment by donni106** [comment]
> ```js
> <View
>    renderToHardwareTextureAndroid={true}>
>    <WebView
>         source={{ uri: 'https://infinite.red' }}
>         style={{ marginTop: 20 }}
>    />
> </View>
> ```
> 
> In my case, I fixed it by adding `renderToHardwareTextureAndroid={true}` on it's parent View.

`renderToHardwareTextureAndroid` on the parent was the fix for me! thanks!

**Comment by tyawei** [comment]
> If your WebView is also inside in a ScrollView, add to the scrollview this: `overScrollMode="never"` it fixed it in my case, without adding the opacity or hardware fixes

this answer saved my life!

**Comment by hieunh1801** [comment]
> `opacity=0.99` or react-navigation `animationEnabled=false` works for me. `androidLayerType="software"` has a very bad impact on performances.

 <Stack.Screen
    ...
    options={{
      ...
      animation: 'none',
    }}
  />
  
  Thank you very much
