### ISSUE TITLE
Inject javascript not loading automatically.

### ISSUE THREAD

**Issue by betorams** [react-native-community/react-native-webview#814]
I'm new to react and I've been playing around with the webview inject javascript to modify the url's css. However, I noticed that in the default version loads the injected javascript instantaneously,
with this library it takes time to actually apply it. 

**Apply injected JavaScript is not instantaneously**

**Before**
![Screenshot_1566936756](https://user-images.githubusercontent.com/21222826/63805752-bb785b00-c8df-11e9-96f8-705c1ed07f44.png)
**After**
![Screenshot_1566936777](https://user-images.githubusercontent.com/21222826/63805781-caf7a400-c8df-11e9-8454-f3fa7602d5c8.png)

**Comment by Titozzz** [comment]
I don't understand your issue

**Comment by betorams** [comment]
@Titozzz on the default webview of react native, the css modifications made with inject javascript were applied immediately. Now with this library, it takes time to actually load those modifications.
