### ISSUE TITLE
Not possible to set scrollIndicatorInsets

### ISSUE THREAD

**Issue by chrise86** [react-native-community/react-native-webview#817]
As of, I believe, `6.2.1` it is now possible to correctly set `contentInset` on iOS. However, it is not possible to set `scrollIndicatorInsets`, which will quite often go hand in hand with the content insets.

It's also not possible to use `contentContainerStyle` to get around it that way.

**Comment by gavrichards** [comment]
It would be great to see this implemented. We have a webview which goes behind a static semi-transparent bar at the bottom, so we use the content inset to ensure all the content of the webview is reachable, but it looks odd that the scroll bar disappears behind that bar.
