### ISSUE TITLE
WTF::HashTable Crash

### ISSUE THREAD

**Issue by zek** [react-native-community/react-native-webview#820]
**Bug description:**

EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000a00
WTF::HashTable<WTF::String, WTF::String, WTF::IdentityExtractor, WTF::StringHash, WTF::HashTraits<WTF::String>, WTF::HashTraits<WTF::String> >::add(WTF::String const&)

Crashed: WebThread
0  WebCore                        0x1e2ac67b4 WTF::HashTable<WTF::String, WTF::String, WTF::IdentityExtractor, WTF::StringHash, WTF::HashTraits<WTF::String>, WTF::HashTraits<WTF::String> >::add(WTF::String const&) + 40
1  WebCore                        0x1e3277c74 WebCore::ResourceLoadNotifier::dispatchWillSendRequest(WebCore::DocumentLoader*, unsigned long, WebCore::ResourceRequest&, WebCore::ResourceResponse const&) + 156
2  WebCore                        0x1e3277c74 WebCore::ResourceLoadNotifier::dispatchWillSendRequest(WebCore::DocumentLoader*, unsigned long, WebCore::ResourceRequest&, WebCore::ResourceResponse const&) + 156
3  WebCore                        0x1e327de88 WebCore::ResourceLoader::willSendRequestInternal(WebCore::ResourceRequest&&, WebCore::ResourceResponse const&, WTF::CompletionHandler<void (WebCore::ResourceRequest&&)>&&) + 1136
4  WebCore                        0x1e3288364 WebCore::SubresourceLoader::willSendRequestInternal(WebCore::ResourceRequest&&, WebCore::ResourceResponse const&, WTF::CompletionHandler<void (WebCore::ResourceRequest&&)>&&)::$_1::operator()(WTF::CompletionHandler<void (WebCore::ResourceRequest&&)>&&, WebCore::ResourceRequest&&) + 316
5  WebCore                        0x1e3286908 WebCore::SubresourceLoader::willSendRequestInternal(WebCore::ResourceRequest&&, WebCore::ResourceResponse const&, WTF::CompletionHandler<void (WebCore::ResourceRequest&&)>&&) + 768
6  WebCore                        0x1e327d1cc WebCore::ResourceLoader::init(WebCore::ResourceRequest&&, WTF::CompletionHandler<void (bool)>&&) + 348
7  WebCore                        0x1e32865a0 WebCore::SubresourceLoader::startLoading() + 156
8  WebKitLegacy                   0x1e3c891a0 WebResourceLoadScheduler::servePendingRequests(WebResourceLoadScheduler::HostInformation*, WebCore::ResourceLoadPriority) + 516
9  WebKitLegacy                   0x1e3c8c2e0 WTF::Function<void (WTF::RefPtr<WebCore::SubresourceLoader, WTF::DumbPtrTraits<WebCore::SubresourceLoader> >&&)>::CallableWrapper<WebResourceLoadScheduler::loadResource(WebCore::Frame&, WebCore::CachedResource&, WebCore::ResourceRequest&&, WebCore::ResourceLoaderOptions const&, WTF::CompletionHandler<void (WTF::RefPtr<WebCore::SubresourceLoader, WTF::DumbPtrTraits<WebCore::SubresourceLoader> >&&)>&&)::$_0>::call(WTF::RefPtr<WebCore::SubresourceLoader, WTF::DumbPtrTraits<WebCore::SubresourceLoader> >&&) + 44
10 WebCore                        0x1e3286410 WebCore::SubresourceLoader::create(WebCore::Frame&, WebCore::CachedResource&, WebCore::ResourceRequest&&, WebCore::ResourceLoaderOptions const&, WTF::CompletionHandler<void (WTF::RefPtr<WebCore::SubresourceLoader, WTF::DumbPtrTraits<WebCore::SubresourceLoader> >&&)>&&) + 312
11 WebKitLegacy                   0x1e3c88b6c WebResourceLoadScheduler::loadResource(WebCore::Frame&, WebCore::CachedResource&, WebCore::ResourceRequest&&, WebCore::ResourceLoaderOptions const&, WTF::CompletionHandler<void (WTF::RefPtr<WebCore::SubresourceLoader, WTF::DumbPtrTraits<WebCore::SubresourceLoader> >&&)>&&) + 108
12 WebCore                        0x1e32b5bf8 WebCore::CachedResource::load(WebCore::CachedResourceLoader&) + 2568
13 WebCore                        0x1e32ba358 WebCore::CachedResourceLoader::requestResource(WebCore::CachedResource::Type, WebCore::CachedResourceRequest&&, WebCore::CachedResourceLoader::ForPreload, WebCore::CachedResourceLoader::DeferOption) + 5076
14 WebCore                        0x1e32bb6c8 WebCore::CachedResourceLoader::requestScript(WebCore::CachedResourceRequest&&) + 52
15 WebCore                        0x1e2c4faac WebCore::CachedScriptFetcher::requestScriptWithCache(WebCore::Document&, WTF::URL const&, WTF::String const&, WTF::String&&) const + 644
16 WebCore                        0x1e2ef05b0 WebCore::LoadableClassicScript::load(WebCore::Document&, WTF::URL const&) + 64
17 WebCore                        0x1e2f27a3c WebCore::ScriptElement::requestClassicScript(WTF::String const&) + 936
18 WebCore                        0x1e2f26548 WebCore::ScriptElement::prepareScript(WTF::TextPosition const&, WebCore::ScriptElement::LegacyTypeSupport) + 644
19 WebCore                        0x1e2f262b8 WebCore::ScriptElement::didFinishInsertingNode() + 28
20 WebCore                        0x1e2e762bc WebCore::ContainerNode::appendChildWithoutPreInsertionValidityCheck(WebCore::Node&) + 808
21 WebCore                        0x1e2e78a30 WebCore::ContainerNode::appendChild(WebCore::Node&) + 80
22 WebCore                        0x1e274ec3c WebCore::jsNodePrototypeFunctionAppendChild(JSC::ExecState*) + 240
23 JavaScriptCore                 0x1e0ca973c llint_entry + 89260
24 JavaScriptCore                 0x1e0ca7d54 llint_entry + 82628
25 JavaScriptCore                 0x1e0ca7d54 llint_entry + 82628
26 JavaScriptCore                 0x1e0ca8748 llint_entry + 85176
27 JavaScriptCore                 0x1e0ca7d54 llint_entry + 82628
28 JavaScriptCore                 0x1e0ca7d54 llint_entry + 82628
29 JavaScriptCore                 0x1e0ca7d54 llint_entry + 82628
30 JavaScriptCore                 0x1e0ca7d54 llint_entry + 82628
31 JavaScriptCore                 0x1e0ca7cb4 llint_entry + 82468
32 JavaScriptCore                 0x1e0ca7cb4 llint_entry + 82468
33 JavaScriptCore                 0x1e0ca7cb4 llint_entry + 82468
34 JavaScriptCore                 0x1e0ca7cb4 llint_entry + 82468
35 JavaScriptCore                 0x1e0c937fc vmEntryToJavaScript + 268
36 JavaScriptCore                 0x1e11c5770 JSC::Interpreter::executeCall(JSC::ExecState*, JSC::JSObject*, JSC::CallType, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&) + 420
37 JavaScriptCore                 0x1e13a7528 JSC::profiledCall(JSC::ExecState*, JSC::ProfilingReason, JSC::JSValue, JSC::CallType, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&) + 188
38 JavaScriptCore                 0x1e1468b34 JSC::JSMicrotask::run(JSC::ExecState*) + 412
39 WebCore                        0x1e2c6436c WebCore::JSExecState::runTask(JSC::ExecState*, JSC::Microtask&) + 88
40 WebCore                        0x1e2c6bac0 WebCore::JSMicrotaskCallback::call() + 84
41 WebCore                        0x1e2e68efc WebCore::ActiveDOMCallbackMicrotask::run() + 72
42 WebCore                        0x1e2ef34cc WebCore::MicrotaskQueue::performMicrotaskCheckpoint() + 104
43 WebCore                        0x1e2c701dc WebCore::JSExecState::didLeaveScriptContext(JSC::ExecState*) + 32
44 WebCore                        0x1e2c56894 WebCore::JSExecState::profiledCall(JSC::ExecState*, JSC::ProfilingReason, JSC::JSValue, JSC::CallType, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&, WTF::NakedPtr<JSC::Exception>&) + 184
45 WebCore                        0x1e2c6dea0 WebCore::JSEventListener::handleEvent(WebCore::ScriptExecutionContext&, WebCore::Event&) + 1084
46 WebCore                        0x1e2ee8790 WebCore::EventTarget::innerInvokeEventListeners(WebCore::Event&, WTF::Vector<WTF::RefPtr<WebCore::RegisteredEventListener, WTF::DumbPtrTraits<WebCore::RegisteredEventListener> >, 1ul, WTF::CrashOnOverflow, 16ul>, WebCore::EventTarget::EventInvokePhase) + 740
47 WebCore                        0x1e2ee5fec WebCore::EventTarget::fireEventListeners(WebCore::Event&, WebCore::EventTarget::EventInvokePhase) + 268
48 WebCore                        0x1e2ee8490 WebCore::EventTarget::dispatchEvent(WebCore::Event&) + 152
49 WebCore                        0x1e32e8d90 WebCore::DOMWindow::postMessageTimerFired(WebCore::PostMessageTimer&) + 192
50 WebCore                        0x1e32f0c9c WebCore::PostMessageTimer::fired() + 108
51 WebCore                        0x1e33d320c WebCore::ThreadTimers::sharedTimerFiredInternal() + 216
52 WebCore                        0x1e33f3258 WebCore::timerFired(__CFRunLoopTimer*, void*) + 28
53 CoreFoundation                 0x1d990b650 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 28
54 CoreFoundation                 0x1d990b380 __CFRunLoopDoTimer + 864
55 CoreFoundation                 0x1d990abb4 __CFRunLoopDoTimers + 248
56 CoreFoundation                 0x1d9905b04 __CFRunLoopRun + 1844
57 CoreFoundation                 0x1d99050b0 CFRunLoopRunSpecific + 436
58 WebCore                        0x1e2595bd8 RunWebThread(void*) + 600
59 libsystem_pthread.dylib        0x1d95982c0 _pthread_body + 128
60 libsystem_pthread.dylib        0x1d9598220 _pthread_start + 44
61 libsystem_pthread.dylib        0x1d959bcdc thread_start + 4

**Environment:**
 - Device: iPhone 6 12.3.1 (16F203)
 - OS: Mac OS X 
 - OS version: Mojave
 - react-native version: 0.60.5 => 0.60.5
 - react-native-webview version: 5.12.1

**Comment by Titozzz** [comment]
No reproduction provided, please open a PR following the template

**Comment by jomla97** [comment]
@zek where you able to find a solution to this issue? It's causing a lot of issues for some of my users and any help would be greatly appreciated.
