### ISSUE TITLE
Callback function needed: `onCanGoBackStateChange`

### ISSUE THREAD

**Issue by HaloWang** [react-native-community/react-native-webview#821]
**Is your feature request related to a problem? If so, Please describe.**

Is there any callback method named `onCanGoBackStateChange`. I need to know `webView.canGoBack` immediately in my problem.

But, sometime these method defined in `WebViewTypes.d.ts` will not be called when HTML `history.length`/`iOS.WKWebView.canGoBack` changed.

```typescript
onLoadingError: (event: WebViewErrorEvent) => void;
onLoadingFinish: (event: WebViewNavigationEvent) => void;
onLoadingProgress: (event: WebViewProgressEvent) => void;
onLoadingStart: (event: WebViewNavigationEvent) => void;
onShouldStartLoadWithRequest: (event: WebViewNavigationEvent) => void;
```

**Describe the solutions you came up with**

I use `setInterval` and `window.ReactNativeWebView.postMessage` to call `onMessage` to get `canGoBack` state. But I know its ugly.

**Additional context**

The HTML I load use `Vue.js`

**Comment by Titozzz** [comment]
Have you tried using onNavigationStateChange ?

**Comment by HaloWang** [comment]
`onNavigationStateChange` is not working for me.

And this is our vue.js source code 😂

```javascript
this.$router.push({ path: 'FooBar?foo=' + 'bar' });
```

**Comment by zs-doron** [comment]
As a workaround, in your Vue app you can call window.ReactNativeWebView.postMessage when you navigate and then use the value from event.nativeEvent.canGoBack.

RN App:

    class App extends Component<Props, State> {
        // ...

        processMessage(event) {
            console.log('Can go back', event.nativeEvent.canGoBack);
        }

        // ...

        navigationStateChange(event) {
            console.log('Can go back', event.nativeEvent.canGoBack);
        }

        // ...

        render() {
            // ...
            return (
                <WebView
                        onMessage={event => this.processMessage(event)}
                        onNavigationStateChange={event => this.navigationStateChange(event)}
                />
            );
        }
    }

In your Webapp (this is React with TS, add this component where you have your router):

    import { withRouter, RouteComponentProps } from 'react-router-dom';

    const HistoryNotifyer = ({ history }: RouteComponentProps<void>) => {
        history.listen(() => {
            // @ts-ignore
            if (window.ReactNativeWebView) {
                // @ts-ignore
                window.ReactNativeWebView.postMessage(JSON.stringify({
                    type: 'historyUpdated'
                }));
            }
        });

        return null;
    };

    export default withRouter(HistoryNotifyer);

**Comment by vnitMendapara** [comment]
Still Searching Solution for this issue.

**Comment by cbotsikas** [comment]
> `onNavigationStateChange` is not working for me.
> 
> And this is our vue.js source code 😂
> 
> ```js
> this.$router.push({ path: 'FooBar?foo=' + 'bar' });
> ```
> 
> It seems like `onNavigationStateChange` will not be called in this case.
> 
> Maybe KVO is useful:
> 
> > ```objc
> > /*! @abstract A Boolean value indicating whether there is a back item in
> > the back-forward list that can be navigated to.
> > @discussion @link WKWebView @/link is key-value observing (KVO) compliant
> > for this property.
> > @seealso backForwardList.
> > */
> > @property (nonatomic, readonly) BOOL canGoBack;
> > ```

Although this is an old thread, maybe it's helpful for others. It appears that `onNavigationStateChange` is not called on Android when the app uses history pushState and popState when navigating back in history. On iOS it is being called just fine. 
I also noticed that `onLoadProgress` is called in both platform so what I did was to use both like this:
```
      onNavigationStateChange={(navState) => {
        // On Android if the page uses history pushState and popState,
        // onNavigationStateChange is not called but onLoadProgress does
        setCanGoBackInWebView(navState.canGoBack);
      }}
      onLoadProgress={(syntheticEvent) => {
        const { nativeEvent } = syntheticEvent;
        // On Android if the page uses history pushState and popState,
        // onNavigationStateChange is not called but onLoadProgress does
        setCanGoBackInWebView(nativeEvent.canGoBack);
      }}
```
You can also inject a script in the web page so that you can inform the app about the history changes like it's implemented at https://github.com/react-native-webview/react-native-webview/issues/1197#issuecomment-644123824, but in this case you need to inject the script and you might don't want to.
