### ISSUE TITLE
getCurrentPosition failed silently

### ISSUE THREAD

**Issue by moh3n9595** [react-native-community/react-native-webview#822]
Hi, I use `react-native-webview@latest` and prompt for location is not showing, why?

> When location is on in my phone, everything works fine

**Code :**
```
<WebView
	source={{ uri: URI }}
	ref={(webview)=>this.webview = webview}
	startInLoadingState
	domStorageEnabled
	javaScriptEnabled
	mixedContentMode='always'
	geolocationEnabled={true}
	allowUniversalAccessFromFileURLs
	javaScriptCanOpenWindowsAutomaticallyEnabled
	allowFileAccess
	originWhitelist={['*']}
```
Can someone create a snack that works fine on `https://mylocation.org/`?

**Comment by hu-qi** [comment]
Hello，has your problem been solved？

**Comment by moh3n9595** [comment]
I still have problem

**Comment by callmejm** [comment]
same , `geolocationEnabled` but nothing prompt out
