### ISSUE TITLE
Web share api and web push notification are not working in webview.

### ISSUE THREAD

**Issue by atultherajput** [react-native-community/react-native-webview#823]
**Bug description:**
Web share API and web push notification are not working.

**To Reproduce:**
I have a PWA and I opened it in webview.

```
<View style={{ flex: 1, backgroundColor: "red" }}>
      <WebView
         source={{ uri: "https://examplepwa.firebaseapp.com" }}
      />
 </View>

```
I have implemented web share API and notification (using Firebase Cloud Messaging).

**Expected behaviour:**
PWA is working perfectly in chrome browser. But in webview it doesn't work. How to support these features in webview?

**Environment:**
 - OS: Linux
 - OS version: Ubuntu 16.04 LTS
 - react-native version: 0.59.8
 - react-native-webview version: 6.9.0

**Comment by atultherajput** [comment]
Found a solution for web share: 
```
nativeShare = async (data) => {
    const shareOptions = {
      title: 'Share via',
      subject: data.subject,
      message: data.message,
      url: data.url
    }
    await Share.open(shareOptions)
  }

  render() {
    return (
      <View style={{ flex: 1, backgroundColor: "red" }}>
        <WebView
          source={{ uri: "https://examplepwa.firebaseapp.com" }}
          onMessage={event => { this.nativeShare(JSON.parse(event.nativeEvent.data)) }}
        />
      </View>
    );
  }

#In PWA share service:
const webShare = (data) => {
    let { title, text, url } = data
    if (!url) {
        url = document.location.href;
    }
    if (navigator.share) {
        navigator.share({ title, text, url })
            .then(() => console.log('Successful share'))
            .catch((error) => console.error('Error sharing ' + error));
    } else if (window.ReactNativeWebView) {
        const shareObject = { subject: title, message: text, url }
        window.ReactNativeWebView.postMessage(JSON.stringify(shareObject))
    } else {
        console.warn('web share not supported');
    }
}
```
But still I am looking for push notification solution. :(

**Comment by gautama** [comment]
Any luck with the push notifications? So strange that its difficult to get push on iOS with PWA. Looks from your post that react native with WebView shell is also not an option.

**Comment by atultherajput** [comment]
Yeah, it was not possible to get push notifications from Webview. So i had to implement notification service in react native application.

**Comment by carlosalvarez91** [comment]
@atultherajput could you show us how did you implement the notification service in 
react native webview? Thank you

**Comment by asifcse07** [comment]
still searching for solutions

**Comment by JanedoeGVA** [comment]
I'm really interesting too if someone got a solution, thanks !

**Comment by varunshukla** [comment]
I'm looking forward to some solution for this issue. Has anyone got some solution?
@atultherajput Can you show us how you implemented this in RN along with WebView?

**Comment by gautama** [comment]
I tried this. It didn’t work for me. I think the browser matrix does not fully support web push notifications on mobile devices.

The way I got it to work was to build the notification module natively and send messages to it from the web view, which is possible. It’s not a lot of code on the native side, so your main application can continue to be web view. 

Note that iOS app approvals have a hard time justifying the main application being driven from a web view. This is hear say from the web, I didn’t go down this route.

Best,
Gautam

‭‭+1 (425) 553-6137‬‬

**Comment by uqjhack1** [comment]
We are trying to push gps locations from react native to webview. Any idea? Thanks !

**Comment by sdelfi** [comment]
Have the same problem. Any updates?

**Comment by rajeevverma076** [comment]
still searching for solutions

**Comment by amilich** [comment]
Same here

**Comment by vinhmdev** [comment]
same issue

**Comment by manish-eq** [comment]
still searching for the solutions
