### ISSUE TITLE
How to enable forMainFrameOnly option in iOS webview

### ISSUE THREAD

**Issue by muthuspark** [react-native-community/react-native-webview#824]
I am using react-native-webview to load a URL which has multiple iframes. I am injecting javascript into the loaded website using the `injectedJavaScript` method. The code is injected only in the top frames and not in the iframes.

For android, I am overriding the `public WebResourceResponse shouldInterceptRequest(WebView view, WebResourceRequest request)` method to intercept my HTML and add the required Javascript into it. 

For iOS, after some google search I found some results pointing to setting `forMainFrameOnly` to NO. I am a complete noob to Objective C and have absolutely no idea how to set this. I had a look at RNCWKWenView.m file which had `forMainFrameOnly:YES` at 2 places. I replaced YES with NO and then rebuilt my iOS project in xcode. But still not able to get my javascripts in iframes.

**To Reproduce:**
App.js file

```

import React, { Component } from 'react';
import { BackHandler, Platform } from 'react-native';
import { WebView } from 'react-native-webview';

const WEBVIEW_REF = 'webview';

export default class App extends Component {

    webView = {
        canGoBack: false,
        ref: null
    }

    onAndroidBackPress = () => {
        if (this.webView.canGoBack) {
            this.refs[WEBVIEW_REF].goBack();
            return true;
        }
        return false;
    }

    /**
     * generate the javascript needed to be embedded inside the react native code. 
     */
    generateJSCode() {

        var jsCode = "console.log('my script shows');";

        return jsCode;
    }

    componentDidMount() {
        if (Platform.OS === 'android') {
            BackHandler.addEventListener('hardwareBackPress', this.onAndroidBackPress);
        }
    }

    componentWillUnmount() {
        if (Platform.OS === 'android') {
            BackHandler.removeEventListener('hardwareBackPress');
        }
    }

    render() {

        const uri = "http://localhost:8000";

        return (
            <WebView
              ref={WEBVIEW_REF}
              source={{uri}}
              useWebkit={true}
              injectedJavaScript={this.generateJSCode()}
              javaScriptEnabled={true}
              onNavigationStateChange={(navState) => { this.webView.canGoBack = navState.canGoBack; }}
            />
        );
    }
}
```

**The HTML file:**
```
<!DOCTYPE html>
<html>
<head>
	<title>test</title>
</head>
<body>
	<h1>this is a sample page</h1>
	<iframe src="https://wikipedia.org/" style="width:100%;min-height: 400px;"></iframe>
	<iframe src="https://wikipedia.org/" style="width:100%;min-height: 400px;"></iframe>
</body>
</html>
```

**Expected behaviour:**

On iOS: When I set `forMainFrameOnly:YES` as `forMainFrameOnly:NO`, I am expecting the script to get injected in my iframes as well.

**Environment:**
 - OS: MacOS
 - OS version:
 - react-native version: 0.60.5
 - react-native-webview version: 6.9.0

**Comment by shirakaba** [comment]
@muthuspark I'm creating a PR for this, for iOS: #1119
