### ISSUE TITLE
Can not play Netflix videos in Android Webview

### ISSUE THREAD

**Issue by ankur-sardar** [react-native-community/react-native-webview#83]
Go to Netflix and try to play any video. when you touch any video, it is not redirecting to the video player page. 
Try this link for test - https://www.netflix.com/jp-en/originals

Does anyone know why is this happening?

**Comment by jamonholmgren** [comment]
I tried this out and it's true, the videos don't play. I don't really know why not, though.

One way to potentially debug is to follow @ryanlntn's new [debugging guide](https://github.com/react-native-community/react-native-webview/blob/master/docs/Debugging.md).

**Comment by ankur-sardar** [comment]
Yes, I followed that, But could not understand what is the issue.
I got this error message when I open Netflix
![image](https://user-images.githubusercontent.com/14098612/47132787-b5d5e000-d2e0-11e8-8fe0-be2dce6eba7f.png)

**Comment by ankur-sardar** [comment]
@jamonholmgren 
 after investigation, I found that, when we click on Netflix video, it load url with `intent://` scheme, and it is not loading that url scheme. So may be we can handle this in `shouldOverrideUrlLoading` method. I got one solution for this issue in my forked version.
Do you have any solution for this? Or should I make a PR for this solution?

**Comment by Titozzz** [comment]
We should have that functionality however be careful there is already someone working with that method https://github.com/react-native-community/react-native-webview/pull/59

**Comment by maxammann** [comment]
@ankur-sardar would it be enough to cancel the loading and doint the intend stuff in react-native? That way you do not need to write a lot of native code.

**Comment by HackingGate** [comment]
Still don’t know how to solve the issue.
I have a link like https://www.netflix.com/jp-en/originals in my project.
It load url with `intent://` scheme in Android.
Before upgrading to `react-native-webview`. It was able to open Browser. Now it can’t.

I tried to implement `onShouldStartLoadWithRequest`. I got an error when I touch any video. Here's my code looks like.

```js
<WebView
          onShouldStartLoadWithRequest={() => true}
          source={{ uri: 'https://www.netflix.com/jp-en/originals' }}
/>
```

I also tried `originWhitelist`. If I set like this: 

```js
<WebView
          originWhitelist={null}
          source={{ uri: 'https://www.netflix.com/jp-en/originals' }}
/>
```

It opens every url in browser. Then the url redirects to the Netflix app. 
But this isn’t what I want. 
I don't want it open Browser until there’s a `intent://` scheme.

**Comment by HackingGate** [comment]
I tried `Linking.sendIntent()` but didn’t make it work. I finally ended up with https://stackoverflow.com/questions/57514207/open-settings-using-linking-sendintent

Here’s my code like:

```js
<WebView
  source={{ uri: 'https://www.netflix.com/jp-en/originals' }}
  onShouldStartLoadWithRequest={this._onShouldStartLoadWithRequest.bind(this)}
/>
```

```js
_onShouldStartLoadWithRequest = (event) => {
  const { url } = event;
  if (url.startsWith('intent://') && url.includes('scheme=http') && Platform.OS === 'android') {
    SendIntentAndroid.openChromeIntent(url);
    return false;
  }
  return true;
}
```

**Comment by Lacerda53** [comment]
> 
> 
> I tried `Linking.sendIntent()` but didn’t make it work. I finally ended up with https://stackoverflow.com/questions/57514207/open-settings-using-linking-sendintent
> 
> Here’s my code like:
> 
> ```js
> <WebView
>   source={{ uri: 'https://www.netflix.com/jp-en/originals' }}
>   onShouldStartLoadWithRequest={this._onShouldStartLoadWithRequest.bind(this)}
> />
> ```
> 
> ```js
> _onShouldStartLoadWithRequest = (event) => {
>   const { url } = event;
>   if (url.startsWith('intent://') && url.includes('scheme=http') && Platform.OS === 'android') {
>     SendIntentAndroid.openChromeIntent(url);
>     return false;
>   }
>   return true;
> }
> ```

Não deu certo aqui
