### ISSUE TITLE
expo 34 error, Invariant Violation: requireNativeComponent: "RNCWebView" was not found in the UIManager.

### ISSUE THREAD

**Issue by YanYuanFE** [react-native-community/react-native-webview#832]
**Bug description:**
use Expo v34 and react-native-webview 7.0.1, Invariant Violation: requireNativeComponent: "RNCWebView" was not found in the UIManager.

**Expected behavior:**

**Screenshots/Videos:**
![image](https://user-images.githubusercontent.com/17774285/64088980-78523800-cd76-11e9-8001-e67be6dde882.png)

**Environment:**
 - OS: MacOS
 - OS version: 10.14.6
 - react-native version: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz
 - react-native-webview version: 7.0.1

**Comment by wanghe826** [comment]
Your should cd in iOS directory and "pod install",  then run the iOS workspace, it will be ok.

**Comment by YanYuanFE** [comment]
> Your should cd in iOS directory and "pod install", then reopen the iOS workspace and run it.

I use creat-react-native-app init project, not ios directory.

**Comment by ZitaNguyen** [comment]
I have the same problem

**Comment by WhatzzUp** [comment]
If you are using expo, you have to wait till expo updates his sdk because @Titozzz changes are native

@Titozzz  explained his changes in a expo thread: https://github.com/expo/expo/issues/5497

**Comment by Titozzz** [comment]
Thanks @WhatzzUp you are 100% right. Can't use this directly, you need to wait for expo to pull the changes in, (or you can eject but prob not what you are looking for)

**Comment by Baksha2008** [comment]
Same problem. Re-install pods don't help. Has anyone found a solution?

**Comment by pegasus1982** [comment]
Thank @wanghe826 
In my case, Your solution helped me.
I tried to use `react-native-azure-ad-2`.
Then I used **AzureLoginView** to sign in with Microsoft.
And I faced this issue.

You saved my life.
Thank you

**Comment by jannikbuschke** [comment]
Im facing this issue with expo 35.
