### ISSUE TITLE
Pause app when user lock phone

### ISSUE THREAD

**Issue by kenMarquez** [react-native-community/react-native-webview#840]
**I used the Webview to insert a Game when i lock the phone in Android the background game is still executing on the WebView.**

Could you add an parameter to decide if you want to pause the application when the app state it is paused?

**Comment by kefyru** [comment]
import {AppState} from 'react-native';
....

gameStartStop(status) {
   if (status === 'active') {
       // send message to WebView to start game
   } else {
       // send message to WebView to pause game
   }
}

componentDidMount() {
....
AppState.addEventListener('change', gameStartStop);
}

componentWillUnmount() {
....
AppState.removeEventListener('change', gameStartStop);
}
