### ISSUE TITLE
Webview image not loading , image in loading state 

### ISSUE THREAD

**Issue by harryharihar** [react-native-community/react-native-webview#841]
**Bug description:**
I am using webview and web page contain image but its in loading state.

**Environment:**
 - OS:Windows 
 - OS version: Windows 10
 - react-native version:"0.59.9"
 - react-native-webview version:^5.12.1
`
<WebView
            scrollEnabled={true}
                //Loading URL
                source={{
                  uri: initialUrl.DOMAIN_URL + "/",
                  headers: {
                    Authorization: "Basic YmV0YTp2ZWVuYXdvcmxkMTIz",
                    client: "APP"
                  }
                }}
                //Enable Javascript support
                javaScriptEnabled={true}
                //For the Cache
                domStorageEnabled={true}
                //View to show while loading the webpage
                renderLoading={() => this.DotIndicatorLoadingView()}
                //Want to show the view or not
                injectedJavaScript={injectedJs}
                automaticallyAdjustContentInsets={true}
                startInLoadingState={true}
                onMessage={this.onWebMessage.bind(this)}
                onNavigationStateChange={this.onNavigationStateChange}
                // onScroll={this.onScroll}
                //overflow='hidden'
                renderError={(error) => {
                  // console.log(error);
                  return NetInfo.isConnected.fetch().done(
                    isConnected =>
                      this.setState({ isConnected: isConnected })
                  )
                }}
              />`

**Comment by harryharihar** [comment]
`<WebView
                ref={webView => {
                  this.refWeb = webView;
                }}
                style={{
                  height: height,
                  justifyContent: "center",
                  //alignItems: "center"
                }}

                scrollEnabled={true}
                //Loading URL
                source={{
                  uri: initialUrl.DOMAIN_URL + "/",
                  headers: {
                    Authorization: "Basic YmV0YTp2ZWVuYXdvcmxkMTIz",
                    client: "APP"
                  }
                }}
                //Enable Javascript support
                javaScriptEnabled={true}
                //For the Cache
                domStorageEnabled={true}
                //View to show while loading the webpage
                renderLoading={() => this.DotIndicatorLoadingView()}
                //Want to show the view or not
                injectedJavaScript={injectedJs}
                automaticallyAdjustContentInsets={true}
                startInLoadingState={true}
                onMessage={this.onWebMessage.bind(this)}
                onNavigationStateChange={this.onNavigationStateChange}
                // onScroll={this.onScroll}
                //overflow='hidden'
                renderError={(error) => {
                  // console.log(error);
                  return NetInfo.isConnected.fetch().done(
                    isConnected =>
                      this.setState({ isConnected: isConnected })
                  )
                }}
              />`

**Comment by favrio** [comment]
I have `startInLoadingState` be true, web page would stuck at the load screen on android device(not simulators), you can remove `startInLoadingState` for a test.
