### ISSUE TITLE
Wasn't able to build on android

### ISSUE THREAD

**Issue by jehajj** [react-native-community/react-native-webview#842]
**Bug description:**
I was using the version 5.2.1 and everything was working fine.
Then I tried updating to 7.0.2 and I added to android/gradle.properties those 2 lines:
android.useAndroidX=true
android.enableJetifier=true
But unfortunately the build was failing

**To Reproduce:**
Install latest version
link the library
react-native run-android

**Expected behavior:**
successful build

**Screenshots/Videos:**
<img width="563" alt="Screen Shot 2019-09-03 at 5 20 57 PM" src="https://user-images.githubusercontent.com/36712924/64181920-01996580-ce70-11e9-8644-50a351b46a73.png">

**Environment:**
 - OS: Android
 - react-native version: 0.59.8
 - react-native-webview version: 7.0.2

**Comment by draperunner** [comment]
AndroidX support came with React Native v0.60: https://facebook.github.io/react-native/blog/2019/07/03/version-60

So I guess you need to upgrade your React Native version. 

Check out the upgrade heler from 0.59.8 to 0.60.5: https://react-native-community.github.io/upgrade-helper/?from=0.59.8&to=0.60.5

You can find the full changelog here: https://github.com/react-native-community/releases/blob/master/CHANGELOG.md

**Comment by jehajj** [comment]
@draperunner Thanks for your reply.
Make sense, will apply the upgrade
