### ISSUE TITLE
requireNativeComponent: "RNCWebView" was not found in the UIManager

### ISSUE THREAD

**Issue by rendongsc** [react-native-community/react-native-webview#851]
```
   "react": "16.8.6",
   "react-native": "0.60.5",
   "react-native-webview": "^7.0.4"
```
![image](https://user-images.githubusercontent.com/12553638/64412648-71069380-d0c2-11e9-9759-15315b9fd591.png)
After the problem, I tried manual link, but the problem remains.

**Comment by hannojg** [comment]
same here

**Comment by xinggangling** [comment]
I have the same problem too...

**Comment by zanusilker** [comment]
How to resolve this issue?

**Comment by nasof** [comment]
Im using expo and cant eject.  Also getting this error.
    "react-native": "https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz",

**Comment by jk-gan** [comment]
I'm still facing the same issue after ```react-native link``` and then ```pod install```.
```
  "react": "16.8.6",
  "react-native": "0.60.5",
  "react-native-webview": "^7.0.5"
```

**Comment by EnkeChan** [comment]
> I had the same issue. Try `react-native link` and then `cd ios` and `pod install` in the ios folder. It has resolved this problem for me.

It has resolved this problem for me too! Thank you!

**Comment by JySa65** [comment]
I have this same problem with android on linux

**Comment by lb90** [comment]
Hi, I am blocked by this. Is there any workaround? Android + Linux

**Comment by lb90** [comment]
Note: I am using Wix react-native-navigation 3.2. I have found this comment that states RNN v3 breaks auto linking: https://github.com/wix/react-native-navigation/issues/5572#issuecomment-541409925.

Can that be the reason? Anyway, I have also followed the docs and run `react-native link react-native-webview` but nothing has changed so far.

**Comment by lb90** [comment]
That was it! The comment https://github.com/wix/react-native-navigation/issues/5572#issuecomment-541519364 contains a workaround.

@JySa65 if you are using Wix RNN v3 you will find the workaround useful

**Comment by MehmetKaplan** [comment]
The same problem persists with Expo SDK 35 also.

And with Expo manual linking is also not an option.

Any suggestions?

**Comment by michaelVictoriaDev** [comment]
@MehmetKaplan please run: expo install [package-name ...]

**Comment by MehmetKaplan** [comment]
@michaelVictoriaDev ; I had already did the ``expo intall react-native-webview``` command. Unfortunately it did not work.

So the workaround I did was to initiate a clear repo with ```expo init```  and port the existing codes (and also to do the related ```expo install``` actions).

My suspicion is, it can be something related with ```babel-preset-expo``` version difference. The one that comes from previous versions and what ```expo init``` brings seem different:

![image](https://user-images.githubusercontent.com/2387157/70109196-89625c00-1679-11ea-8b3a-c22aa4eaf18d.png)

**Comment by stefandbd** [comment]
For those who did not solve the issue with the latest RN.
Open the workspace file in Xcode and at Build Phases add libreact-native-webview.a
<img width="671" alt="Screenshot 2019-12-05 at 19 21 02" src="https://user-images.githubusercontent.com/5445729/70258160-624c7d00-1794-11ea-841c-79c0ad9b637a.png">

**Comment by SyedUzairAlii** [comment]
my project is on expo and i'm getting this error in ios , how can i perfrom the linking in expo and cant eject the project any help,

**Comment by ahmetcaglayan** [comment]
I'm having the same problem for android on ubuntu. There is no problem with different model devices.

**Comment by belal-mazlom** [comment]
For RN 0.60 and higher
add to podfile
`pod 'react-native-webview', :path => '../node_modules/react-native-webview'`
Then
`cd ios`
`pod install`

**Comment by rmethaniya** [comment]
> I have this same problem with android on linux

First, uninstall react-native-webview package then try to install with **npm install --save react-native-webview**

**Comment by AntonioMerendaz** [comment]
Component Exception
requireNativeComponent: "RNCWebView" was not found in the UIManager.
Still with the same problem! None of the suggestions above worked!
Is there anyone that can help?

**Comment by lung2008123** [comment]
> For those who did not solve the issue with the latest RN.
> Open the workspace file in Xcode and at Build Phases add libreact-native-webview.a
> <img alt="Screenshot 2019-12-05 at 19 21 02" width="671" src="https://user-images.githubusercontent.com/5445729/70258160-624c7d00-1794-11ea-841c-79c0ad9b637a.png">

Works with me! Don't forget to quit your simulator and re-compile your ios-app by `npx react-native run-ios`.

**Comment by andymach** [comment]
just restart the project entirely and make sure your computer connected to internet

**Comment by arejula27** [comment]
Im using android and expo, same bug

**Comment by ChetankumarSB** [comment]
> Im using android and expo, same bug

`react-native link` resolved my problem.

**Comment by pnDeloguePLM** [comment]
> For those who did not solve the issue with the latest RN.
> Open the workspace file in Xcode and at Build Phases add libreact-native-webview.a
> <img alt="Screenshot 2019-12-05 at 19 21 02" width="671" src="https://user-images.githubusercontent.com/5445729/70258160-624c7d00-1794-11ea-841c-79c0ad9b637a.png">

Saved my day. Thank you :) 👍

**Comment by iboxgithub** [comment]
same problem here...my project was working fine yesterday...it seems like all the solutions proposed involve manual linking whereas Expo should take care about it no?

**Comment by jpolvora** [comment]
I was having this error and I found that my folder that contains `MainApplication.java` was wrong. I have copied a project structure and then renamed the project using a tool called `react-native-rename`. Unfortunately, this tool has some bugs, that did not renamed that folder, so, causing errors.

**Comment by iboxgithub** [comment]
for me it was the lib version:
- `"react-native-webview": "^11.17.2"` --> works
- `"react-native-webview": "^11.18.0"` --> doesn't work

so from my point of view it i linked to this lib...so I don't know how this issue can be closed...

**Comment by gb-media** [comment]
> for me it was the lib version:
> 
> * `"react-native-webview": "^11.17.2"` --> works
> * `"react-native-webview": "^11.18.0"` --> doesn't work
> 
> so from my point of view it i linked to this lib...so I don't know how this issue can be closed...

thank you so much. this works great. 
my package for expo looks like:
```
"dependencies": {
  "expo": "~45.0.0",
  "react": "17.0.2",
  "react-native-webview": "^11.17.2",
  "react-native-signature-canvas": "^4.4.1",
  ...
},
```
my tests for signature with `react-native-signature-canvas` is working now on android >= 10.
iOS, not tested.
