### ISSUE TITLE
Is downgrading of react-native will works after upgrade to downgrade version of react-native-webview

### ISSUE THREAD

**Issue by nihp** [react-native-community/react-native-webview#852]
I have upgraded the react-native webview to 7.0.3 and then I got an error and so I have downgraded to my previous version. But after the downgrade, I am getting the error as "**Tried to register two views with the same name RNCUIWebView**". 

Now the version is 5.6.1. Also in RNCWebView.xcodeproj it shows as below

Any solution for this?

![Screenshot 2019-09-06 at 2 33 05 PM](https://user-images.githubusercontent.com/36992338/64415602-42cd8780-d0b3-11e9-8ce5-472ac3582752.png)

**Comment by khalidos32** [comment]
any solution so far?
