### ISSUE TITLE
Cannot attach file when using 'useWebKit'

### ISSUE THREAD

**Issue by Phattana** [react-native-community/react-native-webview#857]
I have implemented an app which use WebView. By the way IOS has announced that UIWebView will be deprecated. The solution which I used is add 'useWebKit' in to WebView for render WkWebView instead of UIWebView. 

My issue is when I use 'useWebKit' my app cannot attach files / photos (which render from the website). In the other hand, if  I have not used 'useWebKit' the app can attach files / photo.

Do you have any  solutions?

Here's some of my code
...
<SafeAreaView style={styles.boxSafeAreaView}>
   <WebView source={{ 'uri': YTU_WEBAPP }} useWebKit={true} />
</SafeAreaView>
...

**Comment by hank121314** [comment]
Where do your files or photos store in? In the device or in the server? If they are stored in the device where is the path for them?

**Comment by Phattana** [comment]
@hank121314  There are attach file button in the website which redirect to device's store

**Comment by hank121314** [comment]
In WKWebview you should add allowingReadAccessToURL props to get files which are stored in the device's store.
`<WebView source={{ 'uri': YTU_WEBAPP }} useWebKit={true}  allowingReadAccessToURL={your_device_store_path} />
`
Update to the latest version is recommended!

**Comment by Phattana** [comment]
@hank121314  i use expo. but in expo don't have allowingReadAccessToURL

**Comment by hank121314** [comment]
@Phattana I have checked expo source code. allowingReadAccessToURL is allowed is SDK 35.
Let's wait for expo release it and keep tracking on it later 😄 .

**Comment by Phattana** [comment]
now i use this `import { WebView } from 'react-native-webview';` that can fix my issue
https://docs.expo.io/versions/latest/sdk/webview/

**Comment by FullstackJack** [comment]
Just wanted to point out that useWebkit is gone now with 7.0.1 removal of UIWebView
