### ISSUE TITLE
Unable to autoplay youtube embedded video

### ISSUE THREAD

**Issue by kohchenggee** [react-native-community/react-native-webview#859]
**Bug description:**
Unable to autoplay youtube embedded video with webview,

**To Reproduce:**
<WebView
        source={{ html: "<html><body><iframe width='560' height='315' src='https://www.youtube.com/embed/RJa4kG1N3d0?&autoplay=1' frameborder='0' allow='autoplay;' allowfullscreen></iframe></body></html>" }}
          style={{ width: width, height: "100%" }}
          cacheEnabled={true}
          allowsInlineMediaPlayback={true}
          mediaPlaybackRequiresUserAction={true}
        />
If the youtube url is in watch, then it will autoplay

**Expected behavior:**
Autoplay the video as soon as it loaded

**Screenshots/Videos:**

**Environment:**
 - OS:
 - OS version:
 - react-native version: "^0.59.9",
 - react-native-webview version: "^5.7.0"

**Comment by partiellkorrekt** [comment]
As a first step you might want to to set "mediaPlaybackRequiresUserAction" to false instead of true ;)

Btw. Only set this when on iOS or android API > 16

What I do:
```
mediaPlaybackRequiresUserAction={((Platform.OS !== 'android') || (Platform.Version >= 17)) ? false : undefined}
```

**Comment by partiellkorrekt** [comment]
Youtube seems to block youtube-autoplay on wkwebview. Changing the useragent solved this problem for me. You can do it globally by adding the following code to "AppDelegate.m" inside the function "application didFinishLoadingWithOptions"

```
NSString *userAgent = @"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.1 Safari/605.1.15";
  NSDictionary *dictionary = [[NSDictionary alloc] initWithObjectsAndKeys:userAgent, @"UserAgent", nil];
  [[NSUserDefaults standardUserDefaults] registerDefaults:dictionary];
```

**Comment by partiellkorrekt** [comment]
Using the following prop, i get autoplay on android as well:
```
userAgent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36"
```

**Comment by NguyenVanVietPoLy** [comment]
work in ios and androi  :D ,  @partiellkorrekt  
    <WebView
              style={{ flex: 1 }}
              source={{ html }}
              mediaPlaybackRequiresUserAction={((Platform.OS !== 'android') || (Platform.Version >= 17)) ? false : undefined}
              userAgent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36"
            />

**Comment by SweetTomato0** [comment]
> work in ios and androi :D , @partiellkorrekt <WebView style={{ flex: 1 }} source={{ html }} mediaPlaybackRequiresUserAction={((Platform.OS !== 'android') || (Platform.Version >= 17)) ? false : undefined} userAgent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36" />

adding both ```mediaPlaybackRequiresUserAction``` and ```userAgent``` works for me! Thanks!
