### ISSUE TITLE
Enable a way to customize menu options when selecting text in web view (iOS)

### ISSUE THREAD

**Issue by fpena** [react-native-community/react-native-webview#862]
Currently, there's no a clear way to add more options to the menu displayed, when selecting text inside the web view. 

This is particularly for iOS.

![27Mde](https://user-images.githubusercontent.com/440097/64757927-5419f800-d4e8-11e9-90ae-8905d431fa27.png)

A possible solution would be to add a new property called `iOSExtraMenuItems` where I can define an object with two values:

1. A title for the new menu item.
1. A function/closure for the intended logic to happen when the menu item is tapped.

The library would need to manage these values and add the extra items to the `UIMenuController` shared instance of the app.

**Comment by iammikeleung** [comment]
I'm looking for a solution to this issue too, I'm hoping this can be added as a feature?

**Comment by yogeshclm** [comment]
> solution

did u find any solution for this ? if yes please help me out
