### ISSUE TITLE
Stopping momentum scroll triggers click event on Android

### ISSUE THREAD

**Issue by clemensmol** [react-native-community/react-native-webview#863]
When scrolling the webview, if we touch the screen it stops the momentum scrolling. Perfect. But... it also triggers a click event in the webview on Android only, seems like  bug to me. At least thats not how Chrome on Android works for example. Any suggestions on how to fix this?

Expected behaviour:
Touching the Webview should stop the momentum scrolling without triggering a click/touch event inside the Webview.

Rreact-native 0.60.5 but earlier versions have the same problems on Android.

**Comment by lieferbaer** [comment]
I have the same issue on android webview app. Is there any solution?
