### ISSUE TITLE
Using WebView (after remove UIWebView) but still got email from IOS

### ISSUE THREAD

**Issue by Phattana** [react-native-community/react-native-webview#867]
Hi,
After react-native-webview has modified code (UIWebView Removal #828 )

But I still got email from Apple about ITMS-90809: Deprecate API Usage.
Should I do anything to stop this warning email? Or just leave it?

Can I also deploy this app to store? Due to the deprecation

Thanks,

**Comment by tranquan** [comment]
I think it's related to this issue
https://github.com/facebook/react-native/issues/25411

Is it better to have this flag `WEBKIT_IOS_10_APIS_AVAILABLE` configured by the main project rather than depends on react?

**Comment by Phattana** [comment]
I use expo34 which referred from this url (https://docs.expo.io/versions/latest/sdk/webview/)

Do you have any guideline to do the way which you recommend? @tranquan 

Thanks,

**Comment by tranquan** [comment]
I upgrade to react-native 0.60.5
There's also another solution is delete UIWebView in react-native project
you can check here:
https://github.com/facebook/react-native/issues/26255

**Comment by Titozzz** [comment]
You can still publish updates as it's only a warning @Phattana . Do you have any other dep that could use and old webview?

**Comment by tranquan** [comment]
@Phattana you can try to search `UIWebView` in Xcode, it will show where the UIWebView being used. For me, it's `FirebaseAuth`. After I updated it to 6.8.1, Apple won't complain anymore

https://github.com/firebase/firebase-ios-sdk/releases/tag/6.8.1

**Comment by vjtc0n** [comment]
Even I removed all UIWebView, Apple still gives me this email, then I cannot submit the app in Appstore Connect.
Any ideas?

**Comment by azayneeva** [comment]
@vjtc0n it's a warning, you can submit and you can publish, they only say in a bit they will not let you

**Comment by Gypsyer** [comment]
In my case.
Long time i used HockeySDK in Podfile.
Solved : Remove HockySDK in Podfile -> Delete Podfile folder and Podfile.log in ios path -> Pod install.
Worked for me.
