### ISSUE TITLE
PWA (Progressive Web App) with WorkBox Support

### ISSUE THREAD

**Issue by magbicaleman** [react-native-community/react-native-webview#869]
I'm looking for guidance on this more than trying to report a bug or request a feature. We've built a PWA that uses WorkBox which handles the offline support.

```
import React from 'react';
// import { SafeAreaView, StyleSheet } from 'react-native';
import WebView from 'react-native-webview';

const App = () => (
    <WebView 
        source={{ uri: 'http://localhost:5000' }}
        contentInsetAdjustmentBehavior='automatic'
    />
);

export default App;
```

When using the code above if my localhost:5000 is running, we are golden. When the local servers is ended; on Chrome browser the site works with its offline support but ReactNative application produces an error (see below).

![image](https://user-images.githubusercontent.com/735039/64978269-1cfa6c80-d883-11e9-8639-9c02c60c246a.png)

Are there any polyfills that could help with this, is this mainly a limitation to the WebView. It seems cache is supported by default, what is the expectation? 

The main goal is to leverage our PWA and get it on the APP store we do want to introduce some push notifications for iOS as well.

**Comment by timothyfbowen** [comment]
@magbicaleman I'm also interested in this functionality, it would be awesome if you could update here if you figure out how to implement this.

**Comment by magbicaleman** [comment]
@timothyfbowen as of right now we decided not to put any effort into solving this. If we do I'll add to this issue.

**Comment by magbicaleman** [comment]
@timothyfbowen we got published on the app store with just a Webview, using this webview.

**Comment by sgimeno** [comment]
Is it possible to open the application from an offline state (ie Flight mode on) with this approach? In iOS when I try to re-open my application after a "hard close" seems the webview is not loading all static resources

**Comment by magbicaleman** [comment]
@sgimeno if I'm not mistaken, I think this is a limitation on the iOS's webview component, in which it does not offer service worker support. 

http://openradar.appspot.com/51092505

In iOS 13, it seems like they added service worker support, but I have not experimented with this myself, I don't know if this component needs to be updated, or if it's just out of the box with iOS 13.

https://love2dev.com/blog/apple-ships-service-workers/

**Comment by benseitz** [comment]
Has anyone testet if in iOS 13 Service Worker and react-native-webview are compatible?

**Comment by zischwartz** [comment]
As far as I can tell, it's not compatible.

This fairly old [stackoverflow answer](https://stackoverflow.com/a/49673400/83859) says "Service Workers in WKWebView now require an entitlement: `com.apple.developer.WebKit.ServiceWorkers`" which apple doesn't appear to offer. 

And the even older  [webkit blog post](https://webkit.org/blog/8090/workers-at-your-service/) has this clarification:
> Update: A previous version of this post stated the Service Worker API is available in all applications using WKWebView. At this time it is only available in Safari, applications that use SFSafariViewController, and web applications saved to your home screen.


And a quick test with [this page](https://jakearchibald.github.io/isserviceworkerready/demos/navigator.serviceWorker/) fails:

```jsx

<WebView
  style={{
    flex: 1,
    width: deviceWidth,
    height: deviceHeight
  }}
  source={{
    uri:
      "https://jakearchibald.github.io/isserviceworkerready/demos/navigator.serviceWorker/"
  }}
/>
```


Am I missing something? Anyone have any ideas? Or even more recent confirmation about the entitlement thing?

**Comment by timothyfbowen** [comment]
I believe it would be helpful to keep this issue open as as far as I know
it hasn't been resolved yet.  I believe this is an Apple SDK issue or I
would try to submit a PR to fix it.

**Comment by danvoyce** [comment]
👎

**Comment by n8sabes** [comment]
**Offline Support is Critical**

PWA platform investments are accelerating faster than any other development methodology and relying upon Service Workers is unviable for native backward compatibility. Mobile OS penetration rates w/o Service Workers are still too high for a number of years to come.

What about downloading a zip of PWA and serving it natively (localhost) on the device as a fallback? I recall doing something like this long ago with Cordova.

Would there be a way to provide a "bridge" directly into WebView that wouldn't require a localhost server?

Ideas welcome.

**Comment by olso** [comment]
@n8sabes Thanks

This hack didn't even occur to me. Very clever ❤️

Combined with https://github.com/futurepress/react-native-static-server

This might actually work

**Comment by edsonayllon** [comment]
@olso Were you able to get this working? How did you download the PWA to storage?

**Comment by kitolog** [comment]
Hello
Does anybody have any news about the offline mode?

**Comment by kitolog** [comment]
Maybe, it'll be helpful.
So, on iOS 14+, wkwebiew has service workers and cache API
To support Android and iOS, you need:
1) your website should be https
2) setup the cache and limitsNavigationsToAppBoundDomains props:
<WebView
....
   cacheEnabled={true}
   cacheMode={isInternetReachable ? 'LOAD_DEFAULT' : 'LOAD_CACHE_ONLY'}
   limitsNavigationsToAppBoundDomains={true}
...
/>   
3) in Xcode, Info.plist file, add:
    <key>WKAppBoundDomains</key>
    <array>
        <string>your-website.com</string>
    </array>
4) Implement the service worker, caching logic, etc.
5) Test on Android and iOS
6) Enjoy :)

**Comment by tholmgren** [comment]
> Maybe, it'll be helpful. So, on iOS 14+, wkwebiew has service workers and cache API To support Android and iOS, you need:
> 
> 1. your website should be https
> 2. setup the cache and limitsNavigationsToAppBoundDomains props:
>    `<WebView .... cacheEnabled={true} cacheMode={isInternetReachable ? 'LOAD_DEFAULT' : 'LOAD_CACHE_ONLY'} limitsNavigationsToAppBoundDomains={true} ... />`
> 3. in Xcode, Info.plist file, add:
>    `<key>WKAppBoundDomains</key> <array> <string>your-website.com</string> </array>`
> 4. Implement the service worker, caching logic, etc.
> 5. Test on Android and iOS
> 6. Enjoy :)

The above works great except.... now JavaScript injection are blocked.  
Any idea how to get JavaScript injection working again after updating the info.plist?  

https://github.com/ionic-team/capacitor/issues/4721#issuecomment-873183407

"Adding WKAppBoundDomains key blocks JavaScript injection and other WKWebView features unless limitsNavigationsToAppBoundDomains is set to true (which is not possible at the moment, will be after the linked PR gets merged).
Without the JavaScript injection, native plugins don't work and the web version is used instead.

More information about App Bound Domains and how they affect the WKWebView can be found [here](https://webkit.org/blog/10882/app-bound-domains/)"

**Comment by Pakile** [comment]
@kitolog, @tholmgren how to implement the service worker, caching logic, etc. Can you provide an example code? Thanks
