### ISSUE TITLE
android builds have out of memory error on release build, includes fix

### ISSUE THREAD

**Issue by HilSny** [react-native-community/react-native-webview#870]
**Bug description:**
On release builds in appcenter we were seeing out of memory errors when trying to build in release mode. We also noticed a warning
```
The DefaultSourceDirectorySet constructor has been deprecated. This is scheduled to be removed in Gradle 6.0. Please use the ObjectFactory service to create instances of SourceDirectorySet instead.
```

**Fix**
What fixed it for us was adding a specific kotlin version to our android/build.gradle
```
kotlinVersion="1.3.41"
```

I'm hoping this fixes things for others and it might be good to suggest to developers that they may need to go this route if they're having trouble building.

**Comment by mikehardy** [comment]
@Titozzz I am experimenting with upgrading to gradle 6, and everything was fine *except* react-native-webview, and for some reason it needed this change (adding `kotlinVersion = "1.3.50"` to my project android/build.gradle in the ext block) or it would fail to compile, saying (oddly enough) either 'java.lang.ExceptionInInitializerError (no error message)'or that "compileSdkVersion is not specified"

Not sure what changed w.r.t. Kotlin for grade 5->6 but this should probably be in the README for android install for gradle 6?

**Comment by Titozzz** [comment]
I am gonna edit the default version to this. Finally updated too and got the problem. @mikehardy Do not hesitate to DM on discord for this kind of issues!
Thanks
