### ISSUE TITLE
Getting a white screen when playing a html page content on ios with react native webView

### ISSUE THREAD

**Issue by hanaechahid** [react-native-community/react-native-webview#877]
Hello,
Actually, I'm trying to play a scorm module with react native webview package, it's working well on android but on ios just a white screen is showing but the module is already playing and I can't see nothing on screen.

this is my code for the web view: 
` <WebView
                    ref={r => (this.webref = r)}
                    useWebKit={false}
                    source={{ uri:  uri}}
                    allowsInlineMediaPlayback={true}
                    cacheEnabled={false}
                    onError={error => {
                        console.log("error:", error);
                    }}
                    onLoadStart={syntheticEvent => {
                        // Update component to be aware of loading status
                        const { nativeEvent } = syntheticEvent;
                        this.setState({
                            loadingScrom: nativeEvent.loading
                        });
                    }}
                    onShouldStartLoadWithRequest={navState => {
                        console.log("navState:", navState);
                        if (navState.url) {
                            return true;
                        } else {
                            this.refs[webref].stopLoading(); 
                            return false;
                        }
                    }}
                    onNavigationStateChange= {navState => {
                        console.log("navState:", navState);
                        if (navState.url) {
                            return true;
                        } else {
                            this.refs[webref].stopLoading(); 
                            return false;
                        }
                    }}
                    onLoadEnd={syntheticEvent => {
                        const { nativeEvent } = syntheticEvent;
                        this.webref.injectJavaScript(jqueryScript);
                    }}
                    injectedJavaScript={injectedJavaScript}
                    javaScriptEnabled={true}
                    renderLoading={this.renderLoadingView}
                    startInLoadingState={true}
                    onMessage= {m => this.onMessage(m)}
                />`

**Environment:**
 - react-native version:0.59.0
 - react-native-webview version:^5.12.1

**Comment by dsky1990** [comment]
same issues

**Comment by adamgajzlerowicz** [comment]
Same here. It worked before. Now just a white screen..

**Comment by sejoon-mfort** [comment]
I have the same issue. Recently, I upgraded Expo from 34 to 36 and it forces me to use react-native-webview 7.4.3. Then, I found that the web page is not loaded and I just see the white screen on iOS whereas nothing is wrong with it on Android. It worked without any problems in the previous version on iOS where I used WebView provided by react-native (not react-native-webview). My guess is that there was a breaking change in webview 7.0, which removed UIWebVIew. I am suspicious of it maybe causing this problem.

**Comment by sejoon-mfort** [comment]
I just solved this problem a little while ago. I was setting the source property to WebView with post method and body property for the data I want to submit like below:

`<WebView
        style={{ flex: 1 }}
        originWhitelist={['*']}
        source={{
          uri: uri,
          method: 'POST',
          body: qs.stringify({
            m: 'abc',
            data: 'data to submit'
          }),
        }}
        onNavigationStateChange={this.onNavigationStateChange}
      />`

And, I changed this to using html and the problem was gone.
`
const html = '
      <div>
        <form name="niceForm">
          <input type="hidden" name="m" value="abc" />
          <input type="hidden" name="data" value="data to submit" />
        </form>
      </div>
      <script>
        document.niceForm.action = "https://nice.checkplus.co.kr/CheckPlusSafeModel/checkplus.cb";
        document.niceForm.submit();
      </script>
    ';
`
`
return (
      <WebView
        style={{ flex: 1 }}
        originWhitelist={['*']}
        source={{ html }}
        onNavigationStateChange={this.onNavigationStateChange}
      />
    )
`

Hope this help.

**Comment by sachinkhedkar** [comment]
Hi, @hanaechahid anaechahid, 

I am working on paying scrom 1.2 content in my react native mobile app. for playing scrom content i am using webview. and Its displayed well. I am trying to integrate scrom APIs into it, but some how i got an issue while doing that. i was tried injecting javascript functions but  not worked.
If you have any demo code snippet, can you please share with me where i can take reference into it. 
It will be great help for me. 

Thanks in advance

**Comment by alanlanglois** [comment]
@sachinkhedkar did you find a way to do it?

**Comment by ManojSankolSR** [comment]
If you're working on playing SCORM 1.2/2004 content in a React Native app and facing issues like white screens on iOS or JavaScript injection problems, I recommend using [react-native-scorm-player.](https://www.npmjs.com/package/react-native-scorm-player) It wraps SCORM packages in a WebView, handles SCORM Runtime API injection automatically, and works on both Android and iOS. This should save you a lot of time dealing with manual integration or platform-specific issues.
