### ISSUE TITLE
vertical scroll in ScrollView (with WebView component inside) stopped works after upgraiding webview from version 7.0.5 to 7.0.6 on Android-Platform

### ISSUE THREAD

**Issue by lubomyr** [react-native-community/react-native-webview#878]
vertical scroll in ScrollView (with WebView component inside) stopped works after upgraiding webview from version 7.0.5 to 7.0.6 on Android platform. When webview cover screen at bottom and mostly cover whole screen, we can't scroll via webview to elements located under webview.
It related that in new version 7.0.6 webview has own scroll, which disable scroll inside scrollview.
It was broken in commit a5cb7ba65c65a68ba714272df21fcef16728e56a,
Probably to fix it we need something like scrollEnabled props for android platform (currently it exist only for ios platform)

platform: Android
react-native: 0.60.5
react-native-webview: 7.0.6

**Comment by KestasVenslauskas** [comment]
Same problem

**Comment by kefyru** [comment]
The same problem with unscrollable webview inside horizontal scrollview on android...

**Comment by kefyru** [comment]
Rolling back to 7.0.5 resolves problem. Waiting for solution))

**Comment by kefyru** [comment]
Is there any news with this issue?

**Comment by Titozzz** [comment]
Will revert the change :(

**Comment by kefyru** [comment]
WORKS GOOD!

**Comment by mrigo** [comment]
On 7.6.0 the bug still exists...
