### ISSUE TITLE
Cannot open Camera in Android stand alone app

### ISSUE THREAD

**Issue by Phattana** [react-native-community/react-native-webview#879]
I have implemented app with WebVIew and used react-native-webview to open web application. After I build the stand-alone app I cannot open the camera which need to attach image.

Do you have any suggestion to solve this problem?

ps. In the other hand, I can open the camera in IOS.
ps2. When I run in expo, the camera can be open

**Environment:**
 - Expo : ^34.0.1
 - react-native version: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz
 - react-native-webview version: ^5.12.1

**Comment by asmakhalfallah2018** [comment]
Phattana i had the same issue i have found a fix but don't know how to patch it :
  1 / check node_modules\react-native-webview\android\src\main\java\com\reactnativecommunity\webview\RNCWebViewModule.java 
2/ replace acceptsImages acceptsVideo functions by : 

```
  private Boolean acceptsImages(String types) {
    return types.isEmpty() || types.toLowerCase().contains("image");
  }
  private Boolean acceptsImages(String[] types) {
    return isArrayEmpty(types) || arrayContainsString(types, "image");
  }

  private Boolean acceptsVideo(String types) {
    return types.isEmpty() || types.toLowerCase().contains("video");
  }
  private Boolean acceptsVideo(String[] types) {
    return isArrayEmpty(types) || arrayContainsString(types, "video");
  }


```
