### ISSUE TITLE
WebView does not load local HTML file in ios 

### ISSUE THREAD

**Issue by jeevithaBA** [react-native-community/react-native-webview#882]
I'm attempting to load a local  file to webview. but the files are not loading in ios, and its working fine in android,

Iam not getting any error, but files not loading in ios, 
                <WebView
                    source={{uri: 'ICF-Package/ICFPackage/index.html' }}
                    ref={(webView) => this.webView = webView}
                    originWhitelist={'["*"]'}
                    javaScriptEnabled={true}
                    domStorageEnabled={true}
                    scalesPageToFit={true}
                    scrollEnabled={false}
                    onLoad={() => this.sendPostMessage()}
                    allowFileAccess={true}
                    allowUniversalAccessFromFileURLs={true}
                />

**Environment:**
 - OS: ios
 - OS version: 10.13.6
 - react-native version: ^0.59.9
 - react-native-webview version: ^5.0.1

**Comment by juhasuni** [comment]
You are passing string to `originWhitelist`. Instead of `originWhitelist={'["*"]'}` you probably mean `originWhitelist={["*"]}`.

**Comment by juhasuni** [comment]
And I suggest that you put it in the form `originWhitelist={['file://*', 'http://*', 'https://*']}`. You should only allow the URL formats that you really need to support.

**Comment by branislavantic87** [comment]
@juhasuni This does not solve the issue. I can confirm that local canvas animation does not show in WebView (ios, it does load on emulator but something is blocking it on device), external uri works fine. Also it worked while WV was part of react native.
Example 
```
<WebView
                    ref={this.webview}
                    originWhitelist={['*']}
                    style={[{ width: '100%', height: '100%', overflow: 'hidden', backgroundColor: 'transparent' }]}
                    source={{ uri: file:///var/mobile/Containers/Data/Application/Documents/web/world_new.html }}
                    onMessage={this.onMessage.bind(this)}
                    onLoadEnd={() => { }}
                    mediaPlaybackRequiresUserAction={false}
                    startInLoadingState={true}
                    scrollEnabled={false}
                    scalesPageToFit={false}

                />
```

Also got this notification 
Did not receive response to shouldStartLoad in time, defaulting to YES.

**Comment by kaviyarasu1987** [comment]
is this still open?? am facing the same issue thanks

**Comment by flashman2** [comment]
Can confirm this issue still exists!

**Comment by flashman2** [comment]
This issue still exists, please don't close.

**Comment by danieloi** [comment]
For me I needed to wrap my component in a View and set the height OUTSIDE the file that returns my WebView: In the file it was imported into. It took several takes and prayer but I finally found it out

**Comment by ykcho5** [comment]
Still having the issue

**Comment by brianwachira** [comment]
> Still having the issue

Did you get a solution to this? I am experiencing the same issue

**Comment by ykcho5** [comment]
Nope. I had to use react native library for ios only for this function.
