### ISSUE TITLE
webview can not load website

### ISSUE THREAD

**Issue by milad-ahmd** [react-native-community/react-native-webview#884]
Hello 
i need to open website in webview that website should open camera and work on it
but webview doesnt load website.

**Environment:**
 - react-native version:0.60
 - react-native-webview version:latest

**Comment by AMINDRH91** [comment]
@elastic
@Momazo7u7

**Comment by andreipfeiffer** [comment]
@milad-ahmd can you provide more context on what type of device/api level did you test on?

@AMINDRH91 does your website (camera prompt) work on Android 6 in a real browser?
I guess your website uses .getUserMedia() api, which might or might not be available in your device's browser/native webview.

**Comment by AMINDRH91** [comment]
@andreipfeiffer  
We have a problem
That link `https://supernovada.com`works well on Android 7,8,9
But not Android 4,5,6
What exactly is wrong?
@elastic
@andreipfeiffer
@YangXiaomei
@imownbey @MalcolmScruggs @CubeSugar

**Comment by andreipfeiffer** [comment]
@AMINDRH91 
1. what is your browser app on Android 6?
2. is that link working in your browser app?

**Comment by AMINDRH91** [comment]
@andreipfeiffer 
1. I used for all version `react-native-webview`
2. work  well on Android 7,8,9  not work in 5,6,4

**Comment by andreipfeiffer** [comment]
@AMINDRH91 it seems we're not understanding each other.

I know you used this package `react-native-webview` and tested it on Android 4-9, and that it works on 7, 8, 9 but it doesn't work on 4, 5, 6.

My question to you is the following:
If you load that url in the Browser Application (Chrome, or whatever browser app is available) on your mobile device / simulator, NOT in your react-native application ... does it work? or not?

**Comment by AMINDRH91** [comment]
Oh, yes now i understand 
works `Chrome` on mobile device 
@andreipfeiffer

**Comment by AMINDRH91** [comment]
![WhatsApp Image 2019-09-21 at 00 12 28](https://user-images.githubusercontent.com/33101099/65372549-8e1e9300-dc7a-11e9-8ea3-04b4b3a64dd3.jpeg)
When I run in Android 6 or 5 I get Same Page blank black page ,but in android 7,9 after get permission Camera we get Video 

I think in udener 6 Amdroid Not work Camera On WebView
@andreipfeiffer

**Comment by andreipfeiffer** [comment]
@AMINDRH91 

1. so when you load that url in Chrome browser (or other default browsder) on Android 4, 5, 6 ... you say it's working?

2. Do you use the `getUserMedia()` API to get the video stream from the webcam?

3. I haven't worked on this feature, but I know that the Android Permissions API have changed starting with Android 6, and the Camera API has changed with Android 5.


@Titozzz do you know what's the API level support for the Camera API in Webview? I guess it's the feature when you use `getUserMedia()` from the DOM API, which should start the camera.

**Comment by devonwesley** [comment]
@AMINDRH91 Did you get this working?

**Comment by AMINDRH91** [comment]
We had to write native for android ... it runs on Android 7,8,9, it doesn't work on some Android 6. We haven't found a device with Android 5  yet to test it on
react-native-community didn't meet our need in Android

**Comment by AwaisAliKolachi** [comment]
@ad7090 can you share how you didthis on native?
