### ISSUE TITLE
App webview unresponsive when debugging

### ISSUE THREAD

**Issue by jpodpro** [react-native-community/react-native-webview#887]
**Bug description:**
I followed the android/chrome debugging steps to debug the webview contents. As soon as the debug instance appears in my browser both the app and the cloned webview contents are completely unresponsive. If i close the debug instance in my browser the app handles taps that were ignored while debugging.

**Expected behavior:**
App responds at all while debugging webviews.

**Environment:**
 - OS: MacOS High Sierra
 - react-native version: 0.59.9
 - react-native-webview version: 5.11.0

**Comment by connor-odoherty** [comment]
I am seeing this as well. `onLoadStart` does not even seem to fire.

Do you happen to be using xCode 11 by any chance? I started seeing issues when I upgraded

**Comment by jpodpro** [comment]
looks like i'm on xCode 10.1
