### ISSUE TITLE
Cannot open PDF in webview on android

### ISSUE THREAD

**Issue by lukas-hanak** [react-native-community/react-native-webview#891]
Hi,
When I want to open the pdf format in a web viewer, the application crashes.

**Environment:**
 - OS: Android
 - OS version: Android 9.0
 - react-native version: Expo SDK 35 / 0.60.5
 - react-native-webview version: 7.2.5

**Comment by leeprobert** [comment]
+1 was going to post this myself. My code:
`import TermsPDF from '../../assets/pdf/terms.pdf'
<WebView
          source={TermsPDF}
          style={theme.termsWebView}
        />`

**Comment by Lukzo-n** [comment]
but I need to view the pdf online, not locally.
example like this .pdf: 
> http://www.pscgames.co.uk/wp-content/uploads/2015/01/MILITO_RULEBOOK.pdf

**Comment by leeprobert** [comment]
The problem is it wants to download the PDF instead of rendering it in the web view.

**Comment by DazzlingFame** [comment]
Also getting a crash when trying to download pdf in the web view

My Environment:

- OS: Android
- OS version: Android 5.1
- react-native version: 0.61.4
- react-native-webview version: 7.4.1

**Comment by vishva-shukla** [comment]
Facing the same issue
Did you guys manage to find solution ?
I'm using Expo
WebView works fine with ios but with android expo just crash with pdf url
![crash](https://user-images.githubusercontent.com/49548904/70773112-8adc0480-1d9c-11ea-9540-72d74f8c4cf4.png)

**Comment by agentile1990** [comment]
This is still an issue for our Android users. WebView attempts to download thePDF instead of rendering it in the view. It also requests access to photos when doing this, so if the app hasn't stated that it needs those permissions, this may cause issues with the Play Store? 

Android: **6.0**
React Native: **0.60.4**
WebView: **5.12.1**

**Comment by Clonescody** [comment]
This is still occuring as of today, adding the `startInLoadingState={true}` prop mad the loader display on Android, but the webview still ends up closing and the app crashes. 

"react-native-webview": "~5.12.0",

Expo CLI 3.11.7 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 13.7.0 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.13.6 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      @storybook/react-native: ^5.1.9 => 5.3.13
      expo: ^34.0.3 => 34.0.4
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.2.tar.gz => 0.59.8
      react-navigation: ^4.0.10 => 4.1.1
    npmGlobalPackages:
      expo-cli: 3.13.1

**Comment by Clonescody** [comment]
Bump, anyone looking into this ?

**Comment by vendroid12** [comment]
I faced the same issue, but i managed to solve it this way! maybe if you're facing the same issue this can help!

 if (Platform.OS === 'android') {
      this.setState({
        pdf : false
      })

    }else{

      this.setState({
        pdf: true,
      })

    }

IPHONE Open PDF with no problem.

**Comment by Clonescody** [comment]
@vendroid12 This works :D Thanks so much !

**Comment by Biplovkumar** [comment]
Nice @eriveltonelias  it worked.
But it is not the solution.
It's a bug of react-native-webview.
.pdf URL is not opening.
I hope it will be fixed in next release of react-native-webview

**Comment by agentile1990** [comment]
Still searching for solutions.

**Comment by KA-32** [comment]
Anyone working on this ? still facing this issue.

**Comment by cdunkel** [comment]
@KA-32 and @ali27001 This is working for me (most of the time):
```
getSource = () => {
    if (this.props.url) {
      if (Platform.OS === 'android' && !isURLAnImage(this.props.url)) {
        // Use the Google Docs viewer for non-image documents on Android
        return { uri: `http://docs.google.com/gview?embedded=true&url=${encodeURIComponent(this.props.url)}` };
      }
      return { uri: this.props.url };
    }
    return { uri: '' };
  };
```
and then the result can be passed into the `source` prop for `<WebView>`.

I say "most of the time" because I do have issues where sometimes the Google Docs viewer doesn't properly open docx files. Closing the view and re-opening it tends to get it to load, but it's obviously not an ideal solution. Just a workaround until there's a more robust fix in react-native-webview.

This is a similar fix to @Biplovkumar's, above.

**Comment by KingAmo** [comment]
while i am in  China, i could not reach any google service, is there any workaround for me ?

**Comment by zhuiye** [comment]
> while i am in China, i could not reach any google service, is there any workaround for me ?
You can write a webPDF parser yourself  or  see this link 
https://blog.csdn.net/DeMonliuhui/article/details/81185611

**Comment by zhuiye** [comment]
> while i am in China, i could not reach any google service, is there any workaround for me ?
花了不到一个小时的时间，后端帮忙部署了一个在线的PDF 解析,用的是pdf.js .具体可以参考下 这篇文章
https://www.cnblogs.com/SavionZhang/p/11757849.html

**Comment by KingAmo** [comment]
@zhuiye thanks a lot!

**Comment by TravellerOnTheRun** [comment]
and we're still facing the same issue as of today, will it be fixed any time soon? Is there a solution except using google docs?

**Comment by veasnabig** [comment]
I fount the solution from stackoverflow. You can check the link below.
https://stackoverflow.com/questions/58155621/react-native-webview-for-android-not-displaying-pdf-and-word-files

**Comment by visharma14** [comment]
webview fetch base64 pdf ???

**Comment by juspriet** [comment]
https://stackoverflow.com/questions/58155621/react-native-webview-for-android-not-displaying-pdf-and-word-files/69360044#69360044
