### ISSUE TITLE
post paramters are sent as request body not post parameters in ios

### ISSUE THREAD

**Issue by sajadabasi** [react-native-community/react-native-webview#892]
**Bug description:**
I want to send post parameters but by using body it will send post body not post parameters and i can send get parameters but not post parameters.

**To Reproduce:**
```
      <WebView
        animating
        startInLoadingState
        source={{
          uri: 'http://192.168.43.238/test.php',
          method:'POST',
          body:'groupcode=test',
        }}
      />
```
```
<?php
var_dump($_POST);
```
**Expected behavior:**
I'd like to get post parameters with $_POST not in request body with file_get_contents('php://input')

**Environment:**
 - OS: ios
 - react-native version: 59.9
 - react-native-webview version: 5.8.1

**Comment by kegi** [comment]
I've faced that bug too. Here is a workaround that worked for me : 

`headers: {
     'Content-Type': 'application/x-www-form-urlencoded',
  }`

**Comment by SandroMachado** [comment]
This issue is not fixed yet.

**Comment by ganesh-trabacus** [comment]
Is this issue fixed? please update if yes.

**Comment by jjcastroc88** [comment]
@kegi config fix the problem

**Comment by zabojad** [comment]
Today with latest version, the proposed solution doesn't work... Has anyone found a solution?
