### ISSUE TITLE
Zooming does not work if scrolling is disabled in webview IOS. 

### ISSUE THREAD

**Issue by Aleverh** [react-native-community/react-native-webview#893]
**Bug description:**
Im my Webview i set height because in my screen i have some webview and some native elements. This is all i wrapped in scroll view. 
The problem that even if i set webview height correctly, in ios devices there is a webview scroll. So when i tried to scroll my screen sometimes i scroll webview. 
So i have to disabled webview scroll, but after that zooming works incorrectly. It always zoom to the top left conner.
Is there is a possibility to disable only vertical scroll in webview?
**To Reproduce:**
- set height to webview
- disable webview scroll 
- try to zoom webview

**Expected behavior:**
zoom works correctly
 
![Screen Recording 2019-09-24 at 12 38 22](https://user-images.githubusercontent.com/46888311/65501233-48a3d500-dec9-11e9-8cc1-e3d0ebf57d07.gif)

**Screenshots/Videos:**
webview zoom to the top left conner

![Screen Recording 2019-09-24 at 12 50 00](https://user-images.githubusercontent.com/46888311/65501609-f616e880-dec9-11e9-8377-2b82e02a29b2.gif)

**Environment:**
 - OS: Mac os 
 - OS version: 12
 - react-native version: expo 33
 - react-native-webview version: ~5.8.1

**Comment by davidhlee** [comment]
This issue doesn't seem to be resolved. I'm still encountering this when I set scrollEnabled=false. The focal point of the zoom gets pinned to the top left instead of from where I pinch from.
