### ISSUE TITLE
Cursor overlaps keyboard in webview in android

### ISSUE THREAD

**Issue by AlekseyKutsko** [react-native-community/react-native-webview#899]
**Bug description:**
I set focus to div with attribute contenteditable="true" and scroll content. When cursor is under keyboard, it overlaps keyboard.

**Expected behavior:**
Cursor doesn't overlap keyboard

**Screenshots/Videos:**
[https://monosnap.com/file/59vXU3OWYlU0mw9w6VSFrHD5ylYa5P](https://monosnap.com/file/59vXU3OWYlU0mw9w6VSFrHD5ylYa5P)

**Environment:**
 - OS: Android
 - OS version: 7.1.2
 - react-native version: 0.59.9
 - react-native-webview version: 5.12.1

**Comment by jzyds** [comment]
same issue
