### ISSUE TITLE
MIGRATED: The use of postMessage will lead to WebView onLoadStart run Twice (#16547)

### ISSUE THREAD

**Issue by jamonholmgren** [react-native-community/react-native-webview#9]
Migrated from https://github.com/facebook/react-native/issues/16547.

@TrustTheBoy says:

---

Environment
OS: macOS Sierra 10.12.6
Node: v7.10.0
Yarn: 0.27.5
npm: 4.2.0
Watchman: 4.7.0
Xcode: Xcode Version 9.1 beta (9B37)
Android Studio: 2.3
react-native: 0.48.4
react: 16.0.0-alpha.12
Target Platform: iOS (8-11.1) android(4.4.4-8.0)

Steps to Reproduce
messtest = e => {
  const message = e.nativeEvent.data
  alert(message)
}
<WebView
  ref={w => this.webview = w}
  source={{uri:jumpUrl}}
  onMessage={this.messtest}
  domStorageEnabled={true}
  javaScriptEnabled={true}
  startInLoadingState={true}
  dataDetectorTypes="none"
  onLoadEnd={()=>{
    console.log('load end... onLoadEnd function');
  }}
  onLoadStart={()=>{
    console.log('load start..');
  }}
  renderLoading={this._renderLoading}
  //onNavigationStateChange={this.onNavigationStateChange}
/>
![image](https://user-images.githubusercontent.com/20201085/32039573-f34cd0f8-b9f3-11e7-8e61-1ba1b39f8db5.png)

Expected Behavior
LoadStart should be executed before loadEnd,As you can see from the diagram, load end... re executes load start, and then does not execute load end, which causes the state to be updated. It has always been load start

---

_More info in original issue thread_

**Comment by Titozzz** [comment]
Will probably need to be closed once #66 is solved

**Comment by 1111mp** [comment]
@Titozzz How to solve it in IOS

**Comment by Ehesp** [comment]
Closing as fixed in https://github.com/react-native-community/react-native-webview/issues/66 - if this is still an issue let us know and we'll re-open.
