### ISSUE TITLE
crash on second try of image download  

### ISSUE THREAD

**Issue by asmakhalfallah2018** [react-native-community/react-native-webview#905]
When downloading an image in react-native-webview (on android) the first time the download is working fine and no crash , the second time when we try to download the same image  the dowload 
is achieved but app crashes

**Expected behavior:**

downloading the same image more than one time without app crashing 

Logcat android:

> 'Encountered an error loading page', { description: 'net::ERR_FAILED',
>       code: -1,
>       canGoForward: false,
>       canGoBack: true,
>       title: '30',
>       loading: false,
>       url: 'https://www.lirao.fr/QryIsapi.dll?MfcIsapiCommand=GetUploadedAttachement&file=$TYPE-3-2019-09-26-11-16-57-upload-0$IMG_1569489449115.jpg&forceDownload=1',
>       target: 319 }

**Environment:**

 - react-native version:0.59.8
 - react-native-webview version:5.12.1

some code 👍 

     `import React, { Component } from 'react';
     import { WebView } from 'react-native-webview';
     class CustomWebView extends Component {
    render() {
    return (
      <WebView
      contentInset={this.props.contentInset}
      style={this.props.style} // workaround for ios webview bug ....
      ref={this.props.refFunction}
      userAgent={this.props.userAgent}
      javaScriptEnabled={this.props.javaScriptEnabled}
      injectedJavaScript={this.props.injectedJavaScript}
      geolocationEnabled={true}
      source={this.props.source}
      onNavigationStateChange={this.props.onNavigationStateChange}
      onMessage={this.props.onMessage}
      renderError={this.props.renderError}
      mixedContentMode={"always"}
      onError={this.props.onError}
      onLoadEnd={this.props.onLoadEnd}
      startInLoadingState={this.props.startInLoadingState}
      renderLoading={this.props.renderLoading}
        />
      );

**Comment by hadassaChemouni** [comment]
I have the same error.
@asmakhalfallah2018  Did you find a solution ?

**Comment by MingBillCheng** [comment]
I have the same problem. Did you find any solution ?

**Comment by zhang-shoujian** [comment]
I have the same problem on Android 7.

**Comment by jihanarifia** [comment]
Currently, I have the same problem on android 10, the apps is always force close
