### ISSUE TITLE
Downloading a URI starting with blob:http://... on android crashes the app

### ISSUE THREAD

**Issue by JulianaCP** [react-native-community/react-native-webview#909]
**Bug description:**
I have a webview on Android that attempts to download an embedded pdf file via a blob URL. However, the app crashes on such attempt.

**To Reproduce:**

import React from 'react'
import { View } from 'react-native'
import { WebView } from 'react-native-webview'

const App = () => {
  return (
    <View style={{ flex: 1 }}>
      <WebView
        source={{
          uri: 'blob:https:// url'
        }}
        javaScriptEnabled
        allowFileAccess
        mixedContentMode={'always'}
        domStorageEnabled
        textZoom={150}
      />
    </View>
  )
}

export default App;

The link  should download a file, but the app crashes on clicking the link.
in this case the blob is in th uri by default but if a user clicks in a button  inside any website like google.com that generate a blob download the app crash.

![image](https://user-images.githubusercontent.com/14304676/65693066-e7971100-e030-11e9-8849-8ea6080e2983.png)

**Comment by TobalOW** [comment]
same issue here

**Comment by suryacaprice** [comment]
We have the same issue
