### ISSUE TITLE
WebView will not start render if the page/tab it is on is not the active tab of a bottomTabNavigator

### ISSUE THREAD

**Issue by connor-odoherty** [react-native-community/react-native-webview#913]
**Bug description:**

The WebView does not launch until the page it is rendered on is "active".

For example:

I use react-navigation to create a `bottomTabNavigator`. When I set `lazy` to false, it renders all tabs, both the one currently focused, and all the other tabs in the background.

On some of these pages, I render a WebView. However, despite the components still loading and rendering the background, the WebView does not launch (onLoadStart doesn't even start) until I navigate to the page it is contained on.

**To Reproduce:**

From a StackOverflow with the same issue:

```
Tab

const Tab = () => { 
    console.log('render') // this is being called right away

    return (<WebView 
             onLoadStart={() => console.log('on load start') // this is being called only when tab becomes active (clicking on it) }
             source={{uri:'linkgoes.here'}} />) 
}
```

```
  const TabNavigator = createBottomTabNavigator(
  {
    TabOne: {
      screen: Tab
    },
    TabTwo: {
      screen: Tab
    }
  },
  {
    initialRouteName: 'TabOne',
    lazy: false,
  }
)
```

You will see that the WebView does not start until the page gains focus.

**Expected behavior:**

The WebVIew renders in the background, and should be loaded by the time I actually navigate to the page.

**Environment:**
 - OS: iOS
 - OS version: iOS 13.1
 - react-native version: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz
 - react-native-webview version: 7.0.5

**Other notes**

Looks like it's a bug where it returns early if no window is present

This SO user had a similar experience: https://stackoverflow.com/questions/56923273/react-native-webview-only-starts-loading-when-on-active-tab-in-react-navigation

There is PR out to solve the issue, but it looks like it comes with a bunch of bad side effects: https://github.com/react-native-community/react-native-webview/pull/813

**Comment by connor-odoherty** [comment]
Any updates or possible workarounds for this issue?

**Comment by adimshev** [comment]
Please fix it! Our users have bad experience because of this!

**Comment by PradeepVL** [comment]
Did we find the solution or any patch
?
