### ISSUE TITLE
Update React Native Documentation

### ISSUE THREAD

**Issue by lcsvcn** [react-native-community/react-native-webview#916]
showsVerticalScrollIndicator = {false}
showsHorizontalScrollIndicator = {false}

It's not on https://facebook.github.io/react-native/docs/webview but it works!

It makes the scroll bar invisible on the webview.

It should be nice to have an updated documentation!!

**Comment by Titozzz** [comment]
this documentation lives under the docs repository on this repo directly! For an updated reference check it out :). If anything is missing from there please PR ❤️
