### ISSUE TITLE
index.js refers to lib/WebView even though that doesn't exist. Should be src/WebView

### ISSUE THREAD

**Issue by Aequitas737** [react-native-community/react-native-webview#917]
**Bug description:**
Error during bundling because file `./lib/WebView` cannot be found.
If I change lib to src then it works fine (until next yarn install obviously)

**To Reproduce:**
add `    "react-native-webview": "react-native-community/react-native-webview#v6.9.0",` to package.json
`yarn run install`
`yarn run start` -> errors once you connect a device and start bundling

**Expected behavior:**
no error, shouldn't have to manually edit the file after each install.

**Environment:**
 - Windows 10
 - Samsung Galaxy S6,
 - Android 7.0
 - yarn: 1.5.1
 - react-native version: 0.59.9
 - react-native-webview version: 6.9.0

**Comment by 1442916418** [comment]
你好！
 react-native-webview#v5.0.1 版本报错：
![image](https://user-images.githubusercontent.com/42958928/67270198-c4a23480-f4ea-11e9-8591-d5a5f0981dd6.png)
请问这个应该在什么地方修改！谢谢！
