### ISSUE TITLE
 java.lang.IllegalStateException: Unable to create layer for RNCWebViewManager$RNCWebView

### ISSUE THREAD

**Issue by kefyru** [react-native-community/react-native-webview#921]
in some android devices i had this error:
 java.lang.IllegalStateException: Unable to create layer for RNCWebViewManager$RNCWebView

**Comment by al-shivani** [comment]
Hi 
I am also getting the same error. Any Solution?

**Comment by Asleepace** [comment]
Any update on this?

**Comment by safaiyeh** [comment]
Can you make a reproducible repo and mention which phones this occurs on?

**Comment by Gregoirevda** [comment]
Made a repo here: https://github.com/Gregoirevda/react-native-webview-fail
Using version react-native-webview@11.17.0

Running on Android 11 crashes. Solved by adding `androidLayerType="hardward"` (software also works, but not on Android 8)

The issue happens when the WebView is

**Comment by keerthipativinaykumar** [comment]
Same it's working for latest version when adding the hardware tag but in lower versions like 8 Android it's crashing any rectify example please share

**Comment by fdobre** [comment]
Can we re-open this? Anybody any idea how to fix the crash on Android 8?

**Comment by Solly74** [comment]
Can this be re-opened please? I am experiencing the same issue for Android 8
