### ISSUE TITLE
decelerationRate prop doesn't have any effect for WKWebviews

### ISSUE THREAD

**Issue by TristanH** [react-native-community/react-native-webview#927]
**Bug description:**
Regardless of what value I set [decelerationRate](https://github.com/react-native-community/react-native-webview/blob/master/docs/Reference.md#decelerationrate) to, it seems to not change the behavior of the webview. Instead, it stays at relatively high deceleration rate. The decelerationRate is much higher than the same url when opened in iOS safari.

**To Reproduce:**
Made a Snack reproducing this:

https://snack.expo.io/@readwise/decelerationrate-bug-example

**Expected behavior:**
Notice the iOS scroll deceleration rate in the Snack, then open the same webpage on iOS safari and try scrolling. On iOS safari the deceleration is a lot slower, and feels more natural.

**Environment:**
 - OS: iOS
 - OS version: 13
 - react-native version: latest?
 - react-native-webview version: 7.4.0

**Comment by raymondjacobson** [comment]
also seeing this

**Comment by jcottam** [comment]
Update value to an integer - works for me as such `decelerationRate={1}`

**Comment by ts-mms** [comment]
thank you @jcottam !

**Comment by davibe** [comment]
It is not working for me today with the latest version of iOS, Xcode, and this library

**Comment by FlashTang** [comment]
I'm not use this react but swift native , I noticed this too , ios 15 and latest Xcode
`webView.scrollView.decelerationRate = .fast`
just not working

**Comment by FlashTang** [comment]
> I'm not using react but swift native , I noticed this too , ios 15 and latest Xcode `webView.scrollView.decelerationRate = .fast` just not working

solution：
webView.scrollView.decelerationRate must inside scrollViewWillBeginDragging like so :
```
func scrollViewWillBeginDragging(_ scrollView: UIScrollView) {
        scrollView.decelerationRate = .fast
}
```
