### ISSUE TITLE
Warning: [RCTRootView cancelTouched] is deprecated and will be deleted soon.

### ISSUE THREAD

**Issue by uxman-sherwani** [react-native-community/react-native-webview#930]
**Bug description:**
After upgrading from react-native 0.60.5 to 0.61.2, a screenshot warning to show up on every click inside the web view.

**To Reproduce:**
Fresh install of react-native-webview on a new react-native 0.61.2 project

**Screenshots/Videos:**
![Simulator Screen Shot - iPhone X - 2019-10-03 at 15 28 42](https://user-images.githubusercontent.com/3153380/66131551-e5feb780-e5f3-11e9-91ca-0e1cfd324f6b.png)

**Environment:**
 - OS: MacOS
 - OS version: Mojave 10.14.6
 - react-native version: 0.61.2
 - react-native-webview version: 7.4.0

**Comment by suretarget** [comment]
https://github.com/kmagiera/react-native-gesture-handler/pull/657

**Comment by fuermosi777** [comment]
I don't think react-native-gesture-handler's case has anything to do with this one as the web view doesn't depend on that package.

**Comment by leitom** [comment]
I can confirm this issue on both android and ios with the specified versions above.
When both platforms are in release mode on device the app force-quit's.

**Comment by fekajin** [comment]
same issue..

**Comment by student-t** [comment]
?
