### ISSUE TITLE
Enable to dymanically toggle prop "hideKeyboardAccessoryView" on ios

### ISSUE THREAD

**Issue by shuuha** [react-native-community/react-native-webview#933]
Hello, It would be nice to have this feature if possible. Currently in my project I need to make `hideKeyboardAccessoryView` visible on certain web screens, but with the existing implementation I can only disable it and after that it stays in that state till the end, or remount of the Webview, but remounting is not the solution in this case.
Would greatly appreciate any help in this, even any directions what direction I should dig in the native code even though I am not familiar with obj-c.

**Comment by julien-meichelbeck** [comment]
Same issue here, this is actually a bug as the prop is not taken into account, just the default/first value.

> Would greatly appreciate any help in this, even any directions what direction I should dig in the native code even though I am not familiar with obj-c.

Same!
