### ISSUE TITLE
For IOS 13 react-native-webview is  not showing pdf file

### ISSUE THREAD

**Issue by shoaib2019** [react-native-community/react-native-webview#936]
**Bug description:**

For IOS 13, react-native-webview is showing a string instead of pdf. It is working fine on ios 12 or less. 

**To Reproduce:**

- update your ios to ios 13
- run a react native web view sample project with url of pdf
**Expected behavior:**

- it should render a pdf
![Screen Shot 2019-10-07 at 3 01 00 PM](https://user-images.githubusercontent.com/46445441/66302954-5d458b80-e913-11e9-9eb1-c13f517bfa7f.png)

**Screenshots/Videos:**

*
![IMG_71FFB325CC1E-1](https://user-images.githubusercontent.com/46445441/66302900-3edf9000-e913-11e9-97f6-ba38dc661470.jpg)
*Environment:**
 - OS: IOS
 - OS version: 13
 - react-native version: 0.59
 - react-native-webview version: 7.4.1

**Comment by e-klimovich** [comment]
I have the same problem. also i tried to downgrade `react-native-webview` to `6.0.2` and `5.0.1`, `useWebKit={true}` - nothing changed

**Comment by bcgilliom** [comment]
This seems to be specifically on PDFs with the header: `content-type: application/octet-stream`

**Comment by krisnadiputra** [comment]
I have the same problem, it works well on ios 12 or less, but showing nothing (keep loading) after upgrading to ios 13.

**Comment by eladgel** [comment]
fixed this with this [pull request](https://github.com/react-native-community/react-native-webview/pull/963)

**Comment by Titozzz** [comment]
This pull request means trusting file extenstion over mime type, are we sure that is a good idea ?

**Comment by kingdaro** [comment]
Still waiting for this PR https://github.com/react-native-community/react-native-webview/pull/963

**Comment by Liqiankun** [comment]
@kingdaro this PR is not working on iOS 12.
