### ISSUE TITLE
Clear cookies on demand

### ISSUE THREAD

**Issue by bscaspar** [react-native-community/react-native-webview#937]
I am using a webview for Instagram oauth. The user's auth details are saved to the webview so when they close the app/reopen, they remain logged in (same behavior as in a browser). This is great! However, when they log out, I need to clear the cookies so their auth details are removed from the webview. I'm using expo so can't dive into native code, and react-native-cookies isn't a viable solution. Nor is incognito={true} since I need the cookies to persist until they are cleared on logout.

**Comment by byteasc** [comment]
You may be able to use RCTNetworking to clear the cookies

**Comment by bscaspar** [comment]
That's what I use currently, unfortunately it doesn't look like that works with the new WKWebView implementation - it did with the old UIWebView.

**Comment by byteasc** [comment]
That sucks :/ Hadn't messed much with the webview with the changes so wasn't sure

**Comment by Linuhusainnk** [comment]
Have you got any solution?
