### ISSUE TITLE
How to get html code using injectedJavascript - React-native

### ISSUE THREAD

**Issue by TajSinghESGI** [react-native-community/react-native-webview#941]
Hi everyone, I wanna access the html code of youtube in react native. I need to use the injectedJavascript in order to render the youtube channel without the headerBar, so I tried : 

```
render(){

    let jsCode = `
        document.querySelector("header-bar").style.display = "none";
        `;

    return(
        <WebView
          style={{flex:1}}
          javaScriptEnabled={true}
          source={{uri: 'https://www.youtube.com/watch?v=c4Hi8OVEbuY&list=PLSlVQ0kIy6qzezeIJZW6SAl-cMiyvvbhN'}}
          injectedJavascript={jsCode}
       />
    )
}
```

But it's not doing what I want, I think I'm not accessing it the good way. Can someone know how to do it ?

Thanks

**Comment by usmanrwp** [comment]
document.getElementById("your header id").innerHTML = '';
