### ISSUE TITLE
Sending request headers to next redirect

### ISSUE THREAD

**Issue by TheMakerOleguch** [react-native-community/react-native-webview#943]
**Bug description:**
Hi. I am trying to load web page with several redirects according to OAuth logic, while iOS working properly, for Android i see a canceled requests. While debugging request headers each of them i see that for Android i am not sending referrer and other headers. I have tried to remove handling for shouldOverrideUrlLoading and all seem work properly, i see that i can get headers from WebResourceRequest but it is supported only from ANDROID.VERSION.N.
As i can see we forgot all request headers after redirect and load pure one, am i wrong?

**To Reproduce:**
Load simple webpage with OAuth redirects and see behavior on Android

**Expected behavior:**
Successfully login and see home page

**Screenshots/Videos:**

**Environment:**
 - OS: Android
 - OS version: 28
 - react-native version: 0.60.7
 - react-native-webview version: 7.4.1

**Comment by kaystd** [comment]
Same issue

**Comment by gabriel-tentaculo** [comment]
@TheMakerOleguch hi there, how did you inspect the request headers going out of the app?
I have tried using fiddler to inspect network traffic but nothing that passes through the webview is logged.
