### ISSUE TITLE
Webview not appearing in Expo Web

### ISSUE THREAD

**Issue by HaseemUlHaq** [react-native-community/react-native-webview#945]
**Bug description:**
Working fine in expo mobile app, but same code doesn't show anything when opening Expo App on Web browser by running command expo start --web

**Environment:**
 - expo: "^35.0.0"
 - react-native : "https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz"
 - react-native-webview: ^7.4.1

**Comment by supersh86** [comment]
I have the same error.

**Comment by internetammo** [comment]
still a bug
