### ISSUE TITLE
iOS13 can't save image

### ISSUE THREAD

**Issue by guoxuzan** [react-native-community/react-native-webview#946]
**Bug description:iOS13 can't save image from webview

**To Reproduce:**

**Expected behavior:**

**Screenshots/Videos:**

**Environment:**
 - OS:iOS
 - OS version:13
 - react-native version:0.55.1
 - react-native-webview version:7.4.1

**Comment by rlebosse** [comment]
The issue is still here.

If it can help :

**Comment by KingAmo** [comment]
so could you please tell me how you save image from WebView?
