### ISSUE TITLE
Log Network Request

### ISSUE THREAD

**Issue by rahultatvasoft** [react-native-community/react-native-webview#949]
**Bug description:**
@Titozzz Want to log network request when internally call api in webview.

i call one webpage in webview, this page internally calls many api, i want log these apis. it's header request or response. so how can i trace?

**Environment:**
OS: macOS Mojave
OS version: 10.14.6
react-native version: 0.60.4
react-native-webview version: 7.4.1

**Comment by frankoprifti** [comment]
I want to get video source from a movie site so I can play with external player and download it.
I have done with an external heroku puppeteer scraper that im intercepting network requests but ideally it should work directly from intercepting network requests that webview makes

**Comment by longlwu2000** [comment]
> I want to get video source from a movie site so I can play with external player and download it. I have done with an external heroku puppeteer scraper that im intercepting network requests but ideally it should work directly from intercepting network requests that webview makes

English is not my native language, so please excuse any mistakes. I am developing an application with features similar to yours. Have you found a way to intercept network calls in WebView? Could you please share how you managed to do it? Thank you.
