### ISSUE TITLE
How could I get cookie in webview which is set in react-native?

### ISSUE THREAD

**Issue by taoqf** [react-native-community/react-native-webview#950]
**Bug description:**

I have fetch a request in react-native, then the server response set a cookie named `jssession`.

When I send http request in webview, the request header does't contain  the cookie `jssessionid`.

**To Reproduce:**

**Expected behavior:**

If cookie is set in one side (react-native or webview), the other(webview or react-native) will share the same cookie.

**Screenshots/Videos:**

**Environment:**
 - OS: Android and IOS
 - react-native version: 0.59.10
 - react-native-webview version:5.12.1

**Comment by alubeck** [comment]
Your react-native-webview version is quite old? There were a huge changes since them, i.e. favoring ```WKWebView``` instead of ```UIWebView```.

Which is your iOS version where you experienced your problem?

I have an issue with iOS11 and cookies in webview. They just do not get restored and I get logged out in webview.

**Comment by taoqf** [comment]
Yes, `5.5.0` which I am using.
I am trying to upgrade to latest version now, but there's lots of error when I upgrade react-native to 0.60.x.

**Comment by canaanites** [comment]
+1 cookie problem!

**Comment by netgfx** [comment]
I don't have that issue, since I can login to gmail and other sites and even after I close the App and re-enter I am still logged on or my cart has the items added (even if I'm not logged in).

**Comment by netgfx** [comment]
@canaanites I'm not directly manipulating site cookies, however doing API calls that require session information seems to work, and backend is able to retrieve Session information successfully.

**Comment by safaiyeh** [comment]
The solution for this is to use react-native-cookies. iOS stores session & http-only cookies on the device and removes them from the response headers. https://github.com/joeferraro/react-native-cookies

**Comment by SwathyPA** [comment]
Still searching for a solution
