### ISSUE TITLE
WebView inside ScrollView problem

### ISSUE THREAD

**Issue by oliverdolgener** [react-native-community/react-native-webview#951]
**Bug description:**
We are using a WebView inside a ScrollView to display other RN components above or below the WebView. This worked perfectly fine before upgrading from RN 0.59.10 to 0.60.5 and above. Now we're facing an annoying bug (on Android, iOS works fine) where the ScrollView automatically scrolls to the WebView's position when tapping the WebView (see video). That behaviour only occurs for the first tap after the initial rendering.

**To Reproduce:**
```
return (
    <ScrollView>
      <Text style={{ fontSize: 20 }}>Native Component</Text>
      <Text>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</Text>
      <Text style={{ fontSize: 20 }}>WebView</Text>
      <WebView style={{ height: 1000 }} source={{ uri: 'https://www.lipsum.com/' }} />
    </ScrollView>
);
```

**Expected behavior:**
The ScrollView should not scroll to the WebView's position. It should keep it scroll position.

**Screenshots/Videos:**
![WebView_ScrollView](https://user-images.githubusercontent.com/22632842/66749993-8920be00-ee8b-11e9-8ff1-7cccb4a23ce7.gif)

**Environment:**
 - OS: Android
 - OS version: 9
 - react-native version: 0.61.2
 - react-native-webview version: 7.4.2

**Comment by aryojamousi** [comment]
Can confirm this, having the same issue...

**Comment by Sanan4li** [comment]
I am getting this error.
Invariant Violation: View config not found for name RNCWebView.]
if anyone knows solution please share

**Comment by harryharihar** [comment]
what is the solution , i am facing this issue from long day back .

**Comment by Aryojaam** [comment]
We are still facing the problem and still looking for a solution...

**Comment by kaysiegert** [comment]
The issue is still exists.

**Comment by aryojamousi** [comment]
The issue is most likely caused by this commit in the React-Native project:
https://github.com/facebook/react-native/pull/25105/files#diff-d0c2b20a285e8b8516a8e95010d86569R230

**Comment by Zynio** [comment]
+1

**Comment by ozerty** [comment]
Any news about this issue ?

**Comment by Zakyyy** [comment]
+1

**Comment by supersunkist** [comment]
me too

**Comment by Hannes-Endare** [comment]
Any progress on this?

**Comment by Aryojaam** [comment]
from the looks of it, try to avoid this?!! :/

**Comment by ngsayjoe** [comment]
Can confirm that the issue still persists as of 11.0.3

**Comment by hblab-luunv** [comment]
https://stackoverflow.com/a/65942887/17307562
fix this issue
