### ISSUE TITLE
post request work in android but not in IOs.

### ISSUE THREAD

**Issue by celciusjj** [react-native-community/react-native-webview#953]
**Bug description:**

I have a application with a webview, this webview have a post request, the webview works in android and get the page, but when i try in IOs does not work.

You can visualize the token in console, and the uri

the exception occurs in postman when the token is invalid, but it is not invalid because it works in postman and android.

The page not is mine

**Expected behavior:**
Show the page in IOs same to android.

![image](https://user-images.githubusercontent.com/37490999/66847060-5ed90a00-ef38-11e9-890f-f05584c32820.png)

**The code**

```
            <WebView
            
            nativeConfig={{props: {webContentsDebugginEnabled: true}}}
            source={{uri: navigation.getParam('uri'), method: 'POST', body: `token=${navigation.getParam('token')}`}}
            injectedJavaScript={injectedJavascript}
            onMessage={() => this.props.navigation.navigate('Main')}
            startInLoadingState={true}
            >
            </WebView>

**Comment by PAronofsky** [comment]
> i solve this error with
> 
> > I've faced that bug too. Here is a workaround that worked for me :
> > headers: { 'Content-Type': 'application/x-www-form-urlencoded', }

Does Android automatically send this header? Anyone know what the difference is that would explain what's going on here?

**Comment by Wsm2018** [comment]
Anyone found a fix for this? 
Similar to the issue, I have a payment gateway where i send the data using POST request in the WebView. 
For Android, there is no issue. Works as expected. But on iOS, it is not working. I added this as well 
headers={{
        'Content-Type': 'application/x-www-form-urlencoded'
}}
But it still does not work. 
Anyone knows a fix for this ??

**Comment by Wsm2018** [comment]
@celciusjj Were you able to find a solution for this ????

**Comment by MatteoMark** [comment]
@Wsm2018 Hello,
you have to add it to the "source" parameter, not as a parameter itself.
For instance:
```
<WebView
	source={{ uri: "www.google.it", method: 'POST', body: html_body, headers: { 'Content-Type': 'application/x-www-form-urlencoded', }}}
	javaScriptEnabled={true}
	originWhitelist={['*']}
	onMessage={(event) => method()}
....
```
Hope this helps

**Comment by BinaryVigilante** [comment]
Why has this issue been closed?

When I add `headers: { 'Content-Type': 'application/x-www-form-urlencoded', }` I get `WebView: `source.headers` is not supported when using POST.` in the console.

**Comment by harshrajput688** [comment]
`<key>NSAppTransportSecurity</key>
<dict>
    <key>NSAllowsArbitraryLoads</key>
    <false/>
    <key>NSAllowsArbitraryLoadsInWebContent</key>
    <true/>
    <key>NSAllowsLocalNetworking</key>
    <true/>
    <key>NSExceptionDomains</key>
    <dict>
        <key>your-api-domain</key>
        <dict>
            <key>NSIncludesSubdomains</key>
            <true/>
            <key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
            <true/>
            <key>NSTemporaryExceptionMinimumTLSVersion</key>
            <string>TLSv1.1</string>
        </dict>
    </dict>

> Replace "your-api-domain" with your API domain and
Add this to your info.plist and start your project again

**Comment by zabojad** [comment]
@Wsm2018 Did you find a solution ?

Neither @BinaryVigilante  nor @harshrajput688 seems to work...

**Comment by eduardo-santos-tribia** [comment]
I'm facing the same issue as @zabojad, so the solutions provided are not working.

**Comment by eduardo-santos-tribia** [comment]
I think I found the reason for the issue on iOS:

iOS is always passing `{ Origin: "file:// } `as a Header prop and in my case my server does not allow it. I'm trying to remove this Origin or change it during the Webview POST, but I have had no success.
