### ISSUE TITLE
Listen to `postMessage` event within web view and redirect to React Native

### ISSUE THREAD

**Issue by hoangpham95** [react-native-community/react-native-webview#954]
**Bug description:**
I am trying to listen to a special message inside my webview and redirect the event back to React Native:
```typescript
render() {
     const redirectPostMessage = `(function() {
            alert("Hello, world! 1");
            window.addEventListener("message", function (event) {
                window.ReactNativeWebView.postMessage(JSON.stringify(event.data));
            });
        })();`;

        return (
            <WebView
                renderLoading={() => <ActivityIndicator />}
                ref={r => this._webView = r}
                javaScriptEnabled={true}
                injectedJavaScript={redirectPostMessage}
                onMessage={this._onMessage.bind(this)}
                source={{ uri: someURL }}
                bounces={false}
                onLoad={this._onLoad.bind(this)}
                onError={this._onLoadError.bind(this)}
                onLoadStart={this._onLoadStart.bind(this)}/>
        );
}
```
**Expected behavior:**
`onMessage` should be able to listen to the postMessage event within the webview.

**Actual result**
React Native onMessage can't receive any message from postMessage within the web view.

**Environment:**
 - OS: iOS
 - react-native version: 0.59
 - react-native-webview version: 7.4.2

**Comment by khuongTiet** [comment]
I ran into a similar problem so I put up this PR: https://github.com/react-native-community/react-native-webview/pull/958,

I think this could help solve your problems!

**Comment by hoangpham95** [comment]
yep I ended up changing the `MessageHandlerName` variable. Also, `react-native-webview` should expose an API/props to register `MessageHandlerName`, e.g.
```
<WebView registeredMessageHandler={["MyCustomMessageHandler1", "MyCustomMessageHandler2"]}
    {...otherProps}/>
```
So all the `postMessage` from other message handler can be handle within React Native.

**Comment by hoangpham95** [comment]
Btw @khuongTiet  my problem is a little bit different. My webview consumes an embed video and the iframe using its own message handlers to send message to hosted webview, that's why I couldn't receive the `postMessage` from the iframe with the default message handler.

**Comment by joshbax** [comment]
@hoangpham95 
In the file `RNCWKWebView.m`, (or `RNCUIWebview.m` if you set `useWebKit={false}`) find where the message `postMessage:(NSString*)message` is implemented. Then replace the line:
