### ISSUE TITLE
iOS: Not send data on form with target is "blank"

### ISSUE THREAD

**Issue by FonDorn** [react-native-community/react-native-webview#957]
**Bug description:**
When submit form with **target="_blank"** then no data sending on action url. If form target is **_self** then work as expected. On Android with _target="\_blank"_ work as expected too.

**To Reproduce:**
For example create form with _target="\_blank"_:
```
...
<form method="POST" action="https://blabla.com/login" target="_blank">
<input type="hidden" name="data" value="testData" />
<button type="submit">Go</button>
</form>
...
```

**Expected behavior:**
Redirect to site with next url: `https://blabla.com/login?data=testData`, but redirect to `https://blabla.com/login` without data.
If change target to _target="\_self"_ will work as expected.

**Environment:**
 - OS: iOS
 - OS version: 13.1
 - react-native version: 0.60.4
 - react-native-webview version: 7.4.1

**Comment by artsnr1** [comment]
For me it's working on ios but not on android

**Comment by toffo10** [comment]
Seems like the bug is still present on iOS 17.4
