### ISSUE TITLE
Browser Local Storage

### ISSUE THREAD

**Issue by zelenko** [react-native-community/react-native-webview#964]
**Bug description:**
When moving from Expo 34 to Expo 35 the WebView was moved from `react-native` to `react-native-webview`.  Since that change was made local storage in WebView stopped working.  It was working fine before.

**To Reproduce:**
Login to https://login.salesforce.com/ with one username, logout and login with second username.  

**Expected behavior:**
All used usernames should be stored in local storage.

**Screenshots/Videos:**

**Environment:**
 - OS: IOS
 - OS version: IOS 13.1.2
 - react-native version: React Native 0.59
 - react-native-webview version: 7.0.5
 - Expo CLI version: 3.4.0
 - Expo SDK version: 35.0.0

**Comment by jrvq** [comment]
I'm having the same issue
