### ISSUE TITLE
allowFileAccessFromFileURLs not working on iOS

### ISSUE THREAD

**Issue by Lestat86** [react-native-community/react-native-webview#970]
Hi guys,
i've encountered this bug on iOS devices: 
I have a local html static site in my main application bundle. 
If i load said file inside a webview, when my html tries to load any content with another `file://` call (done by javascript), i get an error. I don't even know what the error is, because all i get is a `Webcontent process terminated`.

I've investigated a little - well, a lot - and i found the solution: if i add this line 
```swift
[_webView.configuration.preferences setValue:@TRUE forKey:@"allowFileAccessFromFileURLs"];
```
to line 258 of `RNCWebView.m`, then the errors mutate to something telling me that i don't have permission to do that.

With this info, i copy my site folder to the cache folder (i.e. `RNFS.CachesDirectoryPath`) and set the `allowingReadAccessToURL` to that - and voilà, it works.

I cannot understand any of objective c/swift, so i'd rather not do a messy pull request - but i think that this issue could be easily solved by managing the `allowFileAccessFromFileURLs` param, as it is done in the android version.

**To Reproduce:**
Create a static page with some js that access another file via `file://`
Create a webView like so:
```react-native
    const options = {
      allowsInlineMediaPlayback:        true,
      javascriptEnabled:                true,
      allowFileAccess:                  true,
      allowUniversalAccessFromFileURLs: true,
      allowFileAccessFromFileURLs:      true,
      mixedContentMode:                 'always',
      originWhitelist:                  [ '*' ],
      source: 'file://path/to/file'
    }
   
   <WebView {...options}/>
```

See it fail as described above.

Modify as described above, and add 
```react-native
allowingReadAccessToURL:          `file://${RNFS.CachesDirectoryPath}`
```
to options, and see it work.

**Expected behavior:**
I'd like to load a static html file, containing some javascript, via the file protocol. When said javascript file tries to access another file via the file protocol, it should work.

**Environment:**
 - OS: osx
 - OS version: mojave
 - react-native version: 0.60
 - react-native-webview version: 7.4.1

**Comment by StasD** [comment]
This needs to be fixed, urgently!

**Comment by Lestat86** [comment]
There might be a pull request waiting for this, i saw it in the list...

**Comment by StasD** [comment]
I didn't search, but I'm now trying to fix this myself. If I'm successful, I will create a new pull request! :)

**Comment by Lestat86** [comment]
Great! :)

**Comment by StasD** [comment]
Here: https://github.com/react-native-community/react-native-webview/pull/1061 :)

**Comment by knivesq** [comment]
Somehow I am still having this issue, at first it was fixed, but since 24 january I can't do file urls requests anymore, is there anyone who has a working example to see if i am doing something wrong?
