### ISSUE TITLE
Preload WebView while in background/offscreen

### ISSUE THREAD

**Issue by voydz** [react-native-community/react-native-webview#971]
Hello,

first of all thanks for your time maintaining this awesome project.

**Is your feature request related to a problem? If so, Please describe.**

I am trying to preload a WebView while in background. I use react-navigation with a BottomTabNavigator and its `lazy`-mode deactivated; this renders all tabbed children at the same time. As the WebView is a direct child of one of the tabs I confirmed it calling the `render` function of the WebView tab directly at app start while the navigator is loaded. However `onLoadStart` is only called if I navigate to the WebView tab - effectively becoming onscreen and visible. This is too late in my case.

**Describe the solutions you came up with**

* I tried a forced `reload` without success. 
* Found various ways to do it in native, which are not applicable for react-native. (i.e. [see here](https://coderwall.com/p/trjkcg/preloading-uiwebview-or-wkwebview-in-swift))

**Additional context**

Tried it on iOS only at the moment.

**Comment by Ranatchai** [comment]
+1 I want to use it in the same case.

**Comment by safaiyeh** [comment]
This would need to be implemented @voydz.

Would you like to take a shot at implementing this?

**Comment by voydz** [comment]
@safaiyeh I would love to, but I am afraid I got no time at the moment to work on this reliably.

**Comment by danlannz** [comment]
This is still and issue for me but I currently don't have the time to fix it. Can we keep this issue open as a placeholder. I would like to take a shot at it when I can find the time

**Comment by connor-odoherty** [comment]
Was this regression a choice made by react-native-community/react-native-webview, or was it necessary to conform to iOS guidelines?

**Comment by MrXyfir** [comment]
Anyone have any good tips for preloading webviews?

**Comment by mykolat** [comment]
+1

**Comment by EQuimper** [comment]
@MrXyfir your idea is good, the issue I do have, is my webview are in seperate screen. I would love to preload the webview in the screen before the other one. Don't think it's possible this way. Are maybe by using something like react context and use the component to get render in but .... it's hard haha. The only way I do see is preloading a local html file

**Comment by MrXyfir** [comment]
@EQuimper Ah yeah that's a lot harder if it's on a separate screen. Something else I've done that might not work for you is for example I have three screens: Screen 1, Screen 2, Screen 3 (with webview). I needed Screen 3 to be fully loaded the second it become visible. What I ended up doing was moving Screen 2 into a modal (with https://github.com/react-native-modal/react-native-modal) that was outside of the screens and trigger by updating my global state. When the user navigates from Screen 1 to 2, what I actually do is update our global state to show Screen 2, and then after 500ms it navigates in the background from Screen 1 to Screen 3. Then when you hit "next" on Screen 2, it simply updates the global state to close the modal, leaving Screen 3 already loaded and ready to go!

**Comment by goleary** [comment]
Wow that's a gnarly workaround @MrXyfir 

Could someone please reopen this? @safaiyeh? It's still very much an issue.

**Comment by ngodangkhoa** [comment]
Have any updating for this feature?

**Comment by juanjorge** [comment]
@ngodangkhoa here there are open a PR with the fix: https://github.com/react-native-webview/react-native-webview/pull/2626

**Comment by shantanuIngle** [comment]
> @ngodangkhoa here there are open a PR with the fix: #2626

this is working great when I tried this on my local
I hope this gets verified merged soon

**Comment by Santhosh-Umapathi** [comment]
"react-native-webview": "^13.10.0"

Still the same issue, has to be reopened

**Comment by LoadJulz** [comment]
Anyone got the patch previously posted to run? I have tried it with current react native packages but for iOS it still doesn't seem to work.

**Comment by joshuarichards001** [comment]
I'm currently looking for this feature. People are still interested!

**Comment by noamyagil** [comment]
I think a fix was release according to this issue:
https://github.com/react-native-webview/react-native-webview/issues/2431
