### ISSUE TITLE
stopLoading() not working

### ISSUE THREAD

**Issue by gavrichards** [react-native-community/react-native-webview#973]
**Bug description:**

stopLoading() does not stop a tapped link from loading on Android.

I'm using react-native-webview with React Navigation. I'm trying to handle stacking webview screens using StackActions.push() to push the same route on to the stack. I've got it working fine on iOS, but on Android stopLoading() doesn't appear to do anything. Tapping a link in page A opens up page B in a new view on the stack, but underneath page B has also opened in the first view too. So when you tap back, you see the same page again, and from there there's no way to get back to the original page again. There doesn't seem to be any way to prevent this.

In addition, I often find the stacked view opening twice when tapping a link.

Related issue: https://github.com/react-native-community/react-native-webview/issues/8

**To Reproduce:**

I've created a repository with the minimum code required for this issue to be reproduced.
https://github.com/gavrichards/react-native-webview-stack
The important code is in `src/WebViewWrapper.js`

**Expected behavior:**

stopLoading() should prevent a tapped link from loading in the current webview, and allow me to make it so the link is instead loaded in a stacked route.

**Screenshots/Videos:**

https://vimeo.com/368033141

**Environment:**
 - OS: Android
 - OS version: 10.0
 - react-native version: 0.61.2
 - react-native-webview version: 7.4.3

**Comment by xAirx** [comment]
I am experiencing the same issue

**Comment by andybee** [comment]
I'm also having this issue, would really appreciate a maintainer taking a glance over this one.

**Comment by gavrichards** [comment]
Thanks @Titozzz, I think I've got it working on Android using `onShouldStartLoadWithRequest` by duplicating what I'm doing in `onNavigationStateChange`, as follows.
Is it necessary to do it this way for Android and then duplicate it in `onNavigationStateChange` for iOS?
Do I need to call `this.webview.current.stopLoading()` if I'm returning false here?
```
if (Platform.OS === 'android') {
  webViewProps.onShouldStartLoadWithRequest = event => {
    const {url} = event;

    if (url === this.props.url) {
      return true;
    }

    this.webview.current.stopLoading();

    this.props.navigation.dispatch(
      StackActions.push({
        routeName: this.props.nextRouteName,
        params: {
          url,
          title: this.state.title,
        },
      }),
    );

    return false;
  };
}
```

**Comment by MayoudP** [comment]
> Do I need to call `this.webview.current.stopLoading()` if I'm returning false here?

Does `stopLoading()` worked for you @gavrichards ? On my side it's actually not stopping the rendering of the URL I don't want to load/display :/

**Comment by gavrichards** [comment]
@MayoudP I've left the call to `stopLoading()` in there, but it seems to be the `return false` in `onShouldStartLoadWithRequest` that is doing the trick, and leaving out use of `onNavigationStateChange` altogether.

My revised `onShouldStartLoadWithRequest` is looking more like this now:
```
handleShouldStartLoadWithRequest = event => {
  const {url, navigationType} = event;

  // Only iOS gives us navigationType = 'click', which we can use to avoid stacking
  // when this event is triggered by something that's not a click on a link
  if (Platform.OS === 'ios' && navigationType !== 'click') {
    return true;
  }

  if (url === 'about:blank') {
    return false;
  }

  if (url === this.props.url) {
    return true;
  }

  // On Android, redirection would cause the destination URL to be opened in a new stack
  // Because we don't get navigationType = 'click'
  // A common redirect is http>s, so let's handle that individual case
  if (url === this.props.url.replace('http://', 'https://')) {
    return true;
  }

  this.webview.current.stopLoading();

  this.props.navigation.dispatch(
    StackActions.push({
      routeName: this.props.nextRouteName,
      params: {
        url,
        title: this.state.title,
      },
    }),
  );

  return false;
};
```

**Comment by 2xSamurai** [comment]
This is still not working for me on android. On iOS it's working fine.
`"react": "16.9.0",
    "react-native": "0.61.5",`

**Comment by gregoryfm** [comment]
Any news? Same error here.

**Comment by drkmcfrk** [comment]
+1 experiencing this as well. 

`"react": "16.8.3", "react-native": "0.59.9"` same behaivior on iOS and Android.

**Comment by alimertcakar** [comment]
This happened to me with a fresh expo + react native webview build today

**Comment by crush12132** [comment]
anything can be solved this problem?

**Comment by crush12132** [comment]
Anyone can be solved this problem?

**Comment by Takesizmail** [comment]
+1

**Comment by philiparpin** [comment]
+1

**Comment by matiasj899** [comment]
+1
