### ISSUE TITLE
is it the drop in replacement of react-native-web

### ISSUE THREAD

**Issue by kopax** [react-native-community/react-native-webview#985]
Dear all, sorry in advance if I am in the wrong place,

Is this project a drop in replacement for react-native-web ?

I ask because react-native-web is not compatible yet with react-native 0.60 so xandroid, and all the description of the project I read call the thing webview, but I have no clue if it's meant to be compatible with web.

Thanks a lot for sharing!

**Comment by filipef101** [comment]
its for rendering a webview in a react native app. Not related to that. please close the issue, thanks
