### ISSUE TITLE
Android File Upload Camera/Video isn't working properly

### ISSUE THREAD

**Issue by Elbis** [react-native-community/react-native-webview#99]
> Problem 1.

On every phone i've tested after PR#60, i can see options Camera/Video/Documents for upload type 
On my own phone, (Galaxy A3 - 5.0.2) camera is opening properly,but on Android 7 and 8(Other phones) it's not.

> Problem 2.

With Galaxy A3 5.0.2(Camera/Video/Docs option working) i can't take photo. When i take a photo, react native app is restarting. 

By the way, upload documents is working properly. 

My codes
**WebView.js**

```

import React, { Component } from 'react';
import firebase from 'react-native-firebase'
import { WebView } from 'react-native-webview'
export default class App extends React.Component {

    static navigationOptions = {
        header: null,
    };

    constructor() {
        super();
        this.state = {
            // firebase things?
            link: 'https://mobilehtml5.org/ts/?id=23',
        };
    }



    async componentDidMount() {
        const { navigation, screenProps } = this.props
        if (screenProps.webViewLink != null) {
            this.setState({ link: screenProps.webViewLink })
            console.log("webview:" + screenProps.webViewLink)
        }

        this.notificationOpenedListener = firebase.notifications().onNotificationOpened((notificationOpen: NotificationOpen) => {
            // Get the action triggered by the notification being opened


            const action = notificationOpen.action;
            // Get information about the notification that was opened
            const notification: Notification = notificationOpen.notification;
            if (notification.data.link) {
                this.setState({ link: notification.data.link })
            }
        });/*
      const gelenLink = this.props.navigation.getParam('webViewLink', 'http://www.google.com/')
      console.log("webviewden bildiriyorum: "+gelenLink)
      this.setState({link: gelenLink})*/
    }
    componentWillUnmount() {
        this.notificationOpenedListener();
    }


    render() {
        return (
            <WebView
            
            source={{ uri: this.state.link }}
            
            
        
          />
          );
    }
}

```
**AndroidManifest**
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.company.xtedarik"
    android:versionCode="1"
    android:versionName="1.0">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.CAMERA"/>
    <application
      android:name=".MainApplication"
      android:allowBackup="true"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:theme="@style/AppTheme">
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:windowSoftInputMode="adjustResize"
        android:screenOrientation="portrait" >
        
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
      <service android:name="io.invertase.firebase.messaging.RNFirebaseMessagingService">
        <intent-filter>
          <action android:name="com.google.firebase.MESSAGING_EVENT" />
        </intent-filter>
      </service>
      <service android:name="io.invertase.firebase.messaging.RNFirebaseInstanceIdService">
        <intent-filter>
          <action android:name="com.google.firebase.INSTANCE_ID_EVENT" />
        </intent-filter>
      </service>
        <provider
      android:name="com.reactnativecommunity.webview.RNCWebViewFileProvider"
      android:authorities="${applicationId}.fileprovider"
      android:exported="false"
      android:grantUriPermissions="true">
      <meta-data
        android:name="android.support.FILE_PROVIDER_PATHS"
        android:resource="@xml/file_provider_paths" />
    </provider>

    </application>

</manifest>

```
**package.json**
```
{
  "name": "xtedarik",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "babel-jest": "23.6.0",
    "fs-extra": "^6.0.1",
    "jest": "23.6.0",
    "metro-react-native-babel-preset": "0.48.0",
    "react-test-renderer": "16.5.0",
    "replace-in-file": "^3.4.0"
  },
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "apk": "cd android && ./gradlew assembleRelease",
    "rename": "node ./bin/rename.js",
    "start": "react-native start",
    "test": "jest"
  },
  "jest": {
    "preset": "react-native"
  },
  "dependencies": {
    "react": "16.5.0",
    "react-native": "0.57.1",
    "react-native-elements": "^1.0.0-beta6",
    "react-native-firebase": "^5.0.0",
    "react-native-vector-icons": "^6.0.2",
    "react-native-webview": "^2.4.0",
    "react-native-webview-file-upload-android": "^1.1.2",
    "react-navigation": "^2.18.0"
  }
}

```
```

**Comment by Titozzz** [comment]
Are you sure you did the complete setup and you are not using CAMERA without authorization ?

**Comment by andreipfeiffer** [comment]
@Elbis can you provide the native error from Android Studio?

Did you setup the FileProvider properly? IE: create the `file_provider_paths.xml` in your `/res/xml/` folder?

**Comment by finalquest** [comment]
I will try on our project to see if is also failing

**Comment by finalquest** [comment]
OK. I tested on an Samsung J7Neo, running android 7.0.
Everything is working fine.
@Elbis take into account, that for Android 6.0 and up, the request for camera permissions must be done on runtime. Is not sufficient with the ones in the manifest.xml.
You can use react-native-permissions if you want.

Regarding problem 2, I dont have a phone with android 5.x

**Comment by Elbis** [comment]
I fixed Problem 1, thank you @Titozzz & @finalquest . 
Problem 2 is still appears at Android 6.0< devices. (5.0.2)

**Comment by Elbis** [comment]
I completed setup properly by the way. It's running on Android 6.0> devices and i also have file_provider_paths.xml

**Comment by finalquest** [comment]
> I fixed Problem 1, thank you @Titozzz & @finalquest .
> Problem 2 is still appears at Android 6.0< devices. (5.0.2)

@Elbis can you upload an stacktrace of the native code?.
I cant find any device < 6.0 here. I will try to repro on emulator, but is not ideal.

regards

**Comment by Elbis** [comment]
I requesting permission at ComponentDidMount. At logs (react-native log-android) "Camera permission denied" what i have got. (Nothing appearing about permission ACCEPT/DECLINE etc.) I will try stacktrace now. Thank you for quick reply

**Comment by andreipfeiffer** [comment]
@Elbis Are you using the CAMERA permission for another feature?

**Comment by Elbis** [comment]
@andreipfeiffer No, it's already works on >6.0 
On 5.0.2, After take a photo and click "OKAY", app is restarting.
On >6.0 it's working as expected

By the way, i can't reach stacktrace of the native code. 
Is there a way to get Stacktrace? I tried gradlew.bat installDebug --stacktrace but it's not what i want

**Comment by andreipfeiffer** [comment]
If you don't use the CAMERA for something else, why do you have it in your manifest?
You don't need it for using this package.

**Comment by andreipfeiffer** [comment]
If you want to get the StackTrace, start the app using Android Studio, and it will output the error/exception.

**Comment by Elbis** [comment]
May be there is a solution like[ this](https://github.com/jamesmontemagno/MediaPlugin/issues/418#issuecomment-351874857) for API 21?

**Comment by andreipfeiffer** [comment]
Hmmm I don't see any Error, Exception, or a reason why the App crashes.
The only thing that looks weird is `W/ContextImpl: Failed to ensure directory: /storage/extSdCard/Android/data/com.sefamerve.xtedarik/files`, which might have something to do with the image storage, but it's only a Warning, not a crash Error.

I will try to find an Android 5.0 phone, to replicate this myself.
On my emulator, it works fine (no idea why).

**Comment by Elbis** [comment]
I am going crazy. When i researching this [error](https://github.com/react-native-community/react-native-webview/issues/99#issuecomment-431287573) i found a 'solution' what "reboot your phone". I don't know why but after reboot my phone, its working well. I'm sorry for this issue.

PS: I found another Android 5.0.1 device and its working well on that phone too.

You can #close this issue...

**Comment by andreipfeiffer** [comment]
OMG, really? WTF? :)
These scenarios are frikin' unbelievable.

Glad it works and thanks for the feedback :)

**Comment by Elbis** [comment]
By the way, whenever i build app to my device(A3) with react-native run-android this error appears and i have to restart my phone.

It could be it appears due to cache or storage station. 
May be a control statement need to prevent the application from destroying. I know i have to restart my phone(5.0), but users aren't 👎

**Comment by andreipfeiffer** [comment]
@Elbis could you try to build it for production?

**Comment by Elbis** [comment]
Sorry, i'm late. Yes i tried your suggestion today and it works without any error/exception or crash. Thank you for all @andreipfeiffer  🥇
