### ISSUE TITLE
How to ignore ssl check?

### ISSUE THREAD

**Issue by klower** [react-native-community/react-native-webview#990]
How to ignore ssl check?
when redirect to a https url, webview show white page.
Like android：
![image](https://user-images.githubusercontent.com/4176873/67842574-605c2200-fb35-11e9-9c49-585b081033d9.png)

**Comment by klower** [comment]
I just modified the RNCWebViewManager：
![image](https://user-images.githubusercontent.com/4176873/67844828-648a3e80-fb39-11e9-8676-f46eac78a110.png)
It works now

**Comment by klower** [comment]
I am very anxious to hope that you can add ignoreSSL property

**Comment by xuanzhiqiang** [comment]
Is there a solution to this problem? Ignore ssl verification, this should be a very important attribute.

**Comment by llauderesv** [comment]
I'm also experiencing this issue. Maybe in the future this would be supported in the library

**Comment by llauderesv** [comment]
I found this solution to disable the SSL check 

Go to:
`node_modules/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java`

and find the method named **onReceivedSslError** and update the code using the following snippet below.
```
@Override
public void onReceivedSslError(WebView view, SslErrorHandler handler, SslError error) {
   // handler.cancel(); Comment this line to by passed SSL check.
  handler.proceed();
}
```
You could also use [patch-package](https://github.com/ds300/patch-package) to handle this update.

Hope it helps.

**Comment by ahelord** [comment]
Where is location of file?

**Comment by QJerryxjh** [comment]
support it plz 求求了 orz~

**Comment by lkwjohn** [comment]
+1

**Comment by BatchCodes** [comment]
@ahelord 
`node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java`

**Comment by Chasty** [comment]
what about ios?

**Comment by RaresOP** [comment]
> @ahelord
> `node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java`

how do you trigger a rebuild after changing it?

**Comment by miteshdb** [comment]
Any solution for ios as well?

**Comment by aldunnaeyonus** [comment]
just do this.

- (void)                    webView:(WKWebView *)webView
  didReceiveAuthenticationChallenge:(NSURLAuthenticationChallenge *)challenge
                  completionHandler:(void (^)(NSURLSessionAuthChallengeDisposition disposition, NSURLCredential * _Nullable))completionHandler
{
    
	NSURLCredential * credential = [[NSURLCredential alloc] initWithTrust:[challenge protectionSpace].serverTrust];
	completionHandler(NSURLSessionAuthChallengeUseCredential, credential);
	}

**Comment by bigorangemachine** [comment]
> just do this. `
> 
> * (void)  webView:(WKWebView *)webView
>   didReceiveAuthenticationChallenge:(NSURLAuthenticationChallenge *)challenge
>   completionHandler:(void (^)(NSURLSessionAuthChallengeDisposition disposition, NSURLCredential * _Nullable))completionHandler {
>   NSURLCredential * credential = [[NSURLCredential alloc] initWithTrust:[challenge protectionSpace].serverTrust];
>   completionHandler(NSURLSessionAuthChallengeUseCredential, credential);
>   }
>   `

Formatting broke.  For anyone looking for greater clarity 

```
 - (void) webView:(WKWebView *)webView didReceiveAuthenticationChallenge:(NSURLAuthenticationChallenge *)challenge completionHandler:(void (^)(NSURLSessionAuthChallengeDisposition disposition, NSURLCredential * _Nullable))completionHandler {
   NSURLCredential * credential = [[NSURLCredential alloc] initWithTrust:[challenge protectionSpace].serverTrust];
   completionHandler(NSURLSessionAuthChallengeUseCredential, credential);
}
```

It needs to be added to the [RNCWebView.m file](https://github.com/react-native-webview/react-native-webview/blob/v11.23.1/apple/RNCWebView.m#L946) but line 946 Xcode will say its duplicate so comment 946-989.  I did this change and info.plist change to get it work!


In version 12.0.2 looks like [it got moved](https://github.com/react-native-webview/react-native-webview/blob/v12.0.2/apple/RNCWebViewImpl.m#L964) lines 964-1007.  I'm not sure if its the same update but if I end up trying I will edit this message.

**Comment by triztian** [comment]
I just ran into this issue. On production you'd try to avoid resorting to this but our company's QA and Dev environments make use of self-signed certificates some changes _have_ to be tested in those environments and sometimes the certificate checks need to be disabled.

I think this should still be a valid issue.

**Comment by eswarant** [comment]
Can anyone help me to bypass ssl error? I am using expo cli not native cli.

**Comment by kloshar4o** [comment]
+
