### ISSUE TITLE
Cannot access href of <a> tag [ANDROID]

### ISSUE THREAD

**Issue by Shashank2406** [react-native-community/react-native-webview#992]
react-native: 0.59.5
react-native-web-view: ^7.4.3

I cannot access href prop of anchor tag in HTML, the target seems to empty every time. This is happening only on android 
`{"href":"about:blank#1","ancestorOrigins":{},"origin":"null","protocol":"about:","host":"","hostname":"","port":"","pathname":"blank","search":"","hash":"#1"} `

It occurs when href is as follows 
`<a href="/test/url" class="site-btn">Test</a>`

Works fine if I have complete URL in the href prop
`<a href="https://www.google.com" class="site-btn">Test</a>`

None of the prop callback provides the href, it is always "about:blank" and URL is blank

**Comment by pkf1994** [comment]
got same issue
