### ISSUE TITLE
android can't work load error -2

### ISSUE THREAD

**Issue by tianweicc** [react-native-community/react-native-webview#995]
load error -2

**Environment:**
 - OS: android
 - OS version: android
 - react-native version: 0.59
 - react-native-webview version: 7.4.3

**Comment by a0985944005** [comment]
android/gradle.properties and adding 2 lines:

android.useAndroidX=true
android.enableJetifier=true

**Comment by a0985944005** [comment]
android/gradle.properties and adding 2 lines:

android.useAndroidX=true
android.enableJetifier=true
