### ISSUE TITLE
First time load too slow

### ISSUE THREAD

**Issue by nakinthorn** [react-native-community/react-native-webview#996]
Everytime when i clear app and launch again
it very very slow load.
why it happen ?

and how to make it faster like open in browser
everytime when open in browser it too faster and instance time loads
but when open in webview it take too long time load all the time

**Comment by nakinthorn** [comment]
hello anybody here ?

**Comment by Liqiankun** [comment]
@nakinthorn How did you solve it?

**Comment by mi-zona** [comment]
+1

**Comment by Liqiankun** [comment]
```js
 <WebView cacheEnabled={false} />
``` 
This works for me.

**Comment by haduy97** [comment]
How did you guys solve it ??

**Comment by Liqiankun** [comment]
@haduy97 set cacheEnabled false solved my problem.

**Comment by haduy97** [comment]
> @haduy97 set cacheEnabled false solved my problem.

thank you for your replied, but i thought that if we turn on cache the webview will working faster than using network for somehow. Could you explain me more why cacheEnabled false will work faster please ?

**Comment by Liqiankun** [comment]
I just know the way it is. But I don't know why the way it is. Sorry. ^^

**Comment by GobindaSaha** [comment]
> ```js
>  <WebView cacheEnabled={false} />
> ```
> 
> This works for me.

How? I mean cacheEnable should make it fast to load.

**Comment by scchess** [comment]
cacheEnabled to false didn't work on me.

**Comment by fungmo** [comment]
cacheEnabled to false didn't work on me.

**Comment by olive49** [comment]
cacheEnabled to false didn't work on me.

**Comment by jordan-tpz** [comment]
Hi, any solution ?
