### ISSUE TITLE
Webview has been removed React Native

### ISSUE THREAD

**Issue by HariMohan-eng** [react-native-community/react-native-webview#997]
I am using react-native but now i have updated my react-native version. When i run my project in iOS, I am getting web-view revoked error. I have searched more but did't get any working solution till now, please update your library or give me a suggestion how can i solve this error. please do it on priority basis ASAP.

**Comment by HariMohan-eng** [comment]
please fix on urgent basis.

**Comment by andreipfeiffer** [comment]
@HariMohan-eng please consider the following:

* you didn't mention what React Native version did you use before;
* you didn't mention what React Native version did you update to;
* please read the Change List before you upgrade to a new version, especially the Breaking Changes section;

This repository contains the `WebView` package that was extracted from React Native core, and maintained separately by the community.

Please see below how to install and use it:
https://github.com/react-native-community/react-native-webview/blob/master/docs/Getting-Started.md

**Comment by HariMohan-eng** [comment]
Hi,
Thanks for connect with me.
Previously We used  "react-native": "^0.59.6". Due to some limitations in older version we have upgraded to  "react-native": "0.61.4" (on which we facing the same error which i have mentioned earlier- Web view has been removed from react native)

How we can remove this error, Please let me know ASAP.

**Comment by andreipfeiffer** [comment]
@HariMohan-eng I just pointed you to the Getting Started guide for the `react-native-webview`.
As you said, the `WebView` component was removed from `React Native` core, so you have to install it separately.

Here's how:
https://github.com/react-native-community/react-native-webview/blob/master/docs/Getting-Started.md

**Comment by HariMohan-eng** [comment]
Hi,
We are importing webview from react-native-webview rather from react-native even we are getting the same error that i have mentioned before. 
Please find my attached screenshot of simulator.

![Simulator Screen Shot - iPhone 11 - 2019-11-14 at 11 16 50](https://user-images.githubusercontent.com/56437951/68829957-5f4bf880-06d0-11ea-8109-61298421e75d.png)

**Comment by andreipfeiffer** [comment]
@HariMohan-eng that piece of code is included in `react-native`'s WebView: https://github.com/facebook/react-native/blob/master/index.js#L503

Are you importing your `WebView` component like this?

```
import { WebView } from 'react-native-webview'
```

Also, could you reproduce this issue in an empty RN project?

**Comment by arstropica** [comment]
Also experiencing the same issue on v. 0.60.5.  I think the culprit is [src/WebView.tsx](https://github.com/react-native-community/react-native-webview/blob/5ddd6c6fc277b348d1e6725c76f98ab55ea282c1/src/WebView.tsx#L2).  It generates a js lib file with the legacy import statement from react-native.

**Comment by andreipfeiffer** [comment]
@Titozzz do you have any idea why there's an import from `react-native` of the old `WebView` component?

**Comment by pokemon145** [comment]
//first need to install this npm 
 npm install --save react-native-webview
//then import 
import { WebView } from 'react-native-webview'

**Comment by ansalmishra10** [comment]
i am still getting this error please someone tell me any solution.

**Comment by arstropica** [comment]
@ansalmishra10 Make sure you search your project for the webview import statement that is causing the error. For me, it turned out that the error was being caused by [react-native-webview-bridge](https://github.com/alinz/react-native-webview-bridge) and not react-native-webview. I found an import statement for the old native webview component and created a pull request that has now been [merged into the latest version](https://github.com/alinz/react-native-webview-bridge/commit/575b6bd679ac1deecddad56e01592c8cfa08a47e).

**Comment by dogeri28** [comment]
> Also experiencing the same issue on v. 0.60.5. I think the culprit is [src/WebView.tsx](https://github.com/react-native-community/react-native-webview/blob/5ddd6c6fc277b348d1e6725c76f98ab55ea282c1/src/WebView.tsx#L2). It generates a js lib file with the legacy import statement from react-native.

I believe this is the issue, but i am new to react native. As i dont know where i can manually change the import statement for [..src/WebView.tsx]
